### ISSUE TITLE
making my other suggestions readable.

### ISSUE THREAD

**Issue by wordpass1** [studio-minus/ppg-bugs-and-requests#1003]
after some thinking, I have just realised that both of my suggestions do not explain how it would function in any practical way. so im fixing it

**Feature description**
bullet force thing: when bullets go past an object/stuff like sand and dirt. they kick it forward. this can be seen in objects already (to a limited extent.). but it happens to the ground aswell irl. it would be a cool detail if you could see some black dust kick up when bullets are close to the floor.

the "cooler" activation signal: when the cooler activation sinal is destroyed, it turns off anything connected to it, which the regular activation sinal does not.. thats it.

**Feature purpose**
bullet force thing: it would be realistic, and add to the lore. suggesting that the chambers arent as clean/flat as we thought.

the "cooler" activation signal: would probably make mechs cooler, adding weak spots that can disable weapons/other parts.

**Additional context**
It could be argued that the floor in the chambers is flat. and thats fine, I would still like to see bullets knock objects over even if they miss, and yeah idk what the cooler activation signal was. im sorry for wasting your time zooi. but i feel obligated to include it.

**Comment by mestiez** [comment]
You can edit your existing issues.
