### ISSUE TITLE
Fix map icons

### ISSUE THREAD

**Issue by 5hart** [studio-minus/ppg-bugs-and-requests#1004]
**Feature description**
The map icons in the "choose map" screen all have a small black outline around them, but some of the icons have outlines that don't fully surround the icon. Slanted, Default, Snow, Humongous, Substructure, and sea all seem to have this as far as I can notice.

![image](https://user-images.githubusercontent.com/46716733/160330148-4d3ddb3d-cf34-4c29-a86e-68150f4565f8.png)

![image](https://user-images.githubusercontent.com/46716733/160330162-9339814e-f661-4be4-b414-d4d52d2667e4.png)

I added pictures of Default and Slanted so you can hopefully see what I'm talking about. Somebody please let me know if you can see what I'm talking about as well.

**Feature purpose**
It makes the pictures all look poor quality in my opinion, since they are pretty noticeable. I'm not suggesting an icon overhaul (although that's not entirely out of the question), but if you can, I think these should be fixed.

**Additional context**
I already posted an issue about the proportions of the screen a while back as well, so I hope I'm not being a bother about it 😅.

**Comment by DindinYT37** [comment]
That depends on screen resolution as the border is likely just a black square behind the map icon which is exactly +1 pixel on each side, and sometimes, when interpolating from the original map icon to fit whatever resolution you have - it can leave out one or two lines of pixels, which results in this.

**Comment by mestiez** [comment]
I just removed the outline for now.
