### ISSUE TITLE
Wheels gets replaced with Wooden Wheels

### ISSUE THREAD

**Issue by X3Buster** [studio-minus/ppg-bugs-and-requests#1005]
**Describe the bug**
When spawning in a saved creation with the normal wheels, the wheels get replaced with wooden wheels

**Clearly describe how to reproduce the bug**
Spawn in any creation containing normal wheels in the latest 1.23 release

**Mod list**
No Mods loaded

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: Release 1.23
 - GPU:NVIDIA GeForce GTX 1050 Ti
 - CPU:AMD Ryzen 7

**Additional notes**
![People Playground 2022_03_28 16_27_13](https://user-images.githubusercontent.com/102367138/160420460-487ae6e2-6a7a-4f9b-a76b-163d7a8926da.png)

**Comment by mestiez** [comment]
fixings
