### ISSUE TITLE
Make it easier to configure different sentry types

### ISSUE THREAD

**Issue by ahlad69** [studio-minus/ppg-bugs-and-requests#1007]
**Feature description**
As the title so blatantly says, it would be really nice to make it easier to have turrets that don't use FirearmBehaviour

**Feature purpose**
very useful for modders

**Additional context**
I attempted to create flame and roscket turrets but they _really_ dont like to be anything but firearms

love, ahlad :)
![image](https://user-images.githubusercontent.com/83554136/160480362-b6557eba-95f5-4d7e-87bf-831881d07bbd.png)

**Comment by wordpass1** [comment]
Thought this was part of the game at first! The pixel art is amazing, Hope zooi assists you!

**Comment by mestiez** [comment]
I never saw this but `AutomaticSentryController` was created for this purpose. It has no knowledge of firearms or anything, it just detects limbs and emits events. [There is no tutorial or anything but this is relatively clear](https://www.studiominus.nl/ppg-modding/internalReference/AutomaticSentryController.html)

**Comment by mestiez** [comment]
Clarification: this has been part of the game for a long time now

**Comment by DindinYT37** [comment]
...and nobody has ever known! Now let's watch the influx of new turret mods.
