### ISSUE TITLE
Blood is Still Lost When the Weapon is Still In

### ISSUE THREAD

**Issue by Electrooooo** [studio-minus/ppg-bugs-and-requests#1010]
Bug Description
When stabbing someone with a knife (I have not yet tested this with other weapons), even though the visual effect for bleeding does not show when the knife is still in, they still lose blood according to the Inspect menu.

How to reproduce the bug
-Stab someone
-View Inspect Menu and it will show the person losing blood.

Additional notes
first time really writing a bug report so please contact me if there is anymore information I should provide that is not in the exported game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8366235/exported.game.debug.info.md)

**Comment by fhgb54643689** [comment]
thats meant to happen its just a little less blood loss

**Comment by mestiez** [comment]
Yes bleeding still happens but not as quickly and not visually.
