### ISSUE TITLE
Liquid centrifuge becomes airborne when turned on

### ISSUE THREAD

**Issue by basedkit** [studio-minus/ppg-bugs-and-requests#1013]
**Describe the bug**
liquid centrifuge becomes airborne when activated 

**Clearly describe how to reproduce the bug**
spawn in the liquid centrifuge and activate it.   

**Mod list**
  No mods

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.23
 - GPU: NVIDIA Geforce GTX 1660 Ti 
 - CPU: AMD Ryzen 7 4800H with Radeon Graphics

**Additional notes**
idk if this was a intentional feature or not so please let me know if it was

**Comment by mestiez** [comment]
did you accidentally make it weightless?

**Comment by basedkit** [comment]
> did you accidentally make it weightless?

i have a video of it so is there anywhere you would like me to send it?

**Comment by 5hart** [comment]
I don't have this problem, I did try making it weightless and it starts to go crazy, but that's not what the post is suggesting. Only thing I noticed that was weird was that if you let it fall then it wiggles a bit while falling, but I'm assuming that's just from the spinning in the center.

**Comment by basedkit** [comment]
> I don't have this problem, I did try making it weightless and it starts to go crazy, but that's not what the post is suggesting. Only thing I noticed that was weird was that if you let it fall then it wiggles a bit while falling, but I'm assuming that's just from the spinning in the center.

weird, i have a video of it going nuts so idk why its being odd for me

**Comment by mestiez** [comment]
cant reproduce
