### ISSUE TITLE
Wind

### ISSUE THREAD

**Issue by PopsTheGuy** [studio-minus/ppg-bugs-and-requests#1014]
**Feature description**
Wind, It can blow stuff away and yeah basically that.

**Feature purpose**
I thought it would be cool if there was wind in the game y'know.

**Additional context**
None here.

**Comment by wordpass1** [comment]
I know I'm not really one for accuracy to the lore with suggestions, But how would wind be created in the chambers? Maybe wind should exist in its own map? Or the fan should create it. (Despite kind of doing that.)

**Comment by DindinYT37** [comment]
> I know I'm not really one for accuracy to the lore with suggestions, But how would wind be created in the chambers? Maybe wind should exist in its own map? Or the fan should create it. (Despite kind of doing that.)

Lore was never confirmed in the first place.
