### ISSUE TITLE
The Alarm Lights gets brighter when you clear everything in the uncharted territory map

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#1016]
**Describe the bug**
Since the addition of reseting the whole map when you clear everything, The alarm lights on the uncharted territory map doesn't get reseted and more alrm lights gets added making it brighter so the map gets brighter everytime you clear everything.

**Clearly describe how to reproduce the bug**
1. Go to the uncharted territory map
2. Kepp clearing everything and you can notice it

**Mod list**
I don't think mods is the cause

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.23
 - GPU: no need
 - CPU: no need

**Comment by 5hart** [comment]
Just tried it and it does happen

**Comment by henqqk** [comment]
what is uncharted territory?

**Comment by mestiez** [comment]
fixed
