### ISSUE TITLE
Bazooka Back Blast

### ISSUE THREAD

**Issue by sokadu** [studio-minus/ppg-bugs-and-requests#1019]
Add a backblast force for the bazooka.

This is for realism and fun

In real life bazookas and most forms of RPG's have a blast of gases out of the back that cause lots of damage. there is already a cloud of smoke so just adding a AOE blast in that area would be perfect.

**Comment by ppgplayer** [comment]
brooo i was wondering why there was no backblast turns out it's just not in the game
