### ISSUE TITLE
Lamps

### ISSUE THREAD

**Issue by 2ee4jnufew** [studio-minus/ppg-bugs-and-requests#1028]
**Feature description**
There are so many cool lamps in the game, but they are not available to us.

**Feature purpose**
It would be nice to add these lamps. As for me, they are useful everywhere.

**Additional context**
![20220329122519_1](https://user-images.githubusercontent.com/69415642/160692759-0563188a-20ba-47bf-97fe-e35449a41ea4.jpg)
![24](https://user-images.githubusercontent.com/69415642/160692907-fe0a8495-0e81-4192-bcce-d2d88f0b34e3.jpg)
![20220317154236_1](https://user-images.githubusercontent.com/69415642/160692943-50d0b192-397c-47bf-902c-7489070857ca.jpg)

**Comment by TheBeeThat** [comment]
these are literally in the base game

**Comment by TheBeeThat** [comment]
they are called floodlights
![image](https://user-images.githubusercontent.com/96020070/161401105-66952838-f4e6-4279-966d-e30e25a7a5d3.png)
for the love of god please fix your eyes

**Comment by DindinYT37** [comment]
> they are called floodlights ![image](https://user-images.githubusercontent.com/96020070/161401105-66952838-f4e6-4279-966d-e30e25a7a5d3.png) for the love of god please fix your eyes

We don't have the modern ones featured in the third picture though, Mr. Moderator.

**Comment by 2ee4jnufew** [comment]
> they are called floodlights ![image](https://user-images.githubusercontent.com/96020070/161401105-66952838-f4e6-4279-966d-e30e25a7a5d3.png) for the love of god please fix your eyes

If you are talking about the fact that this spotlight is, then I'm talking about everything else. In many buildings, they will not be superfluous. Especially the third one.

**Comment by 2ee4jnufew** [comment]
The lamp from the first photo is much better than the one we have. The second one is also useful, for example, if there is a very long corridor

**Comment by ahlad69** [comment]
> > they are called floodlights ![image](https://user-images.githubusercontent.com/96020070/161401105-66952838-f4e6-4279-966d-e30e25a7a5d3.png) for the love of god please fix your eyes
> 
> We don't have the modern ones featured in the third picture though, Mr. Moderator.

_says the fuckin minimod_

**Comment by DindinYT37** [comment]
> > > they are called floodlights ![image](https://user-images.githubusercontent.com/96020070/161401105-66952838-f4e6-4279-966d-e30e25a7a5d3.png) for the love of god please fix your eyes
> > 
> > We don't have the modern ones featured in the third picture though, Mr. Moderator.
> 
> _says the fuckin minimod_

Bro you've been replying to every reply on mine and tell me I don't have a life, what's your problem??

**Comment by mestiez** [comment]
Closed because none of you can behave
