### ISSUE TITLE
Car, that freezes in the air

### ISSUE THREAD

**Issue by henqqk** [studio-minus/ppg-bugs-and-requests#1029]
If you take the rear door on the default car, then freeze the car, the door will stuck and car wont be able to return to its normal position (how it works is shown on the video right here -> 
               (https://drive.google.com/file/d/1t6hhe8yRvubwd7ArCOtZLG05ybiakD1b/view?usp=sharing)

Steps to reproduce the problem.
1. Detach rear door on the car and throw it 20 meters far from the car
2. Freeze car
3. Make sure car tilted by -45 degrees
4. Copy that car
5. Paste it 

Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

Extra Lightsabers
COD: MW2
Special Weapons and Tactics mod
A Crap Ton of Damage
Army Mod
MaTT's Car Collection
Animated Weapons+
Blocksify's Marvel Bundle
Mercedes Maybach
AMG G63 MOD
Nuclear Playground
Blocksify's Spies & Hitmen Mod
DABABY MOD
More Weapons Mod
COMBAT SPEC-OPS
COMBAT SPEC-OPS MAP
ROPE TOOL
POLICE+
Vanilla Weapons+ 2
Bombs Expanded
Military+
Per Pixel Destruction
Advanced Damage
Active Humans
Weapons Mod

 - Windows 10
 - 1.23:
 - GTX 1060 3GB:
 - Xeon E3-1230 V2:

**Comment by pjstarr12** [comment]
the game thinks the joint is still fixed when pasting

**Comment by mestiez** [comment]
fixed
