### ISSUE TITLE
Spelling error on some items?

### ISSUE THREAD

**Issue by 5hart** [studio-minus/ppg-bugs-and-requests#1031]
**Feature description**
Not sure if this would really be a feature request, but I don't think it's a bug either. Basically, I just noticed that on the laser pointer, the description is "A colorable laser pointer", and on the LED bulb, the description contains "Colourable LED bulb." This is the only place that I noticed this, but it might be on other things as well.

**Feature purpose**
It's nothing special really, but I just happened to notice it while playing, that the two are spelled differently.

**Additional context**
I'm on the 1.23 release if that's important.

**Comment by royalealbert27** [comment]
They have the same meaning

**Comment by 5hart** [comment]
I know, but you know how in America, we spell it "colorable", meanwhile in europe and most other countries, it's spelled "coloured". Just pointing out a spelling error.

**Comment by 5hart** [comment]
> They have the same meaning

I know, but you know how in America, we spell it "colorable", meanwhile in europe and most other countries, it's spelled "coloured". Just pointing out a spelling error.

**Comment by mestiez** [comment]
I am inconsistent because in code it's usually `color`, but in text it's usually "colour".

**Comment by 5hart** [comment]
> I am inconsistent because in code it's usually `color`, but in text it's usually "colour".

I see, it's not a big deal or anything however, but I do think you should fix it to whatever you spell it like.

**Comment by mestiez** [comment]
I did fix it :)
