### ISSUE TITLE
Syring Liquid In Flasks

### ISSUE THREAD

**Issue by GodPhase777** [studio-minus/ppg-bugs-and-requests#1034]
**Feature description**
Allow stabbing syringes into flasks, blood tanks, liquidentifiers and centrifuges to transfer blood or syringe liquid.

**Feature purpose**
Make vats of healing liquid or strength liquid to hook multiple people up to.

**Additional context**
It would be more useful with some way to hook people up to tanks easier.

**Comment by DindinYT37** [comment]
This makes no sense?

**Comment by GodPhase777** [comment]
In what way?  you can make vats of syringe liquid to spray or inject into multiple people at once, with some easier way to hook them up to a liquid tank it would be more useful.

**Comment by DindinYT37** [comment]
> In what way? you can make vats of syringe liquid to spray or inject into multiple people at once, with some easier way to hook them up to a liquid tank it would be more useful. Not much use other than being able to inject multiple people at once though.

You know you can shoot syringes to make them spray and you can just use a blood vessel wire to connect them to multiple people at once, and an injectable flask is already found in a mod and not very useful (since we have blood vessel wires) in the first place.

**Comment by GodPhase777** [comment]
> > In what way? you can make vats of syringe liquid to spray or inject into multiple people at once, with some easier way to hook them up to a liquid tank it would be more useful. Not much use other than being able to inject multiple people at once though.
> 
> You know you can shoot syringes to make them spray and you can just use a blood vessel wire to connect them to multiple people at once, and an injectable flask is already found in a mod and not very useful (since we have blood vessel wires) in the first place.

Didn't know that, i guess i am still newish and dont know every little detail yet. Thanks for clearing that up. Should i close this as its completely useless with that info in mind? I don't know if im allowed to close this issue myself or not.

**Comment by DindinYT37** [comment]
> > > In what way? you can make vats of syringe liquid to spray or inject into multiple people at once, with some easier way to hook them up to a liquid tank it would be more useful. Not much use other than being able to inject multiple people at once though.
> > 
> > 
> > You know you can shoot syringes to make them spray and you can just use a blood vessel wire to connect them to multiple people at once, and an injectable flask is already found in a mod and not very useful (since we have blood vessel wires) in the first place.
> 
> Didn't know that, i guess i am still newish and dont know every little detail yet. Thanks for clearing that up. Should i close this as its completely useless with that info in mind? I don't know if im allowed to close this issue myself or not.

You opened it, you can close it if you want to. If you wanna close this since you think it'd be useless, close it, if not, then don't.
