### ISSUE TITLE
Ragdoll animation in context menu

### ISSUE THREAD

**Issue by StealthDrifter** [studio-minus/ppg-bugs-and-requests#1037]
**Feature description**
An animation like walking and flat pose but instead they're just forever a ragdoll until animations are cleared.

**Feature purpose**
Will be very useful for stuff like throwing people off cliffs, attaching people to chairs, and just generally would be a great addition.

**Additional context**
pretty much a repost of #628 but I would like to add my opinion that this would be a very good feature to add.

**Comment by DindinYT37** [comment]
You know, opinions can be shown with comments.

**Comment by Drogo-man** [comment]
have you heard of knocking ppl unconscious?

**Comment by DindinYT37** [comment]
Update: I recommend [Quick Right Click options](https://steamcommunity.com/sharedfiles/filedetails/?id=2516131949), since it also has a "Knock out" and "Wake up" feature.
