### ISSUE TITLE
Friction Burn

### ISSUE THREAD

**Issue by cl0udsz** [studio-minus/ppg-bugs-and-requests#1040]
**Feature description**
Friction causes heat, i.e if something rubs against the ground at a very high speed it heats up. The harder it's pressed against the ground and the faster it's travelling, the more heat is created. Wouldn't actually set anything on fire (unless it's highly flammable) but would just heat it up or, in the case of a human, cause burns on the skin - these burns could be the same as the damage done to a person after they have been set on fire (charred and blackened flesh).

**Feature purpose**
Thought of this when my person was ejected at a high speed from a 50s F1 car and skidded against the ground without taking any harm from the friction or lack thereof. Thought it would be very cool to have this as a feature

**Comment by Drogo-man** [comment]
Already in the game.

**Comment by cl0udsz** [comment]
> Already in the game.

If it's already in the game, could it be updated? I think it would be cool for friction burn to occur in the scenario I mentioned above.

**Comment by DindinYT37** [comment]
> > Already in the game.
> 
> If it's already in the game, could it be updated? I think it would be cool for friction burn to occur in the scenario I mentioned above.

Friction doesn't always happen and I only ever saw it happen at insanely high speeds and pressure.
