### ISSUE TITLE
New mechanical activation options and different instruments to use

### ISSUE THREAD

**Issue by Rkivebyday** [studio-minus/ppg-bugs-and-requests#1041]
**Feature description**
Basically the new mechanical activation options would be spawnables same with the instruments
**Feature purpose**
The purpose being for more advanced mechanical contraptions and or music box creations
**Additional context**
Hmm idk jus comment down below if ya need me to further explain some stuff

**Comment by DindinYT37** [comment]
We have like no idea what you mean.

**Comment by Rkivebyday** [comment]
Long story short essentially different variations of timed gates that can either activate one twice three times etc and as for instruments I'm thinking of a different variation of the bell or some configurable item like the bells for music

**Comment by DindinYT37** [comment]
The Instruments were already requested before, and multi-requesting is not allowed on here (I don't make the rules). About the timed gate things, it might be accepted, but can't you just make that yourself in vanilla?

**Comment by Rkivebyday** [comment]
Yeah you could do the timed gates in vanilla but if you want some more complex functioning creations that are strict with activation inputs the different variations of timed gates/or logic gates would be nice

**Comment by DindinYT37** [comment]
> Yeah you could do the timed gates in vanilla but if you want some more complex functioning creations that are strict with activation inputs the different variations of timed gates/or logic gates would be nice

I guess.

**Comment by Rkivebyday** [comment]
Any who I digress
