### ISSUE TITLE
Breaking the hip sets limb health to 0

### ISSUE THREAD

**Issue by SeVeredC0nnection** [studio-minus/ppg-bugs-and-requests#1043]
When breaking the hip bone (or bone that connects the legs to the body) of a human or Android that limb immediately loses all health unlike any other limb below the chest.

Just break the hip bone on a human or Android.

**Comment by SeVeredC0nnection** [comment]
@mestiez any update on this?

**Comment by DindinYT37** [comment]
This is probably because of the "is lethal to break" property.
