### ISSUE TITLE
Gas and gunpowder in PP

### ISSUE THREAD

**Issue by HanSlukas** [studio-minus/ppg-bugs-and-requests#1047]
I would like gasses, maybe some explosive, som poisonous etc, they would be in the menu, and when you hold E gas spawns (Goes up depending on gas). And gun powder, it would be spawned in quantity by how long you hold E (Same with gas), if gunpowder gets hot it explodes, same with gasses, and if it gets shot it also explodes, of course depending on gas type.

The gas I would like because I think it could be fun to mess around with, imagine filling a giant building with helium and the shooting it then all of it blows up! Even better, imagine making your own Sun with a gas generator of some kind! And gunpowder would be nice for making cannons, guns and such.

No additional context.

**Comment by Drogo-man** [comment]
Ugh

**Comment by DindinYT37** [comment]
I'm pretty sure both of this was requested several times before...

**Comment by mestiez** [comment]
Duplicate of #423

**Comment by fhgb54643689** [comment]
you may want to see a doctor about that
