### ISSUE TITLE
i cant delete items

### ISSUE THREAD

**Issue by roximb** [studio-minus/ppg-bugs-and-requests#1052]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
i habve to many to all them write

**System info (please complete the following information)**
 - Operating system: 
 - Game version:lastest
 - GPU:builed in
 - CPU:AMD Ryzen 5 5600G with Radeon Graphics

**Additional notes**

**Comment by mestiez** [comment]
at least put a little effort in, christ
