### ISSUE TITLE
Bug with laser and fixed cable

### ISSUE THREAD

**Issue by Starwatcher01** [studio-minus/ppg-bugs-and-requests#1054]
**Describe the bug**
If you connect any object (e.g. the big metal beam) with the fixed cable to the background and shoot with a powerful laser at the big metal beam the fixed cable disappears.

**Clearly describe how to reproduce the bug**
1. Connect a laser pointer to an industrial generator with a wire
2. Make them indestructable and freeze them
3. Take any object (for example the big metal beam) and connect it with the fixed cable to the background
4. Activate the laser and the industrial generator
5. Wait until the laser causes explosions

The fixed cable should disappear after that

**Mod list**
1. Simple Syringes Mod (deactivated)
2. Wild Medieval (deactivated)
3. V+ Field gun (deactivated)

**System info**
 - Operating system: Windows 10
 - Game version: 1.23 (March 28 2022)
 - GPU: NVIDIA GeForce RTX 3060 
 - CPU: AMD Ryzen 7 3700X 8-Core Processor

**Additional notes**
This bug occours also at other connections.

Sorry for my bad english, I´m from germany. I tried my best.

**Comment by DindinYT37** [comment]
Pretty sure that's a feature.

**Comment by mestiez** [comment]
Not a bug. The laser just cuts every wire off.
