### ISSUE TITLE
Multiplayer idea 

### ISSUE THREAD

**Issue by Azertu1** [studio-minus/ppg-bugs-and-requests#1055]
I think it would be possible to add a multiplayer mode in which we see the cursor of the other player with his nickname above, it would be very fun to play and create things with his friends. Since the game does not require a very good pc to run it, we could host the servers directly on our pc (and the player who joins us just enters the ip address). It would be really great of you to create such a mode.
I hope my explanation was understandable, could you let me know if you plan to add multiplayer please.

**Comment by fawdot** [comment]
zooi has mentioned that he won't ever make multiplayer

**Comment by DindinYT37** [comment]
Please use the template, and as @fawdot said zooi has already said before that it will never be added. You can count on some multiplayer mods in the works though I guess.
