### ISSUE TITLE
Some lights on Substructure have an incorrect collision shape

### ISSUE THREAD

**Issue by 2ee4jnufew** [studio-minus/ppg-bugs-and-requests#1056]
**Describe the bug**
Collision error

**Clearly describe how to reproduce the bug**
Collision only in the center. And then there she is crooked

**Mod list**
None.

**System info**
 - Operating system: Windows 7
 - Game version: 1.23.6
 - GPU: builed in
 - CPU: GeForce GT 650M

**Additional notes**

https://user-images.githubusercontent.com/69415642/161449119-08afe67c-adab-4ea2-bdcf-ed2d64870409.mp4

**Comment by DindinYT37** [comment]
The moment when zooi just retextures the LED and forgets to make a new collider for it.

**Comment by 2ee4jnufew** [comment]
> The moment when zooi just retextures the LED and forgets to make a new collider for it

He can make a collision, then a stroke, and then add it to us

**Comment by DindinYT37** [comment]
> > The moment when zooi just retextures the LED and forgets to make a new collider for it
> 
> He can make a collision, then a stroke, and then add it to us

What?

**Comment by 2ee4jnufew** [comment]
> > > The moment when zooi just retextures the LED and forgets to make a new collider for it
> > 
> > 
> > He can make a collision, then a stroke, and then add it to us
> 
> What?

Well, it can update the collision. And then add the lamp.

**Comment by DindinYT37** [comment]
> > > > The moment when zooi just retextures the LED and forgets to make a new collider for it
> > > 
> > > 
> > > He can make a collision, then a stroke, and then add it to us
> > 
> > 
> > What?
> 
> Well, it can update the collision. And then add the lamp.

What has adding the lamp to do with this bug report...

**Comment by 2ee4jnufew** [comment]
> 
What? Bug about collision error

**Comment by 2ee4jnufew** [comment]
Personally, it seems to me that with a normal collision it will be better.

**Comment by mestiez** [comment]
Fixed
