### ISSUE TITLE
manual layer priority options

### ISSUE THREAD

**Issue by Koshi32** [studio-minus/ppg-bugs-and-requests#1057]
**Feature description**
A way to manually change layer priority of objects, such as a 'layer up/layer down' button in the context menu or something simialar.

**Feature purpose**
helps with making things look nice when creating, probably only visual

**Additional context**
layer priority seems to change at will, such as items popping over eachother when deleting unrelated things or between saves. 
sometimes layer priority is important when trying to make things look nice, and it can be a hassle to try and sort things out as-is.

**Comment by ATPGaming** [comment]
you may want to close this since it was added with the beta
