### ISSUE TITLE
Spile for human

### ISSUE THREAD

**Issue by YeBaited** [studio-minus/ppg-bugs-and-requests#1058]
**Feature description**
An item, It looks like a straw that you can puncture through a human, and blood will come out at the end of it.

**Feature purpose**
Milking human and getting their blood. Or like a mosquito so they can drink blood through spile.

**Additional context**

![example](https://user-images.githubusercontent.com/50571477/161517520-59c0586d-789b-40ec-b1a5-ba3f577dd1d1.jpg)

**Comment by DindinYT37** [comment]
Dunno man, sounds a bit weird for ppg

**Comment by TheBeeThat** [comment]
how does that sound weird for ppg?

**Comment by UniDuki** [comment]
You can make a simple spile using syringes already
![image](https://user-images.githubusercontent.com/69184577/161559590-f4297fa0-9ec5-4e4c-9eb4-0928d11e0038.png)

**Comment by DindinYT37** [comment]
> how does that sound weird for ppg?

Doesn't sound like something PPG should/would have.

**Comment by ppgplayer** [comment]
> > how does that sound weird for ppg?
> 
> Doesn't sound like something PPG should/would have.

That is not up for you to decide. We literally have a 4 legged, glue smelling monster in the game and THIS is too much?

**Comment by ppgplayer** [comment]
> You can make a simple spile using syringes already ![image](https://user-images.githubusercontent.com/69184577/161559590-f4297fa0-9ec5-4e4c-9eb4-0928d11e0038.png)

Well, you can make a statue of a dog but that doesn't mean you have a dog.

**Comment by YeBaited** [comment]
Was kinda thinking of something like this

![image](https://user-images.githubusercontent.com/50571477/161727287-99b76fbc-e9b0-44f1-9bfc-2b2fdc167492.png)

**Comment by DindinYT37** [comment]
> > > how does that sound weird for ppg?
> > 
> > 
> > Doesn't sound like something PPG should/would have.
> 
> That is not up for you to decide. We literally have a 4 legged, glue smelling monster in the game and THIS is too much?

I never said so, and I didn't say it's too much - I said it doesn't feel like something that would be in ppg. Also it's quite bold of you to assume that I would consider myself to be the decider of that.

**Comment by mestiez** [comment]
What is the difference between this and a syringe + outlet
