### ISSUE TITLE
Change the base material, density, and bullet resistance of resizable housing.

### ISSUE THREAD

**Issue by abritishoutcast** [studio-minus/ppg-bugs-and-requests#1060]
It would be an addition to normal resizable housing, and through the context menu, you could choose its base material, how much it weighs relative to its size (Density) and how good it is as stopping bullets. I'd rather have bullet resistance be directly proportional to it's resistance to blocking gunshots, but I'm not sure all people would.

This would be so you could have a universal building material, and so you didn't have to create another layer of utility parts under the resizable housing like bulletproof sheets.

**Comment by DindinYT37** [comment]
Similar to #910

**Comment by Skiiitles** [comment]
> Similar to #910

You're right! How could someone have the audacity and not have read 20 pages of suggestions! People these days smh :(

**Comment by mestiez** [comment]
> > Similar to #910
> 
> You're right! How could someone have the audacity and not have read 20 pages of suggestions! People these days smh :(

You can search for keywords.
