### ISSUE TITLE
Map loaded entities not obeying audio sliders. 

### ISSUE THREAD

**Issue by Balloon-Snake** [studio-minus/ppg-bugs-and-requests#1061]
I have noticed that on the new map and the map that is accessed via the Uncharted Territory portal, some of the map loaded objects are abnormally loud. Specifically, on the Substructure map, the spotlights, when collided with an object, produces a sound louder than anything else I have experienced in the game. Same with the radio in the Uncharted Territory map. It is so loud that it makes me jump if I do not do it on purpose. I have not experienced a problem with any other items.

1. Load into Substructure or the Uncharted Territory map.
2. Hit the wall mounted spotlights with an object.
3. If on the UT map, simply hit the radio, or throw it.

No mods. Only saved contraptions.

 - Operating system: Windows
 - Game version: 1.23.6
 - GPU: NVIDIA GeForce RTX 2060
 - CPU: Intel(R) Core(TM) i7-10700F CPU @ 2.90 GHz

Shooting/blowing these items up does not produce the effect, it seems only collisions produce it.

**Comment by DindinYT37** [comment]
Yes, finally someone is reporting this. I never found a vanilla way to reproduce this so I never reported it, but this changes with the Substructure map.

**Comment by mestiez** [comment]
oops

**Comment by mestiez** [comment]
fixed
