### ISSUE TITLE
Per-human options/syringes to completely disable organ failure (Brain damage, liver damage, etc)

### ISSUE THREAD

**Issue by googleooer** [studio-minus/ppg-bugs-and-requests#1063]
**Feature description**
It would either be a right click option or a syringe. When used on a human, it would completely disable brain/lung/etc damage for it.

**Feature purpose**
It would be really nice to have, especially when trying to make super-powered humans. It's kinda dumb how a human with super strength that can regenerate body tissue in a few seconds gets permanent brain damage as soon as it hits its head and keeps having seizures forever.

**Additional context**

**Comment by Drogo-man** [comment]
You should request this on the crapton of damage mod, that's where the organs are from.

**Comment by DindinYT37** [comment]
> You should request this on the crapton of damage mod page, that's where the organs are from.

They don't come from there, the vanilla game also has Organs - just not visible to us. And the "crapton of damage" mod is pretty buggy and ruins most superhumans, etc.

**Comment by Drogo-man** [comment]
> > You should request this on the crapton of damage mod page, that's where the organs are from.
> 
> They don't come from there, the vanilla game also has Organs - just not visible to us. And the "crapton of damage" mod is pretty buggy and ruins most superhumans, etc.

Crapton of damage is the one with the brain damage and the seizures. The vanilla game only has lungs and brain, that can't get seizures.

**Comment by DindinYT37** [comment]
> > > You should request this on the crapton of damage mod page, that's where the organs are from.
> > 
> > 
> > They don't come from there, the vanilla game also has Organs - just not visible to us. And the "crapton of damage" mod is pretty buggy and ruins most superhumans, etc.
> 
> Crapton of damage is the one with the brain damage and the seizures. The vanilla game only has lungs and brain, that can't get seizures.

I'm pretty sure there is some kind of seizure in the vanilla game too, anyway, since this is from a mod (apparently) - this whole issue is invalid.

**Comment by googleooer** [comment]
is it? i dont remember ever installing that mod

**Comment by googleooer** [comment]
Huh, I guess it is
