### ISSUE TITLE
Add recompile button always there

### ISSUE THREAD

**Issue by WhiteholeSteve** [studio-minus/ppg-bugs-and-requests#1072]
**Feature purpose*
Make it always there, so us modders don't have to reload ppg

**Comment by DindinYT37** [comment]
Please use the template, and this was already requested several times and rejected before.

**Comment by DindinYT37** [comment]
Duplicate of #694 and #589 - similar to #605.

**Comment by WhiteholeSteve** [comment]
oh okay
