### ISSUE TITLE
Android bug

### ISSUE THREAD

**Issue by BugMan33** [studio-minus/ppg-bugs-and-requests#1073]
**Describe the bug**

Android's upper arm is behind upper leg. 

**Clearly describe how to reproduce the bug**

Spawn android.

**Mod list**

Science Hazard Minus - Active
Time accelerator - Active

**System info**
 - Operating system: Windows 10 pro 64 bit
 - Game version: 1.23.6
 - GPU: Amd Radeon RX 5500M
 - CPU: Amd Ryzen 7 4800H

**Additional notes**

Bug.

![Android bug](https://user-images.githubusercontent.com/89192183/162484065-9bafa350-d35a-4508-bd00-65f3f55971b3.PNG)

**Comment by DindinYT37** [comment]
Are you sure that's his arm and not the other leg though?

**Comment by mestiez** [comment]
This has been fixed
