### ISSUE TITLE
speedometer

### ISSUE THREAD

**Issue by ifrost-source** [studio-minus/ppg-bugs-and-requests#1080]
**Feature description**
It would be a small object like a the thermometer, which could be put on any vehicle (or moving object) to show how fast that object is going.

**Additional context**
N/A

**Comment by ppgplayer** [comment]
I mean like, I could see this being useful for builds that need calculations. Like artillery or missiles to see how far they would go. I think this would be very useful.

**Comment by mestiez** [comment]
Duplicate of #662

**Comment by ifrost-source** [comment]
oh sorry, should I delete this 🙁?
