### ISSUE TITLE
invisible particle projector will show up on detail view

### ISSUE THREAD

**Issue by citizenthe** [studio-minus/ppg-bugs-and-requests#1081]
see invis particle projector lying around somewhere
![image](https://user-images.githubusercontent.com/96728876/162567237-a12ff9cf-de11-4962-81c1-914025c7cea7.png)
maybe something like this idk

**Comment by DindinYT37** [comment]
Use the template please, otherwise great feature request.

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/162577838-2eaa9588-c36f-4195-a1ba-6743575f4366.png)
