### ISSUE TITLE
Red eye

### ISSUE THREAD

**Issue by 2ee4jnufew** [studio-minus/ppg-bugs-and-requests#1084]
**Feature description**
When turning off the color, make a red eye for android. And when a little red in the light

**Feature purpose**
Also make different shades of the robot to make it look more realistic.

**Additional context**
I can't take a screenshot, a similar idea was in the "Blood eye" mod

**Comment by DindinYT37** [comment]
I don't understand the "And when the ate is red" part, can you explain what you mean there?

**Comment by 2ee4jnufew** [comment]
Translator, I'm sorry. To be a little red in the light

**Comment by mestiez** [comment]
I have no idea what this means :(

**Comment by H-is-the-best-letter** [comment]
They probably meant that android eyes should glow red in the dark.

**Comment by 2ee4jnufew** [comment]
> I have no idea what this means :(

For example, your animation. There, the android has the same eyes, and the dents make it more realistic

**Comment by 2ee4jnufew** [comment]
> They probably meant that android eyes should glow red in the dark.

And in the light, but not so much.

**Comment by 2ee4jnufew** [comment]
@mestiez

**Comment by mestiez** [comment]
Yeah I still don't understand any of this. A red glowing eye? Is that all?

**Comment by 2ee4jnufew** [comment]
> Yeah I still don't understand any of this. A red glowing eye? Is that all?

The robot in the animation has red eyes. And I ask that they be red when the lights are off

**Comment by 2ee4jnufew** [comment]
@mestiez

**Comment by mestiez** [comment]
There is no need to keep mentioning me

**Comment by UniDuki** [comment]
I believe they are talking about this steam update animation, and asking for the androids in game to look more like this.
https://cdn.akamai.steamstatic.com/steamcommunity/public/images/clans/35398057/f5394860c49757f69d658712ae798c3a581262c5.gif
