### ISSUE TITLE
Humans still alive after headshots

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#1087]
**Describe the bug**
When a human dies all the other limbs are still active and alive; when you stab someone their head is ragdolled while there bodies and still functioning,

**Mod list**
advanced damage
the nearby conflicts base :us army
ppg 3d
military trucks
doors mod
blood on walls 
darker blood
prison bus
r0y1t0 cars pack 1 (wip)
private military contractors 
wound infections
law enforcement base: less lethal dlc 
time accelerator 
law enforcement base : usa
feet arent indestructible 
firearmada 
warthog collection
throwing knife 
massa
front facing human 
musket mod
mo fluids 
injectable flasks mod 
legion
gorey human 2.0
flipping heck
gentle drag
dream
russian roulette 
wheelchair
hold k to make wires invisible 
shockwave mod
humans +
discord pack

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.23.6
 - GPU: nvidia mx330
 - CPU: intel core i7

**Additional notes**
![20220409202837_1](https://user-images.githubusercontent.com/55041380/162600529-b5c839a8-05e0-4dc1-8614-baaea60d7a03.jpg)

**Comment by Drogo-man** [comment]
I've seen this bug without mods btw

**Comment by Aspa102** [comment]
sometimes when I broke the neck of a human, they'd stumble around for a few seconds, which shouldn't happen if I recall.

**Comment by DindinYT37** [comment]
This is realistic, after death your still beats for around 40 seconds.

**Comment by mestiez** [comment]
Not a bug. The human almost certainly dies instantly, but that doesn't mean all limbs just stop living immediately too.
