### ISSUE TITLE
Lamps again

### ISSUE THREAD

**Issue by 2ee4jnufew** [studio-minus/ppg-bugs-and-requests#1089]
**Feature description**
We received one modern lamp. But what about the rest of the things? Board, grate?
**Feature purpose**
After all, a board and a grate can also be used where, like a shower. As for lamps, we do not have a large lamp and a changeable single lamp.
**Additional context**
![20220329122519_1](https://user-images.githubusercontent.com/69415642/162608955-9bac9876-cbf0-4ad8-9cd1-20dfea3677e8.jpg)
![chalkboard](https://user-images.githubusercontent.com/69415642/162609012-1e990130-083c-466a-b192-31b29d148862.png)
![Light](https://user-images.githubusercontent.com/69415642/162609017-eb4afe05-ecba-4caf-99f2-463dff4e10bf.png)

**Comment by DindinYT37** [comment]
Didn't you already suggest the lamp thing in #1028?

**Comment by ifrost-source** [comment]
Read the title again

**Comment by DindinYT37** [comment]
> Read the title again

I can read, you know? The question was why he suggested it again.

**Comment by TheBeeThat** [comment]
our hero dindin is here to minimod again!! 😊😊

**Comment by 5hart** [comment]
I was kinda confused reading this. Could you explain it again one more time?

**Comment by DindinYT37** [comment]
> I was kinda confused reading this. Could you explain it again one more time?

He's requested the other items, like the board as well.

**Comment by 5hart** [comment]
> > I was kinda confused reading this. Could you explain it again one more time?
> 
> He's requesting the other items from the new Substructure, like the board as well.

Ohh, that makes sense. Yeah I agree with that then. Along with those siren lights, that would be cool.
