### ISSUE TITLE
Make the collision branches IDEAL

### ISSUE THREAD

**Issue by Quickness19** [studio-minus/ppg-bugs-and-requests#1090]
**Feature description**
please make a good collision of tree branches and bushes

**Feature purpose**
Objects will not levitate over a branch. It is inconvenient to fight in a tree.

**Additional context**
![Скриншот 10-04-2022 220605](https://user-images.githubusercontent.com/69407926/162617262-65c37848-c342-4328-955e-9073427eee69.jpg)

**Comment by mestiez** [comment]
Collision shapes are kept simple to improve performance
