### ISSUE TITLE
Layering Issues with Android 

### ISSUE THREAD

**Issue by CyborgUnit** [studio-minus/ppg-bugs-and-requests#1091]
**Describe the bug**
The lower half of the android's arm seems to phase through its thigh, as if it was behind it and not in front of it
![image](https://user-images.githubusercontent.com/103378285/162630576-2781cf98-6898-4973-9486-c38eea60dac3.png)

**Clearly describe how to reproduce the bug**
All you have to do is spawn an Android in game 

**Mod list**
![image](https://user-images.githubusercontent.com/103378285/162630742-44f354bd-3609-4f4d-9f2a-a0e85daa3310.png)
![image](https://user-images.githubusercontent.com/103378285/162630764-b179eb00-0af5-4a23-8bb1-7f1fba0b9ac0.png)

**System info**
 - Operating system: Windows 10
 - Game version: 1.23.6
 - GPU: Nvidia GeForce GT 1030
 - CPU: ![image](https://user-images.githubusercontent.com/103378285/162631005-070a6da6-8b54-4cb6-b681-db8f96a8ea7f.png)

**Additional notes**
this has really been *bugging* me, so pls fix

**Comment by 2ee4jnufew** [comment]
There is a beta, they fixed it there

**Comment by CyborgUnit** [comment]
> There is a beta, they fixed it there

thank
