### ISSUE TITLE
PPG taking up more RAM than I have available on my computer and crashing every active program.

### ISSUE THREAD

**Issue by remram25** [studio-minus/ppg-bugs-and-requests#1093]
I would provide a screenshot but due to the nature of this crash I do not believe that its possible. PPG takes up all my RAM, Computer screen goes black and locks up for a 2 seconds then goes back on, every app that was open has magically closed, And I don't know where its trying to write data when all my RAM is in use which really concerns me.

**Comment by BBQGiraffe** [comment]
how much ram do you have on your system? if you don't know, press windows key + r at the same time and type "dxdiag" then press enter and it'll tell you along with some other system information

**Comment by remram25** [comment]
8gb active and usable is more like 6gb

**Comment by remram25** [comment]
PPG killed my taskbar and stuff is now randomly ghosting

**Comment by BBQGiraffe** [comment]
8gb should be enough for ppg + windows, what programs are you running at the same time as ppg?

**Comment by remram25** [comment]
I have tried closing all other programs and it still crashes hard

**Comment by BBQGiraffe** [comment]
this sounds like a serious issue, either windows is being windows or mestiez broke something

**Comment by remram25** [comment]
there's no crashlog in the steam folder which probably means it hard crashed

**Comment by remram25** [comment]
gonna try and restart my pc

**Comment by BBQGiraffe** [comment]
also please use the templates

**Comment by BBQGiraffe** [comment]
also please use the templates

**Comment by Drogo-man** [comment]
> 8gb should be enough for ppg + windows, what programs are you running at the same time as ppg?

I use 4 GBS of ram, and running fine.

**Comment by mestiez** [comment]
How many mods do you have

**Comment by mestiez** [comment]
closed until i get a response lmao

**Comment by remram25** [comment]
It was a problem with the amount of mods i had.
