### ISSUE TITLE
Stone bricks wall

### ISSUE THREAD

**Issue by Marcelo-sosa** [studio-minus/ppg-bugs-and-requests#1094]
**Feature description**
now that there are stones in the game could you add stone bricks/stone brick wall? they would be more resistant than the normal brick wall.

**Feature purpose and additional context**
not be anything "weird" or "out of place" in the game since there are many medieval things in the game, such as the torch, the wooden wheel or the wooden pole that is It would look great with stone bricks to make medieval castles, dungeons or torture rooms.
Edit 2:this is an illustration of what a castle would look like using the stone brick wall, and yes, I used the resizeable housing by freezing it, but that's not a replacement for a destructible wall that wouldn't cause a ton of lag
![ScreenShot_20220410223002](https://user-images.githubusercontent.com/103383717/162839828-59ab7238-13b0-48c4-88f9-561817c6fd86.jpeg)

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/175785432-2dfe4c27-3939-4cf4-bf49-763c2a5be69c.png)
I added two variants

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/175785453-f60afba0-4bca-4910-a3e3-3268d4fc080a.png)
