### ISSUE TITLE
visual bug: transparency on android's flesh and not on its skeleton which means the transparency can turn to skeleton

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#1097]
**Describe the bug**
![image](https://user-images.githubusercontent.com/101178735/162694100-1d46f2fb-a27b-41da-afb9-f4057a894958.png)

**Clearly describe how to reproduce the bug**
spawn an android then thruster his head off until his flesh and you can see the transparency then thruster his head off until skeleton. No transparency anymore

**Additional notes**
I just noticed it just now :(

**Comment by basedkit** [comment]
yeah that is super weird lmfao i never noticed it. the head just like rebuilds itself

**Comment by mestiez** [comment]
fixed
