### ISSUE TITLE
Flamethrowers spazzing out

### ISSUE THREAD

**Issue by MiezLP** [studio-minus/ppg-bugs-and-requests#1098]
hook up a flamethrower to a constant signal and it will flicker on and off instead of staying on. this appears to only happen when you put multiple flamethrowers on the same signal.

**Comment by DindinYT37** [comment]
Please use the template. Also, this is likely because of too many propagation signals being sent.

**Comment by mestiez** [comment]
This is because of an issue I haven't yet been able to fix but I am aware of. The same can happen to the Minigun
