### ISSUE TITLE
Can't set lagbox delay

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#110]
**Describe the bug**
Can't set lagbox delay sometimes

**Clearly describe how to reproduce the bug**
I'm not really sure, but I think when a timed gate is touching a lagbox you can't set the delay?. It's strange.
Here's a video that might explain it better: https://youtu.be/ASINAmBucd4

## System info

 - **OS**: Windows 10  (10.0.19043) 64bit

 - **CPU**: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz

 - **GPU**: Intel(R) UHD Graphics

 - **Memory**: 7 GB

**Comment by mestiez** [comment]
It works fine in my game. Are you sure you have no mods?

**Comment by UniDuki** [comment]
I tested it with mods and without mods but it seemed very inconsistent. I can't make it happen again now no matter what I do.

also I first found this "bug" when I tried to select all of this and set the lag box delay, and it didn't work just like in the video
![image](https://user-images.githubusercontent.com/69184577/130330014-2dee6b96-f973-4ff7-a0c0-45ce997e8d7b.png)

**Comment by mestiez** [comment]
I am unable to reproduce this but I'll look around

**Comment by mestiez** [comment]
I figured out the issue. The game thinks that a timed gate **is** a lagbox because one inherts the other.

**Comment by mestiez** [comment]
Fixed :)
