### ISSUE TITLE
1.23.6/7(?) Objects spawned by mods / game frequently have unclamped audio at very loud volumes. 

### ISSUE THREAD

**Issue by vincentix** [studio-minus/ppg-bugs-and-requests#1104]
Mods that seem to rely on object spawning and other places in the base game where objects are spawned by the game and not explicitly the user have incredibly loud collision audio sfx independent of volume settings. 

See : Radio sprite objects on hallway easter egg. Objects that are default in map. 
Most frequently caused by mods that duplicate, or spawn objects. (Limb Regrowth, Object Spawner) 
Consistent across different mod authors and game versions as of now. I have not explicitly tried this on 23.7 as it came out literally today but I will update if this has been resolved. 

not incredibly important as a bug but tends to make me shit myself as I idly constructing something when a random brick has million decibel collision sounds. 

 - Operating system: Windows 10 (old) 
 - Game version: 1.23.6/7
 - GPU: GT 730 lmao 
 - CPU: FX4300 AMD

: UPDATE does not appear to be a replicable issue as of 23.7

**Comment by DindinYT37** [comment]
Was probably fixed when #1061 was fixed.
