### ISSUE TITLE
Turn off map ambience.

### ISSUE THREAD

**Issue by Drogo-man** [studio-minus/ppg-bugs-and-requests#1108]
**Feature description**
A setting that turns off map ambiance.

**Feature purpose**
To prevent players that play for long periods of time from going crazy.

**Additional context**
I think I have the humongous map ambiance burned into my brain now.

**Comment by Marcelo-sosa** [comment]
This already exist

**Comment by Drogo-man** [comment]
wait what?

**Comment by Drogo-man** [comment]
oh
