### ISSUE TITLE
Syringe circulation is really bad.

### ISSUE THREAD

**Issue by Drogo-man** [studio-minus/ppg-bugs-and-requests#1109]
**Describe the bug**
Syringes don't circulate around the body that well.

**Clearly describe how to reproduce the bug**
Stab somebody in the foot, and use a coagulation syringe on the head.

**Mod list**
I found it with mods, but replicated it perfectly without.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.23.7
 - GPU: AMD Ryzen 5 4600H 3.00 GHz
 - CPU: NVIDIA GeForce GTX 1650

**Additional notes**
here you can see the problem better.
![People Playground Screenshot 2022 04 12 - 17 51 51 01](https://user-images.githubusercontent.com/102727246/163003163-339c57cf-5f37-46f3-a3d7-7fecce7c2c40.png)

**Comment by fhgb54643689** [comment]
yeah this has been a pain in the ass for a long time for me

**Comment by mestiez** [comment]
#1172
