### ISSUE TITLE
mods

### ISSUE THREAD

**Issue by SCRATHY049** [studio-minus/ppg-bugs-and-requests#111]
none of the lightsaber mods work

u download the lightsaber mod and they just cant activate anymore

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: any above 1.12 i remember idk for sure
 - GPU: none
 - CPU: some kind of amd

**Additional notes**

**Comment by Rademenes16** [comment]
Mods are unofficial, you download and use them on your own risk. Zooi won't fix mods of other people.
