### ISSUE TITLE
there is no liquid in red barrel

### ISSUE THREAD

**Issue by hoddddd** [studio-minus/ppg-bugs-and-requests#1112]
there is no liquid in red barrel

**Comment by Drogo-man** [comment]
how is this a bug?

**Comment by hoddddd** [comment]
> how is this a bug?

the red barrel assumes the presence of some explosive liquid in it, in game you have ability to move liquids, "the inability to pump the liquid out of the barrel" It is obviously a mistake/bug/error

**Comment by Drogo-man** [comment]
> > how is this a bug?
> 
> the red barrel assumes the presence of some explosive liquid in it, in game you have ability to move liquids, "the inability to pump the liquid out of the barrel" It is obviously a mistake/bug/error

It's not specified as a container. I mean, you have the nitroglycerin in the chemical tab.

**Comment by hoddddd** [comment]
> > > how is this a bug?
> > 
> > 
> > the red barrel assumes the presence of some explosive liquid in it, in game you have ability to move liquids, "the inability to pump the liquid out of the barrel" It is obviously a mistake/bug/error
> 
> It's not specified as a container. I mean, you have the nitroglycerin in the chemical tab.

Indeed

**Comment by DeckerExpert** [comment]
> > > how is this a bug?
> > 
> > 
> > the red barrel assumes the presence of some explosive liquid in it, in game you have ability to move liquids, "the inability to pump the liquid out of the barrel" It is obviously a mistake/bug/error
> 
> It's not specified as a container. I mean, you have the nitroglycerin in the chemical tab.

i mean, the nuke also isnt specified as a container, yet there is some liquid that is able to be pumped out.

**Comment by Drogo-man** [comment]
> > > > how is this a bug?
> > > 
> > > 
> > > the red barrel assumes the presence of some explosive liquid in it, in game you have ability to move liquids, "the inability to pump the liquid out of the barrel" It is obviously a mistake/bug/error
> > 
> > It's not specified as a container. I mean, you have the nitroglycerin in the chemical tab.
> 
> i mean, the nuke also isnt specified as a container, yet there is some liquid that is able to be pumped out.
> 

That's an Easter egg.

**Comment by DeckerExpert** [comment]
> > > > > how is this a bug?
> > > > 
> > > > 
> > > > the red barrel assumes the presence of some explosive liquid in it, in game you have ability to move liquids, "the inability to pump the liquid out of the barrel" It is obviously a mistake/bug/error
> > > 
> > > 
> > > It's not specified as a container. I mean, you have the nitroglycerin in the chemical tab.
> > 
> > 
> > i mean, the nuke also isnt specified as a container, yet there is some liquid that is able to be pumped out.
> 
> That's an Easter egg.

fair enough.
