### ISSUE TITLE
Androids freak out when you make everything weightless but their feet

### ISSUE THREAD

**Issue by 5hart** [studio-minus/ppg-bugs-and-requests#1115]
**Describe the bug**
I was messing around with gravity and whatnot when I made androids weightless for everything but their feet. It started to go crazy and flail around, then eventually fly off.

**Clearly describe how to reproduce the bug**
Step 1. Spawn an android
Step 2. Make every part of it weightless except its feet
Step 3. Move it around a bit if it doesn't do anything at first
Step 4. Watch it throw a tantrum

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.23.7
 - GPU: GTX 1060 6GB
 - CPU: Intel i7 9700k

**Additional notes**
You can also up the gravity to yield bigger results, such as it literally start to roll around the map.

**Comment by Drogo-man** [comment]
They freak out when they are falling, AKA not on the ground. since there isn't any pressure keeping them on the ground, they freak out. I think.

**Comment by 5hart** [comment]
> They freak out when they are falling, AKA not on the ground. since there isn't any pressure keeping them on the ground, they freak out. I think.

I figured it wasn't much of a bug, but I tried it with humans and it didn't affect them nearly as much as androids

**Comment by DindinYT37** [comment]
> > They freak out when they are falling, AKA not on the ground. since there isn't any pressure keeping them on the ground, they freak out. I think.
> 
> I figured it wasn't much of a bug, but I tried it with humans and it didn't affect them nearly as much as androids

Because the androids upper body weighs more than a humans' perhaps?

**Comment by 5hart** [comment]
> > > They freak out when they are falling, AKA not on the ground. since there isn't any pressure keeping them on the ground, they freak out. I think.
> > 
> > 
> > I figured it wasn't much of a bug, but I tried it with humans and it didn't affect them nearly as much as androids
> 
> Because the androids' upper body weighs more than a humans' perhaps?

I get that, I was just confused since I made it weightless.

**Comment by 5hart** [comment]
> I checked it out, and i think i know what the problem is. It's because they are really strong, so when their upper body hits the ground, they use enough force to get on their feet again (they are heavy, so they use a lot of strength). But since they are semi weightless, they just launch themselves into space.

Ok, so it's just physics, and not really a bug?

**Comment by DindinYT37** [comment]
> > I checked it out, and i think i know what the problem is. It's because they are really strong, so when their upper body hits the ground, they use enough force to get on their feet again (they are heavy, so they use a lot of strength). But since they are semi weightless, they just launch themselves into space.
> 
> Ok, so it's just physics, and not really a bug?

Probably a Unity problem if anything.
