### ISSUE TITLE
Additional settings for detectors

### ISSUE THREAD

**Issue by ppgplayer** [studio-minus/ppg-bugs-and-requests#1117]
**Feature description**
Time settings: if something is detected for X seconds, activation signal goes out. If any less than that, no signal goes out. (toggleable) 
Wave mode: If X detected in X radius, activation signal goes out.

**Feature purpose**
Could be very good for guidance systems and ballistic computers. 

**Additional context**
One of a few suggestions i will make in the coming days regarding detectors.

**Comment by DindinYT37** [comment]
Time setting can be replicated using a timed gate.

**Comment by ppgplayer** [comment]
> Time setting can be replicated using a timed gate.

A time gate sends an activation signal and THEN PREVENTS further activation signals. Have you used the timed gate before?

**Comment by DindinYT37** [comment]
> > Time setting can be replicated using a timed gate.
> 
> A time gate sends an activation signal and THEN PREVENTS further activation signals. Have you used the timed gate before?

Yeah, I did and I didn't say you could replicate it with just a timed gate, but if you use it right and think about it instead of instantly going to passive aggressively reply - you can replicate the behavior you're looking for.

**Comment by ppgplayer** [comment]
> > > Time setting can be replicated using a timed gate.
> > 
> > 
> > A time gate sends an activation signal and THEN PREVENTS further activation signals. Have you used the timed gate before?
> 
> Yeah, I did and I didn't say you could replicate it with just a timed gate, but if you use it right and think about it instead of instantly going to passive aggressively reply - you can replicate the behavior you're looking for.

No you couldn't. Not even if you use it "just right". If you post something, expect people not to agree with you. If you want me not to react to your "suggestions" in such a way then stop suggesting things that don't work even close to what it says.

I know what you do on this board. And honestly, I'm fed up with it. This is getting "off-topic", so hide your messages.

**Comment by DindinYT37** [comment]
> > > > Time setting can be replicated using a timed gate.
> > > 
> > > 
> > > A time gate sends an activation signal and THEN PREVENTS further activation signals. Have you used the timed gate before?
> > 
> > Yeah, I did and I didn't say you could replicate it with just a timed gate, but if you use it right and think about it instead of instantly going to passive aggressively reply - you can replicate the behavior you're looking for.
> 
> No you couldn't. Not even if you use it "just right". If you post something, expect people not to agree with you. If you want me not to react to your "suggestions" in such a way then stop suggesting things that don't work even close to what it says.
> 
> I know what you do on this board. And honestly, I'm fed up with it. This is getting "off-topic", so hide your messages.

I wouldn't consider this off topic as this is a discussion about the request, anyway, it is possible to do but you probably haven't tried. Not saying an extra item would be bad since it'd still be more convenient than doing it vanilla. But it is possible to make.

**Comment by ppgplayer** [comment]
> > > > > Time setting can be replicated using a timed gate.
> > > > 
> > > > 
> > > > A time gate sends an activation signal and THEN PREVENTS further activation signals. Have you used the timed gate before?
> > > 
> > > 
> > > Yeah, I did and I didn't say you could replicate it with just a timed gate, but if you use it right and think about it instead of instantly going to passive aggressively reply - you can replicate the behavior you're looking for.
> > 
> > 
> > No you couldn't. Not even if you use it "just right". If you post something, expect people not to agree with you. If you want me not to react to your "suggestions" in such a way then stop suggesting things that don't work even close to what it says.
> > I know what you do on this board. And honestly, I'm fed up with it. This is getting "off-topic", so hide your messages.
> 
> I wouldn't consider this off topic as this is a discussion about the request. Anyway, it is possible to do but you probably haven't even tried and are just jumping to assumptions. I'm not saying an extra item to do this would be bad since it'd still be more convenient than doing it vanilla, but it is possible to make.
> 
> **Edit: I have tested it in vanilla, it works but is quite bulky - though we can resize things in ppg so that wouldn't be a problem. I would still say a new item to do this would be more convenient.**

Part count is the main concern of this. The more parts the worse the stability and the more the lag. I am not jumping to assumptions, because technically ANYTHING is possible in the game. I consider this to be off topic as we are going back and forth.

If you already knew it would be bulky and impractical, don't suggest the solution. I know full well myself what it takes, so don't think you are some universal god with knowledge beyond human comprehension. I already considered this.

**Comment by DindinYT37** [comment]
> > > > > > Time setting can be replicated using a timed gate.
> > > > > 
> > > > > 
> > > > > A time gate sends an activation signal and THEN PREVENTS further activation signals. Have you used the timed gate before?
> > > > 
> > > > 
> > > > Yeah, I did and I didn't say you could replicate it with just a timed gate, but if you use it right and think about it instead of instantly going to passive aggressively reply - you can replicate the behavior you're looking for.
> > > 
> > > 
> > > No you couldn't. Not even if you use it "just right". If you post something, expect people not to agree with you. If you want me not to react to your "suggestions" in such a way then stop suggesting things that don't work even close to what it says.
> > > I know what you do on this board. And honestly, I'm fed up with it. This is getting "off-topic", so hide your messages.
> > 
> > 
> > I wouldn't consider this off topic as this is a discussion about the request. Anyway, it is possible to do but you probably haven't even tried and are just jumping to assumptions. I'm not saying an extra item to do this would be bad since it'd still be more convenient than doing it vanilla, but it is possible to make.
> > **Edit: I have tested it in vanilla, it works but is quite bulky - though we can resize things in ppg so that wouldn't be a problem. I would still say a new item to do this would be more convenient.**
> 
> Part count is the main concern of this. The more parts the worse the stability and the more the lag. I am not jumping to assumptions, because technically ANYTHING is possible in the game. I consider this to be off topic as we are going back and forth.
> 
> If you already knew it would be bulky and impractical, don't suggest the solution. I know full well myself what it takes, so don't think you are some universal god with knowledge beyond human comprehension. I already considered this.

It's quite bold of you to assume that I think of myself like that, and I didn't know it was gonna be bulky - that's why it was an **edit** and not directly featured in the reply, since I had to test it first. It was way simpler in my head so I suggested it, then also if you knew "full well" what it takes, why did you deliberately told me it was impossible?

**Comment by ppgplayer** [comment]
> > > > > > > Time setting can be replicated using a timed gate.
> > > > > > 
> > > > > > 
> > > > > > A time gate sends an activation signal and THEN PREVENTS further activation signals. Have you used the timed gate before?
> > > > > 
> > > > > 
> > > > > Yeah, I did and I didn't say you could replicate it with just a timed gate, but if you use it right and think about it instead of instantly going to passive aggressively reply - you can replicate the behavior you're looking for.
> > > > 
> > > > 
> > > > No you couldn't. Not even if you use it "just right". If you post something, expect people not to agree with you. If you want me not to react to your "suggestions" in such a way then stop suggesting things that don't work even close to what it says.
> > > > I know what you do on this board. And honestly, I'm fed up with it. This is getting "off-topic", so hide your messages.
> > > 
> > > 
> > > I wouldn't consider this off topic as this is a discussion about the request. Anyway, it is possible to do but you probably haven't even tried and are just jumping to assumptions. I'm not saying an extra item to do this would be bad since it'd still be more convenient than doing it vanilla, but it is possible to make.
> > > **Edit: I have tested it in vanilla, it works but is quite bulky - though we can resize things in ppg so that wouldn't be a problem. I would still say a new item to do this would be more convenient.**
> > 
> > 
> > Part count is the main concern of this. The more parts the worse the stability and the more the lag. I am not jumping to assumptions, because technically ANYTHING is possible in the game. I consider this to be off topic as we are going back and forth.
> > If you already knew it would be bulky and impractical, don't suggest the solution. I know full well myself what it takes, so don't think you are some universal god with knowledge beyond human comprehension. I already considered this.
> 
> It's quite bold of you to assume that I think of myself like that, and I didn't know it was gonna be bulky - that's why it was an **edit** and not directly featured in the reply, since I had to test it first. It was way simpler in my head so I suggested it, then also if you knew "full well" what it takes, why did you deliberately told me it was impossible?

Oh lord here we go.

**Comment by DindinYT37** [comment]
> > > > > > > > Time setting can be replicated using a timed gate.
> > > > > > > 
> > > > > > > 
> > > > > > > A time gate sends an activation signal and THEN PREVENTS further activation signals. Have you used the timed gate before?
> > > > > > 
> > > > > > 
> > > > > > Yeah, I did and I didn't say you could replicate it with just a timed gate, but if you use it right and think about it instead of instantly going to passive aggressively reply - you can replicate the behavior you're looking for.
> > > > > 
> > > > > 
> > > > > No you couldn't. Not even if you use it "just right". If you post something, expect people not to agree with you. If you want me not to react to your "suggestions" in such a way then stop suggesting things that don't work even close to what it says.
> > > > > I know what you do on this board. And honestly, I'm fed up with it. This is getting "off-topic", so hide your messages.
> > > > 
> > > > 
> > > > I wouldn't consider this off topic as this is a discussion about the request. Anyway, it is possible to do but you probably haven't even tried and are just jumping to assumptions. I'm not saying an extra item to do this would be bad since it'd still be more convenient than doing it vanilla, but it is possible to make.
> > > > **Edit: I have tested it in vanilla, it works but is quite bulky - though we can resize things in ppg so that wouldn't be a problem. I would still say a new item to do this would be more convenient.**
> > > 
> > > 
> > > Part count is the main concern of this. The more parts the worse the stability and the more the lag. I am not jumping to assumptions, because technically ANYTHING is possible in the game. I consider this to be off topic as we are going back and forth.
> > > If you already knew it would be bulky and impractical, don't suggest the solution. I know full well myself what it takes, so don't think you are some universal god with knowledge beyond human comprehension. I already considered this.
> > 
> > 
> > It's quite bold of you to assume that I think of myself like that, and I didn't know it was gonna be bulky - that's why it was an **edit** and not directly featured in the reply, since I had to test it first. It was way simpler in my head so I suggested it, then also if you knew "full well" what it takes, why did you deliberately told me it was impossible?
> 
> Oh lord here we go.

Don't "Oh lord here we go" me, you were the one that (apparently) deliberately told me it was impossible even though you were fully aware that it was possible yourself - which has provoked this whole discussion. **Now** we can hide these replies as off-topic since now they're actually too far off-topic to be considered fitting for this issue.

**Comment by mestiez** [comment]
Can both of you stop quoting each other? Just type a comment as a reply instead.
