### ISSUE TITLE
New weapons

### ISSUE THREAD

**Issue by CrocodileBundy** [studio-minus/ppg-bugs-and-requests#112]
I got 3 new wepon ideas:

1. A .22 long rifle pistol with and without a supressor
2. A nail gun which can be used to nail humans and those spiders to planks and other stuff
3. A taser which can damage the Android but the humans and spider just get tased without killing or burning them

(I know those things aren't spiders but I don't know the name of them)

**Comment by mestiez** [comment]
You should separate each feature request into its own issue next time :)

**Comment by mestiez** [comment]
1. What makes this different from the other weapons? 
2. What makes this different from the shard gun?
3. What is the purpose of this gun?

**Comment by CrocodileBundy** [comment]
The .22lr does less damage than the other pistols so theres not too much
bleeding

The nail gun actually goes through the body and sticks them to e.g. wood

And the purpose of the taser is just to taste them I guess 🤔

zooi ***@***.***> schrieb am So., 22. Aug. 2021, 00:06:

**Comment by mestiez** [comment]
The shard gun already goes through, and pins, bodies.

**Comment by CrocodileBundy** [comment]
But only through legs and arms but not through the head and body.

zooi ***@***.***> schrieb am Di., 24. Aug. 2021, 11:42:

**Comment by roscosthebalm** [comment]
they can go through there heads but it doesnt look like it

**Comment by vda8** [comment]
all these things are already in the game, or in a mod.
