### ISSUE TITLE
Centrifuge Won't Work

### ISSUE THREAD

**Issue by PortalFan15** [studio-minus/ppg-bugs-and-requests#1122]
**Describe the bug**
The liquid centrifuge does not work.

**Clearly describe how to reproduce the bug**
1. Spawn in two or more different liquids, and a centrifuge.
2. Add liquids to centrifuge
3. Activate centrifuge.

**Mod list**
None

**System info (please complete the following information)**
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8485033/exported.game.debug.info.md)

**Additional notes**

Main.log repeatedly sends the message
[EXCEPTION] NullReferenceException: Object reference not set to an instance of an object
	LiquidContainerController.AddForce (UnityEngine.Vector2 globalForce, System.Single randomisation) (at c0b2f919e1914e24885355a6ecb919ab:0)
CentrifugeBehaviour.FixedUpdate () (at c0b2f919e1914e24885355a6ecb919ab:0)

as long as the centrifuge is activated.

**Comment by Drogo-man** [comment]
What happens, and what's suppose to happen??

**Comment by mestiez** [comment]
Oh I think I understand what the issue is. You must have disabled Fancy Effects

**Comment by mestiez** [comment]
Fixed
