### ISSUE TITLE
Flourescent lamps glowey overlay bit displays over ground when on.

### ISSUE THREAD

**Issue by baconfrymanpan** [studio-minus/ppg-bugs-and-requests#1125]
**Describe the bug**
Flourescent lamps glowing bit displays over the floor, The only other item that has this problem is the lightbulb.

**Clearly describe how to reproduce the bug**
Press pause. Spawn flourescent lamp, Turn it on. And move it under the floor.

**Mod list**
Water Physics
Darker Blood (love this mod)
No Internal Bleeding. 
Flipping Heck.
Example Mod 3.0 (Deactivated. Adds 2 items.)

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.23.9
 - GPU: GeForce GT 1030
 - CPU: Intel i5-2400

**Additional notes**
![lksdjaf](https://user-images.githubusercontent.com/103342629/163435002-afe9f6f7-b6e1-4e54-afff-a7bc94575313.PNG)
funny image

**Comment by baconfrymanpan** [comment]
ignore zdoom launcher in my task bar, its all in your head

**Comment by mestiez** [comment]
Fixed
