### ISSUE TITLE
Axes not disappearing 

### ISSUE THREAD

**Issue by Breezy10101** [studio-minus/ppg-bugs-and-requests#113]
Whenever you undo (z) a creation with a axe in it the axe wont disappear.

Select a creation that has an axe and then press z.

1.21.2

This is a really annoying bug because you have to manually delete the axes or do Clear Everything

**Comment by mestiez** [comment]
Are these contraptions very old? If they are, this is to be expected. Contraptions inevitably become outdated as the game evolves.

**Comment by mestiez** [comment]
Never got a response
