### ISSUE TITLE
when you clear everything when you pull out the secret block from the blocks map and the alarm starts, the map becomes void

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#1132]
**Describe the bug**
when you clear everything when you pull out the secret block from the blocks map and the alarm starts, the map becomes void

**Clearly describe how to reproduce the bug**
get the secret block out of its place then wait for alarm to start then clear everything then boom!

**Additional notes**
if you don't know what I am talking about with the secret block, it's a new secret in the blocks map. find it yourself shhh

**Comment by Koshi32** [comment]
what's "the secret block"?

**Comment by basedkit** [comment]
> what's "the secret block"?

its a hidden movable map block you can find

**Comment by mestiez** [comment]
Not void, the lights are just off
