### ISSUE TITLE
humans die when frozen at high speeds

### ISSUE THREAD

**Issue by basedkit** [studio-minus/ppg-bugs-and-requests#1136]
**Describe the bug**
if you have a human in a flying creation going relatively fast and you freeze them they will die

**Clearly describe how to reproduce the bug**
set iterations to max and use continuous, then make/use a flying creation and have a human sit in a chair, once your moving somewhat fast freeze it and they will die.

**Mod list**
no mods

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.23.7
 - GPU:  Nvidia GeForce 1660 Ti
 - CPU: Ryzen 7

**Additional notes**

**Comment by mestiez** [comment]
This happens because of g-forces but I guess the calculation shouldn't be made when frozen

**Comment by mestiez** [comment]
Fixed :)

**Comment by basedkit** [comment]
> Fixed :)

@mestiez it still kills them :(

**Comment by DindinYT37** [comment]
> > Fixed :)
> 
> @mestiez it still kills them :(
> also physics are acting a bit funky now

Doesn't mean it's already published.
