### ISSUE TITLE
Fixed resistor.

### ISSUE THREAD

**Issue by Drogo-man** [studio-minus/ppg-bugs-and-requests#1139]
**Feature description**
A normal resistor. But it's fixed to a certain percent of resistance (that you can change in the context menu).

**Feature purpose**
A better resistor, that doesn't have a handle that can be wonky and unpredictable.

**Additional context**
It's really annoying, as an avid electronics maker, that you cant have a fixed resistor. As the current one always changes resistance on the slightest touch and is VERY inaccurate.

**Comment by UniDuki** [comment]
Also make it adjustable with colored signals please!
