### ISSUE TITLE
Clear Debris fix

### ISSUE THREAD

**Issue by StealthDrifter** [studio-minus/ppg-bugs-and-requests#114]
Clear debris should clear box debris too, seems like a oversight that it doesn't clear box debris.

**Comment by DindinYT37** [comment]
What do you mean with "Box Debris"?

**Comment by StealthDrifter** [comment]
when a box breaks it splits into 4 or 5 parts that is basically debris

**Comment by mestiez** [comment]
This is not a feature request, this is a bug report.
