### ISSUE TITLE
Invisible cursor

### ISSUE THREAD

**Issue by Farrelmeme** [studio-minus/ppg-bugs-and-requests#1141]
**Describe the bug**
Your Cursor will be invisible

**Clearly describe how to reproduce the bug**
Well... Get the Font machinw thing, and then press ENTER Boom your cursor is invisble. To get the cursor back is by changing the font, thats the challanging part

**Mod list**

**System info (please complete the following information)**
 - Operating system: 
 - Game version: 
 - GPU:
 - CPU:

**Additional notes**

**Comment by DindinYT37** [comment]
There is no changing font?

**Comment by mestiez** [comment]
I have no idea what you're talking about. What is a font machine.

**Comment by mestiez** [comment]
I will close this until I get a response or any kind of elaboration

**Comment by UniDuki** [comment]
The "font machine" is the key trigger I assume.
1. Open the key trigger menu
2. Left click on space to set the key
3. While your mouse is invisible click cancel

Your mouse should now be invisible until you quit the game or open the menu again. No mods

**Comment by DindinYT37** [comment]
> This report does not make any sense. But this bug I found is very similar, and may be what they are trying to say:
> 
> 1. Open the key trigger menu
> 2. Click to edit the trigger key
> 3. While your mouse is invisible click cancel
> 
> Your mouse should now be invisible until you quit the game or open the menu again. No mods

But, do you know why did he said Font-Machine or changing Font?
