### ISSUE TITLE
Fragmentation explosives shouldn't blow humans to pieces.

### ISSUE THREAD

**Issue by RottenPotatoB** [studio-minus/ppg-bugs-and-requests#1146]
**Feature description**
Fragmentation explosives don't dismember humans or send them flying, instead they only deal shrapnel damage.

**Feature purpose**
Realism as in real life the blast from a fragmentation grenade is too small to cause any damage alone and their true deadliness comes from the shrapnel they send flying off.

**Comment by Drogo-man** [comment]
If ppl are close enough they can get blown to pieces. It kinda depends on the grenade tho.

**Comment by TamasB14** [comment]
A casual grenade is enough to blow one of your legs off and damage your other leg if close.

**Comment by planimun** [comment]
I feel as if there should be a weaker general explosions with a smaller radius maybe, but it's not the weirdest thing ever for your limbs to come off if too close.

**Comment by mestiez** [comment]
but is more fun this way
