### ISSUE TITLE
Objects frozen like in the air

### ISSUE THREAD

**Issue by GamingNoob666** [studio-minus/ppg-bugs-and-requests#1147]
**Describe the bug**
An object will be frozen like, but it very slowly falls to the ground, you can spawn items on top of it to make it slightly move, but if you click on an object, it will regain its gravity, and fall.

**Clearly describe how to reproduce the bug**
Grab an item, while moving it pause the game, go into settings and change the collision quality to a different one you had before and then it happens

**Mod list**
I deactivated all my mods and tried, it still works.

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8509564/exported.game.debug.info.md)

**Additional notes**
no

**Comment by ppgplayer** [comment]
this happens with alt tab too just click and deal with it

**Comment by mestiez** [comment]
Technically the same as #444
