### ISSUE TITLE
Firework Damage Radius

### ISSUE THREAD

**Issue by Dekkri** [studio-minus/ppg-bugs-and-requests#1151]
Whenever a firework is detonated its explosion radius is left behind even though the item has been expended.

To reproduce the effect, spawn in a firework, go into detailed view, detonate the firework. Even if you go out and back into the detailed view the radius of the explosive is still outlined

All Mods are deactivated

Overdose
Humans+
Hasmat Mod Remastered
Chemical Warfare
Powers Mod
CSGO SAS NPC's Mod
FleasyWeapons- Small Weapons
FleasyWeapons- Rifles
C.T.T.C Tech MOD
The Grappling Gun Mod
Wild Medieval
Dawid23 Gamer's Chemistry mod
The Nearby Conflicts Base: Ukraine Ground Forces
Melee Weapons
Tactical Armor Mod
Cormandy Republic Mod

 - Operating system: Windows 10
 - Game version: 1.23.6
 - GPU: AMD Radeon 8750M
 - CPU: Intel(R) Core(TM) i7-46000

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8521602/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
Please keep the headers of the template when making an issue.

**Comment by mestiez** [comment]
Fixed :)
