### ISSUE TITLE
Extreme Realistic Water?!?!?

### ISSUE THREAD

**Issue by FFreaky** [studio-minus/ppg-bugs-and-requests#1154]
Feature1: Extreme Realistic water in setting
Feature2:water are can on floor
Feature3:When You Drop Something Water Will Splat But That Not Effect

**Comment by Drogo-man** [comment]
No.

**Comment by DindinYT37** [comment]
Please use the template, also it was already stated several times that water physics will not happen.

**Comment by Marcelo-sosa** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2793815479
