### ISSUE TITLE
Boat Motor Saving Bug

### ISSUE THREAD

**Issue by MaxeUA** [studio-minus/ppg-bugs-and-requests#1164]
**Describe the bug**
So the new motor used for boats does not react to red propagation wire as it should be, and the "reverse gear" setting doesn't work with saving either.

Check it by saving the Boat Motor with reversed gear

**Mod list**
None.

**System info (please complete the following information)**
I don't really think that i need to include theese.

**Additional notes**

**Comment by mestiez** [comment]
Fixed :)
