### ISSUE TITLE
G-Force should knock people out

### ISSUE THREAD

**Issue by Uniconrzss** [studio-minus/ppg-bugs-and-requests#1166]
**Feature description**
Make G-Force a thing. People will get knocked out if subjected to a high enough g force. Should be also toggleable.

**Feature purpose**
Could be good for rp purpouses and another problem for engineers to solve if g force is enabled.

**Additional context**
Maybe also make people more tolerant to gforce the more they are exposed to it or something like that i dunno.

**Comment by ppgplayer** [comment]
honestly bro i think this is already in the game tbh. i mean they don't lose consciousness or whatever but you can fling those little guys around and see the g forces at play

**Comment by DindinYT37** [comment]
This is already a thing, as mentioned by zooi before in another issue. Hence why humans die when travelling at high speeds without collision of any kind.

**Comment by mestiez** [comment]
This already exists, but doesn't make people pass out.

**Comment by YourLocalPlonker** [comment]
Yeah I once tried the effects of G-Forces on humans and they do not pass out but they start dying

**Comment by basedkit** [comment]
> This already exists, but doesn't make people pass out.

would it be possible to make that toggleable?

**Comment by bluewoods64** [comment]
its a shame that you cant get them fast enough before they for some reason rip in half because of you pulling them
