### ISSUE TITLE
You can disintegrate slider connectors.

### ISSUE THREAD

**Issue by mestiez** [studio-minus/ppg-bugs-and-requests#1170]
**Describe the bug**
You can disintegrate slider connectors. This leaves a line without connectors and it shouldn't exist.

**Clearly describe how to reproduce the bug**
Spawn slider.
Spawn disassembler gun.
Shoot both connectors until they disintegrate.

**Mod list**
None.

**System info (please complete the following information)**
 - Operating system: Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
 - Game version: 1.23.11
 - GPU: NVIDIA GeForce RTX 3070 and NVIDIA GeForce GTX 1050 Ti
 - CPU: AMD Ryzen 7 5800X 8-Core Processor, 3801 Mhz, 8 Core(s), 16 Logical Processor(s)

**Comment by DindinYT37** [comment]
Huh?

**Comment by AlexCodeMan** [comment]
1.23.11?

**Comment by ppgplayer** [comment]
did this mf forget to switch accounts and self-filed a bug report lmao

**Comment by Drogo-man** [comment]
> did this mf forget to switch accounts and self-filed a bug report lmao

I'm pretty sure it's just to document the bug, or something.

**Comment by ppgplayer** [comment]
> > did this mf forget to switch accounts and self-filed a bug report lmao
> 
> I'm pretty sure it's just to document the bug, or something.

there is something called notepad, google docs and paper

**Comment by StealthDrifter** [comment]
> > > did this mf forget to switch accounts and self-filed a bug report lmao
> > 
> > 
> > I'm pretty sure it's just to document the bug, or something.
> 
> there is something called notepad, google docs and paper

its almost like this is a bug forum, posting it here will let others know it exists and not create duplicate bug reports.
this could also be the same as notepad in a way, just public.

**Comment by DindinYT37** [comment]
> > > > did this mf forget to switch accounts and self-filed a bug report lmao
> > > 
> > > 
> > > I'm pretty sure it's just to document the bug, or something.
> > 
> > there is something called notepad, google docs and paper
> 
> its almost like this is a bug forum, posting it here will let others know it exists and not create duplicate bug reports.
> this could also be the same as notepad in a way, just public.

People don't care if the bug was already reported, rather, they get offended.
About the notepad thing - he could've put it directly on the project though?

**Comment by mestiez** [comment]
This issue board is not just to let others report bugs, it's a bug tracker. This is where I keep track of all bugs so I will report them myself too.

**Comment by mestiez** [comment]
Fixed
