### ISSUE TITLE
Syringe effects not applying to some body parts

### ISSUE THREAD

**Issue by Aeternaliter** [studio-minus/ppg-bugs-and-requests#1172]
**Describe the bug**
When injecting a syringe into a human, there's a good chance that some limbs will not be affected (This is most apparent on the zombie syringe where the skin is supposed to change color, either that or it only applies to the zombie syringe.) I've had this happen many times.

**Clearly describe how to reproduce the bug**
Inject a human with a zombie syringe
Repeat several times and you should see one of the zombies with an arm or leg that isn't affected (you may need to move them around a bit to see if the background limbs aren't affected)

**Mod list**
Flipping heck
Human decal enabler

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.23.7 (I think)

**Additional notes**
The bug only seems to happen on background arms or legs, and it doesn't happen all the time

**Comment by TamasB14** [comment]
Seen that issue too. It seems like the effect does not always reach further bodyparts.

**Comment by DindinYT37** [comment]
> Seen that issue too. It seems like the effect does not always reach further bodyparts.

It would be funny if zooi were to turn this bug into a feature; some humans could have better and worse blood circulation (stronger/weaker hearts ig) which could cause this.

**Comment by mestiez** [comment]
I think I fixed it. Don't hesitate to open this issue if you encounted it again (after the update)
