### ISSUE TITLE
Enable the Recompile button for mods under certain circumstances 

### ISSUE THREAD

**Issue by Punkkinn** [studio-minus/ppg-bugs-and-requests#1173]
**Feature description**
Whenever a mod in the mods menu has the ‘upload’ button, the ‘recompile’ button should also be enabled as well.

**Feature purpose**
To make it so modders don’t have to close the game and reopen it every time they make a slight change. 

**Additional context**
It would significantly increase the speed at which modders are able to make their mods

**Comment by DindinYT37** [comment]
This was already rejected several times.
