### ISSUE TITLE
I can access the latest versions, including if I play crack We will squirt out fires and fires and besides that, a steam engine should come to the game so that old trains and locomotives can be made, also it will be a new energy source, I want them in the 1.24 update please add them from me that's all

### ISSUE THREAD

**Issue by 821lemur** [studio-minus/ppg-bugs-and-requests#1181]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by DindinYT37** [comment]
Use the template, you put everything that should be in the issue's body in it's title.
