### ISSUE TITLE
I want a water pump that can work with electricity, that is, with any power source, this pump will work and draw water when it is powered, but a new tool hose will be needed to carry the water. We will be able to extinguish the fires with splitting water and wipe the blood and explosion stains on the ground, and especially the fires need to be extinguished with water, besides, we will combine soap and water and make foam and use them to extinguish oil fires, I hope it will be added to the 1.24 update.

### ISSUE THREAD

**Issue by 821lemur** [studio-minus/ppg-bugs-and-requests#1182]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by DindinYT37** [comment]
Use the template, you put everything that should be in the issue's body in it's title.

**Comment by hunterPea** [comment]
sounds good but i think zooi will never add liquid physics, its sad but i understand zooi, programming and making games is hard as f##k and extremely stressful, im saying this because of my own experience;

btw you should reformat that......
