### ISSUE TITLE
new tool hose will be very useful

### ISSUE THREAD

**Issue by 821lemur** [studio-minus/ppg-bugs-and-requests#1183]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by DindinYT37** [comment]
Use the template, you put everything that should be in the issue's body in it's title.
