### ISSUE TITLE
sparks on metal clash

### ISSUE THREAD

**Issue by 69Chosen69** [studio-minus/ppg-bugs-and-requests#1187]
new particle thing where when metal objects can clash and produce sparks

increases detail

**Additional context**

**Comment by DindinYT37** [comment]
Can you like, properly use the template? Otherwise good idea though.

**Comment by YourLocalPlonker** [comment]
it would also be cool if metal slides too fast on the ground or bumps into something to fast it would generate sparks

**Comment by YourLocalPlonker** [comment]
Great request! totally love that idea!

**Comment by 69Chosen69** [comment]
> Can you like, properly use the template? Otherwise good idea though.

wazap
