### ISSUE TITLE
my request is that if a generator is connected and started while a water pump is in contact with any water, pressing the f key will pump water into the hose, which is the new tool, but it will be necessary to connect the hose to a valve, thanks to this, we will be able to really extinguish the fires with water.

### ISSUE THREAD

**Issue by 821lemur** [studio-minus/ppg-bugs-and-requests#1188]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by DindinYT37** [comment]
Use the template, you put everything that should be in the issue's body in it's title.

**Comment by ppgplayer** [comment]
this guy really likes his hoses

**Comment by 821lemur** [comment]
> bu adam hortumlarını gerçekten seviyor

I don't like hoses, I just want to put out a fire with water in the game

**Comment by ppgplayer** [comment]
> > bu adam hortumlarını gerçekten seviyor
> 
> I don't like hoses, I just want to put out a fire with water in the game

:( Why don't you like hoses
