### ISSUE TITLE
In order to extinguish the fire with water in the game, it is only necessary to contact the fire with water, but thanks to my great idea, this will not be necessary. You will add the fire extinguisher used by real life firefighters to the game as in my idea, and also the pressure of the pump in my idea can be adjusted, I hope it will be added in the 1.24 update.

### ISSUE THREAD

**Issue by 821lemur** [studio-minus/ppg-bugs-and-requests#1190]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by DindinYT37** [comment]
Use the template, you put everything that should be in the issue's body in it's title.

**Comment by TamasB14** [comment]
> Use the template, you put everything that should be in the issue's body in its title.

Not worth trying, he can't see you. Let mestiez close his requests; That way he might realise what he did wrong.

**Comment by DindinYT37** [comment]
> > Use the template, you put everything that should be in the issue's body in its title.
> 
> Not worth trying, he can't see you. Let mestiez close his requests; That way he might realise what he did wrong.

Yeah but he might also realize it if he gets multiple notifications on each issue.

**Comment by ppgplayer** [comment]
aughhhhhhhhhhhhhh
