### ISSUE TITLE
Universal fluid decal placement

### ISSUE THREAD

**Issue by alikeobservant** [studio-minus/ppg-bugs-and-requests#1194]
**Feature description**
Liquid decals (blood, oil, anything fluid) should be able to spray on every object, with the most important one being humans. There are many mods that do this but are a bit janky.

**Feature purpose**
This will allow the player to achieve numerous things with the way fluid is placed in the game

**Additional context**
No other context

**Comment by ppgplayer** [comment]
based opinion but there are probably some problems with it idk remember when but zooi said it|

i still think it's a good idea

**Comment by ppgplayer** [comment]
> > based opinion but there are probably some problems with it idk remember when but zooi said it|
> > i still think it's a good idea
> 
> Heard it was removed for humans because it could clash with the flesh/bone layer of it.

o yea it was probably that

**Comment by mestiez** [comment]
Im not sure what this means. Are you just asking for decals on humans?

**Comment by mestiez** [comment]
This is already possible though. You can push any liquid through something like a liquid outlet and it'll get everywhere.

**Comment by DindinYT37** [comment]
> This is already possible though. You can push any liquid through something like a liquid outlet and it'll get everywhere.

I know, which is why I haven't really said much about it (since I can't be fully sure that I understood it right).
