### ISSUE TITLE
Characters Not Burning

### ISSUE THREAD

**Issue by xerxes93** [studio-minus/ppg-bugs-and-requests#1197]
https://user-images.githubusercontent.com/18428165/166069845-f9dfc017-fef7-4688-bac1-ef15ef8efb52.mp4

help

**Comment by DindinYT37** [comment]
1. How do we know you aren't using a mod to,,, disable burning for example.
2. Please use the template.
3. You haven't even provided **any** information about this other than "Characters not burning".
