### ISSUE TITLE
infinte source for the empty syringe

### ISSUE THREAD

**Issue by unkown367** [studio-minus/ppg-bugs-and-requests#120]
description
allows you to have a infinte source of what ever is in the syringe

purpose
so you don't have to keep refilling the syringe

**Comment by mestiez** [comment]
Isn't this impossible? An infinite syringe continuously makes more of the liquid it is assigned, while an empty syringe is not assigned any liquid. This means that it has to multiply whatever it contains at that moment which could change at any time because of liquid mixing and stuff.
