### ISSUE TITLE
SAVED WITH ERRORS HELP ME PLEASE I WANNA SAVE THINGS :(

### ISSUE THREAD

**Issue by NexmV** [studio-minus/ppg-bugs-and-requests#1204]
The bug is whenever I try to save A build I have spent time on, it says crap Like *saved with errors* and it works sometimes. I've researched this a BUNCH on most platforms such as steam yt google and more and the only one I found was one where there was a update. I don't have that though. Its so frustrating.

**Comment by DindinYT37** [comment]
Please use the template. Also this is likely caused by a mod.
