### ISSUE TITLE
Running animation

### ISSUE THREAD

**Issue by YourLocalPlonker** [studio-minus/ppg-bugs-and-requests#1207]
Basically an animation that allows living things to run.

Living creatures will be able to move faster

**Comment by DindinYT37** [comment]
Please use the template.

**Comment by YourLocalPlonker** [comment]
> Please use the template. Also, this is pretty much a duplicate of #724, zooi has also already answered #724 so I suggest checking there.

ok

**Comment by ppgplayer** [comment]
this needs to be added solely for entertainment and watching the humans trying to run

**Comment by YourLocalPlonker** [comment]
> this needs to be added solely for entertainment and watching the humans trying to run

ok
