### ISSUE TITLE
Pack of Features/Reworks

### ISSUE THREAD

**Issue by TamasB14** [studio-minus/ppg-bugs-and-requests#121]
1.) Bleeding (Rework)
- Creatures who got stabbed will only bleed when the object they got stabbed with is out of them.
- Bleeding will decrease if the wound is hold upwards.
- Bleeding can be stopped/decreased temporary when there's an object pushed on the wound.

2.) Weapons after death (Feature)
- Disabling the weapon's collission after death, until the weapon is out of the creature's body.
(After a creature who has been using a weapon dies, it causes them to drop their weapons which leads to the weapons sticking into their body breaking their bones unrealistically. By making the weapon no collide to the body until it's out of the body's personal space, it would fix this problem.) The weapon will still have collission towards other objects except the body it was connected to.

3.) Bullets (Rework)
- Bullets should shrapnel after going through obstacles/creatures. (But not physical bullets, instead of physical shrapnel, that one bullet particle should just turn into more less damaging "particles".)
- Option for tracer's color to be changed.
- Sometimes bullets should cause sparks on metal surfaces allowing things near metal to explode. ( So dynamites would no longer explode on hit, unless something caused a spark)

4.) Heat (Rework)
- Adding option to fully eliminate heat-spreading through objects.
- Adding cooling feature for the fire-extinguisher.
- Heating things through a hot object should be much slower.
- Creatures stepping on hot objects should withstand more heat before burning like a torch.
(The current temperature feature is really broken, often causing fires that can't be put out.)

5.) Arrowheads (New item)
- Sticking arrows. (The current arrow just hits the target and falls out. How about making an arrow type that is alot more harder to fall out?)

6.) Explosives (Rework)
- Some explosives should have shrapnels. (F.E.: Grenades)

7.) Lighters, Matches (New item)
- Lighters (Unlimited) being able to burn things.
- Matches (One-use) being able to burn things.

**Comment by mestiez** [comment]
Please do not group feature requests.

**Comment by mestiez** [comment]
1. The object pushy thing is not going to happen. It's too CPU hungry for what it is.

2. This is possible but, for performance reasons, only in a very basic way.

3. This is most likely too demanding for the processor...

4. The fire extinguisher does cool objects but only if they are on fire. 
Fires keep burning if the area or the objects in it are simply too hot. There is no way for the system to be consistent if this wasn't the case.

5. Arrows that are harder to pull out are also harder to put in. 

6. Fragmentation explosives do send out shrapnel, it's just not physical or visible.

7. What is the difference between a lighter and a flamethrower/torch?
What is the purpose of a one-use match?
