### ISSUE TITLE
Frozen Humans stop rotting.

### ISSUE THREAD

**Issue by devastator162** [studio-minus/ppg-bugs-and-requests#1213]
**Feature description**
When human body temperature is below a certain amount of degrees the human stops rotting.

**Feature purpose**
A bit of realism.

**Additional context**
none

**Comment by Marcelo-sosa** [comment]
bro, this already happens in the game...

**Comment by devastator162** [comment]
since when? (last time I tried human rot anyway, human temperature was at least -100 degrees)

**Comment by DindinYT37** [comment]
> since when? (last time I tried human rot anyway, human temperature was at least -100 degrees)

Why's that in brackets?

**Comment by DindinYT37** [comment]
> bro, this already happens in the game...

Are you sure you don't have a damage mod or something that does this?

**Comment by mestiez** [comment]
This already happens. The threshold is -50 degrees Celsius
