### ISSUE TITLE
More aliens

### ISSUE THREAD

**Issue by thisinsaname** [studio-minus/ppg-bugs-and-requests#1214]
**Feature description**
More alien like creatures. We have the gorse already but more would be cool.

**Feature purpose**
It provides more ways to kill humans, experiment, and just have fun in general. I'm not sure exactly what they would do, I'll leave that up to the dev, but they should do something harmful to humans/androids or even gorse.

**Comment by DindinYT37** [comment]
Do you mean different "entities" like how the Gorse isn't a humanoid? I agree if you mean not-humanoid entities, but if you mean humanoid entities - you could just use mods.
