### ISSUE TITLE
new right click settings

### ISSUE THREAD

**Issue by 69Chosen69** [studio-minus/ppg-bugs-and-requests#1217]
**Feature description**
its like resize but it simultaneously resizes the length and width of an object without having to put 2 objects together

**Feature purpose**
makes gameplay easier

**Additional context**
this can happen when you resize 2 objects together, but theres no feature that can do the same thing with one object

**Comment by DindinYT37** [comment]
Just hold shift when resizing one object...

**Comment by 69Chosen69** [comment]
> Just hold shift when resizing one object...

OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

**Comment by DindinYT37** [comment]
> > Just hold shift when resizing one object...
> 
> OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH

Close the Issue?

**Comment by 69Chosen69** [comment]
> > > Just hold shift when resizing one object...
> > 
> > 
> > OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
> 
> Close the Issue?

alright mate

**Comment by DindinYT37** [comment]
> > > > Just hold shift when resizing one object...
> > > 
> > > 
> > > OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
> > 
> > 
> > Close the Issue?
> 
> alright mate

So why didn't you close it...

**Comment by 69Chosen69** [comment]
> > > > > Just hold shift when resizing one object...
> > > > 
> > > > 
> > > > OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
> > > 
> > > 
> > > Close the Issue?
> > 
> > 
> > alright mate
> 
> So why didn't you close it?

i need  time

**Comment by DindinYT37** [comment]
> i need time

What???

**Comment by 69Chosen69** [comment]
> 

i need time

**Comment by 69Chosen69** [comment]
> > i need time
> 
> What???

to delete

**Comment by DindinYT37** [comment]
> > > i need time
> > 
> > 
> > What???
> 
> to delete

Dude, it's literally one clicks to close this issue...
