### ISSUE TITLE
Brain Matter Settings

### ISSUE THREAD

**Issue by curz3** [studio-minus/ppg-bugs-and-requests#1218]
Description: Add a feature in the settings that allows you to adjust the percent chance of brain matter spawning on headshots, amount of brain matter, and a realism setting so that only high calibre firearms can spawn brain matter particles.

Purpose: I requested this feature because seeing a 9mm blow someone's brains out and not a sniper rifle was unrealistic. Its purpose is to add another layer of personalization and adjustability. At the time of making this request, there are no mods or tools that do this.

**Comment by DindinYT37** [comment]
Please use the template. Also:
- It's about strength not only chance as far as I know.
- Why would you need a setting to adjust the amount? Is it too much for you? Too less?
- Pretty sure it's realistic enough; Brain matter only "spawns" when either firing a "weak" gun (like a Pistol) at small distance (directly on the head) or when it's within a certain distance with a stronger gun (ex. a sniper or even a shotgun)

About your purpose, pretty sure it's how I described: Weak gun at very short distances or stronger gun at a bit longer distances.
![image](https://user-images.githubusercontent.com/64973205/167252784-ed0f610c-7318-47f4-a424-47421e75db1f.png)

(My opinion)
I don't know why you would want to change any of this as it is just a minor quality of life feature, and those settings don't really change much.
