### ISSUE TITLE
Abnormal stiffness on humans that causes leg damage on spawn.

### ISSUE THREAD

**Issue by GitNeto** [studio-minus/ppg-bugs-and-requests#1219]
Unnormal stiffness on humans that causes leg damage on spawn.

Just spawn a human about 3 feet above the ground and due to its stiffness, it will get bruises and annoying blood on its legs.

No Mod-List is needed many players have complained about this issue since the beta came out.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.23.7
 - GPU: GTX 1050
 - CPU: Intel Core i5

**Comment by DindinYT37** [comment]
You know it would be pretty nice if you could keep the template's headers.
Also, I don't think it's important enough to be fixed unless it's really easy to fix since it doesn't really hurt the human.

**Comment by WWWOWWWPL** [comment]
i agree. it's really annoying when a guy falls onto the ground from a meter and makes an enormous blood splatter while getting his legs fucked up

**Comment by DindinYT37** [comment]
> i agree. it's really annoying when a guy falls onto the ground from a meter and makes an enormous blood splatter while getting his legs fucked up

This doesn't even happen when they fall from a meter?

**Comment by Drogo-man** [comment]
I've had this happen from like 10 centimeters where the ground will shake, you'll hear a gaint crack and thud, and the legs will get really screwed up. This was pre beta, and I'm pretty sure it's as old as the game itself.

**Comment by DindinYT37** [comment]
> I've had this happen from like 10 centimeters where the ground will shake, you'll hear a gaint crack and thud, and the legs will get really screwed up. This was pre beta, and I'm pretty sure it's as old as the game itself.

You guys have weird experiences, this hasn't happened to me yet.

**Comment by ppgplayer** [comment]
> > I've had this happen from like 10 centimeters where the ground will shake, you'll hear a gaint crack and thud, and the legs will get really screwed up. This was pre beta, and I'm pretty sure it's as old as the game itself.
> 
> You guys have weird experiences, ~this hasn't happened to me yet~.
> 
> **Edit:** It just happened to me, since I went on to test with a lot of humans. Though it happens rarely, it does happen; but I wouldn't consider it "fucking up their legs" since they can still stand and walk as usual (Tested on 1-2m height). Note that it doesn't only happen on freshly spawned humans but also on some "older" humans.

Dindin



nobody cares if you haven't experienced it yet

**Comment by Drogo-man** [comment]
> > > I've had this happen from like 10 centimeters where the ground will shake, you'll hear a gaint crack and thud, and the legs will get really screwed up. This was pre beta, and I'm pretty sure it's as old as the game itself.
> > 
> > You guys have weird experiences, ~this hasn't happened to me yet~.
> > 
> > **Edit:** It just happened to me, since I went on to test with a lot of humans. Though it happens rarely, it does happen; but I wouldn't consider it "fucking up their legs" since they can still stand and walk as usual (Tested on 1-2m height). Note that it doesn't only happen on freshly spawned humans but also on some "older" humans.
> 
> Dindin
> 
> 
> 
> nobody cares if you haven't experienced it yet

This is a game bug and requests forum, you don't have to care. This isn't Twitter.

**Comment by Drogo-man** [comment]
> You guys have weird experiences, ~~this hasn't happened to me yet~~.
> 
> **Edit:**
> It just happened to me, since I went on to test with a lot of humans. Though it happens rarely, it does happen; but I wouldn't consider it "fucking up their legs" since they can still stand and walk as usual (Tested on 1-2m height).
> Note that it doesn't only happen on freshly spawned humans but also on some "older" humans.

When it happens to me, every bone in thier legs get broken, there is blood everywhere and they also sometimes break Thier lower body. I mean it does depend so yeah. Sometimes they just break a foot and sometimes it's Thier whole body.

**Comment by DindinYT37** [comment]
> 
> > You guys have weird experiences, ~~this hasn't happened to me yet~~.
> > 
> > **Edit:**
> > It just happened to me, since I went on to test with a lot of humans. Though it happens rarely, it does happen; but I wouldn't consider it "fucking up their legs" since they can still stand and walk as usual (Tested on 1-2m height).
> > Note that it doesn't only happen on freshly spawned humans but also on some "older" humans.
> 
> When it happens to me, every bone in thier legs get broken, there is blood everywhere and they also sometimes break Thier lower body. I mean it does depend so yeah. Sometimes they just break a foot and sometimes it's Thier whole body.
> 

Have you tried testing it with higher physics iterations?

**Comment by Drogo-man** [comment]
> Have you tried testing it with higher physics iterations? 

I'm always at 128 iterations. I haven't tested it a lower iterations tho.

**Comment by mestiez** [comment]
I think this happens because they usually don't bend their knees when being dropped. Just like in real life, this is a terrible idea.
Should humans bend their knees slightly when falling? Should knees be less rigid?

**Comment by GitNeto** [comment]
Terrible idea as in less rigid knees should not be added? Youre to boss
zooi but considering most rag games have this knee thing, it would
significantly increase the immersiveness of the game. And it wouldnt even
be a big thing just a slight tweak in settings, or maybe im wrong idk.

zooi ***@***.***> schrieb am So., 15. Mai 2022, 13:10:

**Comment by GitNeto** [comment]
> I think this happens because they usually don't bend their knees when being dropped. Just like in real life, this is a terrible idea. Should humans bend their knees slightly when falling? Should knees be less rigid?

Terrible idea as in I won't even think about adding this, or? Considering the simplicity behind this ingame tweak, and the great immersiveness it could bring with it, it should definitely be considered. but you are the boss. Do as you please.

**Comment by mestiez** [comment]
Terrible idea as in landing with your legs fully straightened would be incredibly painful and dangerous.

**Comment by GitNeto** [comment]
> 

Ah okay wonderful, thanks for the clarification.
