### ISSUE TITLE
metal itens bending

### ISSUE THREAD

**Issue by birbhimself** [studio-minus/ppg-bugs-and-requests#1222]
**Feature description**
add an option that when you toggle it metal itens bend when really hot

**Feature purpose**
it would be really cool for blacksmithing

**Additional context**
please for gods sake make it an option or it will fuck most contraptions

**Comment by DindinYT37** [comment]
Basically duplicate of #659

**Comment by YourLocalPlonker** [comment]
how about metal bends not only if it is hot but also when it is normal temp just requires more force?

**Comment by DindinYT37** [comment]
> how about metal bends not only if it is hot but also when it is normal temp just requires more force?

It was already rejected...

**Comment by YourLocalPlonker** [comment]
> how about metal bends not only if it is hot but also when it is normal temp just requires more force?

what a shame but I understand that it would be a pain in the ass to code this
