### ISSUE TITLE
Ballast tank.

### ISSUE THREAD

**Issue by Drogo-man** [studio-minus/ppg-bugs-and-requests#1225]
**Feature description**
An object that floats, but will fill with water if submerged upon activation.

**Feature purpose**
It could be used for submarines and other sorts of watery stuff.

**Additional context**

**Comment by YourLocalPlonker** [comment]
Would be cool if there was a threshold you can set how much water it fills with

**Comment by ppgplayer** [comment]
yes 

also would be cool if there was a way to make an airtight container, but from what i've heard zooi doesn't wanna add water physics

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/168426981-719d950b-647d-461b-9190-98a65673798a.png)
This is a liquid canister. Its buoyancy depends on the amount of liquid inside.
