### ISSUE TITLE
Better Physics Engine, Because they usually go and explode

### ISSUE THREAD

**Issue by EverythingIsTakenAlready** [studio-minus/ppg-bugs-and-requests#1226]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by DindinYT37** [comment]
Please use the template.
