### ISSUE TITLE
Humand sounds / Screaming

### ISSUE THREAD

**Issue by Lennozeros** [studio-minus/ppg-bugs-and-requests#1232]
| What does it do? |

Well i think you know what i mean.
I would love an update where the people that you are playing with can scream if they get hurt or starting to make choking sounds when they get a knife in the chest. Or drowning sounds, screaming sounds when they fall or starting to laugh because of craziness when you kill someone infront of them. BUT you can turn the human sounds ON and OFF (You can edit every single sound) in the settings for people that find it annoying. It is turned OFF by default so people dont get "scared"

| Why? |

I just want them to have more feelings and to make the game sound more lively. I know that there is a mod for it but there are only like 5 sounds that arent really good...

dear,
Lennozeros

**Comment by DindinYT37** [comment]
Please use the template.

**Comment by DindinYT37** [comment]
The suggestion good I guess but I rather have it be off by default since this could seem not only annoying but also really creepy and weird to new users.

**Comment by Drogo-man** [comment]
MOD MOD MOD

**Comment by Lennozeros** [comment]
@DindinYT37 
Thats why i said that you can turn it OFF if its annoying. And i edited more text... for people that download the game for the first time have to turn it ON so they wont get "scared"
