### ISSUE TITLE
Change video on TV

### ISSUE THREAD

**Issue by 2ee4jnufew** [studio-minus/ppg-bugs-and-requests#1236]
**Feature description**
Ability to change video on TV.

**Feature purpose**

For example, in order for the video to be put in a folder or a link to a video / gif

**Comment by DindinYT37** [comment]
You're basically requesting for NSFW to be part of the PPG workshop.

**Comment by 2ee4jnufew** [comment]
> You're basically requesting for NSFW to be part of the PPG workshop.

Why? in many screenshots I would like to see interference on the TV and so on

**Comment by DindinYT37** [comment]
> > You're basically requesting for NSFW to be part of the PPG workshop.
> 
> Why? in many screenshots I would like to see interference on the TV and so on

If people can decide what video to put in and then upload it to the workshop, guess what the people will do with that opportunity.

**Comment by 2ee4jnufew** [comment]
> > > You're basically requesting for NSFW to be part of the PPG workshop.
> > 
> > 
> > Why? in many screenshots I would like to see interference on the TV and so on
> 
> If people can decide what video to put in and then upload it to the workshop, guess what the people will do with that opportunity.

What if there is no workshop?
