### ISSUE TITLE
Entities frozen with Rigidifier don't show up as blue anymore

### ISSUE THREAD

**Issue by Keyaura** [studio-minus/ppg-bugs-and-requests#1239]
When freezing an entity with the rigidifier, instead of turning blue like intended, their appearance doesn't change to blue, remaining as normal.
 
However, the rigifier still freezes entities and normal.

Can be reproduced by freezing an npc with the rigidifier.

## All loaded mods

	pipe-Ores & Gems-2807254006 v1.3 for game v1.23.9+
		Currently inactive

	zuccian-Symbiote Playground-local v1 for game v1.10+
		Currently inactive

	Geryfisz-Backrooms found footage-local v1.0 for game v1.22+
		Currently inactive

	Punkkinn-Warden Mod-2798981629 vv1.0 for game v1.23+
		Currently inactive

	Mishanya-The Ultimate Car Mod-2795171453 v0.6.2 for game v1.16+
		Currently inactive

	edolphin-Jerma985-2794179339 v1.0 for game v1.9+
		Currently inactive

	Fanboy#1000-Popular SCP's-2793790885 v1.0 for game v1.11
		Currently inactive

	Orsoniks / Navii-Reactive humans-2793371344 v1.0 for game v1.23+
		Currently inactive

	Cleveland Gaming-Donald Trump-2790404876 v1.1 for game v1.23.6
		Currently inactive

	Decibek-Rickrolling Mod-local v1.0 for game vany version
		Currently inactive

	Quickness-Military Truck-2783874579 v1.3.1 for game v1.23.7+
		Currently inactive

	miko.340-isaac-local v1.0 for game v1.15
		Currently inactive

	Aspa102-Favourites Category-2781168915 v1.0 for game v1.23+
		Currently inactive

	Dyadyushka Dyadya-SpawnableLift-2780861030 v1.0 for game v1.23+
		Currently inactive

	royalealbert27-Human with Changeable Feelings-local v1.0 for game v1.22+
		Currently inactive

	FredMichalBear-Lightberry the furry mod-local v1.0 for game v1.16+
		Currently inactive

	Quickness-Prison Bus-2776557560 v1.1 for game v1.22.3+
		Currently inactive

	Kor_BarBeQ-Test Dolls!-2776129502 v1.0 for game v1.19+
		Currently inactive

	Skeleboi-Mandela Catalogue but its People Playground-2774549424 v1.0 for game v1.22+
		Currently inactive

	Cleveland Gaming-Barack Obama-local v1.0 for game v1.11
		Currently inactive

	theimposterjake-Winning smile mod-2767969048 v1.0 for game v1.21
		Currently inactive

	Not XD booi-Volodimir Putin mod-2766223355 v1.0 for game v1.15
		Currently inactive

	DANGER-Ukraine-local vUkraine, what did you expect? for game v1.21
		Currently inactive

	Orsoniks / Navii-SimplePortals-2759460093 v1.0 for game v1.22+
		Currently inactive

	Dyadyushka Dyadya-Acid Sea-2759438689 v1.0 for game v1.22.3+
		Currently inactive

	Kor_BarBeQ-Superior Spiderman Mod-local v1.0 for game v1.19+
		Currently inactive

	ruslan_2k7-Corrupted Human Mod-2752371299 v1.0 for game v1.22.3
		Currently inactive

	AbsolutePug-Meme Animals Mod-2745397945 v1.1 for game v1.22.3
		Currently inactive

	01 Studios-Human Dynamic Emotions-2745225441 v1.0 for game v1.22+
		Currently inactive

	Nikivan-Spy Moyai-2744764459 v1.0 for game v1.22.3+
		Currently inactive

	AbsolutePug-Boneworks Pack: NPCs-2740924519 v1.2.0 for game v1.22.3
		Currently inactive

	Dyadyushka Dyadya-Uncharted Territory Portal-local v1.0 for game v1.11
		Currently inactive

	NutJobGames-Half Life-2732657475 v1.0 for game v1.15
		Currently inactive

	Archo-Tech-Construction Tools+-2729798028 v2.0 for game v1.22.3+
		Currently inactive

	Orsoniks / Navii-Wound Infections-2729065060 v1.0 for game v1.22+
		Currently inactive

	Dawid23 Gamer/Mapper-Human Skin Colors-2727004117 vv1.1.0 for game v1.22+
		Currently inactive

	Dawid23 Gamer-Dawid23 Gamer's Chemistry Mod-2721981192 vv1.1.0 for game v1.23.7+
		Currently inactive

	zooi-Buoyant-local v1.0 for game v1.22.4
		Currently inactive

	Streamed Hams-Weird Humans-2714221016 v1.0 for game v1.22.3
		Currently inactive

	Nev~u-Purple guy-local v1.4 for game v1.12+
		Currently inactive

	kirillX-Doll for tests 2-local v1.0 for game v1.15
		Currently inactive

	Slebbey-Black Hole Bomb Mod-local v1.22.3 for game v1.22.3
		Currently inactive

	Shlag-Shae D. Corp. and Korblox Inc. Mod-2711558334 v1.0 for game v1.22.2
		Currently inactive

	Polars Bear-Polars Bear's More Random Syringes-2711380012 v1.6 for game v1.22+
		Currently inactive
		Malfunctioning

	Aspa102-Limb Regrowth Syringe (Passive)-2708526361 v1.0 for game vpainfully amounts of pain
		Currently inactive

	Polars Bear-Pink Syringe Effects Syringes-2704189371 v1.0 for game v1.22+
		Currently inactive

	Polars Bear-Polars Bear's Custom Syringes'-2703885124 v1.0 for game v1.22+
		Currently inactive

	FredMichalBear-Prototype humans mod-2699827397 v1.0 for game v1.15
		Currently inactive

	ThatFNAFModDev--Freddy Fazbear's Pizzaria Building Kit!-local v1.0 for game v1.15
		Currently inactive

	Duxflavo-Hotline Miami pack-2696207908 v1.0 for game v1.22.3+
		Currently inactive

	Mishanya-Prop Mod-2696169016 v1.3 for game v1.22+
		Currently inactive

	kirillX-Prosthetics mod-local v1.0 for game v1.15
		Currently inactive

	ahlog ridaaaa-clash of clans elixir-local v0.69 for game vCoC enjoyers
		Currently inactive

	citler_the_cat-MilitaryMod Expansion:Russian Military-2682310490 v2.1 for game v1.21.2
		Currently inactive

	FredMichalBear-Big pixels protogen mod-local v1.0 for game v1.16+
		Currently inactive

	john-Gnome Chompski-local v1.0 for game v4.20
		Currently inactive

	Dawid23 Gamer-Evil Mod-2675959939 vv1.0.4 for game v1.23.7+
		Currently inactive

	pjstarr12-Social Credit Mod-2675378078 v1.02 for game v1.0+ i think
		Currently inactive

	InsanePyro-Extinction-local v1.0 for game v1.21+
		Currently inactive

	Xenon-Cyberpunk 2077 weapons mod-local v1.0 for game v1.22.3
		Currently inactive

	enlisted actor-More Humans Mod-2669494511 v1.0 for game v1.14+
		Currently inactive

	Leve-Infernal Skeleton-2668880197 v1.0 for game v1.22.2+
		Currently inactive

	JohnnyTaco-Puppet Master-2668334393 v1.70.7 for game v1.22.x
		Currently inactive

	FredMichalBear-Gentlemen humans mod-local v1.0 for game v1.15
		Currently inactive

	Talonphobia-Talon Zane's Marvelous Weapon Week II-local v1.0 for game v1.22.2+
		Currently inactive

	pjstarr12-Soul Mod-2661139744 v4.95 for game v1.0+ i think
		Currently inactive

	Talonphobia-Talon Zane's Marvelous Weapon Week I-2656268059 v1.0 for game v1.22.2+
		Currently inactive

	Pl4y3r D0G-GTA:SA Mod-2655470844 vALPHA v0.4 for game v1.22.2
		Currently inactive

	James Charles-A Syringe Mod-2655173462 v2.7 for game v1.22.3
		Currently inactive

	TastyPancake-ROBLOX Bloxy Cola-local v1.0 for game v1.22
		Currently inactive

	Ok_zyt-Melon Playground Melon Human-local v1.0 for game v1.15
		Currently inactive

	CTTC321-TRON:Legacy MOD-2647841832 v1.0 for game v1.20+
		Currently inactive

	kubason-Hazardous Enviourment Combat Unit Mod (HL1 Military)-2647625768 v1.0 for game v1.21.3
		Currently inactive

	Shrimpy dies-Extra Additions To Human Tiers-2647605381 vv4.4 for game v1.12+
		Currently inactive

	Orsoniks / Navii-Status Icons-2644689646 v0.1 for game v1.22
		Currently inactive

	RadioactiveE3-SCP: PPG Edition-2643873749 v4.0 for game v1.22+
		Currently inactive

	PersonMan65 (fix by olv)-A Handful of Wierd Syringes (ORIGINAL FIXED)-2642615529 v1.0 for game v1.22
		Currently inactive

	Kyrelink-Hats Mod REWORE-local v4.0 for game v1.23+
		Currently inactive

	blubssubs-Squid game mod-2612715780 v1.0 for game v1.11
		Currently inactive

	Nightzz-Item Plus-2612273009 v6.0 for game v1.21.x
		Currently inactive

	Mishanya-Functional Devices Mod-2605252227 v1.1 for game v1.22.3+
		Currently inactive

	Orsoniks-A Crap Ton Of Damage-2603531653 v0.1 for game v1.21.3
		Currently inactive

	Morzzic-Object Editor-2590195142 v1.3.1 for game v1.23+
		Currently inactive

	ahlad to the bone-skull stick shift-local v0.69 for game vskull stick shift
		Currently inactive

	onions-Headcrabs-2583003386 v1.3 for game v1.20
		Currently inactive

	Maxe-Detroit: Become Human-2571963895 v1.1 for game v1.19+
		Currently inactive

	cttc321-SUPER DROIDS MOD-2566959611 vv1.0 for game v1.13+
		Currently inactive

	zooi-Dead No Collide-local v1.0 for game v1.20
		Currently inactive

	YahyaK-YahyaK's Fallout Pack-local v1.0 for game v1.15
		Currently inactive

	Golden-Cyberpunk 2077 Trauma Medic Pack-local v1.0 for game v1.9+
		Currently inactive

	krzem-saddam hussein mod-local v1.0 for game v1.19.2
		Currently inactive

	Blunco-Gorse-2524339472 v1.0 for game v1.11
		Currently inactive

	Pumpkin-Simple Syringes Mod-2522356867 v2.2 for game v1.18+
		Currently inactive

	Mishanya-The Ultimate Human Mod-2516637907 v1.1 for game v1.21+
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently inactive

	Mishanya-Russian City Mod 2.0-local v0.1.2 for game v1.16+
		Currently inactive

	MR.REX-Emergency Siren-2509362434 v0.6 for game v1.21+
		Currently inactive

	bee queen-TF2 Mercenaries-local v1.0 for game v1.15
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently inactive

	shyguy85-Half Life 2 pack-local v1.0 for game v1.15
		Currently inactive

	Pumpkin-Quality of Life Items-2500516293 v1.7 for game v1.22.3
		Currently inactive

	Blocksify & Frevv-Blocksify's Crazy Syringes Mod-2498890172 v1,000,000 for game v1.18
		Currently inactive

	Skullex(jamesH_2), Aspa102, Kassjak-Scream mod-2494555615 v1.0 for game v1.11
		Currently inactive

	END-more android-2493105501 v1.1 for game v1.16+
		Currently inactive

	Quickness-Metal Things Mod-local v1.0 for game v1.17x
		Currently inactive

	Kubulll-Nuclear Playground-2484034390 v1.0 for game v1.21+
		Currently inactive

	Mishanya-Flags+-2472931413 v2.0 for game v1.22+
		Currently inactive

	Mishanya-Clothes Pack 2.0-local v2.0 for game v1.16+
		Currently inactive

	zooi-depletable engines-2463360042 v1.3 for game v1.19
		Currently inactive

	Talonphobia-Buff Human-2461523630 v1.0.2 for game v1.16.5
		Currently inactive

	Kris-Troll-2459979789 v2.0 for game v1.19
		Currently inactive

	Evalarian-Lawless - High Profile Operations-2457776308 v1.0 for game v1.16
		Currently inactive

	Aspa102-Tool Gun-2452959137 v1.0 for game v1.15+
		Currently inactive

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently inactive

	Mishanya-Colored Cars Mod-2444870694 v1.1 for game v1.16+
		Currently inactive

	Kyrelink and Quickness-The ULTIMATE Minecraft Mod-2442812460 v1.8 for game v1.23+
		Currently inactive

	Umbry Kid, Dexxiol & EyeSpy-People Life (Version 2.2)-2442226886 vbeta 2.2 public release for game v1.18
		Currently inactive

	Sҝữľľ-TrollFace Mod-local v1.0 for game v1.15x
		Currently inactive

	Talon Zane-Map Blocks-local v1.0 for game v1.7
		Currently inactive

	shyguy85-Half Life 1 pack-local v1.0 for game v1.15
		Currently inactive

	Mishanya-YouTube Buttons Mod-local v1.1.0 for game v1.7+
		Currently inactive

	G[DEATH]P-Fallout: New Vegas PPG Edition-2419282576 v1.0 for game v1.15+
		Currently inactive

	Mishanya-Police+-2416686384 v6.4 BETA for game v1.21.3+
		Currently inactive

	Pumpkin-Doors Mod-2400494139 v1.4 for game v1.15
		Currently inactive

	Mishany-Melee Weapons Mod-2389733225 v7.0 for game v1.13+
		Currently inactive

	jimmyl-Android Injectors-2381177128 v1.4 for game v1.12+
		Currently inactive

	Soiled Panties-CRT Televisions!-2379156287 v1.31 for game v1.18
		Currently inactive

	moonSIq-Secure. Contain. Protect [SCP MOD]-2361867196 v1.2 for game v1.12
		Currently inactive

	Your Local Home Invader-Dream-2357636207 v1.20.08 for game v1.11+
		Currently inactive

	jimmyl-Parts and Contraptions-2337159652 v3.9.5 for game v1.18+
		Currently inactive
		Malfunctioning

	[TSF] Life.exe-S.C.P.F. mod-2332568618 v1.0 for game v1.12+
		Currently inactive

	Alibarda-Human Tiers-2308911224 vv4.4 for game v1.12+
		Currently inactive

	YearsLater-The Wasteland-2287416870 v1 for game v1.11+
		Currently inactive

	Alibarda-PowersMod-2276255188 v1.9 for game v1.18+
		Currently inactive

	Talon Zane-Greenhammer-local v1.0 for game v1.12+
		Currently inactive

	Skittles-Skittle's Syringe Mod-2268097682 v1.4 for game v1.19+
		Currently inactive

	Teletubbie With A Shotgun-PPG Spy Mod-local v1.0.5 for game v1.9+
		Currently inactive

	Sir. Doggo-Construction Tools-local v1.0 for game v1.9
		Currently inactive

	weirdo-Chemical Warfare-2226697361 v2.0 for game v1.22.2+
		Currently inactive

	Golden-Hazmat Mod Remastered-2217857980 v1.3.1 for game v1.9+
		Currently inactive

	Azule-Minecraft Building System-2196354023 v1.8 for game v1.12+
		Currently inactive

	weirdo-Functioning Armor-2194511729 v3.0 for game v1.22.2+
		Currently inactive

	Scribble-Simple Blocks-local v1.0 for game v1.8.x
		Currently inactive

	zooi-Controllable anti-air cannon-2178648827 v1.2 for game v1.9.3
		Currently inactive

	zooi and Talon-Minesweeper-2176782485 v1.1 for game v1.9.3
		Currently inactive

	CyberPlays26-Research Facility Mod-local v1.0 for game v1.9+
		Currently inactive

	Morzzic-Russian Roulette Mod-2173352550 v1.1 for game v1.9+
		Currently inactive

	LijmPistool#0021-FNAF Mod-2172529351 v0.9.0 for game v1.22+
		Currently inactive

	odriw-Half-Life PPG-2172043870 v1.0 for game v1.9
		Currently inactive

	Sv1t-scuffed hl1 characters mod-2170013502 v1.3 for game v1.9.4
		Currently inactive

	Sororfortuna-Soror's NPC Pack-2169243678 v11.0 for game v1.19.2
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently inactive

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	Hewaki-Household Mod-2159368880 v1.3 for game v1.8.x
		Currently inactive

	(RU)Enot builder-Construction kit V0.9.5-2151076041 vV0.9.5 for game v1.8x
		Currently inactive

	Pigeom-Hotline Miami Mod-2146651953 v0.2 for game v1.8
		Currently inactive

	Kyrelink-Half Life 2 weapons-2140530282 v1.6 for game v1.7
		Currently inactive

	kortl-COMBAT Props Pack-local v1.0 for game v1.7.x
		Currently inactive

	BBQGiraffe-Doom weapons pack-2137895715 v3.0 for game v1.8.x
		Currently inactive

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently inactive

	Talon Zane-The Greenbrick Mod-2120736639 v1.8 for game v1.12.2+
		Currently inactive

**System info 
 - Operating system: Windows 10 Pro x64 version 21H2
 - Game version: 1.24 preview (64 bit)
 - GPU: Integrated graphics
 - CPU: AMD 5600G

**Additional notes**

**Comment by 2ee4jnufew** [comment]
Are you sure? Any bug can also be due to the mod

**Comment by Keyaura** [comment]
deleted all data in the compiled mods folder, with the bug still persisting.

**Comment by Keyaura** [comment]
![image](https://user-images.githubusercontent.com/105600619/168486513-662b6e05-7e87-4509-9a47-0a1693824b09.png)
my exported game data as of now

**Comment by mestiez** [comment]
Fixed

**Comment by Drogo-man** [comment]
Holy smokes, that's alot of mods. How is your computer even running the game at this point? My PC has a seizure when i install more then 20 large mods.

**Comment by DindinYT37** [comment]
> Holy smokes, that's alot of mods. How is your computer even running the game at this point? My PC has a seizure when i install more then 20 large mods.

To be fair, those are rookie numbers.
