### ISSUE TITLE
Slider both activations

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#124]
**Feature description**
Activating one part of a slider should also activate the other part, as if it was one long object. 

**Feature purpose**
This could be used as basically an extendable activation wire without using a radio.

**Additional context**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/69184577/130353811-ddfa0826-bb3e-487e-9d5d-936f76052df1.gif)

**Comment by mestiez** [comment]
This could destroy contraptions that relied on their seperation

**Comment by UniDuki** [comment]
I feel like some way to have an extendable activation wire would be useful because radios work but only when there is one of the same contraptions at a time.
Maybe an activation "wire" that has no actual wire like phase links.

**Comment by mestiez** [comment]
propagation links would be useful for more experienced players for sure. im a bit worried the link tool menu will become overcrowded with links for each channel though. either way, the slider thing is rejected. propagation links is another story :)
