### ISSUE TITLE
Cauterization of wounds

### ISSUE THREAD

**Issue by TheLivingM3m3** [studio-minus/ppg-bugs-and-requests#1241]
**Feature description**
A new mechanic when objects are at a heat of 300 - 500 degrees Celsius and come in contact with human / gorse skin; the wound should be cauterized with no blood loss. If a sharp object pierces a human / gorse at these heats when you pull the object out the wound will be closed.

**Feature purpose**
This could be used as a new method to treat wounds by cauterization instead of bandaging or using coagulation syringes.

**Comment by DindinYT37** [comment]
Did you close this because you noticed it already happens?

**Comment by TheLivingM3m3** [comment]
> Did you close this because you noticed it already happens?

I did after the fact but I tested before and found it inconsistent so I didn't know whether it was a bug or not

**Comment by DindinYT37** [comment]
> > Did you close this because you noticed it already happens?
> 
> I did after the fact but I tested before and found it inconsistent so I didn't know whether it was a bug or not

We will see since zooi will relabel this as a bug if it is actually a bug.
