### ISSUE TITLE
Option to change chance of brain matter flying out during headshot

### ISSUE THREAD

**Issue by TheLivingM3m3** [studio-minus/ppg-bugs-and-requests#1242]
**Feature description**
A setting to increase or decrease / disable the chance that brain matter flies out during a headshot. Or a zone in the head (above nose) that has a 100% chance of shooting brain out.

**Feature purpose**
For cinematic purposes and cool effect.

**Comment by DindinYT37** [comment]
Similar/Related to #1218.
