### ISSUE TITLE
humans that survive headshots have flucuating blood amounts

### ISSUE THREAD

**Issue by BBQGiraffe** [studio-minus/ppg-bugs-and-requests#1245]
**Describe the bug**
if you shoot a human in the head and the human survives, the inspector has a chance to show the blood amount flickering between baseline and slightly higher(in my testing this is 102 - 106%), it only flickers to the higher amount for a frame or two, this ceases when you bandage the wound, I have not been able to replicate this with stab wounds

**Mod list**
None

**System info**
 - Operating system: Linux Mint (Debian branch)
 - Game version: 1.24 Preview
 - GPU: GTX 1050 TI
 - CPU: Ryzen 3 2200G

**Comment by mestiez** [comment]
I can't reproduce this

**Comment by mestiez** [comment]
are you on preview 4?

**Comment by BBQGiraffe** [comment]
yep

**Comment by fhgb54643689** [comment]
i am getting the same problem its like the blood in the brain is moving back and fourth from another limb

**Comment by BBQGiraffe** [comment]
after further testing this seems to happen most often when you using the Handcannon and shoot the lower area of the head at a straight angle from a meter or two away

**Comment by mestiez** [comment]
I've encountered flickering between 4% and 8% blood amount & pressure when shot in the arm

**Comment by mestiez** [comment]
Okay I think I fixed it
