### ISSUE TITLE
Blood Spawning When Person Has No Blood / Too much blood

### ISSUE THREAD

**Issue by RadialVolcano27** [studio-minus/ppg-bugs-and-requests#1246]
The first bug is that when someone has no blood and their limbs get crushed, more blood appears. All you have to do is take out all their blood with a tank and then smash them with a 1 ton weight to make the limbs explode and BOOM! More blood. 

The other issue is related to people smacking into things. If you smack a person into the ground over and over, you could probably paint the entire floor of the default map red.

I have a lot of mods but found that nothing changes. My pc can run the game find but I believe I have an i5-3560 2.5 Hz or something with 16 gb RAM

**Comment by mestiez** [comment]
I can't reproduce either of these issues....

**Comment by Drogo-man** [comment]
> I can't reproduce either of these issues....

I think he means the gore splatter that happens when shot/crushed. It still appears when the person has no blood.

**Comment by mestiez** [comment]
Idk what to do with this issue. Please follow the template carefully next time and try not to group issues.
