### ISSUE TITLE
Option to instantly put out all fire and reset the heat of items.

### ISSUE THREAD

**Issue by TamasB14** [studio-minus/ppg-bugs-and-requests#125]
An option to put out everything that is burning on the map and also reset the heat of the items. (Similiar to clear debris)
This could solve many problems such as never ending fires.

I'm sure everybody who loves playing with explosives would like that. I often get problems that after few "airstrikes" I heat up the map so much Humans just burn at spawning. I manually have to cool down the whole place to continue my work.

**Comment by xpdatabase11** [comment]
You can do that by click and holding your LMB, dragging the box over every object in the scene. Then click extinquish.

**Comment by TamasB14** [comment]
> You can do that by click and holding your LMB, dragging the box over every object in the scene. Then right click and extinquish.

Indeed, but if I heat up the ground of the map or a stick of iron to like 9999 C degree, how will I be able to instantly cool it? Sometimes I cause never ending fires because I heated one iron bar up so much I can't extinguish the rest and I can't cool it down.

**Comment by mestiez** [comment]
> > You can do that by click and holding your LMB, dragging the box over every object in the scene. Then right click and extinquish.
> 
> Indeed, but if I heat up the ground of the map or a stick of iron to like 9999 C degree, how will I be able to instantly cool it? Sometimes I cause never ending fires because I heated one iron bar up so much I can't extinguish the rest and I can't cool it down.

You cannot heat up the map floor. If you can, you are on a modded map which I don't consider.

**Comment by TamasB14** [comment]
> > > You can do that by click and holding your LMB, dragging the box over every object in the scene. Then right click and extinquish.
> > 
> > 
> > Indeed, but if I heat up the ground of the map or a stick of iron to like 9999 C degree, how will I be able to instantly cool it? Sometimes I cause never ending fires because I heated one iron bar up so much I can't extinguish the rest and I can't cool it down.
> 
> You cannot heat up the map floor. If you can, you are on a modded map which I don't consider.

I also said "stick of iron", and I can't cool multiple objects down.
