### ISSUE TITLE
toggle new gore shaders

### ISSUE THREAD

**Issue by imheretoreportbugs** [studio-minus/ppg-bugs-and-requests#1250]
you should make the gore shaders content togglable in the settings (when you release it) because sometimes people like the old stuff

**Comment by DindinYT37** [comment]
Please use the template.

**Comment by mestiez** [comment]
i prefer the new look

**Comment by mestiez** [comment]
nevermind i understand if people want to revert to how things were

**Comment by 2ee4jnufew** [comment]
Template?

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/168883105-df26b66f-0881-4339-8110-f110296d3ef1.png)

**Comment by DindinYT37** [comment]
> ![image](https://user-images.githubusercontent.com/32131519/168883105-df26b66f-0881-4339-8110-f110296d3ef1.png)

New one somehow looks way more brutal...
