### ISSUE TITLE
3 Suggestions

### ISSUE THREAD

**Issue by slaterrr** [studio-minus/ppg-bugs-and-requests#1252]
Make a customizable tv, so you can play youtube videos on it and stuff.

Make an ice block, which is slidey.

Make it so you can make a conveyer belt go backwards with a red signal

**Comment by DindinYT37** [comment]
Please use the template and don't multi-request.

**Comment by slaterrr** [comment]
> Please use the template and don't multi-request.

who are you

**Comment by mestiez** [comment]
Please seperate your feature requests into seperate issues.
