### ISSUE TITLE
fix Instance.fixcolliders();

### ISSUE THREAD

**Issue by birbhimself** [studio-minus/ppg-bugs-and-requests#1254]
make it so that fixcolliders can fix concave hitboxes too, it would help alot to make things realistic

i want that in the game because i was making a sword and stuff wasnt working because fixcolliders is bad

**Comment by mestiez** [comment]
concave colliders should be manually created. box by box

i guess i could write an algorithm that checks the sprite contents (without being slow, somehow) and creates a collider, but this would be an unnecessary amount of work for the computer.
