### ISSUE TITLE
Indestructible non-conductive wire

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#126]
**Feature description**
An indestructible non-conductive wire named **cable**

**Feature purpose**
There's an indestructible conductive wire,
a destructible conductive wire,
and a destructible non-conductive wire

So where is the indestructible non-conductive wire.

**Comment by StealthDrifter** [comment]
blood vessel wire?

**Comment by Km3red** [comment]
> blood vessel wire?

That still has a purpose. we need something that serves no purpose except for being a cable, so we don't have anything interfering

**Comment by UniDuki** [comment]
And blood vessel wires cannot connect to the back wall

**Comment by mestiez** [comment]
> And blood vessel wires cannot connect to the back wall

Good point.
