### ISSUE TITLE
Infinite sources for flasks

### ISSUE THREAD

**Issue by StealthDrifter** [studio-minus/ppg-bugs-and-requests#127]
Kind of like how you can enable and disable infinite sources on syringes, you should also be able to do it with the flasks.

**Comment by unkown367** [comment]
this is like #120 but for flasks

**Comment by mestiez** [comment]
correct and it it has the same problem

**Comment by StealthDrifter** [comment]
> correct and it it has the same problem

I meant of the default flasks, not custom flasks, like how the default syringes have infinite sources but not custom syringes
