### ISSUE TITLE
Blood pressure

### ISSUE THREAD

**Issue by Theklapek** [studio-minus/ppg-bugs-and-requests#1276]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

New mechanics: 
-More blood in human body = Higher blood pressure

-People die when they have high blood pressure

-People will explode with too high blood pressure

**Feature purpose**

The game will be more realistic

**Additional context**

**Comment by DindinYT37** [comment]
Blood pressure already exists; Use the template; Remove the templates' placeholders when using it.

**Comment by Theklapek** [comment]
> Blood pressure already exists and does quite literally what you described. Also, please use the template and remove the templates' placeholders when using it.

![obraz_2022-05-16_223339981](https://user-images.githubusercontent.com/93428290/168677898-4722ee7f-80e2-4d7a-84f7-1436a0e46884.png)
No, he is alive with almost 500% blood amount and still have normal blood pressure

**Comment by DindinYT37** [comment]
> > Blood pressure already exists and does quite literally what you described. Also, please use the template and remove the templates' placeholders when using it.
> 
> ![obraz_2022-05-16_223339981](https://user-images.githubusercontent.com/93428290/168677898-4722ee7f-80e2-4d7a-84f7-1436a0e46884.png) No, he is alive with almost 500% blood amount and still have normal blood pressure



> > Blood pressure already exists and does quite literally what you described. Also, please use the template and remove the templates' placeholders when using it.
> 
> ![obraz_2022-05-16_223339981](https://user-images.githubusercontent.com/93428290/168677898-4722ee7f-80e2-4d7a-84f7-1436a0e46884.png) No, he is alive with almost 500% blood amount and still have normal blood pressure

That's the only thing in your list that isn't in the game...

**Comment by Theklapek** [comment]
> That's the only thing in your list that isn't in the game...

,,-More blood in human body = Higher blood pressure" - He have more blood and still same blood pressure

,,-People die when they have high blood pressure" and  ,,-People will explode with too high blood pressure"  - He is alive 

How it is only thing that isn't in game?

**Comment by DindinYT37** [comment]
> -More blood in human body = Higher blood pressure
>
>-People die when they have high blood pressure
>
>-People will explode with too high blood pressure

People die when they have high blood pressure and explode with too high blood pressure. They die **because** they explode, and it's this is a setting.

**Comment by DindinYT37** [comment]
> ![Screenshot (114)](https://user-images.githubusercontent.com/102178009/168862139-9f2afea4-8069-400d-92f9-540852138674.png)
> 
> ...

So what part about "it's a setting but it may have also been completely removed from the game" have you not understood?
