### ISSUE TITLE
Something that may deliver more reponsive feedback for whenever you shoot an creature/human..

### ISSUE THREAD

**Issue by Nunane** [studio-minus/ppg-bugs-and-requests#1277]
So here's what I thought would be a great idea for the game whenever you shoot someone you'll hear the bullets going through their flesh

The purpose of this feature is for the shooting combat to be more satisfying and impacting
Whenever you shoot someone you hear nothing, well maybe when you blow their brains out..
But that doesn't count, so.. Sound effects for that would be nice.

**Comment by Drogo-man** [comment]
Its already exists
