### ISSUE TITLE
People on fire to be extinguished in water.

### ISSUE THREAD

**Issue by howlzy** [studio-minus/ppg-bugs-and-requests#1287]
This is a game mechanic.

Pretty simple, I've just noticed when playing that if a dump someone who is ignited into the water they aren't extinguished, so they stay on fire while submerged. I'm not sure if it's a bug.

**Comment by DindinYT37** [comment]
They get extinguished though?

**Comment by howlzy** [comment]
Oh sorry I think you're right.
