### ISSUE TITLE
Activation Transformer only outputs on green channel

### ISSUE THREAD

**Issue by Tinotin1** [studio-minus/ppg-bugs-and-requests#129]
**Describe the bug**
I don't know if this is a bug or not, but the activation transformer only outputs on the green channel.

**Clearly describe how to reproduce the bug**
1. Attach generator to activation transformer
2. Attach red or blue propagation wire to anything
3. Activate generator

**Mod list**
None

**System info**
 - Operating system: Windows 10 Build 19042
 - Game version: 1.21.2 (64 bit)
 - GPU: GeForce GTX 1660
 - CPU: Intel i5-9400f

**Comment by mestiez** [comment]
Yes definitely a bug. Fixed :)
