### ISSUE TITLE
humans bleed out in seconds when shot

### ISSUE THREAD

**Issue by BBQGiraffe** [studio-minus/ppg-bugs-and-requests#1298]
**Describe the bug**
humans are completely emptied of blood in a couple seconds when shot

**Clearly describe how to reproduce the bug**
shoot a guy, this happens with any limb

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Linux Mint(Debian Branch)
 - Game version: 1.24 Beta 7

**Comment by Drogo-man** [comment]
Yeah, that's why guns are so deadly. You bleed out pretty quickly when you have a giant hole in or near a mayor artery or organ.

**Comment by Drogo-man** [comment]
Okay, I checked it out, and it's VERY fast. They pretty much instantly die.
