### ISSUE TITLE
Hovercraft still convey on conveyor belts

### ISSUE THREAD

**Issue by Km3red** [studio-minus/ppg-bugs-and-requests#130]
**Describe the bug**
Title says it all, despite hovercrafts hovering off the ground, they still convey or are moved along when on conveyer belts

**Clearly describe how to reproduce the bug**
Its simple, 1. put a hovercraft on a line of conveyer belts 2. activate the conveyer belts.

**Mod list**
Dead no-collide (disabled)
Liquid related machinery (disabled)
quick right click options (disabled)
wheelchair (disabled)
Flipping heck (disabled) 

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: Latest release (1.21.2)
 - GPU: Nvidia GeForce 3060 laptop gpu
 - CPU: 11th gen intel core 17-11800h 2.30GHz

**Additional notes**
Hover thrusters also appear to move erratically and randomly when on conveyer belts, I don't know if this is a bug or not however

**Comment by Tinotin1** [comment]
This is probably because of the circle colliders on the conveyor belt. It doesn't use a box collider like you would think.

**Comment by mestiez** [comment]
Fixed :)
