### ISSUE TITLE
Detectors send signals when broken

### ISSUE THREAD

**Issue by Trevor-01** [studio-minus/ppg-bugs-and-requests#1304]
[](url)**Describe the bug**
When a detector is on and sending an activation signal, if broke, it will continue sending the signal.

**Clearly describe how to reproduce the bug**
Get any detector (preferably an anything detector), and have it be detecting something. Connect it to a flamethrower using an activation wire. Destroy the detector with a gun and the flamethrower will still be shooting fire.
**Mod list**
N/A

**System info**
 - Operating system: Windows 11
 - Game version: 1.23.9
 - GPU: RTX 2060
 - CPU: I-5

**Additional notes**
![20220518174627_1](https://user-images.githubusercontent.com/98299435/169174321-52c4a68e-d5f0-49d1-9b45-8b3be19ad8be.jpg)

**Comment by mestiez** [comment]
fixed :)
