### ISSUE TITLE
unpredictable behaviour when connecting a dying human to an alive human while using syringes

### ISSUE THREAD

**Issue by BBQGiraffe** [studio-minus/ppg-bugs-and-requests#1305]
**Describe the bug**
connecting a dying human to a living human and then using syringes will cause unpredictable behavior 

**Clearly describe how to reproduce the bug**

1. spawn two humans, A and B
2. Stop A's heart
3. while A is dying, Connect a blood vessel from A to B and another from B to A (direction is important)
    * A will now use B's blood pressure to stay alive
4. inject either human with whatever syringes you want

this will cause strange behaviors
* wildly fluctuating blood amounts and blood being brought into existence
    (ex: B will have 400% blood and A will have 40% or all of B's blood will transfer to A)
* blood vessels start to glow incredibly bright

**Mod list**

None
**System info**
 - Operating system: Linux Mint (Debian Branch) 
 - Game version: 1.24 preview 8
 
![image](https://user-images.githubusercontent.com/45021140/169174656-40276ead-65e3-476d-9a15-d1fdaf7b8945.png)

**Comment by DindinYT37** [comment]
I don't know if this was fixed but I had this happen on several occasions, though with one human and detached limbs.

**Comment by BBQGiraffe** [comment]
> I can't reproduce this in the unreleased version I have. Did I fix this bug by accident?

possibly? I've done that before a few times
