### ISSUE TITLE
The chainsaw doesn't chainsaw

### ISSUE THREAD

**Issue by 404CoderNotFound** [studio-minus/ppg-bugs-and-requests#1308]
**Describe the bug**
The chainsaw doesn't create any wounds, just a lot of bleeding. It's also very hard to remove limbs with the chainsaw now.

**Clearly describe how to reproduce the bug**
1: Open PPG in the latest 1.24 preview.
2: Spawn a human.
3: Spawn a chainsaw.
4: Go to town.

**Mod list**
_See attachment_

**System info (please complete the following information)**
_See attachment_

**Additional notes**
_See attachment
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8726145/exported.game.debug.info.md)
_

**Comment by mestiez** [comment]
fixed
