### ISSUE TITLE
More bell variety or universal bell

### ISSUE THREAD

**Issue by JohnVcav** [studio-minus/ppg-bugs-and-requests#131]
**|Feature description|**

Possibly adding bells from A1 to C6, or a universal bell that can be assigned a note from A0 to C8.

**|Feature purpose|**

although Bells do already exist in the game, I find it extremely limited to make most songs with the notes that currently exists.

**|Additional context|**

a universal bell would replace the current ones and let you choose a note from the right click menu, and as I see it there are a 
couple options for such a menu;

1. show a Labeled Piano with keys A0 to C6/C8

2. have the current note in the center with arrows in each side 

3. a scroll list

There might be more ways, but I'm no professional.

thanks for coming to my ted talk

**Comment by mestiez** [comment]
I love the piano menu idea, this is great

**Comment by JohnVcav** [comment]
Thank you very much!
 finding unusual games to play music in is kind of a interest for me, so I'm hoping you would consider adding it if not too difficult!

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/130660582-a45b8f3b-4b1d-44a7-b45f-af9660888965.png)

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/130660650-b0dc884b-faa0-46b2-accc-a94c17e04c0e.png)
Detail view shows the bell note. (Should it say both C♯ and D♭ or just one of them?)

**Comment by JohnVcav** [comment]
I'm assuming that since C# and D-flat are the same(on a piano) having both might clutter the UI
