### ISSUE TITLE
blood circulation is really really bad

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#1312]
**Describe the bug**
the circulation in creatures is extremely bad to the point i cannot even revive them with the mending syringe and defib

**Clearly describe how to reproduce the bug**
1. shoot the human a lot till its dead and has no blood
2. stop all the bleeding
3. give the human a whole blood tanks worth of blood
4. inject mending syringe
5. use the defib to revive it and it wont come back half the time because the blood pressure is at around 10%

**Mod list**
None 

**System info (please complete the following information)**
 - Operating system: windows 11
 - Game version: 1.24 beta
 - GPU: GTX 1650 Super
 - CPU: intel i5

**Additional notes**

**Comment by 404CoderNotFound** [comment]
thats because that's how dying works...? just use the life syringe smh....

**Comment by fhgb54643689** [comment]
> thats because that's how dying works...? just use the life syringe smh....

thats boring as fuck

**Comment by mestiez** [comment]
I tested the circulation system and out of the problems it has, effective circulation isn't one of them

**Comment by fhgb54643689** [comment]
> I tested the circulation system and out of the problems it has, effective circulation isn't one of them

then what are the problems not allowing me to revive humans without life syringes then?
