### ISSUE TITLE
Blood cirulation broken

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#1313]
**Describe the bug**
Blood circulation broken

**Clearly describe how to reproduce the bug**
Drain some blood from human head and than inspect it. Blood is not circulating at all.

**Mod list**
No

**System info (please complete the following information)**
    Operating system: Win 10
    Game version: 1.23 beta, preview 15
    GPU: 750 ti
    CPU: Intel Core i5-4590 3.30GHz

**Comment by mestiez** [comment]
youre in 1.23 preview 15? in any case, this is no longer the case in 1.24

**Comment by fhgb54643689** [comment]
> youre in 1.23 preview 15? in any case, this is no longer the case in 1.24

blood is not moving from the head 
![image](https://user-images.githubusercontent.com/46871745/169398971-9223c87a-a7ae-4925-a8b8-2aaf9d2e9859.png)

**Comment by DindinYT37** [comment]
> > youre in 1.23 preview 15? in any case, this is no longer the case in 1.24
> 
> blood is not moving from the head ![image](https://user-images.githubusercontent.com/46871745/169398971-9223c87a-a7ae-4925-a8b8-2aaf9d2e9859.png)

...are you still in 1.23 preview 15?

**Comment by fhgb54643689** [comment]
> > > youre in 1.23 preview 15? in any case, this is no longer the case in 1.24
> > 
> > 
> > blood is not moving from the head ![image](https://user-images.githubusercontent.com/46871745/169398971-9223c87a-a7ae-4925-a8b8-2aaf9d2e9859.png)
> 
> ...are you still in 1.23 preview 15?

No.

**Comment by mestiez** [comment]
You should really put the correct version in the version field next time
