### ISSUE TITLE
Incorrect sub-tool order in tool menu

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#132]
## **Feature description**
Change order of propagation wires

## **Feature purpose**
Propagation wires are in an order that makes no sense to me.

**Current order:**
1. Green propagation wire
2. Green destructible propagation wire
3. Red destructible propagation wire
4. Blue destructible propagation wire
5. Red propagation wire
6. Blue propagation wire

**Better Order**:
1. Green propagation wire
2. Red propagation wire
3. Blue propagation wire
4. Green destructible propagation wire
5. Red destructible propagation wire
6. Blue destructible propagation wire

### **Additional notes**
I'd call this a bug but I'm marking it as a feature request

**Comment by mestiez** [comment]
That is not the order of the wires on any of my installations? Do you have any mods enabled?

**Comment by UniDuki** [comment]
I mean when you press number 4 to get to the 4th tool. Then if you press 4 again it will switch to the next propagation wire in the list, and then if you press it again it will go to the next and so on.

**Comment by UniDuki** [comment]
I don't know how to use words so this video might help explain what I mean?
https://youtu.be/YHHkVxWIkjU

**Comment by mestiez** [comment]
Oh I see, I'll work on this

**Comment by mestiez** [comment]
Fixed :)
