### ISSUE TITLE
humans going a really weird brown/purple colour

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#1324]
**Describe the bug**
after a human has been shot a bunch then revived with a reconstructor they start looking like this over a little time 
![image](https://user-images.githubusercontent.com/46871745/169618378-ee9e0eef-cb5b-4715-9d74-40bce0676ec3.png)

**Clearly describe how to reproduce the bug**
1. shoot the shit out of a human with a assault rifle
2. revive them with a reconstructor  and wait a little bit

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: windows 11
 - Game version: 1.24 beta preview 10
 - GPU: GTX 1650 SUPER
 - CPU: intel i5

**Additional notes**
i am unsure if this is a bug or not

**Comment by DindinYT37** [comment]
Isn't that just them rotting?

**Comment by fhgb54643689** [comment]
> Isn't that just them rotting?

it actually isnt because they have no rotting percentage

**Comment by mestiez** [comment]
this is just the bullet wounds progressing. the reconstructor doesn't visually heal wounds so this will stay visible

**Comment by fhgb54643689** [comment]
> this is just the bullet wounds progressing. the reconstructor doesn't visually heal wounds so this will stay visible

do they heal back to normal over time?

**Comment by mestiez** [comment]
eventually yes, but you need to keep them alive
