### ISSUE TITLE
Realistic Water

### ISSUE THREAD

**Issue by ElGuapoSapo** [studio-minus/ppg-bugs-and-requests#1325]
Realistic Water would basically make it to where water doesn't phase through objects, as an example, if I sunk a box underwater the interior would remain dry.

This would make make water vehicles more challenging to create and allow for more practical submarines to be created, It would also allow for ships and other craft of the sort to sink, rather than just fall apart.

**Comment by DindinYT37** [comment]
Water physics have already been said several times to not be added; this was already requested and rejected several times.
