### ISSUE TITLE
life syringe melting people

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#1327]
**Describe the bug**
the life syringe after being injected into a person causes their skin to change to the flesh layer like this 
![image](https://user-images.githubusercontent.com/46871745/169625508-d497ea28-5c25-4b5f-a3c5-2327e9bd6089.png)

**Clearly describe how to reproduce the bug**
reproducing this is somewhat difficult but the easiest and most consistent for me is shooting them a lot then injecting them with the life syringe

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: windows 11
 - Game version: 1.24 preview 10
 - GPU: GTX 1650 SUPER
 - CPU: intel i5

**Additional notes**
this is the same as #1323 but a lot more clear

**Comment by PossiblyRemember** [comment]
Something like this seems to happen with androids where the skin layer seems to be removed after being shocked
![image](https://user-images.githubusercontent.com/105954143/169630817-6ddc31f8-8eba-40f9-b181-37e2836b5b7a.png)

**Comment by mestiez** [comment]
fixed
