### ISSUE TITLE
Regeneration turn human flesh into shit

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#1336]
**Describe the bug**
Regeneration(slowly wound healing or life syringe) have a chance to melt human flesh

**Clearly describe how to reproduce the bug**
Stab/shoot human and wait/inject life syringe. More wound - more chance.

**Mod list**
No

**System info (please complete the following information)**
Operating system: Win 10
Game version: 1.24 preview 12
GPU: 750 ti
CPU: Intel Core i5-4590 3.30GHz

**Additional notes**
![изображение](https://user-images.githubusercontent.com/89081329/169652581-61aa526d-ed2b-41a3-8da6-c0fa7afd02c2.png)

**Comment by PossiblyRemember** [comment]
this seems pretty much the same as issue #1327

**Comment by mestiez** [comment]
duplicate
