### ISSUE TITLE
Cannot save contraptions at all for some reason. (1.24 PREVIEW)

### ISSUE THREAD

**Issue by nourelar** [studio-minus/ppg-bugs-and-requests#1338]
**Describe the bug**
Cannot save contraptions at all for some reason.

**Clearly describe how to reproduce the bug**
Step 1. create literally anything
Step 2. save

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: Windows 10 
 - Game version: 1.24 preview
 - GPU: Intel HD Graphics 4000
 - CPU: Intel i7-3770

**Additional notes**

**Comment by DindinYT37** [comment]
So what about mods?

**Comment by mestiez** [comment]
can only reproduce in an old version of the preview, which was already fixed
