### ISSUE TITLE
Map Editor

### ISSUE THREAD

**Issue by mewhenthewhenithewhen** [studio-minus/ppg-bugs-and-requests#1348]
Basically a map editor similar to like Stick Fight: The Game or BattleBlock Theater
A much more conventional way to create maps and upload them to the Steam Workshop with their own category (kind of like the Mods section), where you can add things like the vent covers, elevator, and maybe if implementable, custom doors or functions (ex. A door thats powered by a liquid detector when it's filled with Nitroglycerin, or just a basic button door). When custom maps first started coming out I saw a lot of potential in it, and I feel like it would be a good idea to add in because it might bring map makers to the game.

Convenient, Conventional, Simple mapping
With an easier way to make maps, creating them would actually be somewhat better since you wouldn't have to freeze and resize hundreds of random props from the spawnlist, downloading roughly 4 mods just to get the props you want. Plus, it would cause less performance drops if it was just there, instead of the floor being made of a shit ton of boulders and metal blocks.

Map Support
idk I just like custom maps, they looked pretty cool lol

**Comment by DindinYT37** [comment]
This was already confirmed long ago...

**Comment by mewhenthewhenithewhen** [comment]
i probably forgot it was confirmed or something, i havent kept up with ppg news besides some updates

**Comment by fishefishe** [comment]
> This was already confirmed long ago...

i didnt know
