### ISSUE TITLE
heart stopped

### ISSUE THREAD

**Issue by MrHushPPG** [studio-minus/ppg-bugs-and-requests#1350]
**Describe the bug** 
As soon as a human spawned at the location, the heart immediately stops

**Clearly describe how to reproduce the bug**
Start the game and spawn human

**Mod list**
Mods deactivated

**System info (please complete the following information)**
 - Operating system: windows
 - Game version: 1.24.1
 - GPU:
 - CPU:

![mdev52AX840yOJ31td-CCfQFQ_hUVoMdhZ0cttwHa2eip2udlE_gZdr4G3EpKTuiHziJshA5p0LL-7_wRShqeiqd](https://user-images.githubusercontent.com/106017720/169694573-d1199b63-17b0-425e-90a5-e376a0bb7039.jpg)
![Put3VPiT5ttHvzfZEj9eUQODiiIAep1mb5GNh5D3x5JxQNcw2nhvJb37z9K5EU1TQ0MetU8jw_2Zcoqcd4euB_QD](https://user-images.githubusercontent.com/106017720/169694574-af387a67-b9a2-4cd2-99c8-9a82778e5169.jpg)

**Additional notes**

**Comment by DindinYT37** [comment]
Personally, I think that the color of "heart stopped" seems to be more desaturated than usual and why would the Human still be alive if his heart stopped? I suggest checking for mods and/or validating your steam files.

**Comment by MrHushPPG** [comment]
On your recommendation, I tried disabling mods. Did not help.[image:
image.png]


вс, 22 мая 2022 г. в 17:27, DindinYT37 ***@***.***>:

**Comment by MrHushPPG** [comment]
Thank you very much for solving my problem!

вс, 22 мая 2022 г., 17:27 DindinYT37 ***@***.***>:
