### ISSUE TITLE
Tempered glass bug

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1352]
**Describe the bug**
Tempered glass still exists after breaking

**Clearly describe how to reproduce the bug**
Step 1: Spawn tempered glass
Step 2: Break tempered glass
Step 3: Press Z
Step 4: See that tempered glass has been deleted (even though it doesnt exist anymore)

**Mod list**
People Playground 3D (inactive)
flipping heck (inactive)

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.24.1
 - GPU: RX 470 8GB
 - CPU: Intel Xeon CPU E3-1230 3.20 GH

**Additional notes**
Kinda related to #193

**Comment by mestiez** [comment]
fixed
