### ISSUE TITLE
Life support machinery

### ISSUE THREAD

**Issue by YourLocalPlonker** [studio-minus/ppg-bugs-and-requests#1354]
**Feature description**
Life support machines. (Like heartbeat maker or respirator)

**Feature purpose**
mainly RP and realism

**Additional context**
Since humans now will stop breathing or the heart will stop beating when the upper torso get penetrated it would be a cool addition to the game for people who do RP

**Comment by BBQGiraffe** [comment]
#494

**Comment by ppgplayer** [comment]
> #494

not the same thing, he doesn't specifically want a circulator

**Comment by mestiez** [comment]
Kind of a duplicate
