### ISSUE TITLE
Humans are still conscious despite being brain dead

### ISSUE THREAD

**Issue by BBQGiraffe** [studio-minus/ppg-bugs-and-requests#1357]
**Describe the bug**
humans that have been shot or stabbed can still have a full conscious bar despite being brain dead

**Clearly describe how to reproduce the bug**
1. spawn human
2. shoot it in the head

![image](https://user-images.githubusercontent.com/45021140/169707446-fe3106d2-0148-43f4-8c84-03c188529553.png)

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8749896/exported.game.debug.info.md)

**Comment by mestiez** [comment]
fixed!!11
