### ISSUE TITLE
Painkiller syringe is not fatal in high doses

### ISSUE THREAD

**Issue by SeVeredC0nnection** [studio-minus/ppg-bugs-and-requests#1359]
**Describe the bug**
Painkiller syringe is no longer fatal in high doses. Blood pressure drops a couple percent and goes back up to 100%

**Clearly describe how to reproduce the bug**
Attempt to overdose a human with the painkiller syringe.

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.24.2
 - GPU: RTX 3090
 - CPU: i9-10900KF

**Additional notes**

![20220522130317_1](https://user-images.githubusercontent.com/61633596/169709742-a039dc2a-146d-408c-9108-f3d6a149f95e.jpg)

**Comment by DindinYT37** [comment]
It says **can** be dangerous in high doses, have you tried it with multiple humans?

**Comment by mestiez** [comment]
fixed / changed.
