### ISSUE TITLE
Hitbox of Fire Alarm Item messed up

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#136]
**Describe the bug**
Hitbox of Fire Alarm is messed up, it looks like it floats but it's on the ground.
![image](https://user-images.githubusercontent.com/64973205/130511142-ac6d98a7-6179-4f3d-865e-98485d794eb2.png)

**Clearly describe how to reproduce the bug**
Place a Fire Alarm.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.21.3
 - GPU: NVIDIA GeForce GTX 1070
 - CPU: AMD Ryzen 2700X

**Comment by mestiez** [comment]
?? There is no fire alarm in the game

**Comment by DindinYT37** [comment]
Noticed that too, weird though.
I noticed that it was added into some mod, but I haven't updated my mods yet.
