### ISSUE TITLE
Painkiller syringe causes random skin damage.

### ISSUE THREAD

**Issue by SeVeredC0nnection** [studio-minus/ppg-bugs-and-requests#1361]
**Describe the bug**
Painkiller syringe seems to now cause skin damage and is still not fatal like it was in the 1.24 preview.

**Clearly describe how to reproduce the bug**
Shove as many painkiller syringes as possible into a human and wait a while.

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.24.3
 - GPU: RTX 3090
 - CPU: i9-10900KF

**Additional notes**
None

**Comment by mestiez** [comment]
Not a bug. Painkiller causes skin damage in high doses and will eventually kill the victim
