### ISSUE TITLE
Disassembler discharges even when broken

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1364]
**Describe the bug**
Disassembler still discharges when dropped even when it is broken
**Clearly describe how to reproduce the bug**
1 - Spawn dissassembler (or multiple)
2 - Break them (for example setting temperature to 10000)
3 - Hit the ground with the broken disassemblers
4 - Watch as one of them discharges even though its clearly broken

**Mod list**
People Playground 3D (inactive)
flipping heck (inactive)

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.24.3
 - GPU: RX 470 8GB
 - CPU: Intel Xeon CPU E3-1230 3.20 GH

**Additional notes**
Same with other guns that can break (like blasters)

**Comment by mestiez** [comment]
fixed
