### ISSUE TITLE
A bug believe it or not

### ISSUE THREAD

**Issue by Diavan02** [studio-minus/ppg-bugs-and-requests#1365]
When I open "Local" everything saved just dissapears.

How to reproduce? I have no idea sadly

I have many many mods but they didn't do anything like this before 

**System info (please complete the following information)**
 - Operating system: You mean Windows, Mac... if yes then Windows
 - Game version: 1.24 patch 3
 - GPU: where do I find this?
 - CPU: again, where?

**Comment by Diavan02** [comment]
sorry that i dont know how to reproduce it :(

**Comment by PossiblyRemember** [comment]
To find the system information, click information on the menu and then click export game debug info

**Comment by Diavan02** [comment]
Thank you... also, I forgot to mention, I deleted 20 pages of military
things because they didn't work good, maybe this helps, deleting too many
things at once.
