### ISSUE TITLE
can u fix the fixed cable?

### ISSUE THREAD

**Issue by Somekidthatactuallyannoying42** [studio-minus/ppg-bugs-and-requests#1372]
so this bug is too annoying and can make game crash, like example all my conraption that i made using the fixed cable but when i blow my one of my vehicle with all fixed cable it start bug like wobbling and it cause bug,lag,crash and please fix it, or make and little weaker fixed cable like can still broke but more durable to broke

**Comment by DindinYT37** [comment]
Please use the template, and I'm pretty sure zooi already knows about this. Maybe try using less fixed cables by utilizing pins?

**Comment by mestiez** [comment]
BBQ is correct. This has been addressed in the "Current problems" task list
