### ISSUE TITLE
Laser recievers and key triggers have the same problems as detectors

### ISSUE THREAD

**Issue by Trevor-01** [studio-minus/ppg-bugs-and-requests#1382]
**Describe the bug**
Laser receivers and key triggers still give activation signals when broken. Detectors were fixed but they were not.

**Clearly describe how to reproduce the bug**
Same as the detector problem

**Mod list**
N/A

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.24.3
 - GPU: RTX 2060
 - CPU: I-5

**Comment by mestiez** [comment]
fixed :)
