### ISSUE TITLE
SAVING DOES NOT WORK?

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#139]
**Describe the bug**
Saving says "Thingy Saved With Errors" and then doesn't save it.
Well it doesn't show up as saved it might be in the files somewhere?

**Clearly describe how to reproduce the bug**
Try save something in 1.21.3

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.19043) 64bit

 - **CPU**: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz

 - **GPU**: Intel(R) UHD Graphics

 - **Memory**: 7 GB

## All loaded mods
None

**Comment by mestiez** [comment]
oh oops, fixed and uploading

**Comment by mestiez** [comment]
i am desperately in need of a better testing sytem
