### ISSUE TITLE
Painkiller addiction

### ISSUE THREAD

**Issue by thatGoober** [studio-minus/ppg-bugs-and-requests#1390]
**Description**
Abusing too much painkillers on a person would make them addicted, with effects such as clumsiness and drowsiness appearing. Even more prolonged use would most likely fail the liver or kidney. Overdosing would, of course kill the person,

**Purpose**
I think this'd be a generally pretty fitting addition and overall just a good idea.

**Additional things** 
Also an option to disable the addiction mechanic, as I think most people would want to chug people with painkillers without worrying about addictions.

**Comment by DindinYT37** [comment]
Damn.

**Comment by Roozz1** [comment]
Damn.

**Comment by ppgplayer** [comment]
mf is adding ME to the game

**Comment by Drogo-man** [comment]
druggies
