### ISSUE TITLE
Resizing bug

### ISSUE THREAD

**Issue by Trevor-01** [studio-minus/ppg-bugs-and-requests#1392]
**Describe the bug**
When resizing an object, if you remove it with a disassembler, the resizing arrows still stay. Even when you clear everything, they would still be there.

**Clearly describe how to reproduce the bug**
Get an object and resize it. While the resizing is happening, shoot it with a disassembler until it is removed. The resizing arrows should still be there and the only way to remove them is to right-click them and stop resizing.

**Mod list**
N/A

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.24.5
 - GPU: RTX 2060
 - CPU: I-5

**Additional notes**
![20220525171836_1](https://user-images.githubusercontent.com/98299435/170385001-49b96836-bcda-412f-9a0e-bd2d1816c89d.jpg)

**Comment by mestiez** [comment]
fixed
