### ISSUE TITLE
Heart stopped bug

### ISSUE THREAD

**Issue by Zer1op** [studio-minus/ppg-bugs-and-requests#1398]
**Describe the bug**
Even with a stopped heart creatures have a heartbeat.

**Clearly describe how to reproduce the bug**
I decided to connec a battey to the human for a second. He got "heart stopped" effect in the inspect mode, but even with this effect he had a heartbeat.
![изображение_2022-05-26_185630376](https://user-images.githubusercontent.com/88717085/170526257-a1177983-6523-4154-98d9-143d1ec4227f.png)

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.24.5
 - GPU: MSI GeForce GTX 1650 
 - CPU: Intel Core I5-9400F

**Additional notes**

**Comment by mestiez** [comment]
fixed
