### ISSUE TITLE
blood regaining bug

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#1399]
**Describe the bug**
the blood regaining feature only regains to around 85 then slows to a really really really slow crawl and practically stops

**Clearly describe how to reproduce the bug**
1. spawn a blood tank and human in
2.drain a bit of their blood
3. wait for it to regain and see that it does not go past 85

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: windows 11
 - Game version: 1.24.5
 - GPU: GTX 1650 SUPER
 - CPU: intel i5

**Additional notes**

**Comment by DindinYT37** [comment]
This seems rather like it's more realistic

**Comment by mestiez** [comment]
this isnt a bug. blood doesnt regenerate to 100%
