### ISSUE TITLE
Hitting detecting doesn't work

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#140]
**Describe the bug**
Landmines and shock detectors don't work

**Clearly describe how to reproduce the bug**
Spawn a landmine, put human on it, look at the unexploded landmine.

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.19043) 64bit

 - **CPU**: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz

 - **GPU**: Intel(R) UHD Graphics

 - **Memory**: 7 GB

## All loaded mods
None

**Comment by mestiez** [comment]
yeah i just noticed this as well... how do i keep missing these things

**Comment by mestiez** [comment]
fixed :(
