### ISSUE TITLE
Passive healing broken

### ISSUE THREAD

**Issue by SoupyyySeal** [studio-minus/ppg-bugs-and-requests#1404]
**Describe the bug**
The "Slowly heal injuries" setting is activated, but any damage to a human, except burns (not including friction burns) doesn't heal. Healing with life syringe still functions.

**Clearly describe how to reproduce the bug**
Damage a human in anyway, usually with a weapon from the Melee or Firearms category. If the human dies, revive it. Wait to see if there is any healing, and repine at the result of nothing. Fire damage heals, if its from pyrokinesis, a flamethrower, a heatray, short exposure to an energy sword, lightning/electricity, or from overheating objects.

**Mod list**
BloodEnhancedMod
Status Icons
Time Accelerator

**System info (please complete the following information)**
 - Operating system: Windows 10 home 64bit 
 - Game version: 1.24
 - GPU: Nvidia GeForce GTX 1660 Super
 - CPU: Intel i5-10400F

**Comment by mestiez** [comment]
fixed again
