### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by SteepProYT** [studio-minus/ppg-bugs-and-requests#1410]
**Describe the bug**
Modification in the "Mods" folder writes in the game Unknown error occurred

**Clearly describe how to reproduce the bug**
I am a mod developer, I ran into a problem, Unknown error occurred on my modification, nothing works, what should I do? Recompile doesn't work

**Mod list**
All mods are disabled, so that when developing a mod, the game does not lag

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.24.5
 - GPU: AMD Radeon(TM) R3 Graphics
 - CPU: AMD A4-9125 RADEON R3

**Additional notes**
![image](https://user-images.githubusercontent.com/106415126/170842822-52cd9e54-f770-4b3d-8dbb-5960b1197219.png)

**Comment by DindinYT37** [comment]
Have you tried checking your mods for bugs first though?

**Comment by mestiez** [comment]
Please attach your log file
