### ISSUE TITLE
Human regenerate blood too fast

### ISSUE THREAD

**Issue by SeVeredC0nnection** [studio-minus/ppg-bugs-and-requests#1416]
**Describe the bug**
Sometimes humans regenerate blood way faster than they lose it even after being riddled with bullets.

**Clearly describe how to reproduce the bug**
Seems to be somewhat random but just shoot a human multiple times (dozens) below the heart and watch the blood amount drop and regenerate.

**Mod list**
Musket Mod

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: Latest
 - GPU: RTX 3090
 - CPU: I9-10900KF 

**Additional notes**
I'd recommend using the Blunderbuss at close range when trying to reproduce this. (Part of the musket mod)

**Comment by mestiez** [comment]
i made it a bit slower
