### ISSUE TITLE
Beheading should kill humans instantly

### ISSUE THREAD

**Issue by Gigi-7688** [studio-minus/ppg-bugs-and-requests#1418]
-Describe the bug

Beheading will not immediately kill a human being.
In fact, he will only die when his blood pressure has dropped to 25%.

-Clearly describe how to reproduce the bug

Press "freeze" on the chest and then detach the head.

-Mod list

All loaded mods:

	GalaxyHighMarshal-BloodEnhancedMod-2811563551 v2.0 for game v1.23+
		Currently inactive

	Orsoniks / Navii-Reactive humans-2793371344 v1.0 for game v1.23+
		Currently ACTIVE

	Team Wilson-People Playground 3D-2785176210 v1 for game v1.21+
		Currently inactive

	JOSIMA-Enhanced Human Sounds-2738554876 v0.1 for game v1.11+
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently inactive

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently inactive

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently ACTIVE
		Has been initialised

	zooi-Per Pixel Destruction-2314372940 valpha 7 for game v1.13.1
		Currently inactive

	Morzzic-Photo Mode-2263832258 v1.0 for game v1.8+
		Currently inactive

	zooi-Controllable anti-air cannon-2178648827 v1.2 for game v1.9.3
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently ACTIVE

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently inactive

-System info

People Playground [v1.24.6] [64 bit]

System info:

OS: Windows 10 (10.0.22000) 64bit
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU: NVIDIA GeForce RTX 2060
Memory: 16 GB

-Additional notes
I wonder why a human who has a broken neck bone should die immediately and one whose head is detached does not.
![Screenshot (138)](https://user-images.githubusercontent.com/102178009/171477545-776cded5-0d66-4d55-9c57-58bd2c403280.png)

![12](https://user-images.githubusercontent.com/102178009/171477576-672f46e5-d148-48b2-bc8b-4984e887e214.png)

**Comment by DindinYT37** [comment]
> -Describe the bug
> 
> Beheading will not immediately kill a human being. In fact, he will only die when his blood pressure has dropped to 25%.
> 
> -Clearly describe how to reproduce the bug
> 
> Press "freeze" on the chest and then detach the head.
> 
> -Mod list
> 
> All loaded mods:
> 
> ```
> GalaxyHighMarshal-BloodEnhancedMod-2811563551 v2.0 for game v1.23+
> 	Currently inactive
> 
> Orsoniks / Navii-Reactive humans-2793371344 v1.0 for game v1.23+
> 	Currently ACTIVE
> 
> Team Wilson-People Playground 3D-2785176210 v1 for game v1.21+
> 	Currently inactive
> 
> JOSIMA-Enhanced Human Sounds-2738554876 v0.1 for game v1.11+
> 	Currently inactive
> 
> Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
> 	Currently inactive
> 
> Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
> 	Currently inactive
> 
> zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
> 	Currently inactive
> 
> zooi-flipping heck-2448120172 v1.7 for game v1.23
> 	Currently ACTIVE
> 	Has been initialised
> 
> zooi-Per Pixel Destruction-2314372940 valpha 7 for game v1.13.1
> 	Currently inactive
> 
> Morzzic-Photo Mode-2263832258 v1.0 for game v1.8+
> 	Currently inactive
> 
> zooi-Controllable anti-air cannon-2178648827 v1.2 for game v1.9.3
> 	Currently inactive
> 
> Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
> 	Currently ACTIVE
> 
> quaq-Active Humans-2163278857 v2.0 for game v1.9+
> 	Currently inactive
> 
> zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
> 	Currently inactive
> ```
> 
> -System info
> 
> People Playground [v1.24.6] [64 bit]
> 
> System info:
> 
> OS: Windows 10 (10.0.22000) 64bit CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz GPU: NVIDIA GeForce RTX 2060 Memory: 16 GB
> 
> -Additional notes I wonder why a human who has a broken neck bone should die immediately and one whose head is detached does not.

I mean, yeah. If his heart and other organs are still intact... could make sense.

**Comment by Gigi-7688** [comment]
![Screenshot (138)](https://user-images.githubusercontent.com/102178009/171475554-c0f81575-7cdd-411c-adfb-1a8162a3bcee.png)

**Comment by DindinYT37** [comment]
> ![Screenshot (138)](https://user-images.githubusercontent.com/102178009/171475554-c0f81575-7cdd-411c-adfb-1a8162a3bcee.png) ![12](https://user-images.githubusercontent.com/102178009/171477377-0e49cbf3-61e2-4991-8f2f-6699f4d1f8b2.png)
> 
> I believe that decapitating a person is equivalent to breaking their neck

The first picture is actually a bug, the second picture seems to make sense though as he is in the midst of dying.

**Comment by SirAJ4895** [comment]
You are still conscious for up to 20 seconds after being decapitated so I guess it's realism.

**Comment by Drogo-man** [comment]
the reason that the head dies instantly when you break the bone is because you're breaking the whole skull, not just the neck as you select the WHOLE head, and the body can still sorta function with the limited brain activity from your brain stem. but being decapitated also severs your brain stem which kills the body, but your head can still live with the remaining blood in your head.

**Comment by Drogo-man** [comment]
> > the reason that the head dies instantly when you break the bone is because you're breaking the whole skull, not just the neck as you select the WHOLE head, and the body can still sorta function with the limited brain activity from your brain stem. but being decapitated also severs your brain stem which kills the body, but your head can still live with the remaining blood in your head.
> 
> Breaking the "head-bone" in PPG is just breaking the neck tho.

still, broken neck shards can pretty much shred the brain.

**Comment by Drogo-man** [comment]
When it comes to the head, scientific studies show that the brain is conscious for like 20-10 seconds after beheading.
Just sayin.

**Comment by DindinYT37** [comment]
> When it comes to the head, scientific studies show that the brain is conscious for like 20-10 seconds after beheading. Just sayin.

Probably why it was changed to be a feature request.
