### ISSUE TITLE
Gate doesn't have double trigger mode

### ISSUE THREAD

**Issue by CandyDendi** [studio-minus/ppg-bugs-and-requests#143]
In the update 1.21 there was a line mentioning that "Gate now has a double trigger mode", but in-game gate doesn't have it. And in other update logs there was no mention of that

I have deleted all of my mods for this.

**System info**
 - Operating system: Windows 10
 - Game version: 1.21.3
 - GPU: AMD Ryzen 5 2600
 - CPU: Radeon RX 560 Series
 
 
![image](https://user-images.githubusercontent.com/89443221/130567772-badd6d71-24ef-43ae-897c-7bc6445c5f8e.png)

![image](https://user-images.githubusercontent.com/89443221/130567699-246d5eeb-6c54-4825-b299-73e8580112cd.png)

**Comment by mestiez** [comment]
That is a timed gate.

**Comment by Aspa102** [comment]
@mestiez A timed gate has a massive timer knob thing on it. That does not. That is a normal gate. They still don't have a double trigger mode.

**Comment by mestiez** [comment]
No idea how I messed this one up
