### ISSUE TITLE
Ejected particles from guns should scale with the weapon

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1443]
When a gun fires in People Playground, the recoil and casings (shells) do not scale. This is a very minor change, but it would be appreciated if you fixed it.

**Comment by DindinYT37** [comment]
Please use the template.

**Comment by SirAJ4895** [comment]
> Please use the template.

How about you please use the template?

**Comment by DindinYT37** [comment]
> > Please use the template.
> 
> How about you please use the template?

Oh wow, haha so funny, totally omg I'm crying.
