### ISSUE TITLE
Can't save multi-piece items

### ISSUE THREAD

**Issue by Brostrod** [studio-minus/ppg-bugs-and-requests#1445]
**Describe the bug**
You can't save items/vehicles/whatever you call them without getting an error message if you remove a part from them

**Clearly describe how to reproduce the bug**
Remove a tire from a vehicle and try to save it

**Mod list**
No mods

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.24.6
 - GPU: GTX 1660 Super
 - CPU: Ryzen 7 5800 8-Core

**Additional notes**

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/175033002-a8fa4bee-4b9e-4de6-ae41-6d8e6b706031.png)
works fine for me... closing until there is more information
