### ISSUE TITLE
Destructible objects bug

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1469]
**Describe the bug**
Broken objects still "exist" even after debris has been deleted from the context menu

**Clearly describe how to reproduce the bug**
1. Spawn an affected destructible object (list below)
2. Break it
3. Delete using the context menu
4. Press the undo button
5. Notice that "X REMOVED" appears

**Additional notes**
Affected objects:
- Bottle
- Concrete Slab
- Crate
- Glass Pane
- Vase
- Plate
- Pumpkin
- Small Boulder
- Wooden Chair
- Wooden pin (has no debris but still shows up when undoing)
- Wooden Table

I dont know if Brick Wall and Brick Cube count since they have unremovable bricks

Also related to #193 and #1352
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8872367/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
I noticed this some time ago, though I thought it was just because the name was still in the object history.

**Comment by mestiez** [comment]
fixed
