### ISSUE TITLE
Painkiller Syringe

### ISSUE THREAD

**Issue by mishamumia** [studio-minus/ppg-bugs-and-requests#1473]
Painkiller creates wounds on ragdolls. I don't think it should.
And (maybe) with update 1.24 androids have less integrity. Much less than in previous androids.

**Comment by DindinYT37** [comment]
Please use the template. Also, it should, read the description...
![image](https://user-images.githubusercontent.com/64973205/173135320-c38dc757-3428-439c-838d-f20635e44d77.png)

**Comment by mishamumia** [comment]
Also it kills, but also causes WOUNDS.

**Comment by DindinYT37** [comment]
> Also it kills, but also causes WOUNDS.

Obviously it kills, it's **dangerous** which means it can lead to death. Also, those aren't wounds - that's skin damage, or as you would say **SKIN DAMAGE**.

**Comment by mishamumia** [comment]
Oh... It just mods maked this...

**Comment by DindinYT37** [comment]
> Oh... It just mods maked this...

So either you had a really weird mod, or you don't just wanna say I'm right for some reason. Though I doubt you'd be lying about this kind of simple thing so I'm guessing you just had a weird mod. Anyway, what mod was it?

**Comment by mishamumia** [comment]
I dunno i just have a lot of mods.

**Comment by DindinYT37** [comment]
> I dunno i just have a lot of mods.

Then how did you find out that it was because of a mod? Did you just disable all mods?
