### ISSUE TITLE
Floating Blood Wounds on Android

### ISSUE THREAD

**Issue by bluewoods64** [studio-minus/ppg-bugs-and-requests#1474]
I know the title sounds stupid. I'm not really sure what else to put.

**Describe the bug**
When an android has blood stains on him, detonating a pink explosive (or anything that would remove the outer "flesh" of the android) causes a strange floating blood stain to be surrounding the android. 
![image](https://user-images.githubusercontent.com/93502259/173144515-94da2576-0e26-4d67-96cd-a124483deb84.png)

**Clearly describe how to reproduce the bug**
Watch video please:
https://www.youtube.com/watch?v=q28VsmuHi8I 

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.24.6
 - GPU: RTX 2060 6GB
 - CPU: i7 11700F

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8882044/exported.game.debug.info.md) 
This includes the mods, right?

**Additional notes**
i know this isnt some game breaking bug but i noticed it so why not. i mean its like a blood stain floating on air

**Comment by DindinYT37** [comment]
This also happens for me, the same thing can also happen with explosion "marks".

**Comment by bluewoods64** [comment]
> This also happens for me, the same thing can also happen with explosion "marks". Edit: ![image](https://user-images.githubusercontent.com/64973205/173147483-a56d6a46-5837-4be3-a8fe-2f927218646a.png) ![image](https://user-images.githubusercontent.com/64973205/173147485-e0c168a9-eccf-4fd4-bb0f-b2aed54acafd.png)

not sure how i missed that. good catch

**Comment by PossiblyRemember** [comment]
I think it's just how decals are put on objects, instead of it being put straight on the skeleton texture or whatever you want to call it, it appears on the collision box. That's the best way I can explain it.

**Comment by DindinYT37** [comment]
> I think it's just how decals are put on objects, instead of it being put straight on the skeleton texture or whatever you want to call it, it appears on the collision box. That's the best way I can explain it.

I know that but I don't think it's impossible to mask the deals to the texture.

**Comment by mestiez** [comment]
this cannot be fixed without a great performance hit
