### ISSUE TITLE
Flamethrower goes through some walls

### ISSUE THREAD

**Issue by Kerferferker** [studio-minus/ppg-bugs-and-requests#1484]
Flamethrower goes through some walls, up to 2 meters  away!

Place a brick wall, human, and a flamethrower down. Position the human up to 2 meters away from the wall and push the flamethrower up to the wall while firing flames. Note that the tip of the flamethrower has to be touching the wall. The human will catch on fire.
 
(This bug works with all mods on and off.)
Cars, Cars, And Cars [v1.2.1] - Um, Idk
Realistic Axe mod - Dyadyushka Dyadya and Maxe
Blood on walls - Orsoniks
Better Androids (Damage overhaul) - Orsoniks
The Ultimate Car Mod - Mishanya
TF2 Mercenaries - gay sewer rat
Human furry mod (reupload) - FredMichalBear
People Playground 3D
Quality of Life Items - Pumpkin
FNAF Mod - LijmPistool#0001
Wound Infections - Orsoniks
flipping heck - Zooi
Dream - Your Local Home Invader and xGrimxReaperx2
POT O' Items - PIMPLE SKUNK and sv1t
The Ultimate Minecraft Mod 1.8 - Kyrelink and Quickness
Functioning Armor - weirdo
Quick Right Click Options - Pump3d
Soror's NPC Pack (40) - Sororfortuna and ph
Human Tiers [ 2.3 ] - Alibarda
Active Humans! - quaq

CONTRAPTIONS
TF2 Payload Bomb - zFwzy
Full Destructible Tower (Vanilla) - Santinnel
Working Toilet - Belligerent Drunk
[HL2] Bridge Point - Patrick Basedman (Shlag)

 - Operating system:  Windows 10
 - Game version: 1.24.6 (64 bit)
 - GPU: NVIDIA GeForce GT 1030
 - CPU: Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz

**Comment by DindinYT37** [comment]
Would be nice if you could keep the template's headers.

**Comment by mestiez** [comment]
fixed
