### ISSUE TITLE
 Sentry turrets target dead severed limbs of alive humans.

### ISSUE THREAD

**Issue by Kerferferker** [studio-minus/ppg-bugs-and-requests#1488]
THE BUG
I'm not sure if this is a bug or a feature, but turrets seem to shoot dismembered, dead body parts of alive humans.

HOW TO REPRODUCE
Spawn a human. Rip off a leg or an arm. Spawn a sentry turret, make sure that the turret isn't facing the human, place the dismembered arm or leg in the turrets vision, and boom, the turret is shooting a dead limb. Note that the human that "donated" their limb has to be alive.

MODS
(This bug works with all mods on and off.)
Cars, Cars, And Cars [v1.2.1] - Um, Idk
Realistic Axe mod - Dyadyushka Dyadya and Maxe
Blood on walls - Orsoniks
Better Androids (Damage overhaul) - Orsoniks
TF2 Mercenaries - gay sewer rat
Human furry mod (reupload) - FredMichalBear
People Playground 3D
Quality of Life Items - Pumpkin
FNAF Mod - LijmPistool#0001
Wound Infections - Orsoniks
flipping heck - Zooi
Dream - Your Local Home Invader and xGrimxReaperx2
POT O' Items - PIMPLE SKUNK and sv1t
The Ultimate Minecraft Mod 1.8 - Kyrelink and Quickness
Functioning Armor - weirdo
Quick Right Click Options - Pump3d
Soror's NPC Pack (40) - Sororfortuna and ph
Human Tiers [ 2.3 ] - Alibarda
Active Humans! - quaq

CONTRAPTIONS
TF2 Payload Bomb - zFwzy
Full Destructible Tower (Vanilla) - Santinnel
Working Toilet - Belligerent Drunk
[HL2] Bridge Point - Patrick Basedman (Shlag)

SYSTEM INFO
-Operating system: Windows 10
-Game version: 1.24.6 (64 bit)
-GPU: NVIDIA GeForce GT 1030
-CPU: Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz

**Comment by mestiez** [comment]
fixed :)
