### ISSUE TITLE
Clock (that shows time)

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1489]
**Feature description**
Digital or mechanical clock that shows system time or you can set your own time. Time format can be changed in settings like temperature. If a mechanical clock breaks then small gear particles should fall out. Maybe in a set amount of time an activation signal should go off 

**Feature purpose**
Closest thing to a clock is a metronome and a circle with two wires so a functional clock would be nice for decor or specific time mechanisms

**Additional context**
I am aware that mods exist but it would be nice to have it in vanilla

**Comment by DindinYT37** [comment]
> Maybe in a set amount of time an activation signal should go off 
> 

Isn't that just a timed gate?

**Comment by bibbybabby** [comment]
> > Maybe in a set amount of time an activation signal should go off
> 
> Isn't that just a timed gate?

No I mean system time

**Comment by Drogo-man** [comment]
> > > Maybe in a set amount of time an activation signal should go off
> > 
> > 
> > Isn't that just a timed gate?
> 
> No I mean system time

You can just use your phone or built-in pc clock?
Also the functional devices mod by Mishanya has a working clock if I remember correctly.

**Comment by DindinYT37** [comment]
> > > Maybe in a set amount of time an activation signal should go off
> > 
> > 
> > Isn't that just a timed gate?
> 
> No I mean system time

How would that be more useful than a timed gate?

**Comment by bibbybabby** [comment]
> > > > Maybe in a set amount of time an activation signal should go off
> > > 
> > > 
> > > Isn't that just a timed gate?
> > 
> > 
> > No I mean system time
> 
> How would that be more useful than a timed gate?

Timed gate is a timed gate, what I mean that for example it activates in 13:45 and only 13:45, timed gates can't do that

**Comment by bibbybabby** [comment]
> 
Idk really it's the type of ideas that come up in the middle of the night that you don't have an elaborate explanation of why should it be in the game, I can close it if you wish

**Comment by DindinYT37** [comment]
> > 
> 
> Idk really it's the type of ideas that come up in the middle of the night that you don't have an elaborate explanation of why should it be in the game, I can close it if you wish

😐
