### ISSUE TITLE
Realistic Gore

### ISSUE THREAD

**Issue by testgeese** [studio-minus/ppg-bugs-and-requests#1490]
If a human is shot anywhere in the body; there's a chance that it'll expel flesh clumps and blood from the exit wound.

For aesthetics, and realism.

Similar to shooting someone in the forehead but instead of brains; it's flesh.
![image](https://user-images.githubusercontent.com/107525464/173728748-3e8ce15f-074d-4514-af83-f3e2651f3eac.png)

**Comment by DindinYT37** [comment]
Basically a mod and #1375

**Comment by testgeese** [comment]
> Basically a mod and #1375

Which mod?
