### ISSUE TITLE
Inspect doesnt show worm staff hole wounds

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1494]
**Describe the bug**
If a worm staff burrows into a human the inspect menu doesnt show holes despite them being visible

**Clearly describe how to reproduce the bug**
1. Spawn human and worm staff
2. Let the staff do its thing
3. Inspect
4. Notice that there is nothing said about the holes

**Additional notes**
related to #1457
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8921640/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
Wouldn't this rather be a feature request? Since this certainly doesn't count as gunshot wounds and I am unsure if this would count as stab wounds - even though they kinda are.

**Comment by mestiez** [comment]
I guess ill just make it count as a stab wound
