### ISSUE TITLE
Broken Immortality Serum

### ISSUE THREAD

**Issue by BugMan33** [studio-minus/ppg-bugs-and-requests#1496]
**Describe the bug**
The Immortality Serum has a very short effect. It used to be endless, now it only lasts a few seconds.

**Clearly describe how to reproduce the bug**
Inject human with immortality serum.

**Mod list**
Functional Terminator Mod - Active
Science Hazard Minus - Active
Time Accelerator - Active

**System info (please complete the following information)**
 - Operating system: Windows 10 pro
 - Game version: 1.24 patch 5
 - GPU: amd radeon rx 5500m
 - CPU: amd ryzen 4800h

**Comment by bywok** [comment]
Same with me. I thought it just didn't work at all?

**Comment by DindinYT37** [comment]
and I was wondering if it just became weaker, turns out it didn't work at all...

**Comment by mestiez** [comment]
Mine works fine?

**Comment by BugMan33** [comment]
> Mine works fine?

It does not have any effect after like 30 seconds.

**Comment by mestiez** [comment]
Could be because there are holes in the body out of which the serum is leaking? Should the serum prevent any leaking?

**Comment by mestiez** [comment]
I guess that would make sense... fixed
