### ISSUE TITLE
The Gorse's head isn't effected by the beam of the beam rifle.

### ISSUE THREAD

**Issue by Kerferferker** [studio-minus/ppg-bugs-and-requests#1497]
THE BUG
If shot directly at the Gorse's head, the beam rifle does nothing, except light the fella' on fire.

HOW TO REPRODUCE
Spawn a Gorse and a beam rifle. Position the rifle above the Gorse. Make sure the laser sight of the rifle is in the middle of the Gorse's head and fire.

MODS
(This bug works with all mods on and off.)
Cars, Cars, And Cars [v1.2.1] - Um, Idk
Realistic Axe mod - Dyadyushka Dyadya and Maxe
Blood on walls - Orsoniks
Better Androids (Damage overhaul) - Orsoniks
TF2 Mercenaries - gay sewer rat
Human furry mod (reupload) - FredMichalBear
People Playground 3D
Quality of Life Items - Pumpkin
FNAF Mod - LijmPistool#0001
Wound Infections - Orsoniks
flipping heck - Zooi
Dream - Your Local Home Invader and xGrimxReaperx2
POT O' Items - PIMPLE SKUNK and sv1t
The Ultimate Minecraft Mod 1.8 - Kyrelink and Quickness
Functioning Armor - weirdo
Quick Right Click Options - Pump3d
Soror's NPC Pack (40) - Sororfortuna and ph
Human Tiers [ 2.3 ] - Alibarda
Active Humans! - quaq

CONTRAPTIONS
TF2 Payload Bomb - zFwzy
Full Destructible Tower (Vanilla) - Santinnel
Working Toilet - Belligerent Drunk
[HL2] Bridge Point - Patrick Basedman (Shlag)

SYSTEM INFO
-Operating system: Windows 10
-Game version: 1.24.6 (64 bit)
-GPU: NVIDIA GeForce GT 1030
-CPU: Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz

NOTES
The Gorse dosen't even flinch at the beam going through him!

**Comment by Drogo-man** [comment]
Did you just make your own headers? Just use the template!

**Comment by DindinYT37** [comment]
Can confirm the bug happens for me too.

**Comment by mestiez** [comment]
This happens because the beam rifle "slices" limbs off. The center limb (head on gorse, torso on humanoids) technically doesn't have any limbs attached so the slicing does nothing. I can fix this by making the beam rifle crush the limb if it has no limbs attached.

**Comment by mestiez** [comment]
Fixed :)
