### ISSUE TITLE
Contraptions won't spawn

### ISSUE THREAD

**Issue by Alexxithymla** [studio-minus/ppg-bugs-and-requests#1505]
**Describe the bug**
Whenever I download a contraption via the addons menu on steam, when I get in game the contraption will not spawn. Even without mods this issue keeps occurring, I have downloaded the correct addons for a contraption, yet it still fails to spawn. I have also reinstalled the game, deleted all my addons and contraptions yet it still doesn't work.

**Clearly describe how to reproduce the bug**
Download a contraption and try and spawn it, with mod or without. I do not know if this is only myself. 

**Mod list**
Quick Right Click

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.24.5
 - GPU: 980
 - CPU: i7 4790K

**Additional notes**
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8934885/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
Doesn't happen for me.

**Comment by Alexxithymla** [comment]
> Doesn't happen for me.

Weird, still happens for me.

**Comment by mestiez** [comment]
Can you try to spawn a contraption, exit the game, and then send the resulting Main log file here? Make sure to remove any personal info that it might contain.
