### ISSUE TITLE
Make cyrillic script consistent with latin script

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1510]
**Feature description**
Make cyrillic consistent, because it has no pixel font, a slight glow and a weird outline

**Feature purpose**
Consistency

**Additional context**

![ЧТО-ТО](https://user-images.githubusercontent.com/104321411/174544804-fe9e1a26-c561-4b85-a605-e7bfc28fb351.png)

**Comment by DindinYT37** [comment]
This happens because the font ppg uses only supports some special characters and ASCII characters.

**Comment by bibbybabby** [comment]
New letters should be added to the font then

**Comment by DindinYT37** [comment]
> New letters should be added to the font then

I was simply telling you why it happened, and to be fair, more characters should be added, not just letters.
