### ISSUE TITLE
Bug in the broken piston

### ISSUE THREAD

**Issue by Gigi-7688** [studio-minus/ppg-bugs-and-requests#1522]
-Describe the bug

Saving a broken piston and spawning it left will lead to a bug in the rod.
This happens with both industrial pistons and normal pistons.

-Clearly describe how to reproduce the bug

1) Break a piston
2) Save
3) Spawn it on the left (The piston must be positioned to the left)

-Mod list

All loaded mods:

	GalaxyHighMarshal-BloodEnhancedMod-2811563551 v2.0 for game v1.23+
		Currently inactive

	Orsoniks / Navii-Reactive humans-2793371344 v1.0 for game v1.23+
		Currently ACTIVE

	Team Wilson-People Playground 3D-2785176210 v1 for game v1.21+
		Currently inactive

	JOSIMA-Enhanced Human Sounds-2738554876 v0.1 for game v1.11+
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently inactive

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently inactive

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently ACTIVE
		Has been initialised

	zooi-Per Pixel Destruction-2314372940 valpha 7 for game v1.13.1
		Currently inactive

	Morzzic-Photo Mode-2263832258 v1.0 for game v1.8+
		Currently inactive

	zooi-Controllable anti-air cannon-2178648827 v1.2 for game v1.9.3
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently ACTIVE

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently inactive

-System info

People Playground [v1.24.6] [64 bit]

System info:

OS: Windows 10 (10.0.22000) 64bit
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU: NVIDIA GeForce RTX 2060
Memory: 16 GB

-Additional notes
Sorry for my English.

![Screenshot (176)](https://user-images.githubusercontent.com/102178009/175357532-20c0dec7-ea81-4fc5-802a-67ae1444b959.png)

**Comment by mestiez** [comment]
fixed :)
