### ISSUE TITLE
burns self heal

### ISSUE THREAD

**Issue by wilsonmcpiston** [studio-minus/ppg-bugs-and-requests#1525]
**Describe the bug**
burning wounds self heal even with auto healing off

**Clearly describe how to reproduce the bug**
burn a human and keep it alive

**Mod list**
quick right click options activated
human tiers activated
cybernetic factions deactivated
the ultimate minecrfat mod activated
simple syringes activated
acid map activated
**System info (please complete the following information)**
 
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8978711/exported.game.debug.info.md)

**Additional notes**
I don't know if it's a feature but it happens even with self healing off

**Comment by DindinYT37** [comment]
Please use the template.

**Comment by f4563** [comment]
> Please use the template.

he is though

**Comment by DindinYT37** [comment]
> > Please use the template.
> 
> he is though 

So where is "Describe the bug" and "Clearly describe how to reproduce the bug" then.

**Comment by mestiez** [comment]
Fixed
