### ISSUE TITLE
Liquid temperature

### ISSUE THREAD

**Issue by LordMilkman** [studio-minus/ppg-bugs-and-requests#1526]
**Feature description**
Says it all in the title, when you heat up a container with liquid in it, it heats up the liquid inside aswell. If you pump the liquid into a person, they get burns all over.

**Feature purpose**
Would be a bit more realistic, could open up some new reactions based on temperature, would generally be more fun.

**Additional context**
Heating up nytroglicerin a lot could blow it up.

**Comment by mestiez** [comment]
#261
