### ISSUE TITLE
Sentry Turret and 9mm Pistol should have more distinct sounds

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1543]
**Feature description**
Sentry Turret and 9mm Pistol currently have the same sound, it would be nice if the sounds would be different

**Feature purpose**
To differentiate sounds, also it doesnt really make sense that a pistol and a sentry have the same firing sound

**Additional context**

https://user-images.githubusercontent.com/104321411/175982892-4bc8c452-2b23-4de2-8004-beab8a12969b.mp4

**Comment by bibbybabby** [comment]
The turret's barrel and shells are different to a 9mm pistol, and about the other sounds you are right, but i still believe they should be different

**Comment by DindinYT37** [comment]
> The turret's barrel and shells are different to a 9mm pistol, and about the other sounds you are right, but i still believe they should be different

We can't be sure about the barrel part; the shells are indeed bigger and different to a 9mm pistol but if you focus on the sounds only, you can hear that the turret has in fact, a more powerful "shot" sound mixed into it.

**Comment by bibbybabby** [comment]
> > > > The turret's barrel and shells are different to a 9mm pistol, and about the other sounds you are right, but i still believe they should be different
> > > 
> > > 
> > > We can't be sure about the barrel part; the shells are indeed bigger and different to a 9mm pistol but if you focus on the sounds, you can hear that the turret has in fact, a more powerful "shot" sound mixed into it.
> > 
> > 
> > The sound has distant sound effects on, i have disabled them and they sound exactly the same
> 
> I have checked myself and the turret has a more powerful sound mixed in with the 9mm pistol shot sound, both with distant sound effects enabled and disabled.

i have checked again and you are indeed correct, the powerful sound is subtle though
