### ISSUE TITLE
ModAPI.FindSpawnable("Wheel") Modding bug.

### ISSUE THREAD

**Issue by PeoplePlayer** [studio-minus/ppg-bugs-and-requests#1545]
**Describe the bug**
When using ModAPI.FindSpawnable("Wheel") to create a new item the modded item referenced as "Wheel" doesn't show up in the
items spawner neither in the specified category, "Metal Wheel' works fine, but when its just "Wheel" this bug produces and the compiler doesn't give any error.

**Clearly describe how to reproduce the bug**

public static void Main()
        {
            ModAPI.Register(
                new Modification()
                {
                    OriginalItem = ModAPI.FindSpawnable("Wheel"),
                    NameOverride = "Old Wheel",
                    DescriptionOverride = "Unpredictable",
                    CategoryOverride = ModAPI.FindCategory("Misc."),
                    ThumbnailOverride = ModAPI.LoadSprite("weight.png"),
                    AfterSpawn = (Instance) =>
                    {
                        Instance.GetComponent<SpriteRenderer>().sprite = ModAPI.LoadSprite("ffsw.png");
                        ModAPI.Draw.Collider(Instance.GetOrAddComponent<<CircleCollider2D>CircleCollider2D>());
                    }
                }
            );
        }
    }

**Mod list**
//

**System info (please complete the following information)**
 - Operating system: Linux Debian 11 (GNOME)
 - Game version: 1.24.5
 - GPU: RTX 3090
 - CPU: Intel Core i7
 - .exe Translation Software: Steam Proton Experimental.

**Additional notes**
There might be some other spawnable items than "Wheel" that are not assigned properly with the FindSpawnable() function.

**Comment by DindinYT37** [comment]
Because "Wheel" is not a spawnable object. Also, codeboxes exist.

Example:
\`\`\`cs
// Your code
\`\`\`
*would turn into*
```cs
// Your code
```

**Comment by PeoplePlayer** [comment]
> 

But the "Wheel" is in the spawnable list:
https://github.com/mestiez/ppg-snippets/blob/master/all%20spawnable%20object%20names.txt
why should it not be spawnable then?

Thanks for code information btw.

**Comment by DindinYT37** [comment]
> > 
> 
> But the "Wheel" is in the spawnable list:
> https://github.com/mestiez/ppg-snippets/blob/master/all%20spawnable%20object%20names.txt
> why should it not be spawnable then?
> 
> Thanks for code information btw.

I am unsure, either this is an actual bug or it's only intended to be used for vehicles though that's unlikely. If zooi doesn't answer until tomorrow I will try to find more out myself.

**Comment by Drogo-man** [comment]
I like your funny words, magic man.

**Comment by PeoplePlayer** [comment]
> I like your funny words, magic man.

Ur on shrooms or wha?🤣

**Comment by DindinYT37** [comment]
@PeoplePlayer I found out that this hasn't been working for quite the time, I checked on some other mods and they always just use a Metal Wheel and re-texture it to their desired wheel texture - most just copy the original one and apply it to the metal wheel. I still can't say for sure if this is intended or not but apparently it's been like this for a long time.

**Comment by Drogo-man** [comment]
> > I like your funny words, magic man.
> 
> Ur on shrooms or wha?🤣

I just don't know C# that well.

**Comment by DindinYT37** [comment]
> I just don't know C# that well.

Me neither 👍

**Comment by mestiez** [comment]
Works for me? 
```cs
Debug.LogFormat("Trying to find WHEEL: {0}", ModAPI.FindSpawnable("Wheel"));
```
prints
```
Trying to find WHEEL: Wheel (SpawnableAsset)
```
