### ISSUE TITLE
Wound outlet "holes"

### ISSUE THREAD

**Issue by TamasB14** [studio-minus/ppg-bugs-and-requests#155]
**Feature description**
After you stab through Ragdoll it only makes an inlet hole, so there should be a feature that makes outlet holes too. Could work with bullets too.

**Feature purpose**
It would add realism and it isn't CPU heavy at all. Stabbing through ragdolls would be much more fun. And you could also determine which ragdoll was just poked and which were actually cut through.

**Additional context**
I'm sure everybody would like it. It's just alot more fun than having 1 hole on the body, which is only the inlet wound :/ 

Excuse?
"but it comes out from the other side of the ragdoll, therefore you don't see it." - Bad excuse, game is 2D and if you stab through something it should make a hole at the very back of the ragdoll atleast.

![bleeding](https://user-images.githubusercontent.com/26002677/131150999-41a3b6a0-a9a4-4b82-905c-28f0ddebc742.png)

**Comment by mestiez** [comment]
Don't assume how CPU heavy something would be because there is no way you could tell.

**Comment by mestiez** [comment]
Bullets already have exit wounds.

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/131364915-d7d6c5b6-7104-47d5-b0ec-2bd348e4a7f1.png)
its a bit weird. it looks fine when stationary but the spear is not really stuck to the other side of their body. the spear only _really_ penetrates the first object it hits and then ignores all the rest. though i guess this is still better.
