### ISSUE TITLE
Death loop

### ISSUE THREAD

**Issue by Verycoolgarfield** [studio-minus/ppg-bugs-and-requests#1558]
**Describe the bug**
If you inject a human with a life syringe in their neck the bone will break and it kills them. It the regenerates and goes on a infinite loop

**Clearly describe how to reproduce the bug**
I don't know exactly how it's done but it's happened around 20% of the time I've tried healing them when injecting the serum.

**Mod list**
None of my mods affect any of the serums since I've turned off and on each one and each yielded the same results

**System info (please complete the following information)**
 - Operating system: Windows
 - Game version: Current
 - GPU: idk lol
 - CPU: idk lol

**Additional notes**
It's just really annoying to hear it pop over and over.

**Comment by DindinYT37** [comment]
Are you aware of the fact that it told you that you can just export your game data and upload it instead of filling out the System info? This has also never happened to me before.

**Comment by mestiez** [comment]
fixed :)
