### ISSUE TITLE
Unstable human.

### ISSUE THREAD

**Issue by TheThroneRo** [studio-minus/ppg-bugs-and-requests#1561]
When i spawn a human he start go crazy limb go crazy so when i spawn when he touche the ground he do like "reality life" hard to explain this bug weird im think im the only one who have this

d ont know how to produce

normal mod just car and weapon mod.

no need detail of my computer

i try lot of thing to fix this but don t know how fix

**Comment by PossiblyRemember** [comment]
ok idk what's going on in this report because I get seizures reading it but maybe physics iterations too low? that's the best I have unless you can give more details on the problem.
