### ISSUE TITLE
Cobblestone Wall and Stone Brick Wall still exists after being deleted

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1567]
**Describe the bug**
If debris from these walls are deleted the undo message still appears

**Clearly describe how to reproduce the bug**
1. Spawn cobblestone wall or stone brick wall
2. Break
3. Delete debris
4. Undo
5. Undo message appears

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9023640/exported.game.debug.info.md)

**Additional notes**
Problem same as #1469

**Comment by mestiez** [comment]
Okay fixed for real I think (I am unsure)

**Comment by PossiblyRemember** [comment]
> how many times has zooi fixed this bug??? its likes herobrine, it gets patched in every update.

Except Herobrine never existed in the first place, but good point
