### ISSUE TITLE
Sentry turret glitching out

### ISSUE THREAD

**Issue by thisinsaname** [studio-minus/ppg-bugs-and-requests#1568]
When the sentry gun targets something in the beta, it will suddenly start flying around the map, even through walls, and explode somewhere.
This also happens when you spawn it in the air, if it hits the floor it will do the same glitch.

To reproduce the issue, spawn a sentry turret while in the beta. Spawn a human in front of it. As soon as it starts targeting them, it will fly around and explode. Alternatively, spawn it in the air by a few meters.

**Comment by DindinYT37** [comment]
Please use the template. But I can entirely confirm this happens, even without a human in front of it.

**Comment by mestiez** [comment]
I need more information because this doesn't happen in an unmodded game as far as I can tell
