### ISSUE TITLE
Sentry turret shots are louder when activated

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1572]
**Describe the bug**
When a sentry turret fires by activation, it is louder

**Clearly describe how to reproduce the bug**
1. Spawn turret
2. Activate it
3. Tip it over or make it shoot something
4. Compare sound volume

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9023745/exported.game.debug.info.md)

**Additional notes**

https://user-images.githubusercontent.com/104321411/176789058-cd4096b1-4499-4ea0-8dc1-c52dce62954e.mp4

**Comment by mestiez** [comment]
Not a bug. The initial shot of a weapon is always a bit louder than the following shots to prevent listening fatigue. Try it with any other gun. Automatic firing is less loud than semi automatic.
