### ISSUE TITLE
Machine Blaster makes metal sounds instead of weapon sounds

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1573]
**Describe the bug**
Slamming a machine blaster to the ground produces metal sounds instead of weapon sounds like the other blasters do

**Clearly describe how to reproduce the bug**
1. Spawn machine blaster
2. Slam it
3. Hear that it makes metal sounds

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9023879/exported.game.debug.info.md)

**Additional notes**
Beam Rifle has the same problem

**Comment by mestiez** [comment]
not a bug it is just big
