### ISSUE TITLE
Weapon audio/other changes

### ISSUE THREAD

**Issue by Uniconrzss** [studio-minus/ppg-bugs-and-requests#1576]
**Feature description**
List of changes to weapons that would be cool:

Add backblasts to Bazooka and Rocket Launcher, this means if a person is standing behind the weapon they will get burnt by the backblast. (Maybe this one could be toggleable in some way cause i would immagine this could break some contraptions like tanks that use theese.)
The audio of the Light Machine Gun sounds more mechanical and not really like an actual machine gun shooting, a faster version of the ak-47 audio would sound better in my opinion. Also the shooting sound effect for the G1 also sounds meh compared to the normal smg.
Another thing i would like to see is the Missile Launchers missiles track flares that are on fire

**Feature purpose**
Backblasts would be cool and audio for some of the weapons also would be cool.

**Additional context**

**Comment by DindinYT37** [comment]
Multi-requests can't/won't be accepted. Also, most of these were already suggested.

**Comment by Uniconrzss** [comment]
> Multi-requests can't/won't be accepted. Also, most of these were already suggested.

Who are you to tell me that

**Comment by DindinYT37** [comment]
> > Multi-requests can't/won't be accepted. Also, most of these were already suggested.
> 
> Who are you to tell me that

Person who knows the rules, and tells you about them before your request gets rejected by zooi.

**Comment by Uniconrzss** [comment]
> > > Multi-requests can't/won't be accepted. Also, most of these were already suggested.
> > 
> > 
> > Who are you to tell me that
> 
> Just a person who knows the rules, and tells you about them before your request gets rejected by zooi.

Then just let zooi reject it. It sounds very snobby when you write that.

**Comment by DindinYT37** [comment]
> > > > Multi-requests can't/won't be accepted. Also, most of these were already suggested.
> > > 
> > > 
> > > Who are you to tell me that
> > 
> > 
> > Just a person who knows the rules, and tells you about them before your request gets rejected by zooi.
> 
> Then just let zooi reject it. It sounds very snobby when you write that.

I am literally just telling you that this request is against one of the few rules an issue here is supposed to follow, it doesn't sound snobby in any way - I'm just informing you of this since you might be interested in splitting your request instead, as it significantly increases your chances of being accepted. Literally anyone has the right to tell you about this, it's preposterous that you think nobody but zooi has the right to give you a pointer on how to get your request to be more likely to be accepted.

**Comment by mestiez** [comment]
awesome comment section as always

**Comment by mestiez** [comment]
and yes please do not group requests as they cant be individually accepted or rejected
