### ISSUE TITLE
pausing moving the CBM machine while the wheels are selected causes positional errors 

### ISSUE THREAD

**Issue by BBQGiraffe** [studio-minus/ppg-bugs-and-requests#1577]
**Describe the bug**
moving a CBM machine while its wheels are selected and the game is paused causes the wheels go be offset incorrectly 

**Clearly describe how to reproduce the bug**

- spawn a CBM machine
- pause the game
- highlight the machine + wheels
- move it around
-
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9026837/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
What's a CBM machine?

**Comment by BBQGiraffe** [comment]
> What's a CBM machine?

cardiopulmonary bypass machine, it's in the new preview 1 update

**Comment by Polyicio** [comment]
Just do I don't have to make an additional report on this, I'd also add the fact that this happens with the normal "motorized wheel" item as well.

**Comment by mestiez** [comment]
Holy shit I fucked up here. Had `phys != null` instead of `phys == null` somewhere in the dragging tool code. Fixed.

**Comment by mestiez** [comment]
Note to Unity if you're ever reading this: let go of Mono, update to .NET 6, and enable nullable checks. It could've prevented this
