### ISSUE TITLE
Chunks of flesh in goreless mode

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1579]
**Describe the bug**
The chunks of flesh while shooting fleshy limbs still appear in goreless mode

**Clearly describe how to reproduce the bug**
Turn on goreless mode and shoot a human in a place such as the torso.

**Additional notes**
A solution would either be to remove them or to make them yellow to be consistent with the rest of goreless mode.

**Comment by mestiez** [comment]
fixed
