### ISSUE TITLE
Objects with secondary moving objects move weirdly in pause time

### ISSUE THREAD

**Issue by NobleIsTaken** [studio-minus/ppg-bugs-and-requests#1582]
**Describe the bug**
Whenever the player is dragging an object that has another object connected to it natively (such as pistons and rotors) while having selected both of the objects, the secondary object is moved exponentially, away from the primary object.

**Clearly describe how to reproduce the bug**
Place down any object that features a moving object with it, such as a rotor or piston.
Stop time
Select both objects with drag click
Try to move them

**Mod List & Specs in Attached File**
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9030698/exported.game.debug.info.md)

**Comment by mestiez** [comment]
Duplicate
