### ISSUE TITLE
Invisible Stringy Tissue

### ISSUE THREAD

**Issue by PossiblyRemember** [studio-minus/ppg-bugs-and-requests#1584]
**Describe the bug**
The stringy tissue when dismembering people is invisible near the right of almost every map I've tested.

**Clearly describe how to reproduce the bug**
Dismember a human near the right side of hybrid or lava.

**Mod list**
Tested with and without mods.

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.25 Preview 2
 - GPU: NVIDIA GeForce GTX 1080
 - CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Additional notes**
I've only tested hybrid and lava maps

**Comment by Gigi-7688** [comment]
This can happen on all maps

**Comment by mestiez** [comment]
I have fixed the issue I think

**Comment by mestiez** [comment]
Don't hesitate to reopen if you still encounter it after or on preview 3

**Comment by PossiblyRemember** [comment]
> Don't hesitate to reopen if you still encounter it after or on preview 3

will do

**Comment by PossiblyRemember** [comment]
It doesn't seem to be fixed :/
