### ISSUE TITLE
Hydraulic Press

### ISSUE THREAD

**Issue by Verycoolgarfield** [studio-minus/ppg-bugs-and-requests#1586]
**Feature description**
A hydraulic press that when activated, well...presses!

**Feature purpose**
The hydraulic press can crush all crushable objects like walls and human. It's can eventually break through anything as it slowly builds up psi.
It well overheat at 1000° or from heavy friction. It's pressure can't be stopped by anything but the 1 ton weight. If a machine that can't be crushed is put in it will just break the machine and make it stop functioning.

**Additional context**
The Hydraulic Press would be a really cool thing to have and I hope to see it in the game!

**Comment by Drogo-man** [comment]
That's just a piston. THATS LITERALLY HOW PISTONS WORK.

**Comment by Verycoolgarfield** [comment]
Pk

**Comment by Verycoolgarfield** [comment]
I'm someone who doesn't mess with the game much so sorry about that.
