### ISSUE TITLE
Penetrating Fall Damage

### ISSUE THREAD

**Issue by SomeBloodyMinger** [studio-minus/ppg-bugs-and-requests#1587]
**Feature description**
Fall damage that transfers through body parts more. For instance, someone falls a high distance and lands on their legs. In the game's current state, only their legs and other body parts that collide with the ground will sustain realistic damage. The sudden stop in hitting something at high speed will damage/ break parts of the body not even involved in the collision itself. 

**Feature purpose**
To make the fall damage in the game more realistic. In my gameplay, I have dropped people from VERY high heights which, without any resistance, should have killed them. However, they still survived around 80% of the time despite, and it was only their lower body parts that were completely destroyed. The LD50 in real life from falling is just over 4 stories, so perhaps you could base the calculations off of that? Nonetheless, I appreciate what you've done with this game very much; and can find myself entertained very easily. 

**Additional context**
![Screenshot (447)](https://user-images.githubusercontent.com/70472570/176988264-677bd592-3984-4837-92e3-8c26be9879ba.png)
_Image showing how far the ragdoll fell, with another human as a reference on the left. The height could be comparable to a skyscraper._
![Screenshot (448)](https://user-images.githubusercontent.com/70472570/176988307-c9707d6e-d9c7-4779-885c-48a931f935f3.png)
_Image showing the result of the fall. Most of the body is still intact, save for mild damage on the head and only the total destruction of some parts of the appendages. These appendages were only destroyed because of their direct collision with the ground._

These examples I took were without mods on the Preview build.

**Comment by SomeBloodyMinger** [comment]
I forgot to mention that, at this height, there were also no broken bones, even in the legs that sustained the brunt of the fall damage.

**Comment by Verycoolgarfield** [comment]
This is actually a really good idea.

**Comment by GitNeto** [comment]
Give this man a raise

**Comment by Drogo-man** [comment]
This is why we have very strong femurs. So that the legs take all of the impact.

**Comment by mestiez** [comment]
Sudden velocity changes do inflict integrity damage in the game currently, but it does not cause bruising.
4 storeys, according to Google, is approximately 12 meters. I'll increase impact damage in general and try some stuff to simulate impact damage propagation

**Comment by mestiez** [comment]
Okay the damage propagation has been implemented and 12 meters is lethal if the human lands in an unfortunate pose.

**Comment by SomeBloodyMinger** [comment]
Doing God's work, my friend.
