### ISSUE TITLE
More settings in the gore settings

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#1588]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by Drogo-man** [comment]
You, didn't even request anything?!?

**Comment by PossiblyRemember** [comment]
I think he just accidentally posted this one, he posted another by the same name that's still open and is actually a request
