### ISSUE TITLE
"Unbreakable" Option for Machines in Context Menu

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#159]
**Feature description**
Add "Make Unbreakable" for Machines in the Context Menu

**Feature purpose**
Pretty obvious. For example: When I use a 120mm Cannon with an Industrial Gyrostabiliser attached on the top of it and shoot it, it's breaking and the Unbreakable option would prevent that.
That was just one of the Examples though it can open many new opportunities.

**Comment by mestiez** [comment]
I kind of like limitions like this. It forces the player to be creative. Sandbox games with complete and total freedom would stop beings games imo. Though maybe this feature does not yet reach that threshold and should be implemented? Do not know

**Comment by DindinYT37** [comment]
I mean, it's optional. People can decide by themselves if they want to try it with a creative method or do it the simple way. Also it can also *boost-creativity* because more compact builds would be possible.
It's just my opinion but I think adding it as an option is a good idea.

**Comment by JohnVcav** [comment]
maybe a machine that makes other machines have really high (not infinite) HP?
or make the wrench increase max HP of a machine?

**Comment by DindinYT37** [comment]
> maybe a machine that makes other machines have really high (not infinite) HP? or make the wrench increase max HP of a machine?

I don't wanna necropost or something but this might be the solution for this issue. Attaching this other Machine to the Original would increase the Durability of the Original and (using Electricity-Power) increase the durability further.
_This would, of course, require the Durability-Increasing Machine to either increase its own Durability as well or just have a high Durability by default._

**Comment by JohnVcav** [comment]
> I cannot agree on the Wrench part though, it would just be the same thing, but way slower and manually instead of right click and setting it. I don't know though, I am not the decision-maker here.

I'm glad we agree on the machine part, it would be interesting to have something like a "repair station", and the wrench idea was more of a random idea that I threw out there.

more or less I was speaking of an item that would increase a machine's durability like something related with nanomachines, 
 or a welder (imagine that you'd be welding something like tungsten or titanium, but you wouldn't see it)

**Comment by DindinYT37** [comment]
> Destructible machinery can now be made indestructible using the context menu

It seems this has been [added to the Changelog](https://github.com/studio-minus/people-playground-changelog/blob/master/CHANGELOG.md#:~:text=Destructible%20machinery%20can%20now%20be%20made%20indestructible%20using%20the%20context%20menu) but not marked as accepted.

**Comment by mestiez** [comment]
yes correct
