### ISSUE TITLE
Option for "auto reloading"

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1594]
**Feature description**
Okay, okay, hear me out mestiez! There would be an option for each gun to have a fixed magazine size, and after it runs out, it stops firing, plays a reload sound, and can shoot again.

**Feature purpose**
This adds a realism factor. In my military roleplays I don't like how the guns are infinite. If someone doesn't like this, they can simply turn it off! Simple!

**Comment by DindinYT37** [comment]
There are mods for this kinda stuff.

**Comment by SirAJ4895** [comment]
Yes, but you need to manually reload them, this would be automatic

**Comment by DindinYT37** [comment]
> Yes, but you need to manually reload them, this would be automatic

If it's gonna do it automatically, why have it in the first place?

**Comment by SirAJ4895** [comment]
So we don't have infinite magazine sizes, it just feels wrong

**Comment by DindinYT37** [comment]
> So we don't have infinite magazine sizes, it just feels wrong

That will just take away freedom of the whole "sandbox" aspect of the game.

**Comment by SirAJ4895** [comment]
I already said, it would be toggleable, it would be good for action scenes

**Comment by DindinYT37** [comment]
> I already said, it would be toggleable, it would be good for action scenes

Your whole request makes no sense at all, there are mods for this. "Yeah but you have to reload it manually with them", then why the frick do you even want to have it reload? Not to mention that you could probably ask the maker of the reloadable weapons mod to add an "automatic" option, though it's likely he'd say the same thing I just did.

**Comment by SirAJ4895** [comment]
I just don't want it to shoot forever. Sorry I upset you, I just try to help make this game better ;-;

**Comment by PossiblyRemember** [comment]
> I just don't want it to shoot forever. Sorry I upset you, I just try to help make this game better ;-;

don't let him get ya down, zooi will decide and I can make a mod if that's what ya want

**Comment by SirAJ4895** [comment]
Thanks 👍

**Comment by PossiblyRemember** [comment]
> Thanks 👍

np, I'll send a link when it is finished

**Comment by DindinYT37** [comment]
> I just don't want it to shoot forever. Sorry I upset you, I just try to help make this game better ;-;

I'm not upset but this won't make the game better, this is a mod thing.

**Comment by DindinYT37** [comment]
> > ...and I can make a mod if that's what ya want
> 
> I am already making a mod

Bro that's literally quoted from you

**Comment by PossiblyRemember** [comment]
> > > ...and I can make a mod if that's what ya want
> > 
> > I am already making a mod
> 
> Bro that's literally quoted from you

I am, I'm also tired, you also quoted yourself, so cool you made a suggestion and obvious comment, ggs mate

**Comment by DindinYT37** [comment]
> > > > ...and I can make a mod if that's what ya want
> > > 
> > > 
> > > I am already making a mod
> > 
> > 
> > Bro that's literally quoted from you
> 
> I am, I'm also tired, you also quoted yourself, so cool you made a suggestion and obvious comment, ggs mate

I haven't quoted myself. Also, what do you mean suggestion and obvious comment?

**Comment by PossiblyRemember** [comment]
> > I am, I'm also tired, you also quoted yourself, so cool you made a suggestion and obvious comment, ggs mate
> 
> I didn't even quote myself...

yeah sorry about that I had a long night, hopefully today is better
