### ISSUE TITLE
Detectors don't detect anything at all (1.25 preview)

### ISSUE THREAD

**Issue by Madkirk74** [studio-minus/ppg-bugs-and-requests#1597]
Detectors aren't detecting anything at all. none of them are.

place a detector and activate it.

I have a lot of mods but I loaded the map before any compiled

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9033837/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
Please use the template.

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/177165564-e5124469-ca59-496e-a5a0-6b5a78f9f118.png)
they work for me... closing until more information is provided
