### ISSUE TITLE
Internal Bleeding

### ISSUE THREAD

**Issue by Jandro22** [studio-minus/ppg-bugs-and-requests#160]
**Feature description**
Bleeding but internally. Could be caused by fast blunt force to the head or torso (Arms and legs would also suffer it but it would be on a lesser scale, as I doubt bleeding inside of your arm is AS bad as bleeding in your stomach). This is opposed to external bleeding that is usually caused by a sharp object like a glass shard or a knife. You would not see any blood effects (It's internal), but you would be able to notice deterioration of their health via more the more detail key (S by default). You would treat it with a coagulation syringe, which would stop the internal bleeding. I know real life internal bleeding can happen with both sharp and blunt, but I feel like sharp objects already have a good bleeding system, and this would be repeating it, so I'm sticking with blunt for now with this idea. I don't know if internal bleeding should be noticeable without the detail key, but if you wanted to do that, maybe make it so they are noticeably impaired? (Waving their arms in the air/stumbling slightly, not enough to move them but enough to notify the player that something is wrong with them maybe?). An additional idea would be to have head internal bleeding cause even more impairment than mentioned before (Almost like a stroke?) Internal bleeding would occur also if they fell a large enough distance (The kind of fall where it's not enough to kill them, but enough for it to not make sense if they could walk it off)

**Feature purpose**
The point of this is that I feel like if you drop a brick onto someone's stomach and crush it, they are perfectly fine apart from that body part being crippled in game. With this feature it would actually be a deadly situation as the bleeding from the crushed stomach could eventually kill them.

**Comment by TamasB14** [comment]
"sharp objects already have a good bleeding system" - Bleeds out even if the knife is inside.

**Comment by DindinYT37** [comment]
> "sharp objects already have a good bleeding system" - Bleeds out even if the knife is inside.

See #121 Point 1

**Comment by mestiez** [comment]
good idea and cool

**Comment by mestiez** [comment]
> Another big note is that internal bleeding should be toggleable, as some players may find it annoying, while others may find it a great feature. I feel like it should be optional, like expandable gore.

unlikely ill make it a toggleable thing. why would internal bleeding be optional if external bleeding isnt. you could always argue that some players wont like a new feature but at that point they should make their own game or mod or whatever, i cant make every single thing optional just in case seven people lose their mind
