### ISSUE TITLE
Double Trigger Laser Receiver

### ISSUE THREAD

**Issue by HiMemX** [studio-minus/ppg-bugs-and-requests#1600]
Ya'll know how detectors, for example, can be set to "single trigger" and "double trigger"? So that the hooked up thing is activated when the detector detects something and deactivated when it doesn't detect anything?
This should be added to the Laser Receiver.

I wanted to build some logic gates using lasers, but I couldn't do it because the receiver doesn't do anything once it stops detecting the laser.
In general, just to make this "Double Trigger" option more consistent, I think it should be added to Laser Receivers aswell.

I'm pretty sure you could also make a mod for this but I have been staring at cheat engine and the modding wiki for like 3 hours now and I just can't do it. If someone does know how to do it however, please share your knowledge with me! Would still love to make a custom receiver out of it.

**Comment by DindinYT37** [comment]
Please use the template. Also, what you've just mentioned is the reason why people usually just use a detector (usually metal) and some pistons.

**Comment by HiMemX** [comment]
> Please use the template. Also, what you've just mentioned is the reason why people just use a detector (usually metal) and some pistons.

I did use the template. 
"Describe the feature" - Check (First paragraph)
"Describe the purpose" - Check (Second paragraph)
"Additional Context" - Check (Third paragraph)

Also just because "people" do it differently doesn't mean it's the better way of doing it.

**Comment by DindinYT37** [comment]
> > Please use the template. Also, what you've just mentioned is the reason why people just use a detector (usually metal) and some pistons.
> 
> I did use the template. "Describe the feature" - Check (First paragraph) "Describe the purpose" - Check (Second paragraph) "Additional Context" - Check (Third paragraph)
> 
> Also just because "people" do it differently doesn't mean it's the better way of doing it.

Exactly, if you do it differently doesn't mean it's the better way of doing it. So you should just use the generally accepted as good way of doing it and use the template. Not to mention that you used it wrong, as you have removed the headers alongside with the placeholders (that should be removed, obviously) - which basically renders the whole template useless as we cannot guess what each paragraph of yours mean if you don't specify it. Do you expect literally every person here to memorize the meanings of each section?

**Comment by HiMemX** [comment]
> 

Guy calm down. I clearly seperated it into 3 parts, it doesn't take a genius to figure out which means what. But it doesn't matter, I have clearly shown what I'd like added and the reasons why.

**Comment by DindinYT37** [comment]
> > 
> 
> Guy calm down. I clearly seperated it into 3 parts, it doesn't take a genius to figure out which means what. But it doesn't matter, I have clearly shown what I'd like added and the reasons why.

I'm not mad or something, but your attitude in that comment was simply stupid. "I clearly separated it into 3 parts" - so you do expect literally everyone that reads your issue to know the template by memory?

**Comment by HiMemX** [comment]
> I'm not mad or something, but your attitude in that comment was simply stupid. "I clearly separated it into 3 parts" - so you do expect literally everyone that reads your issue to know the template by memory?

![Discordmod](https://user-images.githubusercontent.com/99434376/177050132-fb275e7b-b537-46d0-9142-55d296e7af62.png)

**Comment by GitNeto** [comment]
> > I'm not mad or something, but your attitude in that comment was simply stupid. "I clearly separated it into 3 parts" - so you do expect literally everyone that reads your issue to know the template by memory?
> 
> ![Discordmod](https://user-images.githubusercontent.com/99434376/177050132-fb275e7b-b537-46d0-9142-55d296e7af62.png)

hahaaahhahahahhahahhhaah
