### ISSUE TITLE
Stone brick is very soft, has quiet sound and is quite light and does not couse damage

### ISSUE THREAD

**Issue by Fredr1g0** [studio-minus/ppg-bugs-and-requests#1601]
**Describe the bug**
Stone brick is very soft, has quiet sound and is quite light and does not couse damage

**Clearly describe how to reproduce the bug**
Spawn brick

**Mod list**
No mods

**System info (please complete the following information)**
 - Operating system: win 10
 - Game version: Preview build 1.25
 - GPU: GTX 850M
 - CPU: i7 2.20 Hz

**Additional notes**
Thanks for your attention

**Comment by DindinYT37** [comment]
It'd be nice if you would give your issue a "proper" name, as simply saying "a flaw" is not informative of what the issue is at all.

**Comment by mestiez** [comment]
I made it a bit heavier but I don't really see the issue regardless
