### ISSUE TITLE
Cardiopulmonary Bypass machine bug with heart monitor not updating the bpm propertly (1.25 preview)

### ISSUE THREAD

**Issue by dadocastro2801** [studio-minus/ppg-bugs-and-requests#1603]
**Describe the bug**
Human with stopped heart, Cardiopulmonary Bypass machine and two heart monitors will show different bpm rates.
It also won't update when turned off and on

**Clearly describe how to reproduce the bug**
Engange a heart monitor, stop a human heart, start the Cardiopulmonary Bypass machine and engange another heart monitor 

**Mod list**
(All of them inactive)
ArstotzkaMinisterArstotzkas World War Mod
Aspa102Wheelchair
Aubarino-Functional Terminator Mod-2809137426
averageD-Day Map
Azule Quickness-Fish Mod-2599934778
Camdog74-Power Pack Framework-2506978276
citizen-Modern Firearms-2721105504
citizen-Reloadable Explosive Weapons-2799000030
cttc321-DUBSTEP MOD-2595385255
Decibek-Great Gorge-local
Digito-Operation LSA Forces MARSOC MAROSC UPDATE AND GENERAL APOLOGY-2824743154
FasolGDangerZone - SCP-610 Mod -2626113140
FredMichalBear-Happy Wheels mod-local
FredMichalBear-Special testing facility NPC pack-local
FredMichalBearHappy Wheels mod
GDEATHP-GDEATHPs Arsenal-2390309073
Hoodirony360NoscopeSlayer666Pokio City
kirillX-Doll for tests 2-local
kubason-Oil Mod-local
Kyrelink-The Helicopter Mod-local
Kyrelink-Minecraft Blocks mod
LijmPistool Nightzz-Army Mod-2592640598
Mini-City People-2376820541
MiniCity People
Mishanya-Functional Devices Mod-local
Mishanya-The Ultimate Car Mod-2795171453
moonSIqSecure Contain Protect SCP MOD
Morzzic-Object Editor-2590195142
Morzzic-Taser-2361892819
Morzzic-Water Physics-2793815479
MrkWKDHumans
Mumu-Imperial Naval Base Map-local
MumuImperial Naval Base Map
obichnichelovek-MeleeWeaponPack-2803952558
Orsoniks  Navii-Blood on walls-2782471815
Orsoniks  Navii-Reactive humans-2793371344
Orsoniks-A Crap Ton Of Damage-2603531653
OrsoniksNavii-Husk Overdose-local
OzimekPL-SCP Foundation Expanded-2388808764
pjstarr12-SCP-Foundation Mod WIP-2612646839
Pump3d-Quick Right Click Options-2516131949
quaq-Active Humans-2163278857
Quickness-More Vehicles-2805966221
RadioactiveE3-SCP PPG Edition-2643873749
ScriptMeat-Volcanic Map-2395054754
ScriptMeatVolcanic Map
Streamed Hams-Weird Humans-2714221016
Talon Zane-Map Blocks-local
Talonphobia-Syringes-2146791852
Team Wilson FriedFox Blocksify Frevv Colonel Augustus fR4n1oo0 GrinnyBeanie  Aspa-DC Power Pack-2657417307
Team Wilson-People Playground 3D-2785176210
Team Wilson-Team Wilsons John Wick Mod-2642461744
Team WilsonMarvel Power Pack
Teletubbie With A Shotgun-SCP Secret Laboratory-local
ThatFNAFModDev-FNAF Mod FNAF 1-2543035567
TSF Lifeexe-SCPF mod-2332568618
zuccian-Symbiote Playground-local

**System info (please complete the following information)**
 - Operating system: Windows 11 Home Build 22621.105
 - Game version: 1.25 Preview
 - GPU: NVIDIA GeForce RTX 2060
 - CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz

**Additional notes**
![imagen_2022-07-03_195631006](https://user-images.githubusercontent.com/67091340/177051674-1bf82127-d994-44dd-aecc-b46cdb3fdfb0.png)

**Comment by mestiez** [comment]
fixed :)
