### ISSUE TITLE
Muzzle blast can cause concussive damage

### ISSUE THREAD

**Issue by 69XAnonymousX69** [studio-minus/ppg-bugs-and-requests#1604]
**Feature description**
Basic training
**Feature purpose**
to implement Muzzle blast
**Additional context**
https://en.wikipedia.org/wiki/Muzzle_flash (light)
https://en.wikipedia.org/wiki/Muzzle_blast

**Comment by DindinYT37** [comment]
What do you mean "Basic training"? Also, that's not what "Feature purpose" is for - the purpose of your request would probably be "realism".

**Comment by toobusywithanythingforanything** [comment]
pretty smart idea

**Comment by mestiez** [comment]
I have 0 idea what any of this means

**Comment by 69XAnonymousX69** [comment]
> I have 0 idea what any of this means

here is a video that might help you understand it
https://youtu.be/Vt9DzhoTnjU?t=243
