### ISSUE TITLE
Burst Missile Launcher

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1605]
**Feature description**
This is very similar to the Missile Launcher, but it fires a blast of 3 missiles, similar to a shotgun

**Feature purpose**
I originally found out that if you pause the game and activate the Missile Launcher 3 times, you can make it do a 3-missile blast. I think this would be a fun weapon, because isn't that the entire point of this game, to be fun?

**Comment by DindinYT37** [comment]
You can just build this yourself. Usually I wouldn't say this but what you described really isn't hard to make.

**Comment by SirAJ4895** [comment]
Why don't you build it yourself and upload it to the workshop then if it's so easy

**Comment by DindinYT37** [comment]
> Why don't you build it yourself and upload it to the workshop then if it's so easy

https://steamcommunity.com/sharedfiles/filedetails/?id=2830522689

**Comment by SirAJ4895** [comment]
Thanks

**Comment by DindinYT37** [comment]
> Thanks

If this solved your problem, I suggest closing this.

**Comment by Drogo-man** [comment]
Flieger Faust indeed.
