### ISSUE TITLE
Invisible Stringy Tissue

### ISSUE THREAD

**Issue by PossiblyRemember** [studio-minus/ppg-bugs-and-requests#1608]
**Describe the bug**
The stringy tissue when dismembering people is invisible near the right of almost every map I've tested.

https://user-images.githubusercontent.com/105954143/177209567-e8607a20-3f7d-483e-a2b0-ec86d174969e.mp4

*Sorry for the bad quality, had to reduce the quality so it would actually send*

**Clearly describe how to reproduce the bug**
Dismember a human near the right side of almost any map.

**Mod list**
Tested with and without mods.

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.25 Preview 3
 - GPU: NVIDIA GeForce GTX 1080
 - CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Additional notes**
Still happens on 1.25 Preview 3

**Comment by DindinYT37** [comment]
I think you're supposed to just reopen #1584.

**Comment by Verycoolgarfield** [comment]
Huh I didn't know about this bug

**Comment by PossiblyRemember** [comment]
> I think you're supposed to just reopen #1584.

idk how to reopen

**Comment by DindinYT37** [comment]
> > I think you're supposed to just reopen #1584.
> 
> how do I reopen?

Nevermind. I checked and it seems that you can only reopen issues if you closed them, and since zooi closed your issue that won't work. I guess this one's fine then.

**Comment by PossiblyRemember** [comment]
> > > I think you're supposed to just reopen #1584.
> > 
> > 
> > how do I reopen?
> 
> Nevermind. I checked and it seems that you can only reopen issues if you closed them, and since zooi closed your issue that won't work. I guess this one's fine then.

ah, ok, thanks for the reply tho

**Comment by mestiez** [comment]
fixed!! thanks for reporting
