### ISSUE TITLE
Have I gone insane yet?

### ISSUE THREAD

**Issue by KomodoBro** [studio-minus/ppg-bugs-and-requests#161]
![image](https://user-images.githubusercontent.com/88641283/131268538-b02ecf7e-fc32-46ab-bd6e-5e6327436e7f.png)

I have 770 hours in PPG please help me

**Comment by BBQGiraffe** [comment]
you'd think moving the issues from a discord server to GitHub would prevent brain damaged 13 year olds

**Comment by mestiez** [comment]
banned
