### ISSUE TITLE
Humans still regenerate blood too quickly

### ISSUE THREAD

**Issue by SeVeredC0nnection** [studio-minus/ppg-bugs-and-requests#1615]
**Describe the bug**
Humans still regenerate blood faster than they should after certain injuries (for instance survive for up to 5 minutes after literally being blown in half)

**Clearly describe how to reproduce the bug**
Cut a human in half from below the heart

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.25 preview
 - GPU: RTX 3090
 - CPU: i9-10900KF 

**Additional notes**
None

**Comment by mestiez** [comment]
I made it so that blood does not regenerate if the limb is bleeding or dismembered, that should help
