### ISSUE TITLE
Androids having really stupidly low durability

### ISSUE THREAD

**Issue by Blessedsolaris** [studio-minus/ppg-bugs-and-requests#1617]
**Describe the bug**
Androids having really low durability, easily destroyed by blunt weapons.

**Clearly describe how to reproduce the bug**
uh destroy an android with a blunt weapon????
**Mod list**
vanilla (unmodded)

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU: Amd Radeox Rx 6600
 - CPU: AMD ryzen 5 3600 6 core

**Additional notes**

**Comment by mestiez** [comment]
I can't reproduce this? I've been hitting an android with the huge spike and the most I can do is cause temporary fainting.
