### ISSUE TITLE
Stab weapons acting as "bleeding" plugs.

### ISSUE THREAD

**Issue by TamasB14** [studio-minus/ppg-bugs-and-requests#162]
**Feature description**
It's all about that if you stab someone in the chest, it won't bleed until you take the sword/spear/knife/etc. out.

**Feature purpose**
Adds realism and of course prevents my ragdoll bleeding to death from a stab in the stomach with the knife inside, giving you a fine RP about how the ambulance comes and takes out the knife after hitting that poor guy with the coagulation syringe.

**Additional context**
If you stab someone in real life, they won't bleed until you take out of the knife, or someitmes they'll only bleed very little. I just don't want my ragdolls I silently killed to bleed like it's some arterial shot. (Surely talking by experience)

**Comment by ToxicSnake48** [comment]
I would love this
