### ISSUE TITLE
Can't move my camera with middle click.

### ISSUE THREAD

**Issue by RedactedUnicorns** [studio-minus/ppg-bugs-and-requests#1620]
When I middle click, the camera doesn't move most of the time. When it does, it stops moving after a second or two. This issue affects both me and some (not all) of my friends. This is not a hardware issue. Middle click works outside the game.

Middle click and attempt to move the camera.

Active Humans, Feet Aren't Indestructible, and Human Dynamic Emotions (All inactive.)

**System info (please complete the following information)**
 - Operating system: Windows
 - Game version: 1.24.6 (64 Bit)
 - GPU: NVIDIA GeForce RTX 2070
 - CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz

**Comment by mestiez** [comment]
Do you have a controller attached?

**Comment by RedactedUnicorns** [comment]
Ah, sorry for the mistake.

I did already attempt validating game files and reinstalling; those are
some of my go-tos when troubleshooting. I also uninstalled all mods and it
didn’t fix.

**Comment by RedactedUnicorns** [comment]
No, I do not.
