### ISSUE TITLE
Gun attachments

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#1623]
**Feature description**
Thingies that you can attach to picatinny rails on the weapons like grips, sights, stocks, muzzles, flashlights etc.

They would be attached by slamming them in and removed by slamming them with the wrench or by context menu

Some attachments will be interactive like extendable stocks

**Feature purpose**
Mods that provide attachments require you to manually put them using wires, the wires are visible and steel binding is destructible, where's the fun in that?

Also, humans can and **will** grab the weapon instead of the custom grip, this could be solved by attachments disabling the gripping on the  weapon part

**Comment by mestiez** [comment]
This has been in the "Wishful Thinking" list for quite a while now
