### ISSUE TITLE
Customisable energy sword using the right click menus

### ISSUE THREAD

**Issue by RonaBtheCodeR** [studio-minus/ppg-bugs-and-requests#1624]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?
A customisable menu for the Energy sword, so you can customise the shape, colour, handle, damage or whatever.

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?
I saw an image someone posted in the Studio Minus discord which was from another game where you could customise a lightsaber-esque energy sword. Even though this would be pretty hard to implement, i feel like it could add some depth to the game.

**Additional context**
![image](https://user-images.githubusercontent.com/80098646/177552105-59af45ef-e099-411b-88cd-92e742946c14.png)
![image](https://user-images.githubusercontent.com/80098646/177552253-c1f452a4-93be-4f9e-999f-abdbe192e476.png)

**Comment by Drogo-man** [comment]
Reupload lol

**Comment by Drogo-man** [comment]
Shiii nevermind
