### ISSUE TITLE
a animal

### ISSUE THREAD

**Issue by bonesyt101** [studio-minus/ppg-bugs-and-requests#1626]
**Feature description**
spawnible maybe a cat dog deer idk. it would be a alive thing. and it wwould be good for hunting

**Feature purpose**
just a cool thing too add

**Additional context**
nop

**Comment by Drogo-man** [comment]
Too cruel. Animals didn't do anything wrong.

**Comment by Drogo-man** [comment]
Too cruel. Animals didn't do anything wrong.

**Comment by PossiblyRemember** [comment]
> Too cruel. Animals didn't do anything wrong.

I would like to agree, but then what did the humans do wrong?

**Comment by Drogo-man** [comment]
> > Too cruel. Animals didn't do anything wrong.
> 
> I would like to agree, but then what did the humans do wrong?

Everything

**Comment by PossiblyRemember** [comment]
> > > Too cruel. Animals didn't do anything wrong.
> > 
> > 
> > I would like to agree, but then what did the humans do wrong?
> 
> Everything

*dramatic music starts playing*

**Comment by PossiblyRemember** [comment]
> > > > > Too cruel. Animals didn't do anything wrong.
> > > > 
> > > > 
> > > > I would like to agree, but then what did the humans do wrong?
> > > 
> > > 
> > > Everything
> > 
> > 
> > _dramatic music starts playing_
> 
> Don't forget the image being inverted.

![image](https://user-images.githubusercontent.com/105954143/177654927-cbe53aa8-b7e7-4a6e-9536-f0dbb7df5988.png)

**Comment by bonesyt101** [comment]
*doom music starts playing*

**Comment by bonesyt101** [comment]
run

**Comment by PossiblyRemember** [comment]
![image](https://user-images.githubusercontent.com/105954143/177666481-5e0b6d0f-1c70-4564-a01c-61e47b79da56.png)
