### ISSUE TITLE
"Human Toughness multiplier"

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1633]
**Feature description**
Add a slider where you can increase or decrease human toughness in the settings.

**Feature purpose**
THEY'RE SO WEAK! When I throw one onto his back, blood decals appear! In real life, when you get pushed onto a hardwood floor, you may get hurt and bruised, but not FRICKING BLEED EVERYWHERE! Not to mention sometimes when you lay them on their back, they kick the ground and fall asleep. They don't make an effort to even bend their knees, just kick the ground. Another thing, when you try to make them sit without a chair, they fall onto the floor and BLOOD DECALS APPEAR! WHY IS HE BLEEDING IF HE FELL OVER!? These humans need to be stronger! It takes the fun out of the game with how weak they can be, especially how easy it is for bruises to appear.

**Comment by DindinYT37** [comment]
I'm pretty sure you're just annoyed that the blood decal is appearing everywhere, not that he's actually bleeding. Basically what I mean is the problem here would be that blood decals appear even on the slightest decrease of health in a limb, even if it's not actually affecting the human's performance at all.

**Comment by SirAJ4895** [comment]
Correct. I just wrote this in a fit of rage because my humans won't stop creating blood decals whenever I try to do normal things with them.

**Comment by PossiblyRemember** [comment]
> Correct. I just wrote this in a fit of rage because my humans won't stop creating blood decals whenever I try to do normal things with them.

so why didn't you write about the blood decals instead?
