### ISSUE TITLE
Centre of mass/visual centre stays after deletion

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#164]
**Describe the bug**
When deleting an item that you can see the centre of mass of, it will jump to what I think is the world origin or something. Same place as negative hover thruster went.

**Clearly describe how to reproduce the bug**
Spawn in an object,
Select the object,
Turn detail view on,
Delete the object.

**Mod list**
none

**Additional notes**
Also centre of mass/visual centre sometimes doesn't show up until you zoom out or move the camera a bit.
![image](https://user-images.githubusercontent.com/69184577/131411647-b348d726-a945-4da4-b8d4-5c743e46c9e4.png)

**Comment by mestiez** [comment]
fixed :)
