### ISSUE TITLE
Repelling Electromagnet

### ISSUE THREAD

**Issue by MegaKonami** [studio-minus/ppg-bugs-and-requests#1646]
**What**
It's a magnet that repels. Just like an electromagnet, it is stronger when powered.
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Why**
Non-explosive firearm models (e.g. railgun)

**Comment by Drogo-man** [comment]
You know that you can make an electromagnet repel in the context menu right?

**Comment by MegaKonami** [comment]
No clue you could do that.

**Comment by MegaKonami** [comment]
closed
