### ISSUE TITLE
Temperature reset feature.

### ISSUE THREAD

**Issue by TamasB14** [studio-minus/ppg-bugs-and-requests#165]
**Feature description**
Giving the player an option to reset a heated item's temperature to normal.

**Feature purpose**
Could help people reset the temp for things such as metals without needing to use cooling rays/heating rays. It would reset cold and hot objects to like a normal 20-25 Celsious degree.

**Additional context**
People who love playing with explosives often experience problems with overheating materials giving people nightmares on cooling them down if there's multiple items heating eachother.

**Comment by mestiez** [comment]
I added a "Set object temperature" context menu option.
