### ISSUE TITLE
"Decimator Is Very Loud when Destroying Humans"

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1650]
**Describe the bug**
When putting a human into a decimator, the sound effect is extremely loud, this may be because the decimator is seeing each body part of the human as individual, and decimating them at the same time, making the sound very loud.

**Clearly describe how to reproduce the bug**
Spawn a decimator, activate it, and put a human onto it.

**Comment by mestiez** [comment]
fixed
