### ISSUE TITLE
Able to reattach detached body parts

### ISSUE THREAD

**Issue by gogo1701** [studio-minus/ppg-bugs-and-requests#1652]
**Feature description**
To be able to reattach a detached body part, by having a machine, or just connecting it with wires to connect it and make it functional again.

**Feature purpose**
The purpose is so we can make surgery RP or at all the game more realistic.

**Comment by SirAJ4895** [comment]
Full support

**Comment by PossiblyRemember** [comment]
I would love this to be a feature, but truth be told it would probably be a real pain to implement this. However, I did find a [mod](https://steamcommunity.com/sharedfiles/filedetails?id=2801931724), although unstable

**Comment by DindinYT37** [comment]
Basically a duplicate of #1631.
