### ISSUE TITLE
Remove the prompt telling you to switch to Discrete

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1654]
**Feature description**
I'm really tired of every time I boot the game it says "You can set your collision mode to "Discrete" for a significant performance boost!". My computer doesn't have any problem with Continuous mode. Even if others' computers can't handle it, they can use their eyes to see their computer runs worse.

**Feature purpose**
It's a very annoying and unneeded prompt. It should have never even been added.

**Comment by PossiblyRemember** [comment]
it's a small prompt that goes away after 5 seconds, we don't really need this

**Comment by SirAJ4895** [comment]
> it's a small prompt that goes away after 5 seconds, we don't really need this

I have autism and really small things like this annoy me

**Comment by PossiblyRemember** [comment]
> > it's a small prompt that goes away after 5 seconds, we don't really need this
> 
> I have autism and really small things like this annoy me

again, we really don't need this it's there for *5 seconds*

**Comment by SirAJ4895** [comment]
I don't even know why it _is_ there, it just irritates me that it tells me every startup.

**Comment by mestiez** [comment]
i mustve had some kind of parasite in my brain when i added that

**Comment by SirAJ4895** [comment]
Once again proof Zooi is god
