### ISSUE TITLE
You can change the size of toybox when hidden

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#167]
**Describe the bug**
You can change the size of toybox while it's hidden, this is super annoying because I keep accidently making it huge while it's hidden and I'm trying to select things.

**Clearly describe how to reproduce the bug**
Make the toybox menu as small as possible
Hide it (TAB)
Move your move to the very left of the screen
Hold right click and drag it all the way to the right side of the screen
Unhide it (TAB)

**Additional notes**
 I know this is a duplicate of https://github.com/studio-minus/ppg-bugs-and-requests/issues/79, but you said you fixed it 27 days ago, and this issue is still a thing. Unless you skipped putting the bugfix in 4 different updates for some reason, the fix didn't work.

**Comment by mestiez** [comment]
I may be stupid. Fixed for real now
