### ISSUE TITLE
more gun stuff

### ISSUE THREAD

**Issue by SpanishPizza** [studio-minus/ppg-bugs-and-requests#1672]
**Feature description**
when humans hold a gun, it can run out of ammo and then reload it

**Feature purpose**
For fun and good for videos

**Additional context**
No

**Comment by PossiblyRemember** [comment]
should probably be toggleable in settings, for now there is a [mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2761082698)

**Comment by SpanishPizza** [comment]
thanks ill close this suggestion
