### ISSUE TITLE
blood icons in no gore mode

### ISSUE THREAD

**Issue by SpanishPizza** [studio-minus/ppg-bugs-and-requests#1675]
**Describe the bug**
when using the non-gore mode, for the blood tank and blood flask, the icons for the items are still red, although, in non-gore mode, the blood is yellow

**Clearly describe how to reproduce the bug**
turn on non-gore mode and search for the blood tank or blood flask, see icon is red

**Mod list**
Powers Mod
Flipping Heck
Identical Humans
Guns N' Ammo
I forgot some but they don't matter

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**
No

![Screenshot (3416)](https://user-images.githubusercontent.com/108996253/178124556-ddff2b49-0d1b-46c5-b663-322099712a4f.png)
see the blood icons?

**Comment by DindinYT37** [comment]
zooi probably just forgot to change them.

**Comment by SpanishPizza** [comment]
Well, now is his chance to do it.

**Comment by mestiez** [comment]
I didn't forget to change them and there is nothing reasonable I can do about this. Should I just add a post processing effect that replaces all red-ish colours in the game with yellow? Doesn't that go a bit too far?
