### ISSUE TITLE
the bottles are yellow in no-gore mode

### ISSUE THREAD

**Issue by SpanishPizza** [studio-minus/ppg-bugs-and-requests#1676]
**Describe the bug**
when in no-gore mode, the drink in the bottle turns yellow instead of orange

**Clearly describe how to reproduce the bug**
activate no-gore mode and create some bottles

**Comment by DindinYT37** [comment]
Yeah because any kind of red liquid gets turned into yellow/orange liquid.

**Comment by SpanishPizza** [comment]
They should just change it for the bottle.

**Comment by mestiez** [comment]
I can increase the threshold for when a liquid is considered red
