### ISSUE TITLE
"New Achievement Ideas"

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1680]
I'm sorry but the regular template simply didn't work for this suggestion. Don't be telling me "Please use the template." you know who you are.

1. Lawnmower - Kill 3 humans with 1 bullet
2. I shouldn't be alive - Have a human survive with 30+ injuries
3. 4th of Die - Resize a firework massive and detonate it
4. Pyromaniac - Set 100 things on fire
5. Uploader - Upload 10 things to the workshop
6. Special broadcast - Activate the TV easter egg
7. Revival - Bring a dead human back to life with a defibrillator
8. Payback - Kill a Gorse with Beverage M04
9. Headshot - Shoot a human in the head with a sniper rifle from more than 24 ft away
10. Pincushion - Have a human with 20 or more arrows, crystals, or spikes in it at once

**Comment by PossiblyRemember** [comment]
but what about the template

**Comment by DindinYT37** [comment]
The normal template would've worked just fine if you didn't multi-request.

**Comment by SirAJ4895** [comment]
It's not a multi-request as much as just asking for more achievements. Do you want me to make 10 different posts with each achievement or something?

**Comment by DindinYT37** [comment]
> It's not a multi-request as much as just asking for more achievements. Do you want me to make 10 different posts with each achievement or something?

I mean, that's how you're supposed to do feature requests. Since zooi can now "only" accept all of the achievements or none of them.

**Comment by PossiblyRemember** [comment]
> > It's not a multi-request as much as just asking for more achievements. Do you want me to make 10 different posts with each achievement or something?
> 
> I mean, that's how you're supposed to do feature requests. Since zooi can now "only" accept all of the achievements or none of them.

ig zooi could just add the few he wants and just say this is accepted without accepting all?

**Comment by DindinYT37** [comment]
> > > It's not a multi-request as much as just asking for more achievements. Do you want me to make 10 different posts with each achievement or something?
> > 
> > 
> > I mean, that's how you're supposed to do feature requests. Since zooi can now "only" accept all of the achievements or none of them.
> 
> ig zooi could just add the few he wants and just say this is accepted without accepting all?

Yeah he could but what I said was the exact reason why he said not to multi-request.
