### ISSUE TITLE
Update Steam Emoticons and Cards and Animated Profile Icon

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1693]
**Feature description**
you know these funky chat pictures thingies? well, they use old sprites, this is odd

**Feature purpose**
Consistency

**Additional context**
![Безымянный](https://user-images.githubusercontent.com/104321411/178196653-0c8a9423-526b-402f-b31b-4807b5871cef.png)

**Comment by bibbybabby** [comment]
> Technically duplicate of #1553.

I think that achievements and emoticons are different

**Comment by DindinYT37** [comment]
> > Technically duplicate of #1553.
> 
> I think that achievements and emoticons are different

Yeah but it's talking about the same issue; updating the Steam-content images/icons.

**Comment by mestiez** [comment]
Unfortunately the issue mentioned is completely different. Steam doesn't allow updating marketplace stuff like emoticons and cards after they've been uploaded. I can't update them.

**Comment by DindinYT37** [comment]
I mean it's technically the same issue: outdated icons on steam-content.
