### ISSUE TITLE
tritium unable to heal dead brain

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#1696]
**Describe the bug**
tritium does not heal brain death for some reason

**Clearly describe how to reproduce the bug**
simply shoot someone in the head and give them tritium along with a cardiopulmonary bypass machine hooked up to their heart

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: windows 11
 - Game version: 1.25 beta 6
 - GPU: gtx 1650 super
 - CPU: i5

**Additional notes**

**Comment by DindinYT37** [comment]
Isn't tritium just the thing you get from nukes? Isn't that basically radioactivity/radioactive liquid? Also a CBM wouldn't contribute to the brain death in any way.

I might've misunderstood this issue but from what I can see, this makes absolutely no sense.

**Comment by PossiblyRemember** [comment]
In the preview tritium (yes it comes from nukes) was made to where it could heal a dead brain, and unless you stopped the heart CBM probably wouldn't do anything

**Comment by fhgb54643689** [comment]
> Isn't tritium just the thing you get from nukes? Isn't that basically radioactivity/radioactive liquid? Also a CBM wouldn't contribute to the brain death in any way.
> 
> I might've misunderstood this issue but from what I can see, this makes absolutely no sense.

look in the changelog

**Comment by fhgb54643689** [comment]
also this bug has been fixed it was because i didnt fix their internal bleeding
