### ISSUE TITLE
compiling problem cant compiling

### ISSUE THREAD

**Issue by duybip** [studio-minus/ppg-bugs-and-requests#1700]
**Describe the bug**
i cant compiling cuz wen i compiling is start and then fail to reading mod

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
vietnam war mod

**System info (please complete the following information)**
 - Operating system: win 7 64bit
 - Game version: 1.25 preview6
 - GPU: idk
 - CPU:core 2 dua p9600

**Additional notes**

**Comment by Drogo-man** [comment]
Spellnt
