### ISSUE TITLE
my people playground dont update

### ISSUE THREAD

**Issue by theguywholovesmonke** [studio-minus/ppg-bugs-and-requests#1702]
my people playground stop updating before the gore update

for some reason my people playground stop updating before the gore update its original bought from steam and when i try update it says its updated but dont show anything from the update

**Comment by Drogo-man** [comment]
That's seems like a steam or a pc problem

**Comment by theguywholovesmonke** [comment]
> Isso parece um problema no Steam ou no PC

i tried in other computer and even reinstall steam but dont worked :(

**Comment by DindinYT37** [comment]
Are you even enrolled in the beta branch?

**Comment by theguywholovesmonke** [comment]
yes why?
