### ISSUE TITLE
wound bug

### ISSUE THREAD

**Issue by deathhimself23** [studio-minus/ppg-bugs-and-requests#1706]
**Describe the bug**
no bullet hole wounds

**Clearly describe how to reproduce the bug**
shoot the 9mm pistol

**Mod list**
human tiers-active

**System info (please complete the following information)**
 - Operating system: w11
 - Game version: 1.25 preview 9
 - GPU:AMD Radeon(TM) Graphics
 - CPU:AMD Ryzen 3 4300U with Radeon Graphics

**Additional notes**

**Comment by deathhimself23** [comment]
okay as soon as i fixed the recompiling error for the mod, bullet wounds reappeared

**Comment by DindinYT37** [comment]
> okay as soon as i fixed the recompiling error for the mod, bullet wounds reappeared

Then close the issue.
