### ISSUE TITLE
Mod update superposition

### ISSUE THREAD

**Issue by tomatoiab** [studio-minus/ppg-bugs-and-requests#1713]
**Describe the bug**
In 1.25Beta,When you update your mod with remove something then update mod, the workshop will download the removed thing from previous version mod and put the removed thing into your mods folder

**Clearly describe how to reproduce the bug**
0.Use 1.25Beta
1.Update your mod
2.Delete something in your mod.
3.Update your mod again
4.A Magic from steam workshop will make your deleted thing appear in your mod folder!

**Mod list**

	tomatoiab-Tomatoiab Character-local v1.0 for game v1.21+
		Currently inactive

	zuccian-Symbiote Playground-2803459361 v1 for game v1.10+
		Currently inactive

	TheMonkfcRampage-Magdump Mayhem - Guns 'N Armor-2799945427 vover 9000 for game vOVER 9000
		Currently inactive

	Team Wilson-People Playground 3D-2785176210 v1 for game v1.21+
		Currently inactive

	Decibek-Crash Test Dummy-local v1.0 for game vany version
		Currently inactive

	zooi-Darker blood-local v1.0 for game v1.22
		Currently inactive

	R0Y1T0-R0Y1T0 Vehicle Pack 1-2774090496 v2.5 for game v1.22+
		Currently inactive

	Orsoniks / Navii-SimplePortals-2759460093 v1.0 for game v1.22+
		Currently inactive

	Zkryhngro�meister-Science Hazard Minus-2691553761 v1.8 for game v1.24.6+
		Currently inactive

	tomatoiab-PeoplePlayground CN Translation Packet-2635194587 v1.1.3 for game v1.22.3
		Currently inactive

	Maxe-Colorful-2631183398 v1.0.0 for game v1.19+
		Currently inactive

	Maxe-Detroit: Become Human-2571963895 v1.1 for game v1.19+
		Currently inactive

	Fleasy-FleasyWeapons - Rifles-2571665852 v1.3 for game v1.20+
		Currently inactive

	fR4n1oo0, Painter-Metal Humans-2565354244 v1.0 for game v1.19+
		Currently inactive

	CTTC321-Magic Humans Mod-2558160935 vv1.0 for game v1.13+
		Currently inactive

	Aubarino-PP Amod-2551084740 v1.3 for game v1.20+
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently inactive

	Sҝữľľ-More Weapons Mod-local v1.0 for game v1.15x
		Currently inactive

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently inactive

	󠀦󠀦-Powerful Personnel Mod-2433181522 vv1.0 for game v1.19+
		Currently inactive

	Alibarda-Human Tiers-2308911224 v5.1 for game v1.18+
		Currently inactive

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently inactive

	test-test-local v1.0 for game v1.21+
		Currently inactive

	test-test-local v1.0 for game v1.21+
		Currently inactive
		Malfunctioning

	test-test-local v1.0 for game v1.21+
		Currently inactive

	tomatoiab-PeoplePlayground CN Translation Packet-2635194587 v1.1.3 for game v1.22.3
		Currently ACTIVE

	tomatoiab-Tomatoiab Character-2817334791 v1.0 for game v1.21+
		Currently inactive

	Lute_stone-Lute_stone-local v1.0 for game v1.21+
		Currently inactive

	XXX-TEST MOD-local v1.0 for game v1.21+
		Currently inactive

**System info (please complete the following information)**
 - **OS**: Windows 10  (10.0.19044) 64bit

 - **CPU**: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz

 - **GPU**: NVIDIA GeForce RTX 2060

 - **Memory**: 16 GB

**Additional notes**
Dear zooi pls fix it (My English is bad, sry :(

**Comment by PossiblyRemember** [comment]
Did you try to upload without removing the file from mod.json? All scripts are loaded through there, you might've forgotten to remove it, so I'd just redownload the missing file. 
![image_2022_07_13T05_48_49_444Z-1.png](https://user-images.githubusercontent.com/105954143/178660158-8c9b086b-7cf9-4546-bea0-a09d35c046a5.png)

**Comment by tomatoiab** [comment]
> Did you try to update the file without removing the script from mod.json? All scripts are loaded through there, you might've forgotten to remove it, so it would just redownload the missing file. ![image_2022_07_13T05_48_49_444Z-1.png](https://user-images.githubusercontent.com/105954143/178660158-8c9b086b-7cf9-4546-bea0-a09d35c046a5.png) Also ur English is fine :)


thanks for you reminding me, I tried this way, But the workshop still download my deleted file in my mod folder😂.
and thanks for your praise too ;)

**Comment by tomatoiab** [comment]
And when my game version is 1.24,The bug isn't appear.

**Comment by mestiez** [comment]
Local mods (mods you work on should **always** be local) aren't retrieved from the workshop. This issue is most likely caused by cloud saving. Disable it and it should be fine. Report back if it isn't

**Comment by tomatoiab** [comment]
> Local mods (mods you work on should **always** be local) aren't retrieved from the workshop. This issue is most likely caused by cloud saving. Disable it and it should be fine. Report back if it isn't

Oh Thank you zooi.so many thanks
