### ISSUE TITLE
resized fire extinguishers kind of buggy

### ISSUE THREAD

**Issue by RonaBtheCodeR** [studio-minus/ppg-bugs-and-requests#1715]
**Describe the bug**
smaller fire extinguishers do not put out flaming objects unless they are very close to it.

**Clearly describe how to reproduce the bug**
1. resize a fire extinguisher to the smallest size
2. light a human or wooden object on fire
3. use the extinguisher on the human/wooden object
it will show the regular particles but not put them out until it is very close.

**Mod list**
ouch ok theres a lot

The backmaps mod - disabled
2 slopes - enabled
dequalityed's random items - enabled
"thoop" grenade launcher - enabled
valley map - enabled
limb attachments - enabled
named humans - enabled
pride flags! - enabled
minecraft building system - enabled
bloodenhancedmod - disabled
slebbey mod (NEW) - enabled
anti-gravity device - enabled
PPG additions - enabled
remastered DreamSMP mod - enabled (only for murdering dream btw)
more vehicles - enabled
melon playground map mod - enabled
husk overdose - disabled
limb reattachment tools - disabled
magdump mayhem - guns n' armor - disabled
reloadable explosive weapons - enabled 
aerodynamics - disabled
shopping cart -SC - enabled
better androids - disabled
the ultimate car mod - enabled
melon playground mod - enabled
cat mod - enabled
water physics - enabled
reactive humans - enabled
people playground 3D - enabled
blood on walls - disabled
risk of playground - disabled
favourites category - disabled
human with changeable feelings - enabled
melon playground - disabled
guns n' ammo - enabled
simpleportals - enabled
acid sea (FIXED) - enabled
attack on people playground - disabled
functional androids - enabled 
spanish civil war mod - disabled
meme animals mod - disabled
human dynamic emotions - enabled
spy moyai - disabled
boneworks pack: npcs - disabled
enhanced human sounds - disabled
five nights at people playground - disabled

nah im not writing any more that took like 20 minutes

**System info (please complete the following information)**
 - Operating system: windows
 - Game version: 1.25 preview 9 (64 bit)
 - GPU: **Intel (R) UHD Graphics** and **NVIDIA GeForce RTX 3050 Ti Laptop GPU**
 - CPU: 11th Gen Intel Core

**Additional notes**
nah

**Comment by mestiez** [comment]
fixed :)
