### ISSUE TITLE
Androids and Gorses super weird behaviour

### ISSUE THREAD

**Issue by NirronCD** [studio-minus/ppg-bugs-and-requests#1719]
**Describe the bug**
Androids and gorses when you spawn it, will spawn with their joints bugged, eating so much FPS

**Clearly describe how to reproduce the bug**
Just spawn an Android or a Gorse and you will see it

**Mod list**
None actived

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.25
 - GPU: GTX 1050 
 - CPU: i5-4460

**Additional notes**
![asdas](https://user-images.githubusercontent.com/68976538/178836015-fb87d369-ea52-4525-8a3a-93a25c9b5c05.png)

https://user-images.githubusercontent.com/68976538/178837018-11fb624a-c921-476c-994e-795ddccc8a25.mp4

**Comment by PossiblyRemember** [comment]
looks like they are colliding with themselves... that's not good :/

**Comment by DindinYT37** [comment]
Same. Also, People Playground has been eating 16+ gigabytes of RAM since last update...

**Comment by subjectgrimm** [comment]
yeah same thing happened to me, i think it's happening to everyone

**Comment by subjectgrimm** [comment]
welp they JUST fixed it
this whole thing is now outdated

**Comment by NirronCD** [comment]
> welp they JUST fixed it this whole thing is now outdated

yes, they fixed! I can confirm it!
