### ISSUE TITLE
Human Vital Parts revamp

### ISSUE THREAD

**Issue by unknown-4o4** [studio-minus/ppg-bugs-and-requests#172]
**Feature description**
An idea I have is: _Lower-jaw_ part of the head has a much higher chance of survival- compared to the top part (obviously where the brain is.)

And the upper-torso has a slower bleed-out rate; **Not instantly killing the human**.

**Feature purpose**
IMO it will give players a little more fun, to toy around with the humans and not instantly kill them with a single stray bullet to a part that shouldn't normally instant-kill.

**Additional context**
perhaps implement a secondary hitbox for extremely vital parts and somewhat vital? Kind of like sub-hitboxes. Just an idea. Let me know

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/131851585-abba9d0f-f98b-4dc2-9352-f8616692de84.png)
like this

**Comment by unknown-4o4** [comment]
Yeah that's perfect!
