### ISSUE TITLE
Gorse projectile impact effect is incorrect

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1723]
**Describe the bug**
When a gorse spits acid at a human, flesh chunks appear. This probably wasn't meant to happen unless the gorse is also shooting its flesh.

**Clearly describe how to reproduce the bug**
Spawn a human, then spawn a gorse and see its acid has green flesh chunks.

**Mod list**
I tried with and without mods, still happens.

**Comment by mestiez** [comment]
fixed :)
