### ISSUE TITLE
Brain Damage doesn't effect animation overrides

### ISSUE THREAD

**Issue by DerpNebulae** [studio-minus/ppg-bugs-and-requests#1724]
**A pawn with Brain Damage will act as normal, if instructed to walk, sit, stumble, cower, or flat pose.** 

**To Reproduce:**

1. Give a pawn brain damage (as one does)
2. Have them walk

 OS: Windows 10
 Game version: 1.25
 GPU: RTX 3070 ti
 CPU: Ryzen 5 5600X

**Comment by SirAJ4895** [comment]
For clarity, I recommend using the template for submitting bugs.

**Comment by PossiblyRemember** [comment]
Seems like he did use the template, just didn't keep the headers, that's probably what you meant

**Comment by DerpkingRoyale** [comment]
> For clarity, I recommend using the template for submitting bugs.

I did, in fact, use said template.

**Comment by SirAJ4895** [comment]
Sorry, I didn't realize.

**Comment by DerpNebulae** [comment]
oops

**Comment by mestiez** [comment]
you cant walk if you have brain damage

**Comment by mestiez** [comment]
did you just call them pawns?

**Comment by mestiez** [comment]
fixed :)
