### ISSUE TITLE
Android bug in version 1.25

### ISSUE THREAD

**Issue by Frutose** [studio-minus/ppg-bugs-and-requests#1725]
**Describe the bug**
The bug happens whenever i place a android in the game, and it makes the android limbs get all scrambled, And if i select all the android parts, i cant go on the menu

**Clearly describe how to reproduce the bug**
Spawn a android. For the other bug, select all the android parts and press right click

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9106796/exported.game.debug.info.md)

![imagem_2022-07-13_204524866](https://user-images.githubusercontent.com/109248353/178855308-86282755-95f4-4d5f-b8be-52bbd77cdd2f.png)

**Comment by mestiez** [comment]
duplicate and already fixed
