### ISSUE TITLE
Flipping entities & objects

### ISSUE THREAD

**Issue by yarnball02** [studio-minus/ppg-bugs-and-requests#1727]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

It is a mechanic. Its an option on the right click menu, to flip an animal/object.

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some 
form?

I requested it because it was getting repetitive spawning a human with all the things i wanted on it just flipped. It exists as a mod, but doesn't flip everything on an entity

**Additional context**

**Comment by PossiblyRemember** [comment]
[Flipping Heck](https://steamcommunity.com/sharedfiles/filedetails/?id=2448120172), made by zooi

**Comment by mestiez** [comment]
this is one of those
