### ISSUE TITLE
Cobblestone Wall debris is extremely bouncy underwater

### ISSUE THREAD

**Issue by KazotskyKiller** [studio-minus/ppg-bugs-and-requests#1729]
Basically the tiny rocks that fall apart form the cobblestone wall are really bouncy underwater for some reason.

Firstly, take a cobblestone wall and smash it so it breaks. Then throw the rock debris into the water and when they hit the bottom of the water they start bouncing really crazy!

All my mods were disabled during this.

 - Operating system: Windows 10 Pro
 - Game version: Release 1.25 
 - GPU: RTX2060
 - CPU: AMD Ryzen 7

**Comment by mestiez** [comment]
fixed :)
