### ISSUE TITLE
sounds bug

### ISSUE THREAD

**Issue by Quickness19** [studio-minus/ppg-bugs-and-requests#174]
**Describe the bug**
The sound hangs. It goes off for a second and then comes back on again.

**Clearly describe how to reproduce the bug**
I don't know! It happens all of a sudden, like seasons (lol), i.e., one time this bug is there, another time it's not....
https://www.youtube.com/watch?v=NjNGSrmf8vc&ab_channel=Quickness

**Mod list**
Apex Legends Mod (this is my mod and it's activated)
And the rest are not activated and mine. As I understand over time it does not depend on mods, it seems.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.21.3 (64 bit)
 - GPU: NVIDIA Geforce GTX 1050 ti
 - CPU: intel core i3-7100 (4)

**Additional notes**

**Comment by mestiez** [comment]
does this happen in any other game or application?

**Comment by Quickness19** [comment]
> does this happen in any other game or application?

Only in PPG. I can watch YouTube videos at the same time, the sound in the video will be normal, but in ppg it hangs

**Comment by mestiez** [comment]
this is odd. does this also happen if you disable all mods & restart the game?

**Comment by Quickness19** [comment]
> this is odd. does this also happen if you disable all mods & restart the game?

The sound still hangs. I turned off all the mods and restarted the game. I always go into the game itself through the Windows taskbar. I tried to run the game through the steam itself, with the sound is the same problem. Reinstalled the game and still the same bug.

**Comment by Quickness19** [comment]
I noticed that when a large file is loaded, the sound in the game is normal. More precisely, when the game itself hangs, loading something, the background sound works fine

**Comment by Quickness19** [comment]
![Uploading 05-09-2021 125735.jpg…]()

**Comment by Quickness19** [comment]
![Скриншот 05-09-2021 125735](https://user-images.githubusercontent.com/69407926/132113377-484d5385-de23-41a6-9a96-ba2ab301eee5.jpg)

**Comment by Quickness19** [comment]
But the sound started to hang again when all the downloads passed.

**Comment by mestiez** [comment]
Where is the game installed? Have you tried reinstalling your audio drivers? I don't have an explanation why this problem is happening and it's impossible for me to reproduce it as it's unique to your computer.

**Comment by Quickness19** [comment]
> Where is the game installed? Have you tried reinstalling your audio drivers? I don't have an explanation why this problem is happening and it's impossible for me to reproduce it as it's unique to your computer.

Dear developer! I really decided to try reinstalling the sound drivers and now the sound does not hang in the game! But I just don't understand one thing: why everything was fine everywhere, but in PPG the sound hangs?

**Comment by mestiez** [comment]
> > Where is the game installed? Have you tried reinstalling your audio drivers? I don't have an explanation why this problem is happening and it's impossible for me to reproduce it as it's unique to your computer.
> 
> Dear developer! I really decided to try reinstalling the sound drivers and now the sound does not hang in the game! But I just don't understand one thing: why everything was fine everywhere, but in PPG the sound hangs?

It's possible that the audio engine used by Unity specifically had some issues with your, possibly outdated, audio drivers.
