### ISSUE TITLE
Reconstructor heals burns and skin damage

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1740]
**Describe the bug**
Reconstructor reconstructs burns and skin damage despite the description saying otherwise

**Clearly describe how to reproduce the bug**
1. Spawn human
2. Ignite or acid
3. Reconstuct
4. Skin gets mended?

**Mod list**
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9114705/exported.game.debug.info.md)

**Additional notes**
All I wanted was some skelly bois for Christmas

**Comment by Drogo-man** [comment]
No skin = incompatible with life
That's why

**Comment by Drogo-man** [comment]
No flesh or skin = incompatible with life
That's why

**Comment by bibbybabby** [comment]
> No flesh or skin = incompatible with life That's why

But it doesn't heal a gorillion bullet and stab wounds?!?!?

**Comment by DindinYT37** [comment]
> > No flesh or skin = incompatible with life That's why
> 
> But it doesn't heal a gorillion bullet and stab wounds?!?!?

What's a gorillion bullet?

**Comment by bibbybabby** [comment]
> > > No flesh or skin = incompatible with life That's why
> > 
> > 
> > But it doesn't heal a gorillion bullet and stab wounds?!?!?
> 
> What's a gorillion bullet?

...
gorrilion is a comically large number, not a bullet..... if this is a joke it's definitley not funny......

**Comment by DindinYT37** [comment]
> > > But it doesn't heal a gorillion bullet and stab wounds?!?!?
> > 
> > 
> > What's a gorillion bullet?
> 
> ... gorrilion is a comically large number, not a bullet..... if this is a joke it's definitley not funny......

It's not a joke but you said "gorillion bullet and stab wounds" so I thought you meant some kind of gorillion bullet, now with the definition I understand than you meant an extreme amount of bullet and stab wounds. It isn't a joke and it's quite preposterous how you think so.

**Comment by Drogo-man** [comment]
> > > > But it doesn't heal a gorillion bullet and stab wounds?!?!?
> > > 
> > > 
> > > What's a gorillion bullet?
> > 
> > ... gorrilion is a comically large number, not a bullet..... if this is a joke it's definitley not funny......
> 
> It's not a joke but you said "gorillion bullet and stab wounds" so I thought you meant some kind of gorillion bullet, now with the definition I understand than you meant an extreme amount of bullet and stab wounds. It isn't a joke and it's quite preposterous how you think so.
> 
> Also, I suggest using a more common word instead of this - though I should've just googled it.

Party pooper

**Comment by mestiez** [comment]
Limbs will die without flesh and skin, like Drogo-man said. This is not a bug, but the item description is misleading. I will change it.
