### ISSUE TITLE
mouse icon duplicating and disappearing when using multiple monitors

### ISSUE THREAD

**Issue by whichfaris** [studio-minus/ppg-bugs-and-requests#1741]
**Describe the bug**
whenever i open the settings menu my mouse either disappears permanently until i relaunch the game or it freezes in place (i can move it but the icon for my mouse is stuck in place)

**Clearly describe how to reproduce the bug**
when i close my laptop lid and only use my monitor the bug occurs (only with people playground), but if i try it with my laptop lid open everything runs smoothly 

**Mod list**
none

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.25
 - GPU:  NVIDIA GeForce GTX 1050
 - CPU: Intel Core i7 7700HQ @ 2.80GHz

**Additional notes**

**Comment by PossiblyRemember** [comment]
I have a friend who plays this game with his laptop lid closed and hooked up to a monitor and he doesn't seem to have problems, maybe it's the sleep setting.

**Comment by Drogo-man** [comment]
Sounds like a pc problem idk.

**Comment by mestiez** [comment]
I have multiple monitors and everything works fine but I am not on a laptop.

**Comment by DindinYT37** [comment]
I had this happen once on a really old game, I think it was because of full screen. Are you playing on full screen?

**Comment by whichfaris** [comment]
> I had this happen once on a really old game, I think it was because of full screen. Are you playing on full screen?

i tried it on both borderless and fullscreen, neither of them worked. it does work when im playing on windowed

**Comment by DindinYT37** [comment]
> > I had this happen once on a really old game, I think it was because of full screen. Are you playing on full screen?
> 
> i tried it on both borderless and fullscreen, neither of them worked. it does work when im playing on windowed

Borderless and Fullscreen are essentially the same thing. Which is why I asked you if you played on fullscreen.
