### ISSUE TITLE
Floodier Floodlight

### ISSUE THREAD

**Issue by awaheart** [studio-minus/ppg-bugs-and-requests#175]
**Feature description**
Add an outdoor floodlight that would have much a longer range and light cone.
Or make the current floodlights, be floodlights.
Also maybe a brighter torch too.

**Feature purpose**
Currently, floodlights are only kind of useful inside low roof buildings, if you want to light up a whole area outside, or a warehouse with a tall roof, it's best to use a bunch of LED's, but that doesn't look as cool as a few strong floodlights would.

**Additional context**
A "floodlight" compared to a small little LED, it is pathetic.
![image](https://user-images.githubusercontent.com/69184577/132015066-83006c5e-7c08-4fe3-a6ef-07bddca82e30.png)

Huge "floodlight" barely being able to light up a small area.
![image](https://user-images.githubusercontent.com/69184577/132015467-1190c3ea-60a7-40ed-9ee7-dc0313fa7bd4.png)

**Comment by mestiez** [comment]
you can always power a floodlight to make it brighter. this does introduce some flickering because of the sparks, which I should probably turn off

**Comment by UniDuki** [comment]
I know you can make them brighter by powering, but that doesn't make the light go further.
Maybe powering shouldn't just make it brighter but also light further.
