### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by gogo1701** [studio-minus/ppg-bugs-and-requests#1751]
**Describe the bug**
Very weird glitch, that bugged the whole game

**Clearly describe how to reproduce the bug**
I am not sure, but I made a building on the abyss map that was sticking a little bit out and broke the piece that was sticking out and put a bomb in it and then the weird glitch happend

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version:
 - GPU:rtx 3060ti
 - CPU:intel core  i7-9700K
 - RAM:16 gigabytes

**Additional notes**
![image](https://user-images.githubusercontent.com/30569429/179226090-1c8215f1-ece2-444e-8154-7a800de84a89.png)
![image](https://user-images.githubusercontent.com/30569429/179226122-8dfb7817-3576-4c67-9dc3-7546d4abda59.png)
in the middle
![image](https://user-images.githubusercontent.com/30569429/179226150-f049423b-e218-4369-bf13-311817e1c333.png)
![image](https://user-images.githubusercontent.com/30569429/179226162-65a70dd0-45c2-4a87-9df6-744dac6d7c5f.png)

**Comment by DindinYT37** [comment]
So how about a proper name?

**Comment by PossiblyRemember** [comment]
this usually happens when the game get's very laggy with multiple objects, this has been mentioned before, if I understand

**Comment by gogo1701** [comment]
@PossiblyRemember Yeah, it lagged before doing the glitch

**Comment by PossiblyRemember** [comment]
yeah, that's it


> Related to or Duplicate of:
> 
> * [The map might collapse in on itself #1](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1)
> * [Truck Bug #11](https://github.com/studio-minus/ppg-bugs-and-requests/issues/11)
> * [Land Break #166](https://github.com/studio-minus/ppg-bugs-and-requests/issues/166)
> * [Not even sure what happened. Strange hybrid map glitch #471](https://github.com/studio-minus/ppg-bugs-and-requests/issues/471)
> * [Map moved to the side #495](https://github.com/studio-minus/ppg-bugs-and-requests/issues/495)
> * [Lights falling off in Default map. #902](https://github.com/studio-minus/ppg-bugs-and-requests/issues/902)
> * [Map Elements can be glitched out of place #1518](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1518)

wtf why so many

**Comment by DindinYT37** [comment]
> yeah, that's it
> 
> > Related to or Duplicate of:
> > 
> > * [The map might collapse in on itself #1](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1)
> > * [Truck Bug #11](https://github.com/studio-minus/ppg-bugs-and-requests/issues/11)
> > * [Land Break #166](https://github.com/studio-minus/ppg-bugs-and-requests/issues/166)
> > * [Not even sure what happened. Strange hybrid map glitch #471](https://github.com/studio-minus/ppg-bugs-and-requests/issues/471)
> > * [Map moved to the side #495](https://github.com/studio-minus/ppg-bugs-and-requests/issues/495)
> > * [Lights falling off in Default map. #902](https://github.com/studio-minus/ppg-bugs-and-requests/issues/902)
> > * [Map Elements can be glitched out of place #1518](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1518)
> 
> wtf why so many

Why do you ask me why people keep reporting before searching if it already exists?
