### ISSUE TITLE
Bugs i have found within the game

### ISSUE THREAD

**Issue by B-Knots** [studio-minus/ppg-bugs-and-requests#176]
For the bugs i have found within the game one bug that has been most prominent is how rigor mortis no longer functions correctly, only in extreme cold or after i use the defibrillator does the body stiffen up in all gangrenous spots. another issue ive had only with this latest version is that when saving a creation/overwriting a creation it will not do either sometimes. it is very spotty and cost me a few great creations. I hope these can be easily fixed, because otherwise the game works perfectly and still is extremely fun.

**Comment by mestiez** [comment]
hey you're the email person. please do not group bug reports. these issues are meant to be handled seperately.
