### ISSUE TITLE
ventilator 

### ISSUE THREAD

**Issue by Tbskins** [studio-minus/ppg-bugs-and-requests#1769]
**Feature description**
it would be a new spawnable machine that would help a person breath 
**Feature purpose**
the purpose would be to help the person breath when their lung get pierced. it could also give oxygen to the persons brain even if they are missing their body

**Comment by bibbybabby** [comment]
The CBM already does that

**Comment by Tbskins** [comment]
> The CBM already does that

huh it does... that's kind of weird since its supposed to just keep the heart beating?

**Comment by bibbybabby** [comment]
> > The CBM already does that
> 
> huh it does... that's kind of weird since its supposed to just keep the heart beating?

cardiopulmonary means heart & lungs

**Comment by Tbskins** [comment]
> > > The CBM already does that
> > 
> > 
> > huh it does... that's kind of weird since its supposed to just keep the heart beating?
> 
> cardiopulmonary means heart & lungs

OOOOOOOOhhhhhhh. wait it says cardio so of course it does. damn I'm slow. ok thanks

**Comment by Drogo-man** [comment]
As a fellow person who has access to Google, i can say that cardiopulmonary means heart and lungs.

**Comment by Drogo-man** [comment]
I double checked and the CBM in the game only does the heart thingy even tho it's called "cardiopulmonary" which means heart AND lungs.

**Comment by DindinYT37** [comment]
> I double checked and the CBM in the game only does the heart thingy even tho it's called "cardiopulmonary" which means heart AND lungs.

Nope, it also keeps the lungs alive. Though just barely enough for the human to survive, meaning the human will still think he's actually suffocating.

**Comment by Drogo-man** [comment]
> > I double checked and the CBM in the game only does the heart thingy even tho it's called "cardiopulmonary" which means heart AND lungs.
> 
> Nope, it also keeps the lungs "alive". Though it keeps the oxygen-level just barely high enough for the human to survive, meaning the human will still think he's suffocating while being fine.

Then i guess the description should be changed as it says that i only does the heart thingamajig.
