### ISSUE TITLE
Colourable Lasers

### ISSUE THREAD

**Issue by awaheart** [studio-minus/ppg-bugs-and-requests#177]
**Feature description**
Different ways to add Colourable Lasers, favourite to least favourite. Keep default laser green though.

1. Connecting LED's to a laser with electrical wire would shift the colour of the laser towards the colour of the LED's colour. Example: Connecting a red LED to a default green laser would make the laser's colour yellow.

2. Add coloured glass, which would change a laser's colour if shined through.

3. Same as 1, but using the current cathode lights or LEDs instead of coloured glass (might break some existing build).

4. An option in the context menu to change colour, which would open a colour picker menu.

5. Add more lasers with different colours; red, orange, yellow, green, cyan, blue, purple, pink and white

**Feature purpose**
Coloured lasers would be very nice and useful

**Comment by JohnVcav** [comment]
A simple color picker with RGB sliders/Hex code would be really nice for this

**Comment by Drogo-man** [comment]
You can change the color of the laser tho
