### ISSUE TITLE
Pool

### ISSUE THREAD

**Issue by XenonPPG** [studio-minus/ppg-bugs-and-requests#1772]
**Feature description**
Its a new item. It can contain 50L of liquid. things can swim in it. 

**Feature purpose**
This is will be really interresting for experiments. For example: healing pod. Or for making custom maps

**Comment by bibbybabby** [comment]
what would happen if it got flipped upside down?

**Comment by DindinYT37** [comment]
> what would happen if it got flipped upside down?

Exactly why it probably will get rejected, unless all the water just turns into particles and disappears/fades out.

**Comment by MrHushPPG** [comment]
> > what would happen if it got flipped upside down?
> 
> Exactly why it probably will get rejected, unless all the water just turns into particles and disappears/fades out.

you can make a standard outflow of liquid "to nowhere" as with a liquid tank in drain mode

**Comment by DindinYT37** [comment]
> > > what would happen if it got flipped upside down?
> > 
> > 
> > Exactly why it probably will get rejected, unless all the water just turns into particles and disappears/fades out.
> 
> you can make a standard outflow of liquid "to nowhere" as with a liquid tank in drain mode

That's why I said "unless all the water just turns into particles and disappears/fades out", even though I don't know if those are particles - that's what I meant.

**Comment by MrHushPPG** [comment]
> 

ok

**Comment by MrHushPPG** [comment]
> > > > what would happen if it got flipped upside down?
> > > 
> > > 
> > > Exactly why it probably will get rejected, unless all the water just turns into particles and disappears/fades out.
> > 
> > 
> > you can make a standard outflow of liquid "to nowhere" as with a liquid tank in drain mode
> 
> That's why I said "unless all the water just turns into particles and disappears/fades out", even though I don't know if those are particles - that's what I meant.

ok
