### ISSUE TITLE
april fools joke

### ISSUE THREAD

**Issue by pYMxolbo** [studio-minus/ppg-bugs-and-requests#1780]
**Feature description**
make all maps just simply have nowhere to spawn anything (completely map blocks)

**Feature purpose**
it would be funny

**Additional context**
i think it would annoy people and thats what game dev is all about

**Comment by DindinYT37** [comment]
And watch the bug reports flow into the GitHub? I doubt it.

Also wouldn't that just make the game completely unplayable for a whole day? Usually games go for something like a decoration, cosmetic or vanity thing as to not disturb actual gameplay.

**Comment by pYMxolbo** [comment]
> 

it would be funny tho

**Comment by pYMxolbo** [comment]
oop

**Comment by PossiblyRemember** [comment]
bruh, april fools joke would be cool, but it's not this.

**Comment by pYMxolbo** [comment]
if i was making this game i would so thats my entire arguement :)
