### ISSUE TITLE
Sword will not stab

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1785]
**Describe the bug**
Sword will not stab info humans

**Clearly describe how to reproduce the bug**
Spawn Victim -> Spawn Sword -> Try to stab -> fail

**Mod list**
Test with and without mods, still broken

**Additional notes**

https://user-images.githubusercontent.com/106031972/179387192-6bf919ed-5add-4c2e-8bd0-7bfbed254f20.mp4

**Comment by Drogo-man** [comment]
Why does my brain keep adding cartoon "boing" sound effects when watching the video lol.

**Comment by SirAJ4895** [comment]
I like the way you think

**Comment by DindinYT37** [comment]
Works fine for me.
![image](https://user-images.githubusercontent.com/64973205/179393806-4c7f45a9-3ac5-485a-91f8-88ab712851ff.png)
![image](https://user-images.githubusercontent.com/64973205/179393807-a2c87782-6e7f-47ce-8842-aca3761dd569.png)

**Comment by SirAJ4895** [comment]
Well the entire point is that it doesn't work for me!

**Comment by DindinYT37** [comment]
> Well the entire point is that it doesn't work for me!

Then you should've provided actual information about your machine, or export your game information instead of just showing us the bug.

**Comment by SirAJ4895** [comment]
Well, I fixed it

**Comment by Drogo-man** [comment]
I just watched the video again and realized that it isn't Bandicam that lagging, it's ur PC. 12 fps goddamn.

**Comment by SirAJ4895** [comment]
My family doesn't exactly have the income to get me a high-end computer right now. I'm used to not having frames per second over 20.

**Comment by Drogo-man** [comment]
O yeah that sucks.
