### ISSUE TITLE
not being able to install downloaded mods

### ISSUE THREAD

**Issue by Zarasshky** [studio-minus/ppg-bugs-and-requests#1789]
**Describe the bug**

Absolutely all installed mods give an error: the connection was not established because the destination computer rejected the connection request

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

all possible

**System info (please complete the following information)**
 - Operating system:  Windows 7 32 bit
 - Game version: 1.25
 - GPU:NVIDIA GeForce 9600 GT
 - CPU:Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz 2926 mhz 2 cores, logical processors 2

**Additional notes**
![20220717145821_1](https://user-images.githubusercontent.com/109466484/179398981-e84843c2-a638-47ca-8e10-6d78f15c6445.jpg)

**Comment by PossiblyRemember** [comment]
recompile or make compile time higher, see if that works, or maybe its because ur using win7 on 32bit, idk

**Comment by DindinYT37** [comment]
Check your internet connection and turn your VPN off if you have one enabled.

**Comment by mestiez** [comment]
[Here](https://steamcommunity.com/app/1118200/discussions/0/2566437997128941140/) it says:

> ### Operating System
> This game works best on Windows 10. If you have no choice or don't care enough, Windows 7 works too. However, you need the latest version of Windows 7. [Follow this guide to update.](https://steamcommunity.com/linkfilter/?url=https://answers.microsoft.com/en-us/windows/forum/all/how-to-obtain-and-install-windows-7-sp2/c2c7009f-3a10-4199-9c89-48e1e883051e)

Have you seen this yet?

**Comment by mestiez** [comment]
Closing until theres more info
