### ISSUE TITLE
Please add this

### ISSUE THREAD

**Issue by EbicSeal** [studio-minus/ppg-bugs-and-requests#1794]
Ok so can you please add a feature for your own mods where even if they aren't broken show the recompile button so you don't constantly have to restart the game for every test.

Thank you.

**Comment by SirAJ4895** [comment]
What is even the point of saying that there are duplicates? Are you supposed to close your suggestion?

**Comment by DindinYT37** [comment]
> What is even the point of saying that there are duplicates? Are you supposed to close your suggestion?

Yes? That should've been quite obvious, especially if you saw some other issues here already since duplicate issues always just get closed.

**Comment by mestiez** [comment]
> What is even the point of saying that there are duplicates? Are you supposed to close your suggestion?

Yes. Duplicates are redundant because this is an issue board, not a forum.
