### ISSUE TITLE
Dismembered limbs thrown into a decimator destroy other body parts

### ISSUE THREAD

**Issue by blocker2225** [studio-minus/ppg-bugs-and-requests#1799]
**Describe the bug**
Dismembered limbs thrown into a decimator destroy other, undismembered body parts

**Clearly describe how to reproduce the bug**
1. Spawn a decimator
2. Spawn a human
3. Dismember the human
4. Throw one of the limbs into the decimator

**Mod list**
no mods

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.25
 - GPU: GTX 1050
 - CPU: Ryzen 5

**Additional notes**

**Comment by DindinYT37** [comment]
Because deleting a single bodypart removes the whole body.

Related to:
* #1650
* #1800

**Comment by SirAJ4895** [comment]
No it's not that related

**Comment by mestiez** [comment]
Intentional
