### ISSUE TITLE
I really suggest that "Resizable Housing" have an option to move forwards or backwards

### ISSUE THREAD

**Issue by Langsvard** [studio-minus/ppg-bugs-and-requests#1801]
It's more of a mechanic. Resizable housing would be cooler if it could move forwards or backwards in layers so that we could have more variety in our builds/ccontraptions.

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #834
* #838 
* #1057 
* #1223 
* #1227 
* #1515 
* #1684 

Also, please use the template.

**Comment by ATPGaming** [comment]
you may want to close this since it was added with the beta
