### ISSUE TITLE
Folders for Contraptions

### ISSUE THREAD

**Issue by Yggdrasil-Burnes** [studio-minus/ppg-bugs-and-requests#1807]
As someone who has made an obscene amount of contraptions ranging from simple to dense, it would be nice to be able to create folders in the contraptions menu and separate them into said folders. I've been playing a lot of Airships: Conquer the Skies and Barotrauma, mostly shipbuilding, and I've found that being able to manage project files like that really cleans up everything. It would also save on having to implement more complicated sorting features. I could separate contraptions by theme or by type and search up their folder instead of sorting through them one at a time. I've over 50 contraptions which are some variation of beating stick, so it'd be appreciated, but not necessary.

**Comment by PossiblyRemember** [comment]
nice, but please use the template

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #558
* #1153 
* #1206 
* #1575

**Comment by Yggdrasil-Burnes** [comment]
Gotcha. Didn't realize there was a template system in place or that there duplicate suggestions.
