### ISSUE TITLE
Objects and entities will cave-in

### ISSUE THREAD

**Issue by SirAJ4895** [studio-minus/ppg-bugs-and-requests#1808]
**Describe the bug**
I don't know how to describe it, but I took a screen capture.  (They spawned as normal, but the bug occurred when I tried to move the objects)
https://user-images.githubusercontent.com/106031972/179986076-d584ee64-28f1-45a5-b934-6be83183f92d.mp4

**Clearly describe how to reproduce the bug**
It's happened many times, and I've never found any consistent reason for the bug. From what I remember at least, I launched a nuke and pressed "clear all", then the following in the video occurred.

**Mod list**
_All mods were disabled at the time of the bug_

Carbine
Underground Complex
City 39
The Helicopter Mod
More Vehicles
Vanilla Firearms Expansion
Human Decal Enabler
Water Physics
Reactive Humans
Cormandy
Identical Humans
Shipping Container
Gears
Guns N' Ammo
Working Spraycans MOD
Item Plus
Fishing Rod
Injectible Flasks
Quick Right-click Options
Emergency Siren
Animated Weapons+
Quality of Life items
Wheelchair
Flipping Heck
Taser
Explosivemod
Human Tiers
Madness PACK
PowersMod
POT O' ITEMS
Hold K to make wires invisible

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.25
 - GPU: NVIDIA 3.24.0.135
 - CPU: Not sure

**Comment by mestiez** [comment]
Cannot be fixed... just Unity Box2D stuff
