### ISSUE TITLE
m1911

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1812]
**Feature description**
an m1911 pistol

**Feature purpose**
more gun

**Additional context**
no

**Comment by DindinYT37** [comment]
Isn't this just the desert eagle?

**Comment by ATPGaming** [comment]
uh no have you seen the dessert eagle? it has lots of recoil and power. m1911 is like a pocket/sidearm pistol more than anything

**Comment by DindinYT37** [comment]
> uh no have you seen the dessert eagle? it has lots of recoil and power. m1911 is like a pocket/sidearm pistol more than anything

So you mean the other pistol, which is also already in the game?

**Comment by ATPGaming** [comment]
yes sir

**Comment by ATPGaming** [comment]
but m1911 could have different stats idk

**Comment by DindinYT37** [comment]
If you know that a gun almost exactly like this, why do you even bother to request what we already have? There are mods for adding specific weapons, People Playground only adds "broader" weapons.

**Comment by ATPGaming** [comment]
sorry i just think m1911 is cool ill close it then

**Comment by Drogo-man** [comment]
> Isn't this just the desert eagle?

.45 ACP is not the same as .50 AE.

**Comment by DindinYT37** [comment]
> > Isn't this just the desert eagle?
> 
> .45 ACP is not the same as .50 AE.

You think I'm some kind of gun specialist? I'm just good at googling and it said it's similar to a desert eagle, well anyway it was already clarified that it isn't the same and this was already resolved.

**Comment by ATPGaming** [comment]
so if it was resolved then why bother replying

**Comment by DindinYT37** [comment]
> so if it was resolved then why bother replying

You should ask that him, not me.
