### ISSUE TITLE
android syring

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1814]
**Feature description**
add syring that makes human strong like android ~~and also pls add auto9 from terminator~~

**Feature purpose**
so I can rp as terminator

**Additional context**
idk it could also be called nano bot syringe or something

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #1750 
* [Metal Humans](https://steamcommunity.com/sharedfiles/filedetails/?id=2565354244)
* [Functional Terminator Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2809137426)

Also, please don't request multiple things in one issue.

**Comment by ATPGaming** [comment]
ok sorry sir
