### ISSUE TITLE
lunger

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1815]
**Feature description**
add luger gun its weaker than 9mm

**Feature purpose**
idk world war rp

**Additional context**
nope

**Comment by Drogo-man** [comment]
the luger is literally the reason 9x19mm parabellum was invented lol, so why would it be stronger than the modern one???

**Comment by Drogo-man** [comment]
also mods

**Comment by ATPGaming** [comment]
send me a link

**Comment by Drogo-man** [comment]
Just go into the workshop and write "luger" and you should find something i guess.

**Comment by ATPGaming** [comment]
thank you sir ill close it now
