### ISSUE TITLE
atp mask

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1817]
**Feature description**
add atp mask from madness combat

**Feature purpose**
its cool and we need armor in the game lol

**Additional context**
maybe not gonna happen because of copyright or something

**Comment by ATPGaming** [comment]
![image](https://user-images.githubusercontent.com/109692890/180063059-ebb34832-f17d-4282-bd45-3c7490556211.png)

**Comment by ATPGaming** [comment]
sir, are you insulting me?

**Comment by DindinYT37** [comment]
> sir, are you insulting me?

How is it an insult when I'm simply informing you because the way you create issues seems off.

**Comment by ATPGaming** [comment]
ive never used github before sorry

**Comment by ATPGaming** [comment]
pls don't ban me

**Comment by ATPGaming** [comment]
i thought you're an admin

**Comment by ATPGaming** [comment]
also sorry for saying "it's cool" i just think that and I can't come up with any other reason

**Comment by DindinYT37** [comment]
> i thought you're an admin

Nah, just active.
<br>

> also sorry for saying "it's cool" i just think that and I can't come up with any other reason

If you can't come up with any other reasons, then that should be enough reason for you to reconsider if you should even make that issue.

**Comment by ATPGaming** [comment]
ok ok, sorry, i closed it

**Comment by ATPGaming** [comment]
thanks for telling me ill make better suggestions

**Comment by ATPGaming** [comment]
and sorry for spamming suggestions i just have a lot to say I'm not a spammer
