### ISSUE TITLE
when you move guns they should click

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1818]
**Feature description**
when you move a gun hard there should be a click

**Feature purpose**
idk it just thought it sounded cool

**Additional context**
you can turn it off if you don't like it

**Comment by ATPGaming** [comment]
but when you move a pistol fast the slide might move a bit for example

**Comment by ATPGaming** [comment]
ill close it if you want me too

**Comment by Drogo-man** [comment]
if your slide moves on its own you should get your pistol checked lol.

**Comment by ATPGaming** [comment]
ok lol ill close it then
