### ISSUE TITLE
New Animations

### ISSUE THREAD

**Issue by SkyHighPurchase** [studio-minus/ppg-bugs-and-requests#182]
**Feature description**
Low Crawl, Run, and Crouch animations.

**Feature purpose**
A low crawl animation would be where the human lays down, on their chest, and slowly crawls forwards. A Run animation would be a faster (hopefully more stable) version of the walk animation. A crouch animation would be where the human would just crouch down, with one knee on the ground, and their other foot flat on the ground. All of these could be accessible by the context menu, like the other animations.

**Comment by JohnVcav** [comment]
### +1
yes, every new animation add a lot of possibilities

**Comment by mestiez** [comment]
Closed because there are other issues that seperately contain the animations grouped into this issue.
