### ISSUE TITLE
more animations

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1826]
**Feature description**
more animation like running, dancing, backflip, etc

**Feature purpose**
to make humans more fun to use, I hate having only 4 animations to choose from

**Comment by SirAJ4895** [comment]
Why was this closed?

**Comment by ATPGaming** [comment]
sir why are you always commenting on my posts???

**Comment by ATPGaming** [comment]
> Duplicate of or Related to:
> 
> * [New Animations #182](https://github.com/studio-minus/ppg-bugs-and-requests/issues/182)
> * [Animation: Crouch #255](https://github.com/studio-minus/ppg-bugs-and-requests/issues/255)
> * ["Run" animation #441](https://github.com/studio-minus/ppg-bugs-and-requests/issues/441)
> * [Crouch Animation #454](https://github.com/studio-minus/ppg-bugs-and-requests/issues/454)
> * [Allow us to use the panic animation #705](https://github.com/studio-minus/ppg-bugs-and-requests/issues/705)
> * [running #724](https://github.com/studio-minus/ppg-bugs-and-requests/issues/724)
> * [Add more "animations" #743](https://github.com/studio-minus/ppg-bugs-and-requests/issues/743)
> * [animation costructor for human #772](https://github.com/studio-minus/ppg-bugs-and-requests/issues/772)
> * [Crawling animation #825](https://github.com/studio-minus/ppg-bugs-and-requests/issues/825)
> * [More animations/poses for humans/androids #1026](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1026)
> * [Ragdoll animation in context menu #1037](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1037)
> * [Save Poses #1064](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1064)
> * [Running animation #1207](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1207)
> * [Entity Animations #1238](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1238)
> * [Limp Animation/Pose #1806](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1806)
> 
> Also, zooi (the Developer) has told us multiple times before to avoid using words like "more" or "better". While I know this was closed, I still wanted to put this here for anyone coming across.

why are you replying??? i closed it

**Comment by DindinYT37** [comment]
> > Also, zooi (the Developer) has told us multiple times before to avoid using words like "more" or "better". While I know this was closed, I still wanted to put this here for anyone coming across.
> 
> why are you replying??? i closed it

So?

**Comment by ATPGaming** [comment]
i closed it because i found duplicates that's why so you wasted your time finding the duplicates

**Comment by DindinYT37** [comment]
> i closed it because i found duplicates that's why so you wasted your time finding the duplicates

...so?

**Comment by ATPGaming** [comment]
sir i already said it

**Comment by ATPGaming** [comment]
im gonna stop replying because i already closed it and this is a waste of time trying to discuss it

**Comment by DindinYT37** [comment]
> im gonna stop replying because i already closed it and this is a waste of time trying to discuss it

There was nothing to discuss here in the first place, you just decided to stop replying because you've realized this, most likely.
