### ISSUE TITLE
Center of mass not showing up sometimes

### ISSUE THREAD

**Issue by Nicovw321** [studio-minus/ppg-bugs-and-requests#183]
**Describe the bug**
The center of mass doesn't show up sometimes.

**Clearly describe how to reproduce the bug**
Just, type S and click an object while paused, the center of mass just doesn't show up at all.

**Mod list**
None (even without mods it still doesn't show up)

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.21.3
 - GPU: Radeon RX 570
 - CPU: AMD Ryzen 5 2600

**Additional notes**
I need the center of mass so much, so yea.
(sidenote, i liked the jitter of the center of mass, it helped me grab moving objects, since it showed where the object's hitbox was)

**Comment by Nicovw321** [comment]
woops, forgot the GPU lol

**Comment by UniDuki** [comment]
Same for me, although it comes back when I zoom out a lot and move the camera far away from it.

**Comment by Nicovw321** [comment]
> Same for me, although it comes back when I zoom out a lot and move the camera far away from it.

n i c e

**Comment by mestiez** [comment]
Fixed
