### ISSUE TITLE
burst pistol

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1832]
**Feature description**
a pistol that has a 3 round burst

**Feature purpose**
for a burst weapon in the game, I know you can make it already but its hard

**Comment by DindinYT37** [comment]
It's actually not that hard to make, there are also mods for this. Though some kind of burst weapon should probably be included in People Playground.

**Comment by ATPGaming** [comment]
im not good at making stuff in the game

**Comment by DindinYT37** [comment]
> im not good at making stuff in the game

Okay but what's preventing you from subscribing to a mod that adds this? Just wondering.

**Comment by ATPGaming** [comment]
i only play vanilla people playground

**Comment by DindinYT37** [comment]
> i only play vanilla people playground

Mods are a core part of People Playground's gameplay, I'd almost say you're wasting your time if you don't use any at all.

**Comment by ATPGaming** [comment]
its my personal choice ok?

**Comment by DindinYT37** [comment]
> its my personal choice ok?

Okay, but you're gonna be wasting everyone else's time here because I can already foresee you're gonna request a **lot** of things that are already featured in many popular mods.

**Comment by ATPGaming** [comment]
ok ill just stop suggesting forever

**Comment by DindinYT37** [comment]
> ok ill just stop suggesting forever

You could also instead just check if there aren't already mods that are adding what you wanna request just fine.

*Or use mods in general, like every other person...*

**Comment by ATPGaming** [comment]
sir i already told you i dont want to use mods

**Comment by ATPGaming** [comment]
im just gonna stop suggesting, the last thing I want to do is waste a persons time

**Comment by DindinYT37** [comment]
> sir i already told you i dont want to use mods

For what reason? It's very unusual considering 90% of People Playground is all mods.

**Comment by ATPGaming** [comment]
because i tried mods before and they corrupted my saves

**Comment by DindinYT37** [comment]
> because i tried mods before and they corrupted my saves

Mods don't corrupt your saves, either Beta Versions or extremely trashy mods do.

**Comment by ATPGaming** [comment]
i just dont trust mods and im not gonna talk about this further I'm just gonna stop suggesting and play something else

**Comment by PossiblyRemember** [comment]
> i just dont trust mods and im not gonna talk about this further I'm just gonna stop suggesting and play something else

do you know how many people play Ppg? they can report bad mods, and there is already a system for rejecting suspicious mods, unless you go downloading every mod you see, you are gonna be fine, they don't corrupt save data either, the betas are pretty much the only thing that can corrupt save data, so just use mods

**Comment by ATPGaming** [comment]
gentlemen please i already said i stopped im done with this now please leave me alone

**Comment by ATPGaming** [comment]
> > i just dont trust mods and im not gonna talk about this further I'm just gonna stop suggesting and play something else
> 
> do you know how many people play Ppg? they can report bad mods, and there is already a system for rejecting suspicious mods, unless you go downloading every mod you see, you are gonna be fine, they don't corrupt save data either, the betas are pretty much the only thing that can corrupt save data, so just use mods

I'm just gonna say 1 more thing is I'm still not using mods and I was never on a beta. it corrupted my saves that I worked hard on and it was a mods fault so that's it. I'm not even gonna play this game anymore because it has so little content so I'm gonna just get rid of it from my steam library and play something else. that's it and I'm not gonna reply to anything else on my issues. if you want to say something to me then comment on my respiratory

**Comment by PossiblyRemember** [comment]
We can speak on [discord](https://discord.gg/cHDK2Rh9).

**Comment by ATPGaming** [comment]
I don't have discord so just comment on my respiratory
