### ISSUE TITLE
Remove sharp rebar

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#1835]
**Feature description**
Removal of sharp rebar from the game.

**Feature purpose**
Sharp rebar is not a good addition the game. Many contraptions use concrete slabs as building tools and destruction of such contraptions ends up being very laggy. Sharp rebar has a very small collider and a lot of it is created when multiple concrete slabs are destroyed. They simply make the game less stable. We don't need sharp rebar as a separate object. It would be more logical to add it to already existing colliding debree or simply make its collider bigger.

**Additional context**
No additional context is needed.

**Comment by DindinYT37** [comment]
What's "sharp rebar"?

**Comment by tomatoiab** [comment]
> What's "sharp rebar"?

"Destroyed concrete now has loose, sharp rebar"in PPG1.25

**Comment by DindinYT37** [comment]
Alright, I checked in-game and I can completely agree with this. Though I'd rather have it simply be a setting turned off by default, something like "small debris" or whatever.

**Comment by Gigi-7688** [comment]
I have no problem with them

**Comment by BrianTheVoid** [comment]
um, the sharp rebar is already debris, instead there should be a button in the settings to turn off all "small" debris, like, for example, flesh parts that appear when you crush humans, and obviously the "sharp rebar" you are talking about.

**Comment by DindinYT37** [comment]
> um, the sharp rebar is already debris, instead there should be a button in the settings to turn off all "small" debris, like, for example, flesh parts that appear when you crush humans, and obviously the "sharp rebar" you are talking about.

You literally just said what I explained before.

**Comment by Drogo-man** [comment]
It's literally has ZERO impact on performance.

**Comment by DindinYT37** [comment]
> It's literally has ZERO impact on performance.

This is simply incorrect, nothing can have zero impact on performance. While it has little to seemingly no impact on performance for beefy or above-average computers, in high masses or on potato computers even just the new physic calculations needed to be done for those extra objects have an impact on performance.

**Comment by mestiez** [comment]
I've made it so that it only spawns when "Fancy effects" is enabled. I've also lowered the chance of spawning in general.
