### ISSUE TITLE
New Ray cannon breaks on "Void" map

### ISSUE THREAD

**Issue by cg6016** [studio-minus/ppg-bugs-and-requests#1837]
**Describe the bug**
the ray doesnt come straight out of the cannon and heavily drops fps by a few thousand when shooting one

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
Enter the void map, spawn one ray cannon, then shoot it
**Mod list**
Black Hole Tool - Enabled
Right Click Menu Options - Disabled

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.25
 - GPU: NVIDIA GeForce GTX 1660 Super
 - CPU: AMD Ryzen 5 3600

**Additional notes**
who knew a single object could drop 1k fps

**Comment by Drogo-man** [comment]
This is on all maps and yeah it's really annoying

**Comment by DindinYT37** [comment]
Doesn't happen for me.

**Comment by mestiez** [comment]
Fixed :)
