### ISSUE TITLE
Humans do not die from impact with bodies of water

### ISSUE THREAD

**Issue by Gigi-7688** [studio-minus/ppg-bugs-and-requests#1839]
-Describe the bug

Humans can survive falls of more than 1,000 meters (the highest point in the Hybrid) over bodies of water.
According to what I found on Google, the maximum height before suffering serious/mortal damage is around 70-80m.

-Clearly describe how to reproduce the bug

Drop a human into the water from any height.

-Mod list

All loaded mods

	GalaxyHighMarshal-BloodEnhancedMod-2811563551 v2.0 for game v1.23+
		Currently inactive

	Orsoniks / Navii-Reactive humans-2793371344 v1.0 for game v1.23+
		Currently inactive

	Team Wilson-People Playground 3D-2785176210 v1 for game v1.21+
		Currently inactive

	JOSIMA-Enhanced Human Sounds-2738554876 v0.1 for game v1.11+
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently ACTIVE

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently ACTIVE

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently ACTIVE
		Has been initialised

	zooi-Per Pixel Destruction-2314372940 valpha 7 for game v1.13.1
		Currently inactive

	Morzzic-Photo Mode-2263832258 v1.0 for game v1.8+
		Currently ACTIVE

	zooi-Controllable anti-air cannon-2178648827 v1.2 for game v1.9.3
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently inactive

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently inactive

-System info

People Playground [v1.25.4] [64 bit]

System info:

OS: Windows 10 (10.0.22000) 64bit
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU: NVIDIA GeForce RTX 2060
Memory: 16 GB

-Additional notes

I don't know if this is a bug or a feature request.
![what](https://user-images.githubusercontent.com/102178009/180583115-4f99b6f1-7ff6-49ed-871e-47e16e70beb9.png)

**Comment by SomeBloodyMinger** [comment]
That's odd. To my knowledge, before 1.25 was released, people used to die fairly consistently at certain heights and it was actually quite realistic. Perhaps with the tinkering of the fall damage in the latest update, it has broken the fall damage of colliding with the water?

**Comment by Gigi-7688** [comment]
It's possible

**Comment by mestiez** [comment]
I've increased water impact damage a bit
