### ISSUE TITLE
disable burning makes them really strong

### ISSUE THREAD

**Issue by mjeic** [studio-minus/ppg-bugs-and-requests#1841]
**Describe the bug**
When ever you have a human (don't know about robot) and click disable burning it basically makes them invincible except for strong head injuries. If their heart is stopped and you disable burning it makes their heart not stopped, they wont freeze, and they wont really bleed out or die to anything. Any damage to the head that would normally kill them will kill them, they do not regenerate just don't die as they normally would.
**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
1. Spawn human (can do robot don't really know).
2. Scroll down and click disable burning.
3. Shoot, freeze, hit, and burn. wont die as they should except for explosions and head shots.
**Mod list**
Include a list of your mods here and specify whether they're activated or not. Make sure to include deactivated mods, as they could 
still have an effect.
I do not have any mods at the moment
**System info (please complete the following information)**
 - Operating system: Computer
 - Game version: 1.25
 - GPU: not sure
 - CPU: not sure

**Additional notes**
I'm sorry if anything I said was not clear I will check in on this occasionally for any questions and things to clear up.

**Comment by DindinYT37** [comment]
Your System info is literally useless and this is caused by a mod because there is no "Disable Burning" button in People Playground.

**Comment by mjeic** [comment]
well I'm not sure on how to check my system info  and I have no mods to my knowledge but I guess maybe I have some without realizing

**Comment by mjeic** [comment]
> Your System info is literally useless and this is caused by a mod because there is no "Disable Burning" button in People Playground.

first of all I just want to say that was a very polite way of addressing an issue to someone who is obviously not very well used to a computer such as yourself a "Computer wizard" second of all in no way is knowing my GPU or CPU going to help with why that would be happening and third of all I did figure out that I had 2 mods installed (couldn't have figured it out without your super polite response) and it turns out my brother installed them when he was playing. I would like to say that yes this was on my end and should've checked in on this but if you want to work with computers maybe instead of just learning how to work with computers you should work on how to not come off as rude and having an attitude over messages online. would really look good to any future employers. Sad that with 9 maybe close to 10 years of programming out of all of that time you couldn't have figured out how to come up with a much nicer response. in any future times I find a bug with this game or any other in that matter ill think back to you and you're very nice response and think to check if I have any mods installed or anything else like that

**Comment by DindinYT37** [comment]
And you surely know I won't read this, right?

**Comment by mjeic** [comment]
> And you surely know I won't read this, right?

then don't respond dummy. Like what

**Comment by DindinYT37** [comment]
> > And you surely know I won't read this, right?
> 
> then don't respond dummy. Like what

Not responding would make you think you're in the right though.

**Comment by mjeic** [comment]
> > > And you surely know I won't read this, right?
> > 
> > 
> > then don't respond dummy. Like what
> 
> Not responding would make you think you're in the right though.

the fact you think that something like that shows what type of person you are never acknowledging that maybe you aren't always correct I don't think I'm in the right or wrong and neither are you but when working with computers for that long maybe show a little professionalism

**Comment by PossiblyRemember** [comment]
> > > > And you surely know I won't read this, right?
> > > 
> > > 
> > > then don't respond dummy. Like what
> > 
> > 
> > Not responding would make you think you're in the right though.
> 
> the fact you think that something like that shows what type of person you are never acknowledging that maybe you aren't always correct I don't think I'm in the right or wrong and neither are you but when working with computers for that long maybe show a little professionalism

both of you, shush, this comment should be the end of this argument

**Comment by DindinYT37** [comment]
> both of you, shush, this comment should be the end of this argument

You **ain't** the one to decide that but I guess, since is getting cluttered anyway.
