### ISSUE TITLE
Brain damage via lack of oxygen

### ISSUE THREAD

**Issue by NarriX** [studio-minus/ppg-bugs-and-requests#1845]
**Feature description**
When people in peoples playground run out of oxygen they should get brain damage. (Like when they are held underwater for too long, as they die they get brain damage)

**Feature purpose**
Added realism

**Comment by DindinYT37** [comment]
For further information, see [this article about Cerebral hypoxia](https://medlineplus.gov/ency/article/001435.htm#:~:text=Brain%20cells%20are%20very%20sensitive,severe%20brain%20damage%20or%20death.).
