### ISSUE TITLE
Ambient audio pitch is incorrect right after switching a map

### ISSUE THREAD

**Issue by MattapoisettPatton27** [studio-minus/ppg-bugs-and-requests#1846]
**Describe the bug**
When you first choose the map you want after loading the game, it sounds normal. However if you switch the map without restarting the game first the ambience and sound of floodlights turning on completely messes up and i don't know how to describe it. I attached a video so you can see what I'm talking about though. Restarting the game and then going into another map makes it normal.

https://user-images.githubusercontent.com/109884833/180629981-7f8e2d6c-adb7-40d7-9ff8-03275f33bdba.mp4

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
-launch the game
-choose any map
-exit that map and choose another one
**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
"The Ultimate Minecraft Mod" (activated)
**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.25
 - GPU: 15.8 GB
 - CPU: ~2 GHz

**Additional notes**

**Comment by mestiez** [comment]
fixed
