### ISSUE TITLE
Armor plate

### ISSUE THREAD

**Issue by EEASAS** [studio-minus/ppg-bugs-and-requests#1849]
**Feature description**
Armor plate which has greater penetration protection than regular ballistic sheet

**Feature purpose**
More type of armor in vanilla , and so we dont have to resize the clunky ballistic sheets to put them on a human

**Additional context**
![OIP](https://user-images.githubusercontent.com/109891564/180635305-f6b9579e-6d8a-43a9-b6a9-6d5ea6c6b6ac.jpg)

**Comment by kinlee2352** [comment]
The "Bulletproof Sheet" is technically an armor plate. If you are unhappy with the textures, you can customize/modify it in the game files, or modify it with more items.

**Comment by EEASAS** [comment]
I dont know how to art.

**Comment by Drogo-man** [comment]
The bulletproof sheet is an armor plate.

**Comment by bibbybabby** [comment]
> I dont know how to art.

![armor plate](https://user-images.githubusercontent.com/104321411/180646625-b3d03e2d-e539-4a7f-a217-148a15417448.png)
^ I made this sprite specifically for this post for free

**Comment by mestiez** [comment]
Actual armour and clothing is on the "wishful thinking" list so it has a good chance of making it into the game already.
