### ISSUE TITLE
Remove button physics

### ISSUE THREAD

**Issue by plopilpy** [studio-minus/ppg-bugs-and-requests#185]
It's always frustrating when my buttons in something like a car, which has to move, are affected by inertia. As the car/object moves, the button is pushed because of the inertia it's subjected to. Can zooi please fix this?

**Comment by UniDuki** [comment]
I like to use that to tell if something is moving fast.

**Comment by JohnVcav** [comment]
maybe give the button some resistance before it's recognized as a full press?

**Comment by mestiez** [comment]
Follow the template please
