### ISSUE TITLE
String Tissue

### ISSUE THREAD

**Issue by kinlee2352** [studio-minus/ppg-bugs-and-requests#1851]
**Describe the bug**
The graphical issue, If someone has the "stringy tissue" keeping their limbs together, If they were to put it behind their back, you can still see the tissue. 
![image](https://user-images.githubusercontent.com/109797067/180635798-ac4d5571-a3c2-4b9b-a4bd-c2714d48f4c5.png)

**Clearly describe how to reproduce the bug**
Get a chainsaw, and put it on someone's lower arm.
Then, cut off the arm and put it to the side.

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows
 - Game version: Latest
 - GPU: I can't remember
 - CPU: I can't remember

**Comment by PossiblyRemember** [comment]
This is similar to another issue that was posted, I'll edit this comment when I find it

On the menu you can go to information and export game info to put your system info
