### ISSUE TITLE
Decrease heat damage

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#1854]
**Feature description**
Heat and fire are very overpowered. It takes more than a minute for a human to die of burning in real life and in game they die much faster. I suggest decreasing heat damage to a point where it's still dangerous but not a quick painless death.

**Feature purpose**
Humans dying within less than half a minute of burning is dissatisfying and not realistic. Most of the systems in this game are unbalanced in general.

**Additional context**
No need for additional context.

**Comment by DindinYT37** [comment]
Related to #1774

**Comment by EfeYks534** [comment]
_Unrelated to the issue_
I see you've made it a job for yourself to mini-mod this issue page. I suggest taking a break from the internet and going outside, it's the middle of summer in the northern hemisphere. This is the perfect time to go to the beach and have a nice time.

**Comment by PossiblyRemember** [comment]
> _Unrelated to the issue_ I see you've made it a job for yourself to mini-mod this issue page. I suggest taking a break from the internet and going outside, it's the middle of summer in the northern hemisphere. This is the perfect time to go to the beach and have a nice time.

_Unrelated to the issue_
bro he said it was related, and he's not even mini-modding, get a hold of yourself it's only a comment, and blocking him from commenting on your issues I would say is a step too far saying he's doing more help on this github than you just did

**Comment by EfeYks534** [comment]
I wrote "unrelated to the issue" as in my comment was unrelated to my issue (off-topic). He is mini-modding, you will realize if you click any random issue on this page. He's not doing any help, I would go into this but I don't want it to turn into an argument. I can block anyone I want if I don't want to see their messages and it's definitely not too far.

**Comment by PossiblyRemember** [comment]
> I wrote "unrelated to the issue" as in my comment was unrelated to my issue (off-topic). He is mini-modding, you will realize if you click any random issue on this page. He's not doing any help, I would go into this but I don't want it to turn into an argument. I can block anyone I want if I don't want to see their messages and it's definitely not too far.

he spoke 3 words that can't harm you in any way whatsoever and he deserves to be blocked? who cares if you like it, it's there, whether you like it or not, and it help zooi check if issues are related/duplicates or not, and you can honestly just ignore him
