### ISSUE TITLE
bear trap

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1857]
**Feature description**
add a bear trap like in melon playground that has a button, when humans step on it closes and causes wounds

**Feature purpose**
it would be fun throwing the people into bear traps

**Additional Context**
it would probably be in misc category

related to https://github.com/studio-minus/ppg-bugs-and-requests/issues/822

**Comment by DindinYT37** [comment]
Duplicate of #822

**Comment by ATPGaming** [comment]
i just said that on the issue

**Comment by DindinYT37** [comment]
You said it's related, but it's not. It's a duplicate, which makes this whole request useless and that also means this will just get closed.

**Comment by ATPGaming** [comment]
> You said it's related, but it's not. It's a duplicate, which makes this whole request useless and that also means this will just get closed.

ok done
