### ISSUE TITLE
human pain spots

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1858]
**Feature description**
humans should have certain spots that cause more pain like their eyes or crotch

**Feature purpose**
realism because irl when you get hit there it hurts

**Additional context**
probably not gonna happen, but it's still worth asking for

**Comment by PossiblyRemember** [comment]
I don't know if there is an intensity for pain on humans, and didn't you say you were gonna stop playing ppg and stop requesting stuff forever?

**Comment by ATPGaming** [comment]
well i was just upset and being overdramatic. i get like that sometimes

**Comment by ATPGaming** [comment]
> I don't know if there is an intensity for pain on humans, and didn't you say you were gonna stop playing ppg and stop requesting stuff forever?

if you click inspect then you can see "shock" meter which is technically pain intensity

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #172
* #339
* #343
* #352
* #1366 

*This is basically just not-so-vital spots.*

**Comment by ATPGaming** [comment]
not quite, those are spots that are lethal when injured, mine are spots that are cause more pain

**Comment by PossiblyRemember** [comment]
I would imagine if I stabbed your crotch with a knife you'd pretty much be dead

**Comment by ATPGaming** [comment]
i cant confirm it since im not exactly a doctor

**Comment by DindinYT37** [comment]
> not quite, those are spots that are lethal when injured, mine are spots that are cause more pain

Exactly why I said it's basically not-so-vital spots.

**Comment by DindinYT37** [comment]
> I would imagine if I stabbed your crotch with a knife you'd pretty much be dead

Kinda doubt but I don't know and certainly won't look this up.

**Comment by PossiblyRemember** [comment]
> > I would imagine if I stabbed your crotch with a knife you'd pretty much be dead
> 
> Kinda doubt but I don't know and certainly won't look this up.

more of dead on the inside

**Comment by ATPGaming** [comment]
sucks
