### ISSUE TITLE
let us save debris

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1859]
**Feature description**
you should be able to save brick debris and stuff

**Feature purpose**
if you want to make a battle scene or a run-down building

**Additional context**
alternate solution is to add debris items

**Comment by PossiblyRemember** [comment]
how many more requests are you going to open

**Comment by ATPGaming** [comment]
i just have a lot of ideas. how many more times are you gonna ask me things irrelevant to my request?

**Comment by PossiblyRemember** [comment]
> i just have a lot of ideas. how many more times are you gonna ask me things irrelevant to my request?

by your logic, I just have a lot of questions

**Comment by ATPGaming** [comment]
ok, you're right.

**Comment by ATPGaming** [comment]
> how many more requests are you going to open

I'm trying not to spam but i also wanna get my ideas out
