### ISSUE TITLE
Bandaged wounds heal after some time.

### ISSUE THREAD

**Issue by SkyHighPurchase** [studio-minus/ppg-bugs-and-requests#186]
**Feature description**
Bandaged wounds will slowly heal over time.

**Feature purpose**
I decided I want this because I have some strange fascination of taking care of the injured humans. This all happened just a few minutes ago when a human's arms both fell off. I bandaged him up, and thought of how I'd get him back to health, then realzied I couldn't. I believe this feature would be nice, as it would add some "realism" to the game.

**Comment by StealthDrifter** [comment]
they do

**Comment by StealthDrifter** [comment]
https://gyazo.com/b39ccae8f24f9d85f3da597809de3850

**Comment by JohnVcav** [comment]
You probably forgot to give him blood after bandaging

**Comment by UniDuki** [comment]
They "heal" but not visually at all, which would be very nice if they did.

**Comment by JohnVcav** [comment]
you could always use the mending syringe for that effect. I don't know if having him act like wolverine is the best for the game

**Comment by JohnVcav** [comment]
Maybe have the bandage heal him visually overtime corresponding to limb integrity?

**Comment by TamasB14** [comment]
> They "heal" but not visually, which would be very nice if they did.
> For example, this guy got hit by a car and died. I bandaged him up and shocked him with the defibrillator. He is alive and "healed" but you would think he's a rotting corpse if you saw him.
> ![image](https://user-images.githubusercontent.com/69184577/132223941-e823a68e-6901-4de7-a3a4-91161836c674.png)

Mending syringe does the job for rotting parts.

**Comment by UniDuki** [comment]
I'm not talking about reversing rot, I think bandages should visually heal wounds instead of secretly healing them.

**Comment by JohnVcav** [comment]
yea, sometimes you just have skelethor walking around like nothing happened

**Comment by SkyHighPurchase** [comment]
> They "heal" but not visually, which would be very nice if they did.
> For example, this guy got hit by a car and died. I bandaged him up and shocked him with the defibrillator. He is alive and "healed" but you would think he's a rotting corpse if you saw him.
> ![image](https://user-images.githubusercontent.com/69184577/132223941-e823a68e-6901-4de7-a3a4-91161836c674.png)

This is what I want. A visual healing.

**Comment by mestiez** [comment]
forgot to close this ages ago
