### ISSUE TITLE
Development branch in betas

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#1861]
**Feature description**
You know the gmod dev branch? This is pretty much that but for PPG

**Feature purpose**
So regular peasants could have the chance of admiring the Great and **Highly** Unstable Builds

**Additional context**
![image](https://user-images.githubusercontent.com/104321411/180666805-bb40ec58-7d65-44c1-aecc-b6e860234b35.png)

**Comment by ATPGaming** [comment]
if theyre highly unstable it might not be the best idea to let people play them

**Comment by PossiblyRemember** [comment]
I would LOVE this, and it could also help zooi with dev build bugs so that when it releases to beta or release most of the bugs will be fixed. I am a big alpha tester myself so this would be brilliant!

**Comment by ATPGaming** [comment]
i retract my statement earlier. it would be better so we don't have to submit 18 bug reports AFTER the update gets released

**Comment by DindinYT37** [comment]
> if theyre highly unstable it might not be the best idea to let people play them

Then don't play it.

**Comment by DindinYT37** [comment]
> I would LOVE this, and it could also help zooi with dev build bugs so that when it releases to beta or release most of the bugs will be fixed. I am a big alpha tester myself so this would be brilliant!

PossiblyRemember zooi-fanboy moment

**Comment by ATPGaming** [comment]
> DindinYT37

i just said i retracted my statement in the message above? maybe if you read it you would realize that

**Comment by PossiblyRemember** [comment]
> > I would LOVE this, and it could also help zooi with dev build bugs so that when it releases to beta or release most of the bugs will be fixed. I am a big alpha tester myself so this would be brilliant!
> 
> PossiblyRemember zooi-fanboy moment

bruh

**Comment by bibbybabby** [comment]
everybody calm down i dont want my request to be flooded with arguments and insults

**Comment by ATPGaming** [comment]
he's right, i dont want more "incidents" here

**Comment by DindinYT37** [comment]
> > DindinYT37
> 
> i just said i retracted my statement in the message above? maybe if you read it you would realize that

I said it because it was still a valid argument, maybe you would've realized if your brain was properly functioning.

**Comment by DindinYT37** [comment]
> everybody calm down i dont want my request to be flooded with arguments and insults

That wasn't gonna happen from the moment ATPGaming commented here because he seems to always be slow on getting things.

**Comment by PossiblyRemember** [comment]
> everybody calm down i dont want my request to be flooded with arguments and insults

you might want to turn off notifications for the next few messages, things seem to be getting intense

**Comment by DindinYT37** [comment]
> > everybody calm down i dont want my request to be flooded with arguments and insults
> 
> you might want to turn off notifications for the next few messages, things seem to be getting intense

Usually he understands after an explanation though so I doubt there's gonna be further discussion here.

**Comment by ATPGaming** [comment]
> > everybody calm down i dont want my request to be flooded with arguments and insults
> 
> That wasn't gonna happen from the moment ATPGaming commented here because he seems to always be slow on getting things.

I'm gonna be the bigger man here and not continue this argument. think what you want about me but I'm just as smart as anyone else here and i realize that arguing is not going to accomplish anything.

**Comment by DindinYT37** [comment]
> I'm gonna be the bigger man here and not continue this argument. think what you want about me but I'm just as smart as anyone else here and i realize that arguing is not going to accomplish anything.

That doesn't make you the bigger man, that makes you a person with a functioning brain.

**Comment by PossiblyRemember** [comment]
> > > everybody calm down i dont want my request to be flooded with arguments and insults
> > 
> > 
> > That wasn't gonna happen from the moment ATPGaming commented here because he seems to always be slow on getting things.
> 
> I'm gonna be the bigger man here and not continue this argument. think what you want about me but I'm just as smart as anyone else here and i realize that arguing is not going to accomplish anything.

*not as to continue this*, but you do realize by commenting right now you just continued it?

**Comment by DindinYT37** [comment]
> _not as to continue this_, but you do realize by commenting right now you just continued it? if you don't reply he won't say anything, it's nothing to be offended by, just don't say anything else

I clarified his incorrect statement, I haven't continued the argument as that was another topic. Though it might seem so, it really isn't.

**Comment by mestiez** [comment]
hello everyone. idk whats going on here but this is basically what the beta branch is.

**Comment by PossiblyRemember** [comment]
pretty sure they mean a beta branch more beta than beta, or to put it simply alpha branch where features nowhere near finished can be tested

**Comment by bibbybabby** [comment]
The beta branch is for previews, the dev branch is the most recent build that is being developed on
