### ISSUE TITLE
 tree hitbox is broken

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1862]
**Describe the bug**
tree hitbox is broken on one side, because its larger than it should be
![Screenshot (3603)](https://user-images.githubusercontent.com/109692890/180667217-51329d75-fa89-4aca-b511-8b4435b3e4d7.jpg)

**Clearly describe how to reproduce the bug**
move an object onto the sides of a tree, one on of the sides the hitbox is larger than it should be

**Mod list**
i never use mods

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.25
 - GPU: idk
 - CPU: idk

**Comment by PPGTemplateNerd** [comment]
Related to #1090

**Comment by ATPGaming** [comment]
who are you

**Comment by Gigi-7688** [comment]
I suggest you close it.
Zooi has already said that hitboxes are not accurate to improve performance.

**Comment by mestiez** [comment]
No don't close it. The collision shape is inaccurate because there are two sprites for the tree trunk. The collision shape was a fucked up mix that kind of fit both sprites. I have edited the sprites to better match each other and share one collision shape.

**Comment by mestiez** [comment]
fixed n stuff

**Comment by ATPGaming** [comment]
thanks zooi

**Comment by Gigi-7688** [comment]
oh, sorry
