### ISSUE TITLE
advanced collisions option

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1863]
**Feature description**
add an option that makes shape collisions more advanced and accurate

**Feature purpose**
for people who don't have potato pcs and can handle complex collision shapes

**Comment by PossiblyRemember** [comment]
guessing this is because of tree hitboxes? *decent* idea either way

**Comment by DindinYT37** [comment]
That actually depends on the mods you're using, vanilla People Playground pretty much has very accurate hitboxes.

Related to:
* #1090 
* #1862

**Comment by ATPGaming** [comment]
yes its mostly for the tree collisions to be more complex and accurate, the objects already in the game are pretty good with their collisions though

**Comment by DindinYT37** [comment]
So basically, you requested almost the same exact thing of what a request that was just made was requesting - **again**?

**Comment by ATPGaming** [comment]
well zooi wont make the collisions more accurate normally because it would degrade performance, but it COULD be an option too if it wont be by default for people with better pcs

**Comment by PossiblyRemember** [comment]
it'd be nice if there was another option for extra beefy PCs to dynamically generate mod models along with complex vanilla models,

**Comment by ATPGaming** [comment]
thats a really smart idea

**Comment by DindinYT37** [comment]
> well zooi wont make the collisions more accurate normally because it would degrade performance, but it COULD be an option too if it wont be by default for people with better pcs

I'm not saying what you do is wrong, especially since this is not an exact duplicate like the issue you made before. I just found it interesting that it happened again.

**Comment by mestiez** [comment]
super accurate collision shapes are WAY more demanding than youre probably thinking. it would be completely unnecessary and unplayable.
