### ISSUE TITLE
bouncier shell casing

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1864]
**Feature description**
shell casing should bounce after hitting the ground like it does irl

**Feature purpose**
realism, and to make shell casing less stiff

**Additional context**
might only be when fancy effects are turned on

**Comment by Gigi-7688** [comment]
If you look in slow motion, you can see that the shell casings are already bouncing.

**Comment by ATPGaming** [comment]
not as much as in real life tho

**Comment by DindinYT37** [comment]
> not as much as in real life tho

Did you measure it, or how do you know?

**Comment by ATPGaming** [comment]
shell casing bounces higher than that, ive seen videos

**Comment by PossiblyRemember** [comment]
> shell casing bounces higher than that, ive seen videos

not everything you see on video is real mate
