### ISSUE TITLE
Better dismemberment 

### ISSUE THREAD

**Issue by poopy-monkez** [studio-minus/ppg-bugs-and-requests#1865]
**Feature description**
Make a few spawnables that are prosthetic limbs they could be different colors or have different effects like a normal leg or a running hook

**Feature purpose**
It could be used for making cyborg designs or used to fix a dismembered human

**Comment by DindinYT37** [comment]
So how is this better dismemberment?

**Comment by PossiblyRemember** [comment]
and hasn't this been rejected before?

**Comment by ATPGaming** [comment]
you should rename this to "prostetic limbs"

**Comment by DindinYT37** [comment]
Alright imma get the list

**Comment by ATPGaming** [comment]
Related to:
https://github.com/studio-minus/ppg-bugs-and-requests/issues/254
https://github.com/studio-minus/ppg-bugs-and-requests/issues/1612
https://github.com/studio-minus/ppg-bugs-and-requests/issues/1212
https://github.com/studio-minus/ppg-bugs-and-requests/issues/425

**Comment by DindinYT37** [comment]
Duplicate or Similar requests:
* #254
* #435
* #629
* #709
* #1612
* #1631 
* #1652
* #1739
* #1778 

Also, please use the template.

**Comment by ATPGaming** [comment]
dang

**Comment by PossiblyRemember** [comment]
> dang

he takes his job seriously

**Comment by ATPGaming** [comment]
his job of being a mini mod?

**Comment by PossiblyRemember** [comment]
> his job of being a mini mod?

no his job of helping zooi see if it's a duplicate/related to another issue, seriously why do you people call it mini-modding

**Comment by ATPGaming** [comment]
sorry

**Comment by DindinYT37** [comment]
> > his job of being a mini mod?
> 
> no his job of helping zooi see if it's a duplicate/related to another issue, seriously why do you people call it mini-modding

Here some definitions:
![image](https://user-images.githubusercontent.com/64973205/180668533-8e51b317-f551-4660-a161-134efcdb8668.png)
![image](https://user-images.githubusercontent.com/64973205/180668565-34aa403b-4148-453c-a3e6-fe8606280791.png)

**Comment by ATPGaming** [comment]
sorry youre actually helpful though and sorry i called you a minimod

**Comment by DindinYT37** [comment]
> sorry youre actually helpful though and sorry i called you a minimod

You don't have to apologize but I'd rather not have you call me mini-mod all the time.

**Comment by PossiblyRemember** [comment]
> sorry youre actually helpful though and sorry i called you a minimod

oh and btw, I am now your father

**Comment by ATPGaming** [comment]
oh no

**Comment by mestiez** [comment]
please dont engage in off topic useless conversations
