### ISSUE TITLE
Death from hypothermia is unrealistic

### ISSUE THREAD

**Issue by Frederick-7689** [studio-minus/ppg-bugs-and-requests#1867]
-Feature description
Currently, humans go into cardiac arrest when they reach a body temperature of 36°C/35°C.
This occurs when the ambient temperature is about -8°C/-9°C and the heart stops in about 10 seconds (depending on the human's stature).
Actually, cardiac arrest occurs when the body temperature is 28°C or less, but loss of consciousness occurs first.
Moreover, I do not believe that a man dies after only 10 seconds at an ambient temperature of -8°C (even without clothes).
As for the time before death, I found the following information on the Internet:

In the air, hypothermia can develop in as little as five minutes in temperatures of minus -50°F/-45.5°C in people who are not dressed properly and have exposed skin. At -30°F/-34.4°C, hypothermia can occur in about 10 minutes. Death can occur in under an hour in extremely cold conditions.

-Feature purpose
Obviously ralism

-Additional context
It's annoying to see human beings dying in standing after 10 seconds at a temperature of -8°C.

https://user-images.githubusercontent.com/102178009/180677628-d3da1138-f5db-4721-8d04-33df9770b0b4.mp4

**Comment by mestiez** [comment]
I've made a lot of changes to make it more realistic.

**Comment by mestiez** [comment]
though I won't make things as slow as in real life because it's not fun lmao

**Comment by Gigi-7688** [comment]
Of course, they were only directions.
