### ISSUE TITLE
New Item: spotlight

### ISSUE THREAD

**Issue by TamasB14** [studio-minus/ppg-bugs-and-requests#187]
**Feature description**
Similiar to floodlight but it's radious is much more longer and less more wider. It's radious would be three times longer than floodlight

**Feature purpose**
Replacing the need for high powering a foodlight and also giving players alot more comfort and a better looking spotlight.

**Additional context**
Could help people create "Air Raid" scenes at night without needing all the pesky equipment.

**Comment by LaCumbiaDelCoronavirus** [comment]
Dude, just use a flashlight

**Comment by idotwaffle** [comment]
> Dude, just use a flashlight

are you stupid, it is nowhere near as powerful as even the current "floodlight"

**Comment by TamasB14** [comment]
> Dude, just use a flashlight

It's nowhere near as powerful. You can't high power a flashlight to be a floodlight without it heating up or at worst... breaking.

**Comment by idotwaffle** [comment]
#175

**Comment by LaCumbiaDelCoronavirus** [comment]
> > Dude, just use a flashlight
> 
> It's nowhere near as powerful. You can't high power a flashlight to be a floodlight without it heating up or at worst... breaking.

If you're alright with it just make them thin but long. That extends by a bit.
