### ISSUE TITLE
thermal change

### ISSUE THREAD

**Issue by MrHushPPG** [studio-minus/ppg-bugs-and-requests#1872]
Feature description
At high temperatures, some things (like metal rods) will bend when exposed to high temperatures. Let's say I heated metal to 1000 degrees and dropped a one-ton bar on this rod and the rod bent. Also wood can tend to burn and leave behind something like embers. The strange thing is that the wood just turns black after burning and does not lose functionality.
Feature purpose
Realism

**Comment by Frederick-7689** [comment]
https://github.com/studio-minus/ppg-bugs-and-requests/issues/659
