### ISSUE TITLE
Effects don't scale with object

### ISSUE THREAD

**Issue by Mesalon** [studio-minus/ppg-bugs-and-requests#1876]
**Describe the bug**
When you scale something like a generator, the sparks (sparks?) don't scale thus making it pretty distracting.
![image](https://user-images.githubusercontent.com/78909282/180863906-32a4b37e-745d-49a5-8d1f-e3bfe74a6110.png)

**Clearly describe how to reproduce the bug**
Scale a generator.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: Unsure. Most recent one.
 - GPU: Nvidia RTX 2070
 - CPU: Intel i7-9750H

**Comment by mestiez** [comment]
Fixed :)

**Comment by Mesalon** [comment]
Thanks. Love you zooi.
