### ISSUE TITLE
Main Menu Music

### ISSUE THREAD

**Issue by PizzaBroadcast** [studio-minus/ppg-bugs-and-requests#1892]
**Feature description**
You have a menu SOUND, why not add some music over it? Doesn't even have to be complex, _maybe_ just random notes being played that progressively get louder then quieter at some point.

**Feature purpose**
Adds atmosphere to the main menu, which is usually dull and gives you an uneasy feeling.

**Additional context**
I like music

**Comment by bibbybabby** [comment]
I think it's supposed to give you an uneasy feeling

**Comment by PossiblyRemember** [comment]
> I think it's supposed to give you an uneasy feeling 

The whole game does this to me with the creepy ambient sounds, I just turn ambient sounds off

**Comment by MaxeUA** [comment]
no.
