### ISSUE TITLE
Bug with PhysicalProperties

### ISSUE THREAD

**Issue by Chagarock** [studio-minus/ppg-bugs-and-requests#1893]
**The bug**
I made a mod that adds a custom human. When I set up his limbs with PhysicalProperties, all the properties I gave him after he spawns are applied to all Humans.

**How to reproduce the bug**
1. Make a mod that adds a custom human (https://github.com/mestiez/ppg-snippets/blob/master/making%20a%20new%20human.cs);
2. Adjust his limbs with PhysicalProperties (to make the problem clearer, set Softness to 0);
3. Go into the game and pierce an ordinary human with a sword or other sharp object and it will pierce;
4. After spawn the human you made and again try to pierce the same human after that and it will no longer be pierced and it will also be the same with the subsequent humans you spawn.
**(Sorry for my bad english)**

**Mod list**
Only my mod with which I have this bug

**Sys info**
 - OS: Windows 10
 - Game version: 1.25
 - GPU: Nvidia GeForce GTX 960M
 - CPU: intel i5

**Note**
PhysicalProperties - https://www.studiominus.nl/ppg-modding/internalReference/PhysicalProperties.html

**Comment by DindinYT37** [comment]
I'm pretty sure things like Softness are readonly.

**Comment by Chagarock** [comment]
> I'm pretty sure things like Softness are readonly.

No, otherwise after compiling the mod would give an error. This is definitely a bug.

**Comment by DindinYT37** [comment]
> > I'm pretty sure things like Softness are readonly.
> 
> No, otherwise after compiling the mod would give an error. This is definitely a bug.

I was thinking of Friction, which is read-only. mb

**Comment by mestiez** [comment]
PhysicalProperties are shared. You should create a new one that you share across your custom objects. This is not a bug, but it does mean that I haven't properly explained how they work in the docs.

**Comment by mestiez** [comment]
For future reference or anyone who comes across this issue:

```cs
static PhysicalProperties CustomProps;

void Main()
{
   CustomProps = ModAPI.FindPhysicalProperties("Human"); //this method finds the properties and returns a copy. try to make as few copies as possible.
   //the rest of your code
}
```
then somewhere else
```cs
Instance.GetComponent<PhysicalBehaviour>().Properties = Mod.CustomProps; //or whatever namespace you chose
```

**Comment by Chagarock** [comment]
@mestiez, THANK YOU SO MUCH1!! YOU ARE THE BEST!!

**Comment by Chagarock** [comment]
@mestiez, **_I'm sorry, then I decided not to write right away because maybe I misunderstood something. But I assume that you wrote to me about "Physical properties", and not about "PhysicalProperties"._**

**To make it clearer:**
- "**_Physical properties_**" - https://www.studiominus.nl/ppg-modding/snippets/physicalProperties.html
- "**_PhysicalProperties_**" - https://www.studiominus.nl/ppg-modding/internalReference/PhysicalProperties.html

About "Physical properties" I know, they work fine. For "Physical properties" I use the following code:
```
foreach (var limb in Instance.GetComponent<PersonBehaviour>().Limbs {
    limb.PhysicalBehaviour.Properties = ModAPI.FindPhysicalProperties("something");
}
```

**My problem is with "PhysicalProperties"**: All the properties that I give my custom human with "PhysicalProperties" apply to all other humans after it spawns. And even if you exit from any map and enter again (without leaving the game), then these properties will remain. Here is a snippet from my code:

```
foreach (var limb in Instance.GetComponent<PersonBehaviour>().Limbs) {
    limb.PhysicalBehaviour.Properties.Softness = 0;
    limb.PhysicalBehaviour.Properties.BulletSpeedAbsorptionPower = float.PositiveInfinity;
}
```

And I am also confused by the fact that the documentation says: "How easily sharp objects stab **this object**.", "Determines how much of the kinectic energy in bullets is absorbed by **this material**.", etc. (https://www.studiominus.nl/ppg-modding/internalReference/PhysicalProperties.html). It refers to a specific object. That is, it is not written there that this property will be applied to all objects. Therefore, it seems to me that this should not be the case.

Please reply and sorry for disturbing. It still seems to me that I misunderstood something, I will wait for your answer.
