### ISSUE TITLE
Collision View

### ISSUE THREAD

**Issue by hermoron** [studio-minus/ppg-bugs-and-requests#1898]
It has a similar function to 'Thermal Vision'. Pressing a key will enable this feature that highlights any objects colliding with with the object you are holding or hovering at. (With an exception to disabled collision or phase links). The appearance can perhaps match the red highlight you see when hovering over a wire. This collision view can working even when time is paused.

There are times where I eyeball whether the object is colliding with another. But there are also times where the collision box has a small invisible gap and makes it harder to figure out whether I need to use a phase link or disable collision. 

This will be helpful to builders who require precise knowledge whether there will be collision conflicts within their contraptions 
This collision view can working even when time is paused.

**Comment by DindinYT37** [comment]
Please use the template.
