### ISSUE TITLE
Measuring Line

### ISSUE THREAD

**Issue by hermoron** [studio-minus/ppg-bugs-and-requests#1899]
The measuring line is another tool within the wire menu that looks sort of like a hazard yellow and black stripes. Holding the mouse button, It can anchor itself to any object and even the walls or background of the map. The end of the line follows your cursor and shows either the size, or distance. Or perhaps even both. Upon releasing the mouse button, the measuring line disappears.

It will be helpful for contraptions where exact gap and size matters ( ͡° ͜ʖ ͡°). Alongside this, can help machines such as the winch have an exact value of distance within one go, and without having to guess through trial and error.

**Comment by DindinYT37** [comment]
Please use the template.
