### ISSUE TITLE
Objects Stuck In Humanoids

### ISSUE THREAD

**Issue by bigcheese5000** [studio-minus/ppg-bugs-and-requests#1901]
**Describe the bug**
Whenever you try to stab an NPC with anything that is sharp and then you try take it out, it gets stuck in their body. It doesn't matter very much on what the sharp object is, such as when I put a needle into the NPC to heal it, I was not able to take it out of the NPC. This happens with knifes, crossbow bolts, everything. Even if you are paused and you try to take the weapon out, it will ping back into the NPC's body.

**Clearly describe how to reproduce the bug**
Spawn a normal NPC in, stab it with a sharp object, and try to take the weapon out.

**Mod list**
Symbiote Playground - Active
 Water Physics - Active
MURK Characters Pack - Inactive
Water Flask - Active
Object Editor - Active
Super Droids Mod - Active
Quick Right Click Options - Active
Flipping Heck - Active
Taser - Active
Secure. Contain. Protect [SCP MOD] - Active
Dream - Active
Skittle's Syringe Mod - Active
Chemical Warfare - Active
Hazmat Mod Remastered - Active
FNAF Mod - Active
Soror's NPC Pack - Active
Active Humans - Active

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.25.4 (64 bit)
 - GPU:NVIDIA GeForce GTX 970 (I'm pretty sure that's my GPU)
 - CPU: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz

**Additional notes**

**Comment by DindinYT37** [comment]
Doesn't happen for me. Only happened to me before with either modded humans or modded weapons supposed to be like this.

**Comment by bigcheese5000** [comment]
I've opened the game again and tried to recreate my own bug, but it isn't doing it now; I must've had a glitched game.
