### ISSUE TITLE
Cardiopulmonary Bypass Machine continues to provide oxygen even when turned off/broken

### ISSUE THREAD

**Issue by Frederick-7689** [studio-minus/ppg-bugs-and-requests#1904]
-Describe the bug

Simply, the Cardiopulmonary Bypass Machine, if connected to a human/gorse, will continue to provide oxygen even if it is turned off or broken.

-Clearly describe how to reproduce the bug

Kill or puncture the lungs of a human being and connect it to an off/broken Cardiopulmonary Bypass Machine.

-Mod list

All loaded mods:

	Team Wilson-People Playground 3D-2785176210 v1 for game v1.21+
		Currently inactive

	zooi-Darker blood-local v1.0 for game v1.22
		Currently inactive

	JOSIMA-Enhanced Human Sounds-2738554876 v0.1 for game v1.11+
		Currently inactive

	zooi-Buoyant-local v1.0 for game v1.22.4
		Currently inactive

	zooi-Dead No Collide-local v1.0 for game v1.20
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently ACTIVE

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently ACTIVE

	zooi-depletable engines-2463360042 v1.3 for game v1.19
		Currently inactive

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently ACTIVE
		Has been initialised

	zooi-Per Pixel Destruction-2314372940 valpha 7 for game v1.13.1
		Currently inactive

	zooi-Controllable anti-air cannon-2178648827 v1.2 for game v1.9.3
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently inactive

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently inactive

People Playground [v1.25.4] [64 bit]

System info:

OS: Windows 10 (10.0.22000) 64bit
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU: NVIDIA GeForce RTX 2060
Memory: 16 GB

-Additional note

https://user-images.githubusercontent.com/102178009/182035997-8d592486-bd5e-4bb8-9455-a63a0c77ca6f.mp4

https://user-images.githubusercontent.com/102178009/182036049-d8a430ec-20e0-4d3b-adc4-4e2eb98d19be.mp4

**Comment by DindinYT37** [comment]
Why was this bumped?

**Comment by Frederick-7689** [comment]
My error

**Comment by mestiez** [comment]
Fixed :)
