### ISSUE TITLE
Damage on fall into water

### ISSUE THREAD

**Issue by K-odoato** [studio-minus/ppg-bugs-and-requests#192]
**Feature description**
this mechanic will make it so humans take other damages and/or side effects from falling into water from great heights. could be editable in Environment tab.

**Feature purpose**
not much of a purpose, only for some fun and realism.

**Comment by UniDuki** [comment]
They already do though...?

**Comment by K-odoato** [comment]
> They already do though...?

only lose consciousness, im thinking shock or bruises or something

**Comment by UniDuki** [comment]
Definitely a lot worse than just losing consciousness
![image](https://user-images.githubusercontent.com/69184577/132682172-ffa572e2-a1ad-4b0a-b58b-ec3bd2004fbe.png)

**Comment by K-odoato** [comment]
> Definitely a lot worse than just losing consciousness
> ![image](https://user-images.githubusercontent.com/69184577/132682172-ffa572e2-a1ad-4b0a-b58b-ec3bd2004fbe.png)

doesnt do that for me. im also sure im up to date on version.

**Comment by JohnVcav** [comment]
you sure you dropped him fast/high enough? this always happens to me

**Comment by K-odoato** [comment]
> you sure you dropped him fast/high enough? this always happens to me

yea. maybe im just having a bug- ima close this since it seems like its doing something for everyone else
