### ISSUE TITLE
make humans cry

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1925]
**Feature description**
when humans feel a lot of pain they will start crying water particles

**Feature purpose**
more realism, if your spine was crushed you'd probably cry too

**Additional context**
most likely will never happen, but it's still worth asking for

**Comment by Drogo-man** [comment]
Hmmmm

**Comment by PossiblyRemember** [comment]
there's mods for this too y'know

**Comment by DindinYT37** [comment]
This sounds very much like a job for a mod.

**Comment by 69XAnonymousX69** [comment]
> This sounds very much like a job for a mod.

I last checked this board a month ago and you're still here commenting on everything, are you good

**Comment by ATPGaming** [comment]
> > This sounds very much like a job for a mod.
> 
> I last checked this board a month ago and you're still here commenting on everything, are you good

he needs to get a life

**Comment by PossiblyRemember** [comment]
> > > This sounds very much like a job for a mod.
> > 
> > 
> > I last checked this board a month ago and you're still here commenting on everything, are you good
> 
> he needs to get a life

he uses it to help zooi, more than a lot of you are doing, can't you keep your mouth shut?

**Comment by BBQGiraffe** [comment]
pretty sure it's cooler that they don't have mouths, I Have No Mouth and I Must Scream type scenario
