### ISSUE TITLE
Mouths 

### ISSUE THREAD

**Issue by DieFluoro** [studio-minus/ppg-bugs-and-requests#1928]
**Feature description**
I'm not sure if the whole brainless ragdoll aesthetic is necessary for the hinted lore but I think it would be satisfying to have screaming and groaning as an optional mechanic in the settings. Maybe give them mouths too. My idea is like if they get shot or stabbed they start groaning and it slowly stops as adrenaline rises, if they're burning they scream, if they're hit with a blunt object they grunt, if they're shot in the head there is a chance for them to groan as they fall over, if they're injured and profusely bleeding they're loudly grunting as if they're wincing in pain. A stab or gunshot to the stomach or upper torso could produce a gargling sound as if their lungs are filling with blood. This could apply to gorses too, the gorse as a platform for creature ideation is pretty versatile, I can see the gorse having a high pitch xenomorphic sound or a low pitch guttural mucous like sound.

**Feature purpose**
I request this purely because after 200 hours in the game and making every machine you can, I'm back to square one where I'm just using the weapons on the people. It was a little unsatisfying to flamethrower a person and see them convulse in agony without screaming. I see that they don't have mouths but I just think if it were an optional feature it would be quite entertaining

**Additional context**
No additional context I've stated my piece

**Comment by Drogo-man** [comment]
🤨

**Comment by DindinYT37** [comment]
Related to #1232 

Also, the humans have brain it's just that it's not really worth the time and effort to give them proper AI considering it would need to be compatible with mods.

**Comment by DindinYT37** [comment]
Oh btw, there's a mod for screaming.

**Comment by BBQGiraffe** [comment]
[Scream Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2494555615)
I helped make it!
