### ISSUE TITLE
morning star (weapon)

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#1933]
**Feature description**
add a medieval morning star as a new weapon. it would be a heavy, spiked metal ball on a stick

**Feature purpose**
I feel like it could add a lot to the game because we don't really have a heavy, spiked melee weapon. this might not be easy to code, but, the handle could be a different material than the ball, like rubber maybe.

**Additional context**
![image](https://user-images.githubusercontent.com/109692890/182952972-263066bb-a779-4aa8-843e-4feca3cbf742.png)

**Comment by DindinYT37** [comment]
Mod moment...

**Comment by PossiblyRemember** [comment]
ok _before you request_, actually _check_ if it's already been requested mate

**Comment by DindinYT37** [comment]
Duplicate of #1697

**Comment by ATPGaming** [comment]
ok, whatever, im an idiot. im just not gonna suggest anymore and get off this toxic place, FOREVER this time

**Comment by DindinYT37** [comment]
@PossiblyRemember do something, you said you're his father.

**Comment by PossiblyRemember** [comment]
> ok, whatever, im an idiot. im just not gonna suggest anymore and get off this toxic place, FOREVER this time

hey, NOT what I said, you aren't an idiot, and I know you wanna request for one of your games, but there are rules we have to follow, and we should be able to follow them or at least check for these things ourselves

**Comment by DindinYT37** [comment]
> ok, whatever, im an idiot. im just not gonna suggest anymore and get off this toxic place, FOREVER this time

Not really toxic, it's just that you keep repeating the same mistakes over and over again. It may seem like it's toxic since you always get criticism and never praise or something like that, but you have to understand that while you naturally get criticism for doing something wrong, you also won't get praise for the standard.

*Also, if we're being real here, you're probably gonna post another suggestion in a week or two at best.*

**Comment by ATPGaming** [comment]
> > ok, whatever, im an idiot. im just not gonna suggest anymore and get off this toxic place, FOREVER this time
> 
> Not really toxic, it's just that you keep repeating the same mistakes over and over again. It may seem like it's toxic since you always get criticism and never praise or something like that, but you have to understand that while you naturally get criticism for doing something wrong, you won't get much praise or any at all for what's considered a standard here.
> 
> _Also, if we're being real here, you're probably gonna post another suggestion in a week or two at best._

no, I'm not. I'm never going to post another suggestion. You're never going to see me on this forum again. I'm gonna play Mutilate A Doll 2 and never even touch People Playground again. goodbye, wait no, just bye.

**Comment by PossiblyRemember** [comment]
> > > ok, whatever, im an idiot. im just not gonna suggest anymore and get off this toxic place, FOREVER this time
> > 
> > 
> > Not really toxic, it's just that you keep repeating the same mistakes over and over again. It may seem like it's toxic since you always get criticism and never praise or something like that, but you have to understand that while you naturally get criticism for doing something wrong, you won't get much praise or any at all for what's considered a standard here.
> > _Also, if we're being real here, you're probably gonna post another suggestion in a week or two at best._
> 
> no, I'm not. I'm never going to post another suggestion. You're never going to see me on this forum again. I'm gonna play Mutilate A Doll 2 and never even touch People Playground again. goodbye, wait no, just bye.

bro just ignore DindinYT, you don't even have to say anything, he only has "power" over you if you let him bro, play the game, get mods, have fun, you don't have to be offended by him, and ngl, you seem to be overreacting, just take some time to chill. Have a nice day alright?

**Comment by Drogo-man** [comment]
either it doesnt follow the template, is a duplicate, or "you can just mod it in bro".

**Comment by SirAJ4895** [comment]
> either it doesnt follow the template, is a duplicate, or "you can just mod it in bro".

The issue was resolved. Don't try to start the fire back up.
