### ISSUE TITLE
Multiplayer People Playground

### ISSUE THREAD

**Issue by Nicovw321** [studio-minus/ppg-bugs-and-requests#194]
**Feature description**
People Playground but Multiplayer! very hard to implement but i'm sure it could be the best feature the game could have (besides mods)

**Feature purpose**
You play with other people! and... that's it.

**Comment by Nicovw321** [comment]
ever since we talked about it in the ppg wiki discord, i could never stop thinking about this

**Comment by JohnVcav** [comment]
sounds really fun, but I doubt unity would like this very much

**Comment by mestiez** [comment]
This is definitely never happening

**Comment by Nicovw321** [comment]
ohk
