### ISSUE TITLE
Screen Delay Problem (No Lag)

### ISSUE THREAD

**Issue by Mtraus** [studio-minus/ppg-bugs-and-requests#1940]
There's a problem with the game for me. For some reason when I hover/interact/spawn something, there's a 2-second delay for everything. And no, I'm not lagging. my fps is around 100, but trying to interact with something would just delay. Is there a way that I can get past this? Because I made sure that my settings were the lowest settings possible, but uh, I just don't know what would fix the issue. I also tried to uninstall and reinstall the game, but it's still pretty much the same before I uninstalled it. Please find a way to fix this, or tell me why it's happening to me. Thank you.

**Mod List:** 
[People Holding Guns](https://steamcommunity.com/sharedfiles/filedetails/?id=2389320926)
[Ultimate Melee Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2844501696)
[The Backmaps Mod
](https://steamcommunity.com/sharedfiles/filedetails/?id=2832891109)
[E - Bank](https://steamcommunity.com/sharedfiles/filedetails/?id=2645007376)
[The Grappling Gun Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2637017257)
[Skyscraper With Realistic Destruction v7](https://steamcommunity.com/sharedfiles/filedetails/?id=2402531958)
[Status Icons (Fixed)](https://steamcommunity.com/sharedfiles/filedetails/?id=2644689646)
[Operation LSA Forces: MARSOC](https://steamcommunity.com/sharedfiles/filedetails/?id=2824743154)
[Destructible Residential Building
](https://steamcommunity.com/sharedfiles/filedetails/?id=2822542673)
[Secret bunker](https://steamcommunity.com/sharedfiles/filedetails/?id=2816395893)
[The Hospital
](https://steamcommunity.com/sharedfiles/filedetails/?id=2834065216)
[The Ultimate Car Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2795171453)
[Functioning Armor](https://steamcommunity.com/sharedfiles/filedetails/?id=2194511729)
[Magdump Mayhem](https://steamcommunity.com/sharedfiles/filedetails/?id=2799945427)
[Mountain Structure
](https://steamcommunity.com/sharedfiles/filedetails/?id=2812988296)
[Quick Right Click Options](https://steamcommunity.com/sharedfiles/filedetails/?id=2516131949)
[Powers Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2276255188)
[Water Physics](https://steamcommunity.com/sharedfiles/filedetails/?id=2793815479)
[Dynamic Human Emotions
](https://steamcommunity.com/sharedfiles/filedetails/?id=2745225441)
[Explomod](https://steamcommunity.com/sharedfiles/filedetails/?id=2337158074)
[Animated Weapons+
](https://steamcommunity.com/sharedfiles/filedetails/?id=2503670951)
[flipping heck](https://steamcommunity.com/sharedfiles/filedetails/?id=2448120172)
[Scream mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2494555615)
[Functional Helicopter Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2839691188)
[More Vehicles](https://steamcommunity.com/sharedfiles/filedetails/?id=2805966221)

**System Information:**

Operating System: Linux

Game Version: 1.25

GPU: Nvidia Geforce GT 730

CPU: Intel Core i7-12700

Extra Notes: 
The sound inside the game isn't delayed.

**Comment by PossiblyRemember** [comment]
Could ya use the template?
Template:
**Describe the bug**

**Clearly describe how to reproduce the bug**

**Mod list**

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**

**Comment by Mtraus** [comment]
Alright. I'll try fixing it up.

**Comment by PossiblyRemember** [comment]
Wow, ok that's probably a bit more than you needed to put effort into, I mean I'm glad you put links and all but WOW, talk about determination.

**Comment by DindinYT37** [comment]
Aren't some of those contraptions, though?

**Comment by Mtraus** [comment]
> Wow, ok that's probably a bit more than you needed to put effort into, I mean I'm glad you put links and all but WOW, talk about determination. Also why was this closed?

Sorry, I'm kinda new to Github.

**Comment by Mtraus** [comment]
> Aren't some of those contraptions, though?

Yeah. I just decided to add every mod I've implemented into People Playground. Don't really know why.

**Comment by PossiblyRemember** [comment]
> > Wow, ok that's probably a bit more than you needed to put effort into, I mean I'm glad you put links and all but WOW, talk about determination. Also why was this closed?
> 
> Sorry, I'm kinda new to Github. 
> 
> 

It's fine, I was the same way when I came here

> > Aren't some of those contraptions, though?
> 
> Yeah. I just decided to add every mod I've implemented into People Playground. Don't really know why.

probably helpful for zooi though

**Comment by Mtraus** [comment]
Alright, after a while of digging, **I figured out the problem.** 
so, **the main problem is that I was using 2 monitors at once**, and **I've noticed that using those two monitors cause that questionable delay.** And when **I unplugged one of my monitors, I reopened the game, and surprisingly the game was working without any visual delays.** I don't know if its only a problem that'll happen on some type of pc's, but thats how i managed to fix the issue.
_And yes, its going to be a little nerve-racking when you have to unplug a monitor in order to play a game that you solely like and all, haha_
