### ISSUE TITLE
Liquid dispenser is completely broken with blood tank 

### ISSUE THREAD

**Issue by TinFoil77** [studio-minus/ppg-bugs-and-requests#1941]
**Describe the bug**
Whenever i hook up a liquid dispenser with a blood tank and a syringe(syringe sucks the blood, it goes to the blood tank then gets dispensed with the dispenser) it deletes the liquid inside of the blood tank.

**Clearly describe how to reproduce the bug**
Hook up an empty syringe to the blood tank(syringe is on idle) then connect a liquid dispenser to the tank, AKA the shower head, make sure the blood tank is on idle, stab a human with the syringe to take blood, the blood gets deleted inside the blood tank.

**Mod list**
I tried not using mods for this and it still is broken, mods dont affect the bug.

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.25
 - GPU: i have no idea, wont let me view in system settings
 - CPU: i have no idea, wont let me view in system settings

**Additional notes**
I guess the bug started when 1.25 came out, i just noticed it.

**Comment by mestiez** [comment]
Fixed. The liquid wire code is actually incredible. I can't believe I wrote that shit, it's like I'm trying to decipher some unknown language.

**Comment by PossiblyRemember** [comment]
> Fixed. The liquid wire code is actually incredible. I can't believe I wrote that shit, it's like I'm trying to decipher some unknown language.

is the language by any chance Dutch? ig I could say the same for English too though.
