### ISSUE TITLE
"Heart stopped" Issue

### ISSUE THREAD

**Issue by TheNoodle76** [studio-minus/ppg-bugs-and-requests#1944]
**Describe the bug**
If you minorly injure a human their heart will stop, and its really annoying

**Clearly describe how to reproduce the bug**
Mildly inconvenience the human, their heart will stop for no reason

**Mod list**
Its just the base game

**System info (please complete the following information)**
 - Operating system: Windows
 - Game version: latest
 - GPU: GTX 1660
 - CPU: 17 9700k

**Additional notes**
Maybe make them less fragile, its unrealistic for the heart to completely stop with no chance of starting again after getting hit in the head

**Comment by DindinYT37** [comment]
Defibrillator?

**Comment by mestiez** [comment]
I can only explain this by imagining the environment the humans are in is quite cold and smaller humans (less heat capacity) suffer from hypothermia. This system has seen some major changes in the upcoming update so I think this isn't an issue anymore. At least, I can't reproduce it in my current build.
