### ISSUE TITLE
Game starts out of focus which breaks input for some reason [Linux]

### ISSUE THREAD

**Issue by Capybaron** [studio-minus/ppg-bugs-and-requests#1946]
**Describe the bug**
Whenever I start the game from Steam, it starts out of focus. When I regain focus, I cannot click on anything. Steam overlay works

**Clearly describe how to reproduce the bug**
1) Start the game
2) Wait
3) Open the PPG tab
4) Input broken

**Mod list**
No mods

**System info (please complete the following information)**
 - Operating system: Ubuntu 22.04.1 (LTS)
 - Game version: latest beta no idea what version that is (release does this aswell)
 - GPU: Nvidia GeForce 1050Ti
 - CPU: Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz

**Additional notes**
i'm using the latest steam proton (not experimental)

**Comment by mestiez** [comment]
I'm on manjaro 21.3.6 using Proton 7.1 and everything seems to work fine. I tried fullscreen, windowed, borderless, proton experimental, disabling steam overlay, but I can't reproduce what you're experiencing. Is there anything else that could cause this problem?

**Comment by Capybaron** [comment]
> I'm on manjaro 21.3.6 using Proton 7.1 and everything seems to work fine. I tried fullscreen, windowed, borderless, proton experimental, disabling steam overlay, but I can't reproduce what you're experiencing. Is there anything else that could cause this problem?

I found out it's an issue with the 32 bit libraries. Reinstalling them helped. This can be closed now
