### ISSUE TITLE
more creatures

### ISSUE THREAD

**Issue by GrogtheGorillaFrog** [studio-minus/ppg-bugs-and-requests#195]
Well the life section is really lacking and needs more creatures aliens and maybe different types of humans. like another species entirely more than one additional species and also maybe some different roles for that species to give its some more character 

The purpose is for me to have more stuff to kill its getting boring killing the same thing, of course you can download mods but those usually are just remodeled humans i want more than that.

more stuff the funner it gets, oh and also maybe some more mechanism to play with to make for customizable machines like having to make an engine for a car instead of just making the wheels turn that'd be fun.

**Comment by mestiez** [comment]
This is not clear enough. Try to avoid words like "more" and "better", and be _very specific_  as to what you are requesting.

**Comment by GrogtheGorillaFrog** [comment]
that is as specific as i want it i just want you to add more species i want
it to be a surprise as to what species and other stuff you add
