### ISSUE TITLE
Rubber conducts electricity

### ISSUE THREAD

**Issue by Chagarock** [studio-minus/ppg-bugs-and-requests#1952]
**The bug**
In real life rubber can't conduct electricity (https://en.wiktionary.org/wiki/rubber).

**Note**
Physical properties (Rubber) - https://www.studiominus.nl/ppg-modding/snippets/physicalProperties.html

**Comment by DindinYT37** [comment]
Best you can probably do right now is adding a component to constantly set the charge in all limbs to zero...

**Comment by Chagarock** [comment]
> Best you can probably do right now is adding a component to constantly set the charge in all limbs to zero...

Good idea), but how?

**Comment by DindinYT37** [comment]
> > Best you can probably do right now is adding a component to constantly set the charge in all limbs to zero...
> 
> Good idea), but how?

What part do you not know how to do?

**Comment by Chagarock** [comment]
> 



> > > Best you can probably do right now is adding a component to constantly set the charge in all limbs to zero...
> > 
> > 
> > Good idea), but how?
> 
> What part do you not know how to do? Setting the charge or having it happen constantly?

How to make an object constantly discharge a charge of electricity

**Comment by DindinYT37** [comment]
> > 
> 
> > > > Best you can probably do right now is adding a component to constantly set the charge in all limbs to zero...
> > > 
> > > 
> > > Good idea), but how?
> > 
> > 
> > What part do you not know how to do? Setting the charge or having it happen constantly?
> 
> How to make an object constantly discharge a charge of electricity That is, what function to call, for example, to clear all human damage, you can use limb.SkinMaterialHandler.ClearAllDamage()

The only way to this is probably just iterating over all limbs, getting the PhysicalProperties and setting charge to zero.

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/184494433-547ae9e7-734e-4760-93af-18b878348cb7.png)
No it doesn't?

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/184494455-375583bb-cb43-4d50-b6c3-c40d101d6ba7.png)
It does if you put cables but that's the point of cables. I can change this but it would probably destroy every contraption and be pretty confusing.

**Comment by DindinYT37** [comment]
I also like how the topic of this issue was almost entirely changed after my conversation with him...

**Comment by mestiez** [comment]
wrong label

**Comment by mestiez** [comment]
who care
