### ISSUE TITLE
Hit box of the human head is broken when its resized

### ISSUE THREAD

**Issue by sleepyham** [studio-minus/ppg-bugs-and-requests#1956]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**

**Comment by DindinYT37** [comment]
Duplicate of #1328

**Comment by DindinYT37** [comment]
Also, how about actually telling us about the bug next time?

**Comment by PossiblyRemember** [comment]
hopefully _this one_ gets noticed

**Comment by mestiez** [comment]
Ill explain
