### ISSUE TITLE
RPM Laser Measuring Device.

### ISSUE THREAD

**Issue by Skell3to** [studio-minus/ppg-bugs-and-requests#1958]
**Feature description**

It would basically work as a spawnable item In the Machinery Section, it would work similarly to the Infrared Thermometer, but instead of temperature, it would show rotations per minute of the object.. Either by placing a copper wire on the rotating object and every time the laser would detect the copper wire on the object it would by the size of the rotating object and speed that it takes for the copper wire to send a signal back it would output a RPM or RPS Number.

**Feature purpose**

It would be useful for measuring the rotations of a wheel, object, or rotating engine part in a contraption.

**Comment by DindinYT37** [comment]
The Copper wire is just a normal wire but destructible, though I don't really get how this would benefit users it's one of the best requests there was on here in a while.

**Comment by Skell3to** [comment]
> The Copper wire is just a normal wire but destructible, though I don't really get how this would benefit users it's one of the best requests there was on here in a while.

I didn't really have any better idea about the copper wire, cause RPM measurers work that you put something clear like a black tape (on a white object) over the spinning object and the RPM Laser Measurer measurers how fast the object spins by counting rotations by the laser detecting the tape everytime it passes. So I Included it just in case.

**Comment by Skell3to** [comment]
> The Copper wire is just a normal wire but destructible, though I don't really get how this would benefit users it's one of the best requests there was on here in a while.

Forgot to include.. It wouldn't really be a actual benefit, more of a Machinery addition. Would be useful for seeing how different gear ratios work under pressure.. How much power from a generator gives the best stable RPM and so on..

**Comment by DindinYT37** [comment]
> I didn't really have any better idea about the copper wire, cause RPM measurers work that you put something clear like a black tape (on a white object) over the spinning object and the RPM Laser Measurer measurers how fast the object spins by counting rotations by the laser detecting the tape everytime it passes. So I Included it just in case.

Alright, though I'd say, it's probably fine without the tape or whatever since this People Playground doesn't need to be *that* realistic with things like that.

**Comment by Skell3to** [comment]
> > I didn't really have any better idea about the copper wire, cause RPM measurers work that you put something clear like a black tape (on a white object) over the spinning object and the RPM Laser Measurer measurers how fast the object spins by counting rotations by the laser detecting the tape everytime it passes. So I Included it just in case.
> 
> Alright, though I'd say, it's probably fine without the tape or whatever since this People Playground doesn't need to be _that_ realistic with things like that.

Yeah you're right, I'm just clueless when it comes to coding, I included it if something like that would be needed to make it work. code-wise

**Comment by DindinYT37** [comment]
> Yeah you're right, I'm just clueless when it comes to coding, I included it if something like that would be needed to make it work. code-wise

Well I mean, the infrared-thermometer also doesn't work with some tape or whatever, does it? It just reads the temperature as a property from the detected object, and angular velocity is also just a property - the only thing that'd actually be "complicated" with that is converting it from whatever the angular velocity is measured in to rpm.

**Comment by Skell3to** [comment]
> > Yeah you're right, I'm just clueless when it comes to coding, I included it if something like that would be needed to make it work. code-wise
> 
> Well I mean, the infrared-thermometer also doesn't work with some tape or whatever, does it? It just reads the temperature as a property from the detected object, and angular velocity is also just a property - the only thing that'd actually be "complicated" with that is converting it from whatever the angular velocity is measured in to rpm (who knows, it might also already be in rpm).

I see, alright thanks for making it more clear for me.

**Comment by mestiez** [comment]
A device that emits a beam and just shows the RPM of the object at the endpoint of the beam is a bit too specific for my tastes. Something like this would be much more suitable in a mod.
