### ISSUE TITLE
My friend saved a build that took 2 hours, saved it, deleted his build and then it said it was corrupted.

### ISSUE THREAD

**Issue by bob448** [studio-minus/ppg-bugs-and-requests#196]
**Describe the bug**
My friend saved a build that took 2 hours, saved it, deleted his build and then it said it was corrupted.

**Clearly describe how to reproduce the bug**
I don't know.
It had modded humans. The build had modded humans in the save.

**Additional notes**

**Comment by UniDuki** [comment]
What was the mod that your friend used? I have tried saving at least 30 different modded humans and items and all of them are fine. The mod your friend was using must've been broken in some way.

**Comment by bob448** [comment]
I don't know what happened, but it works now.
