### ISSUE TITLE
All controls are gone

### ISSUE THREAD

**Issue by Blueloft** [studio-minus/ppg-bugs-and-requests#197]
I have played this game for many hours and suddenly all controls were gone. I was able to zoom in and out with my mouse and that was it.  in the controls panel the only option is for dragging key. if I try to rebind it to my keyboard the key works but there are no other controls.

**Comment by UniDuki** [comment]
Did you download any mods right before this happened?

**Comment by mestiez** [comment]
this is very unclear. to fix the issue, just delete teh controlscheme.json file in the game directory. 
closing until at least the information requested in the bug report template is present.
