### ISSUE TITLE
Cameras

### ISSUE THREAD

**Issue by SkyHighPurchase** [studio-minus/ppg-bugs-and-requests#1994]
**Feature Description**
I had an idea a bit ago while brainstorming some sort of laser guided contraption. Cameras! My idea was that there would be a camera prop, with a few context menu options:
> Display Screen
> Detect Lasers On/Off
> Detect Heat On/Off

My thought for the "Display Screen" is that it would put up a UI screen on the player's monitor that would show a 3-5 meter area around the camera that the player could always see, even when not near the camera so they could watch what the camera could see. For the "Detect Heat" and "Detect Laser" the camera would try and rotate itself (and the contraption it's wired to) towards whatever it wants to detect. I.e the end point of a laser, or the hottest object it can see.

**Feature Purpose**
I figured it would be nice to have something that would make laser guided missiles (or anything else) a lot easier to make. And why not give it some interesting and unique features while at it?

**Comment by PossiblyRemember** [comment]
seems like a nice idea, I would say that this has been requested before but this seems much more in detail, hopefully this gets accepted, I can see quite a few uses for this

**Comment by SkyHighPurchase** [comment]
It seems I missed the chance to add the feature request tag. Not sure how to do it now, I'm not very adept in the ways of GitHub.

**Comment by SkyHighPurchase** [comment]
This is an absolute mess lmao. I made a new one with the proper tag. Let's hope this old one gets ignored or deleted.

**Comment by PossiblyRemember** [comment]
well at least you used the template without anyone telling you too, that's more than I could say for most people here lmao
