### ISSUE TITLE
Reload Mod option in the mods tab

### ISSUE THREAD

**Issue by Reycko** [studio-minus/ppg-bugs-and-requests#1998]
**Feature description**
I think a "Reload" button could be useful, that way people don't have to restart their game each time a new workshop item has been installed and/or local mods being updated.
You can already recompile mods with errors so why not make it available even where there isn't any errors ?

**Feature purpose**
I'm currently trying to mod PPG and having to restart every code change is a bit annoying and takes a bit of time.
This can be used to help modders (and people in general) reloading a mod instead of restarting the whole game.

**Additional context**
Concept image:
![ppg-reload-concept](https://user-images.githubusercontent.com/78082869/185802605-950e5091-f0ea-43a9-9e94-630ea5fc7d5f.png)
(I did my best to replicate the font but i'm not really good at doing this kind of things)

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #589
* #605 
* #694
* #1072 
* #1173 
* #1192 
* #1794 
* #1957

*Note that basically what you requested here was rejected several times before, so this will probably also be rejected.*

**Comment by Reycko** [comment]
Alright.
