### ISSUE TITLE
Foot hitbox too big

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#200]
**Describe the bug**
The hitbox for the foot is bigger than the foot

**Clearly describe how to reproduce the bug**
Spawn a human
Detach a foot
Put the foot so the toes are facing upwards
You will see it floating

**Additional notes**
Real size
![image](https://user-images.githubusercontent.com/69184577/132955779-7bcdbd0a-95a5-4a61-9ea1-f9d4ebeabba8.png)

**Comment by TamasB14** [comment]
I'm sure it's because of balancing purposes. Poor human would fall backward.

**Comment by UniDuki** [comment]
> I'm sure it's because of balancing purposes. Poor human would fall backward. 

Definitely not, humans actually walk better without their feet.

**Comment by mestiez** [comment]
> I'm sure it's because of balancing purposes. Poor human would fall backward.

This is correct. This is by design.
