### ISSUE TITLE
Attractor machine

### ISSUE THREAD

**Issue by kopygoter** [studio-minus/ppg-bugs-and-requests#2006]
**Feature description**
Well it works like a magnet, but it pulls EVERYTHING! *incredible* I know. Or, you could just add it as an option to the already existing magnet. That would also be nice...
**Feature purpose**
0 gravity ships, planets, ect. would just be really useful in general, also for slowly pulling apart people :)

**Additional context**
nope 👍

**Comment by kopygoter** [comment]
I kid you not there is not a single mod that does this, and trust me. I WOULD KNOW.

**Comment by username90001** [comment]
> **Feature description** Well it works like a magnet, but it pulls EVERYTHING! _incredible_ I know. Or, you could just add it as an option to the already existing magnet. That would also be nice... **Feature purpose** 0 gravity ships, planets, ect. would just be really useful in general, also for slowly pulling apart people :)
> 
> **Additional context** nope 👍

there is way to create gforce or some sort of it 
1 and hardest centrifuge it works fine excluding it breaks due to strange physic when something strange happens
2 fan which can create some sort of gforce and u can even use fan to make humans survive extreme gforce even sun gravity
