### ISSUE TITLE
Disco floor

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2007]
**Feature description**
You know the funny surfaces on dance clubs? This is basically that. It's a resize adjustable disco floor that makes funky RGB gamer lights when activated

**Feature purpose**
Useful for nightclub scenes or when you want to slap a rainbow lighting stick on something

**Additional context**
![DISCOOO!!!!!!!!!1](https://user-images.githubusercontent.com/104321411/186431249-a8134335-3ee9-40e8-8fab-08b71d4dec84.png)

**Comment by TheBeeThat** [comment]
you can make one yourself

**Comment by DindinYT37** [comment]
Also, how exactly would this work in a 2d environment?

**Comment by bibbybabby** [comment]
> you can make one yourself

Yea but every lamp will have to be a color that constantly changes, and no timers that *DING* constantly

**Comment by DindinYT37** [comment]
Sounds very much like a modded thing in my opinion.
