### ISSUE TITLE
controllable  humans 

### ISSUE THREAD

**Issue by mingomango1234** [studio-minus/ppg-bugs-and-requests#2013]
description 
new mechanic that lets you control humans also lets you make them fight each other/other things 

purpose 
the purpose is to make humans more interactive and make them feel like a living entity 
also to let you tell a story with epic fights between nations 

additional context 
be able to give humans enemy's or make them a part of a team also let you control them like in tabs

**Comment by DindinYT37** [comment]
Basically duplicate of #1495
