### ISSUE TITLE
Flamethrower doesn't burn stuff if up close

### ISSUE THREAD

**Issue by urrone** [studio-minus/ppg-bugs-and-requests#2014]
No mods were active.

The flamethrower simply doesn't burn anything if you aim it too close to the target.

![2022-08-27_00-29-09_](https://user-images.githubusercontent.com/102984195/187000673-a17d7fc3-0264-4a81-befb-c44b4eceaf2a.gif)

This one had mods, but the point above still stands.
![2022-08-27_21-24-23_AdobeExpress_AdobeExpress](https://user-images.githubusercontent.com/102984195/187045504-ff629003-dcd3-42aa-a3b9-10fe1193b13e.gif)

**Comment by mestiez** [comment]
fixed :)
