### ISSUE TITLE
items spawning upside down and humans not standing properly?

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2017]
**Describe the bug**
after i activated alot of nukes, items spawns upside down and humans cannot stand properly (look in video)

**Clearly describe how to reproduce the bug**
i just activated alot of nukes then this happened

**Mod list**
Dyadyushka Dyadya-Colorful Displays-2853060790 v1.0 for game v1.24+
		Currently ACTIVE

	TitaniumSpyBorgBear-Breakable Invisible Pin Tool-2673140481 v1.0 for game v1.22.2+
		Currently ACTIVE

	Laska, Quickness-Quick Turn On Poses-local v1.0 for game v1.24
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-People Playground Discord Stats-2846890700 v1.0 for game v1.24+
		Currently ACTIVE
		Has been initialised

	Mishanya-Functional Helicopter Mod-local v0.3 for game v1.25+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Category Switcher-2836149699 v1.0 for game v1.24+
		Currently ACTIVE

	Dyadyushka Dyadya-Colorful Energy Sword-local v1.0 for game v1.24+
		Currently ACTIVE

	Dyadyushka Dyadya-Colorful Blaster-local v1.0 for game v1.24+
		Currently ACTIVE

	Puce-Display machinery attributes-2819846862 v1.0 for game v1.24.6
		Currently ACTIVE

	Joe Mama-Better Call Saul Radio-local v1.0 for game v1.11
		Currently inactive

	Mishanya-The Ultimate Car Mod-2795171453 v0.9 for game v1.16+
		Currently ACTIVE

	hankmart-Anti Rot-local v1.0 for game v1.21+
		Currently ACTIVE

	cloddyclod / aylse-cloddyMod-2794902095 vi never update modversion for game v1.21
		Currently ACTIVE
		Has been initialised

	Frosty-Accurate Resize & Position-2789547018 v1.0 for game v1.23
		Currently ACTIVE

	hankmart-Identical Humans-2788201842 v2.5 for game v1.21+
		Currently ACTIVE

	Aspa102-Favourites Category-2781168915 v1.0 for game v1.23+
		Currently ACTIVE

	Punkkinn-Functional Androids!-2757661232 v1.0 for game v1.22
		Currently ACTIVE

	Quickness-Interphase Human-local v1.1 for game v1.22
		Currently ACTIVE

	Mishanya-Prop Mod-2696169016 v1.3 for game v1.22+
		Currently ACTIVE

	Maui bread-Invisible human-local v1.0 for game v1.15
		Currently ACTIVE

	Mishanya-Functional Devices Mod-2605252227 v1.1 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	Morzzic-Object Editor-2590195142 v1.3.1 for game v1.23+
		Currently ACTIVE

	Aspa102-OCM (By subscribing you accept that the mod is broken and you shouldn't even have it)-2585230438 v2.0 for game v1.21
		Currently ACTIVE
		Has been initialised

	Me again-Androids Mod-local v1.0 for game v1.15
		Currently ACTIVE

	Mishanya-The Ultimate Human Mod-2516637907 v1.1 for game v1.21+
		Currently ACTIVE

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently ACTIVE

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently ACTIVE

	Pumpkin-Quality of Life Items-2500516293 v1.7 for game v1.22.3
		Currently ACTIVE

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently ACTIVE
		Has been initialised

	2factory-Human-like Android-2396107312 v1.0 for game v1.14
		Currently ACTIVE

	jimmyl-Android Injectors-2381177128 v1.4 for game v1.12+
		Currently ACTIVE

	Morzzic-Photo Mode-2263832258 v1.0 for game v1.8+	
		Currently ACTIVE

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently ACTIVE

	Teletubbie With A Shotgun-PPG Spy Mod-local v1.0.5 for game v1.9+
		Currently inactive

	royalealbert27-A pistol that shoots everytime it hits the ground for some reason-2785373496 v1.0 for game v1.21+
		Currently inactive

	royalealbert27-Albert's Random Maps-2774819209 v1 for game v1.22.3
		Currently inactive

	royalealbert27-Albert's Random Maps 2: Hallway-local v1.0 for game v1.14+
		Currently inactive

	royalealbert27-Albert's Random Maps: Hallway-local v1.0 for game v1.14+
		Currently inactive

	royalealbert27-Albert's Stupid Mod-2793141178 v1.0 for game v1.23+
		Currently inactive

	royalealbert27-Amogus Map Mod-2821280027 v1.0 for game v1.14+
		Currently inactive

	royalealbert27-Among Drip Radio 2.0-2797528802 v2.0 for game v1.23+
		Currently inactive

	nitroglycerin-Android disguised as Human-2852900609 v1.0 for game v1.25+
		Currently ACTIVE

	royalealbert27-Android with Randomized Height-2793555514 v1.0 for game v1.21+
		Currently inactive

	royalealbert27-Anti-Slebbey Mod-local v1.0 for game v1.25+
		Currently inactive

	Puppyguard, Fixed by royalealbert27-AutoAim 1.23 Fix-2786293063 v1.0 for game v1.19.2+
		Currently ACTIVE

	royalealbert27-Blebbey's Youtube Mod-local v1.0 for game v1.25+
		Currently inactive

	royalealbert27-Changeable Android Size-2793564550 v2.0 for game v1.21+
		Currently inactive

	royalealbert27-Colorable Block-2780318191 v1.0 for game v1.23+
		Currently inactive

	royalealbert27-Disable Industrial Generator Shake-2785892544 v1.0 for game v1.21+
		Currently inactive

	royalealbert27-Disable Liquid Pressuriser Vibrate-2793548212 v1.0 for game v1.19+
		Currently inactive

	Aubarino-Functional Terminator Mod-2809137426 v1.5 for game v1.20+
		Currently inactive

	royalealbert27-Green and Blue Buttons-2794106694 v1.0 for game v1.21+
		Currently inactive

	royalealbert27-Green Screen Map-local v1.0 for game v1.14+
		Currently inactive

	royalealbert27-Human with Changeable Feelings-2776960901 v1.0 for game v1.22+
		Currently inactive

	royalealbert27-Instant Firework-2797973353 v1.0 for game v1.23+
		Currently inactive

	DominianekOfficial-JellyMOD-local v1.0 for game v1.22+
		Currently inactive

	royalealbert27-Milk Bottle Mod-2797553232 v1.0 for game v1.23+
		Currently inactive

	royalealbert27-Neco Arc Nextbot-2838632675 v1.0 for game v1.20+
		Currently inactive

	royalealbert27-Ocean Map-2821293731 v1.0 for game v1.14+
		Currently inactive

	royalealbert27-Powerful Crates Mod-local v1.0 for game v1.24+
		Currently inactive

	nitroglycerin-Resizable Housing Bottom Layer-2783854857 v1.0 for game v1.23+
		Currently inactive

	royalealbert27-Roblox Camping Mod-local v1.0 for game v1.25+
		Currently inactive

	royalealbert27-Spawnable Vent Cover-2781886603 v1.0 for game v1.23+
		Currently inactive

	royalealbert27-The Son from Camping-2789679663 v1.0 for game v1.22+
		Currently inactive

	royalealbert27-TheBlox27 Mod-2783361345 v1.0 for game v1.21+
		Currently inactive

	royalealbert27-Uncharted Territory Bomb-local v1.0 for game v1.21+
		Currently inactive

**System info (please complete the following information)**
 - Operating system: Windows 10  (10.0.19044) 64bit
 - Game version: 1.25.4
 - GPU: NVIDIA GeForce GTX 1050 Ti
 - CPU: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz

**Additional notes**
this got fixed after i restart the map

THE VIDEO: https://streamable.com/buc5lp

**Comment by mestiez** [comment]
does it still happen when you disable all mods?

**Comment by mestiez** [comment]
??????????? ok
