### ISSUE TITLE
My Contraptions lags me and i dont know why.

### ISSUE THREAD

**Issue by alolfg5435** [studio-minus/ppg-bugs-and-requests#2018]
so when i create a contraption it instantly drops on 33 fps (for example my bmp-2d)  but if i load another person tank its 77 fps. you cant it only happens for me
**Mod list**
ItemPlus
 - Operating system: Windows 10
 - Game version:1.25.4 (64 BIT)
 - GPU: GTX 1650
 - CPU: RYZEN 4600H 5 SERIES
**Additional notes**
i dont fucking know why.....

**Comment by mestiez** [comment]
yeah can you send the contraption at least

**Comment by mestiez** [comment]
guess not lmao
