### ISSUE TITLE
empty (filled) syringe doesn't work at transferring substances with blood vessels

### ISSUE THREAD

**Issue by RedMoonw** [studio-minus/ppg-bugs-and-requests#2028]
**empty (filled) syringe doesn't work at transferring substances with blood vessels**
When I spawn an empty syringe and then fill it with any kind of substance: So it refuses to be able to inject or transfer that same substance with the blood vessels, be it to a person or a flask.
The exception is only for the Blood tank which has a self-intake mode for "drain" and "pull". I've in all matter of ways tried using the "liquid pressurised" to make it work but to no avail but since it is an external force, it doesn't seem to work like the Blood tank and its self-intake.
P.S when I say something doesn't work with the "empty (filled) syringe" I know it does indeed work with the syringe you normally spawn in, (the only difference should be that the normal one shouldn't deplete itself).

**Clearly describe how to reproduce the bug**
I can't really specify why it doesn't work but I can see some sort of difference in when it should work:
The exception is only for the Blood tank which has a self-intake mode for "drain" and "pull". I've in all matter of ways tried using the "liquid pressurised" to make it work but to no avail but since it is an external force, it doesn't seem to work like the Blood tank and its self-intake.

**Mod list**
No mods, I am only 30 hours into the game.

**System info**
 - Operating system:Windows 10
 - Game version:
 - GPU:NIVIDIA GeForce GTX 1080
 - CPU:Intel(R) Core(TM) i9-10900 CPY @ 3.70Ghz (20 CPUs), ~3.7Gz

**Additional notes**
It would be nice to know if this bug will get fixed in the foreseeable future because I am working on this machine / hospital and want to know if I have to work around it or not

**Comment by RedMoonw** [comment]
Game version: v1.25.4

**Comment by DindinYT37** [comment]
...did you set the syringe to push?

**Comment by RedMoonw** [comment]
Okey I did not know syringes also had a separate function to withhold/withdraw their content, kinda feel bad about it.
Kinda also have me confused why they come in set in two different modes... had me convinced something was wrong but I guess I am wrong...

**Comment by DindinYT37** [comment]
I suggest to close the issue now.
