### ISSUE TITLE
humans dont have enough strength to stand up

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#2031]
**Describe the bug**
humans are unable to bring themselves up when face forward on the ground 

**Clearly describe how to reproduce the bug**
set the human to flat pose then lay them on the ground and disable flat pose and more then half of the time they will just not stand up and instead shimmy their knees on the ground

**Mod list**
None
**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.26 preview 1
 - GPU: geforce gtx 1650 super
 - CPU: intel i5

**Additional notes**

**Comment by TeslaCoil9001** [comment]
We need this fixed!

**Comment by mestiez** [comment]
fixed
