### ISSUE TITLE
Change to Fire Extinguisher particles

### ISSUE THREAD

**Issue by TeslaCoil9001** [studio-minus/ppg-bugs-and-requests#2033]
**Feature description**
First of all: Thanks for adding my last suggestions mestiez!

The fire extinguisher particles should look more puffy and cloudy like real fire extinguishers.

**Feature purpose**
Realism and polish

**Additional context**
![image](https://user-images.githubusercontent.com/112362312/187805626-c3b8d13c-9a88-4df2-9c77-e927017cf276.png)

**Comment by DindinYT37** [comment]
I think this wasn't possible because of Unity's particle system but I'm not sure.

**Comment by mestiez** [comment]
Definitely possible and it should be implemented. The fire extinguisher particles have been neglected for too long

**Comment by mestiez** [comment]
https://user-images.githubusercontent.com/32131519/187976068-e5f62b4f-085f-4981-a8dd-5443e8b35341.mp4

**Comment by TeslaCoil9001** [comment]
> 2022-09-01.19-27-45.mp4

You are literally the best dev I've ever seen
