### ISSUE TITLE
FLAMETHROWER NOT FLAMING WOOD [beta]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2035]
**Describe the bug**
when i flame my cool wooden bridge in the beta, it cannot flame like it was fireproof.

**Clearly describe how to reproduce the bug**
get any wood item
get a flamethrower
flame the wood item with flamethrower

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9465853/exported.game.debug.info.md)

**Additional notes**
very bad bug

**Comment by royalealbert27** [comment]
update: it cannot flame anything burnable

**Comment by TeslaCoil9001** [comment]
When mestiez fixes one thing, he breaks another

**Comment by DindinYT37** [comment]
Likely related to #2014

**Comment by mestiez** [comment]
fixed!1
