### ISSUE TITLE
laser sentry turret graphics glitch (beta)

### ISSUE THREAD

**Issue by TeslaCoil9001** [studio-minus/ppg-bugs-and-requests#2036]
**Describe the bug**
When the laser sentry turret fires, a black box appears

**Clearly describe how to reproduce the bug**
Spawn and fire the laser sentry turret

**Mod list**
no mods

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.26 preview 2
 - GPU: idk
 - CPU: idk

**Comment by Afavertov** [comment]
Rocket and missile launcher too

**Comment by mestiez** [comment]
all these are fixed
