### ISSUE TITLE
Rain stops when hitting an object, and putting the camera under the object would change the rain noise to a quiet rumbling outside.

### ISSUE THREAD

**Issue by alikeobservant** [studio-minus/ppg-bugs-and-requests#204]
**Feature description**
title, pretty much all there is to it.

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**
For example, if the camera was like this, it wouldn't change the rain noise.
![image](https://user-images.githubusercontent.com/89762931/132972284-f68a9048-c48f-42f7-b025-caf3a84cce26.png)
Whereas if the camera was like this the rain noise would change to a quieter version. Even though the camera isn't fully in, its still close enough. all of this is futile if rain doesn't stop when hit object
![image](https://user-images.githubusercontent.com/89762931/132972300-17e817a5-6f09-4faa-8cc1-fb3b712ffc00.png)

**Comment by alikeobservant** [comment]
weird shitbag in tower is supposed to be a human for scale

**Comment by TamasB14** [comment]
Wouldn't it require the raindrops to be physical objects? It'd really decrease the performance. My other guess is that the thing you want is called "effect shadowing" for raindrops that stands for basically stopping raindrop effects(sounds too) to go through and object, which is really hard to do in a 2D game with spawnable items as all items would need an individual "shadowing" script which would surely decrease the performance. It'd only work in premade maps where the individual zones could be selected to not have Raindrop effects.

**Comment by mestiez** [comment]
please follow the feature report template
