### ISSUE TITLE
Set the servo of the servo???

### ISSUE THREAD

**Issue by tomatoiab** [studio-minus/ppg-bugs-and-requests#2042]
**Describe the bug**
Set the servo of the servo, Don't Set the speed of the servo
**Clearly describe how to reproduce the bug**
Set servo speed's description is Set the servo of the servo.
**Additional notes**
Thanks zooi to update the game ;)

**Comment by DindinYT37** [comment]
What do you mean?

**Comment by DindinYT37** [comment]
What do you mean?

**Comment by mestiez** [comment]
they meant that there was a malformed description in the context menu. fixed :)
