### ISSUE TITLE
Lowering ambient temperature does not kill humans (beta)

### ISSUE THREAD

**Issue by Frederick-7689** [studio-minus/ppg-bugs-and-requests#2044]
-Describe the bug

By lowering the ambient temperature to the lowest value (-100°C/-148°F), the body temperature of humans drops to only 36°C, remaining constant even after a long time.

-Clearly describe how to reproduce the bug

Place a human and lower the ambient temperature to any value below zero.

-Mod list

All loaded mods:

	Dyadyushka Dyadya-People Playground Discord Stats-2846890700 v1.0 for game v1.24+
		Currently inactive

	Pumpkin-Old Maps-2765380132 v1.2 for game v1.22.3
		Currently inactive

	Team Wilson-People Playground 3D-2785176210 v1 for game v1.21+
		Currently inactive

	JOSIMA-Enhanced Human Sounds-2738554876 v0.1 for game v1.11+
		Currently inactive

	zooi-Dead No Collide-local v1.0 for game v1.20
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently inactive

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently inactive

	zooi-depletable engines-2463360042 v1.3 for game v1.19
		Currently inactive

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently inactive

	zooi-Per Pixel Destruction-2314372940 valpha 7 for game v1.13.1
		Currently inactive

	zooi-Controllable anti-air cannon-2178648827 v1.2 for game v1.9.3
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently inactive

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently inactive

People Playground [v1.26 preview 2] [64 bit]

System info:

OS: Windows 10 (10.0.22000) 64bit
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU: NVIDIA GeForce RTX 2060
Memory: 16 GB

-Additional notes

https://user-images.githubusercontent.com/102178009/187886912-5861deb8-3c12-49c8-b60c-a3ca2c74d9c8.mp4

**Comment by DindinYT37** [comment]
Doesn't happen for me, it could be because of the map  you're using though. On the Default map it works as intended and this doesn't happen though.

**Comment by Frederick-7689** [comment]
I tested it on the snow map.
Now I will try it on the other maps as well.

**Comment by Frederick-7689** [comment]
> Doesn't happen for me, it could be because of the map you're using though. On the Default map it works as intended and this doesn't happen though.

Are you sure you are playing the beta preview?
It happens to me in all maps.

**Comment by mestiez** [comment]
I can't reproduce this at all. People just flash freeze when I set the ambient temperature to -100...

**Comment by Frederick-7689** [comment]
I uninstalled the game and reinstalled it but it still happens.
I disabled all the mods.

**Comment by fhgb54643689** [comment]
same thing happens for me

**Comment by Frederick-7689** [comment]
However the problem was solved with preview 3
