### ISSUE TITLE
More interactive maps like "substructure"

### ISSUE THREAD

**Issue by NDM03** [studio-minus/ppg-bugs-and-requests#2046]
I would like to see a similar map like substructure with some interaction like for example the elevator.
- Maybe like a Building with a couple windows and an elevator with some extras
- furthermore it has no purpose other than fun

edit(making DindinYT37 happy with himself)

**Comment by NDM03** [comment]
> How did you even manage to mess up the template like this

Because i am tired alright now go play roblox and fuck off

**Comment by DindinYT37** [comment]
> > How did you even manage to mess up the template like this
> 
> Because i am tired alright now go play roblox and fuck off
> 

Rude. GitHub is 13+ btw, so you probably shouldn't be on here in the first place.

**Comment by NDM03** [comment]
Why do you feel the need to reply to this thread just because i didnt feel like deleting the standard template of the request talk about 13+

**Comment by DindinYT37** [comment]
> Why do you feel the need to reply to this thread just because i didnt feel like deleting the standard template of the request talk about 13+

Why do you feel the need to instantly insult people you've never met on the internet just because they've asked you a simple question, and rightfully so? The problem is also not just that you "didn't feel like deleting the standard template" but that you completely messed it up. I feel the need to talk about GitHub being 13+ because you act like a literal child.

**Comment by NDM03** [comment]
Because your reply to the thread had an offending setup toward me on how I could be so dumb to mess up a simple thing, and so I replied to you that you could "fuck off" because you can't let a little thing on the internet like a "messed up template" go. next time just scroll by or comment 'ah man i don't think your template is clear enough in this form' reactions toward that will be a lot different. and if you think telling someone to fuck off is acting like a literal child you might need to check your birth certificate because it might say you were born in 2009.

**Comment by DindinYT37** [comment]
> Because your reply to the thread had an offending setup toward me on how I could be so dumb to mess up a simple thing, and so I replied to you that you could "fuck off" because you can't let a little thing on the internet like a "messed up template" go. next time just scroll by or comment 'ah man i don't think your template is clear enough in this form' reactions toward that will be a lot different. and if you think telling someone to fuck off is acting like a literal child you might need to check your birth certificate because it might say you were born in 2009. 

I mean, I was indeed wondering how you managed to mess it up that badly, though not as insult but as curiosity. Considering the fact you're going off on this that badly, I'd suggest you to check your own birth certificate first.

**Comment by NDM03** [comment]
> > Because your reply to the thread had an offending setup toward me on how I could be so dumb to mess up a simple thing, and so I replied to you that you could "fuck off" because you can't let a little thing on the internet like a "messed up template" go. next time just scroll by or comment 'ah man i don't think your template is clear enough in this form' reactions toward that will be a lot different. and if you think telling someone to fuck off is acting like a literal child you might need to check your birth certificate because it might say you were born in 2009.
> 
> I mean, I was indeed wondering how you managed to mess it up that badly, though not as insult but as curiosity. Considering the fact you're going off on this that badly, I'd suggest you to check your own birth certificate first.

didn't know your intention on the first reply, read it like an insult at that time. felt already angry/moody because of my day, and typing is a reply back is then way to easy. but I now edited it specially for you so you can easily read it and can rest easy tonight.

**Comment by DindinYT37** [comment]
> didn't know your intention on the first reply, read it like an insult at that time. felt already angry/moody because of my day, and typing a reply back is then way to easy. but I now edited it specially for you so you can easily read it and can rest easy tonight. 

Well I can understand that since it's just text anyway, and I can't expect you to guess the tone of it right but... how do I say this now... you uh- you _didn't follow the template._

**Comment by NDM03** [comment]
No hard feelings, goodnight lad.

**Comment by mestiez** [comment]
this is not explicit enough
