### ISSUE TITLE
Bug in rocket launcher particles (beta)

### ISSUE THREAD

**Issue by Frederick-7689** [studio-minus/ppg-bugs-and-requests#2047]
-Describe the bug

The particles generated by the rocket of the rocket launcher are surrounded by a black square.

-Clearly describe how to reproduce the bug

Generate and activate a rocket launcher.

-Mod list

All loaded mods:

	Dyadyushka Dyadya-People Playground Discord Stats-2846890700 v1.0 for game v1.24+
		Currently inactive

	Pumpkin-Old Maps-2765380132 v1.2 for game v1.22.3
		Currently inactive

	Team Wilson-People Playground 3D-2785176210 v1 for game v1.21+
		Currently inactive

	JOSIMA-Enhanced Human Sounds-2738554876 v0.1 for game v1.11+
		Currently inactive

	zooi-Dead No Collide-local v1.0 for game v1.20
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently inactive

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently inactive

	zooi-depletable engines-2463360042 v1.3 for game v1.19
		Currently inactive

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently inactive

	zooi-Per Pixel Destruction-2314372940 valpha 7 for game v1.13.1
		Currently inactive

	zooi-Controllable anti-air cannon-2178648827 v1.2 for game v1.9.3
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently inactive

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently inactive

People Playground [v1.26 preview 2] [64 bit]

System info:

OS: Windows 10 (10.0.22000) 64bit
CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
GPU: NVIDIA GeForce RTX 2060
Memory: 16 GB

-Additional notes

![Screenshot (354)](https://user-images.githubusercontent.com/102178009/187941647-25365503-d130-48f1-8fac-25c8270b3431.png)

**Comment by Frederick-7689** [comment]
Update:
This is also the case with missile launchers.

**Comment by mestiez** [comment]
yes this was already reported and fixed

**Comment by Frederick-7689** [comment]
O ok sorry
