### ISSUE TITLE
Some items glitch out of map and generate lag

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#205]
**Describe the bug**
Sometimes items glitch out of map, and while they're falling in the endless void they generate lag.

**Clearly describe how to reproduce the bug**
Put item out of map, continue to play game normally for 10+ minutes.

**Mod list**
I tried disabling all my mods already, it's a vanilla bug.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.12.3
 - GPU: Nvidia GeForce GTX 1070
 - CPU: AMD Ryzen 2700X

**Additional notes**
I think it's generating lag either because they're falling and increasing the "generated area" endlessly, or they're just accelerating to infinity. (Though I think there is a terminal velocity in People Playground)

**Comment by UniDuki** [comment]
How do you "put an item out of the map"?

**Comment by DindinYT37** [comment]
Stop time, zoom out and move it out? You know, the black "walls" you see there don't go all the way. Most of it is just darkness.
Also there's a collision bug at the very left of the map, if you zoom out and move the item with extreme speed to the top or bottom, you can glitch in between the left wall and the floor and just drag it out of map.

**Comment by mestiez** [comment]
The solution here would be to delete objects that go out of bounds. Or at least remove objects that stay out of bounds for too long.

**Comment by mestiez** [comment]
Objects are now destroyed if they are out of bounds for over 5 seconds.
