### ISSUE TITLE
Stabbing someone in the chest should not do nothing

### ISSUE THREAD

**Issue by TeslaCoil9001** [studio-minus/ppg-bugs-and-requests#2051]
**Feature description**
As it suggests, impaling someone in the heart is anti-climactic. it should actually do something. Idk what though...

**Feature purpose**
Fun and realism

**Comment by DindinYT37** [comment]
It quite literally kills them?

**Comment by TeslaCoil9001** [comment]
> It quite literally kills them?
It doesn't. Try actually disabling your mods and stabbing them. You probably have a mod that makes it do that.

**Comment by DindinYT37** [comment]
> > It quite literally kills them?
>
> It doesn't. Try actually disabling your mods and stabbing them. You probably have a mod that makes it do that.

It does, I tested it without any mods to begin with. It at the very least stops his heart which kills him after like 10 seconds.

**Comment by TeslaCoil9001** [comment]
oh sorry. I never noticed it really. i though they died from bleeding.

**Comment by DindinYT37** [comment]
> oh sorry. I never noticed it really. i though they died from bleeding.

Try using "inspect" on the whole human and then stabbing him.
