### ISSUE TITLE
ray cannon explosion weird box [beta]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2056]
**Describe the bug**

https://user-images.githubusercontent.com/101178735/188048228-2e30b8dc-a733-4423-a0cd-a793f83bbfa7.mp4

**Clearly describe how to reproduce the bug**
get ray cannon
shoot it
look at explosion

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9474501/exported.game.debug.info.md)

**Comment by TeslaCoil9001** [comment]
Everything is just falling apart with this update lol

**Comment by DindinYT37** [comment]
> Everything is just falling apart with this update lol

It's a beta, this is what should be expected.

**Comment by mestiez** [comment]
fixed :)
