### ISSUE TITLE
When Jet engine Exploded in jet engine starting/closing,jet engine can't open forever

### ISSUE THREAD

**Issue by tomatoiab** [studio-minus/ppg-bugs-and-requests#2058]
**Describe the bug**
When Jet engine Exploded in jet engine starting/closing,jet engine can't starting forever

**Clearly describe how to reproduce the bug**
1,create Jet engine
2.activate Jet engine
3.Let the Jet engine explode in starting
4.Bug appear
**Mod list**
N/A

My English is not good sry :(

**Comment by DindinYT37** [comment]
What does this even mean

**Comment by tomatoiab** [comment]
> What does this even mean

Mean when you activate the jet engine and let the jet engine explode in it's Warm-up time,the jet engine can't work forever


My English is so bad sry :(

**Comment by DindinYT37** [comment]
Isn't that because it broke from the explosion/overheating though?

**Comment by mestiez** [comment]
fixed
