### ISSUE TITLE
Android's front arm can't get bloody

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#206]
**Describe the bug**
The arm in front of the body and the other arm, can not get bloody no matter how hard you try. Slamming humans into it, modded blood, gorse blood, exploding bodies inside of it. Still no blood on it.

**Clearly describe how to reproduce the bug**
Spawn an android
Smack his front arm with a human a bunch

**Mod list**
None

**Additional notes**
![image](https://user-images.githubusercontent.com/69184577/133482309-8c0fde7a-e7e4-4648-a1dc-2c80b728edde.png)

**Comment by mestiez** [comment]
fixed after seven million years

**Comment by Drogo-man** [comment]
> fixed after seven million years

OMG FINALLY
