### ISSUE TITLE
attachments for weapons

### ISSUE THREAD

**Issue by heartst0p** [studio-minus/ppg-bugs-and-requests#2062]
attachments would be an awesome feature. suppressors, stocks, lasers, etc. maybe even larger mags with different ammo types.

**Comment by heartst0p** [comment]
why is this a thumbs down

**Comment by DindinYT37** [comment]
This is something that should be added by mods in my opinion.

**Comment by TeslaCoil9001** [comment]
This is a duplicate of a feature that was rejected. I'd recommend closing this issue.
1623

**Comment by mestiez** [comment]
this has been on the wishful thinking list and has since been implemented by aspa102
