### ISSUE TITLE
Jet engine breaking sound

### ISSUE THREAD

**Issue by UnHoly-Water** [studio-minus/ppg-bugs-and-requests#2065]
**Describe the bug**
When a jet engine explodes it stops all sound effects from outside of the cameras view from being heard

**Clearly describe how to reproduce the bug**
1. Explode a jet engine (It may need to be on)
2. Try and throw something outside of the cameras view at a wall like an android

**Mod list**
All mods are deactivated
	Dyadyushka Dyadya-Environment time changer-2850737647 v1.0 for game v1.24+
		Currently inactive

	Dyadyushka Dyadya-Fire remover button-2840340693 v1.0 for game v1.24+
		Currently inactive

	Gachatorrent and Aubarino-Starved nextbot-local v1.0 for game v1.20+
		Currently inactive

	Aubarino-Functional Senator Armstrong Mod-local v1.0 for game v1.20+
		Currently inactive

	cryomaniac & Aubarino-Obunga Nextbot-local v66.6 for game v1.20+
		Currently inactive

	Purepsi-Walter White Nextbot-local v1.25 for game v1.25+
		Currently inactive

	Cartoon Cat-Garrett Nextbot-local v1.0 for game v1.20+
		Currently inactive

	Slebbey-Joe Biden Nextbot-local v1.25 for game v1.25+
		Currently inactive

	royalealbert27-Neco Arc Nextbot-local v1.0 for game v1.20+
		Currently inact

	Slebbey-Amogus Nextbot-local v1.25 for game v1.25+
		Currently inactive

	Slebbey-Mommy Long Legs Nextbot-2838369303 v1.25 for game v1.25+
		Currently inactive

	Aubarino-Troll Nextbot-local v1.0 for game v1.20+
		Currently inactive

	Aubarino-Nextbot Base-local v1.0 for game v1.20+
		Currently inactive

	Dyadyushka Dyadya-Dead creatures remover button-2838002082 v1.0 for game v1.24+
		Currently inactive

	Dyadyushka Dyadya-Colorful Energy Sword-local v1.0 for game v1.24+
		Currently inactive

	Brian9171-Limb Attachments-2660556899 v0.3 for game v1.22+
		Currently inactive

	Maxe & Dyadya-Advanced Zombie Injector (v1.2)-2815591838 v1.2 for game v1.24+
		Currently inactive

	Prototrode-Powerful Generators-2811445505 v1.2 for game v1.25+
		Currently inactive

	zuccian-ZOOM-2810253651 v1.0 for game v1.10+
		Currently inactive

	Orsoniks/Navii-Husk Overdose-local v1.0 for game v1.21+
		Currently inactive

	Maxe & Dyadushka-Realistic Axe mod-local v1 for game vAny
		Currently inactive

	Azule-Aerodynamics-2798194010 v1 for game v1.23.x+
		Currently inactive

	Orsoniks/Navii-Better Androids-2795222098 v1.0 for game v1.23+
		Currently inactive

	Dyadyushka Dyadya-Realistic Atom Bomb-2792881991 v1.0 for game v1.23+
		Currently inactive

	Dyadyushka Dyadya-Wind Generator-2785388021 v1.0 for game v1.22.3+
		Currently inactive

	Dyadyushka Dyadya-SpawnableLift-2780861030 v1.0 for game v1.23+
		Currently inactive

	Orsoniks / Navii-SimplePortals-2759460093 v1.0 for game v1.22+
		Currently inactive

	Aubarino-Node Mapper-2644178588 v1.1 for game v1.20+
		Currently inactive

	PeppRRicoochie-The Grappling Gun Mod-2637017257 v2.1 for game v1.22.3
		Currently inactive

	Nightzz-Item Plus-2612273009 v6.0 for game v1.21.x
		Currently inactive

	ahlad to the bone-skull stick shift-local v0.69 for game vskull stick shift
		Currently inactive

	Voidy-Reattach Limbs-2507657213 v1.0 for game v1.20+
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently inactive

	Morzzic-Smart Spawner-2195054961 v2.2 for game v1.10+
		Currently inactive

	Svit and Sky-POT O' Items-2187367733 v1.2 for game v1.9.4
		Currently inactive

	Kelly The Dragon-The Tungsten Mod-2170418527 v2.4 for game v1.8 +
		Currently inactive

	Holy_Water-Dark Souls Death Sound-2854464508 v1.1 for game v1.25+
		Currently inactive

	Holy_Water-Goofy Ahh Noises Pack-2848317867 v1.0 for game v1.25+
		Currently inactive
		Malfunctioning

	Holy_Water-Roblox Oof Slowed-2850930350 v1.1 for game v1.25+
		Currently inactive

	Holy_Water-Roblox Death Sound-2848317867 v1.1 for game v1.25+
		Currently inactive

	Holy_Water-Women Mod-2494111394 v.9.1 for game v1.8+
		Currently inactive

	Holy_Water-Yoda Death Sound-2849076040 v1.0 for game v1.25+
		Currently inactive

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.26
 - GPU: NVIDIA GeForce RTX 2070 Super
 - CPU: Intel Core I7-10700 2.90 GHz
 
[exported game debug info.md.txt](https://github.com/studio-minus/ppg-bugs-and-requests/files/9481547/exported.game.debug.info.md.txt)
ive

**Comment by mestiez** [comment]
fixed must be the 40000 shrapnel coming out
