### ISSUE TITLE
I want to suggest making a device that will accurately pick up the desired effect or create it from the chemistry section .

### ISSUE THREAD

**Issue by NASAsolar** [studio-minus/ppg-bugs-and-requests#2069]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by TeslaCoil9001** [comment]
Please actually fill out your suggestion

**Comment by Reycko** [comment]
idk if "Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?" can make it useful.

**Comment by DindinYT37** [comment]
I will predict, this will get closed as unplanned.

**Comment by mestiez** [comment]
idk wtf this is again
