### ISSUE TITLE
Magnet + Magnet = Lag

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#207]
**Describe the bug**
Having two electromagnets in the same spot, with at least one activated, will cause a lot of lag, also teleport them to the world origin.

**Clearly describe how to reproduce the bug**
Spawn two Electromagnets while paused
Make sure they are both in exactly the same spot
Activate at least one of them
Unpause
Your game should now be super laggy, and both electromagnets should be halfway in the ground at the world origin.

**Mod list**
None

*by world origin i mean like in the centre of where the camera always starts when loading a map, idk if it is actually the world origin*

**Comment by mestiez** [comment]
likely a _divide by zero_ error inside the physics engine

**Comment by DavidCo113** [comment]
It absorbed my entire gigantic frying pan now what
