### ISSUE TITLE
heating jet engine with another jet engines makes it.. cooler?

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2074]
**Describe the bug**
![image](https://user-images.githubusercontent.com/101178735/188265127-88b0674c-bab5-4167-a4c8-fa13d1318ca7.png)
![image](https://user-images.githubusercontent.com/101178735/188265148-d5e21ae1-ab97-4a80-9fcd-cb5730edd684.png)
(look at thermometer)

**Clearly describe how to reproduce the bug**
do it like the image above

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9482322/exported.game.debug.info.md)

**Additional notes**
i dont know if thats how heat works or not

**Comment by Drogo-man** [comment]
Wdym this si perfectly normal

**Comment by mestiez** [comment]
this happens because the exhaust is burning at some temperature. if something is hotter than this exhaust, the exhaust will act cooling. its less realistic but I could make it so that it can only ever heat up.

**Comment by DindinYT37** [comment]
More realistic is better, in my opinion.
