### ISSUE TITLE
Androids will shake

### ISSUE THREAD

**Issue by TeslaCoil9001** [studio-minus/ppg-bugs-and-requests#2079]
**Describe the bug**
When you spawn an android, after a few seconds he starts shaking.

**Clearly describe how to reproduce the bug**
1. Spawn Android
2. Wait 11~ seconds
3. Shaking android

**Mod list**
No mods

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.26 preview 3 (64 bits)
 - GPU: Idk
 - CPU: Idk

**Comment by mestiez** [comment]
fixed :) he was just a bit cold
