### ISSUE TITLE
Tank can't be fully weightless

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#208]
**Describe the bug**
The tank has some un-selectable weight, or a part of it can't be made weightless.
Even if you clearly select the whole tank and make it weightless it still falls to the ground, just a lot slower.

**Clearly describe how to reproduce the bug**
- Spawn a tank, while paused
- Select the whole tank, right click and select "Make weightless"
- Un-pause

What *should* happen is the tank stays mid-air floating because it has no weight. In reality the tank slowly falls, meaning it still has some weight somewhere, even though you definitely just selected it all and "made it weightless".

**Mod list**
None

**Comment by mestiez** [comment]
fixed :)
