### ISSUE TITLE
Archelix Caster not firing

### ISSUE THREAD

**Issue by UnHoly-Water** [studio-minus/ppg-bugs-and-requests#2084]
**Describe the bug**
When zoomed in the archelix caster will not fire but still makes the noise

**Clearly describe how to reproduce the bug**
1. Zoom in
2. Try and fire the archelix caster

[exported game debug info.md.txt](https://github.com/studio-minus/ppg-bugs-and-requests/files/9483626/exported.game.debug.info.md.txt)

**Comment by UnHoly-Water** [comment]
This is not just limited to the preview it is also in other versions if you zoom in far enough

**Comment by UnHoly-Water** [comment]
https://user-images.githubusercontent.com/88122102/188292906-cac93c07-2210-4537-b4d7-16cf8177e922.mp4

This is on version 1.25 and it happens when you fire alot of them at the same time

**Comment by mestiez** [comment]
this happens because the pool has run out of space. the only reasonable option here is to increase the pool size

**Comment by mestiez** [comment]
not a bug really. this is intended behaviour. ill change it to feature request.
