### ISSUE TITLE
A change to the jet-engine SFX

### ISSUE THREAD

**Issue by YourLocalPlonker** [studio-minus/ppg-bugs-and-requests#2089]
**Feature description**
The new jet-engine sounds way too smooth for a jet-engine. It should have a growl to it.

**Feature purpose**
realism

**Additional context**
https://www.youtube.com/watch?v=tdczvix3EiE (here's a video to show what I mean with the growl)

**Comment by DindinYT37** [comment]
I think what you mean is actually just air hitting the microphone of the camera, or I didn't get what you mean at all.

**Comment by Drogo-man** [comment]
Correct me if I'm wrong, but I'm like 99% sure the one in the game is a ramjet engine, not an afterburner.

**Comment by YourLocalPlonker** [comment]
> I think what you mean is actually just air hitting the microphone of the camera, or I didn't get what you mean at all.

I mean yeah noise is created by moving air. But no it isn't the strong wind produced by the engine otherwise the camera would either fly away or melt

**Comment by mestiez** [comment]
this is just the microphone clipping, its not the sound it would make if you were stood there
