### ISSUE TITLE
wow its a weird camera bug

### ISSUE THREAD

**Issue by BrianTheVoid** [studio-minus/ppg-bugs-and-requests#2092]
**Describe the bug**
basically, if you try to zoom in while the game is frozen due to lag, the camera will go upside down when the game is unfrozen, i believe this is because the camera orthographic size goes below 0, this is normally impossible to do, but lag makes it possible.

**Clearly describe how to reproduce the bug**
try to zoom in while the game is frozen.

**Comment by PossiblyRemember** [comment]
wow that is a weird camera bug, but I just tried to lag my game and after it successfully froze and I zoomed in as much as I could, my camera was astonishingly still upside up. what did you do to lead up to this event?

**Comment by BrianTheVoid** [comment]
> wow that is a weird camera bug, but I just tried to lag my game and after it successfully froze and I zoomed in as much as I could, my camera was astonishingly still upside up. what did you do to lead up to this event?
i literally just did what i said, i just made my game freeze and zoomed in, but i used the keyboard key instead of the mouse, so try that instead?

**Comment by PossiblyRemember** [comment]
> i literally just did what i said, i just made my game freeze and zoomed in, but i used the keyboard key instead of the mouse, so try that instead?

still doesn't work, my camera remains fine, what did you do to freeze your game?

**Comment by mestiez** [comment]
I believe it's fixed
