### ISSUE TITLE
Bandages are stiff in 1.26 preview

### ISSUE THREAD

**Issue by Imadethisaccountjustforthisbugreport** [studio-minus/ppg-bugs-and-requests#2095]
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9486517/exported.game.debug.info.md)
Bandages have behavior similar to the stiff springs and can support weight instead of the previous rope-like physics.
![20220904204140_1](https://user-images.githubusercontent.com/86169354/188356601-b4378f00-1ecd-4074-a703-df1a1177a84c.jpg)

**Comment by Drogo-man** [comment]
Someone got in the mood and this was the first thing they saw lol.

**Comment by mestiez** [comment]
I just compared bandage behaviour in 1.25 and 1.26 and it is identical... it never acted like rope. It was always like this.
