### ISSUE TITLE
Arcs from Tesla coils behave strangely, but only if there isn't anything in range.

### ISSUE THREAD

**Issue by Imadethisaccountjustforthisbugreport** [studio-minus/ppg-bugs-and-requests#2096]
Electrical arcs from tesla coils are unaffected by pausing or slow motion, but only when there aren't any conductive objects within range. This isn't a new issue, I noticed it several versions back I just didn't get around to submitting a bug report until now.
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9486543/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
I think this has always been the case though. Also, please use the template.

**Comment by Drogo-man** [comment]
> 

"This isn't a new issue, I noticed it several versions back I just didn't get around to submitting a bug report until now."
