### ISSUE TITLE
reload mods without exiting

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2097]
**Feature description**
a way to reload all your mods without exiting the game

**Feature purpose**
incase you downloaded new mods while playing and don't want to quit out

**Comment by TeslaCoil9001** [comment]
This has already been rejected a lot

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #589
* #605 
* #694
* #1072 
* #1173 
* #1192 
* #1794 
* #1957
* #1998
* #2091

*Note that what you requested here was rejected several times before, not to mention that this was also last requested just 14 hours ago.*

**Comment by TeslaCoil9001** [comment]
I just said that, and he already closed it

**Comment by DindinYT37** [comment]
> I just said that, and he already closed it

No you have not, you only just said that it has already been rejected a lot. You have not provided a full list, or said that the last time this was requested was 14 hours ago.

**Comment by Drogo-man** [comment]
Just exit the game, it takes 2 seconds.
