### ISSUE TITLE
pump shotgun

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2098]
**Feature description**
a shotgun with pump and an animation and sound

**Feature purpose**
more weapons

**Additional context**
![image](https://user-images.githubusercontent.com/109692890/188385205-a9aedb36-1016-4588-903f-98e6be9323ab.png)

**Comment by DindinYT37** [comment]
Added already a crap ton of mods, not to mention that it's just a reskin of what we haven ow.

**Comment by TeslaCoil9001** [comment]
How is this different enough from the regular shotgun?

**Comment by ATPGaming** [comment]
how did you guys comment at the exact same time

**Comment by ATPGaming** [comment]
> How is this different enough from the regular shotgun?

it has pump

**Comment by TeslaCoil9001** [comment]
It seems more like something a mod should do. If you want a weapon to be added then it should be unique and different from the weapons we already have, not just a reskin.

**Comment by DindinYT37** [comment]
> how did you guys comment at the exact same time

Actually I commented earlier.

> How is this different enough from the regular shotgun?
>
> it has pump

It's literally the same.

**Comment by ATPGaming** [comment]
> > how did you guys comment at the exact same time
> 
> Actually I commented earlier.
> 
> > > How is this different enough from the regular shotgun?
> > 
> > 
> > it has pump
> 
> It's literally the same.

that was essentially what was just said

**Comment by TeslaCoil9001** [comment]
Not really

**Comment by Drogo-man** [comment]
I love how the image he provided is just a semi-auto hunting shotgun with wooden furniture.

**Comment by YourLocalPlonker** [comment]
> > How is this different enough from the regular shotgun?
> 
> it has pump

It would be very impractical and would constantly require the player to reload the shotgun manually.

**Comment by TeslaCoil9001** [comment]
> > > How is this different enough from the regular shotgun?
> > 
> > 
> > it has pump
> 
> It would be very impractical and would constantly require the player to reload the shotgun manually.

Enough. It got closed

**Comment by DindinYT37** [comment]
> Enough. It got closed

That doesn't mean people can't keep commenting on the issue.
