### ISSUE TITLE
the abiltiy to distable/defsue the fusion bomb,nuke (you know what im talking about), and other bombs that cause a really big explosion.

### ISSUE THREAD

**Issue by roscosthebalm** [studio-minus/ppg-bugs-and-requests#210]
they could possibly add wire clippers to so you could clip the wires and if you do it wrong it explodes.

**Comment by idotwaffle** [comment]
follow the fucking template
and "clip the wires", what wires? some random wires sticking out the top? a panel that opens up somehow and zooms in and is like a minigame? some tiny wires in a small sqaure? will the wire cutter go through the bomb? bruh cmon
