### ISSUE TITLE
Limb regeneration

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2100]
**Feature description**
Make it so if you take a limb off you can put it back on with stitching or have a syring which makes it regen. just a way to make limbs reattach or grow back.

**Feature purpose**
so that i can put humans back together if i tear their arms off

**Comment by TeslaCoil9001** [comment]
This has already been rejected a lot of times.

**Comment by TeslaCoil9001** [comment]
ATP Gaming carefully picking the worst suggestions to suggest
![image](https://user-images.githubusercontent.com/112362312/188392086-a8fb8fb3-bd06-498e-9c01-a225a83e8a75.png)

**Comment by DindinYT37** [comment]
Related to or Duplicate of:
* #254
* #425
* #435
* #629
* #709
* #1212 
* #1548 
* #1612
* #1631 
* #1652
* #1739
* #1778 
* #1865 
* #1885
* #2082
