### ISSUE TITLE
Add a team feature, so u can make people as a team so they cant shoot eachother please zooi add this i beg u

### ISSUE THREAD

**Issue by kepalabapakkauanjing** [studio-minus/ppg-bugs-and-requests#2119]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by DindinYT37** [comment]
How about actually filling in the issue and not putting everything in the issue? Also, you can do this with some phase links.

**Comment by Drogo-man** [comment]
I don't think this guy has been here for long.

**Comment by mestiez** [comment]
idk wtf this is
