### ISSUE TITLE
The Winch can have negative limits

### ISSUE THREAD

**Issue by DavidCo113** [studio-minus/ppg-bugs-and-requests#212]
**Describe the bug**
The winch can have negative upper and lower limits.

**Clearly describe how to reproduce the bug**
Set the lower limit of the winch to a negative value

**Comment by idotwaffle** [comment]
if this is a "bug" i think i should be an intentional feature cus i like it and it's pretty useful

**Comment by mestiez** [comment]
I can't remember if this was intentional. Very cool.
