### ISSUE TITLE
Problems with updates

### ISSUE THREAD

**Issue by danil22830021** [studio-minus/ppg-bugs-and-requests#2121]
I found out that there was an update in people playground, it was already uploaded to steam (yes, I only found out about the update of the game) I look at what has changed, I decide to check that the tires are bursting or deflating in the game I go in and check I start the car and the game nothing I decide to shoot with a machine gun on the tires the result is nothing happened I check all the updates and everyone writes that everything is updated, I check many more changes And THERE's NOTHING I don't know, either the update hasn't come out yet, but 10 days have already passed since the update and the update should definitely change the game so I don't know

**Comment by DindinYT37** [comment]
How about actually using the template? Also, it wasn't updated yet - we're using the Beta build.
