### ISSUE TITLE
ADD A ARTİLLERY CANNON

### ISSUE THREAD

**Issue by HrKn820** [studio-minus/ppg-bugs-and-requests#2122]
ADD A ARTİLLERY CANNON

**Comment by DindinYT37** [comment]
How about actually using the template instead of just screaming at us?

**Comment by YourLocalPlonker** [comment]
I am pretty sure you can make an artillery cannon yourself and it doesn't require mods. There are so many items in the game you can make an fire-and-forget missile (Missile that doesn't require any further input from the host to find its target) so an artillery cannon should be no problem.
