### ISSUE TITLE
new weapons

### ISSUE THREAD

**Issue by Br1cky** [studio-minus/ppg-bugs-and-requests#2124]
p90, light, high rate of fire, and good penetration for light armor
uzi, high fire rate, low accuracy, high recoil
drill, similar to the chainsaw, but small, and doesn't dethatch parts
machete, a good in-between for the knife and sword
hot knife, a knife that when activated makes the blade very hot (the handle will still be safe)
pickaxe, a heavy double-sided bladed weapon
katana, a lighter sword with a slightly longer blade
aa-12, a full auto shotgun
cannon bomb, a bomb that must be manually lit. kind of like the cartoon bombs you see
bow, a wooden version of crossbow that fits more with medieval
scar-h, a stronger and faster firing assault rifle, but also heavier
syringe shooting crossbow, this one is self-explanitory
some sort of burst weapon, your choice dev
musket, rifle variant of flintlock

that's all

**Comment by TeslaCoil9001** [comment]
Good suggestions, but try not to multirequest. Some of these weapons were also already suggested.

**Comment by Br1cky** [comment]
> Reference in new iss

SHUT THE FUCK UP MINI MOD

**Comment by TeslaCoil9001** [comment]
> > Reference in new iss
> 
> SHUT THE FUCK UP MINI MOD

I really hope you're saying this in a parody way

**Comment by Drogo-man** [comment]
Hmm, these seem like they could easily be added by mods.

**Comment by DindinYT37** [comment]
I doubt this **can** even be accepted, it breaks almost all of the few rules a request should follow. Also, basically all of this can be made by mods and/or already was.

**Comment by bibbybabby** [comment]
> I doubt this **can** even be accepted, it breaks almost all of the few rules a request should follow. Also, basically all of this can be made by mods and/or already was.

i wish a drill could be modded in that is not a knife reskin

**Comment by DindinYT37** [comment]
> > I doubt this **can** even be accepted, it breaks almost all of the few rules a request should follow. Also, basically all of this can be made by mods and/or already was.
> 
> i wish a drill could be modded in that is not a knife reskin

It could be, it's just that nobody does - and even if someone did, unless they put (much?) effort into doing so, it's just gonna be a chainsaw reskin.

**Comment by mestiez** [comment]
Please do not group requests
