### ISSUE TITLE
change layer keybind doesn't work if you dont have the change layers menu open [1.26 preview 4]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2132]
**Describe the bug**
title

**Clearly describe how to reproduce the bug**
1. set up your keybinds for changing layers in the control settings
2. spawn an object with another object (so you can see the layer changes)
3.  change object layer with keybind which doesn't work unless you have edit layers menu open

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9565641/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
Isn't that intentional?

**Comment by royalealbert27** [comment]
> Isn't that intentional?

if it is then why have the keybinds if you have the layer buttons infront of you

**Comment by royalealbert27** [comment]
before you say "so it's faster?" or anything like that, making it work without the layer menu open is much faster than clicking 2 times to get it working

**Comment by mestiez** [comment]
fixed :)
