### ISSUE TITLE
Gorse and fire layers

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#2133]
**Describe the bug**
Fire is behind gorse

**Clearly describe how to reproduce the bug**
Ignite gorse

**Mod list**
No

**System info (please complete the following information)**
 Operating system: Win 10
Game version: 1.26 preview 4
GPU: 750 ti
CPU: Intel Core i5-4590 3.30GHz

![изображение](https://user-images.githubusercontent.com/89081329/190139963-5f09d8b3-00b7-4210-841b-2a7afb73051f.png)

**Comment by Drogo-man** [comment]
That looks kinda cool ngl

**Comment by ATPGaming** [comment]
i never noticed this, or maybe its a new glitch

**Comment by mestiez** [comment]
fixed :)
