### ISSUE TITLE
Fluorescent Lamps should make a sound when activated

### ISSUE THREAD

**Issue by AhmetGeorge** [studio-minus/ppg-bugs-and-requests#2134]
Fluorescent Lamps should make a sound when activated

**Comment by DindinYT37** [comment]
So what happened to the template on this one?

**Comment by TeslaCoil9001** [comment]
Good idea, so should lightbulbs too

**Comment by mestiez** [comment]
Please make the title a very short summary of the entire issue as opposed to something vague
