### ISSUE TITLE
Fluorescent Lamps should make a sound when activated [Better Suggestion Remake]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2135]
**Feature description**
When Fluorescent Lamps gets activated, it should make a sound that plays in the substructure shower room whenever it flickers

**Feature purpose**
i think it's good imo

**Additional context**
just remaking AhmetGeorge's suggestion since they didn't used the template.

**Comment by DindinYT37** [comment]
Duplicate of #2134
