### ISSUE TITLE
Can we have an option in the menu to disable the smoke effects of fire or at least optimize it?

### ISSUE THREAD

**Issue by LaCumbiaDelCoronavirus** [studio-minus/ppg-bugs-and-requests#214]
**Feature description**
I really want the option to turn off the black smoke effects/particles that emit from things that are on fire.

**Feature purpose**
You could add this to benefit a few low-end pc users, also with the fact that my pc is not low-end though struggles to deal with the amount of smoke produced by fire, with just a few smoke particles

**Comment by idotwaffle** [comment]
fire dosnt make smoke for me wdym but there should be an option to reduce fire quality

**Comment by TamasB14** [comment]
Ah yes... the old Mutilate-a-Doll 2 fire effects...

**Comment by DindinYT37** [comment]
You probably installed a mod to do add that smoke, since that isn't part of the game.

**Comment by mestiez** [comment]
There are no smoke effects from fire. You have a mod installed that is badly optimised. Please fill in the form correctly next time.
