### ISSUE TITLE
Torture clothes

### ISSUE THREAD

**Issue by BobbyG555** [studio-minus/ppg-bugs-and-requests#2141]
**Feature description**
Clothes with spikes inside them that spike the wearers.

**Feature purpose**
To cause pain to ragdolls and things like that.

**Additional context**
Maybe have a spiked one, a hot metal kind of one that burns the wearer? and a electric one, that like elecrtocutes the wearer.

**Comment by DindinYT37** [comment]
You know you can make these yourself, right?
