### ISSUE TITLE
Make a faster mod loader

### ISSUE THREAD

**Issue by kasztanixx** [studio-minus/ppg-bugs-and-requests#2150]

**Comment by Drogo-man** [comment]
I think it's pretty fast already

**Comment by DindinYT37** [comment]
How about actually telling us about your request, and using the template? Not to mention that "faster mod loader" is not a valid request.

Also, I'd like you to read up on [this part about GitHub's Terms of Service](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#:~:text=You%20must%20be%20age%2013%20or%20older.%20While%20we%20are%20thrilled%20to%20see%20brilliant%20young%20coders%20get%20excited%20by%20learning%20to%20program%2C%20we%20must%20comply%20with%20United%20States%20law.%20GitHub%20does%20not%20target%20our%20Service%20to%20children%20under%2013%2C%20and%20we%20do%20not%20permit%20any%20Users%20under%2013%20on%20our%20Service.).
![image](https://user-images.githubusercontent.com/64973205/180064147-466d56e3-ff1b-41d4-885e-d3ac24697754.png)

**Comment by mestiez** [comment]
fantastic idea why did i think of that
