### ISSUE TITLE
Liquid valves destroy liquids in mixtures

### ISSUE THREAD

**Issue by nickedyer** [studio-minus/ppg-bugs-and-requests#2154]
**Describe the bug**
If a mixture passes through a liquid valve from one container to another, the lower concentration of liquids will vanish as it passes through the liquid valve. If the mixture is an exact 50/50 or 25/25/25/25, all liquids passing through start to disappear while the concentration stays the same.

**Clearly describe how to reproduce the bug**

1. Connect a container with a mixture of liquids to an empty container with a closed liquid valve
2. Attach a liquid pressurizer to the container with the mixture and turn it to push
3. Open the liquid valve

I've also uploaded two videos to YouTube showcasing the issue, one with an asymmetrical liquid and one with a balanced one. First half of each video showcases expected results by simply connecting a blood vessel wire to each liquidentifier.
[https://www.youtube.com/watch?v=zAcDkHwZYyI](https://www.youtube.com/watch?v=zAcDkHwZYyI)
[https://www.youtube.com/watch?v=np3Lz-CpQqg](https://www.youtube.com/watch?v=np3Lz-CpQqg)

**Mod list**
No mods installed.

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9592896/exported.game.debug.info.md)

**Comment by nickedyer** [comment]
Looks like this was already fixed with #1941 , testing on 1.26 prev. 4 and everything is working as expected. Will leave this open to be closed at your digression in case this is a different problem.

**Comment by DindinYT37** [comment]
This sounds very much like it should be closed if it's already working as expected though?

**Comment by nickedyer** [comment]
Fair enough, just wasn't sure if it was a different issue as described before or not.

**Comment by DindinYT37** [comment]
> Fair enough, just wasn't sure if it was a different issue as described before or not.

I mean, if it works how it's supposed there - there should be an issue, right?

**Comment by nickedyer** [comment]
> > Fair enough, just wasn't sure if it was a different issue as described before or not.
> 
> I mean, if it works how it's supposed there - there should be an issue, right?

No you're right, was trying to be helpful is all.
