### ISSUE TITLE
Deaths from headshot should occur sooner.

### ISSUE THREAD

**Issue by Eukalp** [studio-minus/ppg-bugs-and-requests#2155]
**Feature description**
Whenever I headshot a ragdoll, it slowly loses it's health instead of it being instant. This should really get improved by making ragdolls collapse on headshot thanks to their Central Processing Unit (brain) being damaged. Items they were previously holding should be dropped instantly. It is just stupid how after a headshot, they just hold onto their guns for a while.

**Feature purpose**
The purpose of this improvement is to add a bit more realism into the game.

**Additional context**
Thanks to this long "death time", it often causes items held by the ragdoll to just stick into their body and break their bones.

**Comment by DindinYT37** [comment]
It's realistic how it is currently, the brain being destroyed does not mean the organs are instantly dead too.

**Comment by Eukalp** [comment]
> 

That is not necessarily true. Organs should stay alive, sure... But the human should not be so tense and should not be holding onto items in hands.

**Comment by DindinYT37** [comment]
> > 
> 
> That is not necessarily true. Organs should stay alive, sure... But the human should not be so tense and should not be holding onto items in hands.

The Body is actually in shock so it could be very well that it's still gonna be tense until all organs fail, I don't know about the item thing though.

**Comment by mestiez** [comment]
they will usually immediately drop dead but occasionally stiffen up or twitch. i like it the way it is.
