### ISSUE TITLE
Fragility multiplier value rounds to nearest whole number

### ISSUE THREAD

**Issue by sarcasticastico** [studio-minus/ppg-bugs-and-requests#2160]
**Describe the bug**

When using the fragility multiplier slider, the value shown rounds to the nearest whole number rather than showing decimal places. Unsure if intended behaviour.

**Clearly describe how to reproduce the bug**

Settings > Gore > Fragility multiplier. Proof in additional notes.

**Mod list**

Active:
- Zombie Pack
- Functional Terminator Mod

Inactive:
- People Playground 3D
- Acid Sea
- Human Dynamic Emotions
- Trollge Mod
- Prototype Humans Mod
- Scream Mod

**System info**
 - Operating system: Windows 11
 - Game version: 1.26 preview
 - GPU: NVIDIA RTX 2070
 - CPU: Intel Core i5-10400

**Additional notes**

https://user-images.githubusercontent.com/113901949/191002852-8dc559c9-a639-4272-9049-f1803fdc9e44.mp4

Proof of value changes: 3 tests of 10 identical humans dropped from 10m. Fragility slider paired with overall integrity of the group.

**Test 1**

![integrity 1](https://user-images.githubusercontent.com/113901949/191013851-0e6c1a91-2300-4de1-b321-e6afe45d1498.png)
![slider 1](https://user-images.githubusercontent.com/113901949/191013864-e5982785-728d-4631-85fd-03498e052f58.png)

**Test 2**

![integrity 2](https://user-images.githubusercontent.com/113901949/191013948-88791e32-e624-4b9e-8387-0ec6b6c1c4cb.png)
![slider 2](https://user-images.githubusercontent.com/113901949/191013944-52337744-a9ff-47e0-bcbf-7658b754ac5c.png)

**Test 3**

![integrity 3](https://user-images.githubusercontent.com/113901949/191014025-319cc21f-41a1-4ce8-835d-922245fd2fce.png)
![slider 3](https://user-images.githubusercontent.com/113901949/191014047-7db71b98-87ff-45a7-96f1-b6ba71426940.png)

Though all sliders show a multiplier of 1x, there is a clear difference in the fragility of humans.

**Comment by DindinYT37** [comment]
Pretty sure that's intended since that's what the label says.

**Comment by sarcasticastico** [comment]
Does it not then seem odd for it to be a slider if it only shows whole numbers like this?

**Comment by DindinYT37** [comment]
> Does it not then seem odd for it to be a slider if it only shows whole numbers like this?

Not really. Sliders can be used in many different ways, and for this setting a slider is just more convenient.

**Comment by sarcasticastico** [comment]
The issue isn't the slider itself, it's the fact that the fragility multiplier is definitely changing in a more granular way than 0x, 1x, and 2x. The slider value doesn't reflect this.

**Comment by DindinYT37** [comment]
> The issue isn't the slider itself, it's the fact that the fragility multiplier is definitely changing in a more granular way than 0x, 1x, and 2x. The slider value doesn't reflect this.

That's just how the values increment, probably intended.

**Comment by DindinYT37** [comment]
It's not inconsistent if that's how it was intended to be - of course I cannot tell you for sure if it was intended, but sliders are usually not very consistent with their increments. Especially when they're not even in the same sub-menu.

**Comment by sarcasticastico** [comment]
Fair enough.

**Comment by mestiez** [comment]
https://user-images.githubusercontent.com/32131519/191330820-05490c96-c882-4e31-9648-8890c39a89ae.mp4

Not the case in my build. What exact version are you on?

**Comment by sarcasticastico** [comment]
Very glad you asked. Turns out I was on 1.25.4. The 1.26 preview shows up correctly. Very sorry about that!
