### ISSUE TITLE
foot hit box is to long 

### ISSUE THREAD

**Issue by Tbskins** [studio-minus/ppg-bugs-and-requests#217]
**Describe the bug**
i sometimes see that the foot hitbox is to big

**Clearly describe how to reproduce the bug**
just spawn a human and hover behind the foot

**Mod list**
i do have mods but i saw this bug before i added mods

**System info (please complete the following information)**
i dont think this would change anything

**Additional notes**

**Comment by idotwaffle** [comment]
this is intentional for some reason #200. i think it's stupud and makes problems but zooi says it's needed for the human to balance which makes no sense cus the human uses magic stabilisation and can balance without even having legs

**Comment by roscosthebalm** [comment]
same thing for the head but its the opposite

**Comment by Tbskins** [comment]
ya i dont think its needed because you can shrink the foot and will still stand

**Comment by TamasB14** [comment]
Reason: Balance

It's there for a reason. The only solution I could think of is basically making that part no-collide with bullets and melee weapons. Believe me, if they'd remove that back part, you might experience some unbalanced humans. Even with that big hitbox sometimes my Human just fall back for no reason.

**Comment by idotwaffle** [comment]
Explain how tf humans can balance without any legs or arms but apparently "need longer feet to balance"

**Comment by TamasB14** [comment]
> Explain how tf humans can balance without any legs or arms but apparently "need longer feet to balance"

Might be because of the center of weight of the upper parts of the legs. As the feet are not placed on the legs right at the middle. Some animations are also much more unbalanced. Altought I see no reasons why that back part of the feet should be deleted.

**Comment by Tbskins** [comment]
@TamasB14 do you agree that thy should make it so they don't collide with objects you spawn

**Comment by DindinYT37** [comment]
> this is intentional for some reason #200. i think it's stupud and makes problems but zooi says it's needed for the human to balance which makes no sense cus the human uses magic stabilisation and can balance without even having legs

Magic Stabilisation? That's nonsense. It's using the standard Unity physics, sure they probably have some kind of stabilisers to help with their balance but it's to spread the weight better. An Example for this is if you walk on two thin poles you easily fall over while if you attach two metal plates at the bottom, it's way harder to fall over.

**Comment by idotwaffle** [comment]
it looks completely stupid having a guy laying on the floor dead but his legs floating 
and it's just so confusing when you're trying to fit a human tightly into somewhere

**Comment by DindinYT37** [comment]
> it looks completely stupid having a guy laying on the floor dead but his legs floating
> and it's just so confusing when you're trying to fit a human tightly into somewhere

Agree on that one, maybe disable collision of the invisible/balancing part if possible would be the solution here.

**Comment by mestiez** [comment]
Not a bug. This is by design. 
Duplicate of #200
