### ISSUE TITLE
show details showing without in detail mode and vice versa [1.26 preview 4]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2175]
**Describe the bug**
i spawn a human and he seems to be in detail mode even tho detail mode is off and i can't disable it

for the opposite, an explosion doesn't show it's explosion range in detail mode

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
might not work for you
1. go in slow motion and switch detail mode
2. spawn entity or explosive

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9615007/exported.game.debug.info.md)

**Additional notes**
you need to fix this

**Comment by DindinYT37** [comment]
Doesn't happen for me.

**Comment by royalealbert27** [comment]
![image](https://user-images.githubusercontent.com/101178735/191467889-69922eb6-cffe-4710-90ab-9e7da18f56ca.png)
![image](https://user-images.githubusercontent.com/101178735/191467942-530243b3-25b7-4914-bb07-bbbd4e63b15d.png)
here's the image of the one and the opposite

**Comment by royalealbert27** [comment]
look at the top right corner, it switches detail modes and yet nothing happens on those glitches

**Comment by DindinYT37** [comment]
Still doesn't happen to me, even if you tell me again what it is.

**Comment by TeslaCoil9001** [comment]
Happens to me

**Comment by NirronCD** [comment]
You have a ton of mods on, Can you reproduce this issue with all the mods off?
In the first image the Detail View is on but i don't see nothing on the android, could be a mod issue

**Comment by royalealbert27** [comment]
blast radius even no detail mode on
![image](https://user-images.githubusercontent.com/101178735/191644613-6795541c-9a51-4677-9c25-3f8acb2c9298.png)
no nuke radius even tho detail mode is on
![image](https://user-images.githubusercontent.com/101178735/191644554-0db3ecd3-4208-4607-b500-5a529c5880ce.png)
he's different from the others
![image](https://user-images.githubusercontent.com/101178735/191644650-cddf3e03-077b-4ca5-b4f3-966ac379104b.png)
gorse and human different
![image](https://user-images.githubusercontent.com/101178735/191644669-713a8f6b-4a65-4a12-bdaa-2a47c170a6bd.png)

**Comment by royalealbert27** [comment]
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9621734/exported.game.debug.info.md)
this is my mod list i unsubscribed all mods and subscribed to few (most of the mods are made by me in the computer)

**Comment by royalealbert27** [comment]
whenever i press S, it says a nullreference in the debug log

**Comment by royalealbert27** [comment]
i have found the reason why, the mod, Make Anything Invisible, is the one that messes up your detail views

**Comment by DindinYT37** [comment]
Didn't you say multiple times that you don't have any mods enabled?

**Comment by royalealbert27** [comment]
i actually have fewer mods

**Comment by DindinYT37** [comment]
Not the point. You have said multiple times you don't have any mods enabled and even that you didn't have any at all.

**Comment by royalealbert27** [comment]
some mods still take effect even when disabled

**Comment by DindinYT37** [comment]
That only happens if you didn't restart the game after disabling them.
