### ISSUE TITLE
graphichs settings

### ISSUE THREAD

**Issue by roscosthebalm** [studio-minus/ppg-bugs-and-requests#218]
make more opitons so people with a potato pc can play

**Comment by idotwaffle** [comment]
1. again, follow the template
2. learn how to spell
3. what do you mean more options? reducing fire quality, worse resolution? or do you just mean add an option in the settings to make the game better and faster

**Comment by roscosthebalm** [comment]
1. sorry for not following it my bad
2. yes my spelling sucks
3. your right with what im trying to say so people with a low end pc can play without lag happing almost all the time

**Comment by TamasB14** [comment]
I don't think you can go downer from the current graph settings. The only graph intensive settings would be disabling particles. Sandbox games are always CPU heavy, so is this. It all depends on your CPU, as no graphic settings will give you better performance after you spawn alot of objects.
