### ISSUE TITLE
Phase links can be deleted in normal mode

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#2185]
**Describe the bug**
You can delete a phase link without going in detail mode. This creates unintended results as you can accidentally delete phase links while trying to delete something else. This includes the wire portion of the link too.

**Clearly describe how to reproduce the bug**
Create a phase link between two objects. Disable detailed mode and move your cursor around while pressing backspace.

**System info**
 - Game version: 1.26 beta

**Comment by TeslaCoil9001** [comment]
It's the fricking make everything invisible mod

**Comment by Drogo-man** [comment]
Yeah, it fucks with anything detail view related.

**Comment by EfeYks534** [comment]
> It's the fricking make everything invisible mod

There are no mods active

**Comment by Drogo-man** [comment]
its can still affect the game.

**Comment by EfeYks534** [comment]
> its can still affect the game.

How is it gonna affect the game when the mod doesn't even exist on my computer

**Comment by Drogo-man** [comment]
Mate, you wrote disabled as in the mod was installed but not on, not having the mod at all is something different.

**Comment by mestiez** [comment]
fixed
