### ISSUE TITLE
Knockout Poison appears black

### ISSUE THREAD

**Issue by DavidCo113** [studio-minus/ppg-bugs-and-requests#219]
**Describe the bug**
Because KO poison has its color set when entering a container, the liquid may appear black when saved/reloaded after a reload of the map.

**Clearly describe how to reproduce the bug**
Spawn a KO syringe
Save it to the disk
Open the pause menu and press "restart"
Load the syringe from the save
Spawn it in

**Comment by mestiez** [comment]
Fixed :)
