### ISSUE TITLE
Crate debris bug

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2192]
**Describe the bug**
The crate debris looks slightly different from the normal unbroken crate
![Screenshot (4100)](https://user-images.githubusercontent.com/109692890/192132611-d7ca4e72-fb38-4a7c-9f69-6a5c6b6c8629.jpg)

**Clearly describe how to reproduce the bug**
1. break crate in slow-mo
2. see how the debris is different

**Mod list**
I don't think mods affect this

**System info (please complete the following information)**
 - Operating system: windows 11 
 - Game version: 1.26 preview 4
 - GPU:
 - CPU:
 
 **Additional notes**
 honestly this is very minor so I don't think it will be fixed

**Comment by bibbybabby** [comment]
i think it's because the shading is gone and it's supposed to be like that, otherwise planks would have weird shadows around the edges

**Comment by ATPGaming** [comment]
> 

that explains a lot
