### ISSUE TITLE
Syringes become immune to gunfire after making a human hold it

### ISSUE THREAD

**Issue by caffreze** [studio-minus/ppg-bugs-and-requests#2196]
**Describe the bug**
After you remove a syringe from a humans hand, it becomes immune to gunfire

**Clearly describe how to reproduce the bug**
Make a human hold a syringe, then remove it from its hand, and try to shoot it. You will not be able to

**Mod list**
City map by Decibek
Extinction 1.24.5 (v2.0) by Emem404
Arrows and crystals are now debris by Dyadyushka Dyadya
Additional Vanilla Weapons by Pouloo
The Ultimate Car Mod by Mishanya
Identical Humans by hankmart
FleasyWeapons - Small Guns by Fleasy
FNAF Mod by Ljimpistool#0021
Soror's NPC Pack by Sororfortuna
Time Accelerator by Morzzic
Active Humans by quaq

All activated

**System info (please complete the following information)**
 - Operating system: Windows 10 Home
 - Game version: 1.25.4 64 bit
 - GPU: NVIDIA GeForce GTX 1650
 - CPU: Intel(R) Core(TM) i5-9300HF CPU @ 2.40GHz

Alternatively, you can attach the "exported game debug info.md" file and omit all the game and system information. You can generate this file by pressing the button in the Information page in the game. 
--->

**Additional notes**

**Comment by DindinYT37** [comment]
Doesn't happen for me.

**Comment by NirronCD** [comment]
Neither I
