### ISSUE TITLE
Fixed cables Aren't Very Fixed

### ISSUE THREAD

**Issue by amogushappymeal** [studio-minus/ppg-bugs-and-requests#22]
So basically, my fixed cables don't work. They ( and items attached to it ) can still move.

How to reproduce bug.
spawn 2 items of the same
put them in a way so it looks like a u. ( remember to connect them with a fixed cable )
Freeze the item on the left
copy and paste the item on the left and move it to the right. then unfreeze it and attach the bottom one to the right one
move it.

Mod list
Animated weapons + - active
Madness combat pipe - inactive
Madness mod - active
Nuclear playground - inactive
1000 Degree knife - active
Blockisfys Spys and hitman mod - inactive
DABABY MOD - active
Greenbrick Industries - inactive
Dynamic background music:: Doom soundtrack - inactive
Blockisfys Mafia Mod - inactive
Gorey human 2.0 - inactive
Iraq War mod
Lawless - High profile operations
flipping heck
Syringes ++ ( Reupload )
Ocean
Sulphorous sea - inactive
Combat spec ops - inactive
Combat spec ops map - inactive
Liquids map - inactive
Misc items + Mod
Flasks. More of them - inactive
Special-Weapons - inactive
Retextured nulls + - inactive
Police + - inactive
Escape from tarkov Weapons And humans - inactive
vanilla weapons+ 2
Anno dominl 1154 - inactive
Doors mod
FNF boyfriend
!Unknown mod - inactive
Volcanic map - inactive
Military + - inactive
Melee weapons mod
SCP Foundation Expanded - inactive
More explosives
Android injectors - inactive
Cry of fear mod - inactive
Furries
Drawables - inactive
Simple syringes mod
DOOM ETERNAL The crucible mod - inactive
Taser - inactive
SCP Mod - inactive
Front facing human - inactive
Titanfall small pack - inactive
Apex legends mod - inactive
ExplosiveMod - inactive
Trains and freights mod - inactive
Per pixel destruction - inactive
Human tiers - inactive
Madness PACK - inactive
Hitman mod - inactive
Skittles syringe mod
Niche syringes
Among us Mod - inactive
Chemical warfare - inactive
M1A mod - inactive
hazmat mod remastered - inactive
WoowzWeapons - inactive
Smart Spawner - inactive
Halo weapons - inactive
Extra humans - inactive
Sorors NPC pack - inactive
Humans+ - inactive
Active humans - inactive
DOOM MOD ( Eternal update ) - inactive
Overdose - inactive
Syringes++
Doom weapons pack - inactive
Cinematic mod - inactive
Map blocks
The greenbrick Mod - inactive
( Ones left blank mean they are active )

System info

Operating system: Microsoft windows 10
Game version: 1.18.1 64 bit
GPU: Intel (R) HD Graphics 500
CPU: Intel (R) Celeron (R) CPU N3350 @ 1.10Ghz

**Additional notes**
This has been happening for a while now. It works with most items in the miscellaneous tab.
game debug info
[exported game debug info.md](https://github.com/studio-minus/ppg-bug-reports/files/6650605/exported.game.debug.info.md)

**Comment by amogushappymeal** [comment]
actual bug this time

**Comment by mestiez** [comment]
unity fuckery

**Comment by Eggabegga** [comment]
Unity has no "Unity"

**Comment by SoySmash** [comment]
THAT AMOUNT OF MODS IS NOT OKAY, SEEK MEDICAL ATTENTION
