### ISSUE TITLE
Ambient Music issue in Abyss map

### ISSUE THREAD

**Issue by wave004** [studio-minus/ppg-bugs-and-requests#2200]
**Describe the bug**
The camera trigger thingy for the ambient music in the abyss map seems to be a bit small, unless the camera is somewhat close to the center of the pit (at the bottom) the music won't play - the bottom corners of the pit are uncharacteristically silent

**Clearly describe how to reproduce the bug**
-Load up Abyss
-Go down into the pit
-zoom in a little, move the camera from the sides to the middle, observe how the music toggles on and off

**Mod list**
None

**System info (please complete the following information)**
Irrellevant here I think?

**Additional notes**
None

**Comment by mestiez** [comment]
fixed :)
