### ISSUE TITLE
Physics glitches out at times

### ISSUE THREAD

**Issue by emeraldminer299** [studio-minus/ppg-bugs-and-requests#2202]
**Describe the bug**
Sometimes physics can glitch out, causing objects to glitch all over the place when a lot is happening.

**Clearly describe how to reproduce the bug**
Take a destructible tower or something similar and make it fall over, causing many physics events.

**Mod list**
I would list out mods but considering I have over 20, you can view them in the attached game debug file. Although I did replicate this with all mods disabled too. Needless to say, you do not want to see what my top bar looks like. I'm with you on the opinion that creating it was a mistake.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.26 preview 4
 - GPU: Gigabyte NVIDIA GTX 1660 6GB
 - CPU: AMD Ryzen 3 2200G (I know it's bad, but I'm saving up for an upgrade so you don't have to tell me.)

**Additional notes**
This may not be fixable just because of how Unity deals with physics, but it would be nice if you fix it, assuming it is possible.
But if it isn't then you don't have to worry.

**Comment by emeraldminer299** [comment]
It doesn't look like the debug file actually exported properly so just tell me if you didn't get it and I can upload it here.

**Comment by DindinYT37** [comment]
You didn't even upload it. Also, this was already reported several times and is due to Unity - not People Playground.

**Comment by Drogo-man** [comment]
Tis the unity physics phuckerey, Aka its a unity problem and cant be fixed.

**Comment by mestiez** [comment]
I can never fix this
