### ISSUE TITLE
You cannot delete bricks from broken brick structures

### ISSUE THREAD

**Issue by idiot-with-a-keyboard** [studio-minus/ppg-bugs-and-requests#2218]
**Describe the bug**
You cannot delete bricks from broken brick structures

**Clearly describe how to reproduce the bug**
1. Spawn a brick wall or block
2. Break it
3. Observe undeletable bricks

**Mod list**
No mods

**Comment by ATPGaming** [comment]
I think they are classified as debris

**Comment by Drogo-man** [comment]
Cuz they are particles?

**Comment by MrHushPPG** [comment]
Bricks in the game are accepted as debris. You cannot pick them up but you can remove them with the clear debris button.

**Comment by idiot-with-a-keyboard** [comment]
Pasta Fazul, i am a fool.
Thanks for telling me.
