### ISSUE TITLE
humans glitching

### ISSUE THREAD

**Issue by MiloCullin** [studio-minus/ppg-bugs-and-requests#222]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**

**Comment by idotwaffle** [comment]
the game is literally unplayable with this bug zooi needs to fix it right now

**Comment by fhgb54643689** [comment]
uninstalling and giving bad review because of this terrible bug i cant believe zooi would let this happen

**Comment by Tbskins** [comment]
i don't got this bug is it something with your setting try resetting your settings
