### ISSUE TITLE
save wont load correctly

### ISSUE THREAD

**Issue by hiw353** [studio-minus/ppg-bugs-and-requests#2223]
Ok so the bug is like you have a human and you and got a random armor mod. then you put a human with armor, i saved it load back but its only spawns with guns and a human with no armor.
i tried but i dont know how to

**Mod list**
Lawless 2
Lawless
BloodEnhancedMod
Quick Right Click Options
Cormandy Republic Mod
Crime life USA
Operation LSA Forces: MARSOC
LEGION
Operation LSA Forces: Russia
S&P: Swedish Police
More Vehicles
The Ultimate Car Mod

 - Operating system: windows
 - Game version: normal verison
 - GPU: RTX 2098
 - CPU: intel core i9

**Comment by royalealbert27** [comment]
Chances are that the mod creator doesn't know how to code saving in a contraption

**Comment by DindinYT37** [comment]
Saving Armors never properly worked, either they disappeared or turned into rods. Also, please use the template.

**Comment by hiw353** [comment]
it used to work when i saved them

**Comment by hiw353** [comment]
> Saving Armors never properly worked, either they disappeared or turned into rods. Also, please use the template.

its used to work when i saved them

**Comment by hiw353** [comment]
> Chances are that the mod creator doesn't know how to code saving in a contraption

it used to work fine i think something a problem is removing all of my mods

**Comment by DindinYT37** [comment]
So I have a question. You have a problem with a mod, yet you ask not the mod developer but the game developer? Shouldn't you first ask the mod-maker since it could just be an issue on their end?

**Comment by hiw353** [comment]
> 

i did asked the mod maker, but all of like armor mods are broken for me. its not like one mod its all of the armor mods

**Comment by DindinYT37** [comment]
> > 
> 
> i did asked the mod maker, but all of like armor mods are broken for me. its not like one mod its all of the armor mods

Are you playing on the beta and have you ever thought about the possibility that something that was changed in the beta caused this?

**Comment by hiw353** [comment]
> > > 
> > 
> > 
> > i did asked the mod maker, but all of like armor mods are broken for me. its not like one mod its all of the armor mods
> 
> Are you playing on the beta and have you ever thought about the possibility that something that was changed in the beta caused this?

nope

**Comment by hiw353** [comment]
> > > 
> > 
> > 
> > i did asked the mod maker, but all of like armor mods are broken for me. its not like one mod its all of the armor mods
> 
> Are you playing on the beta and have you ever thought about the possibility that something that was changed in the beta caused this?

i think the causes i removed all of my downloaded mods

**Comment by DindinYT37** [comment]
> i think the causes i removed all of my downloaded mods

So you're saying that you reported the bug that the modded items aren't loading from your saves even though you removed the mods that added those items?

**Comment by hiw353** [comment]
> o you're saying that you reported that the modded items aren't loading from your saves even though

i removed all of my mods due to much mods i redownloaded some of them i saved them with the downloaded mod

**Comment by DindinYT37** [comment]
> > o you're saying that you reported that the modded items aren't loading from your saves even though
> 
> i removed all of my mods due to much mods i redownloaded some of them i saved them with the downloaded mod

The last 8 comments you've left here contradict each other and basically make no sense in relevance to the issue.

**Comment by hiw353** [comment]
> > > o you're saying that you reported that the modded items aren't loading from your saves even though
> > 
> > 
> > i removed all of my mods due to much mods i redownloaded some of them i saved them with the downloaded mod
> 
> The last few comments you've left here contradict each other and basically make no sense in relevance to the is 

the mods that i deleted are broken the cause of the issue is i deleted all of my mods and its causing the problem to my saves.

**Comment by hiw353** [comment]
fuck it im downloading all of the mods

**Comment by DindinYT37** [comment]
> > > > o you're saying that you reported that the modded items aren't loading from your saves even though
> > > 
> > > 
> > > i removed all of my mods due to much mods i redownloaded some of them i saved them with the downloaded mod
> > 
> > 
> > The last few comments you've left here contradict each other and basically make no sense in relevance to the is
> 
> the mods that i deleted are broken the cause of the issue is i deleted all of my mods and its causing the problem to my saves.

Yeah of course your saves that use modded items won't work if you deleted the mods that added those items...

**Comment by hiw353** [comment]
> > > > > o you're saying that you reported that the modded items aren't loading from your saves even though
> > > > 
> > > > 
> > > > i removed all of my mods due to much mods i redownloaded some of them i saved them with the downloaded mod
> > > 
> > > 
> > > The last few comments you've left here contradict each other and basically make no sense in relevance to the is
> > 
> > 
> > the mods that i deleted are broken the cause of the issue is i deleted all of my mods and its causing the problem to my saves.
> 
> Yeah of course your saves that use modded items won't work if you deleted the mods that added those items...

so how i fix it?

**Comment by DindinYT37** [comment]
> > > > > > o you're saying that you reported that the modded items aren't loading from your saves even though
> > > > > 
> > > > > 
> > > > > i removed all of my mods due to much mods i redownloaded some of them i saved them with the downloaded mod
> > > > 
> > > > 
> > > > The last few comments you've left here contradict each other and basically make no sense in relevance to the is
> > > 
> > > 
> > > the mods that i deleted are broken the cause of the issue is i deleted all of my mods and its causing the problem to my saves.
> > 
> > 
> > Yeah of course your saves that use modded items won't work if you deleted the mods that added those items...
> 
> so how i fix it?

You get the mods that added those items, obviously??

**Comment by hiw353** [comment]
> > > > > > > o you're saying that you reported that the modded items aren't loading from your saves even though
> > > > > > 
> > > > > > 
> > > > > > i removed all of my mods due to much mods i redownloaded some of them i saved them with the downloaded mod
> > > > > 
> > > > > 
> > > > > The last few comments you've left here contradict each other and basically make no sense in relevance to the is
> > > > 
> > > > 
> > > > the mods that i deleted are broken the cause of the issue is i deleted all of my mods and its causing the problem to my saves.
> > > 
> > > 
> > > Yeah of course your saves that use modded items won't work if you deleted the mods that added those items...
> > 
> > 
> > so how i fix it?
> 
> You get the mods that added those items, obviously??

I got its still broken

**Comment by DindinYT37** [comment]
> > > so how i fix it?
> > 
> > 
> > You get the mods that added those items, obviously??
> 
> I got its still broken

At this point I can't even be sure if you've actually did what you said.

**Comment by hiw353** [comment]
> > > > so how i fix it?
> > > 
> > > 
> > > You get the mods that added those items, obviously??
> > 
> > 
> > I got its still broken
> 
> At this point I can't even be sure if you've actually did what you said.

im just gonna download all of the mods on people playground

**Comment by hiw353** [comment]
> > > > so how i fix it?
> > > 
> > > 
> > > You get the mods that added those items, obviously??
> > 
> > 
> > I got its still broken
> 
> At this point I can't even be sure if you've actually did what you said.

worked for 2 days its broke again can you help me please

**Comment by DindinYT37** [comment]
> worked for 2 days its broke again can you help me please

Dude. If you remove the mods that you used in your save, obviously it won't work - still.

**Comment by hiw353** [comment]
> > worked for 2 days its broke again can you help me please
> 
> Dude. If you remove the mods that you used in your save, obviously it won't work - still.

no i downloaded them while there in my saves

**Comment by mestiez** [comment]
i cant fix someone else's mod
