### ISSUE TITLE
Corrupted contraptions after deleting mod

### ISSUE THREAD

**Issue by Boskisnoski** [studio-minus/ppg-bugs-and-requests#2224]
It might not be a bug but I need help, I made contraptions that took me alot of time and effort and I care for them alot they would take days to remake. So I made a contraption and posted them onto the workshop a couple hundred people downloaded it but it required mods even though I didn't use any in it. So I delete the mods that it says it needs even though it doesn't directly use them, I don't back up my game ( like a dunce) and I try to load the contraption again and now it says its corrupted, I was just trying to make it vanilla and now its gone, please help. 

download mods then delete them and try and load a contraption

**Mod list**
[Advanced Zombie Injector](https://steamcommunity.com/sharedfiles/filedetails/?id=2815591838)
[Wound Infections](https://steamcommunity.com/sharedfiles/filedetails/?id=2729065060)
[Blood on walls](https://steamcommunity.com/sharedfiles/filedetails/?id=2782471815)
[Status Icons (Fixed)](https://steamcommunity.com/sharedfiles/filedetails/?id=2644689646)
[Ultimate Melee Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2844501696)
[Knifes (Weapon+)](https://steamcommunity.com/sharedfiles/filedetails/?id=2664977773)
[Berserk](https://steamcommunity.com/sharedfiles/filedetails/?id=2636357417)
[Dragon Slayer [BERSERK Mod]](https://steamcommunity.com/sharedfiles/filedetails/?id=2611047032)
[OCM (Fixed, Slightly) (No more MPP TF2 Music Stuff)](https://steamcommunity.com/sharedfiles/filedetails/?id=2585230438)
[Wierd Syringes Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2352420066)
[Apocalypse gear pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2859890572)
[FATAL FOG -FF (FIX)](https://steamcommunity.com/sharedfiles/filedetails/?id=2851509839)
[Pickup Advanced](https://steamcommunity.com/sharedfiles/filedetails/?id=2854748282)
[Adeptus Astartes | A Warhammer 40k Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2856532000)
[Zuccian's Nanomachines](https://steamcommunity.com/sharedfiles/filedetails/?id=2852513095)
[Fire remover button](https://steamcommunity.com/sharedfiles/filedetails/?id=2840340693)
[City - map for PPG](https://steamcommunity.com/sharedfiles/filedetails/?id=2832232690)
[Great Gorge - map for PPG](https://steamcommunity.com/sharedfiles/filedetails/?id=2825329547)
[𝗧𝗛𝗘 𝗛𝗘𝗟𝗜𝗖𝗢𝗣𝗧𝗘𝗥 𝗠𝗢𝗗](https://steamcommunity.com/sharedfiles/filedetails/?id=2824892215)
[Melee Weapon Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2803952558)
[Russian Military Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2779391219)
[Blood eye 4 / VERY RAW BETA / 0.2 / woowz11](https://steamcommunity.com/sharedfiles/filedetails/?id=2221268267)
[Vitals of Steel](https://steamcommunity.com/sharedfiles/filedetails/?id=2678111509)
[Blocksify's Marvel Multiverse](https://steamcommunity.com/sharedfiles/filedetails/?id=2819825536)
[Rooms & Furniture](https://steamcommunity.com/sharedfiles/filedetails/?id=2718595769)
[Modern Firearms](https://steamcommunity.com/sharedfiles/filedetails/?id=2721105504)
[[PA 1.8 - Switching Modes Update] Cormandy Republic Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2792165316)
[Feelings mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2476808016)
[Accurate Resize & Position](https://steamcommunity.com/sharedfiles/filedetails/?id=2789547018)
[Leopard 2A5 2.0 (German Tank)](https://steamcommunity.com/sharedfiles/filedetails/?id=2815976337)
[T-90 2.0 (Russian Tank)](https://steamcommunity.com/sharedfiles/filedetails/?id=2817389224)
[M1A2 Abrams 2.0 (American Tank)](https://steamcommunity.com/sharedfiles/filedetails/?id=2816110716)

**System info (please complete the following information)**
 - Operating system: windows
 - Game version: 1.26 preview
 - GPU:
 - CPU:

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9689629/exported.game.debug.info.md)

**Additional notes**

**Comment by royalealbert27** [comment]
Contraptions with mods requires mod

**Comment by mestiez** [comment]
When a contraption claims it needs a mod, it actually does need that mod. A mod doesn't need to add visible items to be required. Occasionally, mods add behaviour and fail to properly deal with **[serialisation](https://www.studiominus.nl/ppg-modding/tutorials/tutorialSerialisation.html)**. This is not a bug. If you want your contraptions to be free from mods, don't use mods.
