### ISSUE TITLE
blaster layering bug

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2227]
**Describe the bug**
Glowing parts overlap the human body

**Clearly describe how to reproduce the bug**
1. summon human and shiny gun
2. make human grab shiny gun
3. make shiny bits of weapon be in body!!! (other parts dont work for some reason)

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9691380/exported.game.debug.info.md)

**Additional notes**
![thebeatles](https://user-images.githubusercontent.com/104321411/193432062-41cbc4f6-f1e5-4333-87f6-c4eb47a48288.png)
(theres also #1625 !!!!!!!!!!!!!!!!!!!!!!)

**Comment by mestiez** [comment]
fixed :)

**Comment by Drogo-man** [comment]
FINALLY
