### ISSUE TITLE
humans glitching

### ISSUE THREAD

**Issue by MiloCullin** [studio-minus/ppg-bugs-and-requests#223]
whenever I click on a human on the head and attempt to move them, they glitch out and their limbs fly everywhere, iv reinstalled my game and deleted all my mods and its still occuring

I'm not sure what started this bug, I opened the game and it just started doing it

**Comment by MiloCullin** [comment]
its still happening, its now just the ragdoll is glitching out for me 
![image](https://user-images.githubusercontent.com/63679164/134554641-caa1b684-19f1-4678-b21a-945b45eef411.png)

**Comment by idotwaffle** [comment]
## **follow the gosh darn hecking template, it there for a reason**
do you have any settings on that could make this happen, like your physics quality being low or having expanded gore on?

**Comment by DindinYT37** [comment]
# This and #222 is complete nonsense, either make a proper bug report or don't.
