### ISSUE TITLE
New vehicles

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2234]
**Feature description**
Simple, I'd like to see a few new vehicles in the game:

1. Motorcycle
2. Electric Scooter
3. Combine Harvester

**Feature purpose**
These could be some very fun and unique vehicles to add to the game, I know they can already be built but it would be nice to have versions in the base game

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #303
* #369
* #795
* #799
* #1071
* #1549
* #1821
* #1986

**Comment by DindinYT37** [comment]
> I didn't see any boats planes or busses in that suggestion
> 
> "But they're suggesting more vehicles so it's related"
> 
> Not really, they weren't mention in the suggestions

They're still related because it's vehicles, no matter what you say.

**Comment by TeslaCoil9001** [comment]
> > I didn't see any boats planes or busses in that suggestion
> > "But they're suggesting more vehicles so it's related"
> > Not really, they weren't mention in the suggestions
> 
> They're still related because it's vehicles, no matter what you say.

If someone requests an assault rifle, would you list a pistol as a duplicate too?

**Comment by DindinYT37** [comment]
> > > I didn't see any boats planes or busses in that suggestion
> > > "But they're suggesting more vehicles so it's related"
> > > Not really, they weren't mention in the suggestions
> > 
> > 
> > They're still related because it's vehicles, no matter what you say.
> 
> If someone requests an assault rifle, would you list a pistol as a duplicate too?

Not a valid comparison. Vehicles have a few major categories, while weapons have a lot of major categories.

**Comment by ATPGaming** [comment]
stop.
