### ISSUE TITLE
Preview on save spawning

### ISSUE THREAD

**Issue by Saver310** [studio-minus/ppg-bugs-and-requests#224]
**Feature description**
An outline of the selected save will go around your cursor.

**Feature purpose**
This should be done, since spawning custom contraptions like Destructible Towers, get stuck in the floor or fly.

**Additional context**
None

**Comment by idotwaffle** [comment]
this is already a thing...
doesn't work with builds saved before it was added though

if you're trying to spawn something from an old version just pause the game, spawn it, move it to where you want it and then unpause
you could also just save the building again and then it'll have the outline

**Comment by mestiez** [comment]
This is already in the game.
