### ISSUE TITLE
an activation detector

### ISSUE THREAD

**Issue by fatoastcatbruh** [studio-minus/ppg-bugs-and-requests#2245]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by DindinYT37** [comment]
So, how about actually filling out the template?

**Comment by Dawid23-Gamer** [comment]
Activation detector, so an object that detects if it was activated to then send an activation signal?
Sounds like every object in this game to me, ngl, but I might lack context from the missing template info.
