### ISSUE TITLE
steamworkshop not responding

### ISSUE THREAD

**Issue by lechkingofdead** [studio-minus/ppg-bugs-and-requests#225]
**Describe the bug**
a simple issue of steamworkshop not only failing to show BUT im also not able to see any new subs mod or otherwise, i have no idea what in the world is wrong BUT i hope its on the game and not steam end.

**Comment by UniDuki** [comment]
I don't see how the steam workshop not loading is a problem with the game, this is obviously a problem with steam.

**Comment by mestiez** [comment]
Cannot reproduce
