### ISSUE TITLE
Androids should bleed again

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2254]
**Feature description**
Androids should bleed oil again when heavily damaged. It would probably be altered to make it harder to get them to bleed, like maybe having to use a shotgun at point-blank.

**Feature purpose**
It was funny when androids bled oil in the past and I'm not sure why they removed it

**Additional context**
Thank you for the inspiration #2251

**Comment by DindinYT37** [comment]
What inspiration, what I see is just you taking a comment of someone else and turning it into your request again.

**Comment by ATPGaming** [comment]
> What inspiration, what I see is just you taking a comment of someone else and turning it into your request again.

I got inspired by it so I made it a separate issue. Do you want me to close this?

**Comment by DindinYT37** [comment]
> > What inspiration, what I see is just you taking a comment of someone else and turning it into your request again.
> 
> I got inspired by it so I made it a separate issue. Do you want me to close this?

No, I just wouldn't say that it's inspiration.

**Comment by ATPGaming** [comment]
also sucks
