### ISSUE TITLE
Snap to grid

### ISSUE THREAD

**Issue by DieFluoro** [studio-minus/ppg-bugs-and-requests#2268]
**Feature description**
Activated as a setting in options, does exactly what the name suggests, allows players to place items with precision. I would think it should only take effect when time is paused so when time is resumed things may be moved as regular. There should be different options between 1/10 meter, 1/2, and 1 meter, snapping accuracy.

**Feature purpose**
allows players to place items with precision, would make building just a little more pleasant and organized.

**Additional context**
Only applies to objects that are selected, when time is paused.

**Comment by DieFluoro** [comment]
Edit: should also apply to rotating objects, introduce a radial menu as an alternative option to typing the degrees. This would allow players to visualize what an angle will look like or does look like, so we can easier decide the very specific degrees that we desire. Should come in 1, 5, and 10 degree snapping options.

**Comment by DindinYT37** [comment]
Literally, already in the game, just hold ALT.

**Comment by DieFluoro** [comment]
im so sorry skull face emoji

**Comment by Drogo-man** [comment]
JIST HOLD ALT

**Comment by DindinYT37** [comment]
> JIST HOLD ALT

Why do you insist on commenting on something that was already resolved?

**Comment by Drogo-man** [comment]
I see idiotic post and i just comment.

**Comment by DindinYT37** [comment]
> I see idiotic post and i just comment.

Understandable.
