### ISSUE TITLE
Adrenaline does not properly affect the blood.

### ISSUE THREAD

**Issue by phenon21** [studio-minus/ppg-bugs-and-requests#227]
If you inject a syringe with adrenaline into a wounded person, then his bleeding will not stop but will increase, although in real life it should be the opposite.

**Comment by idotwaffle** [comment]
# F O L L O W   T H E   T E M P L A T E
also this is a feature request

**Comment by mestiez** [comment]
This is because adrenaline (in-game) increases heart rate, which increases blood pressure, which makes bleeding more severe. It is not a bug.
