### ISSUE TITLE
Bullpup

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2279]
**Feature description**
Add a bullpup assault rifle, it likely would be a FAMAS F1. It would have more bullet velocity and a slightly higher fire rate than the regular assault rifle.

**Feature purpose**
Even though it is similar to the assault rifle, the assault rifle does not give off the bullpup feeling.

**Additional context**
![image](https://user-images.githubusercontent.com/109692890/196059502-dda466dc-c6ae-4adc-8dc4-a91134a46519.png)

**Comment by TeslaCoil9001** [comment]
1. This is something a mod could do easily. If you were passionate enough, YOU could do it too
2. A duplicate of #1640
3. You might like [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2503670951)

**Comment by ATPGaming** [comment]
> 1. This is something a mod could do easily. If you were passionate enough, YOU could do it too
> 2. A duplicate of ["Bullpup Assault Rifle" #1640](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1640)
> 3. You might like [this mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2503670951)

1. True
2. Also true
3. I will try it

**Comment by DindinYT37** [comment]
Man keeps making duplicates of requests that were already added by mods.

**Comment by ATPGaming** [comment]
> Man keeps making duplicates of requests that were already added by mods.

Hey at least I close them now

**Comment by DindinYT37** [comment]
> > Man keeps making duplicates of requests that were already added by mods.
> 
> Hey at least I close them now

How about you "at least" check if a duplicate already exists?
