### ISSUE TITLE
New syringe

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#228]
**Feature description**
a new syringe in the biohazard category which will only heal visual wounds and nothing else

**Feature purpose**
it gets to be an annoyance when you have a dead body you need to be not mangled apart from accidently hitting it on something so i suggest adding something like this

**Additional context**
None

**Comment by idotwaffle** [comment]
just revive the human and death syringe it or snap it's neck. a syringe that only heals visually makes no sense anyway

**Comment by fhgb54643689** [comment]
> just revive the human and death syringe it or snap it's neck. a syringe that only heals visually makes no sense anyway

fair enough
