### ISSUE TITLE
Death detector

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2280]
**Feature description**
Add a death detector that activates when something dies in front of it

**Feature purpose**
Death based contraptions, simple

**Comment by DindinYT37** [comment]
So you're telling me you don't know how to invert the signal of a life detector?

**Comment by ATPGaming** [comment]
> So you're telling me you don't know how to invert the signal of a life detector?

no

**Comment by DindinYT37** [comment]
> > So you're telling me you don't know how to invert the signal of a life detector?
> 
> no

If you really wanted, you could achieve this with an AND-Gate of a normal detector and an inverted life detector.

**Comment by ATPGaming** [comment]
https://github.com/studio-minus/ppg-bugs-and-requests/issues/598

**Comment by DindinYT37** [comment]
> #598

You can't just mention an issue like that, you have to at least make it clear it's a duplicate of said issue. For example, `Duplicate of #598`.
