### ISSUE TITLE
Oxygen mask/Breathing machine

### ISSUE THREAD

**Issue by kinlee2352** [studio-minus/ppg-bugs-and-requests#2283]
**Feature description**
The oxygen mask would provide oxygen to the human keeping them alive, preventing them from getting brain damage, and possibly allowing them to breathe underwater, I'm not sure about that one though.

**Feature purpose**
Allowing to provide medical attention if the defib isn't working
It will set the oxygen bar to 75% to 50%
Prevents brain damage when humans are incapacitated

**Additional context**
I wish there were more ways to revive a human other than a life syringe.
More medical items would help that.

**Comment by royalealbert27** [comment]
Water breathing syringe + there's a gun that heals

**Comment by bibbybabby** [comment]
Cardiopulmonary Bypass Machine

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #412
* #423
* #541
* #610 
* #787 
* #1085 
* #1220 
* #1709 
* #1916

Also, the Cardiopulmonary Bypass Machine pretty much does what you described as "breathing machine".

**Comment by kinlee2352** [comment]
> Water breathing syringe + there's a gun that heals

I was hoping there was an alternative solution without a syringe
Although that'd work well.

**Comment by kinlee2352** [comment]
> Duplicate of or Related to:
> 
> * [Oxygen/Blood/Circulatory Rework, Volume no2 #412](https://github.com/studio-minus/ppg-bugs-and-requests/issues/412)
> * [Gases #423](https://github.com/studio-minus/ppg-bugs-and-requests/issues/423)
> * [Space and Oxygen #541](https://github.com/studio-minus/ppg-bugs-and-requests/issues/541)
> * [Balloons can store liquids + maybe helium? #610](https://github.com/studio-minus/ppg-bugs-and-requests/issues/610)
> * [Oxygenator #787](https://github.com/studio-minus/ppg-bugs-and-requests/issues/787)
> * [oxygen tanks or somethin #1085](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1085)
> * [Depletable Oxygen Tank/Syringe #1220](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1220)
> * [Expansion of the respiratory system #1709](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1709)
> * [Oxygen tank or other gas tanks #1916](https://github.com/studio-minus/ppg-bugs-and-requests/issues/1916)
> 
> Also, the Cardiopulmonary Bypass Machine pretty much does what you described as "breathing machine".

After I checked this, yeah. It does provide complete oxygen to the person.
I really wish I'd checked that before making this post.
