### ISSUE TITLE
Keybind to make humans do animations

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2287]
**Feature description**
Add keybinds that will make the selected human walk stumble cower and sit.

**Feature purpose**
This would be useful for videos and just as a shortcut so you don't have to open the context menu

**Comment by TeslaCoil9001** [comment]
> mods mods mods mods mods mods https://steamcommunity.com/app/1118200/discussions/0/5635717345348858984/?tscn=1665951823
> 
> don't reply that this should be a vanilla feature challenge

Send me the mod like then...

**Comment by royalealbert27** [comment]
> > mods mods mods mods mods mods https://steamcommunity.com/app/1118200/discussions/0/5635717345348858984/?tscn=1665951823
> > don't reply that this should be a vanilla feature challenge
> 
> Send me the mod like then... If you can't that's why it should be a vanilla feature
Fuck, wrong link, https://steamcommunity.com/sharedfiles/filedetails/?id=2849749019&searchtext=Quick
https://steamcommunity.com/sharedfiles/filedetails/?id=2849749019&searchtext=Quick
https://steamcommunity.com/sharedfiles/filedetails/?id=2849749019&searchtext=Quick
https://steamcommunity.com/sharedfiles/filedetails/?id=2849749019&searchtext=Quick

**Comment by DindinYT37** [comment]
Why the same mod four times?

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #1228

**Comment by ATPGaming** [comment]
sorry am late
