### ISSUE TITLE
Some items should make a whoosh sound when swung quickly.

### ISSUE THREAD

**Issue by QFBlwPNT7tYqk0XGH5r0** [studio-minus/ppg-bugs-and-requests#2292]
**Feature description**
Basically, if you swing a light item very fast in the game, it should make a whoosh sound like in real life, if you've ever picked up a stick and swung it fast, you know what I mean.

**Feature purpose**
Realistic gameplay

**Additional context**
No additional context

Translated from Russian

**Comment by username90001** [comment]
it is not good idea because it may cause problems with high speed things like rockets or cars

**Comment by DindinYT37** [comment]
> it is not good idea because it may cause problems with high speed things like rockets or cars

This is quite simply incorrect. First, it wouldn't be loud enough to drown out the sound of a rocket or supercar. Second, there can be an upper-limit to simply have it not happen if the speed exceeds a specific amount.
