### ISSUE TITLE
 anti-material

### ISSUE THREAD

**Issue by QFBlwPNT7tYqk0XGH5r0** [studio-minus/ppg-bugs-and-requests#2294]
**Feature description**
what I'm asking for is a .50 anti-materiel rifle that can shatter brick walls and bullets can knock back crowds of people.

**Feature purpose**
It would be fun to have something that is not explosive to destroy the buildings.

**Additional context**
Not.

Translated from Russian

**Comment by ATPGaming** [comment]
Duplicate of #2055 but it's a good idea to make it designed to destroy brick walls

**Comment by DindinYT37** [comment]
> Duplicate of #2055 but it's a good idea to make it designed to destroy brick walls

I'm certain that was a given.

**Comment by Drogo-man** [comment]
The sniper is an anti material rifle.
