### ISSUE TITLE
Would really like to see these in the game, it would make it that much better to play

### ISSUE THREAD

**Issue by xXXGraveDiggerXx** [studio-minus/ppg-bugs-and-requests#2299]
I would love RayTracing, its a game thats so great and also simple that anyone can run raytracing if they have a 20 series or even better, and i would love like love to have a multiplayer or something.

**Comment by bibbybabby** [comment]
1. please follow the template
2. please do not multirequest
3. multiplayer will never happen
4. how will raytracing work in this game?

**Comment by DindinYT37** [comment]
Please use the template, and don't multi-request. Not to mention that multiplayer has been said multiple times to never happen – Ray-tracing doesn't have much or even any use in this game.

**Comment by Drogo-man** [comment]
This guy check all the boxes in the "this shit won't get added" list.

**Comment by DindinYT37** [comment]
> This guy check all the boxes in the "this shit won't get added" list.

Not all of them, he didn't put his entire request in the title – and most importantly, he wrote something and didn't just make an unchanged template-issue.
