### ISSUE TITLE
Blood vessel wire pressure

### ISSUE THREAD

**Issue by Cboyjet4** [studio-minus/ppg-bugs-and-requests#230]
**Feature description**
Blood pressure should actually propel blood through blood vessel wires, allowing blood flow/pressure to go through detached limbs with the adequate blood vessel wires going in and out. 

**Feature purpose**
Allowing for limbs to be partially kept "alive" by allowing blood flow to properly go through them, allowing for possibly more freakish creations in the future. (Hooking up someone else to pump blood for someone else, same for limbs, etc.)

**Additional context**
![Sugggestion](https://user-images.githubusercontent.com/71295203/135568074-26ab773f-8537-4a04-a1c7-11174e8e01ee.png)

**Comment by fhgb54643689** [comment]
Great idea 10/10

**Comment by mestiez** [comment]
I experimented with blood vessel wires transferring blood pressure before, but I decided not to implement it for some reason. The liquid system has changed since then so I'll give it another shot

**Comment by Cboyjet4** [comment]
> I experimented with blood vessel wires transferring blood pressure before, but I decided not to implement it for some reason. The liquid system has changed since then so I'll give it another shot

Alright, thanks for the reply,

**Comment by Cboyjet4** [comment]
> It doesn't keep detached limbs alive. Detached limbs cannot be reconnected.

(LATE RESPONSE) Huh, weird, does it have to do with the way humans consume "oxygen" in the sense that only attached limbs get "oxygen" or am I completely wrong?
Realistically, attaching blood vessels to a human would likely keep the limb alive, oxygen and nutrients are stored and carried in the blood, of course, maybe this could be fixed using some cheating, though I'm not the dev here.

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/139529893-384bb0ce-2e7c-4b55-acf5-7c57be16afa8.png)

**Comment by Cboyjet4** [comment]
OOOH, that makes so much more sense lol, thanks for the reply.
