### ISSUE TITLE
Some objects making humans stuck in detail or non detail view.

### ISSUE THREAD

**Issue by Sekaji0** [studio-minus/ppg-bugs-and-requests#2301]
Some objects randombly glitch the game and make humans stuck with the green bars or without even if you switch view modes.

The bug is created by having humasp spawned first then spawning other random objects and then if you spawn another human and toggle detail view.

**Mod list**
-Generic Jojo Mod Remastered
-Everything colourable
-Liquid logic
-Requiem human V2
-Torture mod
-Make anything invisible
-Zombie pack
-PPG: Civilians
-Improved Madness PACK
-PPG Slayer
-Limb attachements
-Functional Terminaor mod
-MeleeWeaponPack
-Melee Weapons
-Melon Playground
-SimplePortals
-More Humans Mod
-Human Tiers+
-Naruto Pack
-Famous people pack
-Quick Right click options
-One Piece mod
-Wheelchair
-flipping heck
-Android injectors
-Taser
-ExplosiveMod
-Human Tiers
-PowersMod
-Chemica Warfare
-Skyttles syringe mod

  System info:
 - Operating system: Windows 11 Pro
 - Game version: 1.26
 - GPU: NVIDIA® GeForce® GTX 1660Ti
 - CPU: AMD Ryzen 7 4800H with Radeon Graphics   2.90 GHz

**Additional notes**
![20221028025452_1](https://user-images.githubusercontent.com/116851926/198420505-a53b427e-21e9-4298-a4af-e0934b465937.jpg)

**Comment by royalealbert27** [comment]
It's your make everything invisible mod, it fucks it up

**Comment by Drogo-man** [comment]
It's the "make everything invisible mod" that does this.

**Comment by ATPGaming** [comment]
I'd recommend closing the bug report
