### ISSUE TITLE
Propane tank

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2308]
**Feature description**
Add a heavy metal propane tank that will explode when shot 

**Feature purpose**
More miscellaneous objects to murder with

**Comment by bibbybabby** [comment]
sounds like a red barrel reskin to me

**Comment by ATPGaming** [comment]
> sounds like a red barrel reskin to me

Okay, how about this? It would be heavier and can ONLY explode by impact, not being shot?

**Comment by DindinYT37** [comment]
> > sounds like a red barrel reskin to me
> 
> Okay, how about this? It would be heavier and can ONLY explode by impact, not being shot?

So, a shot is not an impact, you say?

**Comment by ATPGaming** [comment]
ok this sucks
