### ISSUE TITLE
Saving function bug

### ISSUE THREAD

**Issue by SemenovA1exander** [studio-minus/ppg-bugs-and-requests#231]
I'm talking about saving the contraptions in the "local" tab of items.
I installed a mod from workshop that adds DC characters (mostly reskinned humans) and while some of them were successfully saved, the others consistently drop error "<insert name> saved with errors" and nothing gets added to the local tab. I tried resaving characters that I have previously saved and they do not fail. So some characters consistently fail saving while the other save just fine.
![1deletethis](https://user-images.githubusercontent.com/54928397/135578502-007d5c50-6e11-4549-869c-7b180ed4dfed.png)

**Comment by fhgb54643689** [comment]
**use the template** and also that sounds like a issue with the mod not the game

**Comment by idotwaffle** [comment]
this happens with lots of mods

**Comment by mestiez** [comment]
Please follow the template.
