### ISSUE TITLE
New Animation: Kneel

### ISSUE THREAD

**Issue by Brostrod** [studio-minus/ppg-bugs-and-requests#2316]
**Feature description**
It's a new animation where it makes the character kneel

**Feature purpose**
Gives more poses for character and also helpful for rp

**Additional context**
He look a bit goofy but this is basically what i mean
![image](https://user-images.githubusercontent.com/88124903/198860914-567d1717-0c5d-4857-95d3-32bdc72fd323.png)

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #182
* #255
* #454
* #743
* #1026
* #1826

**Comment by ATPGaming** [comment]
I'd advise you to close this issue now

**Comment by Drogo-man** [comment]
Goofy ahh animation
