### ISSUE TITLE
Physical health inspector

### ISSUE THREAD

**Issue by Cboyjet4** [studio-minus/ppg-bugs-and-requests#232]
**Feature description**
A physical/compact version of the typical context menu human inspect element.
Inspector could show injuries of that specific limb on a screen or hologram when hovering over it. (broken bones, bruises, gunshots, (Internal bleeding???) 

**Feature purpose**
A physical object/scanner for inspecting the damage someone has, for roleplaying and doctoring sake.

**Additional context**
![deadg](https://user-images.githubusercontent.com/71295203/135673817-577eb6ee-c25c-470a-8678-e7b717ece764.PNG)
mockup i made in paint

**Comment by LaCumbiaDelCoronavirus** [comment]
this will seem pretty fun to use if its ever added.

**Comment by Cboyjet4** [comment]
Closed because partially useless, I'll find a better way to suggest something similar.
