### ISSUE TITLE
Make things move easier in lava

### ISSUE THREAD

**Issue by TeslaCoil9001** [studio-minus/ppg-bugs-and-requests#2323]
**Feature description**
Make things able to move in lava faster and with less drag so it feels more like liquid than very hot quicksand

**Feature purpose**
Would make lava actually fun to use

**Comment by bibbybabby** [comment]
Lava is essentially liquid rock, of course it's going to be dense

**Comment by royalealbert27** [comment]
Lava is a very hot quicksand

**Comment by DindinYT37** [comment]
Lava has a density of 2.5-2.7 g/cm³, water only has a density of 1 g/cm³.

**Comment by Drogo-man** [comment]
Basically: water = very liquidy, lava = hot jelly.

**Comment by Dawid23-Gamer** [comment]
Imagine not knowing irl liquid physics 💀

**Comment by TeslaCoil9001** [comment]
Ok ok
