### ISSUE TITLE
All the settings except for drag object got removed.

### ISSUE THREAD

**Issue by barneyhl1** [studio-minus/ppg-bugs-and-requests#233]
It says in the title, all the settings in options got removed, except for drag object which is set to mouse0

I do not know how to reproduce the bug, I just started it up one day and it didn't work so I checked settings and saw that.

I have no mods currently on.

 - Operating system: Windows 10
 - Game version: 1.21.3
 - GPU: Unkown
 - CPU: Unkown

Additional Notes: I have gotten this through familiy sharing and it was working just fine for over  3 months until it just stopped, I had 110.5 hours on the game before it stopped working.

**Comment by idotwaffle** [comment]
This happened randomly for me once and I just restarted my pc and was fine

**Comment by barneyhl1** [comment]
I tried restarting my PC and it didn't help at all, I tried uninstalling then reinstalling the game and it didn't work either.

**Comment by DavidCo113** [comment]
Try deleting ControlScheme.json at `%ProgramFiles(x86)%\Steam\steamapps\common\People Playground`
