### ISSUE TITLE
Beta Z-Fighting

### ISSUE THREAD

**Issue by nourelar** [studio-minus/ppg-bugs-and-requests#2330]
**Describe the bug**
Contraptions spawned in made before 1.26 beta have z-fighting.

**Clearly describe how to reproduce the bug**
Depends on what contraptions your spawning, but some contraptions will have very visible z-fighting.

**Mod list**
Doubt if its a mod issue

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.26 beta
 - GPU: GTX 1080 TI  
 - CPU: I7-3770

**Comment by mestiez** [comment]
that is odd because these objects are sprites and are always properly sorted. what objects specifically cause z-fighting?

**Comment by nourelar** [comment]
I don't really see the problem anymore but most parts that it happened with were rods, brick walls or cubes, and most decorative items, I did see one instance of certain machines z-fighting as well.
