### ISSUE TITLE
Large objects lag the game/lower fps

### ISSUE THREAD

**Issue by LaCumbiaDelCoronavirus** [studio-minus/ppg-bugs-and-requests#234]
**Describe the bug**

**Clearly describe how to reproduce the bug**
With this building, https://steamcommunity.com/sharedfiles/filedetails/?id=2618160196, loading it into my game
lowers fps dramatically (still to a playable rate) but scaling down the entire thing will increase my fps nearer to what it was 
before i added the building.

**Mod list**
Item Plus, The piercer, Fishing Rod, Facility mod, Functional Devices mod, a crap ton of damage, fish mod, water flask, powerful and weak weapons, object editor, skull stick shift, airpod shotty, OCM (overly complicated mod), Headcrabs,FleasyWeapons - rifles, Counter-Strike mod, Liquid-related machinery, injectable flasks mod, quick right click options,  Animated Sniper Rifles+, Animated Weapons+, quality of life items, Generators+, Greenbrick industries, Iraq War mod,  Per pixel destruction,tethers, Hold k to make wires invisible, Map blocks. all mods are enabled

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: v1.21.3
 - GPU: GeForce RTX 2060
 - CPU: AMD Ryzen 5 3600 6core processor

**Comment by fhgb54643689** [comment]
skill issue

**Comment by LaCumbiaDelCoronavirus** [comment]
> LOL. It's like complaining that "My PC does not run Red Dead Redemption 2." It's your hardware man... It's a curse in all sandbox games. You only place as much things as your PC can bear, or just get a better hardware. I got no problems on my side.

Yea dude 188 objects...

**Comment by mestiez** [comment]
Closed because I never got an answer lmao
