### ISSUE TITLE
Firearm with a pointy barrel

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2341]
**Feature description**
Literally a gun but with a bayonet or just a pointy barrel that can stab, most probably a musket but it can be any other weapon type

**Feature purpose**
It is very fun and brutal to stab and shoot someone at the same time

**Additional context**
Something like Assassin's Creed III where you can approach an enemy from behind with a musket and the main character impales the guard and can shoot the other guard because the gun sticks through them

**Comment by Drogo-man** [comment]
spike gun can do that.

**Comment by bibbybabby** [comment]
> spike gun can do that.

Yes but it's not very practical, either the spikes go through but lose momentum from touching the human or they impale the human and make him fly off the gun

**Comment by ATPGaming** [comment]
You can attach an elongated knife to a barrel with a rigid wire and phase link ya know

**Comment by Drogo-man** [comment]
Ah yes, that was the first thing i did when i got the game.

**Comment by bibbybabby** [comment]
> You can attach an elongated knife to a barrel with a rigid wire and phase link ya know

That just means that every human will have to be phase linked, and that means funny passages and no buttstock whacks, not to mention that would be very time consuming and just a disaster

**Comment by Drogo-man** [comment]
No, phase link the bayonet and the gun.

**Comment by bibbybabby** [comment]
> No, phase link the bayonet and the gun.

It already has no collision when it is rigid wired

**Comment by Drogo-man** [comment]
unless its with rigid wire

**Comment by bibbybabby** [comment]
pointless to upkeep because gun attachments now exist

**Comment by Drogo-man** [comment]
I own a musket for home defense.
