### ISSUE TITLE
Mechanical things don't work properly when activated from a fuse

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2343]
**Describe the bug**
Fuse breaks things by activating them

**Clearly describe how to reproduce the bug**
1. make something mechanical
2. hook it up to a fuse
3. activate fuse
4. cry

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9931513/exported.game.debug.info.md)

**Additional notes**

https://user-images.githubusercontent.com/104321411/199790012-bf7d3b7e-5700-4341-85c1-5eeb9bdecec8.mp4

**Comment by DindinYT37** [comment]
Not a bug, the Detector was deactivated. The fuse sent a green signal through the detector, which activated it - due to it being sent **through** the detector, it simply also activated the activation toggle.

**Comment by bibbybabby** [comment]
> Not a bug, the Detector was deactivated. The fuse sent a green signal to the detector, which activated it – and due to it being sent **through** the detector, it also went into the activation toggle and toggled it.
> 
> Edit: If you meant that even though the detector was detecting something, therefore turning off the toggle, that's because the signal of the detector runs **through** the toggle into the gun directly.

forgot to show that activating the detector through the key bind does not make it go through the detector

**Comment by mestiez** [comment]
> activating the detector through the key bind does not make it go through the detector
this is intentional

i dont think there is a bug here
