### ISSUE TITLE
Resize Sharp Object

### ISSUE THREAD

**Issue by Happy0133** [studio-minus/ppg-bugs-and-requests#2350]
Why does this not work? The resized object wont stab in anything.

https://user-images.githubusercontent.com/117456660/200119881-2ccfffa4-e8eb-4970-b463-e0ecb66ed514.mp4

**Comment by Drogo-man** [comment]
Yeah, when is this gonna get fixed?

**Comment by DindinYT37** [comment]
Please use the template.

**Comment by PossiblyRemember** [comment]
duplicate or related to
- https://github.com/studio-minus/ppg-bugs-and-requests/issues/1335
- https://github.com/studio-minus/ppg-bugs-and-requests/issues/2063

**Comment by Happy0133** [comment]
Sorry that I ask but...
What is a template?

**Comment by bibbybabby** [comment]
> Sorry that I ask but... What is a template?

The thing that is automatically added when you click the "new issue" button and then click "get started", you are supposed to fill it out with information

**Comment by Happy0133** [comment]
ah thx man

**Comment by Squibard** [comment]
nooo its not planned :(
