### ISSUE TITLE
Menu sounds are affected by distant sound effects

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2352]
**Describe the bug**
The menu buttons are affected by sound effects

**Clearly describe how to reproduce the bug**
Literally zoom out and go to the menu

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9944295/exported.game.debug.info.md)

**Additional notes**

https://user-images.githubusercontent.com/104321411/200131283-be212c38-e71a-4673-8536-7046f18d6dd6.mp4

**Comment by royalealbert27** [comment]
i think that's intentional cuz of LOREEEE!!!!

**Comment by mestiez** [comment]
Duplicate of #716
