### ISSUE TITLE
Loch Ness Monster

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2354]
**Feature description**
Add the Loch Ness Monster, a creature from Scottish folklore. In People Playground, the Loch Ness Monster would be relatively massive, about the size of a truck. It would be able to float on the surface of the water and use its long neck to reach humans from far away and kill them. 
![image](https://user-images.githubusercontent.com/109692890/200192568-328dfdb4-fc5c-4016-965e-58f297d84aa3.png)

**Feature purpose**
We don't have any sea/amphibious creatures in the game, and this would add it and more variety. Also, come on, the Loch Ness Monster is really cool.

**Comment by tututoller** [comment]
I am sorry but I don't think that this would fit the game considering that it is pretty much set in a inhumane testing grounds.
