### ISSUE TITLE
humans and android layering system is different

### ISSUE THREAD

**Issue by HeyDaewo** [studio-minus/ppg-bugs-and-requests#2357]
**Describe the bug**
you can layer each humans parts

but you can't really change layering on the android parts 

basically when i move the layering on the android the whole android part moves
**Clearly describe how to reproduce the bug**
set the android layering system as the same as the human

**Mod list**
has nothing to do with mods cause i don't use any mods while making stuff expect press K to make wires invis

**System info (please complete the following information)**
 - Operating system: windows11
 - Game version:  1.26 preview
 - GPU: NVIDIA GeForce RTX 3050 Laptop GPU
 - CPU: AMD Radeon TM Graphics

**Additional notes**

**Comment by mestiez** [comment]
this is no longer the case
