### ISSUE TITLE
chainsaw removes wooden struts

### ISSUE THREAD

**Issue by LaCumbiaDelCoronavirus** [studio-minus/ppg-bugs-and-requests#236]
**Feature description**
Chainsaws to remove wooden struts or anything similar.

**Feature purpose**
Chainsaws, when sawing into anything connected to a wooden strut, would destroy the wooden strut.

**Additional context**
holaespanol

**Comment by TamasB14** [comment]
Huh?... why would that be a thing? If there was a metal thing connected to a wooden strut you mean it'd had to cut the wooden strut? Maybe only if it's cutting the wooden part, but still... Why only wooden strut? I'm pretty sure it'd be useless to add one feature to only one strut.
