### ISSUE TITLE
Removing everything on Substructure

### ISSUE THREAD

**Issue by Toerac** [studio-minus/ppg-bugs-and-requests#2362]
**Describe the bug**
Removing everything on Substructure

**Clearly describe how to reproduce the bug**
1. Open map
2. Move the camera to the elevator
![image](https://user-images.githubusercontent.com/93346023/200592740-152bfe2b-0ccc-4360-afae-b37fac603ce9.png)
3. Create any object next to the call button
4. Select object and call button
5. Remove

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9962161/exported.game.debug.info.md)

**Comment by mestiez** [comment]
I can't reproduce this

**Comment by mestiez** [comment]
still not able to reproduce this
