### ISSUE TITLE
Bug - Heart beating on dead and decomposed human

### ISSUE THREAD

**Issue by henriquelmeeee** [studio-minus/ppg-bugs-and-requests#2373]
**Describe the bug**
after a human dies, when shooting with a shotgun (which makes him explode), the heart appears beating, but he is already dead.

**Clearly describe how to reproduce the bug**
you can just kill a human, wait for his heart to stop beating and then shoot him until it explodes, you will see the heart working in a dead.

**Mod list**
All mods are disabled

**System info (please complete the following information)**
 - Operating system: Windows 8.1
 - Game version: 1.26 preview 4
 - GPU: GTX 550Ti
 - CPU: i5 3570 w/ Turbo Boost enabled

**Additional notes**
![image](https://user-images.githubusercontent.com/86432400/201070868-b9b592a5-4fac-4f62-99ac-8624d8d8a24c.png)

**Comment by DindinYT37** [comment]
I'm pretty sure that's from a mod.

**Comment by henriquelmeeee** [comment]
> 

its from this option
![image](https://user-images.githubusercontent.com/86432400/201075436-f564d1b6-3b13-4f96-b552-bf24765413c2.png)

**Comment by henriquelmeeee** [comment]
i had disabled all mods and it continues, weird

Now it doesn't continue anymore, I thought it was from the update

**Comment by DindinYT37** [comment]
Yeah, also I can confirm with certainty it's not because of the "Dismemberment loose tissue" setting.

**Comment by royalealbert27** [comment]
did you make a mod bug report in the game bug report

**Comment by henriquelmeeee** [comment]
> royalealbert27

I can't delete that

**Comment by venixals** [comment]
its a mod and its supposed to be like that, its still beats after a few seconds of the guy being dead.

**Comment by mestiez** [comment]
Not vanilla
