### ISSUE TITLE
Activated Energy Sword generates backwards thrust

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2377]
**Describe the bug**
Energy Sword flies backwards when activated

**Clearly describe how to reproduce the bug**
Turn on the Energy Sword

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/9984444/exported.game.debug.info.md)

**Additional notes**

https://user-images.githubusercontent.com/104321411/201201227-90c5605b-7104-4746-9525-eb8f0ee81071.mp4

**Comment by Drogo-man** [comment]
Isn't this intentional?

**Comment by bibbybabby** [comment]
> Isn't this intentional?

I don't see it being intentional

**Comment by Drogo-man** [comment]
It would make sense since if it's shooting out plasma really fast out the front, it's should move backwards due to newtons 3rd law of gravity.

**Comment by DindinYT37** [comment]
> It would make sense since if it's shooting out plasma really fast out the front, it's should move backwards due to newtons 3rd law of gravity.

I'm pretty sure that wasn't the thought behind this.

**Comment by Drogo-man** [comment]
But it makes sense?

**Comment by DindinYT37** [comment]
> But it makes sense?

I still doubt that it was the thought behind this.

**Comment by mestiez** [comment]
Not a bug. Though it would make a little more sense if it would generate some force when turning off as well

**Comment by Drogo-man** [comment]
I told you so.

**Comment by DindinYT37** [comment]
> I told you so.

You did not, really. You told us what you think was the reason behind this, which it doesn't seem to have been, as zooi would've already added that some force would also be generated when it turns off. Also, I think you misunderstand the difference between "No, you're wrong." and "I doubt that was the thought behind it.".

**Comment by Drogo-man** [comment]
Okay Shakespeare.

**Comment by bibbybabby** [comment]
Oh boy another argument
