### ISSUE TITLE
Simple MP

### ISSUE THREAD

**Issue by alikeobservant** [studio-minus/ppg-bugs-and-requests#238]
**Feature description**
A very simple multiplayer, might seem pretty far fetched but I think this might work.
Really all it is, is that you can see the other person mouse on your screen, or any other placeholder object. It can interact with objects you spawn, and stuff like that. I don't know the first thing about developing but I think it'd be a nice addition to people playground to have an option to player with 2 people.
**Feature purpose**
The purpose is so that people can simply, play together. Having the ability to work together to create contraptions or just plain screwing around would be like gmod but 2D.

**Additional context**
No other context

**Comment by UniDuki** [comment]
#194 "This is definitely never happening"

**Comment by alikeobservant** [comment]
Aw shit
