### ISSUE TITLE
Magnet that attracts everything

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2394]
**Feature description**
Add some sort of magnet that attracts any item

**Feature purpose**
It would be fun to just suck everything into one place like a black hole

**Comment by royalealbert27** [comment]
pull power

**Comment by Drogo-man** [comment]
I think he means it attrects not Magnetic things.

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #156
* #700
* #2006
