### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by Karmy8** [studio-minus/ppg-bugs-and-requests#2395]
Multiplayer:
Add a button that lets you create a server and connect with a friend.
Since there's no character you will be able to see your friends name on steam right next to their cursor.
Some things to add in a multiplayer feature:
- See what they spawn.
- See what they delete.
- See what properties they modify like: object temperature, object angle, etc.
- See how they arrange the wires.
I think that everyone wants a multiplayer feature.

**Comment by ATPGaming** [comment]
Please use the template

Duplicate of:
2395
2299
2189
1055
922
784
475
238
194

**Comment by Drogo-man** [comment]
Not you too

**Comment by royalealbert27** [comment]
developer said it won't ever get added + already been suggested since the dawn of time
