### ISSUE TITLE
Mod categories turn to one category

### ISSUE THREAD

**Issue by salakamaka** [studio-minus/ppg-bugs-and-requests#2397]
**Describe the bug**
I joined the game to make some builds and caught this bug

**Clearly describe how to reproduce the bug**
idk i just joined default and got this

**Mod list**
FNaF, WWII, COMBAT SPECIAL OPERATIONS, DETROIT, IRA, US ARMY, Rus. Army, Ukraine Ground Forces, Flights, Node mapper , SCP-610, Spraycans, NuclearPlayground.

**System info (please complete the following information)**
 - Operating system:  Win 10
 - Game version: 1.26
 - GPU: RTX 2080
 - CPU: Intel 7 9800

![imsadage](https://user-images.githubusercontent.com/103763578/201872397-bfdc5c17-adfd-4315-a20c-2299018885d4.png)
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10010918/exported.game.debug.info.md)

**Additional notes**

**Comment by DindinYT37** [comment]
It would be quite nice if you could make your mod list actually readable.

**Comment by salakamaka** [comment]
> It would be quite nice if you could make your mod list actually readable. Also, are you using the new `ModAPI.RegisterCategory` or the unofficial, unsupported way?

i just subscribing mods in steamworkshop

**Comment by DindinYT37** [comment]
> > It would be quite nice if you could make your mod list actually readable. Also, are you using the new `ModAPI.RegisterCategory` or the unofficial, unsupported way?
> 
> i just subscribing mods in steamworkshop

If the problem is caused by a mod, report it to the mod.

**Comment by salakamaka** [comment]
> > > It would be quite nice if you could make your mod list actually readable. Also, are you using the new `ModAPI.RegisterCategory` or the unofficial, unsupported way?
> > 
> > 
> > i just subscribing mods in steamworkshop
> 
> If the problem is caused by a mod, report it to the mod. The Developers of the game have nothing to do with the mods on it, unless it's a direct issue with the API.

k

**Comment by mestiez** [comment]
I can't do anything to fix this because it's caused by code I don't control
