### ISSUE TITLE
Make procedural gib fragments match actual gore sprites of modded entities

### ISSUE THREAD

**Issue by X13-423** [studio-minus/ppg-bugs-and-requests#2405]
**Feature description**
Instead of using default flesh and bone sprites this feature should use actual flesh and bone sprites of the entity.

**Feature purpose**
As it is now it look really weird when you crush limbs of modded humans who have different flesh and bone sprites.

**Additional context**

**Comment by royalealbert27** [comment]
Yeah

**Comment by mestiez** [comment]
this was unimplemented because it was an unfinished feature (preview release etc.)
it has since been added
