### ISSUE TITLE
Crooked interface - URGENT

### ISSUE THREAD

**Issue by MrHushPPG** [studio-minus/ppg-bugs-and-requests#2409]
What happened to my interface? The problem persists even after turning off mods
![image](https://user-images.githubusercontent.com/106017720/202440713-542715e4-f552-42cf-830f-262f6fd6895b.png)

**Comment by bibbybabby** [comment]
Have you tried restarting the game?

**Comment by MrHushPPG** [comment]
> Have you tried restarting the game?
Restarting the map does not help. Restarting the game solves the problem only for 1 session. When restarting the map, the problem reappears

**Comment by bibbybabby** [comment]
Are you on the preview version?

**Comment by MrHushPPG** [comment]
> Are you on the preview version?

yes

**Comment by bibbybabby** [comment]
> > Are you on the preview version?
> 
> yes

Old mods that use the unofficial method of adding categories are broken in the preview version

**Comment by royalealbert27** [comment]
*breaths in* use the template plsssss

Also of youre really in beta then why there arent a plus icon category which is the offical modded category

**Comment by mestiez** [comment]
what version of the game are you on? please use the template. IIRC github has added form templates that should help prevent issues like this from being hard to understand

**Comment by MrHushPPG** [comment]
The bug has been corrected. THANK YOU! My request is granted.
