### ISSUE TITLE
Weirdness with the capacitor

### ISSUE THREAD

**Issue by MrHushPPG** [studio-minus/ppg-bugs-and-requests#2414]
Description
The gun continues to electrocute target even after disconnecting the capacitor
Steps to reproduce the problem.
1) Take the gun
2) Connect the capacitor 
3) Shoot the target with an electric shock
4) Disconnect the capacitor from the gun
5) Shoot the gun at the target and see that the gun electrocutes the target although it seems that without the device it should not

![YRkNE38645kM16NufXDoFd_3FXb7mFm-pC7exfRiLvaCnzF89gWZGim8snLzUekoXnhi0inCfhtr4r6cPbnvcllR](https://user-images.githubusercontent.com/106017720/202535037-d8e4e71c-b644-42a5-b5a3-b6e8ef13e0db.jpg)

**Comment by Drogo-man** [comment]
Experienced this too.

**Comment by Aspa102** [comment]
should be fixed whenever the next preview or update comes out
