### ISSUE TITLE
Guns with laser attatchment - Laser gets toggled when firing

### ISSUE THREAD

**Issue by wave004** [studio-minus/ppg-bugs-and-requests#2416]
**Describe the bug**
When firing a gun the laser gets toggled - one "F" press resulting in a toggle.

**Clearly describe how to reproduce the bug**
- Spawn Gun with Attatchment Points
- Attatch Laser Attatchment
- Fire gun
- Observe the Laser turning on and off with each "F" press

**Mod list**
none.

**Additional notes**
Does the laser attatchment increase accuracy at all?

**Comment by Aspa102** [comment]
should be fixed whenever the next preview or update comes out
