### ISSUE TITLE
ex. X does Y instead of Z

### ISSUE THREAD

**Issue by mestiez** [studio-minus/ppg-bugs-and-requests#2419]
### Describe the bug

Blah blah this is a test

### Clearly describe how to reproduce the bug

a test again wow
- gotta do this
- gotta do that
- en dit
- en zus
- en zo

### Game debug info

[1668705759-Main.log](https://github.com/studio-minus/ppg-bugs-and-requests/files/10036663/1668705759-Main.log)

**Comment by mestiez** [comment]
:)

**Comment by Drogo-man** [comment]
:)

**Comment by royalealbert27** [comment]
this is the worst suggestion bug report ever!!!!!
