### ISSUE TITLE
Attachment attaches to two weapons at once.

### ISSUE THREAD

**Issue by nilocc** [studio-minus/ppg-bugs-and-requests#2421]
### Describe the bug

Attachment is connecting to other weapons when already occupied.

### Clearly describe how to reproduce the bug

Grab an attachment put it on a gun. Grab another gun drag it to the attachment.

### Game debug info

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.22000) 64bit

 - **CPU**: Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz

 - **GPU**: NVIDIA GeForce GTX 1660 Ti

 - **Memory**: 16 GB

## All loaded mods

	Punkkinn, Talon Zane-Wrath God mod-2253664342 vv1.0 for game v1.11+
		Currently inactive

	Punkkinn, Talon Zane-The Super Collection-2251078075 vv1.0 for game v1.11+
		Currently inactive

	gwenenenen-More Guns-2235585600 v1.0 for game v1.10.2
		Currently inactive

	Golden, Talon Zane-(OPTIONAL) Among Us Mod - NO DEATH ANIMATIONS-2233689167 v1.0 for game v1.9+
		Currently inactive

	Golden, Talon Zane-Among Us Mod-2232883786 v1.0 for game v1.9+
		Currently inactive

	weirdo-Chemical Warfare-2226697361 v2.0 for game v1.22.2+
		Currently inactive

	Teletubbie With A Shotgun-Vietnam Soldiers Mod-2221749809 v1.0.5 for game v1.9+
		Currently inactive

	Woowz11-Blood eye 4-2221268267 v0.1 for game v1.9.5
		Currently inactive
		Malfunctioning

	Golden-Hazmat Mod Remastered-2217857980 v1.3.1 for game v1.9+
		Currently inactive

	weirdo-Advanced Damage-2212880187 v2.1 for game v1.22.2+
		Currently inactive

	CyberPlays26-Cyber's WWII Mod-2212721487 v1.12.1 for game v1.10+
		Currently inactive

	EasyCat-Assasins Mod-local v0.1 for game v1.9
		Currently inactive
		Malfunctioning

	Woowz11-WoowzWeapons--Ammo system---2200529678 vv.1 Alpha for game v1.9
		Currently inactive

	ApDown,Woowz11,Morzzic,Azule-Controllable UFO-2198120027 v1.0 for game v1.9.+
		Currently inactive

	DRAGOLITE-Armor Mod (for PM 2)-local v1.0 for game v1.9+
		Currently inactive

	Morzzic-Smart Spawner-2195054961 v2.2 for game v1.10+
		Currently inactive

	weirdo-Functioning Armor-2194511729 v3.0 for game v1.22.2+
		Currently inactive

	ALASTOR-IrtnerMOD NO MORE BETA!-2193110720 v1.2.5 for game v1.8+
		Currently inactive

	DRAGOLITE-Purple mod 2-2191020236 v1.0 for game v1.9+
		Currently inactive

	Svit and Sky-POT O' Items-2187367733 v1.2 for game v1.9.4
		Currently inactive

	The Doktor/Professor Dark-Space Age-local v1.0 for game v1.9
		Currently inactive
		Malfunctioning

	Morzzic-Russian Roulette Mod-2173352550 v1.1 for game v1.9+
		Currently inactive

	Kelly The Dragon-The Tungsten Mod-2170418527 v2.4 for game v1.8 +
		Currently inactive

	Woowz11-BloodEye3-2170110891 v0.5 for game v1.9+
		Currently inactive
		Malfunctioning

	Sororfortuna-Soror's NPC Pack-2169243678 v11.0 for game v1.19.2
		Currently inactive

	Mr_kWKD-Humans+-2168468454 v1.3.0 for game v1.9
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently inactive

	NotEclipse-Sandbox++-2166702425 v1.0.1 for game v1.8+
		Currently inactive
		Malfunctioning

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	kortl-COMBAT Zombies-local v1.0 for game v1.8.x
		Currently inactive

	Hewaki-Household Mod-2159368880 v1.3 for game v1.8.x
		Currently inactive

	Kyrelink-Flashlight Mod-local v1.0 for game v1.8+
		Currently inactive

	LijmPistool-Duck Gun-2153433081 v1.0 for game v1.8.x
		Currently inactive

	(RU)Enot builder-Construction kit V0.9.5-2151076041 vV0.9.5 for game v1.8x
		Currently inactive

	LijmPistool-Glue Gun-2150807048 v1.0 for game v1.8.x
		Currently inactive

	LijmPistool-Minecraft Swords-2149969616 v1.5 for game v1.8.x
		Currently inactive

	Morzzic-Creeper Mod-2149536449 v1.1 for game v1.8
		Currently inactive

	MerelyMiserable-Overdose-2148965453 v2.0 for game v1.21+
		Currently inactive

	Morzzic-M4A4 Howl Mod-local v1.0 for game v1.8
		Currently inactive

	llAndryushall-AMod - Swords2.0-2146745681 v2.0 for game v1.8
		Currently inactive

	Portal Turret1010-Katana Mod-2146154723 v1.0 for game v1.8.x
		Currently inactive

	Kyrelink-Roleplay Weapons-2145912886 v1.0 for game v1.8+
		Currently inactive

	Pigeom-Medieval Playground-2143456037 v7 for game v1.9+
		Currently inactive

	Sv1t-Bubble gun-local v1.0 for game v1.9
		Currently inactive

	TailsIsAwesome-Sans Bone-local v1.0 for game v1.8+
		Currently inactive

	Kyrelink-Half Life 2 weapons-2140530282 v1.6 for game v1.7
		Currently inactive

	Ladno.-StalkerWeaponsMod-2140155327 v2.0 for game v1.9+
		Currently inactive

	Miguel Freitas-Weapons mod-2138599540 v1.0 for game v1.7
		Currently inactive

	kortl-COMBAT Weapons Pack V3.0-local v3.0 for game v1.7.x
		Currently inactive

	kortl-COMBAT Props Pack-local v1.0 for game v1.7.x
		Currently inactive

	BBQGiraffe-Doom weapons pack-2137895715 v3.0 for game v1.8.x
		Currently inactive

	Grizzly-Ancient Weapons Pack-2137861405 v13.0 for game v1.8.x
		Currently inactive

	Cyxil-Expanded Lightsabers-2137839183 v1.3 for game v1.8
		Currently inactive

	Mr_kWKD-Weapons+-2137654291 v2.0.0 for game v1.15+
		Currently inactive

	kortl-COMBAT Clothes Pack-local v1.0 for game v1.7.x
		Currently inactive

	(RU)Enot builder-Weapon Mod-2137486750 v0.8 for game v1.7x
		Currently inactive

	annoyinggoose-Uhudk-local v1.0 for game v1.10+
		Currently inactive

### Mod list

0 mods

### Game version

1.26 preview,

### Operating System

windows 11

**Comment by royalealbert27** [comment]
can you provide a screenshot

**Comment by royalealbert27** [comment]
here i'll do it
![image](https://user-images.githubusercontent.com/101178735/202675194-bd0df912-48e7-41a3-b82b-8ac277065615.png)

**Comment by MrHushPPG** [comment]
It happened to me, too.
![image](https://user-images.githubusercontent.com/106017720/202679509-4097210d-4e57-430e-a82c-80ce75fd89aa.png)

**Comment by DindinYT37** [comment]
You do know you're supposed to upload your exported game info, not paste its contents into the issue – right?

**Comment by Aspa102** [comment]
should be fixed whenever the next preview or update comes out
