### ISSUE TITLE
Ceiling Turret shoots twice if held

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2424]
### Describe the bug

If the turret is held and activated, it shoots twice instead of once

### Clearly describe how to reproduce the bug

1. hold ceiling turret
2. activate

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10039425/exported.game.debug.info.md)

**Comment by royalealbert27** [comment]
doesnt happen for me

**Comment by DindinYT37** [comment]
Doesn't happen for me.

**Comment by mestiez** [comment]
fixed! :)
