### ISSUE TITLE
gun attachment doesnt save [beta preview 6]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2426]
### Describe the bug

gun attachment doesnt appear when u copy and paste it. it wasnt a problem in the previous preview so why?

### Clearly describe how to reproduce the bug

get a gun then put some attachment then copy and paste it

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10041050/exported.game.debug.info.md)

### Game version

1.26 beta preview 6

### Operating System

Windows 10

### Additional notes

normal vs pasted
![image](https://user-images.githubusercontent.com/101178735/202701207-75478d21-63a3-4a37-8951-84d16ee4d470.png)

**Comment by Aspa102** [comment]
should be fixed whenever the next preview or update comes out
