### ISSUE TITLE
skeletons having flesh fragments when crushed [beta preview 6]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2427]
### Describe the bug

bone have flesh

### Clearly describe how to reproduce the bug

turn a human into skeleton using pink bomb then explode any limbs of it with the gore fragments on

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10041094/exported.game.debug.info.md)

### Game version

1.26 beta preview 6

### Operating System

Windows 10

### Additional notes

screenshot
![image](https://user-images.githubusercontent.com/101178735/202701966-86738209-1539-4bfe-9760-14c828938e0e.png)

**Comment by mestiez** [comment]
oh god

**Comment by mestiez** [comment]
fixed :)
