### ISSUE TITLE
modded entity sprites with higher resolutions dont appear in beta

### ISSUE THREAD

**Issue by niosixtyfour** [studio-minus/ppg-bugs-and-requests#2430]
### Describe the bug

any modded entity with a sprite resolution higher than the default don't appear

### Clearly describe how to reproduce the bug

i spawn in an entity from a mod with the sprite dimensions 32x158 and the sprite appears as the default sprite of the source entity

**Comment by royalealbert27** [comment]
Can you put the debug info?
