### ISSUE TITLE
mysterious white liquid appears if procedural gore is shot

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2433]
### Describe the bug

If the procedural gore has enabled collision and is shot then a strange white liquid appears

### Clearly describe how to reproduce the bug

1. Enable procedural gore collision
2. Shoot
3. 

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10045374/exported.game.debug.info.md)

### Additional notes

https://user-images.githubusercontent.com/104321411/202817315-973ad1af-6f97-4bb8-a236-d08faa4c3ae6.mp4

**Comment by TeslaCoil9001** [comment]
It's cu-

**Comment by royalealbert27** [comment]
doesnt happen for me

**Comment by bibbybabby** [comment]
> It's cu-

![image](https://user-images.githubusercontent.com/104321411/202826362-fed88d7d-4826-4c74-b1f4-4afdc9b1b289.png)

**Comment by Drogo-man** [comment]
Sußy?

**Comment by mestiez** [comment]
Fixed
