### ISSUE TITLE
gun attachments supposed to appear after saving, instead they dont

### ISSUE THREAD

**Issue by ultraballin** [studio-minus/ppg-bugs-and-requests#2439]
### Describe the bug

after attaching any sort of gun attachment and saving, the pasted gun does not have the attachment 

### Clearly describe how to reproduce the bug

step 1) attach an attachment (any) to a gun
step 2) save the gun
step 3) paste the gun

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10047745/exported.game.debug.info.md)

### Game version

1.26 preview 6

### Operating System

Linux Mint 21 x86_64

### Additional notes

the shotgun shell ejecting part on the shotgun turns white after saving and pasting
![Screenshot from 2022-11-19 20-55-18](https://user-images.githubusercontent.com/67960531/202867000-a76e8205-543e-4d25-8efd-a4ec90906f25.png)

**Comment by Aspa102** [comment]
this has been fixed, however an update with the bug fix hasn't been published.
