### ISSUE TITLE
Flashlight Attatchment For Guns

### ISSUE THREAD

**Issue by DrCoomerPhD** [studio-minus/ppg-bugs-and-requests#2440]
### Feature description

A Flashlight Attatchement For Any Gun.
![image](https://user-images.githubusercontent.com/110489194/202874464-dd966b0d-5179-44e9-8e0b-604ea0a09d13.png)

### Feature purpose

To Use In Dark Places. just a prop item sorta
![image](https://user-images.githubusercontent.com/110489194/202874537-182158cb-5cdc-4358-b31a-11eed80246ae.png)

### Additional context

![image](https://user-images.githubusercontent.com/110489194/202874464-dd966b0d-5179-44e9-8e0b-604ea0a09d13.png)
![image](https://user-images.githubusercontent.com/110489194/202874537-182158cb-5cdc-4358-b31a-11eed80246ae.png)
![image](https://user-images.githubusercontent.com/110489194/202874921-5b049e08-0b12-4621-8f11-316f3fec9f3d.png)
![image](https://user-images.githubusercontent.com/110489194/202874904-87bc6f15-aec5-4d3b-b477-05826ebc13ec.png)
ok thanks

**Comment by mestiez** [comment]
yeah

**Comment by mestiez** [comment]
the one acceptable cosmetic attachment
