### ISSUE TITLE
Activation Toggle on gun makes its attachment fall off [beta preview 8]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2441]
### Describe the bug

Activation Toggle on gun makes its attachment fall off

### Clearly describe how to reproduce the bug

get a gun and put some attachments on it then connect the activation toggle then activate it

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10048242/exported.game.debug.info.md)

### Game version

1.26 beta preview 8

### Operating System

Windows 10

### Additional notes

video

https://user-images.githubusercontent.com/101178735/202878433-04fb3cbe-9ea8-4b28-83e6-ad6de7fa1fd9.mp4

this also happens with key trigger too

**Comment by mestiez** [comment]
fixed
