### ISSUE TITLE
minigun not shooting [beta preview 8]

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#2444]
### Describe the bug

it is spinning and making sound but it's not shooting

### Clearly describe how to reproduce the bug

shoot the minigun

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10048310/exported.game.debug.info.md)

### Game version

1.26 beta preview 8

### Operating System

Windows 10

### Additional notes

video

https://user-images.githubusercontent.com/101178735/202879674-b69a2540-92ca-4afb-9f9b-7e5e3236b0f6.mp4

**Comment by bibbybabby** [comment]
heavy's credit card has been declined

**Comment by mestiez** [comment]
Oh no

**Comment by Drogo-man** [comment]
Oh no indeed

**Comment by mestiez** [comment]
fixe

**Comment by Drogo-man** [comment]
Yippee
