### ISSUE TITLE
changeable 1000kg weight ( closed )

### ISSUE THREAD

**Issue by crystorgic** [studio-minus/ppg-bugs-and-requests#2445]

**Comment by royalealbert27** [comment]
Why not get a mod that adds a customizable weight? (Modifiable Weight Mod) unless you're that type of guy who only wants vanilla things.

**Comment by crystorgic** [comment]
> Why not get a mod that adds a customizable weight? (Modifiable Weight Mod) unless you're that type of guy who only wants vanilla things.

oh ok
