### ISSUE TITLE
The minigun has become useless - URGENT

### ISSUE THREAD

**Issue by MrHushPPG** [studio-minus/ppg-bugs-and-requests#2453]
### Describe the bug

Minigun stops firing and just emits a sound

### Clearly describe how to reproduce the bug

Take the minigun and try to shoot with it. You will see how trying to hit targets is futile

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10050350/exported.game.debug.info.md)

### Mod list

Mods deactivated

### Game version

1.26 (beta)

### Operating System

Windows 10

### Additional notes

https://user-images.githubusercontent.com/106017720/202917612-a6cfb2d5-2a2c-4e91-b3ba-44d6ac110686.mp4

**Comment by Drogo-man** [comment]
Fixed already.

**Comment by MrHushPPG** [comment]
> Fixed already.

Indeed. Then I will close this issue as completed
