### ISSUE TITLE
substructure lights blinking?

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2457]
### Describe the bug

annoying bug involving lights in substructure randomly blinking

### Clearly describe how to reproduce the bug

it just randomly appears on it's own

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10050652/exported.game.debug.info.md)

### Additional notes

https://user-images.githubusercontent.com/104321411/202925176-d160b1f7-d1b8-417a-b1ba-a5d73e357aac.mp4

**Comment by Declani** [comment]
I don't think that's a bug

**Comment by bibbybabby** [comment]
Yea because it's LOOOORREEE

**Comment by royalealbert27** [comment]
Did you run out of bug reports

**Comment by mestiez** [comment]
intentional
