### ISSUE TITLE
Cannon bomb

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2471]
### Feature description

Add a cannon bomb, kind of like those black cartoon bombs you see.  It would have a fuse that must be manually lit and will visually burn and cause the bomb to explode.

### Feature purpose

This could be fun since we don't have a bomb with a fuse yet, and it can also be used for cannons as it was intended.

### Additional context

![image](https://user-images.githubusercontent.com/109692890/203635877-bbcc492e-1693-47ca-b82a-37eed7101437.png)
This bomb is pissed off that he hasn't been added yet.

**Comment by bibbybabby** [comment]
Duplicate of #1759

**Comment by ATPGaming** [comment]
Doing DindinYT37's job

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #1150
* #1759 (As pointed out by @bibbybabby)
