### ISSUE TITLE
Goreless Human impacts do not update if the setting is changed

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2475]
### Describe the bug

Goreless spawned humans do not have decals when goreless and vice versa

### Clearly describe how to reproduce the bug

Turn on/off the goreless toggle
Spawn human
Toggle goreless
Smash the human

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10080036/exported.game.debug.info.md)

### Additional notes

https://user-images.githubusercontent.com/104321411/203671806-ccb8f5db-08dc-432f-8c0a-b7908fd4aec6.mp4

**Comment by mestiez** [comment]
yes this is more or less intentional. making a human "goreless" is moderately expensive so i limit the setting to apply only to new objects
