### ISSUE TITLE
Multiple selected objects messes with the context menu

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2476]
### Describe the bug

If 2 objects get selected some buttons will fallback to using the description of the action

### Clearly describe how to reproduce the bug

Select 2 objects (preferably mechanical) and right click

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10080106/exported.game.debug.info.md)

### Additional notes

![image](https://user-images.githubusercontent.com/104321411/203671956-08efbcd3-d645-4691-8aaf-d626203881fc.png)
Notice that there are bugged buttons at the bottom

**Comment by mestiez** [comment]
this is intentional because the description is more general and feels more intuitive when having multiple objects selected that dont share the same functionality. i can change it though. if enough people tell me to

**Comment by DindinYT37** [comment]
How about "Change display contents"?

**Comment by Drogo-man** [comment]
I think its really annoying, it just kinda makes looking for the right thing to press when doing it with multiple things.
