### ISSUE TITLE
Saving or copying Pins.

### ISSUE THREAD

**Issue by Uniconrzss** [studio-minus/ppg-bugs-and-requests#248]
**Describe the bug**
A clear and concise description of what the bug is: **Pins not saving when attached to two conveyor belts. (Also the wheels still colide with each other when conveyorbelts are connected by pins)**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem: **Attach 2 conveyor belts together with pins and save the contraption. When loaded the conveyor belts wont be connected with pins.**

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect: **_(No Mods are active)_ PAEC Arms, PAEC (NEW) Mod, Object Editor, Mini's Roleplay Mod, Military Mod, EVRC Mod, Liquid-Related Machinery, OETF Mod, Split Reality, Broken Bridge(Map), Randomly Generated Items, Signals and Logic Gates, Nuclear Playground, depletable engines, Map Blocks, Copper Republic Mod, Abyss Details, More Gorse, PAEC Mod, City People, MetalMod, Cinematic mod, Drawables, Front Facing Human, Greendice(Random Events), Parts and Contraptions(Broken so not active), Tactical Armors, Trains and Freights MOD, The Mandalorian, More Destructable Objects !, Per Pixel Destruction, Electronic Components, WWII Mod, Human Tiers, Madness PACK, Swords and Katanas pack Part II, Mount and Blade Mod V.0.4, Colored Wires mod (Broken so not active), Quality of Life Items (Deprecated), Chemical Warfare, Blood Eye 4, Advanced Damage, Cyber's WWII Mod, Tethers, HDwoowzMod, Discord Pack, The X npc pack, Functioning Armor, IrtnerMOD NO MORE BETA!, Research Facility Mod, SupremeMOD NO LONGER BETA!, Signal Lost (Mod), BloodEye3, Humans+, Sandbox++, Active Humans, Construction kit V0.9.5, Overdose, Syringes++, Roleplay Weapons, Medieval Playground, COMBAT Weapons Pack V3.0, COMBAT Props Pack, Ancient Weapons Pack, Expanded Lightasbers, Weapons+, COMBAT Clothes Pack, Lightsabers(By you, anime profile pic man), The Greenbrick Mod.**

**System info (please complete the following information)**
 - Operating system: **Windows 10 Pro**
 - Game version: **1.21.3 (64bit)**
 - GPU: **NVIDIA GeForce GTX 1650**
 - CPU: **AMD Ryzen 5 3600 6-Core Processor**

**Additional notes**
Im surprised this hasnt been reported yet, unless it was.

**Comment by mestiez** [comment]
There are several similar issues, all of which are caused by **Unity's epic, well thought out component system**. The simple explanation is that while it's possible to have multiple components of the same type on one GameObject, it is not possible to retrieve any specific one of those based on anything more meaningful than their arbitrary index in the array.

**Comment by mestiez** [comment]
It's still weird. Collision doesn't get turned off nicely like it does with other objects.
