### ISSUE TITLE
Destroyed Jet Engines Still Produce Heat

### ISSUE THREAD

**Issue by b0rah** [studio-minus/ppg-bugs-and-requests#2482]
### Describe the bug

If a jet engine is blown up, it still produces heat. I discovered this when making a jet helicoptor - on crash, it maintained heat at 1500 or so degrees Celsius. 

### Clearly describe how to reproduce the bug

1. Spawn a Jet Engine
2. Activate it
3. Slam it against a surface
4. Done 

### Mod list

Vanilla

### Game version

1.26 preview 11

### Operating System

Windows 10

### Additional notes

Seems like an odd thing to overlook.

**Comment by mestiez** [comment]
fixed
