### ISSUE TITLE
TSR Tank

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2487]
### Feature description

Add the silly-looking TSR Tank, a Russian tank with a heavy front wheel that was SUPPOSED to be able to traverse nearly any terrain, but during testing, it got caught in the mud multiple times and ultimately the idea was scrapped for being too impractical, and barely functional.

### Feature purpose

It would be nice to have this in the game to add more weaponized vehicles, and come on, it looks ridiculous!

### Additional context

![image](https://user-images.githubusercontent.com/109692890/203818510-5cc4c7c6-c0eb-4987-9ce0-de47966acc3f.png)

**Comment by DindinYT37** [comment]
Have you tried building it yourself? It doesn't really look, like it would be that complex to build in-game.

**Comment by TeslaCoil9001** [comment]
> Have you tried building it yourself? It doesn't really look, like it would be that complex to build in-game.

If it was added officially it would have really nice textures and not be as broken as a player made one

**Comment by DindinYT37** [comment]
> > Have you tried building it yourself? It doesn't really look, like it would be that complex to build in-game.
> 
> If it was added officially it would have really nice textures and not be as broken as a player made one

Have you even seen what people have been making?
