### ISSUE TITLE
Energy sword wrong spawn facing

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#249]
When you spawn sword by pressing Q, it facing where it should be facing if it was spawned on E.

Spawn energy sword

No mods.

 - Operating system: Win 10
 - Game version: 1.21.3
 - GPU: 750TI
 - CPU: I3-3240 3.40 GHz

**Comment by mestiez** [comment]
This isn't a bug. It's just oddly drawn.
