### ISSUE TITLE
Code panel layering bug

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2500]
### Describe the bug

its like #2227 but for code lock

### Clearly describe how to reproduce the bug

put a human on the shiny parts

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10098224/exported.game.debug.info.md)

### Additional notes

![image](https://user-images.githubusercontent.com/104321411/204133888-98f06d42-abec-4af0-b64e-418f6fe36383.png)

**Comment by mestiez** [comment]
fixed :)
