### ISSUE TITLE
Phantom explosive rounds

### ISSUE THREAD

**Issue by whynotll83** [studio-minus/ppg-bugs-and-requests#2502]
### Describe the bug

Attaching the explosive rounds to a gun and undoing by clicking Z, the explosive effect is still on the gun and you can combine explosive with other attachments like the electricity.

### Clearly describe how to reproduce the bug

Attach the explosion rounds, press Z to undo, effect is still there.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10098413/exported.game.debug.info.md)

### Game version

1.26 preview 11

### Operating System

Windows 11

**Comment by mestiez** [comment]
@Aspa102 oh no

**Comment by whynotll83** [comment]
The bug still hasn't been fixed in 1.26

**Comment by mestiez** [comment]
now its fixed :)

**Comment by whynotll83** [comment]
Nope, the bug is still there.

**Comment by whynotll83** [comment]
https://user-images.githubusercontent.com/61813529/210244455-b1cfb11f-b199-4e59-9728-aa4db5b13a20.mp4

I wonder if video files work here.

**Comment by DindinYT37** [comment]
That doesn't look like the beta to me.

**Comment by PossiblyRemember** [comment]
> 2023-01-02.06-25-41.mp4 
> I wonder if video files work here.

The bug is fixed in 1.26.2. The current version for release and beta is 1.26.1.
