### ISSUE TITLE
Bullets stop in water

### ISSUE THREAD

**Issue by Beder3105** [studio-minus/ppg-bugs-and-requests#2503]
### Feature description

Bullets should stop after 1 Meter when shot in water, because of drag.

### Feature purpose

This would make the game far more realistic and its not very hard to make.

### Additional context

![suggestion](https://user-images.githubusercontent.com/119169153/204159024-16687521-d29f-4804-8be9-517b38ef7569.png)

**Comment by Beder3105** [comment]
I know my paint skills are bad

**Comment by bibbybabby** [comment]
Would it be physical or a particle?

**Comment by Drogo-man** [comment]
This already in the game tho?

**Comment by Sirblockhead1** [comment]
turn on bullet tracers

**Comment by Beder3105** [comment]
just saw its already in the game, but it takes way to long in irl the bullet stops after about 1 Meter
