### ISSUE TITLE
Jet Engine

### ISSUE THREAD

**Issue by WWWOWWWPL** [studio-minus/ppg-bugs-and-requests#251]
**Feature description**
Works like a normal (rocket) engine, however it first spools up upon activation (and de-activation) before reaching full power, it gradually gets more powerful as it starts up. It's also not as destructive as a rocket engine, simply pushing objects out of its way instead of incinerating them. The engine could also increase / reduce its maximum power (to an extent) by propagating blue and red channels through it, without messing around with resistors and such.

**Feature purpose**
A weaker, safer and more configurable alternative to normal engines, while still being vastly more powerful than an ion engine.

**Additional context**
(Possible afterburner mode? Would require throwing the power configurability idea out of the window so it's toggleable by electronics.)

**Comment by TamasB14** [comment]
What if it's front part would act like a blender too? Sucks in a stickman and turns it into a red mass that comes from the back?

**Comment by DindinYT37** [comment]
@mestiez wasn't this accepted?

**Comment by mestiez** [comment]
yes
