### ISSUE TITLE
Sensors' beam visibility

### ISSUE THREAD

**Issue by CorruptingLight** [studio-minus/ppg-bugs-and-requests#2510]
### Feature description

A lot of contraptions would look better if the sensors' beams would be invisible and only visible in detail view. Maybe an option to toggle visibility in settings at least? Esthetically speaking it would be really nice if machinery, weapons, robots... wouldn't have ugly beams sticking out of them.

### Feature purpose

That's basically it. New update could use it.

### Additional context

Requesting this to be added in vanilla, because nobody likes downloading extra mods looking at new contraptions, plus it's just a little detail. Would like to hear your thoughts...

**Comment by TeslaCoil9001** [comment]
Maybe toggleable in the context menu

**Comment by ghost** [comment]
Got added
