### ISSUE TITLE
Crash when map loads.

### ISSUE THREAD

**Issue by TheThroneRo** [studio-minus/ppg-bugs-and-requests#2516]
### Describe the bug

So i have lot of mod but that not the problem for my opinion im launching "hibrid" but every time its frezze in 90% after that crash so its annoying When i am really really lucky i can play but i need wait 10 minute but i would like fix that

### Clearly describe how to reproduce the bug

Dont know how to reproduce

### Game debug info

This gonna be a little hard to give Game debug info when its frezze when its load a map

### Mod list

![People Playground 03_12_2022 01_00_27](https://user-images.githubusercontent.com/108471642/205411077-d74d5755-6f74-4425-9bff-84e387e1b7a7.png)
![People Playground 03_12_2022 01_00_22](https://user-images.githubusercontent.com/108471642/205411084-8d5aaf91-6671-4f5f-85c8-7efb47cde9d0.png)
![People Playground 03_12_2022 01_00_17](https://user-images.githubusercontent.com/108471642/205411091-ee02ce16-9cb0-46d7-8297-a78065e42e31.png)
![People Playground 03_12_2022 01_00_13](https://user-images.githubusercontent.com/108471642/205411098-e961205f-8d94-4f1f-81b1-f60df901fcb5.png)
![People Playground 03_12_2022 00_59_38](https://user-images.githubusercontent.com/108471642/205411107-56485165-da7a-49cd-8dfe-434df6ea34a1.png)
![People Playground 03_12_2022 00_59_42](https://user-images.githubusercontent.com/108471642/205411110-456098a2-fcd1-4995-b4ec-6cdf7ff10147.png)
![People Playground 03_12_2022 01_00_00](https://user-images.githubusercontent.com/108471642/205411111-ed4c8f24-ab70-480b-a072-029dae5f69e2.png)
![People Playground 03_12_2022 01_00_05](https://user-images.githubusercontent.com/108471642/205411114-d5a5eeab-85d8-40e0-a138-01321085f357.png)
![People Playground 03_12_2022 00_59_00](https://user-images.githubusercontent.com/108471642/205411126-aa8b5c81-7ae4-4023-8537-11e8da817a4d.png)
![People Playground 03_12_2022 00_59_04](https://user-images.githubusercontent.com/108471642/205411129-03e461cb-52e9-479a-9f62-32cebe0d52d0.png)
![People Playground 03_12_2022 00_59_09](https://user-images.githubusercontent.com/108471642/205411130-5082bf0c-7817-4e58-9669-3ae84285d229.png)
![People Playground 03_12_2022 00_59_12](https://user-images.githubusercontent.com/108471642/205411131-f2f4227c-0e0f-49cd-a201-315d4cc54539.png)
![People Playground 03_12_2022 00_59_17](https://user-images.githubusercontent.com/108471642/205411135-96f2ba8a-257f-4793-a28f-90d42c9dae04.png)
![People Playground 03_12_2022 00_59_22](https://user-images.githubusercontent.com/108471642/205411136-f453ebf8-4303-415e-a09e-5ed2c795c8ae.png)
![People Playground 03_12_2022 00_59_26](https://user-images.githubusercontent.com/108471642/205411138-d2e22fc5-744a-4f5f-a060-4f8d9aa97948.png)
![People Playground 03_12_2022 00_59_30](https://user-images.githubusercontent.com/108471642/205411139-446c60c3-9dd6-40f7-a89c-b6431812166a.png)
![People Playground 03_12_2022 00_59_33](https://user-images.githubusercontent.com/108471642/205411141-b970a2a0-5dc6-4a02-832c-17e93a071e79.png)
![People Playground 03_12_2022 00_58_43](https://user-images.githubusercontent.com/108471642/205411143-510ff3cf-411e-4237-8b58-411b811713c4.png)
![People Playground 03_12_2022 00_58_50](https://user-images.githubusercontent.com/108471642/205411144-2c9c5575-1401-488c-9b5d-dff2f61d6554.png)
![People Playground 03_12_2022 00_58_54](https://user-images.githubusercontent.com/108471642/205411146-c0c44a96-3d88-4703-af9c-2da84d87916a.png)
![People Playground 03_12_2022 00_58_39](https://user-images.githubusercontent.com/108471642/205411152-a9108e49-4108-4ecd-bfcd-d1e33dd75a9f.png)
![People Playground 03_12_2022 00_58_26](https://user-images.githubusercontent.com/108471642/205411154-41d12e6e-4f32-4e42-ad95-f1be6917ec38.png)
![People Playground 03_12_2022 00_58_32](https://user-images.githubusercontent.com/108471642/205411155-633744e0-aa01-4bd8-8f8e-5755416a8a29.png)

### Game version

1.26 Preview

### Operating System

Window 11

### Additional notes

!!! I ALREADY TEST WHIT ALL MOD DISABLE ITS DO THE SAME THINGS !!!

**Comment by Drogo-man** [comment]
you should delete some mods.

**Comment by bibbybabby** [comment]
did you disable them all and restarted the game or just disabled them and loaded a level? because if you just disable them they are not fully unloaded, you need to also restart the game

**Comment by TheThroneRo** [comment]
> did you disable them all and restarted the game or just disabled them and loaded a level? because if you just disable them they are not fully unloaded, you need to also restart the game

I already do it i think mod just affect my loading time i already try disable all mod but this do nothing

**Comment by TheThroneRo** [comment]
> you should delete some mods.

Delete or disable?

**Comment by Drogo-man** [comment]
Delete

**Comment by TheThroneRo** [comment]
> Delete

im gonna try

**Comment by TheThroneRo** [comment]
> Delete

Its do the same things

**Comment by DindinYT37** [comment]
This issue is caused by your mods taking up too much ram when loading it. Disabling them won't help, and deleting just one or two won't help either. My personal solution to this, since I use a lot of mods, was to set the priority of the process to “Lowest” and turn off other programs to save more RAM.

**Comment by TheThroneRo** [comment]
> This issue is caused by your mods taking up too much RAM when loading it. Disabling them won't help, and deleting just one or two won't help either. My personal solution to this, since I use a lot of mods, was to set the priority of the process to “Lowest” and turn off other programs to save more RAM.
> 
> I suggest taking a look at your task manager and see how much RAM People Playground takes up while loading.

im gonna test and told you how much ram its take

**Comment by TheThroneRo** [comment]
> This issue is caused by your mods taking up too much RAM when loading it. Disabling them won't help, and deleting just one or two won't help either. My personal solution to this, since I use a lot of mods, was to set the priority of the process to “Lowest” and turn off other programs to save more RAM.
> 
> I suggest taking a look at your task manager and see how much RAM People Playground takes up while loading.

Thanks i restart my pc and just launch steam and people playground its work i also delete mod that i not use
