### ISSUE TITLE
Sentry turrets work upside down

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2518]
### Describe the bug

If the sentry turret is upside down, it does not shut down

### Clearly describe how to reproduce the bug

Rotate the turret so the legs are facing away from the ground

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10146132/exported.game.debug.info.md)

### Additional notes

![image](https://user-images.githubusercontent.com/104321411/205435178-3a4427a7-6bc4-46cd-8d55-52a64895a753.png)

**Comment by mestiez** [comment]
fixed :)
