### ISSUE TITLE
humans muscles tense up when shot in the head

### ISSUE THREAD

**Issue by averagebloxy** [studio-minus/ppg-bugs-and-requests#2522]
### Feature description

it affects the ragdoll and its a new mechanic and  like real life gore because when someone gets shot in the head their muscles tense up then release

### Feature purpose

because it would make the game a lot more fun and i thought of it when i shot a human in the chest and he became too and his legs tensed up for a second then released and i think that should happen when you shoot a human or anything in the head.

**Comment by DindinYT37** [comment]
> I would like the creators discord if possible so i can chat with him about this personally.

This is as personal as it gets for a feature request.

**Comment by bibbybabby** [comment]
This is kind of in the game when humans sometimes stand for a moment after a headshot

**Comment by averagebloxy** [comment]
no, it depends what type of gun you use like a Glock doesn’t but a revolver does and if you use a low power gun that won’t blow their heads off then it’s pretty realistic if you look at gore videos some peoples muscles tense up when shot in the face or head.

**Comment by bibbybabby** [comment]
> if you look at gore videos

Who the fuck asks people to look at gore videos?

**Comment by Eukalp** [comment]
Hi, hunter, pigpicker here!
Caliber doesn't matter at all for shooting something in the head. Indeed you are right that muscles tense up, but there's the thing you are wrong at. It's not only when it's a headshot, it is a natural response of a creature to basically tense up once they feel that sting a shot does to them. From my experience the tense muscles occur at any kind of shots (we mostly do shots to the lungs and hearts of the deer) and in all kind of situations they do tense up for a second. The brain shot feels weird 'cause the brain cannot send the action to loosen the muscles anymore so it might look like they'd been tense for a bit more.

Well right, I'm talking about animals. Humans would act just a bit more different (or not?).
There was a great movie that showed 1:1 the real example of a headshot.
IF you search up on youtube:
_The Search - Russian troops enter Grozny [eng sub]_ and go ot the 1:22 time of it, you'll see it.

Muscle does not tense that much, it's more likely a natural response to the pain of the shot.

**Comment by mestiez** [comment]
like others said, this already occasionally happens
