### ISSUE TITLE
Car hood and trunk collides with the seat

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2532]
### Describe the bug

The hood and trunk collide with the seat but not with the other car parts

### Clearly describe how to reproduce the bug

Rip the hood/trunk off and put it in the seat

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10195791/exported.game.debug.info.md)

### Additional notes

![image](https://user-images.githubusercontent.com/104321411/206729439-228fa6ef-cd4a-4810-af3c-a765d65bf0a1.png)

**Comment by mestiez** [comment]
fixed :)
