### ISSUE TITLE
Explosion Radius on detail mode is white.

### ISSUE THREAD

**Issue by sttkssxe** [studio-minus/ppg-bugs-and-requests#2537]
### Describe the bug

This happened to me when i exploded the bombs on my plane and my pc lagged, and when i pressed S (detail mode) The explosion radius that displays when you press S is white instead of red. (I had no tabs/windows lagging my computer.)

(and theres no way my mods can cause it, since ive ran those mods (active/inactive) for 100+ hours without any issues.)

### Clearly describe how to reproduce the bug

1:Make A build with alot of bombs (make sure the explosion is laggy enough)
2:Explode the bombs
3:Save it as an contraption
4:Load it and press S (i dont really know what happend so it might be unclear)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10202157/exported.game.debug.info.md)

### Mod list

**Construction kit V0.9.5**
**Time Accelerator**
**Rocket Mod**
**FNAF Mod**
**Controllable anti-air cannon**
**POT O' Items**
**Functioning Armor**
**Smart Spawner**
Advanced Damage
**Chemical Warfare**
**More Destructible Objects !**
**Trains and Freights MOD**
Aimbot Gun
**The unmatched powers of the sun**
**ExplosiveMod**
**Parts and Contraptions**
**More Explosives**
**Doors Mod**
**Police+**
**flipping heck**
**depletable engines**
**Metal Things Mod**
**Pirate Cannon**
Scream mod
Beated up human mod
**Quality of Life Items**
**Configurable Explosive**
**The Musket Mod**
**Animated Weapons+**
Signals and Logic Gates
**Emergency Siren**
**Quick Right Click Options**
Randomly Generated Items
Marbles
**Cyberpunk 2077 Trauma Medic Pack**
**Gold Items Mod**
**Raw Pink Liquids**
**Space Mod**
**Liquid-related Machinery**
**AutoAim**
**Modifiable Weight**
**The Bits Mod**
**Fish Mod**
A Crap Ton Of Damage
**Fishing Rod**
**Item Plus**
MilitaryMod Expansion: WW2
**Status Icons**
**Basic Syringes Mod**
**Leopard 2A5**
**M1A2 Abrams**
Invinicibility Syringue
Puppet Master
Super Idol NPC + Water Bottle
**Prop Mod**
**Polar Bear's Custom Syringes'**
**Wild Medieval**
**Level A-D Protection (Hazmat Suit Mod 2)**
**Doll for tests 2**
Buoyant
**Rooms & Furniture**
Wound Infections
**Construction Tools+**
**Prosthetics mod v2**
Boneworks Pack: NPCs
Human Dynamic Emotions
Law Enforcement Base: USA
**Random Activation Propagation**
**Taser**
Old Maps
**Russia vs Ukraine Mod**
Prison Bus
**Camera Mod**
SpawnableLift
Blood on walls
Military Truck
**The Nearby Conflicts Base: US Army
**Wind Generator**
**Female Human**
**V+ Field Gun**
**Syringes++ fixed raw beta**
**Realistic Atom Bomb**
**Reactive humans**
Water Physics
**Human Decal Enabler**
The Hoard
**The Ultimate Car Mod**
**Better Androids**
**Shopping Cart -SC**
Underwater Weapons Mod
**Aerodynamics**
**Reloadable Explosive Weapons**
**Realistic Axe mod**
**Cigarette**
**Limb Reattachment Tools**
**More Vehicles**
Functional Terminator Mod
**Powerful Generators**
**BloodEnhancedMod**
**Catt's Cannons**
**Tiger I 2.0**
**IS-2 2.0**
**Sherman Edition 2.0**
Advanced Zombie Injector (v1.1)
**Leopard 2A5 2.0**
**M1A2 Abrams 2.0**
**T-90 2.0**
Operation LSA Forces: MARSOC (MAROSC UPDATE AND GENERAL APOLOGY)
The Helicopter Mod
Destructive Warfare
Katana Zero
Blood Ocean / Rotes Meer Map
FOX MOD
More Realistic Gun SFX
Gas Can
Category Switcher
Other Flamethrowers
**Ballistic Playground**
ULTRAMAN
**BarBeQ's Coca Cola Playground**
**Dead creatures remover button**
Nextbot Base
**Apollo mod NASA**
**ROBLOX Mod**
**PPG: Civillians**
**Functional Helicopter Mod**
**Fire Remover Button**
left 4 dead gore human
**PPG Additions**
**Ultimate Melee Pack**
**Colored Bus Chairs**
Raised several limbs
**Saitama | One-Punch Man Mod**
Rifles | WWWII
The Metranese Theocratic Empire - Remastered
Ant Mod
Dragon Custom Entity
Pickup Advanced
Deformation Mod
**Human Dynamic Emotions 2**
**PzKpfw V Panther MOD**
cooler gore human
**[Improved] Pickup Advanced (Pickup anything)**
**Attachable**
**Torture Mod**
Better Gore
**Ferris Wheel**
**Liquid Logic**
Everything Colourable
Secret Items Spawn Allower Mod
**Prostheses**
**Arrows and crystals are now debris**
**Auto-Phase Link**
(self made mod)**Earth Mod**
(self made mod)**Explosimod**
(self made mod)**goofy ahh**
(self made mod)**Hi**
**Expanded Lightsabers**
**Mulligan**
(self made mod)**Test Mod**

(bold text:active)
(not bold text:not active)
(self made mod:i made those mods for myself)

### Game version

1.26 preview 3

### Operating System

Windows 10 Home

### Additional notes

![Screenshot (1788)](https://user-images.githubusercontent.com/98581813/206903618-9c5cf393-d015-4855-958a-225f07baf6e7.png)

Additional Notes:
(the glow of the industrial gyrostabiliser is white and is very bright)
![Screenshot (1790)](https://user-images.githubusercontent.com/98581813/206903705-ea05fde7-5b3b-43ec-94bf-f2608053b4b8.png)

**Comment by DindinYT37** [comment]
> (and theres no way my mods can cause it, since ive ran those mods (active/inactive) for 100+ hours without any issues.)

Ever heard of mods updating, or a new game-update breaking mods?

**Comment by mestiez** [comment]
this is all convoluted and extremely likely to be caused by a mod. you have so many mods that i can hardly be expected to figure out which one is causing it. i suggest disabling all of them, restarting, and then enabling them one by one to see which one is causing it

**Comment by Drogo-man** [comment]
♪This is caused by the "everything is colourable" mod, woaahooaah.♪
