### ISSUE TITLE
Acid gives "skin damage" to androids

### ISSUE THREAD

**Issue by IiIIy** [studio-minus/ppg-bugs-and-requests#2539]
### Describe the bug

Draining acid damages androids and gives them "skin damage".

### Clearly describe how to reproduce the bug

With liquid canister
1. Spawn liquid canister
2. Fill it with acid
3. Make bullet holes in it
4. Put the android under the jet of acid
5. Android is damaged by acid and gains "skin damage"
With blood tank
1. Spawn blood tank
2. fill it with acid
3. turn it into "drain mod"
4. put the android under the jet of acid
5. Android is damaged by acid and gains "skin damage"

### Game debug info

-

### Mod list

-

### Game version

1.25.4 (64 bit)

### Operating System

Windows 10

**Comment by DindinYT37** [comment]
Isn't the actual bug here simply that it's called “Skin damage” for a human as well as an android?

**Comment by mestiez** [comment]
i guess its a bit weird but android "skin" is the correct term for its hull
