### ISSUE TITLE
Children of objects cannot pass through humans that hold the parent

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2545]
### Describe the bug

Objects that are parented to other objects like the axe blade and gun attachments cannot pass through people that hold the parent object

### Clearly describe how to reproduce the bug

Grab an axe or a gun with an attachment

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10225338/exported.game.debug.info.md)

### Additional notes

https://user-images.githubusercontent.com/104321411/207759569-22ed78d3-ee74-40f4-91f1-15993a1d8de3.mp4

**Comment by mestiez** [comment]
Fixed :)
