### ISSUE TITLE
Jet engine after duplicated looks like  a jet engine on full power

### ISSUE THREAD

**Issue by temedeme** [studio-minus/ppg-bugs-and-requests#2548]
### Describe the bug

So when you ctrl c - ctrl v  a jet engine that is not turned on the newly copied engine would look like a fully powered one but after
you click F it powers on and later you cannot turn it off

### Clearly describe how to reproduce the bug

1. Spawn a jet engine
2. Ctrl C
3. Ctrl V
4. there you have it

https://user-images.githubusercontent.com/78973345/207842917-2aa4050f-2d80-4a24-804d-6a931bfa14eb.mp4

### Mod list

Active:
Weapon size affects its power 
Prostheses
Everything Colourable
Torture Mod
Human Dynamics Emotions 2
Pickup Advanced
Dead creatures remover button
More Vechicles
Status Icons
Cyberpunkt 2077 Trauma Medic Pack
Quick Right click options
Scream mod
flipping heck
Chemical Warfare
Functioning Armor

Inactive:
Deformation mod
Shopping cart - SC
Mini's roleplay mod
Misc's items mod
City people
Humans+
Active Humans

### Game version

1.26 preview 11

### Operating System

Windows 10

### Additional notes

Also when you  save a jet engine then spawn it, it also bugs it

**Comment by DindinYT37** [comment]
Doesn't happen for me.

**Comment by mestiez** [comment]
i cannot replicate this

**Comment by Drogo-man** [comment]
This might be the "everything is colourable" mod, since it fucks with effects like gore and particles.

**Comment by Squibard** [comment]
oh that makes sense

**Comment by Squibard** [comment]
> This might be the "everything is colourable" mod, since it fucks with effects like gore and particles.

that makes sense

**Comment by Drogo-man** [comment]
Also notice how the jet is abnormally bright? Yep, that also a side effect of it.

**Comment by mestiez** [comment]
alright then
