### ISSUE TITLE
Humans breathe under ice

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2550]
### Describe the bug

If you freeze a human inside ice, it will breathe somehow

### Clearly describe how to reproduce the bug

Chuck a human in water and set temp to -5

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10245447/exported.game.debug.info.md)

### Additional notes

![image](https://user-images.githubusercontent.com/104321411/208089958-b8a4568a-48a0-4b62-8cc7-e2b17dad31f1.png)

**Comment by mestiez** [comment]
fixed :)
