### ISSUE TITLE
Grenade spoon should fly out when activated

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2553]
### Feature description

You know the flat things on exploding rocks? It serves as the thing that holds the spring igniter and it flies off once the pin is pulled, the pin is for safety so the spoon wont fly off so it won't go off in your pocket or belt or whatever. In the game however, only the pin flies off. This should be changed.

### Feature purpose

Realism

**Comment by Drogo-man** [comment]
Actually the spoon is the divider between the igniter and the fuse, so basically, when the spoon is removed it alloes the igniter to fall down and ignite the fuse which then ignites the primer which then ignites the explosive filling, which makes the funny metal parts go wee, which makes the target go "OH MY GOD MY LEG! MY LEG IS GONE!! HOLY FUCKING SHIT IT HURTS SO MUCH OH MY GOD! IM BLEEDING! MEEEDIIIIIC!!!! HEEEELP!! AAAAAAAAAAH!!!!!"

**Comment by bibbybabby** [comment]
Okey dokey I changed it, and the target won't scream at all because most likely the target would pass out from shock / blood loss
