### ISSUE TITLE
Humans aren't structurally sound.

### ISSUE THREAD

**Issue by FaxTurtle** [studio-minus/ppg-bugs-and-requests#2555]
### Describe the bug

When I spawn in a human, they start all 'springy' and then they convulse and die.

### Clearly describe how to reproduce the bug

Spawn a human.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10252512/exported.game.debug.info.md)

### Mod list

ALL MODS ARE NOT ACTIVE

Foods+ Mod
Physical Bullets
3D Saul Goodman Main Menu Replacement
Russian PMC weapons mod
Metal Gear Rising Mod
Torture Mod
Syringes++
Dead Creatures remover button
Real Nerf Guns
Extinction
Venerable Weaponry
The Greenbrick Mod Fixed
Outdated Military Truck
Video Player
Farmbot
Superior Spiderman Mod
Trollge Mod
Purple Guy
Green Jewel Company
Invincibility Syringe
The Agency Mod BETA
Famous People Pack
Friday the 13th mod (Jasons)
Friday the 13th mod (Counselors)
Dark Latex Remover
Misc Pack #2
Throwable Knife
Japan Weapons
Weirdos Pack 2
ShitGuns++
Overly Tactical Guns
Unreleased items mod
Time Changer Tool
People Playground Roblox Mod
Feelings mod DLC
Among us Hats
People's Liberation Army Pack
The Ultimate Human Mod
Quick Right Click Options
Animated Weapons+
The Musket Mod
Decomposition
Generators+
Russian City
Pirate Cannon
Nuclear Playground
Velociraptor Mod
Holy Hand Grenade
Gorey Human 2.0
Iraq War Mod
Terminator Mod
Wheelchair
The ULTIMATE Minecraft Mod
COMBAT SPEC-OPS
COMBAT SPEC-OPS MAP
Copper Republic Mod
Bombs Expanded
Minecraft Weapons Mod
S.T.A.L.K.E.R: Call of PPG
Military+
S.C.P Foundation Expanded
PAYDAY 2; People Playground Edition
Android Injectors
CRT Televisions
City People
Panda Mod
FTC Weapons
Survival Pack
JMOD 2
The300Spartans
Marvel Power Pack
DOOM ETERNAL The Crucible Mod
Taser
Secure. Contain. Protect. [SCP MOD]
Trever Henderson Creations + Iconic Video Games Characters
The Ultimate Admin Gun
Star Wars Dark Saber Mod
ExplosiveMod
S.C.P.F mod
WWII Mod
Human Tiers
Special Forces Mod
PPG13
Super Gorse Mod
Prison Mod
R6S Exothermic Charge
Hitman Mod
PowersMod
DeathCounter
PPG Spy Mod
CreepyPasta Mod
Star Wars Side Characters Mod
ELECTRIC Weapons MOD
Chemical Warfare
Cyber's WWII Mod
Smart Spawner
family guy pack 1
family guy pack 2
Minesweeper
Team Fortress 2 Mod
FNAF Mod
Soror's NPC Pack
Time Accelerator
Active Humans
Ancient Weapons Pack

### Game version

1.25.4

### Operating System

Windows 11

**Comment by Drogo-man** [comment]
It might be the "extinction" mod, because some mods tend to still have a limited effect when disabled, and your problem sounds like what the extinction mod does, so try to uninstall it and see what happens.

**Comment by PossiblyRemember** [comment]
Make sure your Physics Iteration Count is higher than 1. By default, it is at 16.

**Comment by FaxTurtle** [comment]
@PossiblyRemember It worked thanks.

**Comment by PossiblyRemember** [comment]
> @PossiblyRemember It worked thanks.

I'd recommend closing the issue now.
![image](https://user-images.githubusercontent.com/105954143/208340343-7d528ce7-3884-4108-b0a7-78726cca4279.png)
