### ISSUE TITLE
Firework particles have weird cuts

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2569]
### Describe the bug

Some kind of transparent border is cutting the particles

### Clearly describe how to reproduce the bug

explode a firework (preferably a large one)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10276789/exported.game.debug.info.md)

### Additional notes

![image](https://user-images.githubusercontent.com/104321411/208881461-253720b9-8ef8-4930-b883-7d4852169695.png)

**Comment by mestiez** [comment]
this is caused by unity's line renderer and the performance trade-off is not worth it :(
