### ISSUE TITLE
bone eating syringe bug

### ISSUE THREAD

**Issue by DoomKittyAttack** [studio-minus/ppg-bugs-and-requests#257]
**Describe the bug**
when you stick a bone eating syringe in a human then flamethrower him he has bones
**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
look up
**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
no mods
**System info (please complete the following information)**
 - Operating system: linux kubuntu (not ubuntu kubuntu)
 - Game version: 1.21.3
 - GPU:intel integrated
 - CPU:intel integrated

**Additional notes**
this might be a feature request instead of a bug idk

**Comment by UniDuki** [comment]
#96 "Not a bug, simply misnamed"
