### ISSUE TITLE
The upper body and the head is dead but not the rest of the body

### ISSUE THREAD

**Issue by Pitatto** [studio-minus/ppg-bugs-and-requests#2584]
### Describe the bug

It make the head and upper body dead but not the rest of the body, even if i revive them it dont fix.

### Clearly describe how to reproduce the bug

Imagine cracking the neck of a human, the head and the upper body are dead but not the rest, or another example: you kill an entity you revive it but the upper body and the head are dead

### Mod list

S.T.A.L.K.E.R: Hearth of PPG
Immortality Field Mod
Barbeq's Fiream Collection : Glocks
W%E : United States of America
Food + mod
Physical Bullet
Weapon size affects its power mod
Ultimate map blocks
Egg 2.
1.1 Cat gun
Jmc's SCP-610 mod
Prostheses
JMC"s SCP-009 mod
Everything is coulourable
Haley strategic Hot wired mod
75th Ranger mod
Torture mod
JMC's SCP-173 mod
Attachable
Tactical Style mod
Dead Creature = Zombies
Apocalypse gear pack
Human dynamic emotions 2 (it doesnt want to load)
Pickup advanced
Bubble Gum Human mod
Abyss corruption system
Colorful Display
Evironement Time Changer
Zombie Pack
Unlimited Camera Zoom
Pistol I WWii
Fire remover button
Dead creature remover button
Improved madness pack REUPLOAD
Category switcher
Operation LSA Forces : Russia RE...
PPG slayers
Acid antidot
Random tactical gun/HD/
Hazardous Environemen Combat Unit
Great Gorge
The helicopter mod
Operation LSA forces : Marsoc (...
Arrows and Crystals are now debris
Zuccians Superhuman
Advanced Zombie Injector (v1.2)
JMC's Technology and Chemistry
Ballistic dummy
ZOOM
BarBeq's Animator vs Animation
Functional Terminator mod
Anti Gravity device
More Vehicles
Symbiote PLayground
PurgeTrooper
Husk Overdose
Cigarette
(FICTIONAL) Kiev Private Security
Realistic Axes mod
Lawless 2
Reloadable explosive weapons
The Ultimate Car Mod
Water Physics
Popular SCP's
Reactive Humans
Lego Man
Accurate resize & position
Old Maps
SCP : Armory
Detailed Mobile Task Force
Melee Weapons
Wind Generator
People Playground 3D
Extremist group : America
The nearby conflicts base : British ...
Crash test dummy
OutDated Millitary truck
Extremist Groups : Ireland
Blood on walls
Favourites Category
Battle Droid mod pack
Millitary mod expansion : Hungaria
Controled sea (FIXED FOR 1.24)
Private Millitary contractors
Demon Slayer mod
R0Y1T0 Vehicle Pack 1
Video Player
JMC  POWERFULL MASTERS
RGB liquids
Guns N' Ammo
SimplePortals
Acid sea (FIXED)
Human Dynamic Emotion
Nimrod SAS
Modern fiream
Spiderman-No Way Home
Prototype human mod
Feet arent indestructible
Prop mod
Science Hazard Minus
Forging mod
SCP protogen mod
Vitals of Steel
More Human mod
Undertale Mod
Puppetmaster
FireCrackers
Russian Texture pack
DC power pack
A syringe mod
Inferno Syringe
Working Spraycan mod
Human tiers+
Status Icons
Ice humans
Node mappers
Naruto Pack
Syringe and more
poppy playtime!
MillitaryMod Expansion WW2
Colorful
Food mod
[SCP 610 MOD ]
small acid swamps
SCP-Foundation mod (wip) 
Item plus
Call of duty: Modern warfare 2
Special weapons and tactics mod
People Slashers
Laser Tag Mod
Dressed human mod V2
functional device mod
A crap ton of dammage
Special testing facility NPC pack dlc
Fish mod
Naruto Pack (fan version)
C.T.T.C Tech Mod
OCM
Super Drois Mod
Hi-TECH Soldiers & weapons
Auto Aims
Space mod
Quick right click options
Flipping Heck
The Ultimate Minecraft mod

### Game version

Its the last on steam right now.

### Operating System

Windows 10

### Additional notes

![Desktop Screenshot 2022 12 25 - 15 46 17 43](https://user-images.githubusercontent.com/121407620/209484077-3261343c-07ad-426b-84f6-c678780a4dee.png)

**Comment by Pitatto** [comment]
I hope this will be fixed soon ;)

**Comment by Pitatto** [comment]
.

**Comment by Pitatto** [comment]
I finnaly found! Vital of Steel is now a broken mod now my game work!

**Comment by DindinYT37** [comment]
Please do not bump an issue after even less than an hour.
