### ISSUE TITLE
Large creatures

### ISSUE THREAD

**Issue by Githuber56** [studio-minus/ppg-bugs-and-requests#2586]
### Describe the bug

When a large creatrue is placed in the game , it doesn't stand up. It just dies due to it's own fat weight. If it is invincible then it will cower and bounce around and not stand up

### Clearly describe how to reproduce the bug

have a large creature in the game

### Additional notes

``

**Comment by bibbybabby** [comment]
this would happen irl too

**Comment by Drogo-man** [comment]
If its weight increases, should its muscle mas increase too?

**Comment by mestiez** [comment]
could you at least put some effort into answering all the questions lmao
