### ISSUE TITLE
ex. X does Y instead of Z

### ISSUE THREAD

**Issue by protekko** [studio-minus/ppg-bugs-and-requests#2589]
### Describe the bug

liquididentifier doesnt work on human blood corectly,
There is a item that is named liquididentifier ,and it allows you to see whats included in mixture, but it doesnt work corectly, bc if you add some mixtures to human and then chceck his blood in this item, it will say it is human blood 100%

### Clearly describe how to reproduce the bug

if you add some mixtures to human and then chceck his blood in liquididentifier, it will say it is human blood 100%

### Game version

1.25.4

### Operating System

Windows 10 

### Additional notes

i think if you fix that it will be 50% bugfix and 50% new feature. So i reported it as a bug

**Comment by ATPGaming** [comment]
Nice title, I can tell you spent a lot of time on it

**Comment by Squibard** [comment]
lol

**Comment by Drogo-man** [comment]
> Nice title, I can tell you spent a lot of time on it

i think its a bug, happened to some other guy too.

**Comment by DindinYT37** [comment]
> > Nice title, I can tell you spent a lot of time on it
> 
> i think its a bug, happened to some other guy too.

If you're talking about the bug of not filling in a title, then yes.
