### ISSUE TITLE
map issue

### ISSUE THREAD

**Issue by minatokunai** [studio-minus/ppg-bugs-and-requests#2590]
### Describe the bug

each time i load up any map it puts me into a screen with the four starter boxes that tell you how to use your buttons and my cursor turns into a box that will only move into about half the screen and i have disabled all mods to see if it works that way but that doesnt work and im stuck really because it wont let me get out of the paused menu but i can still move the box and when i click on settings the only two options are to change my binding for dragging objects and whether i want gore on or not

![ppg issue](https://user-images.githubusercontent.com/121501113/209677973-f9565696-0e64-49e9-a141-62dd1d74f0ce.png)

### Clearly describe how to reproduce the bug

i dont know how it happened i just opened a map and that happened

### Mod list

i couldnt find how to get the list of them, sorry

### Game version

1.25.4

### Operating System

windows 10

### Additional notes

![image](https://user-images.githubusercontent.com/121501113/209679985-e1f7933d-508e-4c25-b074-9e0dcd3c3a0c.png)

**Comment by DindinYT37** [comment]
Have you tried validating your game files?

**Comment by mestiez** [comment]
you are providing no information

**Comment by Drogo-man** [comment]
Oh hey Zooi, you're alive.
