### ISSUE TITLE
reisizing knife or any other stabing object makes it unable to stab

### ISSUE THREAD

**Issue by Squibard** [studio-minus/ppg-bugs-and-requests#2592]
### Describe the bug

resizing knife or any other stabbing object makes it unable to stab idk how to fix this even resizing it evenly don't work

### Clearly describe how to reproduce the bug

resize knife, sword, lance, or any other stabbing object

### Game debug info

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.19045) 64bit

 - **CPU**: AMD Ryzen 3 2200G with Radeon Vega Graphics 

 - **GPU**: AMD Radeon(TM) Vega 8 Graphics

 - **Memory**: 6 GB

## All loaded mods

	KOR_BarBeQ-BarBeQ's Firearm Collection: Glock Perfection-local v1.0 for game v1.26+
		Currently ACTIVE

	FredMichalBear-Roomba mod-local v1.0 for game v1.15
		Currently ACTIVE

	Dyadyushka Dyadya-Grip Fix-local v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Timtam-Foods+ Mod-2863076379 v1.0 for game v1.26+
		Currently ACTIVE

	Chomuske, Muurkz-Self-Defence guns mod-2895287892 v1 for game v1.24
		Currently ACTIVE

	ibiglaser-Weapon size affects its power Mod-2894415938 v1.0 for game v1.26+
		Currently ACTIVE

	ibiglaser-3D Saul Goodman Main Menu Replacer-2892071899 v1.0 for game vBIG fans of breaking bad
		Currently ACTIVE
		Has been initialised

	Kor_BarBeQ-BarBeQ's Among Us-2883838155 v1.0 for game v1.23+
		Currently ACTIVE

	Laska, Webber, Fludih-Dobromol, Quickness-Prostheses-2882002619 v1.1 for game v1.21+
		Currently ACTIVE
		Has been initialised

	Aitovege-Taser-local v1.2 for game v1.11+
		Currently ACTIVE

	ibiglaser-Secret Items Spawn Allower Mod-2880997928 v1.0 for game v1.26+
		Currently ACTIVE

	DoubleSeven-Heavy Brick-local v1.0 for game v1.8.1
		Currently ACTIVE

	Dyadyushka Dyadya-Liquid Logic-local v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Torture Mod-2870378567 v1.0 for game v1.26+ preview 5
		Currently ACTIVE
		Has been initialised

	Kyrelink-Playable Xylophone Mod-2868316027 v1.0 for game v1.15+
		Currently ACTIVE

	Tye-wynd#5219 on discord-Nuke-local v1.0 for game v1.22+
		Currently ACTIVE

	Mr_kWKD-Attachable-2866743610 v1.0 for game v1.26+
		Currently ACTIVE

	Dyadyushka Dyadya-Pose Manager-local v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya, ibiglaser improvement-[Improved] Pickup Advanced (Pickup anything)-2863389507 v1.0 for game v1.25+
		Currently ACTIVE

	Gorilla-cooler gore human-local v1.0 for game v1.22+
		Currently ACTIVE

	игор-Bomb Tech-2863195081 v1.0 for game v1.14+
		Currently ACTIVE

	Pumpkin-Doors Mod-2400494139 v1.4 for game v1.15
		Currently ACTIVE

	DreamingWarlord-PBullets-2858824981 v1.0 for game v1.25.4
		Currently ACTIVE

	Dyadyushka Dyadya-Human Dynamic Emotions 2-2856823986 v1.0 for game v1.22+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Pickup Advanced-2854748282 v1.0 for game v1.25+
		Currently ACTIVE

	ibiglaser-Abyss corruption system-2853132719 v2.0 for game v1.25+ and Dyadyushka Dyadya
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Raised severed limbs-local v1.0 for game v1.24+
		Currently ACTIVE

	Brian9171 & chonk-PPG Additions-2844222823 v0.3 for game v1.25+
		Currently ACTIVE

	Therac-25-Custom TV-2843819067 v2.0 for game v1.21+
		Currently ACTIVE

	FredMichalBear-Ruler mod-local v1.0 for game v1.15
		Currently ACTIVE

	Dyadyushka Dyadya-Fire remover button-2840340693 v1.0 for game v1.24+
		Currently ACTIVE

	Mishanya-Functional Helicopter Mod-2839691188 v0.3.1 for game v1.25+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Disable QR 01 studio-2830600051 v1.0 for game v1.24+
		Currently ACTIVE

	Engven-No spark-2497957604 v1.0 for game v1.11
		Currently ACTIVE

	Brian9171-Limb Attachments-2660556899 v0.3 for game v1.22+
		Currently ACTIVE

	DeniK-Guns+-218581565 v1.2 for game v1.9
		Currently ACTIVE

	Morzzic-Colored Wires Mod-2242324883 v1.2 for game v1.9+
		Currently ACTIVE

	Dyadyushka Dyadya-Arrows and crystals are now debris-local v1.0 for game v1.24+
		Currently ACTIVE

	hankmart-Emotional Human Template-2822924357 v1.0 for game v1.21+
		Currently ACTIVE

	catt0215-Catt's Cannons-2814325736 v6.0 for game v1.25+
		Currently ACTIVE

	Byter28-Gas Burner-2811763416 v1.0 for game vany
		Currently ACTIVE

	lisov-LISOV's Miscellaneous items-2810850541 v1.0 for game v1.14+
		Currently ACTIVE

	Orsoniks/Navii-Anti-Gravity Device-local v1.0 for game v1.23+
		Currently ACTIVE

	Quickness, Mishanya, arkstar_, Dyadyushka Dyadya, Maxe, Laska-More Vehicles-2805966221 v1.5.1 for game v1.24x
		Currently ACTIVE
		Has been initialised

	Originaly by Kelly The Dragon, Fixed By Gachatorrent64-The Tungsten Mod Fixed-2170418527 v2.4 for game v1.8 +
		Currently ACTIVE

	quidlol-Hecklefruit mod-local v1.0 for game vI dont know
		Currently ACTIVE

	Sohvaperuna-Limb Reattachment Tools-2801931724 v3.2.6 for game v1.24+
		Currently ACTIVE

	Kor_BarBeQ-Cigarette-local v1.0 for game v1.23+
		Currently ACTIVE

	Morzzic-Taser-2361892819 v1.1 for game v1.11+
		Currently ACTIVE

	Maxe & Dyadushka-Realistic Axe mod-local v1 for game vAny
		Currently ACTIVE

	loffies-The Criminal Underworld-local v1.0 for game v1.22+
		Currently ACTIVE

	Evalarian-Lawless 2-local v1.0 for game v1.23
		Currently ACTIVE
		Has been initialised

i just made it a text file and pasted it into here idk if i did it right

### Game version

2.26 preview 11

### Operating System

windows 10

### Additional notes

no

**Comment by Squibard** [comment]
i forgot about the mod list but it says it in the debug info thing

**Comment by mestiez** [comment]
#1335

**Comment by Squibard** [comment]
:( not planned
