### ISSUE TITLE
Copy-Pasted Grabbing Issue

### ISSUE THREAD

**Issue by Cowlord3001** [studio-minus/ppg-bugs-and-requests#2595]
### Describe the bug

When a human or android holding an object is copy-pasted, it cannot pick things up in that hand once it drops said object.
_E.g. A human holding a knife in its right hand is copied using the C key. It is pasted using V key. Its right hand is activated, dropping the knife. Activating its right hand now no longer grabs objects._

### Clearly describe how to reproduce the bug

1. Place an object in a human or androids hand by activating its hand near the object. This was tested with melee weapons and firearms.
2. Copy the human holding the object by selecting it and clicking "copy" in the context menu, or by selecting it and pressing the C key.
3. Paste the human holding the object by clicking "paste" in the context menu, or by pressing the V key.
4. Activate the hand holding the object, causing it to be dropped.
5. Attempt to activate the hand again near a different object. This should produce no results, as the hand can no longer grab objects.
_NOTE: Occasionally, the human or android can pick up the previously-held object again. I am unsure why this happens, but in all other scenarios, it cannot pick up objects anymore in that hand._

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10312190/exported.game.debug.info.md)

### Mod list

- AutoAim, by Puppyguard
- Halo weapons REUPLOAD, by letter
- The ULTIMATE Minecraft Mod, by Kyrelink, Quickness
- Human Tiers, by Alibarda
- Purple mod 2, by DRAGOLITE

**All Active**

### Game version

1.25.4 (64 bit)

### Operating System

Windows 10 Home

### Additional notes

If you need any additional information, feel free to get in touch!

**Comment by mestiez** [comment]
fixed!! :)
