### ISSUE TITLE
empty siringe disappears

### ISSUE THREAD

**Issue by jojosix** [studio-minus/ppg-bugs-and-requests#26]
**Describe the bug**
empty syringe disappears when smashed really hard into ground 

**Clearly describe how to reproduce the bug**
spawn empty syringe and just slam it into the ground after a couple of smashed it disappears

**Mod list**
none

**System info (please complete the following information)**
 - Operating system:  windows 10
 - Game version: 1.19 beta 
 - GPU:AMD Radeon integrated graphics 
 - CPU:AMD Ryzen 5 4500U

**Additional notes**

**Comment by jojosix** [comment]
**EDIT** did some testing it happens to all syringes

**Comment by mestiez** [comment]
This can happen if you are on discrete collision mode and the syringe stabs the inside of the floor lol

**Comment by WrillWasTaken** [comment]
> This can happen if you are on discrete collision mode and the syringe stabs the inside of the floor lol

I tried recreating this bug. It only happened on continuous collision mode.

**Comment by mestiez** [comment]
oh i see when it happens. you stab it into the ground as normal, and then you simply drag it down even further on continuous collision and 16 physics iterations.

i am not sure if i can fix this considering it is unity physics fuckery. ill try, though

**Comment by isavailablh** [comment]
this is problem i had just a little bit ago and i fixed it by just restart
