### ISSUE TITLE
optimisation for you game

### ISSUE THREAD

**Issue by Epicplushdude3** [studio-minus/ppg-bugs-and-requests#2600]
### Feature description

look, I have a pretty Beefy Computer and am only getting 4 FPS I am not a coder but still, just try and fix this thank you :)

### Feature purpose

Gameplay 

### Additional context

![Screenshot (6)](https://user-images.githubusercontent.com/121637247/209997099-5e286bae-ba79-4496-a649-60b7640d7e91.png)

**Comment by DindinYT37** [comment]
This issue is a prime example of what **not** to do when creating one.

**Comment by mestiez** [comment]
i dont know how you have managed to achieve 4 fps with "beefy computer" but i get 60+ on a laptop with integrated graphics and you're not giving me much to work with
