### ISSUE TITLE
Syringes no longer output liquid like as if the game is pre 1.19

### ISSUE THREAD

**Issue by Blessedsolaris** [studio-minus/ppg-bugs-and-requests#2601]
### Describe the bug

Syringes no longer have their post 1.19 look and dont transfer liquids anymore, making the empty syringe obsolete and so on, 1.26 broke some stuff for sure.

### Clearly describe how to reproduce the bug

try to transfer liquids between syringes using a blood vessel wire, they seem to be completely broken.

### Game version

1.26

### Operating System

windows 11

### Additional notes

![image](https://user-images.githubusercontent.com/95949529/210001468-6c5f67d3-ea04-49ec-98cc-438d32bfe74b.png)
This shows a mending syringe trying to go into an empty syringe, which doesnt work.

**Comment by DindinYT37** [comment]
I don't think that's a mending syringe…

**Comment by PossiblyRemember** [comment]
![image](https://user-images.githubusercontent.com/105954143/210019884-1f49f9cf-8465-4b6d-8288-96133484e12e.png)
I think you either may have too many mods enabled or your game is just broken (which I'd doubt), as #2603 still worked for me and so does this. Also, that is not a mending syringe, it's just a syringe coloured dark teal. The empty syringe also isn't even transparent, so none of those syringes seem original or even real.

**Comment by Squibard** [comment]
i think those are modded syringes from pre 1.19

**Comment by Blessedsolaris** [comment]
i went and validated files and it fixed the issue.

**Comment by Squibard** [comment]
> i went and validated files and it fixed the issue.

how validate

**Comment by PossiblyRemember** [comment]
> > i went and validated files and it fixed the issue.
> 
> how validate

![present](https://user-images.githubusercontent.com/105954143/210435635-9e4df8c3-34b9-4a81-85c1-8ee7943e879e.png)

**Comment by Squibard** [comment]
> > > i went and validated files and it fixed the issue.
> > 
> > 
> > how validate
> 
> ![present](https://user-images.githubusercontent.com/105954143/210435635-9e4df8c3-34b9-4a81-85c1-8ee7943e879e.png)

ok ill try it

**Comment by Squibard** [comment]
> > > > i went and validated files and it fixed the issue.
> > > 
> > > 
> > > how validate
> > 
> > 
> > ![present](https://user-images.githubusercontent.com/105954143/210435635-9e4df8c3-34b9-4a81-85c1-8ee7943e879e.png)
> 
> ok ill try it

didnt work how do i fix

**Comment by PossiblyRemember** [comment]
> > > > > i went and validated files and it fixed the issue.
> > > > 
> > > > 
> > > > how validate
> > > 
> > > 
> > > ![present](https://user-images.githubusercontent.com/105954143/210435635-9e4df8c3-34b9-4a81-85c1-8ee7943e879e.png)
> > 
> > 
> > ok ill try it
> 
> didnt work how do i fix

I'm unsure. You may have to uninstall and reinstall, although validating the files should've fixed it already. It might be a mod; you should try to disable all and see if the problem still persists, otherwise I'm clueless.

**Comment by Squibard** [comment]
> > > > > > i went and validated files and it fixed the issue.
> > > > > 
> > > > > 
> > > > > how validate
> > > > 
> > > > 
> > > > ![present](https://user-images.githubusercontent.com/105954143/210435635-9e4df8c3-34b9-4a81-85c1-8ee7943e879e.png)
> > > 
> > > 
> > > ok ill try it
> > 
> > 
> > didnt work how do i fix
> 
> I'm unsure. You may have to uninstall and reinstall, although validating the files should've fixed it already. It might be a mod; you should try to disable all and see if the problem still persists, otherwise I'm clueless.

it was a mod thx
