### ISSUE TITLE
Generators and other power sources dont show their power level

### ISSUE THREAD

**Issue by Blessedsolaris** [studio-minus/ppg-bugs-and-requests#2603]
### Describe the bug

When you activate generators or anything, they usually have a thing showing how much power it has, obviously it doesnt work thanks to the buggy 1.26 update

### Clearly describe how to reproduce the bug

activate a generator/battery/industrial generator

### Game version

1.2.6 64 bit

### Operating System

windows 11 x64

### Additional notes

![image](https://user-images.githubusercontent.com/95949529/210008613-65a161d0-0d5a-4899-a0ee-104ea3c580d2.png)

**Comment by PossiblyRemember** [comment]
Works fine for me.
![image](https://user-images.githubusercontent.com/105954143/210014937-5656304c-d876-4108-bbab-1e4345711e51.png)
Disable all of your mods and double-check that this happens.

**Comment by Blessedsolaris** [comment]
validated files, fixed issue.
