### ISSUE TITLE
Humans do not care if their limbs are removed by the disassembler

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2605]
### Describe the bug

humans dont cower in pain when they are shot by disassembler and their body part is removed

### Clearly describe how to reproduce the bug

shewt a dewd with the disappear gun weapon

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10322587/exported.game.debug.info.md)

### Additional notes

works best on the middle half (the glitchiest part of the human)

![bingbgb](https://user-images.githubusercontent.com/104321411/210022773-f0bceb32-d16c-468e-8193-b49cb16aa8ed.png)

**Comment by Squibard** [comment]
nice picture

**Comment by mestiez** [comment]
it seems like dismemberment has gone insane somewhere along the previous few releases. not only does the person not care, there is also no visual damage

**Comment by mestiez** [comment]
fixed more or less
