### ISSUE TITLE
saves and attachments are have some weirdness

### ISSUE THREAD

**Issue by whydoIextist** [studio-minus/ppg-bugs-and-requests#2607]
### Describe the bug

1.26 just released and here comes some new janky mechanics (the bug is visual only but its weird)
[Img](https://steamcommunity.com/sharedfiles/filedetails/?id=2909355854)

### Clearly describe how to reproduce the bug

so basically if you save a gun with an attachment and then load its somewhere, is says there's open slots but there's not any (also works with copy and paste)

### Mod list

- [S.T.A.L.K.E.R.: heart of PPG](https://steamcommunity.com/sharedfiles/filedetails/?id=2904257651)

- [More Vehicles](https://steamcommunity.com/sharedfiles/filedetails/?id=2805966221)

- [Mellon Playground Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2794290608)

- [Level A-D Protection (Hazmat Suit Mod 2)](https://steamcommunity.com/sharedfiles/filedetails/?id=2710183571)

- [Tactical Armors](https://steamcommunity.com/sharedfiles/filedetails/?id=2334842610)

- [Hold K to make wires invisible](https://steamcommunity.com/sharedfiles/filedetails/?id=2137429065)

All active

### Game version

1.26

### Operating System

Windows 10

### Additional notes

can you add some upper versions of attachments zooi?

**Comment by mestiez** [comment]
fixed :)
