### ISSUE TITLE
Jet Engine Bug

### ISSUE THREAD

**Issue by End3rdragon1234** [studio-minus/ppg-bugs-and-requests#2608]
### Describe the bug

The jet engine does not get powered up by generators, batteries, etc.

### Clearly describe how to reproduce the bug

Attaching the conductive wire to a jet engine and a generator, etc, does not power the jet engine up. Could you please fix? Thank you

**Comment by DindinYT37** [comment]
Because the Jet Engine cannot be powered.

**Comment by mestiez** [comment]
Correct, this is not a bug.

**Comment by End3rdragon1234** [comment]
Why is it like that?
