### ISSUE TITLE
Stabbed syringes stop working after loading

### ISSUE THREAD

**Issue by Smrtonosan** [studio-minus/ppg-bugs-and-requests#2609]
### Describe the bug

Syringes will stop injecting or drawing blood to attached entities if they are saved/copied and pasted together.

### Clearly describe how to reproduce the bug

Stab Human with empty syringe, check if it sucks and injects blood, while the syringe is still injected copy the human and syringe, (or save it to locals), paste human and syringe together, syringe is still attached but wont neither suck or inject blood. (Check if it does)

![Ligma](https://user-images.githubusercontent.com/104994469/210087587-5bfd486c-2f26-4690-9690-2db31865384a.gif)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10325362/exported.game.debug.info.md)

### Additional notes

Applies to all entities not just humans.
![20221230164737_1](https://user-images.githubusercontent.com/104994469/210088282-fa4e391d-fde7-4bb2-9c0a-5cc841855255.jpg)

**Comment by mestiez** [comment]
fixed :)
