### ISSUE TITLE
Deflated tyre appears inflated after deserialisation

### ISSUE THREAD

**Issue by mestiez** [studio-minus/ppg-bugs-and-requests#2610]
### Describe the bug

The tyre isn't squished like it should be after being deflated and then pasted

### Clearly describe how to reproduce the bug

- Spawn car
- Shoot tyre
- Copy
- Paste
- Observe as the tyre behaves deflated but appears inflated

### Game version

1.26.1

### Operating System

Windows 10 Pro 10.0.19044

**Comment by Aspa102** [comment]
self report

**Comment by mestiez** [comment]
fixed
