### ISSUE TITLE
Procedural fragments should be removed with a human "owner" after deletion

### ISSUE THREAD

**Issue by MaxeUA** [studio-minus/ppg-bugs-and-requests#2613]
### Describe the bug

as stated above procedural fragments should be removed with a human owner after deletion, means that the fragments created should despawn as a decal with it's owner, like it happens with car compartments.

### Clearly describe how to reproduce the bug

![image](https://user-images.githubusercontent.com/93492953/210137044-2e80ab18-e539-4216-90fc-7695133e55ee.png)
![image](https://user-images.githubusercontent.com/93492953/210137050-d6c35312-4329-40b3-9235-e54b92ecbd68.png)
![image](https://user-images.githubusercontent.com/93492953/210137052-30e24ecc-4cd9-4976-ac27-d989f1c0f076.png)

### Game version

1.26

**Comment by mestiez** [comment]
it is done
