### ISSUE TITLE
Red barrel exlposion is stopped by materials with disabled collision

### ISSUE THREAD

**Issue by MaxeUA** [studio-minus/ppg-bugs-and-requests#2614]
### Describe the bug

I dont think that this is supposed to be so, that basically invisible stuff stops the explosion wave and prevents ignition of stuff standing behind it

### Clearly describe how to reproduce the bug

![image](https://user-images.githubusercontent.com/93492953/210152263-175d7ef6-dcc8-4657-8c04-0c60ff99b4ec.png)

**Comment by royalealbert27** [comment]
That's how most explosions work

**Comment by Squibard** [comment]
its annoying sometimes

**Comment by mestiez** [comment]
fixed :)
