### ISSUE TITLE
Optimisation of objects that do not move

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2623]
### Feature description

If an object does not move or moves no more than x units within y seconds, the object should go to "sleep"

### Feature purpose

The game will lag less when object quantity is high

### Additional context

The Source engine has it

**Comment by DindinYT37** [comment]
This should naturally also be the case with frozen objects.

**Comment by mestiez** [comment]
This already happens. Sleeping rigidbodies are built into Box2D
