### ISSUE TITLE
something that is able to delete the undeletable

### ISSUE THREAD

**Issue by cuptaza** [studio-minus/ppg-bugs-and-requests#2629]
### Feature description

a part that deletes anything, forcefully on touch

### Feature purpose

undeletable parts are really annoying

**Comment by royalealbert27** [comment]
You wanna delete the map?

**Comment by DindinYT37** [comment]
I'm pretty sure undeletable parts that you might want to get rid of can only be created using mods anyway, though?

**Comment by Squibard** [comment]
what do you mean by undeletable
