### ISSUE TITLE
Human sounds and guts.

### ISSUE THREAD

**Issue by Darky55** [studio-minus/ppg-bugs-and-requests#2631]
### Feature description

it would be a nice addition to the gore system if there were guts. like in the older version when you would rip someone in half you could see intestines or whatever they were. and some sounds would also be cool, such as coughing on blood or crying and screaming ect. There are some mods that do it but they arent that good.

### Feature purpose

this would make the game more immersive and realistic, I have used some mods in the past to simulate this and it made my experience playing the game better.

**Comment by royalealbert27** [comment]
So add advanced gore back and screaming humans mod

**Comment by mestiez** [comment]
humans will never make any human noises

**Comment by mestiez** [comment]
it is just too disturbing and does not fit the game

**Comment by ATPGaming** [comment]
> it is just too disturbing and does not fit the game

It's a sickly, vile, brutal game about mutilating them into piles of flesh, how is it too disturbing?

**Comment by bibbybabby** [comment]
> > it is just too disturbing and does not fit the game
> 
> It's a sickly, vile, brutal game about mutilating them into piles of flesh, how is it too disturbing?

Imagine a human walking a little too hard and going "AHUFHEAHAEHAHHH UEAHHHH AAAAAAAAAA"
