### ISSUE TITLE
Guns that discharge if dropped from high height/large impact

### ISSUE THREAD

**Issue by treefittyy** [studio-minus/ppg-bugs-and-requests#2649]
### Feature description

A random chance that when a gun falls or is dropped it will fire off a shot on impacting with ground/wall

### Feature purpose

Could be a menu toggle, Think it would add a bit of realism.

Item collision and binds could be problematic with such systems.

**Comment by Drogo-man** [comment]
already in the game.

**Comment by treefittyy** [comment]
> already in the game.

Can you give me a repeatable example I can test? I've yet to see this in my own game.

**Comment by Squibard** [comment]
i wish chanced were higher

**Comment by treefittyy** [comment]
Thanks was finally able to get a single shot off! Definitely agree on it being a higher frequency thing.
