### ISSUE TITLE
Option to turn off spitting on gorse. Sword/Knife that poisons entitys. Mutations of human or being able to mix and match different entities together into one creature.

### ISSUE THREAD

**Issue by ReptileFrog** [studio-minus/ppg-bugs-and-requests#2652]
### Feature description

Option when right-clicking to turn off acid spit on gorse. A sword or throwing knife that poisons things. Being able to mutate humans or being able to swap body parts with other creatures with a tool.

### Feature purpose

Idk they all sound like fun ideas. I requested these features because I find myself trying to do these things manually and they never work. Don't think these exist without attaching items together with a cable.

**Comment by Drogo-man** [comment]
Multi request = big nono
Also you can stop a gorse from spottting by breaking it's head bone

**Comment by mestiez** [comment]
Please separate each request into its own issue
