### ISSUE TITLE
Humans do not die of cardiac arrest

### ISSUE THREAD

**Issue by Frederick-7689** [studio-minus/ppg-bugs-and-requests#2654]
### Describe the bug

If you click "Break bone" on "Upper Body", the human will go into cardiac arrest but will not lose blood pressure.

### Clearly describe how to reproduce the bug

-Interact with the upper body of a human being and select "Break Bone".
-Use "Inspect" or "S" to see the blood pressure, and thus also its integrity, remain unchanged.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10396734/exported.game.debug.info.md)

**Comment by mestiez** [comment]
fixings
