### ISSUE TITLE
Crushing every limb of a human removes the generated fragments

### ISSUE THREAD

**Issue by NeonSkye** [studio-minus/ppg-bugs-and-requests#2655]
### Describe the bug

when you crush a human with the procedural fragments option on, fragments spawn. Crushing every limb deletes all the fragments once the last limb is destroyed.

### Clearly describe how to reproduce the bug

go to play, default map

1. Turn on the option for fragments
2. Spawn human
3. Spawn 1 ton weight
4. Crush every limb
5. fragments disappear

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10407007/exported.game.debug.info.md)

### Game version

game version 1.26.2 (64 bit) using unity 2020.3.1f1

### Operating System

Windows 10

### Additional notes

![Screenshot_22](https://user-images.githubusercontent.com/92863316/212207112-c97f74d7-004c-439d-8d8b-0110deec47cc.png)
![image](https://user-images.githubusercontent.com/92863316/212207118-e0080f6a-2c48-4971-bc93-64cd319d3cc8.png)

**Comment by PossiblyRemember** [comment]
This has been fixed, it just isn't released yet. There is a [changelog](https://github.com/studio-minus/people-playground-changelog/commit/b67d5c069369a17bf8e3d194ae2aa7b03a75b595) that shows recent changes and bug fixes to the game.
