### ISSUE TITLE
Sounds are not played when bell is shot except the bell sound

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2657]
### Describe the bug

When a bell that is slanted on a thing is shot, only the bell plays

### Clearly describe how to reproduce the bug

Shoot a bell that is by a thing

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10408418/exported.game.debug.info.md)

### Additional notes

https://user-images.githubusercontent.com/104321411/212243332-8294dac0-71f1-4216-bd50-461cb5fd0d50.mp4

**Comment by mestiez** [comment]
this happens because the bell sound is quite lengthy and it takes up all the available "voices" in the audio engine. it is more of a limitation than it is a bug.
