### ISSUE TITLE
Move some things to another category

### ISSUE THREAD

**Issue by Quickness19** [studio-minus/ppg-bugs-and-requests#266]
**Feature description**
*Rod, Stick, Plank* move to the category Misc.
*De staf van Sinterklaas* move to the category Melee
*Physics Gun* move to the category Firearms

**Feature purpose**
I think these things are in the wrong places and should be moved

**Additional context**
none.

**Comment by idotwaffle** [comment]
why do you think they should be moved, i like them where they are
