### ISSUE TITLE
It is now nearly impossible to stab gorse

### ISSUE THREAD

**Issue by B-Knots** [studio-minus/ppg-bugs-and-requests#2661]
### Describe the bug

The gorse are now almost invulnerable to stabbing, with a sharp object now acting more like a blunt object against them.

### Clearly describe how to reproduce the bug

-spawn in gorse

-try to stab (seems to only do it one in ten times)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10416516/exported.game.debug.info.md)

### Mod list

-Alien vs predator mod (Inactive)

### Game version

1.26.2

### Operating System

windows 10

**Comment by mestiez** [comment]
Duplicate of #2794 ??
