### ISSUE TITLE
when you spawn a human without activating health bars you cant enable it after it got spawned same with if you do it with health bars

### ISSUE THREAD

**Issue by Golden193** [studio-minus/ppg-bugs-and-requests#2665]
### Describe the bug

the human cant have the health bars by pressing s and if you spawn it with the health bars you cant disable the health bars they just keep being there and the health bars still work if you hurt the human

### Clearly describe how to reproduce the bug

spawn a human without health bars now press s and they will not show up same if you had it on so press s then spawn a human then press s again and it wont disappear idk it might be just my computer

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10418499/exported.game.debug.info.md)

### Game version

1.26 preview 3

### Operating System

windows 10

### Additional notes

i tryed to get a video of it but after i had to quit to get the debug info when i went back on a map it didnt do it

**Comment by Golden193** [comment]
also i have i glitch that i have to sometimes restart my computer to get people playground to work but i think its just me

**Comment by Drogo-man** [comment]
1. What drugs are you on, I want some.
2. Same bruh, I had to restart my PC like 5 times just to play Minecraft.

**Comment by bibbybabby** [comment]
disable the make everything invisible mod

**Comment by mestiez** [comment]
Yes. This is a bug caused by the [Make Anything Invisible](https://steamcommunity.com/sharedfiles/filedetails/?id=2864708184) mod.
