### ISSUE TITLE
Nothing added into files affects the game.

### ISSUE THREAD

**Issue by beanman0** [studio-minus/ppg-bugs-and-requests#2667]
### Describe the bug

I could add something like a music file for the jukebox, or a mod into my files and nothing is happening when I open the game. The files added into the game folders don't load.

### Clearly describe how to reproduce the bug

No real way to reproduce as I found no one else with this problem so far, but all that I've done is add something into the files, loaded the game, and nothing worked.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10418775/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
What was your goal?

**Comment by beanman0** [comment]
> What was your goal in the first place?

To make a sort of skin mod over the human without replacing the base human entity. That was what started it. Later, I tried putting in music to a jukebox folder and that didn't work either.

**Comment by mestiez** [comment]
It is possible you have two identical directories for PPG and you are not opening the correct one. Though, you are not really providing much information for anyone here to work with. Besides, this board is for game bugs, not individual technical issues.
