### ISSUE TITLE
steel binding isn't fixed and is barely destructible

### ISSUE THREAD

**Issue by sp22222222** [studio-minus/ppg-bugs-and-requests#2668]
### Describe the bug

steel binding isn't fixed. it can stretch across the map (while having no stress, therefore not breaking) or be crushed, and instead of being under stress and then breaking, it squishes down, and doesn't break.

### Clearly describe how to reproduce the bug

stretching across map:
attach something like a head to a human.
![image](https://user-images.githubusercontent.com/118778597/212522851-841c0ea2-4f7d-452e-b977-9a93c25ff94f.png)
hit said human with a bat multiple times.
watch as the contortion begins.
![image](https://user-images.githubusercontent.com/118778597/212522887-8e599298-af40-4990-896d-fbf0f8a3cce4.png)

crushing
create a chair that isn't directly attached to the ground
![image](https://user-images.githubusercontent.com/118778597/212522971-0ae607d1-abd3-4fd8-896d-e6043df18cdb.png)
sit a human on said chair.
![image](https://user-images.githubusercontent.com/118778597/212522983-86a348cc-8913-4ddf-ba69-46397b2bc017.png)
the chair will break apart and compress.

### Mod list

water physics (inactive)
grip fix (inactive)
hardbass mod (inactive)
liquid machinery (inactive)
wiredit (inactive)

### Game version

1.26.2

### Operating System

Windows 10

**Comment by Drogo-man** [comment]
This is just unity fuckery.

**Comment by mestiez** [comment]
This _is_ unity fuckery but there are two solutions:
- Increase physics iterations
- The game should really group these objects such that they share one rigidbody
But that is a well known problem and this issue doesn't really add much to the discussion

**Comment by Drogo-man** [comment]
I'll keep this In mind if I ever decide to put my hands on unity again.... If.
