### ISSUE TITLE
Ability to repair the turret

### ISSUE THREAD

**Issue by Quickness19** [studio-minus/ppg-bugs-and-requests#267]
**Feature description**
As with all breakable metal objects, the ability to repair a turret with a wrench

**Feature purpose**
hits the turret with a wrench

**Additional context**
none

**Comment by mestiez** [comment]
How is "hits the turret with a wrench" a purpose???

**Comment by Quickness19** [comment]
> How is "hits the turret with a wrench" a purpose???
**Feature purpose** EDIT
When the turret turns over, it shuts down, and I'd like to see the ability to fix it with a wrench like other metal objects. This would add another interaction to the game.
