### ISSUE TITLE
Tank starts without Tank

### ISSUE THREAD

**Issue by Frederick-7689** [studio-minus/ppg-bugs-and-requests#2677]
### Describe the bug

Removing a tank's fuel tank will not be enough to stop its murderous rampage.

![video](https://user-images.githubusercontent.com/102178009/213022210-cc929e20-c51e-4333-982b-3204c5bdc16c.gif)

### Clearly describe how to reproduce the bug

-Remove the fuel tank from the tank (the bug does not reproduce if the tank is blown up).
-Activate the tank

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10439747/exported.game.debug.info.md)

### Additional notes

Apparently this is not the case for other vehicles.

**Comment by Drogo-man** [comment]
Bluetooth fuel pump.

**Comment by mestiez** [comment]
fixed :)
