### ISSUE TITLE
asbestos thrower that will make things dont burn and kill humans slowly by killing their lungs and making them die

### ISSUE THREAD

**Issue by username90001** [studio-minus/ppg-bugs-and-requests#2681]
### Feature description

asbestos thrower makes things dont burn even humans
but it kills humans by killing their lungs 

### Feature purpose

we need make things dont burn
like half sphere from wood i forgot how is it called trees and other things
it can be usefull with maps with alot of things that burn to make them dont lag from fire

**Comment by mestiez** [comment]
weirdly specific
