### ISSUE TITLE
wires/tools bug

### ISSUE THREAD

**Issue by w3st3rn** [studio-minus/ppg-bugs-and-requests#2682]
### Describe the bug

Bandages, wires, cables etc remain visible but not connected (sometimes)

### Clearly describe how to reproduce the bug

No steps to reproduce, just random.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10449104/exported.game.debug.info.md)

### Mod list

Too many to list would take me 30 minutes

### Game version

1.26 [beta]

### Operating System

Windows 10

### Additional notes

![5ddf7a22966860af74f27ba69cd0d160](https://user-images.githubusercontent.com/123009005/213254817-40127faa-bf51-4268-9367-6f5c937854b6.png)

https://gyazo.com/5ddf7a22966860af74f27ba69cd0d160

**Comment by mestiez** [comment]
I can't do anything without the steps to reproduce it.
