### ISSUE TITLE
Filter profanity text option

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2687]
### Feature description

If this setting is on, bad words will be censored with asterisks or hashes or whatever

This will work like the steam censor option (maybe even reuse the list?)

### Feature purpose

so kids won't get grounded when parents see bad words

### Additional context

![image](https://user-images.githubusercontent.com/104321411/213817232-2dd9c7cc-f6c5-4951-8df4-6749de9b861c.png)

**Comment by DindinYT37** [comment]
What is this request for? The game?

**Comment by bibbybabby** [comment]
Yes

**Comment by Squibard** [comment]
> What is this request for? The game?

no bro its for mars

**Comment by DindinYT37** [comment]
> Yes

What is it supposed to do though, filter contraption/mod names?

**Comment by bibbybabby** [comment]
> > Yes
> 
> What is it supposed to do though, filter contraption/mod names?

Filter text displays

**Comment by DindinYT37** [comment]
> > > Yes
> > 
> > 
> > What is it supposed to do though, filter contraption/mod names?
> 
> Filter text displays

I guess, but I'm pretty sure you can delete and edit those freely?

**Comment by Drogo-man** [comment]
Ah yes, because parents are gonna get mad when the games has "frick" in it.

**Comment by bibbybabby** [comment]
> Ah yes, because parents are gonna get mad when the games has "frick" in it.

Well goreless mode got added though

**Comment by bibbybabby** [comment]
> > > > Yes
> > > 
> > > 
> > > What is it supposed to do though, filter contraption/mod names?
> > 
> > 
> > Filter text displays
> 
> I guess, but I'm pretty sure you can delete and edit those freely?

Yea until there's too many or they are hidden and automating it would be good

**Comment by DindinYT37** [comment]
> > Ah yes, because parents are gonna get mad when the games has "frick" in it.
> 
> Well goreless mode got added though

I think there's quite a difference in gore and profanity.

**Comment by bibbybabby** [comment]
> > > Ah yes, because parents are gonna get mad when the games has "frick" in it.
> > 
> > 
> > Well goreless mode got added though
> 
> I think there's quite a difference between gore and profanity.

So slurs and cussing is a-ok but oooh red blood you're grounded grounded grounded for 320873791 decades now go to your room now

**Comment by DindinYT37** [comment]
> > > > Ah yes, because parents are gonna get mad when the games has "frick" in it.
> > > 
> > > 
> > > Well goreless mode got added though
> > 
> > 
> > I think there's quite a difference between gore and profanity.
> 
> So slurs and cussing is a-ok but oooh red blood you're grounded grounded grounded for 320873791 decades now go to your room now

I was against the goreless mode, you're saying this to the wrong person. Also, there's still a difference between a corpse with blood all around it and several wounds on it and a word like “frick”.

**Comment by bibbybabby** [comment]
> > > > > Ah yes, because parents are gonna get mad when the games has "frick" in it.
> > > > 
> > > > 
> > > > Well goreless mode got added though
> > > 
> > > 
> > > I think there's quite a difference between gore and profanity.
> > 
> > 
> > So slurs and cussing is a-ok but oooh red blood you're grounded grounded grounded for 320873791 decades now go to your room now
> 
> I was against the goreless mode, you're saying this to the wrong person. Also, there's still a difference between a corpse with blood all around it and several wounds on it and a word like “frick”.

You're just comparing extremitys here... It's just as saying "There is a difference between a paper cut and the n-word"

**Comment by mestiez** [comment]
game doesn't come with profanity
