### ISSUE TITLE
I dont may to Publish an contraprion to the steam workshop.

### ISSUE THREAD

**Issue by TigerTheTenk** [studio-minus/ppg-bugs-and-requests#2691]
### Describe the bug

I not may to publish the contraption!

1. I try to publish an build, but when the i see page of build... I SEE THAT FU.KIN... SHI... 
![20230121110512_1](https://user-images.githubusercontent.com/123233932/213857549-73135bce-8d72-4ae1-81cc-5ccd7916c3c2.jpg)
I want to fix that... Because i'm an builder, and that for me is a fatal damage...

### Clearly describe how to reproduce the bug

I don't know. But that need fix,

### Game debug info

![20230121110512_1](https://user-images.githubusercontent.com/123233932/213858098-862eb023-5ff4-49e6-a8c0-33d6f77efdd8.jpg)

### Mod list

Flipping heck, Hold K to make wires invisible

### Game version

1.26.3

### Operating System

Windows 10

**Comment by TigerTheTenk** [comment]
Video where i show that: https://www.youtube.com/watch?v=LVii-hJzmaA

**Comment by bibbybabby** [comment]
Change the visibility setting

**Comment by TigerTheTenk** [comment]
LOL... You see what in page of workshop? Guy...

> Change the visibility setting

**Comment by mestiez** [comment]
You cannot upload content from a family shared game. Regardless, this isn't a game bug. It's Steam related.

**Comment by TigerTheTenk** [comment]
And how to fix that?

**Comment by TigerTheTenk** [comment]
How delete the family share?

**Comment by TigerTheTenk** [comment]
I just dont know... I really see anything about that in frist time...
