### ISSUE TITLE
really bad memory leak

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#2693]
### Describe the bug

i opened the game and after half an hour my game spiked to 20gb of memory using all of my ram, restarted the map and it only went up 

### Clearly describe how to reproduce the bug

open any map and leave it for about 30 minutes

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10473918/exported.game.debug.info.md)
![image](https://user-images.githubusercontent.com/68799477/213905534-797a7aa1-6110-4e15-91a3-56837891ad91.png)

**Comment by PossiblyRemember** [comment]
You have 103 mods enabled. You should disable all of them and see if the problem still occurs.

**Comment by mestiez** [comment]
the amount of mods is just far too great for me to determine that this can be fixed by me lmao
