### ISSUE TITLE
Cluster Bomb

### ISSUE THREAD

**Issue by ATPGaming** [studio-minus/ppg-bugs-and-requests#2700]
### Feature description

It's a massive metal shell that opens when activated and drops general-purpose bombs (the bombs dropped would be phase linked)

### Feature purpose

It would be a very fun explosive to kill humans with and also add more explosives since there aren't that many right now

### Additional context

![image](https://user-images.githubusercontent.com/109692890/214203288-9834aca1-5707-474a-ae7d-4bd290ef96ee.png)

**Comment by ATPGaming** [comment]
Nevermind

**Comment by username90001** [comment]
it is warcrime
