### ISSUE TITLE
Engine

### ISSUE THREAD

**Issue by Betryx** [studio-minus/ppg-bugs-and-requests#2701]
### Feature description

Add an actuall fully working engine that can power or transfer power via the drive band.

### Feature purpose

it would be fun

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #1229
* #1256
* #1425

**Comment by username90001** [comment]
> ### Feature description
> Add an actuall fully working engine that can power or transfer power via the drive band.
> 
> ### Feature purpose
> it would be fun
> 
> ### Additional context
> _No response_

u can do engine using electricity transformer detectors and boom boom or something like this
