### ISSUE TITLE
A bunch of cool requests

### ISSUE THREAD

**Issue by venixals** [studio-minus/ppg-bugs-and-requests#2702]
### Feature description

- The obvious first idea would be a world editor. The ability to place map blocks, shapes, or even drawing terrain would be an amazing tool for builders to play with. But this suggestion is far too obvious to make. It's mostly here since it's basically the standard to suggest something like this.

- Surface property modifications
It would be pretty sweet to be able to modify the properties of the floor to behave differently. Perhaps you'd want a certain amount of the floor to behave like quicksand? Or maybe make the floor bouncy like a trampoline? Or slide around like ice? Or what if the walls were sticky? There are a lot of interesting possibilities with this.

- Surface visibility/colors
Imagine having your world colored to fit a theme? Maybe make the walls/ceilings invisible, add a blue sky, and a green ground? Make the grids invisible? Perhaps some background textures like clouds, space, mountains in the distance, a city in the background? That could be a very fun tool to tinker with.

-Lighting ideas
What if you could change the color/brightness/intensity of the world's lighting, to change the overall mood of the world you're making? I imagine it wouldn't be too hard to add in, and it could be a pretty fun addition.

### Feature purpose

The game is a sandbox afterall, i think these properties would be cool 🤷‍♂️

### Additional context

Credit due to - Maelstrom for the ideas

**Comment by ATPGaming** [comment]
Please do not multi request next time

**Comment by Squibard** [comment]
> Please do not multi request next time

why

**Comment by bibbybabby** [comment]
> > Please do not multi request next time
> 
> why

its hard for zooi to accept multirequests because its either all or nothing

**Comment by B-Knots** [comment]
Focus on the map editor, thats what i would want the most

**Comment by mestiez** [comment]
Please separate your requests into their own issues.
