### ISSUE TITLE
Sweat

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2704]
### Feature description

Biologically, humans are known for having a lot of sweat glands, this should be reflected ingame. Shock, heart attacks, low blood pressure, high temperatures etc. should make humans sweaty. Sweat makes them slippery, cools them down, moisturises them, protects a bit from fires etc

### Feature purpose

Realism

**Comment by ATPGaming** [comment]
This would make humans feel more sentient I think, which is good because they feel a bit lifeless currently
