### ISSUE TITLE
Acidic syringe gun

### ISSUE THREAD

**Issue by nate-4000** [studio-minus/ppg-bugs-and-requests#2705]
### Describe the bug

When shooting any liquid, even no liquid out of a syringe gun, the gun causes gorse acid to go into the bloodstream as well as the liquid.

### Clearly describe how to reproduce the bug

Grab a syringe gun
Put life serum in it
Point at human
Shoot 
Wait

### Mod list

No mods, vanilla

### Game version

1.26

### Operating System

Windows 10

**Comment by bibbybabby** [comment]
what do you mean syringe gun?

**Comment by Squibard** [comment]
the shower head thing?

**Comment by nate-4000** [comment]
The gun in the latest update, comes from #2638

**Comment by bibbybabby** [comment]
> The gun in the latest update, comes from #2638

There is no accepted feature tag...

**Comment by bibbybabby** [comment]
I checked and there is no syringe gun in the game, are you 100% absolutely sure that you do not have any mods installed, including disabled ones?

**Comment by DindinYT37** [comment]
There is no syringe gun in the game, this was definitely modded. Which further confirms my theory that people just keep lying about not having any mods active.

**Comment by Squibard** [comment]
yeah i think he lied just so he didnt have to put a mod lists thing

**Comment by DindinYT37** [comment]
> yeah i think he lied just so he didnt have to put a mod lists thing

He could've just exported his Game Debug Info, it includes all of his mods.

**Comment by Squibard** [comment]
> > yeah i think he lied just so he didnt have to put a mod lists thing
> 
> He could've just exported his Game debug info, it includes all of his mods.

he probally didnt know
