### ISSUE TITLE
All mods say error

### ISSUE THREAD

**Issue by tikislizfr** [studio-minus/ppg-bugs-and-requests#2708]
### Describe the bug

whenever I start people playground my mods say error i try to recompile it doesn't work I have reinstalled people playground and the mods and didn't work.

### Clearly describe how to reproduce the bug

I am not sure how to make it happen
![image](https://user-images.githubusercontent.com/114265073/215306410-28c176d4-236a-4349-b57b-ff11458c8a31.png)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10529022/exported.game.debug.info.md)

### Mod list

![image](https://user-images.githubusercontent.com/114265073/215306474-8df66a33-a576-422f-9cbd-11cb0bbf92aa.png)
![image](https://user-images.githubusercontent.com/114265073/215306488-147be9a4-40b4-4c68-bb9e-0b511b324968.png)
![image](https://user-images.githubusercontent.com/114265073/215306494-883a3b29-bda8-4bec-b9e8-dacf7b510975.png)
![image](https://user-images.githubusercontent.com/114265073/215306508-a10f46c3-1b3e-4227-b87f-e55fc2e4e388.png)

### Game version

1.26.4

### Operating System

windows 11

**Comment by mestiez** [comment]
Seems like the game can't get access to the required files, 

- Are two instances of PPG running? 
- Are you playing the game from a different Windows account?
- Try starting the game in admin mode just to be sure
- Restart Steam?
- Restart PC?'

This board is not a tech support board, it's mostly  for universal game bugs.
