### ISSUE TITLE
1.26 Bug

### ISSUE THREAD

**Issue by Joydiixx** [studio-minus/ppg-bugs-and-requests#2709]
### Describe the bug

I am the coder of mod The Henry Stickmin Collection, after 1.26 update, some body textures are not working at all, and showing up default ones.

### Clearly describe how to reproduce the bug

1. Having The Henry Collection mod installed, 2. Spawning up Right Hand Man Reborn, Reginald Copperbottom or Goeffrey, 3. Models are default, now.

### Mod list

The Henry Stickmin Collection

### Game version

1.26

### Operating System

Windows 10

**Comment by mestiez** [comment]
Could you at least post the log and the actual mod? Also your title is anything but descriptive.

**Comment by Joydiixx** [comment]
.

**Comment by DindinYT37** [comment]
Wrong log.
