### ISSUE TITLE
Default models spawn (2x)

### ISSUE THREAD

**Issue by Joydiixx** [studio-minus/ppg-bugs-and-requests#2710]

**Comment by DindinYT37** [comment]
Removing the contents of your issue doesn't hide it, as it's still visible in the edit-logs.

**Comment by DindinYT37** [comment]
Deleting the original version from the edit-logs doesn't hide it, if people have emails enabled (for example), they still have the email with the original content. Generally, I don't understand why you would try to hide your mistake at this point.
