### ISSUE TITLE
Default models in mod.

### ISSUE THREAD

**Issue by Joydiixx** [studio-minus/ppg-bugs-and-requests#2712]
### Describe the bug

https://snipboard.io/1bupnV.jpg Link, for the photo. When I spawn chars with names : Reginald Copperbottom, Geoffrey Plumb, Right Hand Man Reborn - there are default models, either invinsible model, excluding the hat. Modification are fine, same goes for sprites or even code.

### Clearly describe how to reproduce the bug

Whatever how much mods I have installed, even if just one, in workshop, that glitch happens. All you need, is spawn one of 3 those models, and you'll see - it have no own texture. Haven't meet with such problem, before 1.26 got released.

### Game debug info

[Player.log](https://github.com/studio-minus/ppg-bugs-and-requests/files/10530303/Player.log)

### Mod list

https://steamcommunity.com/sharedfiles/filedetails/?id=2523047054

### Game version

1.26.4 

### Operating System

Win 10

**Comment by mestiez** [comment]
this should be reported to the mod author
