### ISSUE TITLE
Increase detectors range up to 100 meters

### ISSUE THREAD

**Issue by PhoeNiX1389** [studio-minus/ppg-bugs-and-requests#2738]
### Feature description

I like to make weapons, machines and stuff.
And when i try to make something that detects living beings or movement, it is too late, bc the detector only has a range of 20 meters max.

### Feature purpose

For longer detection.

**Comment by Mesalon** [comment]
Power it to increase range.

**Comment by username90001** [comment]
if u need more power than 1000 use energy transformer with tons of signal wires or it is just because i use mods 
does game have power limit at 1000 or i just use mods to go farther than limit?

**Comment by PhoeNiX1389** [comment]
Oh ok, so i think i dont need any new features lmao
