### ISSUE TITLE
can you make it for mac please

### ISSUE THREAD

**Issue by nugitttcat** [studio-minus/ppg-bugs-and-requests#2739]
### Feature description

i LOVED this game, but i had to get a mac because my old pc stoped working. .

### Feature purpose

the reason that i am writing this is because this was my favorite game before my pc stoped working.

### Additional context

i miss this game.
ps you don't need a mac to code a game for mac you can ask steam about it

**Comment by Squibard** [comment]
why get mac when mac more expensive get pc

**Comment by nugitttcat** [comment]
it had more fps then my old pc
{i just found it at my dads house, so i bought it off of him

**Comment by Squibard** [comment]
> it had more fps then my old pc ps it is a mini mac

k

**Comment by nugitttcat** [comment]
please

**Comment by mestiez** [comment]
I have no interest in MacOS and I don't have a Mac to test anything on anyway

**Comment by nugitttcat** [comment]
the mac users can test it for you

**Comment by nugitttcat** [comment]
at least try. please

**Comment by Buggem** [comment]
It's purely Apple's fault. They removed 32-bit apps having the effect that Windows API emulators like Proton can't run. Apple's behavior is horrible. I like all computers from Dells to Macs but personally hate the decisions made by Apple.
