### ISSUE TITLE
Magazine Feature

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#274]
Ya know have ammo in the guns and when it runs out you dont actually manually put in a mag that would be a pain in the ass so when you run out your mag drops and your gun is empty so the slide is back and you press F and its loaded again.

The purpose is maybe some people (including me) dont like the infinite ammo thing.

(Note: Do not make this a feature but rather make it a general setting)

**Comment by vda8** [comment]
there is a mod for this https://steamcommunity.com/sharedfiles/filedetails/?id=2761082698
