### ISSUE TITLE
Gore decorations

### ISSUE THREAD

**Issue by Squibard** [studio-minus/ppg-bugs-and-requests#2742]
### Feature description

like where u can spawn in fragments like the procedural ones b ut there items for decorations and stuff

### Feature purpose

for making cool scenes for screenshots

### Additional context

no

**Comment by bibbybabby** [comment]
So you mean bones and organs and tissue blocks?

**Comment by Squibard** [comment]
> So you mean bones and organs and tissue blocks?

i wasnt thinking organs but all the other yes

**Comment by nugitttcat** [comment]
this is good
