### ISSUE TITLE
Grenade fragmentation and deadliness

### ISSUE THREAD

**Issue by NOxNXME** [studio-minus/ppg-bugs-and-requests#2747]
### Feature description

Handgrenades must have a more realistic explosion radius and rely more on its ~260 fragments flying everywhere to cause damage, and therefore it would need 3 new damage radiuses:
 Instant death: from point blank to 2m, the explosion and the shrapnel are very concentrated in this area and will turn a human to dust.
  Major shrapnel damage: from 2m to 15m, there is still a bunch of shrapnel which can be very damaging and still has a good chance to kill, it will not rip limbs off anymore but can kill if it hits just the right spot.
   Minor shrapnel damage: 15m-75m, if the fragments havent lost all their energy in the obstacles nearby yet then they will continue traveling until they hit something

### Feature purpose

The purpose is to increase realism in grenades and make them more deadly to soft targets at a little larger distances as a grenade can become useless because its further than 2.5m from the soft target.

### Additional context

![image](https://user-images.githubusercontent.com/124937188/217951589-26f98dae-05ec-49ab-8e17-62341371e411.png)

**Comment by Mesalon** [comment]
So just rebalance the grenade's range? It already has fragments.

**Comment by NOxNXME** [comment]
> So just rebalance the grenade's range? It already has fragments. 260 fragments is excessive, costly, and pointless.

there is clearly not enough fragments, a human can stay unharmed despite a grenade blasting a few meters in front of them only because there is like 3 fragments, plus the fragment count could be changable in settings from 350 all the way to only using the explosion force for performance

**Comment by DindinYT37** [comment]
What's described in the image already somewhat occurs for me.

**Comment by mestiez** [comment]
I could increase fragment count, if that's what you're asking for. Damage is not strictly defined in this game as it would be in other games. Most mechanics are dynamically implemented. This is why I am reluctant to implement different damage radii. (radii? radiuses? radius (plural))

**Comment by Drogo-man** [comment]
I always find that shrapnel is really inconsistent, grenades often have no effect on a target whatsoever.
