### ISSUE TITLE
when attempting to upload a contraption it just gets stuck at 20% and says "workshop fail" after a bit

### ISSUE THREAD

**Issue by GeneralEfficiency32** [studio-minus/ppg-bugs-and-requests#2749]
### Describe the bug

well basically

when i attempt to upload a contraption (no mods used except for invis wires and object editor) it gets stuck on 20% and says "workshop fail" after a bit

it does it on contraptions that are just one thing too (like a brick)

### Clearly describe how to reproduce the bug

i just have to attempt to upload something and this happens

### Game debug info

[1675050579-Main.log](https://github.com/studio-minus/ppg-bugs-and-requests/files/10703555/1675050579-Main.log)
heres the log for the game session i attempted it on today

(ignore the name of my steam folder i named that thing when i was like 14)

### Game version

current verison

### Operating System

windows 10

### Additional notes

![People Playground 2_9_2023 9_56_41 PM](https://user-images.githubusercontent.com/124960064/217997431-95ff1eb7-4ea1-4055-9b01-95bf8e4c3ac3.png)
![People Playground 2_9_2023 9_57_20 PM](https://user-images.githubusercontent.com/124960064/217997446-ffaa3424-6422-4726-87f6-7c2f71e170c2.png)

**Comment by username90001** [comment]
do u use steam version of ppg

**Comment by GeneralEfficiency32** [comment]
> do u use steam version of ppg

yes i do

**Comment by username90001** [comment]
> > do u use steam version of ppg
> 
> yes i do

are u sure u have internet or u have non official version of ppg

**Comment by Drogo-man** [comment]
This seems like a steam issue.

**Comment by username90001** [comment]
> > do u use steam version of ppg
> 
> yes i do

did u just downloaded pirate or cracked version of ppg and after tried open it in steam and upload save
or maybe this is because of version of ur game idk

**Comment by mestiez** [comment]
This is a Steam thing but, to be fair, the game doesn't help either. There are some checks I could implement that are common causes of failure that the Steam library just doesn't explain on its own.
