### ISSUE TITLE
An explosive that is able to be stopped by objects

### ISSUE THREAD

**Issue by Tyosef** [studio-minus/ppg-bugs-and-requests#2752]
### Feature description

A new spawnable item, that explodes into pieces, It should be stopped by objects.

### Feature purpose

It would allow better guns, more realistic destruction, and powerful cannons.

**Comment by username90001** [comment]
what

**Comment by Mesalon** [comment]
what

**Comment by mestiez** [comment]
almost all explosives behave this way...
