### ISSUE TITLE
Cars should have music stations in them

### ISSUE THREAD

**Issue by bibbybabby** [studio-minus/ppg-bugs-and-requests#2753]
### Feature description

You know the things with the wheels on them that are fueled by OIL? They should have a music station so you can play jukebox music

### Feature purpose

Useful for machinimas so you don't need to strap a glowy heavy jukebox every time

**Comment by username90001** [comment]
just resize jukebox

**Comment by bibbybabby** [comment]
> just resize jukebox

did you read the feature purpose?

**Comment by username90001** [comment]
> > just resize jukebox
> 
> did you read the feature purpose?

U CAN resize it make it weightless and disable collision+ use layers to put it down and make it dont glow

**Comment by bibbybabby** [comment]
> > > just resize jukebox
> > 
> > 
> > did you read the feature purpose?
> 
> U CAN resize it make it weightless and disable collision+ use layers to put it down and make it dont glow

The shiny aura won't go away

**Comment by username90001** [comment]
xd then
