### ISSUE TITLE
make hearth beat monitor create signal if pulse is in config

### ISSUE THREAD

**Issue by username90001** [studio-minus/ppg-bugs-and-requests#2755]
### Feature description

hearth beat monitor will have config that configs at what hearth beat it will output signal
red decreases it
blue increases
like if number is 50 and human heath beat will be 50 it will create signal output

### Feature purpose

idk can be usefull in theory

**Comment by mestiez** [comment]
I will  grant the Nobel Prize to the first person to decipher this issue.

**Comment by username90001** [comment]
> I will grant the Nobel Prize to the first person to decipher this issue.

- hearth beat monitor will create activation signal if human hearth beat is same as u config 
- u go to hearth beat monitor properities and config it to make it create signal when hearth beat same as hearth beat config
can be usefull like realiving or something other
+ using other signal wires to increase or decrease number

**Comment by DindinYT37** [comment]
The point of this issue can easily be done by using a life detector.

**Comment by username90001** [comment]
> The point of this issue can easily be done by using a life detector.

i talk about bpm is bpm low it will like inject beverege or other not life detector because it will start work only when he die so bpm idea good
