### ISSUE TITLE
mouse click bug

### ISSUE THREAD

**Issue by eclizor** [studio-minus/ppg-bugs-and-requests#2757]
### Describe the bug

when ever i press my left mouse button load which scene gui pops up and i cant get rid of it this is happening for me for a whole week now

### Clearly describe how to reproduce the bug

just play a map then click on the screen

### Mod list

vietnam war mod, aimbot gun, 300m skyscraper, portal playground, deformation, Philippine war mod, scp 610 mod, pickup anything.

### Game version

1.25

### Operating System

Windows 10

**Comment by mestiez** [comment]
seems like this is caused by one of your mods. could you try to disable them all and re-enable them one by one to see which mod causes it?
