### ISSUE TITLE
A machine/vent that removes water around it at a specific radius and shape.

### ISSUE THREAD

**Issue by urrone** [studio-minus/ppg-bugs-and-requests#2761]
### Feature description

A machine that can look like a vent, and all it does is makes the surrounding water disappear in a specific x-to-y radius in simple shapes (circle or rectangle) that preferably you can also change.

### Feature purpose

This prop can be mounted on contraptions or any closed space intended to be pressurized to make the illusion of it being pressurized by that closed space.

### Additional context

This can look a bit weird if the contraption or closed space breaks open, so I also thought of some additional feature where the machine/vent is disabled if the surrounding bindings break, or better yet a AI thingy that detects if the closed space around it breaks open, but that'll prob cause many bugs and difficulties.

This epic prop could be named "Pressurizer".

**Comment by username90001** [comment]
this is copy of my suggestion https://github.com/studio-minus/ppg-bugs-and-requests/issues/2684#issue-1548782883

**Comment by mestiez** [comment]
"water" cannot be manipulated, its a static part of the map
