### ISSUE TITLE
Wont let me play

### ISSUE THREAD

**Issue by humanGuyMan12** [studio-minus/ppg-bugs-and-requests#2763]
### Describe the bug

whenever I click on a map to play it puts me back in the main menu but then I cant click anything and I cant even close the game.
So whenever this happens I need to restart my pc. Please fix this.

### Clearly describe how to reproduce the bug

idk It randomly started yesterday and now I cant play

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10774652/exported.game.debug.info.md)

**Comment by Drogo-man** [comment]
At first I thought it was a piracy issue, then I looked at the specs of ur PC, and I bet you could afford the game lmao.
But seriously just try verifying the game files on steam and you should be good.

**Comment by mestiez** [comment]
https://steamcommunity.com/app/1118200/discussions/0/2260188150872985040/

**Comment by mestiez** [comment]
This is not a tech support forum :)
