### ISSUE TITLE
A favorites tab in the spawner menu

### ISSUE THREAD

**Issue by diamondpic** [studio-minus/ppg-bugs-and-requests#2765]
### Feature description

It would be a mechanic/extra tab that appears in the item spawning menu, that when an item is hovered over and a key is pressed it would be added to the tab. (this tab carries over inbetween game relaunches)
The key to add/remove items from this tab would be rebind-able.

### Feature purpose

While there are different tabs for different mods when added, sometime i need to flip between 3-4 specific vanilla objects across several tabs (usually human, a spear, and a generator) but i cant grab them in quick succession.
the literal only purpose is speed/QOL for making contraptions.

### Additional context

basic graphic done in MS paint
![image](https://user-images.githubusercontent.com/28153164/219955169-3b270c7e-9e4a-4221-a4c7-5fa0f978c27b.png)

**Comment by DindinYT37** [comment]
Duplicate of or Related to:
* #422
* #1782
* #2495

**Comment by diamondpic** [comment]
oh its actually a common suggestion? thats really cool

**Comment by diamondpic** [comment]
I DIDNT MEAN TO DO THAT

**Comment by 2xddev** [comment]
There's a mod for this by the way. Look for "Favourites" in the workshop.
