### ISSUE TITLE
Rezising objects messes with the aerodynamics

### ISSUE THREAD

**Issue by Stoniac** [studio-minus/ppg-bugs-and-requests#2766]
Realized my error :(

**Comment by username90001** [comment]
Aerodynamics - Inactive (Issue happened before I installed it) NO OBJECT HAS AERODYNAMIC IN GAME EXCLUDING WINGS SO PROBLEM IS CAUSED BY THIS MOD 
When an object is resized, it will fall or move slower, as if a dampener was placed on it. DAMPENER IS WORKING LIKE THIS IS NOT BUG

**Comment by Stoniac** [comment]
> Aerodynamics - Inactive (Issue happened before I installed it) NO OBJECT HAS AERODYNAMIC IN GAME EXCLUDING WINGS SO PROBLEM IS CAUSED BY THIS MOD
> When an object is resized, it will fall or move slower, as if a dampener was placed on it. DAMPENER IS WORKING LIKE THIS IS NOT BUG

The issue happened before I installed the aerodynamics mod, and continues to happen after uninstalling. It’s not aerodynamics but that’s the closest word I could think of. I also never commented on if the dampener was working, so that’s not really relevant.

**Comment by Stoniac** [comment]
> Aerodynamics - Inactive (Issue happened before I installed it) NO OBJECT HAS AERODYNAMIC IN GAME EXCLUDING WINGS SO PROBLEM IS CAUSED BY THIS MOD When an object is resized, it will fall or move slower, as if a dampener was placed on it. DAMPENER IS WORKING LIKE THIS IS NOT BUG

If you're right, though (which actually I think you might be) how would I fix this?

**Comment by username90001** [comment]
dampers are supposed to work like this litteraly 
for aerodynamic use wings form normal ppg
there is no bug just skill issue

**Comment by Stoniac** [comment]
> dampers are supposed to work like this litteraly
> for aerodynamic use wings form normal ppg
> there is no bug just skill issue

Dampeners are completely irrelevant why are you talking about them

**Comment by username90001** [comment]
> > dampers are supposed to work like this litteraly
> > for aerodynamic use wings form normal ppg
> > there is no bug just skill issue
> 
> Dampeners are completely irrelevant why are you talking about them

u was talking about dampers as bug

**Comment by DindinYT37** [comment]
> > > dampers are supposed to work like this litteraly
> > > for aerodynamic use wings form normal ppg
> > > there is no bug just skill issue
> > 
> > 
> > Dampeners are completely irrelevant why are you talking about them
> 
> u was talking about dampers as bug

Incorrect. He was saying that resized objects were falling like as if they had dampeners on them.

**Comment by username90001** [comment]
> > > > dampers are supposed to work like this litteraly
> > > > for aerodynamic use wings form normal ppg
> > > > there is no bug just skill issue
> > > 
> > > 
> > > Dampeners are completely irrelevant why are you talking about them
> > 
> > 
> > u was talking about dampers as bug
> 
> Incorrect. He was saying that resized objects were falling like as if they had dampeners on them.

well idk then maybe he invented parachute

**Comment by Stoniac** [comment]
> > > dampers are supposed to work like this litteraly
> > > for aerodynamic use wings form normal ppg
> > > there is no bug just skill issue
> > 
> > 
> > Dampeners are completely irrelevant why are you talking about them
> 
> u was talking about dampers as bug

This is not meant to be rude, just a genuine question - is English your first language?

**Comment by username90001** [comment]
> > > > dampers are supposed to work like this litteraly
> > > > for aerodynamic use wings form normal ppg
> > > > there is no bug just skill issue
> > > 
> > > 
> > > Dampeners are completely irrelevant why are you talking about them
> > 
> > 
> > u was talking about dampers as bug
> 
> This is not meant to be rude, just a genuine question - is English your first language?

english is not my first language
