### ISSUE TITLE
X - Ray

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#277]
It works that on some humans when you shoot a bullet you see the bullet enter in 'n out organs and bone.

The feature purpose is for violence.

If this gets added than I would rather it be a setting.

**Comment by idotwaffle** [comment]
but there are no organs?? or do you mean add organs?
and do you wan't the bullets to actually physically interact with the "organs" and "bones" like sniper elite cus that sounds hard to do and would probably look strange in a 2d game where a human is only about 16x32 pixels

**Comment by mestiez** [comment]
Continued in #565
