### ISSUE TITLE
Mods like to undelete stuff in your mod folder

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#2773]
### Describe the bug

If you delete a file and launch the game with the mod, it will reappear for no reason

### Clearly describe how to reproduce the bug

Delete thing in mod folder and launch game

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10814596/exported.game.debug.info.md)

**Comment by Drogo-man** [comment]
this is a steam cloud thing, whenever you delete something it syncs up with the steam cloud, where the mod is still installed.

**Comment by ghost** [comment]
> this is a steam cloud thing, whenever you delete something it syncs up with the steam cloud, where the mod is still installed.

Even the local mods?

**Comment by Drogo-man** [comment]
yup, especially those since steam thinks they are game files.

**Comment by ghost** [comment]
auuuggh
