### ISSUE TITLE
Instead of blood, the color is yellow and no injury is visible

### ISSUE THREAD

**Issue by Hak333** [studio-minus/ppg-bugs-and-requests#2775]
### Describe the bug

No injuries are visible and the blood is not red

### Clearly describe how to reproduce the bug

Just go to the camera and try to injure the people

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10833831/exported.game.debug.info.md)

### Mod list

it is without mods

### Game version

1.26

### Operating System

Windows 10

### Additional notes

Screenshot https://cdn.discordapp.com/attachments/1010878025488941117/1079400915485851779/image.png
there are mods in the photo but I tried without them and nothing changed

**Comment by ghost** [comment]
disable goreless mode

**Comment by Hak333** [comment]
> 

oh thanks sorry
