### ISSUE TITLE
High power lasers can destroy indestructible connections

### ISSUE THREAD

**Issue by victorialilly** [studio-minus/ppg-bugs-and-requests#2777]
### Describe the bug

Lasers powered with either a generator or an industrial generator are able to destroy indestructible connectors like fixed and regular cables.
![image](https://user-images.githubusercontent.com/71139834/221430314-beb5c779-0207-404b-bbe8-42baf225b313.png)
![image](https://user-images.githubusercontent.com/71139834/221430331-25e2ff6f-2873-418f-80f0-a63df7328b1e.png)

### Clearly describe how to reproduce the bug

Attach a laser to a generator and fire it at something connected using fixed cables

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10834458/exported.game.debug.info.md)

**Comment by username90001** [comment]
it is supposed to be like this i think try use mirrors

**Comment by mestiez** [comment]
this is intended behaviour
