### ISSUE TITLE
Gotta say some decouplers would be nice

### ISSUE THREAD

**Issue by Chris353536345373344** [studio-minus/ppg-bugs-and-requests#2781]
### Feature description

Two new items that act like fuses but add a force to push the objects apart when activated (like a weak and strong one)

### Feature purpose

These could be useful in many builds, the most obvious is a rocket to detatch boosters. Or can be used in uhhh, ok yeah decouplers have few usecases tbh

**Comment by username90001** [comment]
good idea because fuse is too light and bad when attached to heavy things

**Comment by mestiez** [comment]
added!!!!!!
