### ISSUE TITLE
Zombies able to heal overtime like humans

### ISSUE THREAD

**Issue by TinFoil77** [studio-minus/ppg-bugs-and-requests#2787]
### Describe the bug

Im not sure if this is a feature or a bug, but zombies are able to slowly heal wounds like humans can. This doesn't really make any sense because they are dead and rotting.

### Clearly describe how to reproduce the bug

Injure a zombie and make sure "slowly heal injuries" is on.

### Game debug info

Not necessary for this bug. 

### Mod list

Not necessary for this bug. 

### Game version

1.26.6+

### Operating System

Not necessary for this bug.

**Comment by Eukalp** [comment]
Yeah, kinda unfun that way.

**Comment by mestiez** [comment]
fixed :)
