### ISSUE TITLE
Uploading a mod won't upload the mod

### ISSUE THREAD

**Issue by Eegeg** [studio-minus/ppg-bugs-and-requests#2790]
### Describe the bug

When i am trying to upload one of my mods it will not work (as existing and new), afterwards when i try again the upload type does not appear again

### Clearly describe how to reproduce the bug

Try to upload certain mods

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10892034/exported.game.debug.info.md)

**Comment by mestiez** [comment]
it has been fixed :)
