### ISSUE TITLE
Wiring leaving red unremovable residue after being removed.

### ISSUE THREAD

**Issue by FnafPizzaFan** [studio-minus/ppg-bugs-and-requests#2792]
### Describe the bug

When removing wires (using backspace) the wires leave a red leftover on the screen that you cannot delete unless you remove the human/object 

### Clearly describe how to reproduce the bug

Spawn a human or object, and put wires on the human (most commonly with the bandage) hold backspace and drag removing them, leaving a red streak. 
![image](https://user-images.githubusercontent.com/90162306/223244785-562b9da1-6b81-4b2d-8ab5-2c89a0bbcfd2.png)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10903257/exported.game.debug.info.md)

**Comment by mestiez** [comment]
I cannot reproduce this... any other instructions?
