### ISSUE TITLE
Gorse cannot be stabbed

### ISSUE THREAD

**Issue by B-Knots** [studio-minus/ppg-bugs-and-requests#2794]
### Describe the bug

This is an update to the previous bug i had mentioned, the gorse are still impossible to stab and produce a metallic sound when attempting to do so. Below i have catalogued each stabbable weapons effect on the gorse.

### Clearly describe how to reproduce the bug

Attempting to stab a gorse will yield no results. The only thing ive seen happen is bruising on the attempted stab area.

Axe- Does not stab
Chainsaw- Stabs
Crossbow bolt- Stabs
Crystal- Does not stab
Energy sword- Stabs
Knife- Does not stab
Lance- Stabs, but requires much force. If a human held this they couldnt stab without dying
Spear- Does not stab
Spike- Stabs but some infrequencies to it
Sword- Does not stab
Crossbow- Stabs, however it is tough to stab a frozen gorse
Schrewbender- Stabs, no problem

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10938339/exported.game.debug.info.md)

### Mod list

Alien Vs Predator Mod (INACTIVE)

### Game version

1.26.6

### Additional notes

![Screenshot (398)](https://user-images.githubusercontent.com/90061456/224219914-2ca10ff9-8cb4-444e-9e25-93147f6ab815.png)

**Comment by ghost** [comment]
This is all happening because of strange hitboxes

**Comment by bebrik1332** [comment]
i have almost same problem but with syringies, when i insert it into human or gorse, i cant pull it back without deleting or shooting it.

**Comment by mestiez** [comment]
I can't reproduce this...

**Comment by B-Knots** [comment]
If it helps i can make a video file of the occurance.
