### ISSUE TITLE
No hp showing and hp showing when detail view off

### ISSUE THREAD

**Issue by peopleplaygroundenjoerlol** [studio-minus/ppg-bugs-and-requests#2800]
### Describe the bug

https://user-images.githubusercontent.com/127614809/224495490-d41be9a0-1572-471c-870e-489cb717aedf.mp4

### Clearly describe how to reproduce the bug

this bug appears randomly

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/10948918/exported.game.debug.info.md)

### Mod list

i have  a lot of mods,i cant write it all:(

### Game version

1.26.6

### Operating System

windows 10 pro

**Comment by ghost** [comment]
make everything invisible mod moment

**Comment by royalealbert27** [comment]
Remove the said mod above
