### ISSUE TITLE
planes

### ISSUE THREAD

**Issue by ThermalEfragulation** [studio-minus/ppg-bugs-and-requests#2802]
### Feature description

new category for planes, basically you activate them they start going forward like cars but you can set hotkeys to control them going up and down maybe a weaponized plane or a jet 

### Feature purpose

well i believe this is a good idea because planes are just cool and in the image for the map "Humongous" it shows a person in a plane which is a little misleading if there are no planes in the base game.

**Comment by username90001** [comment]
> ### Feature description
> new category for planes, basically you activate them they start going forward like cars but you can set hotkeys to control them going up and down maybe a weaponized plane or a jet
> 
> ### Feature purpose
> well i believe this is a good idea because planes are just cool and in the image for the map "Humongous" it shows a person in a plane which is a little misleading if there are no planes in the base game.
> 
> ### Additional context
> _No response_

planes already added - airfoil with rotors to create elevon and propulsion like afterburning jet engine with propelers and even rocket engines
if u cant do it then it is ur skill issue

**Comment by ghost** [comment]
https://github.com/studio-minus/ppg-bugs-and-requests/projects/1#card-78172971
