### ISSUE TITLE
Bullet Knockback/Physics

### ISSUE THREAD

**Issue by fantik86** [studio-minus/ppg-bugs-and-requests#2815]
### Feature description

Im suggesting to add bullet physics in PPG

### Feature purpose

For example:
You took a shotgun and shot people (from little distance). But it didn't knockback it, he just get wounds and fall down

### Additional context

What about make bullets prop (now its particle with some running code on collide)? You can move prop with mouse M1 hold on prop, but you cant do it with most guns (e.g. AK-47, 9mm Pistol)

**Comment by ghost** [comment]
Physical bullets will be expensive to calculate and wouldn't even hit the target anyway

**Comment by mestiez** [comment]
there is knockback, its just not usually exaggerated.

**Comment by mestiez** [comment]
i just slightly increased it, but its not cartoonish like you seem to want. so i guess its rejected?

**Comment by Drogo-man** [comment]
Newtons 3rd law of gravity, the amount of recoil exerted on you and your firearm is the same as on whatever's on the other end of the barrel.
