### ISSUE TITLE
Dead androids getting rusty over time 

### ISSUE THREAD

**Issue by devastator162** [studio-minus/ppg-bugs-and-requests#2816]
### Feature description

Dead/destroyed androids getting a rusty texture over time. Simmilar to dead humans rotting.

### Feature purpose

It would just be a cool feature and that's it really

### Additional context

It would get rusty quicker while in water.

**Comment by mestiez** [comment]
this makes no sense because its not like the metal self-repairs or something. but it would look kind of cool

**Comment by mestiez** [comment]
i implemented it to see if it looked cool and it just looked kind of stupid
