### ISSUE TITLE
SawwedOff

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#282]
**Feature description**
New weapon sawwed off shotty and does way more dismemberment and regular damage.

**Feature purpose**
Listen ik this sounds boring but what if you right click and can change the ammo to either 2 ammo types ,incendiary, and shrapnel. incendiary sets the dude on fire whilst shootin em, and shrapnel sends multiple pieces of metal out the gun to get more spread or hit more people.

**Additional context**
When you spawn it can you make it where its unloaded like this. and you load it by flicking the gun up boom then it has infinite ammo. 

![sawed-off-shotgun-QHetR66W_200](https://user-images.githubusercontent.com/55041380/138390691-1be23114-66e1-4986-97d4-fbf0b4cb49ca.jpg)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by atwal6400** [comment]
> A shotgun... shooting shrapnels? So basically when you shot the gun... the bullet breaks in the chamber into shrapnels?
> 
> * It'd be pretty CPU heavy for a gun: Having multiple modifications, multiple bullets, multiple models, etc.

when i mean shrapnel i mean bigger radius.

**Comment by atwal6400** [comment]
> A shotgun... shooting shrapnels? So basically when you shot the gun... the bullet breaks in the chamber into shrapnels?
> 
> * It'd be pretty CPU heavy for a gun: Having multiple modifications, multiple bullets, multiple models, etc.

it wont be cpu heavy unless you have a good computer if it is cpu heavy then i think you should turn ur graphics down

**Comment by TamasB14** [comment]
> > A shotgun... shooting shrapnels? So basically when you shot the gun... the bullet breaks in the chamber into shrapnels?
> > 
> > * It'd be pretty CPU heavy for a gun: Having multiple modifications, multiple bullets, multiple models, etc.
> 
> it wont be cpu heavy unless you have a good computer if it is cpu heavy then i think you should turn ur graphics down

Graphics are GPU related, so if you have a bad CPU with a good GPU, it won't make a difference. Mostly spawned items use CPU, not GPU.

**Comment by atwal6400** [comment]
> > > A shotgun... shooting shrapnels? So basically when you shot the gun... the bullet breaks in the chamber into shrapnels?
> > > 
> > > * It'd be pretty CPU heavy for a gun: Having multiple modifications, multiple bullets, multiple models, etc.
> > 
> > 
> > it wont be cpu heavy unless you have a good computer if it is cpu heavy then i think you should turn ur graphics down
> 
> Graphics are GPU related, so if you have a bad CPU with a good GPU, it won't make a difference. Mostly spawned items use CPU, not GPU.

well then if you have a bad cpu just dont use shrapnel ammo ig
