### ISSUE TITLE
cardiopulmonary bypass machine re-enables collision after spawning as a save

### ISSUE THREAD

**Issue by Voidyx** [studio-minus/ppg-bugs-and-requests#2821]
### Describe the bug

when you take the cardiopulmonary bypass machine, disable collision on the machine AND the 2 small wheels, SAVE said object as a contraption (name does not matter), and spawn that contraption again, the collision on the wheels is back on, while staying off on the main machine.

### Clearly describe how to reproduce the bug

- Spawn Cardiopulmonary Bypass Machine
- Disable Collision (on the Machine and the 2 Wheels)
- Save as Contraption (any name)
- Spawn Contraption
- The Wheels will have Collision enabled again

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11073143/exported.game.debug.info.md)

**Comment by mestiez** [comment]
fixed :)

**Comment by Voidyx** [comment]
thanks
