### ISSUE TITLE
Blood is not necessary to stay alive

### ISSUE THREAD

**Issue by Dawid23-Gamer** [studio-minus/ppg-bugs-and-requests#2832]
### Describe the bug

When the blood in a ragdoll is replaced with another, non-lethal fluid, the ragdoll will stay alive in a comatose state.
Blood of course isn't really necessary to live as its only function is to transport oxygen, but technically its lack (regardless of Beverage M4 being in the system instead of it or not) should cause suffocation so I think I should report it as a bug anyway.

### Clearly describe how to reproduce the bug

1) Remove a significant amount of blood from a human without killing the ragdoll
2) Inject into it a bunch of non-lethal liquid (like Beverage M04) until the 'blood' pressure is at 100% again
3) Repeat until the blood amount is 0%

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11143132/exported.game.debug.info.md)

### Additional notes

This is as specific as it gets and relates to exactly 1 liquid in my mod but technically reproducable in vanilla so here I am I guess.

**Comment by mestiez** [comment]
fixed!! i think

**Comment by Drogo-man** [comment]
Jokes in you, I have a 89% ABL at all times, and I'm pretty much alive.
