### ISSUE TITLE
Nuke Bomb Bugging Snow Map

### ISSUE THREAD

**Issue by Hak333** [studio-minus/ppg-bugs-and-requests#2833]
### Describe the bug

When I put a house from the workshop and detonate a nuclear bomb, I get a broken map where everything is strange

### Clearly describe how to reproduce the bug

Subscribe to build
Find a house in a medium-sized workshop for example https://steamcommunity.com/sharedfiles/filedetails/?id=2839613836
Go to the map
Plant a nuclear bomb
blow it up

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11147942/exported.game.debug.info.md)

### Mod list

I don't think they have any effect.

### Game version

1.26.6

### Operating System

Windows 10

### Additional notes

![Screenshot_35](https://user-images.githubusercontent.com/115870989/229778433-60f9fc52-63e7-47a8-9c8c-6fcf2ce658cc.png)
Also, when everything is delayed, I can calmly place objects and they just start falling into the void

**Comment by mestiez** [comment]
Directly related, possibly duplicate, of #1
