### ISSUE TITLE
Various projectile balistics

### ISSUE THREAD

**Issue by somera139** [studio-minus/ppg-bugs-and-requests#2836]
### Feature description

Almost every weapon has almost the same balistics and would be nice if we had them different.

### Feature purpose

To make it realistic or more fun to play and test with.

**Comment by mestiez** [comment]
could you be more specific as to what you mean by "different"?

**Comment by somera139** [comment]
basically pistols could have up 100 meter range, SMGs could atleast up to 200, rifles up to 500. I couldn't really know what kinds of balistics weapons (specially cannons like 120mm one) should have but I can say that sniper rifle and a SMG having a small range difference is weird tho its hard to tell since SMGs have more bullet spread and another thing that is a stationary machine gun have actually same balistics as 120mm cannon. I might be wrong actually.
