### ISSUE TITLE
Activator electrode removes gun attatchments

### ISSUE THREAD

**Issue by ian5** [studio-minus/ppg-bugs-and-requests#2838]
### Describe the bug

When using the activator electrode to activate a firearm with attachments (both scope and underbarrel), it removes all attachments even if they aren't directly activated.

### Clearly describe how to reproduce the bug

1) Spawn a firearm, preferably something long like the rifle to make it easier to use the electrode without activating the attachments
2) Attach stuff- this works with both underbarrel attachments and the scope
3) Spawn an activator electrode, pick it up, and use it to activate the gun without hitting the attachments

The attachments of the firearm will pop off even though they weren't activated; this doesn't happen when activating a gun directly with F, or with a propagation wire.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11186241/exported.game.debug.info.md)

### Additional notes

Rifle with scope and laser attachment
![image](https://user-images.githubusercontent.com/18200025/230795004-192a09bd-aa5b-4f6f-9e31-2f0cb11727a9.png)
Activating the electrode detaches both
![image](https://user-images.githubusercontent.com/18200025/230795026-99c9b89e-d4ca-4277-bcba-d362681ca77d.png)
Here's the contraption, for good measure
[Attachment Example.zip](https://github.com/studio-minus/ppg-bugs-and-requests/files/11186248/Attachment.Example.zip)

**Comment by mestiez** [comment]
fixed :)
