### ISSUE TITLE
In Game i dont have audio in weird circumstances ?

### ISSUE THREAD

**Issue by TheMrHydra** [studio-minus/ppg-bugs-and-requests#2842]
### Describe the bug

I cant hear ANYTHING besides like the scream mod or gunshots, no ambient noise or menu noise, or noise when something hits the ground at all

### Clearly describe how to reproduce the bug

it just happened

### Game debug info

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.19045) 64bit

 - **CPU**: AMD Ryzen 7 3700X 8-Core Processor 

 - **GPU**: NVIDIA GeForce RTX 2060

 - **Memory**: 32 GB

## All loaded mods

	NeitherFishNorCat-AJIN:Demi-Human                                                                     -2957362030 v1.2 for game v1.21+
		Currently ACTIVE

	01 STUDIO & INT TEAM-Underwater Things-2946415658 v1.0 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	Abyssal Studio-NHC-local v1.05 for game v1.23+
		Currently inactive

	01 STUDIO-Combat Mod-local v1.0 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	NeitherFishNorCat- Automatic limb repositioning           -2913582654 v1.1 for game v1.21+
		Currently ACTIVE

	ibiglaser-Weapon size affects its power Mod-2894415938 v1.0 for game v1.26+
		Currently ACTIVE

	Dyadyushka Dyadya-Liquid Logic-local v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Torture Mod-2870378567 v1.0 for game v1.26.6
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Human Dynamic Emotions 2-2856823986 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Pickup Advanced-2854748282 v1.0 for game v1.25+
		Currently ACTIVE

	Dyadyushka Dyadya-Environment time changer-2850737647 v1.0 for game v1.24+
		Currently ACTIVE
		Has been initialised

	citizen-Hazardous Environment Combat Unit-local v1 for game v1.20
		Currently inactive

	Dyadyushka Dyadya-Arrows and crystals are now debris-local v1.0 for game v1.24+
		Currently ACTIVE

	Maxe & Dyadya-Advanced Zombie Injector (v1.2)-2815591838 v1.2 for game v1.24+
		Currently ACTIVE

	Mishanya-The Ultimate Car Mod-2795171453 v0.9 for game v1.16+
		Currently ACTIVE

	Fanboy#1000-Popular SCP's-2793790885 v1.0 for game v1.11
		Currently inactive

	Orsoniks / Navii-Reactive humans-2793371344 v1.0 for game v1.23+
		Currently ACTIVE
		Malfunctioning

	Frosty-Accurate Resize & Position-2789547018 v1.0 for game v1.23
		Currently ACTIVE
		Malfunctioning

	loudyfam-SCP: Armory-2789034314 v1 for game v1.20
		Currently inactive

	loudyfam-Detailed Mobile Task Forces-2788364899 v1 for game v1.20
		Currently inactive

	Dyadyushka Dyadya-Wind Generator-2785388021 v1.0 for game v1.22.3+
		Currently inactive

	Dyadyushka Dyadya-Controlled Sea (FIXED FOR 1.24)-2776630725 v1.0 for game v1.24+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Acid Sea (FIXED)-2759438689 v1.0 for game v1.24+
		Currently ACTIVE
		Has been initialised

	01 Studios-Human Dynamic Emotions (SOON PART 2)-2745225441 v1.0 for game v1.22+
		Currently ACTIVE
		Has been initialised

	Orsoniks / Navii-Wound Infections-2729065060 v1.0 for game v1.22+
		Currently inactive
		Malfunctioning

	FredMichalBear-SCP protogen mod-local v1.0 for game v1.16+
		Currently inactive

	RadioactiveE3™-SCP: PPG Edition-2643873749 v4.5 for game v1.22+
		Currently inactive

	[ Fasol_G#DangerZone ]-[ SCP-610 Mod ]-2626113140 v1.0 for game v1.14+
		Currently inactive

	Morzzic-Object Editor-2590195142 v1.3.1 for game v1.23+
		Currently ACTIVE

	Puppyguard-AutoAim-2552152695 v1.0 for game v1.19.2
		Currently ACTIVE

	Fleasy-FleasyWeapons - Small Guns-2546528392 v1.2 for game v1.19+
		Currently ACTIVE

	krzem-throwing knife-2540929350 v1.0 for game v1.19.2
		Currently ACTIVE

	ahlad-small acid swamps-2530315269 v1.0 for game v1.14+
		Currently ACTIVE
		Malfunctioning

	Burgerek_Pl-More Daggers-2524292276 v0.1 for game v1.19
		Currently ACTIVE

	Pumpkin-Simple Syringes Mod-2522356867 v2.2 for game v1.18+
		Currently ACTIVE

	jimmyl and Bonible-Guns,guns,guns!-2522015543 v1 for game v1.18+
		Currently ACTIVE

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently ACTIVE

	Voidy-Reattach Limbs-2507657213 v1.0 for game v1.20+
		Currently ACTIVE
		Malfunctioning

	Quickness, I am a person, Duolanchik, Mishanya-VanillaWeapons+ 3-2505936356 v1.0 for game v1.18.1x
		Currently inactive

	Blocksify & Frevv-Blocksify's Crazy Syringes Mod-2498890172 v1,000,000 for game v1.18
		Currently ACTIVE

	The Ninja Scout-Decomposition-2497957604 v1.0 for game v1.11
		Currently ACTIVE

	Skullex(jamesH_2), Aspa102, Kassjak-Scream mod-2494555615 v1.0 for game v1.11
		Currently ACTIVE

	yefeyks-Generators+-2490397546 v1.0 for game v1.17.3
		Currently ACTIVE

	Kubulll-Nuclear Playground-2484034390 v1.0.0.1 for game v1.26.x
		Currently inactive

	Hoodirony360NoscopeSlayer666-Rhino TRF-2471946749 v1.0 for game v1.14+
		Currently inactive
		Malfunctioning

	kris-Gorey Human 2.0-local v2.0 for game vcurrent versions.
		Currently inactive

	Talon Zane-Map Blocks-local v1.0 for game v1.7
		Currently inactive

	LijmPistool-Liquids Map-2432660281 v1.0 for game v1.14+
		Currently ACTIVE
		Malfunctioning

	Mishanya-Police+-2416686384 v6.4 BETA for game v1.21.3+
		Currently inactive

	Quickness, The Crusader and Duolanchik-VanillaWeapons+ 2-2409064173 v1.0 for game v1.15x
		Currently ACTIVE

	myru-Bombs Expanded-2408928012 v1.1 for game v1.22-1.26+
		Currently ACTIVE

	Mr_kWKD-Military+-2390021263 v1.0 for game v1.11
		Currently inactive

	Crafter_215-More Explosives-2383112201 v1.6 for game v1.25
		Currently ACTIVE

	jimmyl-Android Injectors-2381177128 v1.4 for game v1.12+
		Currently ACTIVE

	JohnnyTaco-Mulligan-2369099463 v1.87 for game v1.16+
		Currently inactive

	moonSIq-Secure. Contain. Protect [SCP MOD]-2361867196 v1.2 for game v1.12
		Currently inactive

	Tableland33-Titanfall Mod-2358293433 v1.3 for game v1.13.1
		Currently inactive

	Kyrelink-Star Wars Dark Saber Mod-2337413002 v1.5 for game v1.10+
		Currently inactive

	jimmyl-ExplosiveMod-2337158074 v1 for game v1.10+
		Currently ACTIVE

	[TSF] Life.exe-S.C.P.F. mod-2332568618 v1.0 for game v1.12+
		Currently inactive

	Damianos28,Kyrelink-More Destructible Objects !-2319326006 v1.0 for game v1.13.1
		Currently ACTIVE

	Alibarda-Human Tiers-2308911224 v5.9 for game v1.18+
		Currently ACTIVE
		Has been initialised

	Adskiy Drochila & Woowz11-Madness PACK-2299286896 v1.6.0 for game v1.12.2
		Currently inactive

	Alibarda-PowersMod-2276255188 v2.2 for game v1.18+
		Currently ACTIVE

	Skittles-Skittle's Syringe Mod-2268097682 v1.4 for game v1.19+
		Currently inactive

	Punkkinn, Talon Zane-The Super Collection-2251078075 vv1.0 for game v1.11+
		Currently inactive

	Pumpkin-Quality of Life Items(Deprecated)-2236268298 v1.7 for game v1.16+
		Currently ACTIVE

	gwenenenen-More Guns-2235585600 v1.0 for game v1.10.2
		Currently inactive

	weirdo-Chemical Warfare-2226697361 v2.0 for game v1.22.2+
		Currently ACTIVE

	Svit and Sky-POT O' Items-2187367733 v1.2 for game v1.9.4
		Currently ACTIVE

	Kyrelink-Star Wars Sith and Jedi Mod 3.3-2182277406 v3.3 for game v1.10+
		Currently ACTIVE

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently ACTIVE

	kortl-COMBAT Zombies-local v1.0 for game v1.8.x
		Currently inactive

	Kyrelink-CSGO Weapon-2157439269 v1.0 for game v1.13+
		Currently ACTIVE

	Portal Turret1010-Katana Mod-2146154723 v1.0 for game v1.8.x
		Currently ACTIVE

	Kyrelink-Half Life 2 weapons-2140530282 v1.6 for game v1.7
		Currently inactive

	Grizzly-Ancient Weapons Pack-2137861405 v13.0 for game v1.8.x
		Currently ACTIVE

### Game version

1.26.6

### Operating System

Win 10

**Comment by ghost** [comment]
check your sound settings

**Comment by TheMrHydra** [comment]
they are all fine

**Comment by mestiez** [comment]
I can only imagine you have a mod enabled that overwhelms the audio system by exceeding the maximum voice count... Can you disable all mods and see if the issue persists?
