### ISSUE TITLE
Heartrate moniter showing 70 bpm when a human is dead

### ISSUE THREAD

**Issue by TheUltimm** [studio-minus/ppg-bugs-and-requests#2847]
### Describe the bug

When playing around with the heartrate moniter on a human with punctured lungs the humans heartrate stayed at 70 bpm when they were dead but instead should be at 0 bpm. When attempting to recreate this the first time the humans heartrate went to zero and realized if you copy and paste a human with punctured lungs while the cardiopulmonary bypass machine is active (without copying the cardiopulmonary bypass machine along with the human) that the humans heartrate will only go down to 70 bpm when dead.

### Clearly describe how to reproduce the bug

1. Spawn in a human and axe, then swing the axe on his back where his lungs would be until he has only punctured lungs and pause the game for this next step. (This may take many attempts until you can puncture his lungs and I don't know a better way to do so without having his heart stop)
2. Attach a cardiopulmonary bypass machine to keep the human alive, a heartrate moniter, and make sure they're both active.
3. Copy only the human itself and paste it attaching a new heartrate moniter to the new human you just pasted, unpause the game, and let him die so you can see that his heartrate stay at 70 bpm.
4. Now remove the cardiopulmonary bypass machine to the first human you made (the one that wasnt copied and pasted), and see his heartrate go to 0 bpm.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11216285/exported.game.debug.info.md)

### Additional notes

![image](https://user-images.githubusercontent.com/130607293/231595835-9bc9019e-4f14-43c1-b95a-8d994e6e7026.png)

**Comment by mestiez** [comment]
how obscure, good find. fixed :)
