### ISSUE TITLE
change the glass on Substructure to Tempered glass

### ISSUE THREAD

**Issue by KurokiTomoko1** [studio-minus/ppg-bugs-and-requests#2850]
### Feature description

it breaks too easily 

### Feature purpose

people would like it maybe

i kinda dont like when  the glass shatters cause then i gotta clear everything to get it back

**Comment by Drogo-man** [comment]
Tempered glass doesn't look as cool when I throw someone through it.

**Comment by ghost** [comment]
>it breaks too easily

that's the point

>i kinda dont like when the glass shatters cause then i gotta clear everything to get it back

tempered glass has the same issue
