### ISSUE TITLE
pls make it where if your holding a gun while human is holding it recoil will be normal instead of non existant

### ISSUE THREAD

**Issue by Squibard** [studio-minus/ppg-bugs-and-requests#2852]
### Feature description

like if your holding a gun and human is too recoil wont be non existent when you normally hold gun and shoot

### Feature purpose

could be toggleable and its also good for roleplays or videos

### Additional context

https://user-images.githubusercontent.com/112280080/231916864-0ceab9a5-aa38-4c3a-ae76-cb41807b83e0.mp4

**Comment by somera139** [comment]
try not holding it but shooting at fixed position instead

**Comment by Squibard** [comment]
> try not holding it but shooting at fixed position instead

ok but I still want this

**Comment by Drogo-man** [comment]
This is a mod issue, a lot of modders forget to add proper recoil to thier guns.

So complain to them.

**Comment by Squibard** [comment]
> This is a mod issue, a lot of modders forget to add proper recoil to thier guns.
> 
> So complain to them.

no I tested with non modded pistol and modded pistol it still has no recoil when I'm holding while human is holding

**Comment by mestiez** [comment]
you are holding the gun so the recoil is absorbed by the cursor. use [Gentle Drag](https://steamcommunity.com/sharedfiles/filedetails/?id=2490855955) or something.

**Comment by somera139** [comment]
> you are holding the gun so the recoil is absorbed by the cursor. use [Gentle Drag](https://steamcommunity.com/sharedfiles/filedetails/?id=2490855955) or something.

it is back...
