### ISSUE TITLE
All of my contraptions don't work 

### ISSUE THREAD

**Issue by brustarr** [studio-minus/ppg-bugs-and-requests#2853]
### Describe the bug

I reinstalled the game after few months and every contraption is giving errors and not working
Error code: This contraption is incompatible with your current version Target 1.25.4, current1.26.6

Is everyone like this? What can I do? Should I throw away hundreds of hours of work?

![5og49nqqitta1](https://user-images.githubusercontent.com/130750830/232013596-2cf8f6aa-a146-4789-9cbe-6559ab8ef0e2.jpg)

### Clearly describe how to reproduce the bug

I played ppg few months ago and reinstalled today, Saw 'Unable to sync files with steam cloud' messege
and all the contraption make version mismatch error
It's not even a mod issue as I rarely use mods in my previous productions.

### Game debug info

[hda.zip](https://github.com/studio-minus/ppg-bugs-and-requests/files/11231572/hda.zip)
this is one of them 

### Game version

1.26.6

### Operating System

windows10

### Additional notes

![20230414190411_1](https://user-images.githubusercontent.com/130750830/232015234-8042dbae-9e03-4c71-9127-45e108632e82.jpg)
![20230414182028_1](https://user-images.githubusercontent.com/130750830/232015241-1d943989-2370-484c-82f4-bf233e749579.jpg)
![20230414190405_1](https://user-images.githubusercontent.com/130750830/232015246-3b8c7d3f-b61f-4c4b-8112-c7dce16938b0.jpg)
![20230414190407_1](https://user-images.githubusercontent.com/130750830/232015250-390627cc-aed5-4ddb-bd0d-39c6448bebfe.jpg)
![20230414190415_1](https://user-images.githubusercontent.com/130750830/232015285-0e47fd79-a4a8-487e-bc30-dbe7fa03d6e6.jpg)

**Comment by mestiez** [comment]
The attached archive does not contain a contraption, only its metadata. 
I need a `jaap` file as well
