### ISSUE TITLE
Human feet, legs, or both sometimes break and suffer a big bruise when spawned in 

### ISSUE THREAD

**Issue by ras09191** [studio-minus/ppg-bugs-and-requests#2854]
### Describe the bug

Sometimes (somewhat rarely), when spawning in a human from just a meter or less above ground, the impact they receive when hitting the ground is abnormally strong and completely breaks one of their legs and feet. ( The ground shakes also for less than a second)
![Screenshot 2023-04-14 181348](https://user-images.githubusercontent.com/130605882/232169185-39674de4-fa9d-42c9-a5ef-4862de05ea49.png)

This is an example of the damage that humans suffer. This is not caused by the bug itself, but rather with a hammer as i dont want to wait an unknown amount of time.

### Clearly describe how to reproduce the bug

Spawn in humans. This bug is somewhat rare, but if you get it, a humans leg or foot (or both) will suffer an abnormal injury.

### Mod list

Blood decals on living creatures
Foods+ mod 
The ultimate car mod
Melon Playground
Functional Devices mod
Humans+ 
Chemical Warfare
Quick Right Click Options

### Game version

1.26.6

### Operating System

Windows 11.

### Additional notes

bug is rare

**Comment by Squibard** [comment]
this happened to me once and its annoying

**Comment by Drogo-man** [comment]
This is just unity fuckery.

**Comment by mestiez** [comment]
yeah i dont know if i can fix this with my rodent brain

**Comment by ras09191** [comment]
:( fine
