### ISSUE TITLE
Make humans surviving headshots far rarer

### ISSUE THREAD

**Issue by ras09191** [studio-minus/ppg-bugs-and-requests#2855]
### Feature description

Humans surviving headshots are way too common than what they thould be. I would like the developer to make headshot survivals a far rarer event (maybe 1 in 500 humans).

![Screenshot 2023-04-14 184532](https://user-images.githubusercontent.com/130605882/232171900-b8298d48-9be8-49c9-83d4-5df2b065fec4.png)

Human shot in the head once 

![Screenshot 2023-04-14 185219](https://user-images.githubusercontent.com/130605882/232171924-1f5097a5-7ef8-4cd7-9a2c-d66aa9f54f55.png)

Same human, shot in the head again

### Feature purpose

Realism. Also, the reason i want this request is because in my experience, i have experienced headshot survivals way more often than what they should be. I even once shot a cowering human 4 times from the the mouth up and he survived.

**Comment by Drogo-man** [comment]
Yes, it's so annoying when I shove a giant 6 inch wide spike into someone's skull and they just walk it off.

**Comment by ras09191** [comment]
I dont get why someone disliked this feature request

**Comment by Drogo-man** [comment]
It's from "awaheartemoji", he's very, critical.

**Comment by ras09191** [comment]
i hope this feature gets accepted

**Comment by ras09191** [comment]
lets go

**Comment by Lordjakob** [comment]
It is estimated that 10% of all headshots with 9mm are not fatal
