### ISSUE TITLE
Stielhandgranate doesn't burstex if heated

### ISSUE THREAD

**Issue by Stupidspacecat37** [studio-minus/ppg-bugs-and-requests#2856]
### Describe the bug

Stielhandgranate doesn't burst when explodes due to heat.

### Clearly describe how to reproduce the bug

1.Heat the stielhandgranate until it explodes.
Result: it didn't burst like it normaly does

**Comment by Drogo-man** [comment]
Burst?

**Comment by mestiez** [comment]
what is the difference...

**Comment by Drogo-man** [comment]
Ooooh, I think he's referring to the Over Complicated Mod, which makes the top of stielhand grenades "burst" open when slammed into something or detonated (like in TF2) instead of just disappearing.

It's a mod.
