### ISSUE TITLE
Can not place things

### ISSUE THREAD

**Issue by oliveeman** [studio-minus/ppg-bugs-and-requests#2857]
### Describe the bug

This bug started as soon as I installed the game I could not place the doums I've unstalled and reinstalled mutapul times and it still will not work one time I was about to place two humans down but other than that im clueless.

### Clearly describe how to reproduce the bug

place something

### Mod list

none

### Game version

curent

### Operating System

windos11

### Additional notes

no L

**Comment by oliveeman** [comment]
I an use powers thought

**Comment by mestiez** [comment]
can you be more specific? what exactly are you doing?

**Comment by Drogo-man** [comment]
Are you old enough to legally be on here?

**Comment by oliveeman** [comment]
placing people.

**Comment by Drogo-man** [comment]
Yes

**Comment by mestiez** [comment]
Closed because I don't think this is going anywhere

**Comment by oliveeman** [comment]
`

> 

no

**Comment by Drogo-man** [comment]
.?"! ye



s
