### ISSUE TITLE
Servo green light won't turn on 

### ISSUE THREAD

**Issue by LucaFrantz** [studio-minus/ppg-bugs-and-requests#2858]
### Describe the bug

The green light on the Servo that is on the left side of the Stand of the Servo won't light up Green when you turn the Servo on (or off).  please fixed or tell me if there is a problem with my copy of people playground please. It won't light up for me. 

### Clearly describe how to reproduce the bug

Go into the default (any) Map spwan in the Servo then activate it and see what happens (green light on or off?)

### Game debug info

![20230420_193135](https://user-images.githubusercontent.com/131392115/233443553-4a84e2c9-add1-4284-a61f-d7f993b18e84.jpg)

### Mod list

None

### Game version

1.26.6

### Operating System

Windows11

**Comment by mestiez** [comment]
cool screenshot but can you not do that again next time? just drag the file in like it says.

**Comment by mestiez** [comment]
the servo doesn't have a green light...
