### ISSUE TITLE
Frictionless mechanical belt

### ISSUE THREAD

**Issue by End3rdragon1234** [studio-minus/ppg-bugs-and-requests#2859]
### Feature description

Version of the mechanical belt that doesn't slip when tranferring the rotational energy between objects and always has the same rotation ratio.

### Feature purpose

The mechanical belt slipping can be annoying and would be more reliable in builds using wheels and belts

**Comment by mestiez** [comment]
unfortunately the slipping is not by choice. it's a technical limitation :(

**Comment by 2xddev** [comment]
> unfortunately the slipping is not by choice. it's a technical limitation :(

iirc you did say you would make a one way rotation link once but that might just be a product of my imagination

**Comment by mestiez** [comment]
turns out even one-way belts have issues that im too stupid to figure out

**Comment by Drogo-man** [comment]
I feel you man
