### ISSUE TITLE
Can't upload/update a mod

### ISSUE THREAD

**Issue by Turboxdd** [studio-minus/ppg-bugs-and-requests#2863]
### Describe the bug

I made a mod and when I want to update it nothing happens. I click on upload and say update existing one but nothing happens.

### Clearly describe how to reproduce the bug

try to upload or update a mod

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11303553/exported.game.debug.info.md)

**Comment by mestiez** [comment]
Duplicate of #2790 which has been fixed

**Comment by Turboxdd** [comment]
Well, It's still not working and It doesn't show anything when I press Update existing

**Comment by vladyslavm32** [comment]
Hi! I recently started to work on my mod and this issue's still present.

<img width="1265" height="289" alt="Image" src="https://github.com/user-attachments/assets/ab68ae91-de95-4e7b-9db9-c19cb8ba97d0" />

After pressing 'Understood' nothing happens and no logs left about this at all. Like the only solution now is to just delete theese folders but it's pretty annoying.
