### ISSUE TITLE
Crash during loading

### ISSUE THREAD

**Issue by TheThroneRo** [studio-minus/ppg-bugs-and-requests#2866]
### Describe the bug

So i have tons of mods installed but it was working pretty fine.
Until i install one new mod. The game freeze during loading screen 
After some minute UnityCrash pop up and the game close almost instantly
I already tried to remove some mods but i dont really know if its mods fault because before this bug to happend i haved no problem with mods at all

### Clearly describe how to reproduce the bug

Idk

### Game debug info

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.22621) 64bit

 - **CPU**: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

 - **GPU**: NVIDIA GeForce GTX 1650 Ti

 - **Memory**: 8 GB

### Mod list

atleast 20 mods active

### Game version

1.26.6

### Operating System

Window 11

### Additional notes

The game was no launch in beta or preview version

**Comment by Drogo-man** [comment]
Sounds like a mod problem

**Comment by TheThroneRo** [comment]
> Sounds like a mod problem

I will try to disable the last mod that i installed before it started to do the bug

**Comment by Drogo-man** [comment]
I mean, it seems like your PC was on the brink of running out of ram, but that one mod pushed it over the edge.

**Comment by TheThroneRo** [comment]
> I mean, it seems like your PC was on the brink of running out of ram, but that one mod pushed it over the edge.

Yeah i will try to disable it my pc told me there is a ram over writting problem
