### ISSUE TITLE
The Air Update

### ISSUE THREAD

**Issue by thumbthumb9** [studio-minus/ppg-bugs-and-requests#2877]
### Feature description

This update should add several gas related things

Such as gasses like 
- Pink Gas (which would just do the same thing as the pink syringe)
- Some sort of real lethal gas (Phosgene gas, Mustard gas, Etc)
- Most importantly Oxygen
- Tear Gas (Which should just make humans and gorse feel pain, little to no damage)
- Maybe helium? (Not really sure what it would do besides making whatever you injected it with float)

And then ways to transport the gases like
- Preferably a new wire or cable, But using the liquid wire would work
- Tanks which run out of air as it's fed into something (Two sizes, light which would be like 65cm - 75cm tall and would be best for giving one human air, Heavy which would be about 1m tall and 2m wide and should have significantly more air than the personal)
- A Duplicator (Which like the liquid duplicator would make an infinite amount of whatever gas is put into it)
- An Emitter (Which would just shoot the gas out into the open space)
- Less important but when you emit gas into war you could make it come out as bubbles that pop once they reach the surface

And Maybe a few slightly unrelated additions like
- A Liquid based flamethrower (It would shoot a sort of napalm that goes much further than the current flamethrower and sticks to whatever it hits, Like real life)
- A Heavy 50 Cal machine gun (Sniper Rifle damage with Light Machine Gun fire rate and accuracy)
- 20mm gun (Like the 30mm but not explosive and less effect)
- And maybe a space map (Like the void map but no oxygen, Starts with 0 gravity, and the temperature is up to you)

### Feature purpose

It would add a lot more possibility to contraptions and would just make the game more fun in general

### Additional context

Obviously you don't have to accept this but if you do I dont expect you to be able to release everything in 1 update

**Comment by DindinYT37** [comment]
Please submit one request at a time, as it would make it easier to address each issue individually. Additionally, a lot in your request has been requested before.

**Comment by ras09191** [comment]
dev wont add

**Comment by mestiez** [comment]
Please do not group requests
