### ISSUE TITLE
bug with the light bulb

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#2878]
### Describe the bug

bug with the light bulb

### Clearly describe how to reproduce the bug

if you take a light bulb, turn it on and bring it to the spotlight there gonna be a huge light cube

### Game version

latest version

### Operating System

Windows 10

### Additional notes

![Screenshot_47](https://user-images.githubusercontent.com/132372258/235697621-141855d5-1c9c-4808-bb11-8f241a79f99d.png)

**Comment by mestiez** [comment]
This is just the bulb being brightened by the spotlight. The bloom is a blurred version of the framebuffer that has been downsampled, causing the "cube" looking artifact. It's not a bug, it's just not very pretty.
