### ISSUE TITLE
Remake selecting system

### ISSUE THREAD

**Issue by XenonPPG** [studio-minus/ppg-bugs-and-requests#2879]
### Feature description

You always select the smallest object

### Feature purpose

![image](https://user-images.githubusercontent.com/102830220/235752171-4bcfe3a6-a8a7-435b-b0a6-05e5a52a0f06.png)
I pointed cursor in the center of this thing. Red cube was selected and there is no way I can select blue one. With new system I would be able to reach both of them. I want this feature because in contraptions with a lot of resizable housing its quite often impossible to reach small parts and details

**Comment by mestiez** [comment]
this was implemented but im not sure if it was because of this issue
