### ISSUE TITLE
Centrifuge starts to move when it shouldn't 

### ISSUE THREAD

**Issue by Danny07-ger** [studio-minus/ppg-bugs-and-requests#2883]
### Describe the bug

If (at least) three centrifuges are staked up each other, they will start moving when activated.

### Clearly describe how to reproduce the bug

- Spawn three centrifuges up each other
- Activate all of them (in no particular order)
- observe

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11409503/exported.game.debug.info.md)

### Additional notes

https://user-images.githubusercontent.com/52317753/236553523-447a0893-de2e-4b07-9267-7c1229ab270f.mp4

**Comment by username90001** [comment]
> ### Describe the bug
> If (at least) three centrifuges are staked up each other, they will start moving when activated.
> 
> ### Clearly describe how to reproduce the bug
> * Spawn three centrifuges up each other
> * Activate all of them (in no particular order)
> * observe
> 
> ### Game debug info
> [exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11409503/exported.game.debug.info.md)
> 
> ### Mod list
> _No response_
> 
> ### Game version
> _No response_
> 
> ### Operating System
> _No response_
> 
> ### Additional notes
>  People.Playground.2023.05.05.-.21.31.59.02.DVR_Trim.mp4

its supposed to work like this even if they are symetrical or asymetrical

**Comment by Danny07-ger** [comment]
You mean its a feature? I dont think so... This doesnt look like its supposed to happen. It would be to specific.

**Comment by username90001** [comment]
> You mean its a feature? I dont think so... This doesnt look like its supposed to happen. It would be to specific.

upper centrifuge rotates like anothers in case if they are synchonized they will of course fall try put boxes and try move then all at once and they will fall
and they will fall even if its desynchonized

**Comment by Danny07-ger** [comment]
I understand now. Not a bug im dumb...
