### ISSUE TITLE
electricicy enhancer

### ISSUE THREAD

**Issue by PeoplePlaygroundIsFun** [studio-minus/ppg-bugs-and-requests#2886]
### Describe the bug

i can duplicate electricity

### Clearly describe how to reproduce the bug

![People Playground 2023-05-07 12_28_31 PM](https://user-images.githubusercontent.com/132833262/236685313-d3b410b9-add2-42f4-9f97-2c5cb1eae3ac.png)

let this explain itself (if it works)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11415297/exported.game.debug.info.md)

### Game version

1.26.6

### Operating System

windows 10

### Additional notes

![People Playground 2023-05-07 12_28_31 PM](https://user-images.githubusercontent.com/132833262/236685513-7a499051-7be5-4e13-974d-39da8a53b089.png)

same image lmao

**Comment by username90001** [comment]
> ### Describe the bug
> i can duplicate electricity
> 
> ### Clearly describe how to reproduce the bug
> ![People Playground 2023-05-07 12_28_31 PM](https://user-images.githubusercontent.com/132833262/236685313-d3b410b9-add2-42f4-9f97-2c5cb1eae3ac.png)
> 
> let this explain itself (if it works)
> 
> ### Game debug info
> [exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11415297/exported.game.debug.info.md)
> 
> ### Mod list
> _No response_
> 
> ### Game version
> 1.26.6
> 
> ### Operating System
> windows 10
> 
> ### Additional notes
> ![People Playground 2023-05-07 12_28_31 PM](https://user-images.githubusercontent.com/132833262/236685513-7a499051-7be5-4e13-974d-39da8a53b089.png)
> 
> same image lmao

there is no problem
power to signal converter works with any power so u can even use battery and result will be always same power
but u can increase power output by adding more signal wires
