### ISSUE TITLE
Humans and robots are invisible

### ISSUE THREAD

**Issue by monokumarg** [studio-minus/ppg-bugs-and-requests#2893]
### Describe the bug

I have a bug for quite some time, I think it's about a weird texture bug that makes robots and humans invisible unless they do damage, I hope a solution can be found

### Clearly describe how to reproduce the bug

I really don't know how it was generated, it only happens to me, but I think that if you need to replicate it, you just have to use proton linux on steam

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11498672/exported.game.debug.info.md)

### Mod list

I don't have mods

### Game version

my version is 1.26.6

### Operating System

linux huayra debian 10

### Additional notes

![Captura de pantalla -2023-05-17 10-22-12](https://github.com/studio-minus/ppg-bugs-and-requests/assets/133882479/8c20f1d6-9973-45ff-9987-7a0f12b8b1dc)
![Captura de pantalla -2023-05-17 10-22-00](https://github.com/studio-minus/ppg-bugs-and-requests/assets/133882479/f633cffd-ab52-4efd-91d7-fdaf9a026b9f)
![Captura de pantalla -2023-05-17 10-21-53](https://github.com/studio-minus/ppg-bugs-and-requests/assets/133882479/5b6371a2-8e42-4af9-8f94-44d5bc7d2c1d)

**Comment by thebob123456** [comment]
hey this has happened to me to but i can only not see the normal people have you found a fix and how have you got it to have that green outline also i have tried uninstalling the game and reinstalling but it has not helped any fixes to this
