### ISSUE TITLE
shrapnel explosions sometimes fail to launch body parts

### ISSUE THREAD

**Issue by thetruss** [studio-minus/ppg-bugs-and-requests#2894]
### Describe the bug

shrapnel explosions such as landmines sometimes will destroy a human's body parts and leave the rest of the body unaffected by the force

### Clearly describe how to reproduce the bug

use landmine next to human
do it multiple times and sometimes either parts of the body are oblieratared (and the rest of the human stays still) or the human will be launched with injuries or death

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11503581/exported.game.debug.info.md)

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/116781200/331610e4-9036-4bcc-adc2-ddfbc0bcaed0

**Comment by username90001** [comment]
i think that because his limbs get oofed and limbs absorb explosion and accelerate while preventing his body from flying away

**Comment by mestiez** [comment]
has been fixed in 1.27
