### ISSUE TITLE
Item that generates force

### ISSUE THREAD

**Issue by Orzech05** [studio-minus/ppg-bugs-and-requests#2902]
### Feature description

It would be good if we had an item that can generate force. Something like a fan, but doesn't decapitate humans instantly as they  touch it.

### Feature purpose

You could make some cool stuff with it.
I don't think it would be that hard to make since we already have fans and those snow thingies at the top of snow map, but as I said one kills humans and the second one is unusable.

**Comment by mestiez** [comment]
So a propeller?

**Comment by Orzech05** [comment]
> So a propeller?

A item that pushes other objects away but doesn't absolutely destroy them when they come in contact.
Now that I think about it, it seems a bit useless since you can just block the fan and achieve the same result, but I think it shouldn't fling objects it touches with collision disabled, so that would be nice if it got changed.
