### ISSUE TITLE
"Aliver" living beings

### ISSUE THREAD

**Issue by Raviolibolonesa** [studio-minus/ppg-bugs-and-requests#2903]
### Feature description

the movement of living beings such as humans would change so they can walk, run and jump properly and be also controllable too. at first when you spawn a human it would stand still and do nothing like now, but when right clicking it the option of "make reactive", "go berserk" and "control human" would be available with this new feature i'm describing, when made reactive the humans would run away when they hear gunshots or explosions, become aggresive when being hit by other humans and occasionally wander the place always watching out for cliffs. but when controlling a human you would be able to walk, run, jump, attack with punches or weapons and crouch. this feature i'm suggesting is inspired by the active humans mod, however i would want the humans to be more agile so they can run and jump better like those epic stickman fight videos on youtube.

### Feature purpose

this feature would allow people to do better roleplay and will allow content creators to make videos easier, and it would look awesome too

**Comment by Drogo-man** [comment]
Haha no.

**Comment by Drogo-man** [comment]
Haha no.

**Comment by ghost** [comment]
bro copypasted [Active Humans](https://steamcommunity.com/sharedfiles/filedetails/?id=2163278857) mod
