### ISSUE TITLE
zombie bug

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#291]
**Describe the bug**
zombies seem to have infinite blood for unknown reasons

**Clearly describe how to reproduce the bug**
hook up a blood tank to somebody infected and it will never run out of blood

**Mod list**
none

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.21.3
 - GPU: gtx 1650 super
 - CPU: intel i5

**Additional notes**

**Comment by mestiez** [comment]
Duplicate

**Comment by DindinYT37** [comment]
Actually this is the original but the other issue was way more detailed so I guess.
