### ISSUE TITLE
sentry turret weird when using immobility field

### ISSUE THREAD

**Issue by thetruss** [studio-minus/ppg-bugs-and-requests#2910]
### Describe the bug

immobbity field influences sentry turret without even touching it

### Clearly describe how to reproduce the bug

spawn turret
spawn immolibbity field and activate it and move it around infront of the turret

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11585431/exported.game.debug.info.md)

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/116781200/8aac4f00-95f9-4d53-9514-f0cf7dd244a9

**Comment by mestiez** [comment]
fixe
