### ISSUE TITLE
Dropping 1000 kg weight on human toes breaks them

### ISSUE THREAD

**Issue by YourLocalPlonker** [studio-minus/ppg-bugs-and-requests#2911]
### Describe the bug

Humans pass out and often just completely fracture after having 1000kg weight fall on their toes

### Clearly describe how to reproduce the bug

spawn a human, spawn a 1000kg weight and drop it from approximately the middle of their shin.

### Mod list

-A bunch of FMB furry mods
-signals and logic gates
-quality of life 
-invisible wires mod

### Game version

1.26

### Operating System

Windows 10

### Additional notes

![20230531161314_1](https://github.com/studio-minus/ppg-bugs-and-requests/assets/96140624/51e15b0d-c0b1-401c-98d6-2249dc61fc87)
![20230531161327_1](https://github.com/studio-minus/ppg-bugs-and-requests/assets/96140624/1c39b574-c9ad-457f-9338-e0be7de5f3be)

Edit: This works for anything that damages the feet, not only the 1 ton weight

**Comment by Drogo-man** [comment]
This is a well know bug with no easy fix.

**Comment by mestiez** [comment]
Not exactly a bug, but a side effect of a little "impact propagation" system I implemented quite a while ago. I could just disable it but not without disabling the system entirely. So far I have not considered that worth it.
