### ISSUE TITLE
Objects deforming or melting, when they are extremely hot

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#2913]
### Feature description

I would like to see metal objects, from mods, and/or from the original game, under a thrusterbed, or a jet engine, really anything hot OR in a contraption designed to incinerate things, to see it glow and turn into a fine paste like in the Powder Toy. I'm guessing this is hard to implement ingame, due to limitations of the Unity engine. Like real physics and/or thermodynamics, when metal is EXTREMELY HOT (some turn into liquid near room temp, like gallium, but we are NOT making different metals, maybe we can do that later) it turns into a liquid or fine paste. It's supposed to be a solid, but beyond its melting point, it starts to turn from a solid into a liquid. Due to this physics, maybe it can lag computers, so maybe we can have settings for this mechanic. Maybe we can do this at a specific temp, like a melting point. This could be used in smelting or blacksmithing ingame, maybe something metal can melt due to physics.  Maybe thermodynamics too. And also, I think this can be used to weld stuff together...I mean, realism is pretty nice. Anyways, I'm probably going to be rejected. Because this has been asked too many times, and it's WAY too hard to make...

### Feature purpose

I love incinerating things in the game, and for some reason I don't like it when it's realistic. So if you could make it a little bit realistic, that would be cool, since we already have the Deformation Mod, so I would love to see metal melt under extremely high temperatures, like when scrap metal is incinerated, and the metal turns into a fine paste, I would love to see this ingame. And no, it doesn't exist in some form, it doesn't exist at all.

**Comment by SaturnAndItsRings** [comment]
hello?

**Comment by SaturnAndItsRings** [comment]
helllooooo?

**Comment by Drogo-man** [comment]
Ahaha no.

**Comment by ghost** [comment]
liquid physics will be added in ~9.9999e+13 business days

**Comment by ghost** [comment]
lol yeah

**Comment by DindinYT37** [comment]
Duplicate of or related to:
* #655
* #659
* #769
* #1222
* #1440 (kind of)
* #2116
* #2392
* #2895
