### ISSUE TITLE
Make shooting humans more realistic/satisfying

### ISSUE THREAD

**Issue by ras09191** [studio-minus/ppg-bugs-and-requests#2915]
### Feature description

When shooting humans in the chest multiple times (lets say 3 for reference) they drop to the ground but move their arms a lot. In real life if you shoot someone in the chest or higher (but not the head) they usually dont move a lot or they stop moving, if you want an example look at videos of people being shot in the chest or just being shot in the torso in general). 

Humans should not be doing flips when they are shot. Ive shot humans and often because of their animation or something like that they flip the fuck out, its funny to watch but annoying as its unrealistic.

Wounds that humans sustain when shot below the chest should be more fatal. They currently arent that fatal. For example when shot in the middle body part the human usually doesnt react or moves a little then stands up until he passes out do to blood loss.

Shooting someone in the chest with a shotgun should be a lot, lot more fatal and should make humans unconscious immediately (not being able to move at all). I highly doubt that someone that has been shot in the chest with a shotgun would be able to move at all. They would be paralysed due to the shock or be dead very very quick as their heart would be destroyed or damaged.

Gun wounds should bleed for longer. Ive shot people and sometimes, the first time they were shot their wound stopped bleeding after like 15 seconds. I have slow healing disabled in settings btw.

Zooi i know that requesting multiple features shouldnt be done but for gods sake if you can implement all of this as that would make shooting humans more satisfying and would be a major improvement to humans.

### Feature purpose

These features would be implemented to make the game more realistic and to make humans less goofy and make shooting people more satisfying. Realism tends to be a lot more satisfying as thats what we live in and are used to.

**Comment by ghost** [comment]
> if you want an example look at videos of people being shot in the chest or just being shot in the torso in general

sanest ppg fan

**Comment by DindinYT37** [comment]
Multi-requesting makes it really hard for zooi to accept this feature-request, as it's impossible to only accept one feature from this issue without accepting the entire issue.

**Comment by ras09191** [comment]
DindinYT he did it once though.

Also, he can accept only one of these if he wants.

**Comment by DindinYT37** [comment]
> DindinYT he did it once though.
> 
> Also, he can accept only one of these if he wants.

Just because it has been done before, doesn't mean this rule isn't effective anymore. Additionally, if he wanted to only accept one of these – how would he mark this issue? As feature-accepted or as feature-rejected?

**Comment by mestiez** [comment]
I don't want to look at videos of people being shot, lol.
Anyway I could just decrease the amount of adrenaline they get when they are shot.  I agree that humans are too rigid when in shock. However because this issue contains multiple requests, I have to close it without accepting it. This doesn't mean I won't implement any of them, however. Please don't group them next time.

**Comment by ras09191** [comment]
Ok, ill write only single features from now on.
