### ISSUE TITLE
ex. X does Y instead of Z

### ISSUE THREAD

**Issue by userNotAvalible** [studio-minus/ppg-bugs-and-requests#2922]
### Describe the bug

Dolls have a strange collider on feet part, It's too big at the back. Also by damaging the feet collider at the back the whole back and legs or just the legs gets badly damaged (killed)

### Clearly describe how to reproduce the bug

Putting an object behind the feet

### Game debug info

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/87705107/4689f2ed-61b7-4335-8e5b-515f5956293c)

**Comment by ghost** [comment]
the invisible thing is for stability, and the body breaking bug has no easy fix
