### ISSUE TITLE
Mirrors do not reflect lasers that have passed through more than 6 panes of glass.

### ISSUE THREAD

**Issue by Koshi32** [studio-minus/ppg-bugs-and-requests#2924]
### Describe the bug

if a laser passes through more than six panes of glass (7+), then mirrors will not reflect the laser and it will instead pass straight through.
![20230610135816_1](https://github.com/studio-minus/ppg-bugs-and-requests/assets/102936027/2f25a335-a227-4084-907e-625ea29f624d)
![20230610135820_1](https://github.com/studio-minus/ppg-bugs-and-requests/assets/102936027/e3e9d31f-2637-413a-8f06-dbef0c5eae56)

### Clearly describe how to reproduce the bug

place more than six panes of glass (at least seven) between a laser emitter or the last surface the laser has reflected off of and it will no longer be reflected off mirrors.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11713018/exported.game.debug.info.md)

### Game version

1.26.6

### Operating System

Windows 10

### Additional notes

bug occurs with no mods active.

**Comment by mestiez** [comment]
Not a bug, just a hardcoded limit
