### ISSUE TITLE
Activations not working

### ISSUE THREAD

**Issue by Nechoaura** [studio-minus/ppg-bugs-and-requests#2942]
### Describe the bug

I have a loop of activations where it cycles indefinitely, problem is after one cycle the items being activated stop responding to the activation single. For example: If after a cycle the next item that's supposed to be activated is a piston, the piston would receive the signal but would not move, it only sends the signal to the next item in the cycle and that item would also not respond and only carry the signal 

### Clearly describe how to reproduce the bug

the cycle i have is for a "fully automatic" firing gun i made myself, however i suppose you could connect multiple pistons to lagbox's in a chain that repeats itself, since basically that's all my gun is

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11780591/exported.game.debug.info.md)

### Mod list

i have well over 30+ mods, so sorry but i didn't bother to type all of them

### Game version

1.26.6

### Operating System

Windows 11

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/136946449/50169406-160e-4f63-8223-1a19854c37e7

**Comment by DindinYT37** [comment]
This is intended behavior, loops like these aren't supported. Consider using a metronome instead.
