### ISSUE TITLE
Obtainable liquids via lakes

### ISSUE THREAD

**Issue by LongerBlade** [studio-minus/ppg-bugs-and-requests#2947]
### Feature description

Give to a syringe or whatever liquid container, the ability to take liquid from the lake, etc lava or water pool. Tanks with the water and lava. Lava container is heated up constantly 

### Feature purpose

The shower head with a water inside can extinguish objects and clean objects, act similar as a soap, doesn't leave traces as other liquids. The shower with a lava starts fire when hit

**Comment by Drogo-man** [comment]
Hehehe no
