### ISSUE TITLE
Incorrect particle display

### ISSUE THREAD

**Issue by SavaTG** [studio-minus/ppg-bugs-and-requests#2960]
### Describe the bug

If Plate spawned by pressing 'Q' it does not display particles on  breaking

### Clearly describe how to reproduce the bug

Select plate and spawn it with 'Q' button

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11878984/exported.game.debug.info.md)

### Additional notes

Also **Tempered Glass Pane**, **Glass Pane** and **Vase** does not display particles when spawned by 'Q' button and then broken

**Comment by mestiez** [comment]
Fixed :)
