### ISSUE TITLE
Increase maximum of physics iteration

### ISSUE THREAD

**Issue by wiksadeey** [studio-minus/ppg-bugs-and-requests#2963]
### Feature description

We have 128 as maximum in settings, but it's not enough.

I've used cheat engine to increase it, physics became some more accurate.

### Feature purpose

This is not so hard request. Useful feature

**Comment by mestiez** [comment]
i was against this at first but who caaaaaaaaaaaaares

**Comment by Drogo-man** [comment]
Yes, MY PC WILL RIVAL THE SUN!
