### ISSUE TITLE
add recoil to the fire extinguisher

### ISSUE THREAD

**Issue by WWWOWWWPL** [studio-minus/ppg-bugs-and-requests#2970]
### Feature description

add some slight recoil to the fire extinguisher when it fires its extinguishing foam

### Feature purpose

fire extinguishers can move other objects with their exhaust but they don't move themselves in the process, which breaks newton's third law. also you could make cool cold gas thrusters out of them for use in 0g.

**Comment by Aspa102** [comment]
cool
ill look at it

**Comment by Aspa102** [comment]
added :)
