### ISSUE TITLE
people I click on teleport away.

### ISSUE THREAD

**Issue by Greendinoflower** [studio-minus/ppg-bugs-and-requests#2976]
### Describe the bug

when I clicked on a human they formed a ball with all of their body parts in one location and teleported like that to the left side of the map and when another person was clicked both that person and the previous people teleported to the same location on the left of the map

### Clearly describe how to reproduce the bug

I have tried to recreate the bug but have been unsuccessful but I can provide info as to what i was doing when it happened.

in the humongous map I spawned in 8 people next to each other facing left. I then spawned a workshop creation called the liquid machine with e to the left of the people I then proceeded to accidentally drain all of the people of their blood by connecting them to the machines tap with liquid conduits and deleted those same conduits. Once that happened, I selected the yellow button on the machine to dispense nitro-glycerine and pressed the green button to confirm. Then I spawned 8 blood tanks to the left of the machine with e, set them all to pull in ascending order and connected conduits between them and the tap of the machine. When one filled up I would delete that ones conduit until all of them were full. once this happened i deleted all of the machine except for the button and deleted the button separately. Once that was all done when I tried to move the people closer to the machine they teleported one by one to the left side of the map and grouped into a little ball.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/11991071/exported.game.debug.info.md)

game crashed right after so not sure if that affects this in any way

### Mod list

oh boy you better strap in for this.

AIRPLANE SU-27 MOD-ACTIVE

HOWITZER 2C3 MOD-ACTIVE

M1A2 ABRAMS MOD REMAKE-ACTIVE

INFECTION MOD-ACTIVE

ABYSSAL FAUNA +-ACTIVE

WATERTIGHT BOX-ACTIVE

SITE PARAGON-ACTIVE

TERRARIA AI-INACTIVE

SYRINGE GUN-ACTIVE

[INC'S] AIRSTRIKE MOD-ACTIVE

HORRIBLE DISEASES MOD-ACTIVE

LAV-25 MOD-ACTIVE

WAR UPON THE WESTERN FRONT, WORLD WAR 1 MOD (WW1) V1.2-ACTIVE

MULTILIFE MOD [UPDATED]-ACTIVE

TOS-1A SOLNTSEPEK MOD-ACTIVE

CYBERS WORLD WAR MOD-INACTIVE

GUN SMOKE TRAILS- ACTIVE

JMC'S SCP-106-ACTIVE

WEAPON SIZE AFFECTS ITS POWER MOD-INACTIVE

JMC'S SCP-939 MOD-ACTIVE

JMC'S SCP-035 MOD-ACTIVE

JMC'S SCP-610 MOD-ACTIVE

PROSTHESES-ACTIVE

RGB ENERGY SWORD-INACTIVE

from now on i'm just going to type a for active and i for inactive

JMC'S SCP-009 MOD-A

JMC'S SCP-076 MOD-A

EVERYTHING COLOURABLE-I

JMC'S SCP-096-A

LIQUID LOGIC-A

JMC'S SCP-049-A

REQUIEM HUMAN V2-I

TORTURE MOD-A

JMC'S SCP-173 MOD-A

ATTACHABLE-I

TACTICAL STYLE MOD-I 

[IMPROVED] PICKUP ADVANCED (PICKUP ANYTHING)-A

OTHER-LIFE: TT PERSONAL AND SARMA PERSONAL-I

DRAGON CUSTOM ENTITY-A

BUBBLEGUM HUMAN MOD-I

BEAR EFT-I

FIRE REMOVER BUTTON-A

FUNCTIONAL HELICOPTER MOD-A

PPG: CIVILIANS-I

DEAD CREATURES REMOVER BUTTON-A

CATEGORY SWITCHER-A

GAS CAN-I

UNDERGROUND COMPLEX-I

DESTRUCTIVE WARFARE-I

UNITED NATION: UNINVOLVED IN PEACE-I

M1A2 ABRAMS 2.0-A

LEPARD 2A5 2.0-A

ADVANCED ZOMBIE INJECTOR (V1.2)-A

BARBEQ'S SKYWALKER SAGA-SUSPICIOUS

FUNCTIONAL TERMINATOR MOD-A

MORE VEHICLES-A

BACKROOMS PLAYGROUND-I

REALISTIC AXE MOD-I

RELOADABLE EXPLOSIVE WEAPONS-A

MORE THAN WARDEN MOD-I

AERODYNAMICS-I

DARTH VADER-I

THE ULTIMATE CAR MOD-I

THE BACKROOMS MOD-I

WATER PHYSICS-I

POPULAR SCPS-I

REACTIVE HUMANS-I

RANDOM JEDI MOD-I

ACCURATE RESIZE AND POSITION-SUS

LIGHTSABER PROPS-I

SCP ARMORY-A

DETAILED MOBILE TASK FORCES-A

STAR WARS POWER PACK-I

PEOPLE PLAYGROUND 3D-I

THE NEARBY CONFLICTS BASE: US ARMY-I

OUTDATED MILITARY TRUCK-I

IMPERIAL TROOPERS MOD PACK-I

BATTLE DROIDS MOD PACK-I

CLONE TROOPERS MOD PACK-I

CONTROLLED SEA (FIXED FOR 1.24)-I

PRIVATE MILITARY CONTRACTORS-I

LAW ENFORCEMENT BASE: GERMANY-I

LAW ENFORCEMENT BASE: LESS LETHAL DLC-I

SIMPLE PORTALS-I

ACID SEA (FIXED)-A

LAW ENFORCEMENT BASE: USA

FIVE NIGHTS AT PEOPLE PLAYGROUND-I

from now on if i don't put I or A at the end it's Inactive.

NANOTECH MOD

CRIN'S CIVIL WAR MOD

WOUND INFECTIONS

NIMROD SAS

LIMB REGROWTH SYRINGE (PASSIVE)

FREDDY FAZBEAR'S PIZZARIA BUILDING KIT!

MILITARYMOD EXPANSION: WARLORDS

A WW 1 THEMED MOD (WEAPONS INCLUDED)

TORNADO MOD V1.0

RUSSIAN TEXTURE PACK

SCP FOUNDATION FACILITY MOD

SOVIET FIRARMS

SCP: PPG EDITION

BAROTRAUMA JOBS-A

THE GRAPPLING GUN MOD-A

COMBAT LIGHTSABERS MOD (RE-CODED)

STAR WARS EXPANDED CLONES 

MILITARYMOD EXPANSION: WW2

STARWARS: CLONES MOD

{ SCP-610 MOD ]

A BIG POTATS WW2 MOD

SQUID GAME ITEMS AND PERSONAGES

SQUID GAME MOD BY CLIFFYROCKET038

SQUID GAME MOD BY CIOSS

SQUID GAME MOD BY BLUBSSUBS

ITEM PLUS

CALL OF DUTY: MODERN WARFARE 2

TF2 MOD

FISH MOD

OBJECT EDITOR

MILITARYMOD

DEAD NO COLLIDE

PROTOTYPE 1 MOD

SPACE MOD

TABS MOD

HENRY STICKMAN COLLECTION MOD

QUICK RIGHT CLICK OPTIONS

GREEK AMRY WW2 MOD -amry isn't a typo

POWER PACK FRAMEWORK

SIGNALS AND LOGIC GATES

ANIMATED WEAPONS+

THE MUSKET MOD-A

QUALITY OF LIFE ITEMS

NUCLEAR PLAYGROUND 

SCP-018

IMPERIAL NAVAL BASE [MAP]

LAWLESS - HIGH PROFILE OPERATIONS

MAP BLOCKS-A

COMBAT SPEC-OPS MAP

COPPER REPUBLIC MOD

S.C.P. FOUNDATION EXPANDED-A

FTC WEAPONS-A

TASER

STAR WARS DARK SABER MOD

S.C.P.F. MOD-A

HUMAN TEIRS

AMONG US MOD

CHEICAL WARFARE

VIETNAM SOLDIERS MOD

CYBERS WWII MOD

UNSC SOLDIERS MOD

SMART SPAWNER

STARWARS INFANTRY MOD 1.4

STAR WARS SITH AND JEDI MOD 3.3

CONTROLLABLE ANTI-AIR CANNON-A

FNAF MOD

ROCKET MOD

SOROR'S NPC PACK

HUMANS+

ACTIVE HUMANS-A

CONSTRUCTION KIT V0.9.5

COMBAT PROPS PACK

finally over that took like an hour to write out hope it helps. congrats on making it to the end of this.

### Game version

1.26.6

### Operating System

windows 11

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/138997445/89361776-a202-4dfd-a677-3842f8586fe4

**Comment by Greendinoflower** [comment]
i am so sorry for what you have to go through here.

**Comment by Greendinoflower** [comment]
you can ask any questions here as i remember it quite well and will check this page a few times a day.

**Comment by Drogo-man** [comment]
This is a very common bug, dunno if zooi is working on a fix.

**Comment by Greendinoflower** [comment]
thank you I didn't know if anyone had encountered this before. Do you know how to recreate it?

**Comment by Drogo-man** [comment]
Idk, nobody really knows.

Probably unity doing the funny, but who knows.

**Comment by FrAmed46** [comment]
least modded ppg player:

**Comment by myron-obsolete-account** [comment]
> least modded ppg player:

I have way less mods duh
