### ISSUE TITLE
Ragdoll physics/interaction is locking FPS to 60 at random.

### ISSUE THREAD

**Issue by ZeekScripts** [studio-minus/ppg-bugs-and-requests#2980]
### Describe the bug

When ragdolls are placed in the game world, and when the game settings allow for >60FPS in normal cases (I use a 144HZ monitor), interactions with the ragdolls (including with the environment) seem to immediately lock the screen FPS to 60. This nullifies any benefit of having >60FPS as it is never utilizied.

**Additional problem**

When loading into the world, FPS is locked into 60. You must press escape (to open the menu) then return to uncap the FPS.

### Clearly describe how to reproduce the bug

**Game Settings**
Mods: None
Collision Mode: Continuous 
Iteration Count: 16
Window Mode: Borderless
V-Sync: **Disabled**
Framerate Limit: 1000 (I tried 144, 300 as well)

**My specs**
12 Core i7 12700k
64GB DDR4 RAM
3070ti GPU w/6GB

**Test Case**
Ensure that when you load into the game world you press escape and return to uncap your FPS. Place down two ragdolls on any map without damaging them. You should see the FPS is still largely above 60 (on my machine). Cause some damage either between the ragdolls or with one ragdoll (e.g throwing it to the ground or punching another). The screen should now lock to 60FPS. 

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12021825/exported.game.debug.info.md)

### Additional notes

This appears to be affecting several game system interactions and does prevent me from playing the game at >60hz.

Multiple different interactions (including some UI elements) cause this performance degradation but this is the most obvious.

**Comment by Squibard** [comment]
turn v-sync off but doing so may cause your screen to "tear"

**Comment by Squibard** [comment]
idk if it will work but maybe

**Comment by ZeekScripts** [comment]
v-sync has no effect  on this, my monitors refresh rate is 144hz, meaning it should get >60fps if it is syncing to my monitors refresh rate. This is a bug.

**Comment by mestiez** [comment]
I cannot reproduce this whatsoever
