### ISSUE TITLE
MultiPlayer

### ISSUE THREAD

**Issue by VVanshHI** [studio-minus/ppg-bugs-and-requests#2985]
### Feature description

Multiplayer mode. In multiplayer you will be able to play with friends and have fun. It's going to be a lot of fun!

So I hope you add! Best regards!

### Feature purpose

Features: It would be fun with friends.

### Additional context

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/139468385/04079e9f-8333-4d90-b231-cc3338ff0675)

**Comment by ghost** [comment]
no

**Comment by ras09191** [comment]
No

**Comment by 2xddev** [comment]
no

**Comment by Squibard** [comment]
no

**Comment by Aspa102** [comment]
keep an eye out for PPGT on the steam workshop, its basically a multiplayer mod 👍

**Comment by Aspa102** [comment]
and to also answer your actual question, no, ppg will never be officially multiplayer.
