### ISSUE TITLE
heat increasing from nothing

### ISSUE THREAD

**Issue by maplestake101** [studio-minus/ppg-bugs-and-requests#2987]
### Describe the bug

If the wooden pillar, wooden pole, giant wooden bowl, crate, wooden chair, wooden wheel, and wooden table is set on fire in any way it will start to rapidly gain more heat then cool down then gain heat again and wont stop until it will no longer burn.

### Clearly describe how to reproduce the bug

Spawn in any of the objects listed above.
Set it on fire in any way.
And now its bugged.

### Game version

1.26

### Additional notes

If I knew how to take a screenshot I would

**Comment by u0068** [comment]
thats because, just like in real life, things get hot when they burn
