### ISSUE TITLE
Heat seeking missile has no temperature/burn effects on its thruster, and also does not run out of fuel.

### ISSUE THREAD

**Issue by djspencer777** [studio-minus/ppg-bugs-and-requests#2993]
### Describe the bug

Missile from the 'missile launcher' has no temperature or burn efffects on its thruster. It also does not run out of fuel, and you can keep it on somewhere for theoretically forever

### Clearly describe how to reproduce the bug

Fire the missile launcher, grab the missile at 20% speed to help, then tether it with a rope/cable/etc. Use a human underneath the thruster of the missile, and nothing happens.

### Mod list

- A crap ton of damage
- Liquid Logic
- LAB HumsV
- Biological Research Centre
- Blood On Walls
- Electric chair
- Feet Aren't Indestructable
- Syringes+
- Humans+
^^
All Active

### Game version

1.26

### Operating System

Windows 10

**Comment by inferknob** [comment]
Not a bug.

**Comment by mestiez** [comment]
?????
