### ISSUE TITLE
Humans defy gravity

### ISSUE THREAD

**Issue by NDM03** [studio-minus/ppg-bugs-and-requests#3]
**Describe the bug**
if i throw a human in the air it comes down way to slow which results in a soft landing

**Clearly describe how to reproduce the bug**
I dont know how to reproduce this bug that is kinda the problem

**Mod list**
Nuclear mod 0.7 by kubulll
this is the only one and its activated

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: newest version (1.17.3)
 - GPU: Nvidia gtx 1650
 - CPU: Intel core I5-9600F

**Additional notes**
I have a mp4 file that shows the bug but its more than 10MB, so if you are interested in that pls send me a message on discord: N_D_M03 #5892

**Comment by mestiez** [comment]
That link directs the user to their own subscriptions page. An actual list would be preferred.

**Comment by NDM03** [comment]
i updated the list for you

**Comment by Alexisz998** [comment]
Hey, i found a way to make a human defy gravity. In fact he is slowed down and land slowly on the ground. To repoduce it you spawn a human next to a wall in any map (it has to be a map wall). If you spawn it at the right distance he slowly fall, maybe than his feet doesn't know if there's ground or not under him. I tried it without mod and it worked still. Hope it can help!

**Comment by NDM03** [comment]
> Hey, i found a way to make a human defy gravity. In fact he is slowed down and land slowly on the ground. To repoduce it you spawn a human next to a wall in any map (it has to be a map wall). If you spawn it at the right distance he slowly fall, maybe than his feet doesn't know if there's ground or not under him. I tried it without mod and it worked still. Hope it can help!

Thank you I hope zooi can find the problem now

**Comment by mestiez** [comment]
fixed lol
