### ISSUE TITLE
Speed limit on objects?

### ISSUE THREAD

**Issue by 2xddev** [studio-minus/ppg-bugs-and-requests#3003]
### Describe the bug

I do not know whether this is intended, a "feature" of unity or genuinely a bug, but it seems like there is some sort of max speed for how fast objects can move. I stumbled upon this while trying to make a vehicle reach the speed of light: When you make an object hit 5000 units per second (14832 km/h, or 4120 m/s or whatever), you will be unable to increase the velocity.

### Clearly describe how to reproduce the bug

Step 1: Get an object and attach a speedometer to it, from a mod or whatever. UnityExplorer will work to check velocity too.
Step 2: Make the object go fast, and wait for it to reach 5000 units per second.
Step 3: Observe as the object is unable to accelerate further.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12139157/exported.game.debug.info.md)

**Comment by 2xddev** [comment]
By the way, if this is actually intended, would it be possible to get a way to change or completely disable this speed limit? Thank you in advance.

**Comment by ghost** [comment]
It's the Aerodynamics mod, disable it.

**Comment by 2xddev** [comment]
> It's the Aerodynamics mod, disable it.

Holy shit, you're a fucking genius.
I completely forgot I had that mod enabled. Thank you!

**Comment by 2xddev** [comment]
> > It's the Aerodynamics mod, disable it.
> 
> Holy shit, you're a fucking genius. I completely forgot I had that mod enabled. Thank you!

May I just add that I just disabled the mod, restarted, made a new vehicle, and that the limit it still in place after all this?

**Comment by ghost** [comment]
Disabled mods can affect your game too

**Comment by 2xddev** [comment]
> Disabled mods can affect your game too

Just uninstalled the aerodynamics mod, limit *still* seems to be in place

**Comment by 2xddev** [comment]
accidentally closed

**Comment by 2xddev** [comment]
I also decompiled some game files, haven't found anything that points towards this being intentional

**Comment by ghost** [comment]
Some other mod also does this then

**Comment by 2xddev** [comment]
> Some other mod also does this then

Okay, another update. I have completely removed every single mod except for Infinite Map, CloddyMod and QoLI. The speed limit is still in place. I have either overlooked something in the game's code, or one of these 3 mods is doing this.

**Comment by mestiez** [comment]
Not a bug. The physics engine has a speed limit of 100 units per update.  Physics updates at a fixed rate of 50hz so your 5000 units per second thing is accurate.
