### ISSUE TITLE
activation toggle is bugged

### ISSUE THREAD

**Issue by HBRT12** [studio-minus/ppg-bugs-and-requests#3004]
### Describe the bug

when an activation toggle is blown up, you can still use it as normal, even though it shows the 'repair' option in the context menu

### Clearly describe how to reproduce the bug

1. spawn an activation toggle and connect it to something
2. spawn a grenade on it and detonate it
3. if you try to use the trigger after it blew up, it still works.

### Game version

1.26 (64 bit)

### Operating System

Windows 11 Home (version 22H2)

**Comment by mestiez** [comment]
Duplicate
