### ISSUE TITLE
ex. X does Y instead of Z

### ISSUE THREAD

**Issue by measilius** [studio-minus/ppg-bugs-and-requests#3005]
### Describe the bug

Game ruining bug where spawning 3 or more of a texture or having 3 or more at one time on the screen causes them to turn invisible. I've tried every setting, deleting and reinstalling, nothing helps. I found someone with the same bug on the steam page, but nobody offered a solution. PLEASE look into it. Running on Parallels MacBook M1

### Clearly describe how to reproduce the bug

Spawn 3 or more of anything. Most prominent is wood, resizable housing and syringes and tires. Must have same textures.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12147159/exported.game.debug.info.md)

**Comment by inferknob** [comment]
please change the name

**Comment by ras09191** [comment]
shut up the dev wont implement

**Comment by inferknob** [comment]
> shut up the dev wont implement

wow thats harsh don't be rude
do you have anything better to do than say "shut up" on the internet?

**Comment by mestiez** [comment]
I have no idea what's going on here
