### ISSUE TITLE
The Utils.EscapeRichText method can be bypassed

### ISSUE THREAD

**Issue by Melodi17** [studio-minus/ppg-bugs-and-requests#3011]
### Describe the bug

This method's intent is to prevent rich text from the input string from being shown, but using `.Replace("noparse", "")` is insecure

### Clearly describe how to reproduce the bug

This can be circumvented by the following:
```csharp
Utils.EscapeRichText("</nonoparseparse>Code here will be parsed as it is NOT enclosed<nonoparseparse>");
// Returns: <noparse></noparse>Code here will be parsed as it is NOT enclosed<noparse></noparse>
```
This is due to the `.Replace` method replacing the noparse present, which, in turn makes the word because of the surrounding text (sorry if that sounds unclear)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12167258/exported.game.debug.info.md)

### Additional notes

Considering this is used in various places, including ones that the input is take from a third party (mods), this is a potentially serious issue.

**Comment by mestiez** [comment]
oh, clever

**Comment by mestiez** [comment]
Fixed it using regex but it's obviously a little slower.
