### ISSUE TITLE
(Coding request) You can change a blood particle's color when modding a new human

### ISSUE THREAD

**Issue by inferknob** [studio-minus/ppg-bugs-and-requests#3028]
### Feature description

Okay, so when you mod in a new human, well a reskinned one, there should either be 2 things

* the already in "blood color" variable should also change the particle's color
or
* there is a new variable with "particle color" which does the same thing.

thats it.

### Feature purpose

For the sake of the sanity of mod developers everywhere who just wanted to make a custom human and are annoyed that the particles are gone
For the sake of the collective of humanity
For your parents and their parents and so on
For your fellow human beings who inhabit this ball we call earth
For our sanity

### Additional context

okay i went too far there maybe but it was funny

happy august

**Comment by Aspa102** [comment]
changing the liquid in a person's body should do this 👍
