### ISSUE TITLE
decoupler detaches with force in the wrong direction

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#3031]
### Describe the bug

when the decoupler is spawned using (q) instead of (e) and you activate it' it will then detach in the wrong direction.

### Clearly describe how to reproduce the bug

spawn a decoupler with q then activate it

### Mod list

None

### Game version

1.27 preview

### Operating System

Windows 11

**Comment by mestiez** [comment]
fixed
