### ISSUE TITLE
ex. X does Y instead of Z

### ISSUE THREAD

**Issue by dralexf** [studio-minus/ppg-bugs-and-requests#3033]
### Describe the bug

i can't move

### Clearly describe how to reproduce the bug

i can't move

### Game debug info

i can't move

### Mod list

i can't move

### Game version

 The exact game version (ex. `1.27 preview 1`)

**Comment by royalealbert27** [comment]
cloddy mod moment

**Comment by fhgb54643689** [comment]
most intelligent bug reporter
