### ISSUE TITLE
Reactor A5 map easily able to be deleted

### ISSUE THREAD

**Issue by VelocityMyth** [studio-minus/ppg-bugs-and-requests#3036]
### Describe the bug

Reactor A5 map can easily be deleted

### Clearly describe how to reproduce the bug

If you select the "CURRENT REACTOR DATA" text display and delete it, it deletes the entire map basically recreating the 'Void' map.

### Game version

1.26

### Operating System

Windows 10

**Comment by mestiez** [comment]
i know
