### ISSUE TITLE
New map nuclear reactor camera is frozen

### ISSUE THREAD

**Issue by Yeetingboy76** [studio-minus/ppg-bugs-and-requests#3037]
### Describe the bug

When launching ppg and finding that there is a new map I went in. I was greeted with a small lagspike but once the lights turned on I tried to move the camera and was not able to. Even when using arrow keys I couldn't move the camera. Trying to camera follow a moving car would result in me pressing the button but nothing happens besides the top left saying I am following the car.

### Clearly describe how to reproduce the bug

I believe to recreate this bug you first have to load into the map but once you are loading during the section where the map has loaded but is dark and there is no menu try moving the camera. This might just recreate the bug although I am not sure.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12327190/exported.game.debug.info.md)

### Game version

1.27 preview 1 (64 bit)

### Operating System

Windows 10

**Comment by royalealbert27** [comment]
probably cloddy mod?
