### ISSUE TITLE
Activated weightless decoupler doesn't apply force until it is touched

### ISSUE THREAD

**Issue by Alextimka** [studio-minus/ppg-bugs-and-requests#3038]
### Describe the bug

https://github.com/studio-minus/ppg-bugs-and-requests/assets/59509074/00333733-5c70-4b98-87b2-759d952959de

### Clearly describe how to reproduce the bug

Make the decoupler weightless, activate it, then touch it with something

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12327208/exported.game.debug.info.md)

**Comment by mestiez** [comment]
fixed
