### ISSUE TITLE
Object outline issue while dragging

### ISSUE THREAD

**Issue by Flakerisu** [studio-minus/ppg-bugs-and-requests#3041]
### Describe the bug

The green outline does not disappear until the cursor leaves the object's hitbox.
If the cursor is moved outside the hitbox and then back inside, letting go will cause the hitbox to not appear again until the cursor leaves the hitbox once more, or until the Drag tool is used.

https://github.com/studio-minus/ppg-bugs-and-requests/assets/68897454/7e80db79-e115-49aa-8078-b7fc281b1177

### Clearly describe how to reproduce the bug

1. Enter a map
2. Spawn an object (any)
3. Move the object around using the Drag tool

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12327267/exported.game.debug.info.md)

### Mod list

Not subscribed to any mods.

### Game version

1.27 preview 1 (64 bit)

### Operating System

Windows 11 Pro

**Comment by mestiez** [comment]
fixed
