### ISSUE TITLE
1.27 all mods' custom controls not working and no modded section in control settings

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#3042]
### Describe the bug

title (ex. a mod uses x to super slow mode but 1.27 removes the custom controls so we can't use it + flipping heck still works because the key is already in the code whereas the first example uses the custom controls in the control settings to use whatever key)

### Clearly describe how to reproduce the bug

get a mod with custom controls that can be rebind in the settings then find it but you cant because there is none so you can't use it

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12327448/exported.game.debug.info.md)

**Comment by mestiez** [comment]
fixed
