### ISSUE TITLE
Makes the camera immovable (Most likely caused by a mod in the Beta 1.27 1 preview) (Game works fine with no mods*)

### ISSUE THREAD

**Issue by SpaceShuttleFan** [studio-minus/ppg-bugs-and-requests#3045]
### Describe the bug

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/125271643/08ee3306-1597-4d1d-9c58-0a1a29c980ec)
 Makes the camera force to an object that doesn't visually exist, you cannot move the camera or use the scroll wheel and using the "follow" option in the context menu does nothing other then change the the text from "GameObject name" to for example a "Piston".

### Clearly describe how to reproduce the bug

Wait for all mods to load and compile, load any map.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12327551/exported.game.debug.info.md)

### Mod list

https://youtu.be/cUohVXMtSSc

(the link is a video with all my mods, it saves time doing it this way. or you can read the below)

	Chymera-Cry Of Fear-3015778193 v1.0.0 for game vAny
		Currently inactive

	Pephel-The Ultimate Human Mod: Remastered-3014289153 v1.5 for game v1.21+
		Currently inactive

	01 STUDIO o. d.-Attack On Humans-local v1.0 for game v1.26+
		Currently inactive

	Orsoniks / Navii-Status Icons-2644689646 v0.1 for game v1.22
		Currently inactive

	jimmybob302-Goofy Creatures and Weapons-3009540185 v1.0 for game v1.11
		Currently ACTIVE

	GHOST MODS-T.I.V 2 MOD-3008900139 v0.9 for game v1.26
		Currently inactive

	Mishanya,Modified by: Me-Z-18 China Transport Helicopter Mod-local v0.3.1 for game v1.25+
		Currently inactive

	Qvill and PapayaModified by: Me-WZ-10 China Armed helicopter -local v0.3.1 for game v1.25+
		Currently inactive

	Qvill and PapayaModified by: Me-WZ-19 China Light armed Attack helicopter-local v0.3.1 for game v1.25+
		Currently inactive

	Qvill and PapayaModified by: Me-WZ-20 China Heavy Armed helicopter-local v0.3.1 for game v1.25+
		Currently inactive

	GHOST MODS-SMOKE GRENADE MOD-local v1.0 for game v1.26
		Currently inactive
		Has been initialised

	Vable Studio-Better car-3000581086 v1.0 for game v1.26+
		Currently inactive

	GHOST MODS-AIRPLANE SU-27 MOD-local v18+ for game v1.25+
		Currently inactive
		Has been initialised

	GHOST MODS-HOWITZER 2C3 MOD-2998844334 v1.0 for game v1.26
		Currently ACTIVE
		Has been initialised

	GHOST MODS-M1A2 Abrams MOD REMAKE-local v1.0 for game v1.26
		Currently ACTIVE

	Vable studios-Infection Mod-2996469139 v1.0 for game v1.26+
		Currently inactive

	Timtam-Transformers mod-local v1.0 for game vAny
		Currently inactive

	GHOST MODS-F-16 MOD-local v18+ for game v1.25+
		Currently inactive
		Has been initialised

	Int Team-Clothed Human-local v1.0 for game v1.26.6+
		Currently inactive

	Danger-Stockalike Shotgun Variants-local vNocom for game vversions above 1.16, excluding beta releases.
		Currently inactive

	Dyadyushka Dyadya-Watertight Box-2989799391 v1.0 for game v1.26+
		Currently inactive

	Dyadyushka Dyadya-Just Collars-2985454065 v1.0 for game v1.26+
		Currently inactive
		Has been initialised

	QVILL and Papaya-T-90 MOD-2982253637 v1.0 for game v1.26
		Currently ACTIVE

	Int team-More Nature-2981286071 v1.2 for game v1.26+
		Currently inactive

	01 STUDIO-Terraria AI-2980059286 v1.0 for game v1.26+
		Currently inactive

	Int Team-Front Facing Human (Improved)-local v1.0 for game v1.26.6+
		Currently ACTIVE

	Double You Workshop-Decoration Paradise-2804980196 v1.0 for game v1.14+
		Currently inactive

	Timtam-Rewind Time-2976806643 v1.0 for game vALL VERSIONS
		Currently inactive

	Ass Monke-Plane Mod-2976023903 v1.1 for game v1.26
		Currently inactive

	NeitherFishNorCat-Mutation Syringe-2975243383 v1.3 for game v1.21+
		Currently ACTIVE

	ibiglaser-Everything Attachable-2974958963 v1.0 for game vMORE Attachments
		Currently inactive

	QVILL and Papaya-T90M REMAKE MOD-2974416298 v1.0 for game v1.26
		Currently ACTIVE
		Has been initialised

	Qvill & Papaya-TYPHOON-K MOD-2974125473 v0.9 for game v1.26
		Currently ACTIVE
		Has been initialised

	QVILL and Papaya-TYPE 59 MOD-2971843128 v1.0 for game v1.26
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Colourable Wires-2971831945 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Qvill & Papaya-BTR-82 MOD-2969563141 v0.9 for game v1.26
		Currently ACTIVE
		Has been initialised

	Qvill and Papaya-AH-64 Apache MOD-2967942036 v0.3.1 for game v1.25+
		Currently inactive
		Has been initialised

	Danger-T-34-85-2967543238 vfive fucking pebbles for game vversions above 1.16, excluding beta releases.
		Currently inactive

	Voin01-76mm anti-tank gun ZIS-3-local v0.69 for game vVanilla+ enjoyers
		Currently inactive

	Dyadyushka Dyadya-Regrowth Mod-2966853166 v1.0 for game v1.26+
		Currently inactive

	Qvill & Papaya-BRDM-2-2966208737 v0.9 for game v1.26
		Currently ACTIVE

	Qvill & Papaya-M270 MLRS MOD-local v0.9 for game v1.26
		Currently ACTIVE
		Has been initialised

	Int Team-More Vehicles 2-2963069537 v1.0 for game v1.26
		Currently ACTIVE
		Has been initialised

	QVILL and Papaya-PERSHING M26 MOD-2961848115 v1.0 for game v1.26
		Currently inactive

	megaturn-Modern Firearms 2 [1.2]-2960174793 v1.2 for game vAny
		Currently ACTIVE

	inc, diego_money-[inc's] Airstrike mod-2960071456 v1.1 for game v1.26+
		Currently inactive

	Qvill & Papaya-SMERCH MLRS MOD-2959032592 v0.9 for game v1.26
		Currently ACTIVE
		Has been initialised

	QVILL and Papaya-TIGER 1 MOD-local v1.0 for game v1.26
		Currently ACTIVE

	Timtam-Horrible Diseases Mod-local v1.0 for game v1.26+
		Currently ACTIVE

	Qvill and Papaya-GAZ TIGER-local v1.0 for game v1.26
		Currently ACTIVE

	QVILL and Papaya-BMP-2 MOD-local v1.0 for game v1.26
		Currently ACTIVE

	Qvill & Papaya-LAV-25 MOD-local v0.9 for game v1.26
		Currently ACTIVE

	Sturmgeschutz-ZERO HOUR - Modern Solutions Unit Nine-2948928658 v1.0 for game vpeople.
		Currently inactive

	QVILL and Papaya-M113 MOD-local v1.0 for game v1.26
		Currently ACTIVE

	Blake_LikesTea-War Upon The Western Front, World War 1 Mod (WW1) V1.2-2948695426 v1.1 for game v1.26
		Currently inactive

	ibiglaser / 01 STUDIO-Contraptions Corruption Remover-2947471983 v1.0 for game vAll ppg players
		Currently ACTIVE
		Has been initialised

	01 STUDIO & INT TEAM-Underwater Things-2946415658 v1.0 for game v1.22.3+
		Currently inactive

	QVILL and Papaya-M2 Bradley MOD-local v1.0 for game v1.26
		Currently ACTIVE

	FudgiecatDX-Front Facing Human Mod-local v1.0 for game v1.22+
		Currently ACTIVE

	Therobot143-Ppg Fallout New Vegas Mod-2944198266 v1.0 for game v1.19
		Currently inactive

	QVILL and Papaya-T-14 Armata MOD-2943243581 v1.0 for game v1.26
		Currently ACTIVE

	megaturn-WW2 in PPG-2941728523 v1.1 for game vAny
		Currently inactive

	Mishanya-CCTV Camera Mod-2941446451 v1.0.1 for game v1.26.6+
		Currently ACTIVE
		Has been initialised

	QVILL and Papaya-BM-21 GRAD MLRS MOD-2940397068 v1.0 for game v1.26+
		Currently inactive

	Decibek-DCBK NPC pack-2940015604 v1.0 for game vany version
		Currently inactive

	Ass Monke-Too Many Vehicles-2939448774 v1.2 for game v1.26
		Currently inactive

	QVILL and Papaya and Ass Monke-TOS-1A Solntsepek MOD-local v1.0 for game v1.26
		Currently inactive

	Eduardoeldo-V&T: TAM (Tanque Argentino Mediano)-2935531478 v1.0 for game v1.26
		Currently ACTIVE

	QVILL and Papaya-T-90M MOD-local v1.0 for game v1.26
		Currently ACTIVE

	Eduardoeldo-V&T: Jeep M151-local v for game v
		Currently inactive

	Eduardoeldo-V&T: M113 APC-local v for game v
		Currently inactive

	Eduardoeldo-G&R: Taran Tactical-2932090931 v2.4 for game v1.26+ (Previews too)
		Currently ACTIVE

	QVILL and Papaya-M1A2 Abrams MOD-2931813706 v1.0 for game v1.26
		Currently ACTIVE

	QVILL and Papaya-Himars M142 MOD-2929893610 v1.0 for game v1.26+
		Currently inactive

	KillanGenifer & Gans-Attachments+-local v0.1 for game v1.26+
		Currently inactive

	megaturn-Modern Firearms-2926090676 v1.4 for game vAny
		Currently ACTIVE

	Edu-COD 4: Modern Warfare SAS-2925872403 v1.0 for game v1.21.2+
		Currently inactive

	Radomir_X_Y-Melee Weapons Pack MWP-local v1.0 for game v1.26.2
		Currently ACTIVE

	Bobr-Ultimate Double Barrel Shotgun Mod-local v1.0 for game v1.21+
		Currently ACTIVE

	Dyadyushka Dyadya & Dyadyushka Danya-Garbage Mod-2919683137 v1.1 for game v1.26+
		Currently inactive

	Agbebk-Random Weapons Pack BETA-2917977692 v0.5 for game vshashlyk
		Currently ACTIVE

	Please Halp-Gun Smoke Trails-2908115498 vpenis for game v1.26
		Currently inactive

	Int Team-Christmas Mod-local v1.0 for game v1.25+
		Currently inactive

	Dyadyushka Dyadya-Text Speecher-2901712357 v1.0 for game v1.26+
		Currently inactive

	FredMichalBear-Roomba mod-local v1.0 for game v1.15
		Currently ACTIVE

	Dyadyushka Dyadya-Grip Fix-local v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	NeitherFishNorCat-Shapeshifter-2898992213 v1.0 for game v1.21+
		Currently ACTIVE

	zuccian-Physical Bullets-2894478669 v1.0 for game v1.26+
		Currently inactive

	Digito-The Vehicle Project: IVECO-LMV-local v1.0 for game v1.25+
		Currently inactive

	Dyadyushka Dyadya-Ultimate Map Blocks-2891519401 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	tornado-Serbian Armed Forces-local v1.0 for game v1.20
		Currently ACTIVE

	Footballboy-SCAV-2848757517 v1. for game v1.20
		Currently inactive

	zooi-Flying Saucer-2859107587 v1.0 for game v1.9.5
		Currently inactive

	Chomuske and Smerch-Russian PMC weapons mod-2883903756 v2.4 for game v1.8 +
		Currently inactive

	Edu-BOPE Mod-2882435128 v1.0 for game v1.21.2+
		Currently inactive

	roff-[1.1] Cat Gun-2882380580 v1.1 for game v1.21+
		Currently inactive

	JulianMagicCraft-JMC's SCP-610 Mod-2882290055 v1.3 for game v1.14+
		Currently ACTIVE

	Int Team-Prostheses-2882002619 v1.4 for game v1.26+
		Currently ACTIVE
		Has been initialised

	ibiglaser-Secret Items Spawn Allower Mod-2880997928 v1.0 for game v1.26+
		Currently inactive

	Dooompy-Cannibal island props mod-2879616947 v1.0 for game v1.23.7+
		Currently ACTIVE

	JulianMagicCraft-JMC's SCP-009 Mod-2879511725 v1.0 for game v1.14+
		Currently ACTIVE

	Void-Void's Modular Weapon Pack (VMWP)-2875194054 v0.5 for game v1.24+
		Currently inactive

	01 STUDIO-Everything Colourable-2874724005 v1.1 for game v1.26+
		Currently inactive

	JulianMagicCraft-JMC's SCP-096-2874450474 v1.0 for game v1.14+
		Currently ACTIVE

	Quickness, Mishanya-Ferris Wheel-2873049225 v1.0 for game v1.26+
		Currently inactive

	ibiglaser-Melon mod-local v1.0 for game v1.26+
		Currently inactive

	oliverino , Bondagad (Vextorlous)-Anti Furry Mod DLC - Anti Furry Fighters-2602845075 v1.0 for game v1.21.2
		Currently inactive

	Dyadyushka Dyadya-Torture Mod-2870378567 v1.0 for game v1.26.6
		Currently ACTIVE
		Has been initialised

	Mr_kWKD-Attachable-2866743610 v1.0 for game v1.26+
		Currently inactive

	Dyadyushka Dyadya-Pose Manager-local v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Edu-Tactical Style Mod.-2865590962 v1.0 for game v1.21.2+
		Currently inactive

	YoprixFine-Chev Floriado-2864908998 v1.0 for game v1.25+
		Currently inactive

	ibiglaser-Make Anything Invisible-2864708184 v1.0 for game v1.25+
		Currently inactive

	samiy_sexualniy_stalker_iz_zoni-EFT weapon pack-2864303408 v1.0 for game v1.20
		Currently inactive

	Dyadyushka Dyadya, ibiglaser improvement-[Improved] Pickup Advanced (Pickup anything)-2863389507 v1.0 for game v1.25+
		Currently ACTIVE

	ibiglaser-Dead creatures = zombies-2863388840 v2.0 for game v1.25+
		Currently inactive

	Timtam-Half Life Universe Pack-local v1.0 for game v1.26+
		Currently inactive

	Eduardoeldo-Extended AK pack-2861393004 v2.4 for game v1.8 +
		Currently inactive

	megaturn-PzKpfw V Panther MOD-2858726915 v1.1 for game v1.25
		Currently inactive

	Dyadyushka Dyadya-Human Dynamic Emotions 2-2856823986 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Morzzic-Deformation Mod-2856121663 v1.0 for game v1.25+
		Currently inactive

	Dyadyushka Dyadya-Pickup Advanced-2854748282 v1.0 for game v1.25+
		Currently inactive

	Timtam-Dragon Custom Entity-local v1.0 for game v1.11+
		Currently inactive

	ibiglaser-Abyss corruption system-2853132719 v2.0 for game v1.25+ and Dyadyushka Dyadya
		Currently inactive

	megaturn-Rifles | WWII-2852283287 v1.4 for game vAny
		Currently inactive

	Laska, Quickness-Quick Turn On Poses-local v1.0 for game v1.24
		Currently inactive

	KIRK-Cinematic mod-2137595375 v1.0 for game v1.7
		Currently ACTIVE

	SamKind-Ultimate Melee Pack Expanded-2844501696 v1.0 for game v1.14+
		Currently inactive

	WooTech-New York Police Department | NYPD-local v1 for game v1.25.0
		Currently inactive

	megaturn-Pistols | WWII-2842111838 v1.6 for game vAny
		Currently inactive

	Smitty the Clown-Buff Human-2841772437 v1.5 for game v1.16.5+
		Currently inactive

	590a1shooter-Walter White Nextbot-local v1.0 for game v1.20+
		Currently inactive

	Purepsi-Saul Goodman Nextbot-local v1.25 for game v1.25+
		Currently inactive

	Mishanya-Functional Helicopter Mod-2839691188 v0.3.1 for game v1.25+
		Currently ACTIVE
		Has been initialised

	Aubarino-Functional Senator Armstrong Mod-local v1.0 for game v1.20+
		Currently inactive

	cryomaniac & Aubarino-Obunga Nextbot-local v66.6 for game v1.20+
		Currently inactive

	Slebbey-Joe Biden Nextbot-local v1.25 for game v1.25+
		Currently inactive

	RadioactiveE3™-PPG: Civilians-2838563034 v1.1 for game v1.23+
		Currently inactive

	Slebbey-Amogus Nextbot-local v1.25 for game v1.25+
		Currently inactive

	hankmart-ROBLOX Mod-2838301763 v2.0 for game v1.26
		Currently ACTIVE

	Aubarino-Troll Nextbot-local v1.0 for game v1.20+
		Currently inactive

	Digito-Operation LSA Forces: Russia REMAKE-2835970309 v1 for game v1.20
		Currently ACTIVE

	elijason-Roblox Character-2835282265 v1.0 for game v1.25
		Currently inactive

	666dtoxzik // defa1t-Underground Complex-2834190786 v1.0 for game v1.24-1.25+
		Currently inactive

	samiy_sexualniy_stalker_iz_zoni-Anzio Ironworks 20MM-2831327818 v1.0 for game v1.20
		Currently inactive

	Dyadyushka Dyadya-Disable QR 01 studio-2830600051 v1.0 for game v1.24+
		Currently ACTIVE

	Eduardoeldo-H.A.W: Vietnam War Mod-2828925727 v2.4 for game v1.8 +
		Currently inactive

	bambat gaming-my first map!-2827954512 v1.0 for game v1.14+
		Currently inactive

	Decibek-Great Gorge-local v1.0 for game v1.14+
		Currently inactive

	BadHmidou-Venerable Weaponry-local vUhhh for game vAny
		Currently inactive

	rAmbo86-GreenScreen map-2817845118 v1.1 for game v1.24+
		Currently inactive

	William_Aton-Some Roblox weapons pack-local v1.0 for game v1.22+
		Currently inactive

	rAmbo86-Spies-2817845118 v1.25 for game v1.25+
		Currently ACTIVE

	PaulRisk-T-90 2.0-2817389224 v2.0 for game v1.24
		Currently inactive

	PaulRisk-M1A2 Abrams 2.0-local v2.0 for game v1.24
		Currently inactive

	PaulRisk-Leopard 2A5 2.0-2451734717 v2.0 for game v1.24
		Currently inactive

	Maxe & Dyadya-Advanced Zombie Injector (v1.2)-2815591838 v1.2 for game v1.24+
		Currently ACTIVE

	PaulRisk-Tiger I 2.0-2814340225 v2.0 for game v1.24
		Currently inactive

	Um, Idk-[Community Update 1] Cars, Cars, And Cars [v1.2]-2813406000 v1.0 for game v1.23.0
		Currently ACTIVE

	DarkGreen-Melon Playground Characters-2751402360 v1.2 for game v1.15
		Currently ACTIVE

	Aubarino-Functional Terminator Mod-2809137426 v1.5 for game v1.20+
		Currently ACTIVE

	Quickness, Mishanya, arkstar_, Dyadyushka Dyadya, Maxe, Laska-More Vehicles-2805966221 v1.5.2 for game v1.24x
		Currently ACTIVE

	DANGER-Vanilla Firearm Expansion-local vF for game v1.21
		Currently ACTIVE

	p0et5&Pizd00za-Hunting equipment mod-2803209354 v0.1 for game v1.23.x
		Currently ACTIVE

	Orsoniks/Navii-Husk Overdose-local v1.0 for game v1.21+
		Currently inactive

	Maxe & Dyadushka-Realistic Axe mod-local v1 for game vAny
		Currently ACTIVE

	citizen-Reloadable Explosive Weapons-2799000030 vfirst version lolololo for game vversion 1.0sus
		Currently inactive

	Bobr-Shopping Cart -SC-2797389191 v1.0 for game v1.11
		Currently ACTIVE

	Mishanya-The Ultimate Car Mod-2795171453 v0.9 for game v1.16+
		Currently ACTIVE

	cloddyclod / aylse-cloddyMod-2794902095 vi never update modversion for game v1.21
		Currently ACTIVE

	Fanboy#1000-Popular SCP's-2793790885 v1.0 for game v1.11
		Currently inactive

	Orsoniks / Navii-Reactive humans-2793371344 v1.0 for game v1.23+
		Currently ACTIVE

	DANGER-Cormandy Republic Mod-2792165316 vX for game vyou.
		Currently ACTIVE

	Ahlad (vanilla flavor)-V+ Field Gun-2787047229 v0.69 for game vVanilla+ enjoyers
		Currently ACTIVE

	citizen-Shipping Container-local v1.0 for game v1.8
		Currently inactive

	Dyadyushka Dyadya-Wind Generator-2785388021 v1.0 for game v1.22.3+
		Currently inactive

	Eduardoeldo-The Nearby Conflicts Base: US Army-local v1 for game v1.21.2
		Currently inactive

	Eduardoeldo-The Nearby Conflicts Base: British Army-2784074151 v1 for game v1.21.2
		Currently ACTIVE

	Eduardoeldo-The Nearby Conflicts Base: USMC-2783124887 v1 for game v1.21.2
		Currently inactive

	R0Y1T0-R0Y1T0 Vehicle Pack 1-2774090496 v2.5 for game v1.22+
		Currently ACTIVE

	Quickness-Farmbot-local v1.0 for game v1.22
		Currently inactive

	Eduardoeldo-Law Enforcement Base: Less Lethal DLC-local v1.2 for game v1.11+
		Currently ACTIVE

	Skittles-Guns 'N Ammo-2761082698 v1.0 for game vwhatever is the latest
		Currently ACTIVE

	Orsoniks / Navii-SimplePortals-2759460093 v1.0 for game v1.22+
		Currently inactive

	Eduardoeldo-Law Enforcement Base: USA-2754575076 v1 for game v1.21.2
		Currently ACTIVE

	DANGER-Delta Octon Mod-2747083163 vUknown for game v1.21
		Currently inactive

	Dyadyushka Dyadya-Inverse Teleportation-local v1.0 for game v1.11
		Currently inactive

	Dyadyushka Dyadya-Uncharted Territory Portal-2737814654 v1.1 for game v1.11
		Currently ACTIVE

	citizen-Modern Firearms-2721105504 v1.0 for game v1.20
		Currently inactive

	megaturn-Wild Medieval-2708133294 v1.2 for game vAny
		Currently inactive

	kubason-Military+ Expansion-local v1.0 for game v1.21.3
		Currently inactive

	Mishanya-Prop Mod-2696169016 v1.3 for game v1.22+
		Currently ACTIVE

	citizen-Russian Firearms-2688921316 v1.0 for game v1.20+
		Currently inactive

	Ghost Turtle-Tornado Mod V1.0-2666039457 v1.0 for game v1.22.2
		Currently ACTIVE

	miko.340-master chief-local v1.0 for game v1.14
		Currently ACTIVE

	citizen-Soviet Firearms-2650033205 v1.0 for game v1.20+
		Currently inactive

	TastyPancake-ROBLOX Bloxy Cola-local v1.0 for game v1.22
		Currently ACTIVE

	RadioactiveE3™-SCP: PPG Edition-2643873749 v4.5 for game v1.22+
		Currently inactive

	Quickness-More Coloring Vases-local v1.0 for game v1.22
		Currently inactive

	PeppRRicoochie-The Grappling Gun Mod-2637017257 v3.5 for game v1.25
		Currently inactive

	[ Fasol_G#DangerZone ]-[ SCP-610 Mod ]-2626113140 v1.0 for game v1.14+
		Currently ACTIVE

	CliffyRocket038-Squid Game Mod-2615439393 v1.0 for game vcurrent versions.
		Currently inactive

	Nightzz-Item Plus-2612273009 v6.0 for game v1.21.x
		Currently inactive

	Mishanya-Functional Devices Mod-2605252227 v1.1 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	Mini-Mini's Roleplay Mod-2587903303 v1.0 for game v1.18
		Currently ACTIVE

	wahladhog-The Warthog Collection-2577882501 v1.0 for game v1.21+
		Currently inactive

	Bonible-FIREARMADA - G/G/G/P/M-2575642003 v1.3 for game v1.25+
		Currently ACTIVE

	Fleasy-FleasyWeapons - Rifles-2571665852 v1.3 for game v1.20+
		Currently ACTIVE

	Kyrelink-Hats Mod-local v2.5 for game v1.7
		Currently ACTIVE

	cttc321-SUPER DROIDS MOD-2566959611 vv1.0 for game v1.13+
		Currently ACTIVE

	zooi-Dead No Collide-local v1.0 for game v1.20
		Currently ACTIVE

	Fresh Ace-People Playground Roblox Mod-2557348261 v1.0 for game v1.16+
		Currently ACTIVE

	jimmyl-Liquid-related Machinery-2550340103 v0.6 for game v1.19+
		Currently inactive

	um, idk-Saab 900 Cabrio + Audi Quattro Mod-local v1.1 for game v1.16+
		Currently inactive

	Fleasy-FleasyWeapons - Small Guns-2546528392 v1.2 for game v1.19+
		Currently ACTIVE

	FredMichalBear-Flatout + Wreckfest mod-2535736318 v1.0 for game v1.15
		Currently ACTIVE

	MaTT-MaTT's Car Collection-2523816328 v1.0 for game v1.19+
		Currently inactive

	vaporwave124-purge siren and more credit mr .rex-local v0.5 for game v1.14+
		Currently ACTIVE

	ValZ-Henry Stickmin Collection MOD-local v1.3.0 for game v1.19
		Currently inactive

	jimmyl and Bonible-Guns,guns,guns!-2522015543 v1 for game v1.18+
		Currently inactive

	Mishanya-The Ultimate Human Mod-2516637907 v1.1 for game v1.21+
		Currently ACTIVE

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently ACTIVE

	MR.REX-Emergency Siren-2509362434 v0.6 for game v1.21+
		Currently ACTIVE

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently ACTIVE

	Mr_kWKD-The Musket Mod-2502525912 v1.3 for game v1.18+
		Currently ACTIVE

	Frosty-Configurable Explosive-local v1.1 for game v1.15
		Currently inactive

	Pumpkin-Quality of Life Items-2500516293 v1.8 for game v1.26
		Currently ACTIVE

	YearsLater-The Dooompy Mod-local v1 for game v1.11+
		Currently ACTIVE

	Lord Mumu-Imperial NPC Pack 0.2-2476100687 v1.0 for game v1.16
		Currently ACTIVE

	Mumu-Imperial Trench 1 [MAP]-2473575934 v1.0 for game v1.14+
		Currently inactive
		Malfunctioning

	Mumu-Imperial Naval Base [Map]-local v1.0 for game v1.14+
		Currently inactive
		Malfunctioning

	Talonphobia-Buff Human-2461523630 v1.0.2 for game v1.16.5
		Currently inactive

	Aspa102-Wheelchair-2455335631 v1.0 for game v1.16+
		Currently inactive

	Mishanya-Colored Cars Mod-2444870694 v1.1 for game v1.16+
		Currently inactive

	Kyrelink, Quickness-The ULTIMATE Minecraft Mod-2442812460 v1.9 for game v1.23+
		Currently ACTIVE

	LordMumu-Imperial Weapons-2441871246 v0.1 for game v1.14
		Currently ACTIVE

	Mumu L-Baton Empire Stuff-2441636525 v1.0 for game v1.14
		Currently ACTIVE

	Mishanya-Police+-2416686384 v6.4 BETA for game v1.21.3+
		Currently ACTIVE

	Quickness, The Crusader and Duolanchik-VanillaWeapons+ 2-2409064173 v1.0 for game v1.15x
		Currently inactive

	Mr_kWKD-Military+-2390021263 v1.0 for game v1.11
		Currently ACTIVE

	Mishany-Melee Weapons Mod-2389733225 v7.0 for game v1.13+
		Currently inactive

	Soiled Panties-CRT Televisions!-2379156287 v1.31 for game v1.18
		Currently ACTIVE

	Morzzic-Taser-2361892819 v1.2 for game v1.11+
		Currently ACTIVE

	Avien Jones-Front Facing Human-local v1.0 for game v1.7
		Currently ACTIVE

	jimmyl-ExplosiveMod-2337158074 v1 for game v1.10+
		Currently ACTIVE

	CookieKwisp-Fortnite Assault Rifles-local v1.0 for game v1.13.1
		Currently inactive

	CookieKwisp-Fortnite Handguns-2328588618 v1.0 for game v1.13.1
		Currently inactive

	kim mo cee-Trains and Freights MOD-2325628005 v0.2 for game vv1.26.5
		Currently inactive

	Alibarda-Human Tiers-2308911224 v5.9 for game v1.18+
		Currently ACTIVE
		Has been initialised

	aaaaaaaaaaaaaaaa-DeathCounter-local v1.0 for game v1.11.1
		Currently inactive

	Golden, Talon Zane-Among Us Mod-2232883786 v1.0 for game v1.9+
		Currently ACTIVE

	weirdo-Chemical Warfare-2226697361 v2.0 for game v1.22.2+
		Currently ACTIVE

	weirdo-Functioning Armor-2194511729 v3.0 for game v1.22.2+
		Currently ACTIVE

	little andy-Andy's 50.cal M2 Browning-2175370982 v1.0 for game v1.9+
		Currently ACTIVE

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently ACTIVE

### Game version

1.27 preview 1 (beta) 

### Operating System

Windows 10

### Additional notes

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/125271643/1eccfce4-8843-483c-a872-7a7073f65730)

**Comment by mestiez** [comment]
iirc some mod called cloddy causes this. no idea why but i hope preview 2 fixes it
