### ISSUE TITLE
ex. an X that does Y

### ISSUE THREAD

**Issue by isiszxcvbnm** [studio-minus/ppg-bugs-and-requests#3048]
### Feature description

His lever is still there   This working principle is incorrect   His pull ring and lever should come off at the same time
![IMG_20230812_231939](https://github.com/studio-minus/ppg-bugs-and-requests/assets/142107267/743f30d9-f7cc-4e9a-b67a-292b9f3ef533)
![Cache_-2390f8c3eca643e6](https://github.com/studio-minus/ppg-bugs-and-requests/assets/142107267/effa3d40-bb2f-430e-bc42-174b7cec7b38)

### Feature purpose

The working principle of hand grenades in reality is not that. For the sake of reality, please modify this issue

**Comment by mestiez** [comment]
what the hell is this submission

**Comment by 2xddev** [comment]
> what the hell is this submission

What he meant is that the lever of the grenade should hinge upwards when the grenade is activated, since that happens in real life too. I think english isn't his first language, but hopefully you get the point now
