### ISSUE TITLE
Reactor A5 has a large open cavity at the top of the map

### ISSUE THREAD

**Issue by inferknob** [studio-minus/ppg-bugs-and-requests#3050]
### Describe the bug

Title explains it. When I spawn a nuclear bomb the light and sprite go through the top of the map to reveal an open cavity.

### Clearly describe how to reproduce the bug

Go to reactor A5
Spawn nuclear bomb near the reactor itself, not too far away from the top.
Detonate nuclear bomb
Scroll far out

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12327901/exported.game.debug.info.md)

**Comment by mestiez** [comment]
i know
