### ISSUE TITLE
A Custom map creator for the 1.27 update

### ISSUE THREAD

**Issue by RandomGenerator-13** [studio-minus/ppg-bugs-and-requests#3051]
### Feature description

The feature being described here is related to a new map editor for the 1.27 update for People Playground. This new feature will allow players to create their own custom maps and levels for the game, utilizing the game's physics engine and other mechanics to create their own unique gameplay experiences. Players will be able to place objects, terrain, vehicles, and other elements on their maps to create unique levels that can be shared with the community. This feature will offer players a lot of freedom to create their own custom levels and share them with others, adding more replayability and variety to the game.

### Feature purpose

The purpose of the map editor feature being requested is to provide players of People Playground with a way to create their own custom maps and levels for the game, utilizing the physics engine and other mechanics to create unique gameplay experiences. The feature is likely to add a significant amount of replayability and variety to the game, as players will be able to share their custom levels with the community and play on levels created by others. This will allow for a more interactive and community-driven experience for players, potentially leading to more engagement and enjoyment of the game over time.

**Comment by inferknob** [comment]
Dude, this is literally already being made. Read. The. Blog.

**Comment by RandomGenerator-13** [comment]
where bruh
