### ISSUE TITLE
Activation signal of an activation toggle cuts out when attached to a Tesla gun.

### ISSUE THREAD

**Issue by sneet3** [studio-minus/ppg-bugs-and-requests#3052]
### Describe the bug

I have a build that relies on activation toggles and tesla guns. When the activation toggle, toggles activation for the Tesla gun for a period of time, or when the game is paused, the toggle resets and the Tesla gun loses it's charge and is forced to start over again.

I had a makeshift nuclear reactor built using this feature, it's no longer working now

### Clearly describe how to reproduce the bug

Attach an activation toggle to a tesla gun, and activate it. Wait a little, then the activation signal will cut out. 

### Mod list

Watertight box (active)
Husk overdose (disabled)
A crap ton of damage (disabled)
chemical warfare (disabled)
active humans (disabled)

### Game version

1.27

### Operating System

Windows 10

**Comment by mestiez** [comment]
related to the many activation bugs
