### ISSUE TITLE
Make it so the extra shot impact particles work with the custom blood colour code

### ISSUE THREAD

**Issue by ThatScottishGuy** [studio-minus/ppg-bugs-and-requests#3055]
### Feature description

Make it so the extra shot impact particles work with the custom blood colour code or make the particles that appear when a limb is crushed the same as the extra shot impact particles.

### Feature purpose

Just a quality of life addition

**Comment by mestiez** [comment]
what is "the custom blood colour code"

**Comment by ThatScottishGuy** [comment]
apologies for the late response, its this. (code below)


   var cal = ScriptableObject.CreateInstance<DecalDescriptor>();
                       var cal2 = ScriptableObject.CreateInstance<
DecalDescriptor>();

                                  foreach (LimbBehaviour limb in person.
Limbs)
                       {
                           foreach (var body in person.Limbs)
                           {

                           }


                           cal.Sprites = limb.BloodDecal.Sprites;
                           cal.IgnoreRadius = limb.BloodDecal.IgnoreRadius;
                           cal.Color = new Color32(0, 255, 4, 255);
                           limb.BloodDecal = cal; //Lazy
                            limb.BloodLiquidType = "Lime";//<-- You should
change the name of liquid here
                           limb.CirculationBehaviour.Drain(limb.
CirculationBehaviour.Limits.y);
                           limb.CirculationBehaviour.AddLiquid(Liquid.
GetLiquid("Lime"), limb.CirculationBehaviour.Limits.y);//<-- You should
change the name of liquid here
                           limb.PhysicalBehaviour.Properties = prop;
                       }
                       var Safe = new GameObject();
                       person.BleedingParticlePrefab = UnityEngine.Object.
Instantiate<GameObject>(person.BleedingParticlePrefab, Safe.transform);
                       person.BloodExplosionPrefab = UnityEngine.Object.
Instantiate<GameObject>(person.BloodExplosionPrefab, Safe.transform);
                       prop.ShotImpact = UnityEngine.Object.Instantiate<
GameObject>(prop.ShotImpact, Safe.transform);
                       Safe.SetActive(false);
                       cal2.Sprites = person.BleedingParticlePrefab.
GetComponentInChildren<BleedingParticleBehaviour>().BloodSplatController.
Decal.Sprites;
                       cal2.IgnoreRadius = person.BleedingParticlePrefab.
GetComponentInChildren<BleedingParticleBehaviour>().BloodSplatController.
Decal.IgnoreRadius;
                       cal2.Color = new Color32(0, 255, 4, 255);
                       person.BleedingParticlePrefab.GetComponentInChildren<
BleedingParticleBehaviour>().BloodSplatController.Decal = cal2; //again

                        foreach (var thi in person.BleedingParticlePrefab.
GetComponentsInChildren<ParticleSystem>())
                       {
                           var main = person.BleedingParticlePrefab.
GetComponentInChildren<ParticleSystem>().main;
                           main.startColor = new ParticleSystem.
MinMaxGradient(new Color32(0, 255, 4, 255));
                           if (thi.gameObject.GetComponentInChildren<
FancyBloodSplatController>())
                           {
                               thi.gameObject.GetComponentInChildren<
FancyBloodSplatController>().Decal = cal2;
                           }
                           var renderer = thi.gameObject.GetComponent<
ParticleSystemRenderer>();
                           renderer.material.color = new Color32(0, 255, 4,
255);
                       }

                       foreach (var thi in person.BloodExplosionPrefab.
GetComponentsInChildren<ParticleSystem>())
                       {
                           var moon = thi.main;
                           moon.startColor = new ParticleSystem.
MinMaxGradient(new Color32(0, 255, 4, 255));
                       }

                       foreach (var con in person.BloodExplosionPrefab.
GetComponentsInChildren<FancyBloodSplatController>())
                       {
                           con.Decal = cal2;
                       }

                       foreach (var thi in prop.ShotImpact.
GetComponentsInChildren<ParticleSystem>())
                       {
                           var moon = thi.main;
                           moon.startColor = new ParticleSystem.
MinMaxGradient(new Color32(0, 255, 4, 255));
                           if (prop.ShotImpact.GetComponentInChildren<
FancyBloodSplatController>())
                           {
                               prop.ShotImpact.GetComponentInChildren<
FancyBloodSplatController>().Decal = cal2;
                           }
                       }
}

    public class Lime : Liquid
{
    public Lime()
    {
        this.Color = new Color32(0, 255, 4, 255);
    }

    public override void OnEnterContainer(BloodContainer container)
    {
    }

    public override void OnEnterLimb(LimbBehaviour limb)
    {

    }

    public override void OnExitContainer(BloodContainer container)
    {
    }

  public const string ID = "Lime";//<-- You should change the name of
liquid here}

}
    }

**Comment by DindinYT37** [comment]
```cs
var cal = ScriptableObject.CreateInstance < DecalDescriptor > ();
var cal2 = ScriptableObject.CreateInstance < DecalDescriptor > ();

foreach(LimbBehaviour limb in person.Limbs) {
    foreach(var body in person.Limbs) {

    }

    cal.Sprites = limb.BloodDecal.Sprites;
    cal.IgnoreRadius = limb.BloodDecal.IgnoreRadius;
    cal.Color = new Color32(0, 255, 4, 255);
    limb.BloodDecal = cal; //Lazy
    limb.BloodLiquidType = "Lime"; //<-- You should
    change the name of liquid here
    limb.CirculationBehaviour.Drain(limb.CirculationBehaviour.Limits.y);
    limb.CirculationBehaviour.AddLiquid(Liquid.GetLiquid("Lime"), limb.CirculationBehaviour.Limits.y); //<-- You should
    change the name of liquid here
    limb.PhysicalBehaviour.Properties = prop;
}
var Safe = new GameObject();
person.BleedingParticlePrefab = UnityEngine.Object.
Instantiate < GameObject > (person.BleedingParticlePrefab, Safe.transform);
person.BloodExplosionPrefab = UnityEngine.Object.
Instantiate < GameObject > (person.BloodExplosionPrefab, Safe.transform);
prop.ShotImpact = UnityEngine.Object.Instantiate <
    GameObject > (prop.ShotImpact, Safe.transform);
Safe.SetActive(false);
cal2.Sprites = person.BleedingParticlePrefab.
GetComponentInChildren < BleedingParticleBehaviour > ().BloodSplatController.
Decal.Sprites;
cal2.IgnoreRadius = person.BleedingParticlePrefab.
GetComponentInChildren < BleedingParticleBehaviour > ().BloodSplatController.
Decal.IgnoreRadius;
cal2.Color = new Color32(0, 255, 4, 255);
person.BleedingParticlePrefab.GetComponentInChildren <
    BleedingParticleBehaviour > ().BloodSplatController.Decal = cal2; //again

foreach(var thi in person.BleedingParticlePrefab.
    GetComponentsInChildren < ParticleSystem > ()) {
    var main = person.BleedingParticlePrefab.
    GetComponentInChildren < ParticleSystem > ().main;
    main.startColor = new ParticleSystem.
    MinMaxGradient(new Color32(0, 255, 4, 255));
    if (thi.gameObject.GetComponentInChildren <
        FancyBloodSplatController > ()) {
        thi.gameObject.GetComponentInChildren <
            FancyBloodSplatController > ().Decal = cal2;
    }
    var renderer = thi.gameObject.GetComponent <
        ParticleSystemRenderer > ();
    renderer.material.color = new Color32(0, 255, 4,
        255);
}

foreach(var thi in person.BloodExplosionPrefab.
    GetComponentsInChildren < ParticleSystem > ()) {
    var moon = thi.main;
    moon.startColor = new ParticleSystem.
    MinMaxGradient(new Color32(0, 255, 4, 255));
}

foreach(var con in person.BloodExplosionPrefab.
    GetComponentsInChildren < FancyBloodSplatController > ()) {
    con.Decal = cal2;
}

foreach(var thi in prop.ShotImpact.
    GetComponentsInChildren < ParticleSystem > ()) {
    var moon = thi.main;
    moon.startColor = new ParticleSystem.
    MinMaxGradient(new Color32(0, 255, 4, 255));
    if (prop.ShotImpact.GetComponentInChildren <
        FancyBloodSplatController > ()) {
        prop.ShotImpact.GetComponentInChildren <
            FancyBloodSplatController > ().Decal = cal2;
    }
}
}

public class Lime: Liquid {
    public Lime() {
        this.Color = new Color32(0, 255, 4, 255);
    }

    public override void OnEnterContainer(BloodContainer container) {}

    public override void OnEnterLimb(LimbBehaviour limb) {

    }

    public override void OnExitContainer(BloodContainer container) {}

    public
    const string ID = "Lime"; //<-- You should change the name of
    liquid here
}

}
}
```
