### ISSUE TITLE
Camera doesn't work.

### ISSUE THREAD

**Issue by Glitchkio** [studio-minus/ppg-bugs-and-requests#3056]
### Describe the bug

The camera wont move a bit even if I follow a object it doesn't move and there isn't a zoom in or zoom out. This is for all maps. :( 

### Clearly describe how to reproduce the bug

I have no idea it just wont move.

### Mod list

I disabled all my mods for the new update.

### Game version

Preview 1.27

### Operating System

Asus tuf A15

**Comment by mestiez** [comment]
uninstall cloddymod or something
