### ISSUE TITLE
decoupler breaks every paste/contraption spawn

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#3062]
### Describe the bug

title
before
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/101178735/9739d53d-c83f-4d5c-9d4a-029a22788d26)
after
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/101178735/f16b8170-b4a8-4818-bcbf-464b03dd57ca)

### Clearly describe how to reproduce the bug

make a cool and simple contraption using decoupler then copy and paste it

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12328515/exported.game.debug.info.md)

**Comment by mestiez** [comment]
fixed :)
