### ISSUE TITLE
weird camera glitch in preview thing

### ISSUE THREAD

**Issue by Squibard** [studio-minus/ppg-bugs-and-requests#3063]
### Describe the bug

i cant move my camera and it says im following something and i cant unfollow it

### Clearly describe how to reproduce the bug

load a map in preview thing

### Game debug info

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.22621) 64bit

 - **CPU**: AMD Ryzen 5 5600X 6-Core Processor 

 - **GPU**: NVIDIA GeForce RTX 3050

 - **Memory**: 16 GB

## All loaded mods

	01 STUDIO-Soft zooi-3011374767 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Orsoniks / Navii-Status Icons-2644689646 v0.1 for game v1.22
		Currently inactive

	Wtrmlon-Jelly Dummy-3008653058 v1.0 for game v1.12.6
		Currently ACTIVE

	GHOST MODS-SMOKE GRENADE MOD-local v1.0 for game v1.26
		Currently inactive

	Vable Studio-Better car-3000581086 v1.0 for game v1.26+
		Currently ACTIVE

	Xenon-Advanced Chemistry Mod-3000021644 v1.0 for game v1.26.6
		Currently ACTIVE
		Has been initialised

	GHOST MODS-M1A2 Abrams MOD REMAKE-local v1.0 for game v1.26
		Currently ACTIVE

	FEX-Weapon SFX Realism Mod-local v1.0 for game v1.26+
		Currently ACTIVE

	Kasztanbest, Timtam-Holsters Mod-2994553868 v1.0 for game v
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Watertight Box-2989799391 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Just Collars-2985454065 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Danger-Stockalike AK Variants-local vNocom for game vversions above 1.16, excluding beta releases.
		Currently ACTIVE

	Int team-More Nature-2981286071 v1.2 for game v1.26+
		Currently ACTIVE

	Double You Workshop-Decoration Paradise-2804980196 v1.0 for game v1.14+
		Currently ACTIVE

	Timtam-Rewind Time-2976806643 v1.0 for game vALL VERSIONS
		Currently inactive

	ibiglaser-Everything Attachable-2974958963 v1.0 for game vMORE Attachments
		Currently ACTIVE

	Dyadyushka Dyadya-Colourable Wires-2971831945 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Regrowth Mod-2966853166 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	NeitherFishNorCat-Syringe Gun-2966658771 v1.0 for game v1.21+
		Currently ACTIVE

	Int Team-More Vehicles 2-2963069537 v1.0 for game v1.26
		Currently ACTIVE
		Has been initialised

	Int Team-Sorted items in categories-2962119927 v1.1 for game v1.26.6+
		Currently ACTIVE

	megaturn-Modern Firearms 2 [1.2]-2960174793 v1.2 for game vAny
		Currently inactive

	Qvill & Papaya-SMERCH MLRS MOD-2959032592 v0.9 for game v1.26
		Currently ACTIVE
		Has been initialised

	Timtam-Horrible Diseases Mod-local v1.0 for game v1.26+
		Currently inactive

	Int Team-MPW library-2953788932 v1.1.8 for game v1.26+
		Currently ACTIVE
		Has been initialised

	ibiglaser / 01 STUDIO-Contraptions Corruption Remover-2947471983 v1.0 for game vAll ppg players
		Currently ACTIVE
		Has been initialised

	01 STUDIO & INT TEAM-Underwater Things-2946415658 v1.0 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	01 STUDIO-Combat Mod-2943789568 v1.0 for game v1.27+
		Currently ACTIVE
		Malfunctioning

	Mishanya-CCTV Camera Mod-2941446451 v1.0.1 for game v1.26.6+
		Currently ACTIVE
		Has been initialised

	QVILL and Papaya-BM-21 GRAD MLRS MOD-2940397068 v1.0 for game v1.26+
		Currently inactive

	QVILL and Papaya-Himars M142 MOD-2929893610 v1.0 for game v1.26+
		Currently ACTIVE

	KillanGenifer & Gans-Attachments+-local v0.1 for game v1.26+
		Currently ACTIVE

	Bobr-Ultimate Double Barrel Shotgun Mod-local v1.0 for game v1.21+
		Currently ACTIVE

	Dyadyushka Dyadya & Dyadyushka Danya-Garbage Mod-2919683137 v1.1 for game v1.26+
		Currently inactive

	Dyadyushka Dyadya-Colourable Map Background-2915554666 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	zooi-depletable engines-2463360042 v1.2 for game v1.16.5
		Currently ACTIVE

	NeitherFishNorCat-Automatic limb repositioning-2913582654 v1.1 for game v1.21+
		Currently ACTIVE

	CheeseYums1/ibiglaser-Mouse Eating Chocolate-2892071899 v1.0 for game v(any version would probably work)
		Currently inactive

	Um, Idk-[Community Update 1] Cars, Cars, And Cars [v1.2]-2813406000 v1.0 for game v1.23.0
		Currently ACTIVE

	Please Halp-Gun Smoke Trails-2908115498 vpenis for game v1.26
		Currently ACTIVE

	Mrhypes-Breaking bad background intro-2900869544 v1.0 for game vShrek
		Currently inactive

	Dyadyushka Dyadya-Grip Fix-local v1.0 for game v1.26+
		Currently inactive

	Timtam-Foods+ Mod-2896506613 v1.0 for game v1.26+
		Currently ACTIVE

	Chomuske, Muurkz-Self-Defence guns mod-2895287892 v1 for game v1.24
		Currently inactive

	ibiglaser-Weapon size affects its power Mod-2894415938 v1.0 for game v1.26+
		Currently ACTIVE

	ibiglaser-3D Saul Goodman Main Menu Replacer-2892071899 v1.0 for game vBIG fans of breaking bad
		Currently inactive

	Dyadyushka Dyadya-Ultimate Map Blocks-2891519401 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Int Team-Prostheses-2882002619 v1.4 for game v1.26+
		Currently ACTIVE
		Malfunctioning

	ibiglaser-Secret Items Spawn Allower Mod-2880997928 v1.0 for game v1.26+
		Currently ACTIVE

	JulianMagicCraft-JMC's SCP-009 Mod-2879511725 v1.0 for game v1.14+
		Currently inactive

	JulianMagicCraft-JMC's SCP-096-2874450474 v1.0 for game v1.14+
		Currently inactive

	Dyadyushka Dyadya-Liquid Logic-local v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	JulianMagicCraft-JMC's SCP-049-2871703058 v1.0 for game v1.14+
		Currently inactive

	Dyadyushka Dyadya-Torture Mod-2870378567 v1.0 for game v1.27+
		Currently ACTIVE
		Malfunctioning

	JulianMagicCraft-JMC's SCP-173 Mod-2870118211 v1.3 for game v1.14+
		Currently inactive

	Kyrelink-Playable Xylophone Mod-2868316027 v1.0 for game v1.15+
		Currently ACTIVE

	Dyadyushka Dyadya-Pose Manager-local v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Goosey-Gooseys' Garage PREVIEW-local v1.1 for game v1.22
		Currently ACTIVE

	Dyadyushka Dyadya, ibiglaser improvement-[Improved] Pickup Advanced (Pickup anything)-2863389507 v1.0 for game v1.25+
		Currently ACTIVE

	игор-Bomb Tech-2863195081 v1.0 for game v1.14+
		Currently ACTIVE

	Pumpkin-Doors Mod-2400494139 v1.4 for game v1.15
		Currently ACTIVE

	DreamingWarlord-PBullets-2858824981 v1.0 for game v1.25.4
		Currently ACTIVE

	Dyadyushka Dyadya-Human Dynamic Emotions 2-2856823986 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Pickup Advanced-2854748282 v1.0 for game v1.25+
		Currently ACTIVE

	ibiglaser-Abyss corruption system-2853132719 v2.0 for game v1.25+ and Dyadyushka Dyadya
		Currently inactive

	JUMBLR-The Bank Robbers Mod-local v1 for game v1.20
		Currently inactive

	dbgvhtcfrxd-Breaking Bad Characters Mod-local v1.0 for game v1.22+
		Currently inactive

	Dyadyushka Dyadya-Raised severed limbs-local v1.0 for game v1.24+
		Currently ACTIVE

	Brian9171 & chonk-PPG Additions-2844222823 v0.3 for game v1.25+
		Currently ACTIVE

	Therac-25-Custom TV-2843819067 v2.0 for game v1.21+
		Currently ACTIVE

	Dyadyushka Dyadya-All Liquids Generator-2840387929 v1.0 for game v1.24+
		Currently ACTIVE

	Dyadyushka Dyadya-Fire remover button-2840340693 v1.0 for game v1.24+
		Currently ACTIVE

	Mishanya-Functional Helicopter Mod-2839691188 v0.3.1 for game v1.25+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Dead creatures remover button-2838002082 v1.0 for game v1.24+
		Currently ACTIVE

	Kasztanbest,Addik-Best Breaking Bad Mod-2834406953 v1.0 for game v1.14+
		Currently inactive

	Prussian Doge-Furries-2834007979 v1.1 for game v1.24+
		Currently ACTIVE
		Malfunctioning

	Dyadyushka Dyadya-Colorful Energy Sword-local v1.0 for game v1.24+
		Currently ACTIVE

	Dyadyushka Dyadya-Colorful Blaster-local v1.0 for game v1.24+
		Currently ACTIVE

	Dyadyushka Dyadya-Disable QR 01 studio-2830600051 v1.0 for game v1.24+
		Currently ACTIVE

	Engven-No spark-2497957604 v1.0 for game v1.11
		Currently ACTIVE

	Brian9171-Limb Attachments-2660556899 v0.3 for game v1.22+
		Currently ACTIVE

	Dyadyushka Dyadya-Arrows and crystals are now debris-local v1.0 for game v1.24+
		Currently ACTIVE

	Palto_PPG-Money Mod-2820106194 v1.1 for game v1.11
		Currently ACTIVE

	catt0215-Catt's Cannons-2814325736 v6.3 for game v1.25+
		Currently ACTIVE

	Byter28-Gas Burner-2811763416 v1.0 for game vany
		Currently ACTIVE

	lisov-LISOV's Miscellaneous items-2810850541 v1.0 for game v1.14+
		Currently ACTIVE

	Aubarino-Functional Terminator Mod-2809137426 v1.5 for game v1.20+
		Currently inactive

	Orsoniks/Navii-Anti-Gravity Device-local v1.0 for game v1.23+
		Currently ACTIVE

	Quickness, Mishanya, arkstar_, Dyadyushka Dyadya, Maxe, Laska-More Vehicles-2805966221 v1.5.2 for game v1.24x
		Currently ACTIVE

	Sohvaperuna-Limb Reattachment Tools [EOL]-2801931724 v3.3.1 for game v1.24+
		Currently ACTIVE

	Morzzic-Taser-2361892819 v1.1 for game v1.11+
		Currently ACTIVE

	Maxe & Dyadushka-Realistic Axe mod-local v1 for game vAny
		Currently ACTIVE

	Snooza & Bonible-Magdump Mayhem - Guns 'N Armor-2799945427 vover 9000 for game vOVER 9000
		Currently ACTIVE

	loffies-The Criminal Underworld-local v1.0 for game v1.22+
		Currently inactive

	Evalarian-Lawless 2-local v1.0 for game v1.23
		Currently ACTIVE
		Has been initialised

	Azule-Aerodynamics-2798194010 v1 for game v1.23.x+
		Currently ACTIVE

	Slebbey-Uncharted Territory Siren Mod-local v1.23.10 for game v1.23.+
		Currently ACTIVE

	Slebbey-Invalid Siren Mod-2797192028 v1.23.10 for game v1.23.+
		Currently ACTIVE

	Mishanya-The Ultimate Car Mod-2795171453 v0.9 for game v1.16+
		Currently ACTIVE

	pjstarr12-SCP-244 Mod-2794909117 v1.0 for game v1.12+
		Currently inactive

	cloddyclod / aylse-cloddyMod-2794902095 vi never update modversion for game v1.21
		Currently ACTIVE

	Dyadyushka Dyadya-Realistic Atom Bomb-2792881991 v1.0 for game v1.23+
		Currently ACTIVE

	pjstarr12-Bullet Detector Mod-local v1.02 for game v1.0+ i think
		Currently ACTIVE

	Pumpkin-The Bits Mod-local v1.6.2 for game v1.13+
		Currently ACTIVE

	hankmart-Identical Humans-2788201842 v3.0 for game v1.26+
		Currently ACTIVE

	kubason-Oil Mod-local v1.21.2 for game v1.21.2
		Currently ACTIVE

	theimposterjake-More blood colors-2787260581 v1.0 for game v1.23
		Currently inactive

	Ahlad (vanilla flavor)-V+ Field Gun-2787047229 v0.69 for game vVanilla+ enjoyers
		Currently inactive

	pjstarr12-Lean Liquid Mod-2785798205 v1.02 for game vwhatever version idfk
		Currently ACTIVE

	kubason-Duracell Battery-local v1.21.2 for game v1.21.2
		Currently inactive

	zooi-Darker blood-local v1.0 for game v1.22
		Currently ACTIVE

	2Epic4You-snapping heck-local v1.0 for game v1.21
		Currently ACTIVE
		Has been initialised

	kirillX-Prosthetics mod v2-local v2.0 for game v1.23.3
		Currently ACTIVE

	Senpai-i-i...-Traumatic Gun-2730106495 v1.0 for game vAny
		Currently ACTIVE

	3    -SCP-049-local v1.0 for game v1.15
		Currently inactive

	Blakary and Mr_kWKD-Super Slow Motion Updated-2719636807 v1.0 for game v1.22+
		Currently ACTIVE
		Has been initialised

	pjstarr12-Feet Arent Indestructible-local v1.02 for game v1.0+ i think
		Currently ACTIVE

	-Home alone-local v1.0 for game v1.15
		Currently inactive

	Mishanya-Prop Mod-2696169016 v1.3 for game v1.22+
		Currently ACTIVE

	no-Instant Debris-local v1.0 for game vpeople who want pixels that turn into debris
		Currently ACTIVE

	Matyfou-Firecrackers-2666846595 v1.1 for game v1.12.2+
		Currently ACTIVE

	the mad man-movies mod only use for ppg movies-local v1.0 for game v1.15
		Currently inactive

	James Charles-A Syringe Mod-2655173462 v2.7 for game v1.22.3
		Currently ACTIVE

	pjstarr12-Customizable Gun Mod-local v1.0 for game v1.21+
		Currently inactive

	Nightzz-Item Plus-2612273009 v6.0 for game v1.21.x
		Currently ACTIVE

	Mishanya-Functional Devices Mod-2605252227 v1.1 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	WixeZ-Powerful and Weak Weapons-2595930856 v1.1 for game v1.20+
		Currently ACTIVE

	Morzzic-Object Editor-2590195142 v1.3.1 for game v1.23+
		Currently ACTIVE

	Fleasy-FleasyWeapons - Rifles-2571665852 v1.3 for game v1.20+
		Currently ACTIVE

	itic-Auto-9-2569581765 v1.0 for game v1.20
		Currently ACTIVE

	fieryhenry-Modifiable Weight-local v1.0 for game v1.20+
		Currently ACTIVE

	jimmyl-Liquid-related Machinery-2550340103 v0.6 for game v1.19+
		Currently ACTIVE

	Fleasy-FleasyWeapons - Small Guns-2546528392 v1.2 for game v1.19+
		Currently ACTIVE

	jimmyl and Bonible-Guns,guns,guns!-2522015543 v1 for game v1.18+
		Currently ACTIVE

	sneby-Thermal Devices-2518984513 v1.1 for game v1.19+
		Currently ACTIVE

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently ACTIVE

	MR.REX-Emergency Siren-2509362434 v0.6 for game v1.21+
		Currently ACTIVE

	Quickness, Mishanya-Titanic Mod-local v1.0 for game v1.18x
		Currently inactive

	zooi-Signals and Logic Gates-2504621801 v1.4 for game v1.26
		Currently inactive

	Mr_kWKD-The Musket Mod-2502525912 v1.3 for game v1.18+
		Currently ACTIVE

	Frosty-Configurable Explosive-local v1.1 for game v1.15
		Currently ACTIVE

	Pumpkin-Quality of Life Items-2500516293 v1.8 for game v1.26
		Currently ACTIVE

	The Ninja Scout-Decomposition-2497957604 v1.0 for game v1.11
		Currently ACTIVE

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently inactive

	yefeyks-Generators+-2490397546 v1.0 for game v1.17.3
		Currently inactive

	Blocksify & Frevv-Blocksify's Spies & Hitmen Mod-2480936339 v1.0 for game v1.11
		Currently inactive

	Blocksify-Blocksify's Mafia Mod-2471624645 v1.0 for game v1.11
		Currently inactive

	JGrimesGamed-Slider Enabler-local v1.0 for game v1.16+
		Currently ACTIVE

	JGrimesGamed-Mo' Fluids-2460574441 v1.0 for game v1.16+
		Currently ACTIVE

	JGrimesGamed-Gasoline Enabler-local v1.0 for game v1.16+
		Currently ACTIVE

	Evalarian-Lawless - High Profile Operations-2457776308 v1.0 for game v1.16
		Currently ACTIVE

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently ACTIVE
		Has been initialised

	Talon Zane-Map Blocks-local v1.0 for game v1.7
		Currently ACTIVE

	Quickness-Minecraft Doors Mod-2403302283 v1.0 for game v1.13x
		Currently ACTIVE

	Joe Roy-Misc. Items Mod-2397586458 v1.0 for game v1.14
		Currently ACTIVE

	Frosty-Gunpowder Mod-2394796059 v1.0 for game v1.14
		Currently ACTIVE

	OzimekPL-S.C.P. Foundation Expanded-2388808764 v1.2 for game v1.12+
		Currently inactive

	jimmyl-Android Injectors-2381177128 v1.4 for game v1.12+
		Currently ACTIVE

	Morzzic-Taser-2361892819 v1.2 for game v1.11+
		Currently ACTIVE

	jimmyl-Parts and Contraptions-2337159652 v3.9.5 for game v1.18+
		Currently ACTIVE
		Has been initialised

	[TSF] Life.exe-S.C.P.F. mod-2332568618 v1.0 for game v1.12+
		Currently inactive

	jimmyl-Parts and Contraptions-local v1 for game v1.10+
		Currently ACTIVE

	Alibarda-PowersMod-2276255188 v2.2 for game v1.18+
		Currently ACTIVE

	Morzzic-Photo Mode-2263832258 v1.0 for game v1.8+
		Currently ACTIVE

	Teletubbie With A Shotgun-PPG Spy Mod-local v1.0.5 for game v1.9+
		Currently inactive

	weirdo-Chemical Warfare-2226697361 v2.0 for game v1.22.2+
		Currently ACTIVE

	mishmeow-BagBomb Mod-2224901002 v1.0 for game v1.9.5
		Currently ACTIVE

	Morzzic-Smart Spawner-2195054961 v2.2 for game v1.10+
		Currently ACTIVE

	weirdo-Functioning Armor-2194511729 v3.0 for game v1.22.2+
		Currently ACTIVE

	Mr_kWKD-Humans+-2168468454 v1.3.0 for game v1.9
		Currently ACTIVE

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently ACTIVE

	(RU)Enot builder-Construction kit V0.9.5-2151076041 vV0.9.5 for game v1.8x
		Currently ACTIVE

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently ACTIVE

### Additional notes

it says windows 10 but im running windows 11 in the debug info

**Comment by Egan306** [comment]
i think it happens when you load many mods, it happened to me before too, just open 10 or 15 mods then it should be fixed, i think
