### ISSUE TITLE
Bomb effect on Reactor A5

### ISSUE THREAD

**Issue by FaeyanPlaya** [studio-minus/ppg-bugs-and-requests#3067]
### Describe the bug

Дым и огонь от бомб выходят за карту Reactor A5.

### Clearly describe how to reproduce the bug

Дым и огонь выходят за карту и не накладываются на некоторые объекты.

### Game version

Preview 1.27

### Operating System

Windows 10

### Additional notes

![20230813113131_1](https://github.com/studio-minus/ppg-bugs-and-requests/assets/139833225/c7aa7d29-a691-43f7-b071-740b77621bcf)
![20230813113150_1](https://github.com/studio-minus/ppg-bugs-and-requests/assets/139833225/7905d130-3acd-4e7f-99b2-923a32c1e7f2)

**Comment by mestiez** [comment]
English please
