### ISSUE TITLE
Catapult & Boulder

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#307]
**Feature description**
When you spawn it the spoon looking thing is at the top (like at an 60 degree angle) you load it with a boulder, pull the lever on the catapult the will set it back (so then it will probably be at an 15 degree angle) then you get a knife and then cut the rope and then it flings the boulder. It may also be used for humans if they can fit ig.

**Feature purpose**
This is adds a another type of medieval vibe to the game like the sword.

**Comment by vda8** [comment]
just make one yourself. its thee purpose of the game.
