### ISSUE TITLE
when you spawn a naval mine with "Q" its horns gets messed up

### ISSUE THREAD

**Issue by Egan306** [studio-minus/ppg-bugs-and-requests#3070]
### Describe the bug

![naval](https://github.com/studio-minus/ppg-bugs-and-requests/assets/142122720/a7c006cd-886f-435b-90c4-a0888f652439)

### Clearly describe how to reproduce the bug

just spawn a naval mine using "Q"

### Mod list

none

### Game version

1.27 preview 2

### Operating System

Windows 11

### Additional notes

none

**Comment by mestiez** [comment]
fixed
