### ISSUE TITLE
sound problem on the new Reactor A5

### ISSUE THREAD

**Issue by sha1g** [studio-minus/ppg-bugs-and-requests#3071]
### Describe the bug

Basically after you clear the map and break the glass the sound settings dont apply to it
i have every sound setting set to 30% and that does not apply to the glass, every sound the glass makes is just louder than any other.

### Clearly describe how to reproduce the bug

Clear the map, set sounds to 30%, break the glass in Reactor A5

### Mod list

no mods active

### Game version

1.27 preview 2 (64 bit)

### Operating System

Windows 10 Pro

**Comment by mestiez** [comment]
yeah fixed
