### ISSUE TITLE
Copying and Pasting Office Chair

### ISSUE THREAD

**Issue by Spicypebbles** [studio-minus/ppg-bugs-and-requests#3075]
### Describe the bug

when you paste a copied office chair or load in a contraption that uses the office chair the wheels are elevated from the ground 
or way beneath the chair. Even weirder things happen when you take certain parts of the chair apart and paste it with the wheels being located far from the chair and elevated from the ground.

### Clearly describe how to reproduce the bug

Copy and paste or save and load the office chair

### Game version

1.27 preview 2

### Operating System

Windows 10

**Comment by mestiez** [comment]
fixed
