### ISSUE TITLE
I can't move my camera on reactor A5 is this a feature or a bug?

### ISSUE THREAD

**Issue by THISISAPIE** [studio-minus/ppg-bugs-and-requests#3077]
### Describe the bug

So, when I get on reactor A5 I could not move my camera is this a feature or a bug.

                                                                                                                                           Also, I am on windows 11

### Clearly describe how to reproduce the bug

go onto reactor A5 on windows 11 or it might be a widespread problem.

### Game version

1.26 preview

### Operating System

Windows 11

**Comment by THISISAPIE** [comment]
Btw i love your game and I have over 295 hours on it.

**Comment by THISISAPIE** [comment]
Turns out I can't move my camera on any map I join so that is a bummer.

**Comment by mestiez** [comment]
Uninstall Cloddymod or whatever
