### ISSUE TITLE
Resend detailed information

### ISSUE THREAD

**Issue by isiszxcvbnm** [studio-minus/ppg-bugs-and-requests#3078]
### Feature description

Modify the animation of the grenade  This can make the game more realistic
![Cache_-2390f8c3eca643e6](https://github.com/studio-minus/ppg-bugs-and-requests/assets/142107267/133e0894-d94a-4a8f-84da-040a20b33637)
![Screenshot_20230813_213405](https://github.com/studio-minus/ppg-bugs-and-requests/assets/142107267/361839ae-b98a-48f9-9a69-4510f48e2486)

### Feature purpose

Make the game more realistic

**Comment by mestiez** [comment]
please stop spamming this
