### ISSUE TITLE
Add Shrapnel to grenade

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#308]
**Feature description**
Now before you say "This is just the same as the spike grenade." It isnt. This makes so when the grenade explodes 2 or 3 pieces of flamin hot sharp metal. 2 to 3 is way less than like the 1000 pieces of metal that launches out of the spike grenade.

**Feature purpose**
Realism and to make the grenade more deadly.

**Comment by mestiez** [comment]
has been in the game for quite a while now. just forgot about this issue.
