### ISSUE TITLE
upside down vacuum chamber at the top of Reactor map heats up

### ISSUE THREAD

**Issue by sha1g** [studio-minus/ppg-bugs-and-requests#3082]
### Describe the bug

I dont think its a massive problem but
the top of the Reactor A5 can heat up
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/82260424/31afb762-4c99-46ad-8771-9503dd9909d9)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/82260424/6b73b634-36d3-4fdb-ab8b-9f25c5488f4c)

### Clearly describe how to reproduce the bug

Put something hot to the top of Reactor A5

### Mod list

all inactive

### Game version

1.27 preview 2

### Operating System

Windows 10

**Comment by mestiez** [comment]
lmfao
