### ISSUE TITLE
Decoupler keeps the force of a normal sized decoupler even after shrinking down

### ISSUE THREAD

**Issue by Julzgamz** [studio-minus/ppg-bugs-and-requests#3083]
### Describe the bug

Decoupler normally decouples then repulse eachother with a force, said force stays the same even if the decoupler is small : ex
when the decoupler is very small, using it will decouple it with the strength of a bullet (for its size)

### Clearly describe how to reproduce the bug

Spawn a decoupler then resize both parts to be smaller, after that use it and you will notice the force is too big for its size

### Mod list

 ihave no mods enabled but my whole mod list comprises of:
 Reactive humans, Ai player mod,Souls mod,Attack on titan, On shot dismemberement, bobs one punch man, Snake in PPG, smoke grenade mod, Better car, Pain? no thanks!, The utopia ennemies detected, infection mod, Tunnel, Watertight box, a dragon ball mod, Just collars, Terraria AI, Mutation seringe, regrowth Mod, Mpw library, CCTV cameras and Attachments +

### Game version

1.27 preview

### Operating System

windows 10

### Additional notes

thats all i think

**Comment by mestiez** [comment]
fie
