### ISSUE TITLE
A small bug   Naval Mine

### ISSUE THREAD

**Issue by isiszxcvbnm** [studio-minus/ppg-bugs-and-requests#3085]
### Describe the bug

There is a problem with the detonator of the Naval Mine   The detonator was originally upright  
![IMG_20230815_080722](https://github.com/studio-minus/ppg-bugs-and-requests/assets/142107267/9e4539a9-ea47-494f-9bc6-56ec2f812908)
![IMG_20230815_080737](https://github.com/studio-minus/ppg-bugs-and-requests/assets/142107267/0fdc6991-a55c-4bad-9f4c-67695b79e865)

### Clearly describe how to reproduce the bug

Pause time and place naval mine   There's no problem at this point   When you lift the time pause   You will find that the position of the detonator is incorrect 

### Game version

1.27

**Comment by Julzgamz** [comment]
actually this happens for me when i place the naval mine using spawn left instead of spawn right, never happens anything weird when i pause time

**Comment by mestiez** [comment]
already solved
