### ISSUE TITLE
Reactor display can go below absolute zero.

### ISSUE THREAD

**Issue by eurtod** [studio-minus/ppg-bugs-and-requests#3089]
### Describe the bug

The display for the reactor shows the current temperature and if you want long enough it will go below absolute zero even though the thermometer doesn't.

### Clearly describe how to reproduce the bug

Start the reactor level and leave without doing anything for a bit. Eventually it will go down enough.

### Mod list

None

### Game version

1.27

### Operating System

windows 10

**Comment by u0068** [comment]
this bug was already reported
