### ISSUE TITLE
An issue thats really annoying for me.

### ISSUE THREAD

**Issue by FOXXO-Company** [studio-minus/ppg-bugs-and-requests#3091]
### Describe the bug

So the minigun and the green generator are bugged.
The minigun doesnt have its animation and has white pixel in front of the minigun.
And the generator doesnt show the status like the green neon stripes.

### Clearly describe how to reproduce the bug

I dont know how to fix..

### Mod list

No mods.

### Game version

1.27 preview

### Operating System

Windows 10

### Additional notes

Please fix thanks!

**Comment by u0068** [comment]
please rename this report to something like 'minigun and generator visual bug', or even better split it up into 2 different reports.
also please say what you were doing when this bug happened? devs cant fix the bug if they dont know why it happens.

**Comment by mestiez** [comment]
???? cant reproduce
