### ISSUE TITLE
Reactor temperature is able to go below -273.15°C

### ISSUE THREAD

**Issue by AnCopper** [studio-minus/ppg-bugs-and-requests#3093]
### Describe the bug

The reactor breaks the laws of thermodynamics by being able to cool below absolute zero.
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/82319489/ca4d8e93-87fb-4dde-befd-77cdc8e42bc1)

### Clearly describe how to reproduce the bug

By looking at the reactor data panel.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12363094/exported.game.debug.info.md)

### Mod list

-

### Game version

1.27 preview

### Operating System

Windows 11

### Additional notes

-

**Comment by mestiez** [comment]
known
