### ISSUE TITLE
pressing + and - on an object changes its layer

### ISSUE THREAD

**Issue by alikeobservant** [studio-minus/ppg-bugs-and-requests#3095]
### Feature description

if you hover over an object with ur mouse and it is highlighted green, then you can press the + or - keys on ur keyboard to move it one layer up, or down. you can also do shift + or shift -  to move it all the way to the top or all the way to the bottom

### Feature purpose

very simple but very useful. it's extremely tedious moving layers using the context menu, especially when you have 10+ objects, and they all need their own separate layers. this would save lots of time for everyone and make more people use the layering system if implemented.

**Comment by mestiez** [comment]
you can already bind keys to these actions
