### ISSUE TITLE
Copying or saving the office chair causes its wheels to be misplaced

### ISSUE THREAD

**Issue by YourImagianation** [studio-minus/ppg-bugs-and-requests#3096]
### Describe the bug

Like the title says, If I try to copy or save the office chair or any creation that contains it, the wheels will spawn somewhere other than their intended spot

### Clearly describe how to reproduce the bug

try to copy or save the office chair, spawn it back in or paste it.

### Game version

1.27 preview

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/142452979/2aa00db4-e4ac-4ba8-854d-fecd269bcebf

**Comment by mestiez** [comment]
already fixed!
