### ISSUE TITLE
Remove maximum angular velocity

### ISSUE THREAD

**Issue by wiksadeey** [studio-minus/ppg-bugs-and-requests#3102]
### Describe the bug

I found out that there is maximum angular velocity (3000rpm)

I saw that when i was doing engine, and after reaching 3000rpm, it's just freezes object's rotation until you stop it

### Clearly describe how to reproduce the bug

You need create mod that will print angular velocity of object in right down edge.

### Game version

1.27p1

### Operating System

Windows 11

**Comment by mestiez** [comment]
Not a bug, this is an intentional limit that I won't remove

**Comment by wiksadeey** [comment]
Uhh, ok
