### ISSUE TITLE
Contraptions all corrupted

### ISSUE THREAD

**Issue by KriegYay** [studio-minus/ppg-bugs-and-requests#3108]
### Describe the bug

Okay so.. Sorry to bother you again. I did fix the camera issue, but 1.27 corrupted all of my contraptions, I had like 300 of them, and they're all gone.

### Clearly describe how to reproduce the bug

For what I can understand, simply playing the 1.27 version.

### Game debug info

Is this the file? 
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12384346/exported.game.debug.info.md)

**Comment by mestiez** [comment]
I can't reproduce this. Even my contraptions from 1.0.2 (over one year old) still work. Could you share one of the affected contraptions?
