### ISSUE TITLE
BETA: when you load in its stuck Following GameObject

### ISSUE THREAD

**Issue by nebulal0l** [studio-minus/ppg-bugs-and-requests#3109]
### Describe the bug

When you load into Default or any map it follows "GameObject" as soon as you start.

### Clearly describe how to reproduce the bug

Open any map on 1.27 beta

### Game debug info

idk

### Mod list

I HAVE NO MODS ENABLED

### Game version

1.27 BETA

### Operating System

Windows 10

**Comment by mestiez** [comment]
uninstall cloddymod
