### ISSUE TITLE
Camera is not moving

### ISSUE THREAD

**Issue by AttackOnLouie** [studio-minus/ppg-bugs-and-requests#3111]
### Describe the bug

Using Mouse2 or arrow keys is not moving camera for me

### Clearly describe how to reproduce the bug

Go onto one of the maps (any of them) and attempt to move the camera

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12386511/exported.game.debug.info.md)

### Game version

1.27 preview 2

### Operating System

Windows 10

**Comment by mestiez** [comment]
uninstall cloddymod
