### ISSUE TITLE
suspicious mod and forbidden identifiers will it get fixed 

### ISSUE THREAD

**Issue by Volta23** [studio-minus/ppg-bugs-and-requests#3112]
### Feature description

I have notice a few mods come up with suspicious mod and that they are using forbidden identifiers to make the mods  and the game says do you want to accept risk so I was wondering if its going to get fixed because people are confused if its safe or not and can they use them so I'm wondering is it safe  

### Feature purpose

the purpose is it make sure us mod users  test the mods out and have fun with out getting a suspicious mod because people think its a virus and they delete the mod 

### Additional context

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/142722778/560337d7-013e-4cb4-a5d5-0714e860cb1b)

**Comment by mestiez** [comment]
Whether it's safe or not depends on the mod. The warning is there because the game has detected some _potentially_ unsafe code. It's your choice to accept the risk. Read the comments on the workshop page.
