### ISSUE TITLE
you can spawn item outside the map (Reactor A5)

### ISSUE THREAD

**Issue by nickich-09** [studio-minus/ppg-bugs-and-requests#3114]
### Describe the bug

you can spawn an item outside the map (Reactor A5)

### Clearly describe how to reproduce the bug

zoom out the camera, spawn the object

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12396170/exported.game.debug.info.md)

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/88079829/cdea1a9a-b28b-4342-83d2-81340b1cfffe

**Comment by mestiez** [comment]
this is actually okay
