### ISSUE TITLE
You can delete the entire Reactor A5 level 

### ISSUE THREAD

**Issue by ergo-man** [studio-minus/ppg-bugs-and-requests#3116]
### Describe the bug

Deleting the temperature screen will delete the entire map

### Clearly describe how to reproduce the bug

Right click the temperature screen, click delete

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12399583/exported.game.debug.info.md)

**Comment by mestiez** [comment]
thats okay

**Comment by mestiez** [comment]
this bug has been reported countless times and its already fixed please please look if your issue has already been reported
