### ISSUE TITLE
Not being able to move camera in People Playground Preview

### ISSUE THREAD

**Issue by CPU-119** [studio-minus/ppg-bugs-and-requests#3122]
### Describe the bug

I am unable to move my camera using the middle mouse button and moving the mouse around. The arrows do not seem to work either.

### Clearly describe how to reproduce the bug

Enter a map, try to press mouse buttons or use the middle mouse button and move the mouse around.

### Mod list

I have alot of mods so I am unable to list them. All of them are activated. However, they do not affect the camera in the non-beta version. I am not quite sure if it affects the preview version.

### Game version

1.27 preview

### Operating System

Windows 10

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/89999793/1262f8b3-d14f-4ac4-a385-a9f307c8472b

**Comment by ghost** [comment]
cloddymod moment

**Comment by CPU-119** [comment]
I don't use cloddymod
