### ISSUE TITLE
a map maker (for mods)

### ISSUE THREAD

**Issue by fishefishe** [studio-minus/ppg-bugs-and-requests#3128]
### Feature description

its very annoying when i see people make maps when i code like a dying fish. a map maker could be very helpful!

### Feature purpose

could make map mods easier

### Additional context

maybe it could be like the pizza tower "make your own pizza" mod where you can place collision/blocks and hazards.

**Comment by fishefishe** [comment]
im sorry if this has been recommended before i just needed to post this :(

**Comment by fishefishe** [comment]
this apperently has been confirmed sorry i didnt know

**Comment by myron-obsolete-account** [comment]
> this apperently has been confirmed sorry i didnt know

and why don't you, like
close it?!
