### ISSUE TITLE
Humans die instantly when weight is dropped on their feet

### ISSUE THREAD

**Issue by ThatCanadiankid** [studio-minus/ppg-bugs-and-requests#3137]
### Describe the bug

When heavy weight is dropped on a human's foot it dies almost instantly with most of its body being X'd out in detailed view

### Clearly describe how to reproduce the bug

Step 1: Summon a human
Step 2: Drop 1 ton weight on foot. 

Yeah simple as that

https://github.com/studio-minus/ppg-bugs-and-requests/assets/119873007/3dcbb5a7-c1be-4c85-99bd-3d4417b0c632

This effect is consistent between different iteration counts and is the same with non-preview versions of the game

### Mod list

I'm not that patient.

But this effect is still consistent when I dont have any mods active either

### Game version

1.27 preview

### Operating System

Windows 11

### Additional notes

for all I know this might not be a bug. 

But I don't think every single bone should be broken and a person should die instantly when their feet break

Event though this effect is still consistent if their bones (except for the foot obivously) aren't broken either.

**Comment by Drogo-man** [comment]
A known bug, it's just unity being unity.

**Comment by regv2137** [comment]
weird I don't have that bug, maybe they are just unconscious?
