### ISSUE TITLE
An in-game Map Creator

### ISSUE THREAD

**Issue by OoferTheCooler** [studio-minus/ppg-bugs-and-requests#3138]
### Feature description

It's a system that lets you enter a map creator when in the main menu.

### Feature purpose

It let's you create maps using background items (doors, pipes) for detail, props, map blocks such as water, basic, lava, etc.
You can then save the maps to play on them, or you can also upload them to the steam workshop for people to use.

I think it'd be great for people who wanna make maps but don't know how to use any softwares to do so. It'd also be simple to use and fun to spend time on.

**Comment by myron-obsolete-account** [comment]
there is a map maker being developed https://studiominus.nl/blog/index.html
