### ISSUE TITLE
Recompile Button

### ISSUE THREAD

**Issue by CPU-119** [studio-minus/ppg-bugs-and-requests#3146]
### Feature description

A recompile button but you can recompile the mods even if they don't have errors in them.

### Feature purpose

Recompiling mods even if they don't have errors. Useful for when you need to tweak values in the mod or scripting it while the game is open but you don't want to always restart the game for the changes to take effect. Instead you just press recompile, mod gets recompiled and the changes takes effect.

**Comment by royalealbert27** [comment]
there used to be a mod for that but for some reasons 01 studios deleted it because zooi doesn't like recompiling because of nerd reasons
