### ISSUE TITLE
I can't move my visual

### ISSUE THREAD

**Issue by GoldenPalace18** [studio-minus/ppg-bugs-and-requests#3149]
### Describe the bug

When I enter in any map in the demo, I can't move my visual saying that I'm following a "Game Object" in the top corner Right,

### Clearly describe how to reproduce the bug

Just enter in a map

### Mod list

Combat Mod, Evrything Colourable, Fish mod, Liquid Logic, Regrowth, Torture, Ultimate map block, More Nature, More vehicles 1 and 2, True minecraft Sword, MR, GJMR, Gore

### Game version

1.27 prewiew

### Operating System

Windows 10

**Comment by royalealbert27** [comment]
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/101178735/8a2459d4-d28d-4a40-81e6-d3eb3969ebb6)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/101178735/6e409f25-c4d3-4ba5-8011-dd93e49f5fa6)

**Comment by Egan306** [comment]
BANANE

**Comment by myron-obsolete-account** [comment]
> ![image](https://user-images.githubusercontent.com/101178735/265678988-8a2459d4-d28d-4a40-81e6-d3eb3969ebb6.png) ![image](https://user-images.githubusercontent.com/101178735/265679428-6e409f25-c4d3-4ba5-8011-dd93e49f5fa6.png)

thanks for using me
