### ISSUE TITLE
ex. X does Y instead of Z

### ISSUE THREAD

**Issue by PokeMrowa** [studio-minus/ppg-bugs-and-requests#3150]
### Describe the bug

I dont have any stuff from new update but i keep updating it. I tried to reinstall it but it gave nothing.

### Clearly describe how to reproduce the bug

I dont have any stuff from new update but i keep updating it. I tried to reinstall it but it gave nothing.

**Comment by royalealbert27** [comment]
pls look for tutorials https://www.youtube.com/watch?v=q20z-w2e6RU

**Comment by myron-obsolete-account** [comment]
try actually enabling the beta
