### ISSUE TITLE
Rigor Mortis

### ISSUE THREAD

**Issue by themonke09** [studio-minus/ppg-bugs-and-requests#3158]
### Feature description

A chance for rigor mortis to occur in humans, obviously when they are shot and killed or stabbed (i think it can occur with stabbed?)

### Feature purpose

Basically just for "realism" but it could also add... ragdoll modding capabilities maybe? (i dont know how this stuff works)

### Additional context

basically they just flop over when they get shot in the head and its kinda anti climatic so it would be cool for this to happen (it could be a togglable option!)

**Comment by mestiez** [comment]
Waht you're describing does not seem to be rigor mortis
