### ISSUE TITLE
Direct rocket hit will not mutilate people (enough)

### ISSUE THREAD

**Issue by Jandro22** [studio-minus/ppg-bugs-and-requests#316]
**Feature description**
Pretty simple suggestion. Right now if a _direct rocket_ hits a person, they will have their arms and legs and chest meatified, sure, but nothing actually tears off. In reality their arms and legs and head should literally be blown off.

**Feature purpose**
It would look a lot cooler instead of having all limbs stay intact after a _rocket_ hits their chest directly

**Additional context**
![image](https://user-images.githubusercontent.com/53024346/139327269-8703cae0-f29e-4bd3-ae7b-fd2c0a16d271.png)
This is what it _should_ look like

![image](https://user-images.githubusercontent.com/53024346/139327378-8bd736b7-e8dc-437c-971e-ecf3e31cc1ef.png)
This is what it _currently_ looks like. Notice how none of the limbs tear off.

**Comment by mestiez** [comment]
I have increased the explosion dismember chance. The video you linked looks so badass.
