### ISSUE TITLE
A People playground mobile port

### ISSUE THREAD

**Issue by Technocode9868** [studio-minus/ppg-bugs-and-requests#3160]
### Feature description

Basically this will be porting the PC version to mobile perhaps the price might be £7 and I will happily spend that money on the appstore 

### Feature purpose

Because you will get more profit on mobile than you do already 
Also expanding the games players
Your competitors Regular human workshop ect...
Will lose a lot of buyers making your game even more popular 

### Additional context

Perhaps the graphics could be adapted so lag wouldn't occur and the Interface could be something like this
When you want to spawn something just click the icon and double tap to spawn when you wanna change the settings double tap on the item you spawned basically the pc one without the keys 

Sorry if I am wasting your time...

**Comment by myron-obsolete-account** [comment]
clueless

**Comment by myron-obsolete-account** [comment]
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/53058491/f68141e1-f85b-4514-9cfa-a133363add96)

**Comment by myron-obsolete-account** [comment]
and there never will be one

**Comment by Technocode9868** [comment]
Why did you close my idea @mestiez

**Comment by mestiez** [comment]
I'm not interested in a mobile version

**Comment by Technocode9868** [comment]
Why @mestiez

**Comment by Technocode9868** [comment]
I mean it could bring more players @mestiez

**Comment by mestiez** [comment]
I don't really care about bringing in more players. I'm not a mobile gamer person myself so there's really nothing driving me to do it

**Comment by Technocode9868** [comment]
I really want it mobile because I can't buy a PC or anything like that

**Comment by Technocode9868** [comment]
Will you consider it someday @mestiez

**Comment by Technocode9868** [comment]
![Screenshot_20230916-125749_Samsung Notes](https://github.com/studio-minus/ppg-bugs-and-requests/assets/144607460/49d2d59c-2df6-4035-a8f1-85da3edcae1b)

I'm starting a petition anyway

**Comment by myron-obsolete-account** [comment]
@mestiez do you remember me
