### ISSUE TITLE
Counter, an a context menu option for the counter.

### ISSUE THREAD

**Issue by Chickennuggetma** [studio-minus/ppg-bugs-and-requests#3167]
### Feature description

It is a machine that when activated, displays a number on its screen, that goes up by one (or any set amount by the player) every time it is activated. A context menu option to reset at a certain number, and send out an activation signal when a certain number is reached.

### Feature purpose

It would make tracking how many times something has happened like a strike of lighting (through the use of electric signal converters) a realistic possibility. It can be used for many machines as well, serving as a timer and other things.

### Additional context

I got this idea when trying to test the frequency of the lighting strikes in the Reactor map, I realized there is no machine that can do this. There is probably some way to make something like this using what we already have, but it would be very useful (and potentially lag reducing due to not having to use so many machines just for one mechanic.) to have this implemented. 
Thank you.

**Comment by mestiez** [comment]
https://github.com/studio-minus/ppg-bugs-and-requests/assets/32131519/abcb8f52-2410-4a33-ada3-b3969e1fefaf
