### ISSUE TITLE
a list of feature requests from me

### ISSUE THREAD

**Issue by bigmaerk** [studio-minus/ppg-bugs-and-requests#3177]
### Feature description

**note: might add more later**
1. invisible glue for cleaner creations (rather than using say, an ugly fixed cable everywhere)
2. more sound-focused objects like varied alarms, louder bells and amplifiers. you can
3. security cameras that can be viewed on a TV via radio
4. a lantern that when broken will spread fire (if lit beforehand of course), but also just makes things feel home-y
5. more actions when cowering for humans, gorses and androids such as running away, pleading and/or changing facial expression (unless these things not being a part of them are part of lore)
6. wires keep their slack when moving connected objects in stop-time, unless holding shift or vice versa
7. bells would move up or down semitones when scrolling with your mouse hovering over them
8. UI in detail view would scale with their objects or scale with your zoom amount, adjusted by a slider in the options menu, and/or a toggle
9. motorized wheels would have a brake timer in the right-click menu, if set to 0, stopping will be instant
10. a find object menu that opens by numbered list by pressing a keybind that can teleport the view to an object (that will also give contraptions their name. this feature will also need to add individual names to objects like "Human 1", "Brick Cube 3", etc.)
11. a light robotic arm that can be moved around like the screen's arm in the reactor map (because we don't have a good way to do this with our current tools)
12. the glass on a blood tank will break upon being shot
13. an option for realtime shadows for players that have higher-end computers
14. humans will be blinded by bright lights (not sure what functionality you could have with this, maybe to cower and a visual acuity level to drop in the inspect menu, or a red "blind" message to appear)
15. multiple chunks of limbs separate along with the limb itself, or deformation of limbs
16. nitroglycerin will explode upon being mixed with certain liquids
17. custom statistics or variables that can be used for different objects
18. text displays when connected to an object with a red wire should display whatever text is on the connected object (such as heart monitors, thermometers, infrared thermometers or even holographic displays and/or other text displays.

### Feature purpose

i thought up these ideas while playing the game and not playing the game to hopefully make the game more extended and expandable than it already is. i believe that it'll make the game way more involved than it already is, but also add more functionality and usefulness to some objects. some of these i wanted to have in the game before i even thought about suggesting them because those things seemed annoying to deal with (such as wires losing their slack when moved in stop-time).

### Additional context

have a good day

**Comment by mestiez** [comment]
please dont group feature requests

**Comment by bigmaerk** [comment]
> please dont group feature requests

would you rather me individually request them?
