### ISSUE TITLE
new liquid outlet/pressurizer  feature

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#318]
**Feature description**
when attaching a pressurizer to the liquid outlet i suggest that it makes it shoot farther
**Feature purpose**
simply to make say a weapon that shoots death liquid across farther and generally i think it would be interesting
**Additional context**
none

**Comment by mestiez** [comment]
I have made it so that powering an outlet makes it eject with more force.
