### ISSUE TITLE
Reverb is gone randomly.

### ISSUE THREAD

**Issue by srabbs** [studio-minus/ppg-bugs-and-requests#3188]
### Describe the bug

Reverb randomly stops, no matter where the camera is.

### Clearly describe how to reproduce the bug

It's random.

### Operating System

Windows 10

**Comment by shurik3124** [comment]
Same problem.

**Comment by Afavertov** [comment]
Same

**Comment by mestiez** [comment]
If it's random I'm not sure what I have to look for. Any other information? Does it happen on all maps?

**Comment by Afavertov** [comment]
It happen on all maps, but more notably on big ones like hybrid.

**Comment by Afavertov** [comment]
Just fire 30mm at metal pole.

**Comment by Afavertov** [comment]
Hope you will notice difference before and after. If not - just repeat it by yourself. 
Object that you fire MUST be in center of the screen for bug to occur.
https://youtu.be/A8jol-hA2Sw

**Comment by Afavertov** [comment]
Noticed it?

**Comment by Drogo-man** [comment]
Well, i have found this happening when many loud sounds happen at once, ive seen it happen when you make a giant pile of dynamite and detonate them all.
