### ISSUE TITLE
Game flipped upside down on iPad

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#3190]
### Describe the bug

Whenever I open the game, the entire thing is just upside down. The limited settings menu has nothing to resolve this. I am using a 10th-generation iPad to play. The problem is extremely annoying, as I use an external keyboard and mouse, and the mouse is inverted. I have included a screenshot of the problem.
![IMG_6596](https://github.com/studio-minus/ppg-bugs-and-requests/assets/142110372/86588cd0-d7a5-4a21-9ae3-be5ea858b261)
(You may have to rotate your monitor to simulate the problem. The iPad’s UI rotates with the game, so the iPad though “up” was down.

### Clearly describe how to reproduce the bug

Use an iPad (10th generation if possible) and just play the game.

### Game debug info

Not on iPad.

### Mod list

Also not on iPad

### Game version

AAAAAAAAAWFEFGFVGGDFFESFDGG THAT DOES NOT EXIST ON IPAD

### Operating System

iPadOS 17 (218329)

### Additional notes

I included a video of how the messed-up rotation. (Don’t mind my parrot.)
https://github.com/studio-minus/ppg-bugs-and-requests/assets/142110372/58fda835-3dcf-4128-9c2e-3ae1b6c94799
.

**Comment by ghost** [comment]
How did you even launch it on an iPad?

**Comment by DindinYT37** [comment]
There's no iPad version?

**Comment by mestiez** [comment]
Please uninstall that app, it's not mine and someone is profiting off my work
