### ISSUE TITLE
Game crashes after installing some mods

### ISSUE THREAD

**Issue by MInecrafterPictures** [studio-minus/ppg-bugs-and-requests#3194]
### Describe the bug

After installing a couple more mods in addition to a bunch of them already present I noticed taht the game crashes whenever I try to run a map, ene a default one.
Most of my mods are downloaded from the Steam Workshop, but only one, which I don't think it's the problem, it downloaded from elsewhere.

### Clearly describe how to reproduce the bug

Mod subscription to various ones

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/12830297/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
Your PC is likely running out of RAM, just use fewer mods. Note that inactive mods can still impact this as they're loaded in nonetheless.

**Comment by Onogen** [comment]
Bro needs more ram
