### ISSUE TITLE
game stuck at 60 fps

### ISSUE THREAD

**Issue by kkl15** [studio-minus/ppg-bugs-and-requests#3196]
### Describe the bug

my game is stuck at 60 frames no matter what i disabled v sync, reinstalled, verified the games files and its still not working

### Clearly describe how to reproduce the bug

starting up the game

### Game debug info

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.22621) 64bit

 - **CPU**: 12th Gen Intel(R) Core(TM) i7-12700H

 - **GPU**: NVIDIA GeForce RTX 3060 Laptop GPU

 - **Memory**: 16 GB

### Mod list

All loaded mods

	Kasztan -Slicing Mod-3044394410 v1.0 for game vLatest
		Currently ACTIVE
		Malfunctioning

	DoKo321-Natural Disasters MOD-3044407758 vv1.1 for game v1.27+
		Currently ACTIVE
		Has been initialised

	L_R-LR's Hats n' Stuff-3039591742 v1.0 for game v1.25+
		Currently ACTIVE

	Dozi-Idk really-local v1.0 for game v1.8 +
		Currently ACTIVE

	Yakuari-Yakuari's 20th Century Law Enforcement Series - America-3021683292 v2.4 for game v1.8 +
		Currently ACTIVE

	Dyadyushka Dyadya-Grips Objects No Collide-3023377752 v1.0 for game v1.26+
		Currently ACTIVE

	01 STUDIO o. d.-Context Menu Speed Changer-local v1.0 for game v1.26+
		Currently ACTIVE

	GHOST MODS-M1A2 Abrams MOD REMAKE-local v1.0 for game v1.26
		Currently ACTIVE

	FEX-Weapon SFX Realism Mod-local v1.0 for game v1.26+
		Currently ACTIVE

	Int Team-Clothed Human-2992087897 v1.1 for game v1.26.6+
		Currently ACTIVE

	Dyadyushka Dyadya-Just Collars-2985454065 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	korbykob-Uncollidable Bodies-2963729979 v1.3 for game v1.21+
		Currently ACTIVE

	Int Team-More Vehicles 2-2963069537 v1.0 for game v1.26
		Currently ACTIVE
		Has been initialised

	megaturn-Modern Firearms 2 [1.2]-2960174793 v1.2 for game vAny
		Currently ACTIVE

	Int Team-MPW library-2953788932 v1.1.10 for game v1.26+
		Currently ACTIVE
		Has been initialised

	01 STUDIO-Combat Mod-2943789568 v1.0 for game v1.27+
		Currently ACTIVE
		Has been initialised

	Eduardoeldo-G&R: Taran Tactical-2932090931 v2.4 for game v1.26+ (Previews too)
		Currently ACTIVE

	megaturn-Modern Firearms-2926090676 v1.4 for game vAny
		Currently ACTIVE

	Bobr-Ultimate Double Barrel Shotgun Mod-local v1.0 for game v1.21+
		Currently ACTIVE

	NeitherFishNorCat-Automatic limb repositioning                             -2913582654 v1.1 for game v1.21+
		Currently ACTIVE

	Please Halp-Gun Smoke Trails-2908115498 vpenis for game v1.26
		Currently ACTIVE

	Dyadyushka Dyadya-Grip Fix-local v1.0 for game v1.26+
		Currently ACTIVE
		Malfunctioning

	ibiglaser-Weapon size affects its power Mod-2894415938 v1.0 for game v1.26+
		Currently ACTIVE

	Edu-Tactical Style Mod.-2865590962 v1.0 for game v1.21.2+
		Currently ACTIVE

	Dyadyushka Dyadya-Human Dynamic Emotions 2-2856823986 v1.0 for game v1.26+
		Currently ACTIVE
		Has been initialised

	megaturn-Pistols | WWII-2842111838 v1.6 for game vAny
		Currently ACTIVE

	GalaxyHighMarshal-BloodEnhancedMod-2811563551 v2.0 for game v1.23+
		Currently ACTIVE
		Malfunctioning

	Quickness, Mishanya, arkstar_, Dyadyushka Dyadya, Maxe, Laska-More Vehicles-2805966221 v1.5.2 for game v1.24x
		Currently ACTIVE

	Evalarian-Lawless 2-local v1.0 for game v1.23
		Currently ACTIVE
		Has been initialised

	Azule-Aerodynamics-2798194010 v1 for game v1.23.x+
		Currently ACTIVE

	hankmart-Human Decal Enabler-2794433695 v2.0 for game v1.21+
		Currently ACTIVE

	hankmart-Identical Humans-2788201842 v3.0 for game v1.26+
		Currently ACTIVE

	zooi-Darker blood-local v1.0 for game v1.22
		Currently ACTIVE

	Eduardoeldo-Law Enforcement Base: Germany-local v1 for game v1.21.2
		Currently ACTIVE

	Eduardoeldo-Law Enforcement Base: Less Lethal DLC-local v1.2 for game v1.11+
		Currently ACTIVE

	Eduardoeldo-Law Enforcement Base: USA-2754575076 v1 for game v1.21.2
		Currently ACTIVE

	pjstarr12-Feet Arent Indestructible-local v1.02 for game v1.0+ i think
		Currently ACTIVE

	Bonible-Vitals of Steel-local v1.12 for game v1.22.3
		Currently ACTIVE

	pjstarr12-Bones Break On Shot-local v1.02 for game v1.0+ i think
		Currently ACTIVE

	Mini-Mini's Roleplay Mod-2587903303 v1.0 for game v1.18
		Currently ACTIVE

	Fleasy-FleasyWeapons - Rifles-2571665852 v1.3 for game v1.20+
		Currently ACTIVE

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently ACTIVE

	Camdog74-Power Pack Framework-2506978276 v1.0 for game vEveryone to use!
		Currently ACTIVE

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently ACTIVE

	Mr_kWKD-The Musket Mod-2502525912 v1.3 for game v1.18+
		Currently ACTIVE

	Aspa102-Wheelchair-2455335631 v1.0 for game v1.16+
		Currently ACTIVE

	zooi-flipping heck-2448120172 v1.7 for game v1.23
		Currently ACTIVE
		Has been initialised

	Mr_kWKD-Military+-2390021263 v1.0 for game v1.11
		Currently ACTIVE

	Mishany-Melee Weapons Mod-2389733225 v7.0 for game v1.13+
		Currently ACTIVE

	Skittles-Skittle's Syringe Mod-2268097682 v1.4 for game v1.19+
		Currently ACTIVE

	weirdo-Advanced Damage-2212880187 v2.3 for game v1.22.2+
		Currently ACTIVE
		Has been initialised

	weirdo-Functioning Armor-2194511729 v3.0 for game v1.22.2+
		Currently ACTIVE

	zooi-Controllable anti-air cannon-2178648827 v1.2 for game v1.9.3
		Currently ACTIVE

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently ACTIVE

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently ACTIVE

### Game version

v.12.6

### Operating System

windows 11

**Comment by mestiez** [comment]
How do you know it's stuck at 60fps?

**Comment by kkl15** [comment]
> How do you know it's stuck at 60fps?

because i can see the fps on steam
