### ISSUE TITLE
Saving doesnt work

### ISSUE THREAD

**Issue by Onogen** [studio-minus/ppg-bugs-and-requests#3197]
### Describe the bug

im on 1.27p2 right now and i like building a lot of things but somehow saving doesnt work for me pls fix it

### Clearly describe how to reproduce the bug

Launching the game and trying to save something

### Game version

1.27p2

### Operating System

Windows 10

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/147315823/5c372319-28be-41a4-b585-986ccf43e03a

**Comment by mestiez** [comment]
Seems like a mod issue to me

**Comment by Onogen** [comment]
> Seems like a mod issue to me

Nah I tried disabling mods it's the same issue
