### ISSUE TITLE
Metal fasteners (fixed cables) are too soft

### ISSUE THREAD

**Issue by PZKPFW5** [studio-minus/ppg-bugs-and-requests#3209]
### Describe the bug

Sometimes the weight of the structure is too large and the metal fasteners (destructible and not) are fixed not tightly, but gently, that is, the heavy structure swings strongly and bends in the places of fastening of its parts, while it swings strongly and breaks the entire structure

### Clearly describe how to reproduce the bug

I am the creator of tanks and vehicles. Very often, when building a case, I encounter rocking and breaking of some parts in places of metal fasteners

### Mod list

No mods

### Game version

1.26.6

### Operating System

Windows 11

### Additional notes

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/134402396/d468fd9a-e3fe-496a-a078-f90eb3ace6fc)
The tower bends, although I fixed it with metal fasteners

**Comment by mestiez** [comment]
The fixed-ness of a cable is mostly determined by the mass difference between the two objects you're connecting. Also this bug is unfixable as far as I'm aware and it's been reported countless times :(
