### ISSUE TITLE
Blood spraying

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#321]
**Feature description**
Only when you get shot in the upper chest blood sprays out like this image and I mean this doesnt happen when you get shot but after.

**Feature purpose**
Realism and violence purposes.

**Additional context**
ayo for the people who are confused pretend the iron is blood.

![20211030084859_1](https://user-images.githubusercontent.com/55041380/139540172-f93da8ad-3f9d-4f9c-8052-8ee8133a6e13.jpg)

**Comment by atwal6400** [comment]
> "Realism and violence purposes."
> 
> -Shows a picture from a movie about an unrealistic blood spray.

idek what movie this is from but like i mean a blood squib in movies.

**Comment by Cboyjet4** [comment]
Have you played the game and shot somebody, literally identical.

**Comment by atwal6400** [comment]
> Have you played the game and shot a ragdoll, literally identical to what you are "suggesting".

i mean like a blood squirt not impact

**Comment by Cboyjet4** [comment]
> > Have you played the game and shot a ragdoll, literally identical to what you are "suggesting".
> 
> i mean like a blood spraying not impact

![image](https://user-images.githubusercontent.com/71295203/139557070-266284ab-b3e7-4b8a-abb5-727897d0cbb8.png)
![image](https://user-images.githubusercontent.com/71295203/139557084-dd8e604b-696f-46bc-9e8a-5a656f9b76b3.png)

**Comment by atwal6400** [comment]
> > > Have you played the game and shot a ragdoll, literally identical to what you are "suggesting".
> > 
> > 
> > i mean like a blood spraying not impact
> 
> ![image](https://user-images.githubusercontent.com/71295203/139557070-266284ab-b3e7-4b8a-abb5-727897d0cbb8.png) ![image](https://user-images.githubusercontent.com/71295203/139557084-dd8e604b-696f-46bc-9e8a-5a656f9b76b3.png)

im talking about adding smoke to that and a spraying sound for like 2 seconds then a gushing sound for like 4

**Comment by Cboyjet4** [comment]
> im talking about adding smoke to that and a spraying sound for like 2 seconds then a gushing sound for like 4

🤦‍♂️
