### ISSUE TITLE
camera not moving in sea map in beta (fix: the fix was to change maps)

### ISSUE THREAD

**Issue by artificerrain** [studio-minus/ppg-bugs-and-requests#3214]
### Describe the bug

so when i went in the beta version of PPG the game camera wasn't moving, it was very confusing, may you fix it

### Clearly describe how to reproduce the bug

it didn't go away, no matter how much i have tried.

### Game debug info

(i don't understand this, I AM SO SORRY ONCE AGAIN.)

### Mod list

i have to many to count, and i am sure none of them would do that stuff on beta of PPG

### Game version

beta

### Operating System

windows 11

### Additional notes

it says GameObject on the sea map, with the eye ball telling me i am "watching it" but there is nothing, i have restarted my PC about 2 times and it didn't work, please explain how to help me or anything my steam account is FelixFox, my email is sophia.setchfield@gmail.com, please message me on gmail or DM me on steam, i will reply when i can. thank you.

**Comment by artificerrain** [comment]
lol, i only made an account for this bug report-

**Comment by mestiez** [comment]
> and i am sure none of them would do that stuff on beta of PPG

This is not a justified assumption. 

The issue you are describing is commonly caused by a mod called "Cloddymod"
