### ISSUE TITLE
Insanely low FPS on newest preview when spawning humans

### ISSUE THREAD

**Issue by 2xddev** [studio-minus/ppg-bugs-and-requests#3216]
### Describe the bug

After updating to the newest preview, FPS drops below 30 when spawning a human

### Clearly describe how to reproduce the bug

Update to the newest preview (preview 4), spawn a human (haven't tested anything else), check FPS before and after

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/13043528/exported.game.debug.info.md)

### Game version

1.27 preview 4 (64 bit)

### Operating System

Windows 11 🤮

### Additional notes

This may or may not be due to mod usage, but I can't tell because I am very achterlijk. Thank you!

**Comment by 2xddev** [comment]
By the way, when you kill or knock out the human, the lag stops

**Comment by 2xddev** [comment]
This does not happen with androids or gorses, just humans.

**Comment by flabberghastedpuddle3** [comment]
**I can verify it happens on windows 10.** _Its universal I believe at least for windows until that is verified._
Wait I turned it from "beta to non-beta to beta back again" and it seems to be alright now. 
Not sure if this is a fluke. but it is just fine for me now?
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/148487490/18818778-ff35-453c-96ff-8a8fbc45d964)
So all I can say is, Try if it doesn't work well I will never know.

When it was it was up to 10fps with just two "humans" On a gtx 1080.

**Comment by flabberghastedpuddle3** [comment]
Earlier it was up to like 10fps before I reverted and stuff

**Comment by mestiez** [comment]
This seems to have been caused by the Scream mod. I read its code and implemented and uploaded a fix.
