### ISSUE TITLE
Possibility to reset the Counter without context menu

### ISSUE THREAD

**Issue by YourLocalPlonker** [studio-minus/ppg-bugs-and-requests#3220]
### Feature description

It should be a spawnable block in the machinery section. Doesn't really matter how it looks but preferably just a remodeled Activation Toggle block to keep it simple.

### Feature purpose

It would reset the Counter it is connected to with a green wire to 0 so systems with the Counter could run autonomously without the player having to reset each Counter themselves. I also think it could be used to reset anything else like the Pointer or the Rotor to their inherent position (The position they spawned in).

### Additional context

I don't really care about the Pointer and Rotor thing because that might cause some problems while coding. I really just want the thing with the Counter as that would just set the value of the Counter to 0. It would also be cool if it turned off lights. So if a light is off it will simply stay off and if it is on it will be turned off

**Comment by u0068** [comment]
probably better to just have it reset when it receives a red signal or something like that

**Comment by mestiez** [comment]
green increments, red decrements, blue clears

**Comment by YourLocalPlonker** [comment]
> green increments, red decrements, blue clears

Thank you good sir
