### ISSUE TITLE
stielhandgranate has spoon

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#3222]
### Describe the bug

stielhandgranate has spoon but it should not have one

### Clearly describe how to reproduce the bug

spawn it, that's it

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/13058650/exported.game.debug.info.md)

### Additional notes

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/104321411/ab195810-5cab-44aa-ae9f-3e000ba7856c)

**Comment by mestiez** [comment]
the fuck?

**Comment by mestiez** [comment]
fixed lmao
