### ISSUE TITLE
Fire extinguisher recoil is wrong.

### ISSUE THREAD

**Issue by Alexthebug9** [studio-minus/ppg-bugs-and-requests#3228]
### Describe the bug

The recoil on the fire extinguisher is in the wrong direction.

### Clearly describe how to reproduce the bug

use the fire extinguisher.

### Mod list

None

### Game version

1.27

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/123699091/feddea56-fd30-4f8d-9bcb-48f539b915d2

**Comment by mestiez** [comment]
fixed
