### ISSUE TITLE
Brains

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#324]
**Feature description**
When any human gets shot in the head some brains or brain matter will splat out and fall on the ground jiggly. (unless you want to to be a visual thing like the dismemberment particle.)

**Feature purpose**
Realism or Violence

**Comment by cuberon** [comment]
why do you make 50 feature requests per day

**Comment by ATPGaming** [comment]
@mestiez Wasn't this accepted a long time ago?

**Comment by DindinYT37** [comment]
Hey look, present ATPGaming found past ATPGaming!

**Comment by mestiez** [comment]
kind of... i guess ill accept it. sorry for epic delay, i should get other people to do this for me
