### ISSUE TITLE
Gun jamming/Breaking.

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#326]
**Feature description**
When guns get exploded there should be a clicking sound when you try to fire it that indicates the gun is jammed. Now I feel like only the glock should break when shot because its made of plastic.

**Feature purpose**
Realism and just a cool concept all together imo.

**Additional context**
![20211028171302_1](https://user-images.githubusercontent.com/55041380/139352827-7e9453e4-69e9-4388-beef-177ce5a23224.jpg)

**Comment by atwal6400** [comment]
> 1st - Guns don't explode it's usually the bullet causing the exploision. 2nd - Glock is not entirely plastic. The exterior is made out of hardened plastic, rest is metal.
> 
> A bit better concept:
> 
> * After you damage a gun enough using an explosive or another bullet, it should break. (But that'd require broken textures)
> * Too overheated guns should break.
> * Broken guns could be fixed using the wrench

ye thanks for some insight on my idea

**Comment by mestiez** [comment]
I don't think this fits the game. It's a cool idea for a mod though.
