### ISSUE TITLE
ex. X does Y instead of Z

### ISSUE THREAD

**Issue by HristoMihovski** [studio-minus/ppg-bugs-and-requests#3261]
### Describe the bug

Lorem ipsum

### Clearly describe how to reproduce the bug

Lorem ipsum

### Game debug info

Lorem ipsum
![Banner-Sustainable-Barbados-03Aug23](https://github.com/studio-minus/ppg-bugs-and-requests/assets/144589040/f334ec48-e1a8-428b-a4cd-b8725dcf6e0c)

### Mod list

Lorem ipsum

### Game version

Lorem ipsum

### Operating System

Windows 11

### Additional notes

Lorem ipsum

**Comment by Drogo-man** [comment]
Lorem Ipsum moment
