### ISSUE TITLE
NullReferenceException when grenade lever and pin hit the ground

### ISSUE THREAD

**Issue by PeppRRicode** [studio-minus/ppg-bugs-and-requests#3267]
### Describe the bug

When you activate a grenade the pin and lever fall to the ground; when this happens it will - on most occasions - throw a NullReferenceException 

I don't think it's game breaking because there isn't a use for the lever and pin of a grenade, but i think it's worth looking at because of it being a collision and PhysicalBehaviour issue

### Clearly describe how to reproduce the bug

Take 2 handgrenades, go near a corner and use a grenade, when the lever and pin of the first grenade hit the ground, use the other. 
If you have "log debug messages" on you will see the error being thrown.

If it doesn't work with 2 try with more grenades at the same time

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/13232282/exported.game.debug.info.md)

### Game version

1.27.3

### Operating System

Windows 10

**Comment by mestiez** [comment]
can't replicate
