### ISSUE TITLE
A machine which, when a signal is received, it sends out multiple signals at once

### ISSUE THREAD

**Issue by floofyneko69** [studio-minus/ppg-bugs-and-requests#3284]
### Feature description

A little quirk of the game is, when paused, a device can be activated multiple times at once, and it works as intended, such as a gun fires as many bullets as activated when paused.
So why not take this quirk and put it into a new device, which receives a signal and multiplies it by a variable amount entered by the user into another device, and sends that multiplied number of signals down a single signal wire.

### Feature purpose

The purpose of this new spawnable item is simply for fun, a joke item in a sense, and though it exists already, by pausing the game and repeatedly activating an item a number of times, that alone gets tiring to do

### Additional context

![signal multiplier concept](https://github.com/studio-minus/ppg-bugs-and-requests/assets/54698638/132d1057-3db9-4452-aeb4-60c8c84a6b08)

**Comment by ghost** [comment]
try using a timer

**Comment by floofyneko69** [comment]
> try using a timer

A timer delays a signal by a variable amount of time, and it can only send one signal after that timer finishes ticking down
Yes, that includes receiving spammed signals, they all get sent in the order received
