### ISSUE TITLE
Completed

### ISSUE THREAD

**Issue by isiszxcvbnm** [studio-minus/ppg-bugs-and-requests#3293]
### Feature description

Add a menu for modifying attributes to all weapons    damage， Recoil force， impact force， penetration， The firing rate of a gun， switch between semi-automatic and fully automatic      Add a save function， The value will not reset when switching directions    This is not difficult for you

### Feature purpose

Add more modified features to the game， Can make the game more playable

### Additional context

My friend has probably made it, but the technology is not mature enough to save it

**Comment by inferknob** [comment]
Mods exist, and are so easy to make.
