### ISSUE TITLE
small buttons glitch out next to explosions

### ISSUE THREAD

**Issue by man-man-man-man** [studio-minus/ppg-bugs-and-requests#3310]
### Describe the bug

i was trying to make a mechanism that detects an explosion and sends out a signal using a button, since shock detectors dont do that for some reason. and whenever a big enough explosion goes off, like a plastic explosive, the moving part of the button flies away which breaks my machine and it thinks its constantly being pressed.

### Clearly describe how to reproduce the bug

put a frozen small button next to a plastic explosive and detonate it, theres a good chance the red part will just fly away and despawn

### Mod list

no mods

### Game version

1.27

### Operating System

windows 10

**Comment by mestiez** [comment]
i didnt fix the bug because i think that's just unity physics moment, but i made the shock sensor respond to explosions
