### ISSUE TITLE
My Saiyans Heads Are Broken

### ISSUE THREAD

**Issue by Giggles1227** [studio-minus/ppg-bugs-and-requests#3312]
### Describe the bug

Every Time I Spawn A Saiyan They Either Look Straight Up Or Straight Down

### Clearly describe how to reproduce the bug

Just Spawn A Saiyan

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/13685577/exported.game.debug.info.md)

### Additional notes

![Screenshot 2023-12-15 072114](https://github.com/studio-minus/ppg-bugs-and-requests/assets/153920738/ae1d2ada-6bad-4104-a6c8-527998f36eed)  This Is The Dragon Ball Remastered Mod

**Comment by ghost** [comment]
Leave a comment on the mod page for the mod creator
