### ISSUE TITLE
heart monitor displaying 70 bpm with heart beat machine but human is dead

### ISSUE THREAD

**Issue by kacpi11222** [studio-minus/ppg-bugs-and-requests#3323]
### Describe the bug

if you kill human and connect heart beat monitor and machine it says 70 bpm even if its only torso or without blood but in real life its not possible

### Clearly describe how to reproduce the bug

kill human (every part must be X) get heart machine and connect it with heart and heart monitor then start machine and it says 70 bpm

### Mod list

advanced damage deactivated

### Game version

1.17.3

### Operating System

windows 10

### Additional notes

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/115418343/98e4ee53-81b5-4151-9ed0-3c69b0948091)

**Comment by fhgb54643689** [comment]
thats because the machine takes over the heart dumb dumb

**Comment by dikastisthereal** [comment]
it is dead but it has a heart beat because of the long machine (i dont remember the name), so if you disconnect its chest from the machine it wont have a heart beat and the beat monitor will show 0 BPM. So its not a bug its a smart detail.

**Comment by Aspa102** [comment]
the cardiopulmonary bypass machine takes over the heart's function and that is what the heart monitor is reading
