### ISSUE TITLE
an gas that does gassing

### ISSUE THREAD

**Issue by not7142** [studio-minus/ppg-bugs-and-requests#3345]
### Feature description

So basically a gas simulation. For that purpose existing fire simulation physics can be used. So yk when u shoot a suringe it explodes into gas, so why dont make some air humidifier that sucks out a liquid and then sprays it as gas. 

### Feature purpose

I think it should be implemented because then people can make toxic gas granades and stuff, it prob can be usen in many different ways but i really want it because i want to make an anastesia chamber which i still will make, but if the game had actual gas i could like charge a liquid tank and then spray it.

### Additional context

Sorry for quite deranged text, feeling quite unwell on the moment of typing this

**Comment by deadhitter1** [comment]
I think what would be easily doable is making a 'gas outlet' or 'sprinkler' that makes smoke like the Fire Extinguisher, except the smoke has the Liquid's effects.

**Comment by not7142** [comment]
I guess that makes more sense, however most gasses should rather go up. Just some heavy ones down. Or water physics but without being affected by gravity

**Comment by username228a91** [comment]
we have extingusher
