### ISSUE TITLE
Nerf pumpkins to op

### ISSUE THREAD

**Issue by kolokythi** [studio-minus/ppg-bugs-and-requests#3346]
### Describe the bug

i threw a pumpkin real hard through a decimator in slow motion it hit the ground shattered and deleted the damn floor it looked like it had move downwards but everything fell through it 
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/116385928/1bd0c27c-8115-4d2b-9367-b1c351897740)
idk if that worked but i doubt the floor should look like that

### Clearly describe how to reproduce the bug

get decimator, point at ground, get pumpkin, go into slow motion, drag the pumpkin real fast through the decimator it shouldn't disappear, then make the pumpkin explode on the flooring

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/13929270/exported.game.debug.info.md)

### Mod list

.

### Game version

1.26 preview 3

### Operating System

windows 11

### Additional notes

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/116385928/b44715b3-1c50-4733-89e4-9dfbcbd49804)

**Comment by mestiez** [comment]
Lmfao awesome
