### ISSUE TITLE
Vase shards are f'ed

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#335]
**Description**
No selection outlines on vase shards, and if you hold them & press the delete keybind then it spams VASE SHARD DELETED but nothing actually happens.

**Steps to reproduce**
Break a vase

**Mod list**
No mods

**System info**
 - Operating system: Irrelevant
 - Game version: 1.22 beta
 - GPU: Irrelevant
 - CPU: Irrelevant

**Comment by mestiez** [comment]
fixed :)
