### ISSUE TITLE
freaky humans

### ISSUE THREAD

**Issue by V4ul7B0y** [studio-minus/ppg-bugs-and-requests#3354]
### Describe the bug

when a humanoid holds a weapon/firearm, they begin to freak out

### Clearly describe how to reproduce the bug

take a human, have them hold a gun, and watch them freak out

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/14002725/exported.game.debug.info.md)

### Game version

1.27.5

### Operating System

Windows 11

**Comment by mestiez** [comment]
What

**Comment by V4ul7B0y** [comment]
ok, so i spawned a human in people playground, then i spawned a gun, the had the human hold the gun, and they started spazing out.

**Comment by V4ul7B0y** [comment]
please fix this.

**Comment by mestiez** [comment]
Cannot replicate. Try uninstalling your mods?

**Comment by TEQUILATEQUILA** [comment]
HOW DO I DOWNLOAD A MOD :(

**Comment by V4ul7B0y** [comment]
found the problem, apparently it was the mulligan mod.
