### ISSUE TITLE
Excalibur toggles break state on cars

### ISSUE THREAD

**Issue by Alextimka** [studio-minus/ppg-bugs-and-requests#3356]
### Describe the bug

https://github.com/studio-minus/ppg-bugs-and-requests/assets/59509074/f773b6f9-fd45-46f8-abc1-b50d50ac3018

If you stab a car with a broken engine using Excalibur, the car engine gets fixed.

### Clearly describe how to reproduce the bug

1. Spawn Excalibur
2. Spawn a car
3. Stab the car with Excalibur
4. The car engine is broken
5. Stab the car again
6. The car engine is fixed

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/14039313/exported.game.debug.info.md)

**Comment by Aspa102** [comment]
amazing
