### ISSUE TITLE
System.Reflection is making all of my mods suspicious

### ISSUE THREAD

**Issue by inferknob** [studio-minus/ppg-bugs-and-requests#3357]
### Describe the bug

Literally all of my mods (exaggeration, probably only 80%) are marked Suspicious because of "System.Reflection". I don't understand why but I am scared of accepting the risk and may regretting it.

### Clearly describe how to reproduce the bug

Open PPG, go to mods, it will show a lot of mods being marked suspicious from System.Reflection, for example:

On-Shot Dismemberment
Soft Zooi
Snake in People Playground
Watertight Box
Fish Mod
Functional Devices Mod
And so much more.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/14058073/exported.game.debug.info.md)

**Comment by soulware1** [comment]
the game literally can't do anything to your computer, maybe messing with its own files but not much else, zooi is just paranoid or smth

**Comment by mestiez** [comment]
> the game literally can't do anything to your computer, maybe messing with its own files but not much else, zooi is just paranoid or smth

Don't spread this sentiment if you have no idea what you're talking about. 

`System.Reflection` allows mods to circumvent all safety measures which technically allows them to do _anything_ to your computer. A mod could be as harmful as proper malware. This is why `System.Reflection` is marked as suspicious.

**Comment by soulware1** [comment]
eh   still disregard it, just don't subtoeverynewmodever, since i feel like there could be a worse glue  library situation,
