### ISSUE TITLE
Deserialed error???

### ISSUE THREAD

**Issue by soulware1** [studio-minus/ppg-bugs-and-requests#3361]
### Describe the bug

contraptions just deflate (don't spawn with any attachments) when spawned in

### Clearly describe how to reproduce the bug

have [my mod list](https://steamcommunity.com/sharedfiles/filedetails/?id=3148799822) i guess????

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/14074745/exported.game.debug.info.md)

### Additional notes

this still happens after a FULL reinstall (completely deleting the folder, as steam uninstall leaves some data behind)
also screenshot of one of the deflated thingies
![Screenshot 2024-01-27 205427](https://github.com/studio-minus/ppg-bugs-and-requests/assets/81992759/0f741aba-0e45-4284-8644-3b4a4e7695aa)

**Comment by mestiez** [comment]
Yeah idk you have so many mods that it's impossible to debug this

**Comment by soulware1** [comment]
skrill issue :(
