### ISSUE TITLE
when dismember a person and spawn a new one it get knock out and never wake up

### ISSUE THREAD

**Issue by tristanellix** [studio-minus/ppg-bugs-and-requests#3363]
### Describe the bug

when dismember a person and spawn a new one it get knock out and never wake up

### Clearly describe how to reproduce the bug

when dismember a person and spawn a new one it get knock out and never wake up

### Game debug info

https://github.com/studio-minus/ppg-bugs-and-requests/assets/158284260/33de5d8a-f25e-4fe3-9b7e-bfdebcbbae41

### Game version

latest

### Operating System

windows 10

**Comment by inferknob** [comment]
so next time you should do what asked instead of not responding to basically anything. You should export game debug info and if you can't then you NEED to write your mod list. Other than that, disable mods.
