### ISSUE TITLE
items bloom gets white and broken after inserting a save

### ISSUE THREAD

**Issue by Tomatofarmer444** [studio-minus/ppg-bugs-and-requests#3365]
### Describe the bug

inserting the asset (any) makes the items bloom get broken. eg. machinery active light.
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/105720013/6edc9e23-1964-447d-96b3-b8b39d42c7d6)

### Clearly describe how to reproduce the bug

described above
(does this even with all mods off)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/14229847/exported.game.debug.info.md)

**Comment by mestiez** [comment]
This is caused by a mod. Either that colourable mod or the invisibility mod. I know this because I've seen it before and this doesn't happen in my vanilla build
