### ISSUE TITLE
Electricity memory leak?

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#3369]
### Describe the bug

Don't know if it's actually a memory leak or something else- It happened 3 times already, so imma report it; I was making electronic logic stuff for like 3-5 hours in one map, had batteries active in the background for the entire time and after those few hours the game would run very poorly whenever a generator or anything with charge was active on the map. 
It was totally fine if there was no activated generators, I could spawn a ton of stuff, but even 5 active batteries would make it laggy. After I went into another map, it was back to normal.

### Clearly describe how to reproduce the bug

Don't know exact conditions, I guess have batteries active for few hours

### Game debug info

CPU: i7-9750H 2.60GHz
Memory: 8 GB
GPU: NVIDIA GeForce GTX 1660 Ti

### Mod list

Hold K to make wires invisible
- deactivated

flipping heck
- deactivated

### Game version

1.27.5, but happened in previous versions too

### Operating System

Windows 10  (10.0.19045) 64bit

### Additional notes

After about 3 hours in one map with active batteries spawned in;

https://github.com/studio-minus/ppg-bugs-and-requests/assets/119551742/bb275cef-1ad0-46df-9599-186faa588b32

Vsync is on for showing difference in performance a bit clearer, it never normally goes below 60fps.

**Comment by mestiez** [comment]
this is especially odd because electricity is just a number. if you can reproduce this issue then id appreciate if you could attach a log file (MAKE SURE TO REMOVE SENSITIVE DATA)
