### ISSUE TITLE
Fire kills too quickly

### ISSUE THREAD

**Issue by beanssssse** [studio-minus/ppg-bugs-and-requests#337]
**Feature description**
is it just me or does the fire kills humans way too fast? It's a matter of 1-3 seconds for them to simply drop dead after being lit on fire, they don't even have time to react in most cases, what happened? I remember they would stay a good bit of time alive on fire but now it seems they just die instantly

**Feature purpose**
So we could maybe go back to the old style of burning.

**Additional context**
n/a

**Comment by beanssssse** [comment]
> I think heat damage decrease will be the best in this case..

Agreed

**Comment by mestiez** [comment]
I agree.
