### ISSUE TITLE
Reactor A5 sandbox

### ISSUE THREAD

**Issue by Foxlord2** [studio-minus/ppg-bugs-and-requests#3375]
### Feature description

Reactor A5 sandbox will be Reactor A5 but you don't have to worry about the reactor meltdown.

### Feature purpose

so people can play with the map freely and don't have to work about the reactor meltdown.

**Comment by mestiez** [comment]
please god let me remember this

**Comment by ghost** [comment]
Would be cool if it was some autopilot button near a status screen

**Comment by Foxlord2** [comment]
yeah that would be cool Bibbybabby

**Comment by Aspa102** [comment]
did he remember

**Comment by Foxlord2** [comment]
Guys, he remembered 0o0
