### ISSUE TITLE
Workshop contraptions are broken, deserialisation errors are deleting wires in the contraptions.

### ISSUE THREAD

**Issue by Gmwatso** [studio-minus/ppg-bugs-and-requests#3376]
### Describe the bug

When I download a workshop contraption, it deletes some of the wires. Usually, these wires are connected to guns. This makes the contraption completely useless. It gives me a deserialisation error when this happens.

### Clearly describe how to reproduce the bug

I've got 200-300 mods active, it could really be any one of these. I've got no idea how to find which one is causing this without taking hours activating every mod one by one. I don't know how to replicate this.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/14397516/exported.game.debug.info.md)

### Mod list

Here's a list of all the mods/contraptions I have downloaded (most are contraptions):
https://steamcommunity.com/sharedfiles/filedetails/?id=3168298988

### Game version

1.27

### Operating System

Windows 11

### Additional notes

Video of the bug:
https://github.com/studio-minus/ppg-bugs-and-requests/assets/127570077/e51ff90b-0897-4f39-a82b-8fdb47b96aa9

Thanks for making one of my favorite games!

**Comment by mestiez** [comment]
apparently caused by the "Grouping mod"? unclear
