### ISSUE TITLE
Physics Spaghetti

### ISSUE THREAD

**Issue by deadhitter1** [studio-minus/ppg-bugs-and-requests#3377]
### Describe the bug

I'm sure you know. Anything with more than a few connections can turn into spaghetti at any moment when it hits something.

This is a common problem in physics engines, but in People Playground, it's exceptionally common.
I can't make vehicles or contraptions with more than ~5 fixed cables because it'll irreversibly spaz.

I suspect the problem is with how fixed cables work. They shouldn't have elastic properties. 

**Fixed cables should keep objects at a fixed distance, having them act as a single object.**

This is my main issue with this game, because it prevents me from doing most of what I want.

### Clearly describe how to reproduce the bug

Connect two 1-ton weights to a small object inbetween the weights, for example, a rod, then bend it.

The bigger the difference in mass between cabled objects, the more likely it is to spaghet. 
The lower the mass of the objects, the more likely it is to spaghet.

**Comment by deadhitter1** [comment]
Last week

**Comment by mestiez** [comment]
fixed joints inherently have elastic properties because they are springs. this issue cannot be fixed as far as i know

**Comment by mestiez** [comment]
for completeness: a "solution" would be to not use fixed joints at all, but instead group the colliders and attach them to a single rigidbody. this is partially implemented in PPG but it became pretty clear that it wasn't a feasible solution due to the _many_ fundamental design flaws in PPG
