### ISSUE TITLE
"ppgModLoader" File Missing and crashing the game.

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#3382]
### Describe the bug

Im not really sure if this was mentioned before but for me whenever i play ppg after some time like a few minutes and my workshop things pop up and load in, but then when a small tiny addon gets processed it crashes my game and i tried to delete the ones that are causing it it gave me even more crashing issues and when i read my crash log it was said that apparentally i dont have the ppgModLoader File but its there in my files?? I mean i didnt pirate the game or anything i just bought it off steam a few years ago and this started just now. I tried to validate files and i mean it did what it had to do but after installing the modloader file it keeps on crashing no matter what i do, maybe perhaps its a mod reading bug or anything like that?

### Clearly describe how to reproduce the bug

Open PPG like always just click the green button, It starts up and loads all my mods and workshop addons then just wait till something like a small addon or anything like that and it just crashes (I dont know how to really reproduce this as many people have this bug but i think this is the only place i can just wait for any help)

### Game debug info

Crash Log here
[Player.log](https://github.com/studio-minus/ppg-bugs-and-requests/files/14545687/Player.log)
Debug Info 
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/14545697/exported.game.debug.info.md)

### Game version

1.27.5 (64 Bit)

### Operating System

Win 10

**Comment by mestiez** [comment]
Many of your mods seem to be completely broken... Anyway it seems that the modloader's `config.json` file does not exist. Maybe an antivirus software keeps removing it by accident?
