### ISSUE TITLE
Ideas i guess...

### ISSUE THREAD

**Issue by gabeio64** [studio-minus/ppg-bugs-and-requests#3383]
### Feature description

 number 1 add a keybind to sit humans like if your holding a human and you press h or smth it will

make number 2 More cars thats it...

number 3 more building items for builders

number 4 changing the channel on a tv [there will be alot of channels news ones cartoon ones] just some fun stuff!

number 5 More modding support allow modders to do more things

number 6 Better broken bone ragdoll physics

number 7 More Variants to objects

number 8 Gore improvments

number 9 More/Better sound effects

number 10 Better Tutorial [i remember not knowing how to spawn objects in other ways than right Two weeks after i got the game]

number 11 ui/Menu tweaks

number 12 Crash fixes

Number 13 some sort of culling if not in the game already

number 14 some more optimization

number 15 Some more gore settings

number 16 More settings in general

number 17 Texture Tweaks

Number 18 Better Mod menu/Making mods enabled by default

number 19 Adding the option to make humans react to stuff like if someone dies infront of them they will run away kinda like the Active humans! mod DISABLED BY DEFAULT

number 20 LAST ONE add more ambient sounds and make there reasons to play the snow map for the love of god 

### Feature purpose

just because funny and alot of people will plob like some of these changes the tv channels one i think is bad imo

**Comment by mestiez** [comment]
please don't group requests
