### ISSUE TITLE
Dismembering modded characters.

### ISSUE THREAD

**Issue by JustAnotherUserXD** [studio-minus/ppg-bugs-and-requests#3385]
### Describe the bug

Characters just freeze and when I spawn a new one it just gets knocked out.

### Clearly describe how to reproduce the bug

This happens when a modified character's limb is crushed or when the character loses a limb..

### Mod list

Mulligan, DragonBall Playground Remaster, Identical Humans, Quick Right Click Options, Grips Objects No Collide, Better Sword, THE FLASH MOD, Deadpool mod, God Cube and Parachute Mod.

### Game version

1.27 preview 5

### Operating System

Windows 10

**Comment by mestiez** [comment]
i can't fix mods lol, message the mod creators
