### ISSUE TITLE
After enough physical damage, it no longer becomes visible.

### ISSUE THREAD

**Issue by JNJNRobin1337** [studio-minus/ppg-bugs-and-requests#3387]
### Describe the bug

When damaging a [Damagable Entity (person, gorse, etc)], after a certain point, it no longer appears on the body. This does not affect Percentage Damage (ie, burning or skin damage).
When caused with Impact Damage (ie, brick) it also prevents visible damage from other causes (gun, stab).

### Clearly describe how to reproduce the bug

Life syringe and something to cause visible damage (gun, knife, etc).
For the specific way i have often achieved it, mending syringe and Cardiopulmonary Bypass machine. also brick (stone)

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/14566036/exported.game.debug.info.md)

**Comment by mestiez** [comment]
to be clear, do you mean that wounds no longer show up after too much damage was done and then healed?
