### ISSUE TITLE
Context menu option that will make using electricity more stable.

### ISSUE THREAD

**Issue by iamtheonewhoshits** [studio-minus/ppg-bugs-and-requests#3394]
### Feature description

Option in context menu to prevent things from electrocuting (if you get electricity on any metal thing normally when it collides with other things it will bounce around) and will still be able to transform energy through itself by electrical wires.

### Feature purpose

Will be extremely useful in super tight contraptions which will use electricity to move around or as a weapon, will prevent most often way to cause *ball of mess*, bug which is basically infinetely rotating bidndings and indestructible parts of contraption at speed of sound, which will destroy everything else on the map, also this *ball* is hard to remove if its already bouncing.

### Additional context

![Снимок экрана 2024-03-22 161912](https://github.com/studio-minus/ppg-bugs-and-requests/assets/164353257/942a19ad-2d19-44de-bde5-eabc04b69287)
![Снимок экрана 2024-03-22 162006](https://github.com/studio-minus/ppg-bugs-and-requests/assets/164353257/d48e0e11-af3e-4d5d-8b78-0cf956d17b94) Basically explanation in pictures of idea im suggesting.

**Comment by Aspa102** [comment]
done :)
