### ISSUE TITLE
Flipped resistor flips the output of the resistor instead of keeping the normal value

### ISSUE THREAD

**Issue by hunterprine267** [studio-minus/ppg-bugs-and-requests#3404]
### Describe the bug

Whenever you spawn a resistor to the left or right and set an angle on it, and if when you flip it, the resistance it outputs changes to the angle it looks like visually. This causes problems when you have a resistor in a contraption set to a specific value and when you spawn that contraption to the left instead of the right, the amount of resistance is flipped. This would make a machine that is made to have 10% resistance always, when spawned the opposite direction will have 90% resistance.

### Clearly describe how to reproduce the bug

Spawn a resistor and set a new value, connect it to a battery, connect it to a gauge. Save and spawn in the opposite direction. See the wrong amount of desired resistance on the gauge.

### Game debug info

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/14810370/exported.game.debug.info.md)

### Game version

1.27.3

### Operating System

Windows 11

### Additional notes

I realize this is probably a coded feature, but feel it to cause many problems and to be seen as a bug.

**Comment by Aspa102** [comment]
oversight
ill add it to my list of bugs
