### ISSUE TITLE
Make blue activation signals toggle parking brakes on the motorised wheel

### ISSUE THREAD

**Issue by LoveDestroyer69** [studio-minus/ppg-bugs-and-requests#3406]
### Feature description

It's very simple. Green signal starts the motor, red signal reverses it and the blue one... does nothing? So, here is what it should do: TOGGLE PARKING BRAKES, simple as that, i bet its just a function to be called.
So, to better explain this, blue activation goes in, the parking brakes toggle from on to off or from off to on.

### Feature purpose

It would make braking in user-made cars easier, as of right now you have to manually select the wheels and click to toggle the brakes. By implementing this feature, with the click of a button you could toggle them on command, easy as that, no weird pausing, selecting toggling and so on...

### Additional context

Blue Signal ---> Toggle Parking Brakes

**Comment by Aspa102** [comment]
consider it done
