### ISSUE TITLE
Resizing the rotor does not change the weight of the disc

### ISSUE THREAD

**Issue by CowsFart** [studio-minus/ppg-bugs-and-requests#3409]
### Describe the bug

If you resize a rotor, both the base and disc of the rotor will shrink, however the weight of the disc does not decrease. This makes smaller rotors very heavy for such a little size. 

What should happen: Resizing the rotor will shrink the base and the disc in size, decreasing the weight of both.
What happens instead: Resizing the rotor will shrink the base and the disc in size, but only the base decreases in weight.

For context, here are the parts I'm talking about:
Rotor base -> https://github.com/studio-minus/ppg-bugs-and-requests/assets/126122609/76f93617-0dc5-492d-bc00-978cbb6eb036
Rotor Disc -> https://github.com/studio-minus/ppg-bugs-and-requests/assets/126122609/31a54429-cc4f-456f-877f-34d707aa1bee

### Clearly describe how to reproduce the bug

Go onto any map and spawn a rotor. Hold left click and drag to select both the base and the disc. Press 'G' to toggle detail view. Notice that the center of mass (the yellow and black symbol), is in between the disc and the base. Now, right click and select "Resize". Hold the 'LEFTSHIFT' key and shrink the size of the rotor. As you shrink the rotor, notice that the center of mass rises to the disc, instead of staying in the same place as it should. This doesn't make sense because if the size of the two objects keeps relative, so should the weight. This means the weight of the disc is not decreasing, and that is the bug.

### Mod list

No mods.

### Game version

1.27.5

### Operating System

Windows 10

### Additional notes

This also applies to the servo and the pointer.

This bug also applies the other way around. Instead, if you increase the size of the rotor, only the base will increase in weight, moving the center of mass down instead.

**You can actually avoid this bug. After shrinking the rotor, resize the disc just a tad bit, and its weight will automatically adjust according to its size.**

**Comment by Aspa102** [comment]
this happens because technically the two parts dont actually talk to each other when they're being scaled down and hence only one changes their mass (this is coded in the physical behaviour); the other doesn't notice its been shrunk and its mass remains the same
