### ISSUE TITLE
Zombies

### ISSUE THREAD

**Issue by Whelchur** [studio-minus/ppg-bugs-and-requests#341]
**Feature description**
Please Add Zombie Variants That Has AI Like Speedy But Weak Zombie,Slow But Powerful Zombie,Normal Zombie With AI Or Other Variants That You Can Think,Thanks.
**Feature purpose**
I Sent This Request Because Of I Bored From Normal Zombies That Cant Infect And Does Not Have AI
**Additional context**
Please Make Them Spawnable Without Zombie Syringe Or Other Syringes

**Comment by Cboyjet4** [comment]
Save a zombie and spawn it, it's as simple as that.
As for AI, zooi has stated multiple times that they will not add any sort AI to the game.
