### ISSUE TITLE
Donno if it is an actual bug but here I go

### ISSUE THREAD

**Issue by egelee06** [studio-minus/ppg-bugs-and-requests#3411]
### Describe the bug

Like I said on the title I don't know if this is a bug or if it can be fixed. When you apply to much force to a human (e.g. shooting them with an accelerator) considering they they don't just blow up into a million pieces their limbs just start spinning and that goes on of minutes and probably hours(I haven't seen them stop) 

### Clearly describe how to reproduce the bug

to recreate the bug maybe try making a human invincible and shoot him with an accelerator

**Comment by mestiez** [comment]
I am aware
