### ISSUE TITLE
New Customizable Gore Options

### ISSUE THREAD

**Issue by GitNeto** [studio-minus/ppg-bugs-and-requests#3418]
### Feature description

The '**Customizable Gore Options**' feature allows users to **adjust** the **level of gore** in the game according to their **preferences**. This feature enables players to **modify specific elements** such as **projectile wound sizes**, **explosion fragment wound sizes**, and other graphic details, such as shown in the picture for additional context.

### Feature purpose

Remember when you (**mestiez**) conducted a **vote** on the **bullet hole sizes** for an **upcoming update**? As we know, there were **various opinions** and **diverse votes** reflecting the **community's preferences**. This **feature**, as far as I know, aims to **annihilate** further complaints about the **gore system**. Whether it's the **length of blood squirts** or the **behavior of blood**, this feature intends to **address any concerns** or **opinions hurled your way**. It's designed to offer the customization needed to match **individual preferences**, hopefully putting **an end** to those ongoing **debates**.

### Additional context

![example for zoi](https://github.com/studio-minus/ppg-bugs-and-requests/assets/86885794/7f582b41-b8f9-4cff-b90e-be10f8e67fc2)

**Comment by Aspa102** [comment]
i definitely saw this more than a few weeks ago? huh?

**Comment by GitNeto** [comment]
> i definitely saw this more than a few weeks ago? huh?

What are your thoughts on this idea?

**Comment by Aspa102** [comment]
too much work for not a lot of reasons
why should the player even be allowed to disable just cuts? what is the point?
its way too complicated of a feature and i cant think of any good reason for it to exist other than making 3 people happy because they can adjust the bullet hole size

**Comment by GitNeto** [comment]
> too much work for not a lot of reasons why should the player even be allowed to disable just cuts? what is the point? its way too complicated of a feature and i cant think of any good reason for it to exist other than making 3 people happy because they can adjust the bullet hole size

I hear you Aspa, but we should not overlook the importance of the so-called player satisfaction here. For you it might seem like a lot of work for what you perceive as “minimal impact”, but we should consider the bigger picture, alright?

We know this community is diverse when it comes to preferences, (trust me, it is). I don't like to repeat myself, though I have to mention the bullet wound size drama again. I am pretty sure that was just the tip of the iceberg when it came to the different types of opinions out there. Offering these options isn't just about (as you say) making ”three people happy”; it's about acknowledging and respecting the different types of preferences within our player base.

And let's not kid ourselves about the “complexity”. Other games, even those who are mostly run by solo devs, have similar features included, (Human Workshop) and it works just fine. We are not reinventing the wheel or anything; we are just giving players more control over their experience. (Honorable Mention: Garry's Mod)

So, yeah, maybe it's not the easiest thing for the devs to implement, but isn't player satisfaction worth the effort? We should prioritize giving the players the best experience that we can possibly give them, even if it means a bit more work on our end.

Looking forward to your thoughts.

**Comment by Aspa102** [comment]
no
