### ISSUE TITLE
Bullets shoot  but freeze in place

### ISSUE THREAD

**Issue by Rhinocerross** [studio-minus/ppg-bugs-and-requests#3448]
### Describe the bug

When I fire any gun in the game it will shoot a bullet as a yellow line, that freezes, these lines can only collide with humanoids and when they do, if it is a human it will go through and go to the next area the bullet would normally be but with an android, it works fine. It seems like it fires and doesn't know where the bullet should be so it puts a line.
<img width="693" alt="Screenshot 2024-06-09 at 9 20 44 PM" src="https://github.com/studio-minus/ppg-bugs-and-requests/assets/126845496/409d61b2-33d1-4bb3-9fd0-49e50e182b40">

### Clearly describe how to reproduce the bug

I don't know how to produce it

### Game debug info

[exported game debug info.md](https://github.com/user-attachments/files/15757103/exported.game.debug.info.md)

### Mod list

I have no mods but it seems to act like they are still there
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/126845496/6d6e53ce-0835-4707-becf-bf33d64aa315)
![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/126845496/af5d55ad-025e-496b-89f3-ad7d1194448d)

### Game version

1.27.5

### Operating System

Running windows ten through whiskey (virtual machine)

**Comment by Aspa102** [comment]
its possible the virtual machine isn't perfect and there is some error occurring
or maybe something is terribly wrong lol

**Comment by Rhinocerross** [comment]
i got a windows machine now so
