### ISSUE TITLE
ex. X does Y instead of Z

### ISSUE THREAD

**Issue by Lunius88** [studio-minus/ppg-bugs-and-requests#3450]
### Describe the bug

https://github.com/studio-minus/ppg-bugs-and-requests/assets/172534749/e5c981dd-5385-43d4-928b-5bcc0d40a005

### Clearly describe how to reproduce the bug

https://github.com/studio-minus/ppg-bugs-and-requests/assets/172534749/2c001ecd-89af-47ad-b5b5-1f5ef3b7a3c2

### Game debug info

[exported game debug info.md](https://github.com/user-attachments/files/15809788/exported.game.debug.info.md)

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.22631) 64bit

 - **CPU**: 12th Gen Intel(R) Core(TM) i5-12400F

 - **GPU**: NVIDIA GeForce RTX 4060 Ti

 - **Memory**: 32 GB

## All loaded mods

	Mobrack20-Gore Human-3143374104 v1.0 for game v1.27+
		Currently ACTIVE

	NeitherFishNorCat-Rewinder -3086864906 v1.0 for game v1.21+
		Currently ACTIVE

	Dyadyushka Dyadya-Antigravity Map-local v1.0 for game v1.26+
		Currently inactive
		Malfunctioning

	zuccian-Generic Jojo Mod Remastered-2876316369 v1 for game v1.10+
		Currently ACTIVE

	01 STUDIO-Everything Colourable-2874724005 v1.1 for game v1.26+
		Currently inactive
		Malfunctioning

	Dyadyushka Dyadya-Liquid Logic-local v1.0 for game v1.26+
		Currently inactive
		Malfunctioning

	Dyadyushka Dyadya-Torture Mod-2870378567 v1.0 for game v1.27+
		Currently inactive
		Malfunctioning

	Dyadyushka Dyadya-Pose Manager-local v1.0 for game v1.26+
		Currently inactive
		Malfunctioning

	Dyadyushka Dyadya, ibiglaser improvement-[Improved] Pickup Advanced (Pickup anything)-2863389507 v1.0 for game v1.25+
		Currently inactive
		Malfunctioning

	Kor_BarBeQ-BarBeQ's Ultimate FNaF Animatronics Pack-2843820727 v1.0 for game v1.24+
		Currently inactive

	Mishanya-Functional Helicopter Mod-2839691188 v0.3.1 for game v1.25+
		Currently ACTIVE

### Operating System

windows 11

**Comment by mestiez** [comment]
please describe the problem using words
