### ISSUE TITLE
Mechanical belts use original object collider instead of modded new 

### ISSUE THREAD

**Issue by SavaTG** [studio-minus/ppg-bugs-and-requests#3455]
### Describe the bug

If i add a new object that has different collider to its original mechanical belts won't register that and change how they cover the object 

### Clearly describe how to reproduce the bug

make a mod that adds big item and set OriginalItem to something like brick. Fix colliders on this new item.
In game try to connect this item with another vanilla item with belt. Spin the vanilla item

### Game debug info

[exported game debug info.md](https://github.com/user-attachments/files/15921226/exported.game.debug.info.md)

### Additional notes

https://github.com/studio-minus/ppg-bugs-and-requests/assets/87876009/2244c7ec-4e11-4d93-ba8e-651628c1e4d2

this container that i added weighs a lot but this bug is not effected by weight at all

**Comment by Aspa102** [comment]
you didn't regenerate the collider grid points or something i cant recall lol

**Comment by SavaTG** [comment]
> you didn't regenerate the collider grid points or something i cant recall lol

![image](https://github.com/studio-minus/ppg-bugs-and-requests/assets/87876009/0682b2f0-781b-4cb3-b55e-a2c983142ab2)
Thanks!
