### ISSUE TITLE
Copy & Paste

### ISSUE THREAD

**Issue by BloodyPierce** [studio-minus/ppg-bugs-and-requests#3457]
### Describe the bug

The bug is that when you copy an object that has an explosive area or has a built in light (example: Jet Engine) it will make the light more brighter than normal

### Clearly describe how to reproduce the bug

Select (example: Jet Engine) and copy & paste it or save it and then place it down again from the saves tab.

### Game debug info

![Snimka zaslona 2024-06-24 224455](https://github.com/studio-minus/ppg-bugs-and-requests/assets/108227743/ad7034b6-c19a-44c9-bb00-389096e15944)
The top one is the non copy and pasted and the bottom one is the one i copy and pasted / saved and placed down from the saves tab

**Comment by mestiez** [comment]
This is likely caused by that "everything colourable (?)" mod
