### ISSUE TITLE
black screen when mods loaded

### ISSUE THREAD

**Issue by avgdarkenjoyer** [studio-minus/ppg-bugs-and-requests#3464]
### Describe the bug

when i load on, all the mods start loading, but when the final one finishes, the screen just turns black and i cant click or see anything.

### Clearly describe how to reproduce the bug

idk

### Game version

1.27

### Operating System

windows 10

**Comment by royalealbert27** [comment]
*sigh* you didnt even list the mods. how can we help you? Just uninstall the mods and see what happens.
