### ISSUE TITLE
please ad this

### ISSUE THREAD

**Issue by peapleplayground-player** [studio-minus/ppg-bugs-and-requests#3466]
### Feature description

we need a feature to be able to flip stuff so its facing the other way

### Feature purpose

just makes it easier when doing stuff

**Comment by royalealbert27** [comment]
*sigh* just use the flipping heck mod. It won't be in vanilla. don't ask why.

**Comment by peapleplayground-player** [comment]
> _sigh_ just use the flipping heck mod. It won't be in vanilla. don't ask why.

ok thanks
