### ISSUE TITLE
Scuffed teleporter breaks maps

### ISSUE THREAD

**Issue by vaccyyy** [studio-minus/ppg-bugs-and-requests#3479]
### Describe the bug

I made a scuffed teleporter two years ago (with no mods) that still works in today’s patch and completely messed up a bunch of the maps I made it using a servo and human that somehow works (i have no idea how) and i have never been able to replicate it, i just saved it while it still worked. I posted it on people playground steam discussions under “glitched hybrid.” idk if there’s anything that can be done with this.

### Clearly describe how to reproduce the bug

I used the scuffed teleporter (i can post as a contraption if needed) until it worked (just spawning it and hoping it works, sometimes it just kills the guy so i would press z and spawn it again) twice which would mess up the maps in crazy ways.

### Mod list

Active humans (active)
status icons (active)
fire remover button (active)
easier arm selection (active)
guns n’ ammo (inactive)
power orbs mod (active)
other weapon attachments (active)
grouping mod (active)
rewinder (active)
syringe gun and gas emitter and more! (active)
human dynamic emotions 2 (active)
reloadable explosive weapons (inactive)
quick right click options (active)
power pack framework (active)
powersmod (active)
chemical warfare (active)
russian roulette mod (active)
BarBeQ’s sky walker saga lightsabers (inactive)

### Game version

1.27 patch 5

### Operating System

Windows 11 Pro

### Additional notes

Everything is under “glitched hybrid” in steam discussions
Acc name: vaccy (with a mr president pfp)

**Comment by mestiez** [comment]
#1
