### ISSUE TITLE
Boat Motors work "better" then Resized upwards

### ISSUE THREAD

**Issue by Lordjakob** [studio-minus/ppg-bugs-and-requests#3489]
### Feature description

When Resized to be larger depending on the size the boat motor gets more powerfull and can push larger and heaver objects in the water

### Feature purpose

It would allow for the creation of large boat contraptions and Such 

### Additional context

Depending on the Size it could be 2x 5x 10x Stronger 
![grafik](https://github.com/user-attachments/assets/d8422c48-b26c-44fa-9e3f-1ab537c48329)

**Comment by Aspa102** [comment]
done

**Comment by Lordjakob** [comment]
Thanks
