### ISSUE TITLE
Remove out of bounds item deletion.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#349]
Make out of bound item stop removing.

Item deletion when it out of bound is buggy and useless.

**Comment by idotwaffle** [comment]
buggy how? seems fine for me

**Comment by Afavertov** [comment]
Items can randomly dissapear.

**Comment by mestiez** [comment]
That bug has been fixed and this feature is certainly not useless. #205

**Comment by vda8** [comment]
i never see the purpose in it, but i never see why not?
