### ISSUE TITLE
fps going down for no reason

### ISSUE THREAD

**Issue by kwazar0X** [studio-minus/ppg-bugs-and-requests#3494]
### Describe the bug

after some months of playing fps started being strange like it went from 60 to 10 and kept there, i tried reinstalling, tried asking nothing helped, IT IS NOT MOD problems, i deleted contraptions, mods still same thing, hope there is a fix. (deleting all game files then installing doesn't help too)
AND i also seen other people crying in the steam with the same problem.

### Clearly describe how to reproduce the bug

unknown

### Game debug info

[exported game debug info.md](https://github.com/user-attachments/files/16992134/exported.game.debug.info.md)

### Mod list

Generic PMC / Private Military Company REMAKE : status active
Protogen pack mod REUPLOAD : status active
Item Plus : status active
MPW library : status active
Quick Right Click Options : status active
Useful Context Menu Options : status active
Quality of Life Items : status active
Aerodynamics : status active
Background Tools Mod : status active
More Vehicles : status active
Magdump Mayhem [RD]W] : status active
More Vehicles 2 : status active
The Ultimate Car Mod : status active
flipping heck : status active
Identical Humans : status active
Humans+ : status active
The Bank Robbers Mod : status active

### Game version

1.27 patch 5 (1.27.5)

### Operating System

Windows 7 ultimate SP1, 64bit

### Additional notes

i join the game after like 10s fps going from 60 to 56 then slowly to 30 and then stays on 10-15 fps
P.S laptop specs: Windows 7 ultimate SP1, 64bit ; GT 525m, 4x i3-2350m, 6 gb of ram, HDD, dell laptop: INSPIRON, srs premium sound, 1600x900 monitor

**Comment by NameLord** [comment]
Remove these damn mods, and try again.. dummy dumbell.

**Comment by mestiez** [comment]
how do you know its not mod problems lmao

**Comment by kwazar0X** [comment]
well as i discovered later that ur game first has performance issues and
also that my laptop is currently broken because not only after fps started
going down but also i started getting whole laptop crashes what went into
other programs.
