### ISSUE TITLE
I NeEd FrIeNdS tO pLaY tOgEtHeR

### ISSUE THREAD

**Issue by NameLord** [studio-minus/ppg-bugs-and-requests#3496]
### Feature description

Why noone are intrested in in Multiplayer or 2 Player Mod ? :| IT DOESN'T MAKE ANY SENSE..........

### Feature purpose

Advertise the game so more people come and mutilate the dolls.

### Additional context

Please fix it.

**Comment by 2xddev** [comment]
this feature request is the reason why github needs age verification
