### ISSUE TITLE
lvl_train_machinist engine bug

### ISSUE THREAD

**Issue by kidnamedlarp** [studio-minus/ppg-bugs-and-requests#3504]
### Describe the bug

In lvl_train_machinist, if you walk past the machinist and shoot the engine thingy or whatever, it wont inflict any damage at all. You are able to shoot is as much as you want without it exploding, and it will only start registering your damage input after you kill the machinist. I am not sure if this is intended or not but its kind of stupid lol.

### Clearly describe how to reproduce the bug

Load the level, walk past the machinist without killing him and shoot the engine.

### Mod list

N/A

### Game version

MIR 0.49.4

### Operating System

Windows 11

### Additional notes

Here is a clip of the bug occuring: https://medal.tv/games/madness-interactive-reloaded/clips/iNXHrq6uP3dWCsLPU?invite=cr-MSxGUGosMTg5MzI0MTMzLA

**Comment by T1kva1** [comment]
stop posting Madness Combat issues! this is the People Playground forum

**Comment by kidnamedlarp** [comment]
uh mb i didnt read the forum name properly, but do you want me to repost this in the mir one?
