### ISSUE TITLE
Cpu Multi-Core Support

### ISSUE THREAD

**Issue by Ryan10123** [studio-minus/ppg-bugs-and-requests#3507]
### Feature description

I've been enjoying this game, but  I've been encountering some significant performance issues. When I try to rapidly place objects or people (Or do anything in the game that puts any kind of strain on my CPU), my game's performance takes a nosedive. Surprisingly, even though the game struggles to run above ten framsw-per-second, my CPU usage remains at only 20%, After some digging, I discovered that the game runs only on a single CPU core. This game would reap great benifits if it revieved an update that allowed it to use all of the CPU cores to it's benefit. 

### Feature purpose

This design flaw is limiting the game's potential. If the game could utilize multiple CPU cores to calculate physics, it's would massively improve performance. Addressing issue would not only enhance the gaming experience for many players but also potentially increase sales. The game's system requirements could possibly be lowered, while also bringing positive feedback from players who enjoy the enhanced performance of the game after the update. I hope you can consider updating the game to make it more efficient and enjoyable for everyone.

This issue is of great importance. I believe this isuue is urgent enough to justify its own game update.

### Additional context

Disclamer: I am unable to confirm nor deny the fact that this game runs only on one CPU core, as the program I  planned to use the check indivisual CPU core core usage (MSI Afterburner) has reset my graphics card fan settings, causing my GPU to overheat after a short period of time, crashing my PC. So, I do not currently can not use my PC (Without risking irreversible damage to my GPU), meaning I can not run any tests at the moment. The only reason I was able to record my overall CPU usage on one instance was because I used the AMD Adrenaline overlay (Which does not show individual core usage, just overall CPU usage) before I installed MSI Afterburner. Granted, I do not have first hand proof. I retrieved this information from the internet, meaning my sources could be outdated or outright incorrect. I will have a technician friend of mine work on my PC soon enough, but his schedule frequently full, meaning it may be a while before I can provide you with an update.

System Specifications:
GPU: Generic AMD RX 580 2048 (8GB VRAM)

CPU: AMD Ryzen 5 5600X

**Comment by Aspa102** [comment]
Uploading Unity_E0A0Px4Z3a.mp4…

current unity version game uses completely breaks physics if you enable multithreading
updating the game version caused the entire project to break when attempted

**Comment by Aspa102** [comment]
https://imgur.com/Bm9Qg53

the unity version this game runs on has completely broken multithreaded physics
updating the version went terribly wrong when it was attempted so it is likely not to be done

**Comment by Ryan10123** [comment]
I see, I don't know much about that but I'm assuming updating the unity
version would be a lot of work wouldn't it?

**Comment by Ryan10123** [comment]
Forget about my previous reply. I probably should have read your email more
thoroughly haha. Anyways, I'm sure you would agree that multicore physics
would be a great feature to have if it worked correctly, so for any
possible sequel/successor to people playground, I would definitely write
that down on your list of features to add. I understand why you say it
probably won't happen now because it would most likely require a full
recompilation of the game. Thank you for replying to my ticket and testing
out the idea, I can see you are just as passionate about gaming as I am 😋
