### ISSUE TITLE
Possible Mac port for the game?

### ISSUE THREAD

**Issue by ProfessorConfundus** [studio-minus/ppg-bugs-and-requests#351]
**Feature description**
Making a port of the game for Mac, since Mac has no equivalent to Proton.

**Feature purpose**
Allowing a wider audience of people (including myself, who can no long play the game due to myself switching to Mac) to play the game. Windows is natively supported, on linux, the game runs great under Proton, but on macOS, well, there's no option to play other than resource hungry virtual machines or the buggy and laggy Mac versions of Wine like PlayOnMac.

**Comment by mestiez** [comment]
No, I don't own a MacOS computer. This will unfortunately probably never be happening.

**Comment by Buggem** [comment]
> **Feature description** Making a port of the game for Mac, since Mac has no equivalent to Proton.
> 
> **Feature purpose** Allowing a wider audience of people (including myself, who can no long play the game due to myself switching to Mac) to play the game. Windows is natively supported, on linux, the game runs great under Proton, but on macOS, well, there's no option to play other than resource hungry virtual machines or the buggy and laggy Mac versions of Wine like PlayOnMac.

it did but then it mysteriously disappeared in this commit: https://github.com/ValveSoftware/Proton/commit/a84120449d8177fa40f3de729e55d238d3c24877


you could also just build from the old source code though. or not, as i think it was removed as part of the 32-bit banishment.
