### ISSUE TITLE
Highlight the vital spots in detailed view?

### ISSUE THREAD

**Issue by unknown-4o4** [studio-minus/ppg-bugs-and-requests#352]
**Feature description**
Just wondering maybe you could get the human vital spots to show when you go into detailed view? [S]

**Feature purpose**
Perhaps it could help let people know that it does exist and their exact positions. To which they can adjust body armor accordingly to the vital spots.

**Additional context**
A simple hitbox/outline like the ones you've provided in my previous request on vital spots implementation.

**Comment by TamasB14** [comment]
That is a good idea!

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/139529920-df5970ba-861f-4e10-b114-14f5b21ebf7f.png)
Ignore the numbers and yellow boxed. Isn't this a bit too crowded already? You can barely see the vital spots.

**Comment by Afavertov** [comment]
Why heart location so weird? Human cant be stabbed in heart from behind, and cant survive stab from front.

**Comment by mestiez** [comment]
> Why heart location so weird? Human cant be stabbed in heart from behind, and cant survive stab from front.

Stay on topic please

**Comment by TamasB14** [comment]
Maybe if there would be a differend detail view. One that shows healthbar of living things and status of living things(for example: Dead, Uncoscious), and another one that shows the rest such as Exploision radious, Vital parts.

**Comment by Cboyjet4** [comment]
> Maybe if there would be a differend detail view. One that shows healthbar of living things and status of living things(for example: Dead, Uncoscious), and another one that shows the rest such as Exploision radious, Vital parts.

Dude, just use the inspect element on the humans to see if they are dead or unconscious, it's as simple as pressing right click and scrolling for a few miliseconds, on the other hand, as said before I'm not a huge fan of more options and clutter to the game.

**Comment by unknown-4o4** [comment]
seems like the feedback is pretty mixed, not too sure either.

**Comment by TamasB14** [comment]
> > Maybe if there would be a differend detail view. One that shows healthbar of living things and status of living things(for example: Dead, Uncoscious), and another one that shows the rest such as Exploision radious, Vital parts.
> 
> Dude, just use the inspect element on the humans to see if they are dead or unconscious, it's as simple as pressing right click and scrolling for a few miliseconds, on the other hand, as said before I'm not a huge fan of more options and clutter to the game. IMO, The vital spots dont really need to be seen, I'm pretty sure everyone knows where someone's brain or heart is.

Dude, don't be like the elders who want to keep something in the same state! More options and more features are alot more fun than having a game using the same exact stuff. You'll get bored. + I'm pretty sure having new stuff just refreshens ya either.

**Comment by mestiez** [comment]
> Dude, don't be like the elders who want to keep something in the same state! More options and more features are alot more fun than having a game using the same exact stuff. You'll get bored. + I'm pretty sure having new stuff just refreshens ya either.

It's not about being against new features as a whole. They just don't want the game to become a convoluted mess because of seven thousand very specific and useless suggestions.

**Comment by mestiez** [comment]
Maybe something like this would be be better suited for an x-ray screen

**Comment by TamasB14** [comment]
> Maybe something like this would be be better suited for an x-ray screen

I'd be hyped for an X-Ray screen.

**Comment by unknown-4o4** [comment]
> Maybe something like this would be be better suited for an x-ray screen

Much better, I'm excited for it :D
