### ISSUE TITLE
Human copy-paste BRAIN DEPARTURE

### ISSUE THREAD

**Issue by raeganirwin** [studio-minus/ppg-bugs-and-requests#353]
Whenever you create a human, copy them, then paste them, their brain pastes outside of their head and can cause physics issues such as: broken necks, changed center of gravity, and in the worst cases the funny source engine ragdoll bug out where the body spasms everywhere.
![brain bug](https://user-images.githubusercontent.com/93420256/139521897-3054897f-4bf8-415b-b521-582d71544b50.png)

**Comment by raeganirwin** [comment]
GPU: gtx 960
CPU: Intel i7-6700k
Mods: I have some mods, but this has been a bug I've had since before I installed any.

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/139529661-c4cf1e8b-b39b-4001-af92-a472ccaebe81.png)
