### ISSUE TITLE
No Uploud button (Again)

### ISSUE THREAD

**Issue by Quickness19** [studio-minus/ppg-bugs-and-requests#355]
**Describe the bug**
I wanted to export the mod to the workshop, but I can't, because there is no Uploud button.

**Clearly describe how to reproduce the bug**
I wouldn't just write like that. All my mods can't be updated now. 
I have attached a json file

**Mod list**
mine

**System info (please complete the following information)**
System info (please complete the following information)
Operating system: Windows 10
Game version: 1.22 beta (64 bit)
GPU: NVIDIA Geforce GTX 1050 ti
CPU: intel core i3-7100 (4)

**Additional notes*
![139512473-28304779-f05b-496c-8a94-25933d89d7fd](https://user-images.githubusercontent.com/69407926/139530156-9787bc4b-afc9-45bc-81ab-ddd71a047d48.jpg)
*
![image](https://user-images.githubusercontent.com/69407926/139530172-ab62303a-0ba7-403f-bf4f-91d32689eb98.png)

**Comment by mestiez** [comment]
Good bug report :)

**Comment by mestiez** [comment]
Fixed
