### ISSUE TITLE
Heat is not damaging humans anymore/

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#356]
If there is 1000 ambient temperature, human will die from fire but not from heat.

Set temperature to 1000 degrees.

No

Operating system: win 10
Game version: 1.22 beta
GPU: 750 ti
CPU:Intel Core I3-3240 3.40 GHz

**Comment by Afavertov** [comment]
Even 1000 heating element doesnt deal damage to human.

**Comment by mestiez** [comment]
Fixed :)
