### ISSUE TITLE
Showerhead water interaction

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#359]
**Description**
When the showerhead liquid collides with water (as in water in the sea map etc.) it should dissolve inside it and get in any container nearby.

**Purpose**
Realism

**Comment by mestiez** [comment]
this would be cool but im afraid its a little cpu hungry

**Comment by mestiez** [comment]
this would totally be possible if i could access the scene from another thread without using the nightmare hell job system unity provides.

**Comment by EfeYks534** [comment]
The next time you make a game, don't forget to do it in your own engine
