### ISSUE TITLE
Ammo types.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#361]
Different ammo types that can be choosed trough context menu(HE(exploding like blaster shot or artillery if gun big enough), APHE(exploding after hitting and penetrating target), AP(better bullet penetration), incendiary(incendiary), JHP(worse penetration but much better damage for living organisms) and regular FMJ). There is arleady projectiles with special effects, so it will be not so hard to implement.

Fun, vehicles and realism.

**Comment by Afavertov** [comment]
I want to create heli with explosive autocannon like this https://www.youtube.com/watch?v=o3lybSntpSw
Or plane with HE minigun. https://www.youtube.com/watch?v=IMMGywAxBmg

**Comment by EfeYks534** [comment]
How about using other guns that do the same thing

**Comment by Afavertov** [comment]
Only guns with HE ammo is blasters, dissasembler, ion and laser detached cannon, so there is no regular firearm with specific ammo.

**Comment by skibdibbmdada** [comment]
This is a very good feature

**Comment by mestiez** [comment]
idk why this wasnt closed yetlol
