### ISSUE TITLE
Springs display normal when directional snapping

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#368]
**Describe the bug**
When trying to directionally snap a spring, it just looks like it normally would, until you let go, then it will jump to where it should be with the ALT directional snapping

**Clearly describe how to reproduce the bug**
Try connecting 2 objects using a spring, while holding ALT (Snap)

**Mod list**
None

This also happens with bandages

**Comment by mestiez** [comment]
fixed :)
