### ISSUE TITLE
British Bus

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#369]
**Feature description**
A UK bus that has more seats and a unique design.

**Feature purpose**
A new addition to vehicles and imo has a very unique good looking design. Also holds more passengers.

**Additional context**
![eb56007453701138044a95a789d98e07](https://user-images.githubusercontent.com/55041380/139560719-a9c021c8-9494-44ff-bd12-b072d201b3fc.jpg)

**Comment by TamasB14** [comment]
But it literally has the same purpose as the current bus. I can also just put two buses on eachother.

**Comment by atwal6400** [comment]
> But it literally has the same purpose as the current bus. I can also just put two buses on eachother.

the 1st bus would be messed up and the roof would bend in

**Comment by atwal6400** [comment]
> But it literally has the same purpose as the current bus. I can also just put two buses on eachother.

nooo the roof would be open, the window would be open, maybe theres a bus door that you can press f on, and the engine would be located on the bottom half.

**Comment by mestiez** [comment]
i don't really understand why this needs to be in the game

**Comment by vda8** [comment]
mods bro, mods.
