### ISSUE TITLE
Cars Exploding

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#370]
**Feature description**
Makes it so that cars are destructible like vulnerable to explosives. 

**Feature purpose**
Realism and it would be fun to blow up cars
**Additional context**
![3019361-poster-1280-car](https://user-images.githubusercontent.com/55041380/139561097-d7a1b1ae-9318-4c96-936b-7a6a06d2c448.jpg)

Inspired by GTA

**Comment by 404CoderNotFound** [comment]
Like almost all your other feature requests, **This already exists, if you do not play the game don't make feature requests.**

**Comment by mestiez** [comment]
Cars are destructible but it doesn't look that cool. Regardless, this feature request is vague.

**Comment by atwal6400** [comment]
> Like almost all your other feature requests, **This already exists, if you do not play the game don't make feature requests.**

doesnt exist at all

**Comment by atwal6400** [comment]
> Like almost all your other feature requests, **This already exists, if you do not play the game don't make feature requests.**

this only blows off the doors
