### ISSUE TITLE
Flies on dead bodies

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#371]
**Feature description**
Decomposed bodies have flies buzzing around them over time.

**Feature purpose**
Realism and it go's to show how long its been since you killed that person.

**Comment by fhgb54643689** [comment]
how in the fuck would flies be inside a completely contained box

**Comment by TamasB14** [comment]
It's not that bad actually. Flies effect at a 100% rotten body. Would be a perfect Halloween update.

**Comment by mestiez** [comment]
There are no flies

**Comment by atwal6400** [comment]
> how in the fuck would flies be inside a completely contained box

vents
