### ISSUE TITLE
Camera Shake

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#373]
**Feature description**
When theres an explosion your camera sways or shakes a bit or alot.

**Feature purpose**
So you can feel the impact of the explosives.

**Comment by idotwaffle** [comment]
this is already a thing...

**Comment by Cboyjet4** [comment]
Dude, have you even played the game? half of the suggestions you are making are outright dumb or already in the game.

**Comment by atwal6400** [comment]
> this is already a thing...

my b bru
