### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by FatherHaggis** [studio-minus/ppg-bugs-and-requests#374]
Make it so that the battery can store a charge of energy

**Comment by TamasB14** [comment]
We need this for sure! Accumulator is not a Generator too. Instead accumulator and battery should be something that can be charged with electricity through generators and anything that produces electricity.

**Comment by mestiez** [comment]
Their name doesn't really describe their function. They are intended as weak sources of power, not actual accumulators.
