### ISSUE TITLE
center of mass incorrect on objects spawned with q

### ISSUE THREAD

**Issue by somepurplekale** [studio-minus/ppg-bugs-and-requests#375]
**Describe the bug**
the center of mass is displayed incorrectly on objects spawned with q. the center of mass seems to be correct on objects spawned with e.

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
choose an object (minigun and ak47 both have this problem)
spawn the object with both e and q
check each object in detail view

video:
https://www.youtube.com/watch?v=6KSbuwg5Wu4

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
active: 
flipping heck
greenhammer
photo mode
controllable anti-air cannon
the steampunker
combat weapons pack v3.0

inactive:
the greenbrick mod
depletable engines

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.20
 - GPU: RX 560X
 - CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 2.10 GHz

**Additional notes**

**Comment by mestiez** [comment]
fixed :)
