### ISSUE TITLE
rework for guns/ballistics at high speeds

### ISSUE THREAD

**Issue by somepurplekale** [studio-minus/ppg-bugs-and-requests#376]
**Feature description**
rework guns so that they don't hit the plane they're mounted on at high speeds

**Feature purpose**
planes with guns frequently get hit by their own bullets, with or without tracers. implementing this change would vastly improve planes and dogfights. I personally wouldn't mind if only the hitscan mode were fixed (if fixing tracers isn't worth the effort).

**Additional context**
video of the problem: https://www.youtube.com/watch?v=_qki66qF4Zw

**Comment by mestiez** [comment]
This happens because the bullet leaves the barrel at a set speed, without considering its current speed.

**Comment by mestiez** [comment]
It works better now but I have disabled the _bullets going as fast as the gun_ part because it's causing some strange (but expected) behaviour

**Comment by somepurplekale** [comment]
thank you, especially for the quick update :)
