### ISSUE TITLE
Universal Autocannon

### ISSUE THREAD

**Issue by somepurplekale** [studio-minus/ppg-bugs-and-requests#378]
**Feature description**
A new gun called "Autocannon" with multiple parameters such as caliber, ammo type (ap, he, aphe), explosive mass, gun type (normal, large machine gun type tracers, physical shells), fire rate, velocity, accuracy, damage multiplier, penetration multiplier, etc. The sprite changes into smaller or bigger versions of itself depending on the caliber (nothing crazy, only if the size of the bullet gets much larger than the visual size of the barrel). A button called "parameters" in the context menu opens a larger menu with all of these variables.

**Feature purpose**
The game doesn't have a 20mm autocannon that fires explosive shells. It has a bunch of other unfilled niches, like an artillery cannon, anti tank gun, 30mm autocannon, detached tank cannon with physical rounds, etc. Adding this gun would fill all of these roles without the need for a new gun every time. I've built multiple planes and feel that they'd be much more satisfying if they used light cannons rather than the machine guns we have now.

**Additional context**
a 20mm cannon that I think looks good
https://www.lonesentry.com/articles/ttt/pics/german-mg151-aircraft-cannon.jpg 

shooting a plane in game with machine guns (being able to blow them apart instead would be amazing)
https://www.youtube.com/watch?v=C8kC-8OEG3g

**Comment by mestiez** [comment]
this is basically a combination of #361 and #360
