### ISSUE TITLE
BURNING / FOLLOW UP

### ISSUE THREAD

**Issue by beanssssse** [studio-minus/ppg-bugs-and-requests#383]
**Feature description**
I was the creator of the original burning post, the additions are cool and work but the time until the burning effects(the black) are too quick, could this possibly be slower?

**Feature purpose**
Finish of the burning, now that the right speed for the burning is set the burning of the skin addition being slower would be cool and top it off
**Additional context**
n/a

**Comment by beanssssse** [comment]
nvm its ok

**Comment by mestiez** [comment]
Please don't make the title full caps super vague stuff next time
