### ISSUE TITLE
Left Facing gun going crazy

### ISSUE THREAD

**Issue by MountainDog24** [studio-minus/ppg-bugs-and-requests#385]
**Describe the bug**
Guns spawn with insane inaccuracy (I pull the trigger and somebody behind the barrel gets headshotted, or point blank range barrel to the head and it hits the neighbors dog somehow.) 
**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
If I spawn a gun and it is facing left the gun gets the bug
**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
Quick Right Click options
Blocksify's Mafia Mod
Flipping heck
The Ultimate Minecraft Mod
Mulligan
Taser
Explosive mod
Skittle's syringe mod
Vietnam Soldiers mod
John Wick mod
Sorers NPC Pack
**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version:1.22 beta
 - GPU:Nvidia GeForce RTX 2060
 - CPU:AMD Ryzen 5 3600 6-Core Processor

**Additional notes**
![Bad Gun](https://user-images.githubusercontent.com/93484560/139593418-064a0d3e-722a-4303-8214-4c96b9188ee6.PNG)

I don't know if the image is working or not, since I've never used GitHub before, but if it is, you can clearly see the bullet going to who the hell knows where even though the gun is giving my man a kiss.

**Comment by UniDuki** [comment]
I can't make this happen for me. It is probably one of your mods not playing well with the 1.22 beta.

**Comment by mestiez** [comment]
oh yeah i know why this happens

**Comment by mestiez** [comment]
Fixed
