### ISSUE TITLE
30mm cannon round should disappear or be weakened after impact.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#389]
Projectile not destroying after hitting target and exploding.

Shoot something with 30mm cannon.

No

Operating system: win 10
Game version: 1.22 beta
GPU: 750 ti
CPU:Intel Core I3-3240 3.40 GHz

**Comment by Afavertov** [comment]
![изображение](https://user-images.githubusercontent.com/89081329/139598950-156ddb57-7567-4a27-9e49-6c73bd5941c3.png)

**Comment by Afavertov** [comment]
Or made round weaker after explosion.

**Comment by mestiez** [comment]
This isn't a bug. The round explodes once and then continues on.

**Comment by TamasB14** [comment]
A good explanation:
High Explosive AntiTank Rounds (HEAT)
It produces literally the same thing! Explodes on impact and the fuse continues to go on. I think it's just perfect. Altought I'd add the description "Shots HEAT rounds" to prevent any misunderstanding.

**Comment by TamasB14** [comment]
![image](https://user-images.githubusercontent.com/26002677/139602173-456d0a16-ec3d-4548-8bd8-2c97087fc5dc.png)

**Comment by Afavertov** [comment]
I now about HEAT, but at this moment in ppg after explosion round have same armor piercing and can penetrate wall or tank.

**Comment by TamasB14** [comment]
> I now about HEAT, but at this moment in ppg after explosion round have same armor piercing and can penetrate wall or tank.

Oh well... HEAT rounds most of the time damage things even if it's fuse did not directly hit a tank. The force the projectile gets from the exploision and the velocity can be strong enough to even penetrate two light-armoured vehicles.

**Comment by Afavertov** [comment]
I think it cant penetrate bunker.
![изображение](https://user-images.githubusercontent.com/89081329/139603153-a1e30fca-80ec-4f85-9d6c-bf9f94c3f053.png)

**Comment by Afavertov** [comment]
It just should be renamed and round should be a little weaker after explosion.

**Comment by Afavertov** [comment]
Forget it, this gun is fun.
