### ISSUE TITLE
30mm cannon barrel explosion is too big.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#390]
When 30mm cannon shoot, it can destroy electronic behind it.

Fire with cannon when electronic nearby.

No

Operating system: win 10
Game version: 1.22 beta
GPU: 750 ti
CPU:Intel Core I3-3240 3.40 GHz

![изображение](https://user-images.githubusercontent.com/89081329/139599050-53384e9f-9f36-4185-8b7e-bd63628945f2.png)

**Comment by mestiez** [comment]
this whole thing is annoying anyway... why does it destroy electronics?

**Comment by mestiez** [comment]
this isnt really a bug, more like a feature request

**Comment by TamasB14** [comment]
> this whole thing is annoying anyway... why does it destroy electronics?

Most cannons do destroy electronics. As I checked it's mainly because of the recoil. The gun transfers the recoil to the nearby objects.
