### ISSUE TITLE
30mm cannon sound.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#391]
There is strange click sound after main autocannon sound.

Shoot couple times and wait.

No.

Operating system: win 10
Game version: 1.22 beta
GPU: 750 ti
CPU:Intel Core I3-3240 3.40 GHz

**Comment by mestiez** [comment]
Yeah I noticed the annoying clicking noise. I had to upload the build anyway because of some urgent bug fixes.

**Comment by mestiez** [comment]
Fixed

**Comment by Afavertov** [comment]
Shit, i really hate this sound, when fix will be realised?
