### ISSUE TITLE
Gun accuracy is terrible

### ISSUE THREAD

**Issue by HelpMeNowThanks** [studio-minus/ppg-bugs-and-requests#394]
**Describe the bug**
If you spawn the gun reversed (A.K.A pressing q), the bullets go all over the place, including backwards, 90 degrees both ways, etc.

**Clearly describe how to reproduce the bug**
Take a gun (ex. AK-47) and spawn it with *Q*, then just shoot.

**Mod list**
Quality of Life Items
Items plus
Stungun **(ACTIVE)**
Gas warfare mod
Configurable Explosives

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22 Beta
 - GPU: NVidia Gtx 1030
 - CPU: Intel Core i3 (don’t know the numbers)

**Additional notes**

**Comment by idotwaffle** [comment]
how are there 4 of the exact same bug reports lmao
#394, #388, #384 and #385

**Comment by Afavertov** [comment]
You at beta 4?
