### ISSUE TITLE
Turning off the lamps on the map and the flashlight does not work

### ISSUE THREAD

**Issue by arthurueban** [studio-minus/ppg-bugs-and-requests#397]
![image](https://user-images.githubusercontent.com/93498048/139607685-2ed2969f-4f1d-4594-9ae4-2edea4c338de.png)

**Comment by fhgb54643689** [comment]
**use the template**

**Comment by Afavertov** [comment]
Enable this option.
![изображение](https://user-images.githubusercontent.com/89081329/139608149-1fb4c4ab-a491-4743-86a1-59fce43f1a52.png)
****

**Comment by Afavertov** [comment]
Enable this option.
![изображение](https://user-images.githubusercontent.com/89081329/139608173-dd7687a0-2c39-4efb-9f56-5727b9ca78eb.png)
