### ISSUE TITLE
physical bullets come out of the guns

### ISSUE THREAD

**Issue by bluewoods64** [studio-minus/ppg-bugs-and-requests#400]
i think it'd be pretty cool if you could actually see a physical bullet while you are in 1% slow mo, but its just a yellow line that cant be interacted with. this is probably a pretty stupid request but im just gonna post it anyway

**Comment by MaxeUA** [comment]
How do you imagine this in-game? Stupid suggestion

**Comment by TamasB14** [comment]
I think I read something somewhere about it. They don't want to add this.

**Comment by mestiez** [comment]
:D Please follow the template next time.

**Comment by vda8** [comment]
what the.

**Comment by bluewoods64** [comment]
> what the.

why are you replying to a 4 month old suggestion. its rejected and doesn’t matter

**Comment by vda8** [comment]
> > what the.
> 
> why are you replying to a 4 month old suggestion. its rejected and doesn’t matter lol

idk i was bored
