### ISSUE TITLE
Whenever a human runs out of oxygen make him sink to the bottom of the water.

### ISSUE THREAD

**Issue by apidimus** [studio-minus/ppg-bugs-and-requests#404]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by mestiez** [comment]
Please follow the template.
