### ISSUE TITLE
Android Nitroglycerin bug

### ISSUE THREAD

**Issue by Alexthebug** [studio-minus/ppg-bugs-and-requests#405]
**Describe the bug**
when androids are filled with nitro and you blow them up, parts of them don't have collision anything, and have weight issues.

**Clearly describe how to reproduce the bug**
fill an android with nitro and blow it up

**Mod list**
none

**System info (please complete the following information)**
 - Operating system: 
 - Game version:1.22 beta 8
 - GPU:
 - CPU:

**Additional notes**

**Comment by mestiez** [comment]
Fixed :)
