### ISSUE TITLE
Bottle/ Glass Coffee Table

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#409]
**Feature description**
Destructible bottle. Glass tabletop counter.

**Feature purpose**
Addition to destructible items, can be used for scenarios. Can be used for scenery, or RP.

**Additional Context**
I was only going to do Bottle but I figured it was too short so I did 2.

**Comment by mestiez** [comment]
Half accepted ages ago i  guess
