### ISSUE TITLE
Oxygen/Blood/Circulatory Rework, Volume no2

### ISSUE THREAD

**Issue by Cboyjet4** [studio-minus/ppg-bugs-and-requests#412]
**Feature description**.

**This is a MASSIVE suggestion, feature wise and READ wise!!! I've spent the last hour or so rewriting my original draft (because I lost it) sorry if I have any shoddy spelling or bad grammar in some areas.**

Whew, It's been a long time since I've dug this up, this suggestion MAY be outdated due to the recent health updates, if so I apologize for that, the suggestion was written all the way back in may, and originally intended for the discord server, so I've decided since the update has come out, now's a good time to finally post my suggestion, it's pretty big, and I'm not really sure if most of this already exists, so if I'm suggesting something that already partially exists, that's probably my fault lmao, anyways.

For this suggestion, I've partially reworked the oxygen and partially the blood system, the two things I've never really like in game, they're pretty wonky from my testing and experience.

Basically, the oxygen system (_FROM MY EXPERIENCE_) works on a "breathing" basis, instead of "blood oxygen" basis, oxygen is lost slowly overtime after death, and oxygen can be lost based on what bodypart is hit. For example, if someone is hit in the chest with a piercing weapon, they lose oxygen quicker than a "regular death", same for the head, except they lose oxygen near instantly. 
This system is a bit strange for a few reasons, 1. humans lose integrity immediately after oxygen runs out, which is usually slower when humans die "regularly", but as I've said above, they instantly lose oxygen during those two events. 2. is that it's based on a "lung oxygen" basis rather than a "blood oxygen" as I've said before, if you don't get what I'm saying, oxygen is usually stored in the blood, lungs put oxygen into blood, that's their purpose, with this system, oxygen is only really "lung based" and is lost based on how much air is "expelled" from the lungs, this could have a probably easy "fix" but since I'm a nerd, and enjoy complex health systems, I'm making this suggestion.

**Lung System**

**First off**, for this system lungs have a state, breathing, not breathing, pretty simple. **2nd off**, lungs put oxygen into blood itself, so the oxygen level is purely based off of IF the human is breathing. **3rd off**, oxygen is used up depending on how blood is circulating around the body.
So if someone is shot in the in shot in the lungs, state goes to not breathing, they die, they stop breathing.

A "simplified" explanation would be this 

Lung state **=** breathing > blood oxygen goes up. > Blood pressure circulates that oxygen and uses it around the body, which gives "supply" to limbs and keeps their "health" up, which I'll get into later.

Now lets do the opposite.
Lung state **=** not breathing > blood oxygen is eaten based on if blood is circulating > limbs get no oxygen and die.

Now, for the limb health, In my opinion limb health should be eaten up slowly AFTER blood oxygen fully depletes, obviously, maybe a rate after 30 seconds integrity should start being lost??? maybe it'd only lose integrity fully after around a minute or two.

(As well as the brain, maybe humans would lose consciousness around 10 seconds after blood oxygen depletes?) 

(Side notes)
(Possibly oxygen shouldn't deplete for around 15 seconds after the non breathing state happens? obviously they'd still have air in their lungs. and obviously they'd stay conscious.)
(Along that, oxygen should be lost based on how fast blood is being sent around the body, so usually 45 seconds for a normal heartrate, which is usually 60 BPM across most humans. so a person with a higher heartrate would lose oxygen at a MUCH faster rate than a person with a slow one, as I've said before)

**Heart system**

First off, the heart now can change BPM based on a "stack" system I've come up with.

The heart now has 6 levels, the heartrate changes how fast it "beats" based on those levels, the lower it is, the slower the heart "beats", the higher it is, the higher the heart "beats.

Second off, Blood pressure is now a non constant, and is controlled by the heart.

Lets say the regular heartrate for a PPG human is a level 3, 60 BPM or 110/80 mmHg (Also known as blood pressure), (or 100% blood pressure in PPG), blood pressure slowly shifts how much it is based on how fast the heart beats, let's say the heart switches from a level 3, to level 4, or 80 BPM the blood pressure should slowly rise to about 120/80 mmHg (maybe around 120% blood pressure in numbers?), level 5, 150 BPM could be 130/80 mmHg (or around 130%, also called hypertension, you get the gist, lower than 3 would decrease the blood pressure more, because I'm too lazy to do any more math with this.)
(Side note)
(Visually, in my opinion, on heart rate monitors and the inspect element, heartrate should slowly increase, and not be a sudden jump when levels change, obviously.)

3rd off, in this system, the heart is controlled differently than the regular system, and works differently as well, obviously.
Let's say the brain controls the heart and how it beats.

Let's say someone with this is shot in the head, the brain is no longer controlling the heart, but the heart doesn't immediately stop.
Realistically, the heart kind of "freaks out" a little and starts to beat faster until it cant anymore, since it has no input from the brain, as there's not a brain to control the heart anymore.
(_Low blood oxygen levels should cause this as well, as the heart itself is getting no oxygen and is beating faster to try to sustain itself_)

Example of this could possibly be: Shoot someone in the head > heart "levels" rises to around level 5 and blood pressure steadily increases. > heart stops.

Now, shooting someone in the heart is a bit different than shooting someone in the head, lets say the heart is destroyed in this scenario, obviously the heart stops beating instantly of course, and blood pressure steadily decreases.
Example of this obviously is > Shoot someone in heart vital spot > heart stops > blood pressure decreases and goes to zero.
(Side notes)
(As I've mentioned before, blood pressure should not be a constant, but sorta a "flow", as in travels at a sort of "speed" and **slowly** increases based on what rate the heart is beating.

Combining these two features, you've got a "revamped" blood system, this is really all I can remember/think of, so here's some other notes.
(What if oxygen is stored as a "value" in blood? like my older suggestion, running a blood vessel through an arm with a health human would keep that limb "alive" because it has oxygen)
(I'd also appreciate it if the human inspect element was changed to view both the proper blood pressure and the heartrate.)

_**Alright, here's a simplified explanation, for recollection and simpflication obviously.**_ 

Breathing has 2 states, breathing and not breathing, breathing raises blood oxygen and not breathing does not, and eventually lowers it.

Blood oxygen is a value in the blood raised by breathing, blood oxygen is used up faster when the heart is beating faster, also known as higher blood pressure, when blood oxygen reaches super low levels or 0, limb integrity starts to decrease after a while.

Heart has 5 states, 1 to 5, higher heartrate, higher blood pressure, when the heart stops, the state is 0. and blood pressure stops.

Blood pressure is a "flow" maintained by the heart, based on how fast it beats, as I said before, lower heartrate, lower blood pressure, higher heartrate, higher blood pressure.

**Feature purpose**
Physically accurate blood and heart system, replacing the old system with a (huge) fresh and new one, that's accurate to how humans actually breathe and such.

Along with that, this could open up TONS of more possibilities for medical items and medical gameplay, personally, I love games which allow you to do stuff like stitching people back together, saving people from the brink of death, ETC.

An example could be a ventilator item you stick on someone's chest or mouth, an item that would force humans to breathe and such.
Maybe even a blood pumper object, something like that could increase blood pressure without the need for restarting the heart, if you ever would need that.
Items such as the defibrillator would actually restart a physical heart as well, so there's that
(side notes)
(What effect would this have on the water breathing syringe, would it increase blood oxygen? or just make people able to breathe underwater)

**Additional context**
_Here's a quick 'diagram' of the system_
![image](https://user-images.githubusercontent.com/71295203/139789333-49283710-d13b-4b38-a753-62c7345aecb5.png)
_Example image of what the inspect element could look like. (mind the incorrect fonts, had to remake the old image and was too lazy to find the original fonts, lol.)_
![image](https://user-images.githubusercontent.com/71295203/139789594-0876df75-a84b-4346-a06c-3111211c42d1.png)

**Comment by Afavertov** [comment]
My PC saying no.

**Comment by Afavertov** [comment]
My PC saying no.

**Comment by Cboyjet4** [comment]
> My PC saying no.

not sure if this will effect performance at all lol, it's literally just numbers, maybe slightly?

**Comment by NirronCD** [comment]
Since i start to play this game, in 2020, i've been thinking about how the health system can be improved, and you made a awesome rework of that system, good job, i completely agree but gonna be hard to code it

**Comment by Cboyjet4** [comment]
> Since i start to play this game, in 2020, i've been thinking about how the health system can be improved, and you made a awesome rework of that system, good job, i completely agree but gonna be hard to code it edit: health system like the game rimworld, would be cool too

Meh, the game probably isn't even built for a system like rimworld's, rimworld's is injury based and doesn't really fit in a 2D sandbox, as for the coding part, I'm not sure how hard it'll be to code, leave that to zooi.

**Comment by NirronCD** [comment]
> > Since i start to play this game, in 2020, i've been thinking about how the health system can be improved, and you made a awesome rework of that system, good job, i completely agree but gonna be hard to code it edit: health system like the game rimworld, would be cool too
> 
> Meh, the game probably isn't even built for a system like rimworld's, rimworld's is injury based and doesn't really fit in a 2D sandbox, as for the coding part, I'm not sure how hard it'll be to code, leave that to zooi.

yea, you're right, rimworld is a totally different game, but good job anyways.

**Comment by Cboyjet4** [comment]
Going back to this, this is a writing mess of mine, I shouldn't have made this so long, I could've simplified it easily lol.

**Comment by Cboyjet4** [comment]
Issue closed, if I do this again I'll simplify it.

**Comment by Cboyjet4** [comment]
Closed, this is a massive mess I wrote when I didn't know how to english.
