### ISSUE TITLE
Water liquid.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#413]
Liquid that have no effect to human and extinguish fire, decrease temperature of items and clean items.

Fun and realism.

**Comment by TamasB14** [comment]
Whole new liquid system, or just something like a water bucket pouring out water like a shower head?

**Comment by Afavertov** [comment]
Just liquid.

**Comment by Cboyjet4** [comment]
> Just liquid.

what do you mean

**Comment by Afavertov** [comment]
![изображение](https://user-images.githubusercontent.com/89081329/139909498-84473e16-e273-47b5-acac-55784119723e.png)

**Comment by Afavertov** [comment]
![изображение](https://user-images.githubusercontent.com/89081329/139909628-b555cc74-aa67-47f6-8a00-74a18105a998.png)

**Comment by Cboyjet4** [comment]
phrase your suggestions better lol
