### ISSUE TITLE
Bandaged wound still show as bleeding in inspect menu.

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#414]
Bandaged wounds still show as bleeding in inspect menu.

Stab human, bandage him and use inspect.

No

Operating system: win 10
Game version: 1.22 
GPU: 750 ti
CPU:Intel Core I3-3240 3.40 GHz
![изображение](https://user-images.githubusercontent.com/89081329/139923065-2c05c7f8-5661-4860-bc55-3343babfd492.png)

**Comment by TamasB14** [comment]
After you bandage your wound, you're still going to bleed. Now my other question is... Will it still show bleeding if you wait a bit too?

**Comment by mestiez** [comment]
It would disappear after quite a while. I've decreased the threshold so that it no longer displays "bleeding" unless it's visible.
