### ISSUE TITLE
Flipping heck + expanded gore brain glitch

### ISSUE THREAD

**Issue by bluewoods64** [studio-minus/ppg-bugs-and-requests#420]
**Describe the bug**
First of all, this is an issue with the mod. If thats not something that can be fixed then I guess just ignore this. Whenever you enable expanded gore and flip a human around, their brain goes completely away from the body and the neck snaps.

**Clearly describe how to reproduce the bug**
1. Make sure expanded gore is on
2. spawn a human
3. flip them around using flipping heck mod.
4. brain will go bonkers

**Additional notes*
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7464810/exported.game.debug.info.md)

**Comment by Cboyjet4** [comment]
expanded gore is unsupported + it's a mod.

**Comment by atwal6400** [comment]
> expanded gore is unsupported + flipping heck is a mod.

well i mean its made by the dev

**Comment by mestiez** [comment]
This isn't for any mods, not even mine, and I will probably never pay attention to expanded gore again.

**Comment by bluewoods64** [comment]
> expanded gore is unsupported + flipping heck is a mod.

it's made by zooi, that's why i mentioned it. not to mention almost everyone uses it.
