### ISSUE TITLE
Fire has collision

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#424]
**Feature description**
Fire actually collides with the physical world.

**Feature purpose**
Realism and kind of weird that fire just goes through the world.

**Additional context**
![20211103154710_1](https://user-images.githubusercontent.com/55041380/140219820-6c0d7017-38d5-4576-9279-cc734d7c3926.jpg)

pretend that the wood is fire

**Comment by unknown-4o4** [comment]
awkward
