### ISSUE TITLE
Prosthetic Limbs

### ISSUE THREAD

**Issue by bluewoods64** [studio-minus/ppg-bugs-and-requests#425]
**Feature description**
A plastic/metal leg or arm that automatically snaps to a missing limb.

**Feature purpose**
It would be cool for building a hospital, curing a human, and various other creative things.

**Additional context**
Nothing else

**Comment by Afavertov** [comment]
Made it by yourself.

**Comment by Cboyjet4** [comment]
> Made it by yourself.

???????????????????????????

Also, duplicate of #254 https://github.com/studio-minus/ppg-bugs-and-requests/issues/254

**Comment by bluewoods64** [comment]
> Made it by yourself.

wdym make it by myself? i can't code. this is literally a feature request page, i am requesting a useful feature.

**Comment by bluewoods64** [comment]
> > Made it by yourself.
> 
> ???????????????????????????
> 
> Also, duplicate of #254

well it seems like zooi didnt notice it so i'll just say it again

**Comment by mestiez** [comment]
> > > Made it by yourself.
> > 
> > 
> > ???????????????????????????
> > Also, duplicate of #254
> 
> well it seems like zooi didnt notice it so i'll just say it again

That isn't how the issue board works. There shouldn't be any duplicates, whether you think I noticed or not.
