### ISSUE TITLE
Spleen

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#426]
**Feature description**
New vital organ located near the chest.

**Feature purpose**
Another way to cause internal bleeding.

**Additional context**
![TvvHpLV6RcPa3Y7PAcYLBi](https://user-images.githubusercontent.com/55041380/140227245-97710c2c-0326-4639-b882-0bcf36713b86.jpg)

"What happens when your spleen bursts?
A ruptured spleen (a fist-sized organ located in the left upper abdomen) occurs when the surface of this organ is injured, which can lead to internal bleeding. Symptoms include pain in the abdomen and nausea. A ruptured spleen is treated with surgery if the patient has lost a large amount of blood."

**Comment by bluewoods64** [comment]
I feel like this would be too difficult to implement into a 2d body

**Comment by atwal6400** [comment]
> I feel like this would be too difficult to implement into a 2d body

i feel like the placement would be perfect like in between the upper and middle chest

**Comment by idotwaffle** [comment]
but how would you damage the spleen? if just hit it hard then that'll cause internal bleeding, spleen or no spleen

**Comment by atwal6400** [comment]
> but how would you damage the spleen? if just hit it hard then that'll cause internal bleeding, spleen or no spleen

ik but it could also be another way of fast blood loss.

**Comment by mestiez** [comment]
Any injury can cause internal bleeding. This would add nothing.
