### ISSUE TITLE
New Set Object Temperature has no limit

### ISSUE THREAD

**Issue by bluewoods64** [studio-minus/ppg-bugs-and-requests#427]
**Describe the bug**
I'm not sure if this is considered a bug or a feature request, but it should probably have a limit. I set the human's temperature to about 6 billion and when I inspect it actually shows it. I feel it should have some limit.

**Clearly describe how to reproduce the bug**
1. get human
2. set temperature to something crazy
3. inspect human
4. big number

**Mod list**
not necessary

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22
 - GPU: Integrated intel 530
 - CPU: i7 6700

**Additional notes**
sorry if this is a waste of your time

**Comment by Afavertov** [comment]
Thats fun.

**Comment by bluewoods64** [comment]
nvm this isn't that bad leave it in
