### ISSUE TITLE
Question (repost because its closed now because i made a mistake)

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#428]
What will happen to feature requests that don't get "accepted feature" or "rejected feature."

note: ik im not following the template but its just a question we might not get an answer to.

**Comment by bluewoods64** [comment]
I think they're just ignored, which is sad because I've seen many good ones that weren't even labeled. I might be wrong but it seems like they're just ignored.

**Comment by atwal6400** [comment]
> I think they're just ignored, which is sad because I've seen many good ones that weren't even labeled. I might be wrong but it seems like they're just ignored.

if that's the case, that's kinda disappoint

**Comment by CUBE0R** [comment]
zooi's gonna respond to anything they are somewhat interested in, or want to question or close. If zooi responds, there is probably a decent chance its being considered if its not to be told why its being closed or whatever.
