### ISSUE TITLE
SPAS 12

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#429]
**Feature description**
Fully auto shotgun.

**Feature purpose**
This is diff from the normal one because it's fully automatic, and ik you can just spam click the shotgun but this is for people that want realistic gun fights.

![SPAS_12_Classic](https://user-images.githubusercontent.com/55041380/140237450-dfe6afc5-1bb8-401e-b6fd-25290d198a60.png)

**Comment by bluewoods64** [comment]
you could probably ask a modder and they could maybe make it for you

**Comment by atwal6400** [comment]
> you could probably ask a modder and they could maybe make it for you

Just the gun on its own? Also I don't have any form of communication with any types of modders nor if I request one to them it will probably decline it.

**Comment by BBQGiraffe** [comment]
learn C# and read the modding wiki

**Comment by Afavertov** [comment]
AA12 is better for auto shotgun.
