### ISSUE TITLE
M1911

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#431]
**Feature description**
New Colt manufactured pistol that holds 7 rounds.

**Feature purpose**
I know this sounds the same as all the other pistols but this one is different in damage. Would be way more powerful that the 9mm and Pistol, idk about the Revolver though, but it would probably hold a lot of damage that's why it would be different from all the other pistols.

**Additional context**
![download](https://user-images.githubusercontent.com/55041380/140237690-7e9ce1c6-bf6d-4031-a1f9-a4e6c6cfde63.jpg)

**Comment by atwal6400** [comment]
waffle why do you hate me bro

**Comment by EfeYks534** [comment]
It's probably because you keep spamming feature requests

**Comment by atwal6400** [comment]
> It's probably because you keep spamming feature requests

ik but its mad annoying
