### ISSUE TITLE
Hook

### ISSUE THREAD

**Issue by bluewoods64** [studio-minus/ppg-bugs-and-requests#432]
**Feature description**
Metal hook for hanging people (or really anything that can be poked.) I think this would be pretty cool for some horror scene.

**Feature purpose**
Just another cool addition to the game. Hook someone by the head.

**Additional context**
The picture below is from a modpack that for some reason the hook doesn't work
![Screenshot 2021-11-03 214911](https://user-images.githubusercontent.com/93502259/140249736-540153aa-1b9d-4514-a700-80383192e9e5.png)
.

**Comment by UniDuki** [comment]
#272

**Comment by atwal6400** [comment]
> **Feature description** Metal hook for hanging people (or really anything that can be poked.) I think this would be pretty cool for some horror scene.
> 
> **Feature purpose** Just another cool addition to the game. Hook someone by the head.
> 
> **Additional context** The picture below is from a modpack that for some reason the hook doesn't work ![Screenshot 2021-11-03 214911](https://user-images.githubusercontent.com/93502259/140249736-540153aa-1b9d-4514-a700-80383192e9e5.png) .

zooi thinks its creepy

**Comment by bluewoods64** [comment]
> > **Feature description** Metal hook for hanging people (or really anything that can be poked.) I think this would be pretty cool for some horror scene.
> > **Feature purpose** Just another cool addition to the game. Hook someone by the head.
> > **Additional context** The picture below is from a modpack that for some reason the hook doesn't work ![Screenshot 2021-11-03 214911](https://user-images.githubusercontent.com/93502259/140249736-540153aa-1b9d-4514-a700-80383192e9e5.png) .
> 
> zooi thinks its creepy

well, yeah. thats kinda the whole point..

**Comment by bluewoods64** [comment]
> #272

nvm sorry didnt see that
