### ISSUE TITLE
Map Loading issue

### ISSUE THREAD

**Issue by ath0rus** [studio-minus/ppg-bugs-and-requests#434]
**Describe the bug**
Maps are not loading correctly and it seems that multiple are merged into one

**Clearly describe how to reproduce the bug**
Launch the game, and load a map (i use Alt + F4 to exit the game)

**Mod list**
Hydrolic Pistons by sneby

**System info (please complete the following information)**
 - Operating system: WIndows 10 21H1
 - Game version: 1.22 (64-bit)
 - GPU: GTX 1660s
 - CPU: i7 10700

**Additional notes**

**Comment by bluewoods64** [comment]
do you have a video of it
