### ISSUE TITLE
Working transplantation

### ISSUE THREAD

**Issue by Whiskey-Bravo** [studio-minus/ppg-bugs-and-requests#435]
**Feature description**
I would really like to have a workin transplantation because right now you can connect the the limbs together but they will not be able to live unless they have a live syringe connected in someway. I want to be able to amputate limbs and connect them to another human and have it working or atleast semi working.

**Feature purpose**
I wanted to request this because i got frustrated several times when trying to transplantation a limp and connect it back together and it still dying.

**Comment by mestiez** [comment]
Did you mean "working transplantation"? Because amputation is definitely working.

**Comment by TamasB14** [comment]
> Did you mean "working transplantation"? Because amputation is definitely working.

Pretty sure he means transplantation.

**Comment by TamasB14** [comment]
Actually, I tried doing transplantations a while back using the "blood wire" between two detached limbs. Do you think it'd be possible making the blood wires work that way?

**Comment by CommanderKrieger** [comment]
> Did you mean "working transplantation"? Because amputation is definitely working.

Yep edited It because like you said I meant transplantation
