### ISSUE TITLE
Infrared Thermometer uses Fahrenheit but with Celsius cap

### ISSUE THREAD

**Issue by SalreixVonOtsuu** [studio-minus/ppg-bugs-and-requests#436]
**Describe the bug**
I set my temperature unit to Fahrenheit, and while a regular Thermometer at its lowest temperature will display -459 properly, an Infrared Thermometer can only go as low as -273, but once the Thermometer temperature goes below -273 Fahrenheit, the Infrared Thermometer will display the same value.

**Clearly describe how to reproduce the bug**
Set temperature unit to Fahrenheit, get a Thermometer and it's counterpart, set the Thermometers temperature to -459 or higher, and place the Infrared Thermometer such that its ray touches the Thermometer. (Also, IT seems to not be synced with T, its generally off by 1 degree for a moment while temp is changing)

**Mod list**
-A Handful of Weird Syringes by Personman65 (Inactive)
-Object Editor by Morzzic (Active)
-Raw Pink Liquids by davidco7777 (Active)

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22
 - GPU: don't know
 - CPU: don't know

**Comment by bluewoods64** [comment]
you can check your cpu and gpu in task manager

**Comment by SalreixVonOtsuu** [comment]
idk how

**Comment by mestiez** [comment]
Fixed :)
