### ISSUE TITLE
assetbundle loading for the modding api

### ISSUE THREAD

**Issue by TalonZane** [studio-minus/ppg-bugs-and-requests#437]
**Feature description**
currently, the modcompiler doesnt recognize the assetbundle class, which sucks. modders could use the assetbundle class to unlock a lot more potential with ease, notably ui and custom entities

**Feature purpose**
im trying to write a unity plugin for entity creation to streamline the process since trying to do it soley with code is very fucking inefficient.

**Comment by mestiez** [comment]
Please try not to put nonsense in your issue

**Comment by TalonZane** [comment]
sorry about that, figured it was a required field for a valid request and didnt feel like rephrasing what was already apart of the description

**Comment by DindinYT37** [comment]
lmao "buh buh buhhhhh plltlllllll agahhhhh"
