### ISSUE TITLE
Broken objects should transform properties to debris

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#452]
**Feature description**
Whenever a destructable object is broken, the resulting debris should have the same heat and electricity factors as the parent. For objects that create multiple debris, it should be distributed equally.

**Feature purpose**
It's annoying that these factors aren't transmitted to debris and it can create rather unexpected behavior, one could also view this as a bug report as this is not how objects should behave when they're broken into debris.

**Additional context**
There is no additional context.

**Comment by mestiez** [comment]
Electricity and burn progress were already being transferred. I've added temperature and burning intensity too though.
