### ISSUE TITLE
make humans have a reaction to having their lungs shot 

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#459]
**Feature description**
when humans are suffocating from a ruptured lung they should have the same animation as drowning and fire etc

**Feature purpose**
it honestly makes no sense to have a human sitting perfectly still with a ruptured lung dying slowly so thats why i suggest some kind of animation for it

**Additional context**
none

**Comment by idotwaffle** [comment]
i'm in the latest version and humans do not appear to have lungs, i don't even see anything in the changelogs about lungs.
could you please explain how to "rupture" a human's lungs?
