### ISSUE TITLE
Mortar shell copy & pasting/save & loading issue

### ISSUE THREAD

**Issue by Tr0jancat** [studio-minus/ppg-bugs-and-requests#461]
**Describe the bug**
Explosion radius of mortar shell gets smaller each time of copy and pasting, same issue with saving.

**Clearly describe how to reproduce the bug**
1)Turn on "Detail view"
2)Spawn mortar shell
3)Copy/Save spawned mortar shell
4)Paste copied/Load saved mortar shell

**Mod list**
[Greenbrick Industries](https://steamcommunity.com/sharedfiles/filedetails/?id=2476975606)
[Fleeb Community Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2469355028)
[Iraq War mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2467426507)
[Tool gun](https://steamcommunity.com/sharedfiles/filedetails/?id=2452959137)
[Liquids Playground](https://steamcommunity.com/sharedfiles/filedetails/?id=2449430059)
[The ULTIMATE Minecraft Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2442812460)
[Imperial Weapons](https://steamcommunity.com/sharedfiles/filedetails/?id=2441871246)
[City](https://steamcommunity.com/sharedfiles/filedetails/?id=2441064195)
[COMBAT SPEC-OPS](https://steamcommunity.com/sharedfiles/filedetails/?id=2434956470)
[Liquids Map](https://steamcommunity.com/sharedfiles/filedetails/?id=2432660281)
[Escape From Tarkov Weapons and Humans](https://steamcommunity.com/sharedfiles/filedetails/?id=2412528040)
[Taser](https://steamcommunity.com/sharedfiles/filedetails/?id=2361892819)
[The Ultimate Admin Gun](https://steamcommunity.com/sharedfiles/filedetails/?id=2356907365)
[Star Wars Dark Saber Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2337413002) **INACTIVE**
[ExplosiveMod](https://steamcommunity.com/sharedfiles/filedetails/?id=2337158074)
[More Destructible Objects !](https://steamcommunity.com/sharedfiles/filedetails/?id=2319326006) **INACTIVE**
[Special Forces Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2302032461)
[R6S Exothermic Charge](https://steamcommunity.com/sharedfiles/filedetails/?id=2279649593)
[PowersMod](https://steamcommunity.com/sharedfiles/filedetails/?id=2276255188)
[More Guns](https://steamcommunity.com/sharedfiles/filedetails/?id=2235585600) **INACTIVE**
[Cyber's WWII Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2212721487)
[Stalker Guitar](https://steamcommunity.com/sharedfiles/filedetails/?id=2195322845)
[IrtnerMOD NO MORE BETA!](https://steamcommunity.com/sharedfiles/filedetails/?id=2193110720) **INACTIVE**
[Russian Roulette Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2173352550)
[Time Accelerator](https://steamcommunity.com/sharedfiles/filedetails/?id=2167988616)
[Active Humans](https://steamcommunity.com/sharedfiles/filedetails/?id=2163278857) **INACTIVE**
[Syringes++](https://steamcommunity.com/sharedfiles/filedetails/?id=2146791852) **INACTIVE**
[COMBAT Weapons Pack V3.0](https://steamcommunity.com/sharedfiles/filedetails/?id=2137927041)
[COMBAT Props Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2137926802) **INACTIVE**
[COMBAT Clothes Pack](https://steamcommunity.com/sharedfiles/filedetails/?id=2137492313) **INACTIVE**

**System info**
 - Operating system: Windows 10 Pro 20H2 64bit
 - Game version: 1.22.1
 - GPU: NVIDIA GeForce 940MX GDDR5 2048MB / Intel HD Graphics 620
 - CPU: Intel Core i3-7100U

**Additional notes**
There is a [video](https://youtu.be/00Qtj17E1Yw) of described issue

**Comment by UniDuki** [comment]
None of the vanilla explosives do this, this is not a place to report problems with mods.

*In case you didn't know, the mortar shell is not in the game. This is a problem with most of the explosives from "ExplosiveMod".*
