### ISSUE TITLE
Objects clip through walls.

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#462]
**Describe the bug**
Objects that have a high velocity and travel a long way clip through walls. If you dont understand what I said I'm saying that objects that go to fast (like that are flinged) clip through walls.

**Clearly describe how to reproduce the bug**
None that I know of.

**Mod list**
dead no collide
a handful of weird syringes 
combat lightsabers 
legion
grappling hook mod 
firearmada
thermite charge r6
functiong armour
warthog
beat up humans mod
controllable anti air cannon
spy mod
tacti cool atachments
throwing knife
massa
front facing human
musket mod
mo fluids 
injectable flasks mod
drawables
gorey human 2.0
flipping heck
gentle drag
weapons+ 2.0.1
doors mod
military+
dream
russian roullete gun
taser
wheelchair
more destructible objects
per pixel destruction
hold k to make wires invisible
shockwave mod 
assassin mod
human +
sorors npc pack (40)
discord pack

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.22.1
 - GPU: nvidia mx330
 - CPU: intel core 17

**Comment by BBQGiraffe** [comment]
what do you have your collision iterations set as in your settings?

**Comment by atwal6400** [comment]
> what do you have your collision iterations set as in your settings? and do you have continuous or discrete collisions?

continuous

**Comment by bluewoods64** [comment]
> > what do you have your collision iterations set as in your settings? and do you have continuous or discrete collisions?
> 
> continuous

What's your physics iteration count? Try raising it, that might help. If you're on continuous you shouldnt be experiencing phasing through objects.

**Comment by mestiez** [comment]
If this still happens in continuous mode, I can't do anything about it. Unity claims objects will not phase through each other in continuous collision mode so if that still happens then the gods of bloated generalised game engines have damned my soul.
