### ISSUE TITLE
Substance Tolerance 

### ISSUE THREAD

**Issue by CUBE0R** [studio-minus/ppg-bugs-and-requests#463]
**Feature description**
Basically, when you slowly give people an extremely small portion of a substance, (like acid or oil) they will slowly build a tolerance, so you might start with 1-2 percent acid and then slowly go to 5 percent after a bit and etc and they will have less negative effects depending on the tolerance, similar to real life poisons, and you can get 100 percent tolerance over time. Although it would take a good while to do this.

**Feature purpose**
Adds a bit of realism and allows you to make acid proof, or oil proof, or gorse blood proof humans, which seems pretty interesting without just adding a version of the human with acid resistance or whatever.

**Additional context**

**Comment by Afavertov** [comment]
I think you cant be tolerate acid, neurotoxin(death syringe) and toxic oil that can kill gorse.

**Comment by BBQGiraffe** [comment]
this isn't how human beings work you don't "build up a resistance" to acid or oil you're just poisoning yourself

**Comment by CUBE0R** [comment]
I mean, i get oil and acid wouldnt probably work, but substances like venom can slowly build up tolerance to the venom. Some people purposefully inject themselves with small doses of venom to build up a tolerance, its just you cant have an "acid resistant human" or an "oil resistant human" and I thought this would be a more interesting way then just going add oil resistant human or something like that. Some people with allergies to nuts or otherwise will slowly start to eat more nuts to build a tolerance and get out of the deathly allergic zone. Also, its possible to build up a tolerance to some poisons that arent nonproteinaceous, although oil and acid is probably more far fetched than that.
