### ISSUE TITLE
Androids should be 100% burnable like humans

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#469]
There is no difference between 50 and 100% burned androud.

Burn android with pink explosive.

No

Operating system: win 10
Game version: 1.22 beta
GPU: 750 ti
CPU:Intel Core I3-3240 3.40 GHz
![изображение](https://user-images.githubusercontent.com/89081329/141018841-74a67988-c83b-4c3d-bbd1-942a26f3841a.png)

**Comment by mestiez** [comment]
Not a bug really. A fully burnt android just doesn't look different.

**Comment by Afavertov** [comment]
In older vesions android can be burned to exoskeleton.
