### ISSUE TITLE
Not even sure what happened. Strange hybrid map glitch

### ISSUE THREAD

**Issue by bluewoods64** [studio-minus/ppg-bugs-and-requests#471]
![Screenshot 2021-11-09 192830](https://user-images.githubusercontent.com/93502259/141032995-8ccb929c-71ba-4a36-8126-46963b2e7d6c.png)
Ok, really I'm not sure what I did. I'll give you an in depth detail of what was happening moments before I did it. 
I was by the small shore on the hybrid map. I had about 8-9 people on the shore. I just used a gun and shot all them. I then proceeded to smash them with the trailer thing, while slightly moving towards the water. My fps dropped to about 2, which even though my pc is bad, it usually never gets that low. Then a few frames later I see the whole shore disappear, and when I zoom out, a few other things were changed. Overall, I was just very confused. But hey, extra map I guess.

**Clearly describe how to reproduce the bug**
Refer above

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7509150/exported.game.debug.info.md)

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22
 - GPU: Integrated Intel Hd 530
 - CPU: i7 6700

**Additional notes**
I know this is going to be near impossible to reproduce, however I thought I might aswell post this. I don't think it's a mod since I don't know of any mods that modify the map.

**Comment by idotwaffle** [comment]
seems like #1 to me?
but the humans gliching out for no reason could be it's own bug?
