### ISSUE TITLE
Boat

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#473]
**Feature description**
Motorized boat that is used for ocean transportation can't move on land but moves decent on water. Has two special parts, Fan which can only be started when generator is started, Generator helps the boat move. And how you make the boat move is activate the generator which will start the fan which will eventually make the boat move.

**Feature purpose**
New way of transportation and it would be cool to have a boat because then you can mount a gun on it or even make the fan faster.

**Additional context**
![boat](https://user-images.githubusercontent.com/55041380/141050166-f0f4d211-a01c-443a-b53c-90616d7b8e29.png)

P.S I know you can just make a boat but a vanilla version of the game the weight would be proper and it could actually move
and a propeller would be to high speed to make a boat like this as I said it should be decent on water not like a jet ski type speed.

**Comment by Afavertov** [comment]
Made it by yourself. Barrel and propeller.

**Comment by alikeobservant** [comment]
that destroys creativity no way

**Comment by atwal6400** [comment]
> **Feature description** Motorized boat that is used for ocean transportation can't move on land but moves decent on water. Has two special parts, Fan which can only be started when generator is started, Generator helps the boat move. And how you make the boat move is activate the generator which will start the fan which will eventually make the boat move.
> 
> **Feature purpose** New way of transportation and it would be cool to have a boat because then you can mount a gun on it or even make the fan faster.
> 
> **Additional context** ![boat](https://user-images.githubusercontent.com/55041380/141050166-f0f4d211-a01c-443a-b53c-90616d7b8e29.png)

**Comment by atwal6400** [comment]
> that destroys creativity no way

"Simple MP" destroys creativity no way. Also didnt zooi say he would never implement mp? On steam, disc, and even the forum its self.

**Comment by Purepsi** [comment]
its the easiest fucking thing to do idiot

**Comment by atwal6400** [comment]
> its the easiest fucking thing to do idiot

read the edit

**Comment by alikeobservant** [comment]
so you get pissed off at my comment and take the time to search my profile and all of my posts to find that, that's pretty petty

**Comment by atwal6400** [comment]
> so you get pissed off at my comment and take the time to search my profile and all of my posts to find that, that's pretty petty

no i just saw it in the forum?
