### ISSUE TITLE
Please add a multiplayer feature

### ISSUE THREAD

**Issue by Oqarshi** [studio-minus/ppg-bugs-and-requests#475]
**Feature description**
This feature can make people join your sandbox world and play with you! If you want to play with someone then you can go into a world and generate a code for the other people to enter and join your world!

**Feature purpose**
I want to play with my friends in their sanbox world

**Additional context**
:D

**Comment by Vkn164** [comment]
#194 "this is definitely never happening"

**Comment by bluewoods64** [comment]
Won't happen.

**Comment by DavidCo113** [comment]
Nope lol

**Comment by alikeobservant** [comment]
I honestly dont know any reason for this not being an option other than the fact that servers can be a HUGE pain in the balls to maintain, and can also be very expensive. And for a game this large, it definitely wouldn't be cheap on mestiez side.
