### ISSUE TITLE
More rigid Rigid Cables and Pins

### ISSUE THREAD

**Issue by Vkn164** [studio-minus/ppg-bugs-and-requests#477]
Feature description
A much more rigid rigid cable and pin..

Feature purpose
given enough force (or just movement in general) an object put in place by rigid cables or pins will not stay in place or stay attached to the rotation point

**Comment by Aspa102** [comment]
blame unity
I guess mestiez could make his own joints though

**Comment by mestiez** [comment]
The rigidity of physics constraints depends on the amount of solver iterations. There is no "weld" constraint in Unity's weird version of Box2D. Something I've experimented with is an "amalgamation" feature that would group objects together and have them share a single rigidbody. It would ensure a perfectly rigid weld. It caused a lot of issues with objects that expect to have their own rigidbody, though, and I eventually dropped it.

**Comment by Vkn164** [comment]
ah ok, thanks for the clarification
