### ISSUE TITLE
Remove The Skeleton in Electric Shock and Also That Easter egg from the jukebox that explodes the head Substituting for a Bleeding A short distance in the region that would be the ears of humans when releasing the next update

### ISSUE THREAD

**Issue by CATS2040** [studio-minus/ppg-bugs-and-requests#479]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by idotwaffle** [comment]
uh you're ment to put all that stuff in the description and feature purpose, not the title. also you're not ment to group feature requests

**Comment by bluewoods64** [comment]
Maybe use the template

**Comment by mestiez** [comment]
Please follow the template.
