### ISSUE TITLE
Fix Human Bug When they fall from a high height they cross the floor, fix this in next update plz.

### ISSUE THREAD

**Issue by CATS2040** [studio-minus/ppg-bugs-and-requests#480]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**

**Comment by Afavertov** [comment]
All you had to do, was follow the damn template, cats2040!
