### ISSUE TITLE
Add flip 

### ISSUE THREAD

**Issue by CATS2040** [studio-minus/ppg-bugs-and-requests#483]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by bluewoods64** [comment]
please just leave this thread if youre just not gonna use the template multiple times. This is a mod, and zooi said they will not be adding it to the game due to a reason that can be found in the mod description. I do not know the reason off the top of my head, i'd have to check
