### ISSUE TITLE
Neck

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#485]
**Feature description**
New body part that is located in between upper chest and head.

**Feature purpose**
When you shoot it theres 2 things that could happen. 1. Suffocation. 2. Paralyzation

**Additional context**
Have it connected to the head and I said paralyzation because the spinal cord is in the neck.

**Comment by Purepsi** [comment]
noooo go away

**Comment by atwal6400** [comment]
> noooo go away

can you stop. please i didnt even do anything

**Comment by Cboyjet4** [comment]
> > noooo go away
> 
> can you stop. please i didnt even do anything

Not to be offense, but literally all you've been suggesting for the last month are things that literally either aren't getting added, or have an extremely small chance of getting added, plus you've even suggested things that are already in the game.

**Comment by atwal6400** [comment]
> > > noooo go away
> > 
> > 
> > can you stop. please i didnt even do anything
> 
> Not to be offensive, but literally all you've been suggesting for the last month are things that literally either aren't getting added, or have an extremely small chance of getting added, plus you've even suggested things that are already in the game.

ye ive just been putting alot of requests for features in the game because the only way to make the game better is mods and personally i like vanilla stuff better thats why ive been spamming but other than that i think the only feature request that ive already done that are in the game is like one and ill stop trying to post feature requests sorry.

**Comment by alikeobservant** [comment]
As long as the neck isn't visible, this would be fun!

**Comment by Cboyjet4** [comment]
> As long as the neck isn't visible, this would be fun!

That'd likely confuse people anyways.
Blood coming out of an invisible joint, suffocating randomly?

**Comment by YourLocalPlonker** [comment]
That is so true i have played for so long and haven't even noticed
