### ISSUE TITLE
Adrenaline not working

### ISSUE THREAD

**Issue by jamesipod** [studio-minus/ppg-bugs-and-requests#491]
**Describe the bug**
People will full adrenaline can still be knocked out. 

**Clearly describe how to reproduce the bug**
Inject a human with adrenaline. Hit with item on head very hard. Watch them pass out. Using the normal adrenaline syringe produces the same result as the modded "Infinite Adrenaline Syringe". I realize it might be related to the internal bleeding status effect, but I still believe this to be a bug as they become unresponsive, even with large amounts of adrenaline coursing through their every vein. 

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7524455/exported.game.debug.info.md)

**Comment by mestiez** [comment]
Brain damage is not cured by adrenaline. Maybe internal bleeding is too easily caused?
