### ISSUE TITLE
Cardiopulmonary bypass Machine

### ISSUE THREAD

**Issue by BBQGiraffe** [studio-minus/ppg-bugs-and-requests#494]
**Feature description**
a machine that can be connected to the chest of a "human" to allow continued blood flow after severe heart damage

**Feature purpose**
forcing the dumb little people to stay alive longer would be funny

**Additional context**
drew a concept sketch in my journal
![IMG_20211112_093754](https://user-images.githubusercontent.com/45021140/141493152-d7a5f1ea-9c67-4e3f-97ee-e60b9cd48e4a.jpg)

**Comment by alikeobservant** [comment]
This man put effort into his drawing so please let him have this 


plus this would be pretty cool soo

**Comment by DindinYT37** [comment]
Notification for everyone interested: This feature has been accepted.
