### ISSUE TITLE
Lightning Strike effect on humans

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#496]
**Feature description**
When a human is struck by lightning there is a very small chance that they will posses powers of electricity and how they use it is activate their hands and it will send a lightning strike straight ahead. 

**Feature purpose**
It would just be nice to have humans posses powers that are only restricted to the player
**Additional context**
![strike](https://user-images.githubusercontent.com/55041380/141594993-d914f2b1-08e6-44ef-9c0e-fe471f6c92f6.png)

**Comment by TamasB14** [comment]
The way you ask for "Realism" the 95% of the time and one ridicolously big "above-nature" anomaly just makes me chuckle.

**Comment by atwal6400** [comment]
> The way you ask for "Realism" the 95% of the time and one ridicolously big "above-nature" anomaly just makes me chuckle.

my b bruh
