### ISSUE TITLE
Mods not loading.

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#497]
**Describe the bug**
When all your mods load your most recent one just keeps on loading.

**Clearly describe how to reproduce the bug**
None that I know of.

**Mod list**
The only mod this effects currently is A crap ton of damage.

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.22.2 (64 bit) 
 - GPU: nvidia mx330
 - CPU: intel core i7

**Comment by idotwaffle** [comment]
what?? you say it's the most recent mod that gets stuck loading, but then you say it's only the "crap ton of damage" mod that gets stuck loading. those 2 things contradict each other, what do you mean?

**Comment by atwal6400** [comment]
> what?? you say it's the most recent mod that gets stuck loading, but then you say it's only the "crap ton of damage" mod that gets stuck loading. those 2 things contradict each other, what do you mean?

its fine now but it used to not just be a crap ton of damage its my recent mods like one time it was the assasins mod
