### ISSUE TITLE
Cannot move more than 1 selected thing

### ISSUE THREAD

**Issue by DrLarbob** [studio-minus/ppg-bugs-and-requests#500]
When I paused the game and wanted to move a human, I couldn't. It will not let me move more than one selected item

**Clearly describe how to reproduce the bug**
Try to select and move more than one item at once in pause mode.

**Mod list**
No Mods

 - Operating system: Win 10
 - Game version: 1.22.2
 - GPU: Gtx 1650
 - CPU: 

https://user-images.githubusercontent.com/94234865/141650449-e1459791-aead-439f-a3b3-a5359cbd8430.mp4

Intel core i-5

**Additional notes**

**Comment by DrLarbob** [comment]
well, i have one mod, but I removed it before and tried and nothing happened. Bug was still there

**Comment by mestiez** [comment]
Can't reproduce this

**Comment by bluewoods64** [comment]
yeah you cant move more than one thing, even if youve selected multiple things. atleast im pretty sure, i could be wrong.

**Comment by mestiez** [comment]
You definitely can move multiple objects at once if you are in paused mode.

**Comment by DrLarbob** [comment]
Yes, I used to be able to move multiple selected items, but now I just doesn't work. I tried uninstalling the game, getting rid of all mods.. It is very annoying.

**Comment by DrLarbob** [comment]
> You definitely can move multiple objects at once if you are in paused mode.

please, anything! Its still like this aghhhh!!! I'm going insane.

**Comment by mestiez** [comment]
I can't reproduce it. You need to give me more information.

**Comment by mestiez** [comment]
Closed until more information is given

**Comment by DrLarbob** [comment]
Okay, when i select things with the square select it does not work. I've tried multiple mice and none of them fix the problem. I went onto my other computer with the mice and it works just fine. I don't know what more information that you need, but this is all i know.

**Comment by DrLarbob** [comment]
also, if you look at the video, the square select tool does not work for me.

**Comment by DrLarbob** [comment]
after a year. still have same darn bug

**Comment by mestiez** [comment]
the problem is that i cannot reproduce this no matter what i do. something about your game must be different for this to occur. try different computers, different versions, different peripherals.
