### ISSUE TITLE
Humans randomly produce white liquid

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#505]
**Describe the bug**
Sometimes, blood splatters will be completely white. This is very rare but the ones I encountered were small decals produced by a human falling and hurting their foot. Expanded gore doesn't need to be enabled for this to happen. The decal was also way more smaller than a blood splatter should be.

**Clearly describe how to reproduce the bug**
As far as I know, there is no one way to reproduce this. The most common way I got it was a human falling from a little height and hurting their foot although it wasn't bruised by the impact.

**Mod list**
No mods need to be present for this to happen.

**System info**
 - Operating system: Linux Mint
 - Game version: 1.22.2
 - GPU: GeForce GTX 650 Ti Boost
 - CPU: Intel(R) Core(TM) i7 CPU   975  @ 3.33GHz

**Additional notes**
Although I thought this was only possible by the presence of a mod, it happened to me while no mods were active or loaded so this leads me to believe that this is in fact a bug in the core game play rather than a side effect of a mod that may or may not be changing the game's damage mechanics that would effect the blood color in a way that would make it appear completely white. I am certain that there are several mods that do this but when I encountered this bug while I was playing the game, I was traumatized due to the fact that I was using no mods at the time and the human I spawned was completely normal. This bug is severely game changing and completely ruined my experience with this game and I can't play it anymore as it reminds me of the fact that despite there being no mods that may or may not be changing the game's core damage mechanics that would change the blood color to be white, this can still happen.

**Comment by mestiez** [comment]
I am still completely unable to reproduce this.

**Comment by alikeobservant** [comment]
Happens to me as well, unsure how to reproduce this, I think its completely random

**Comment by EfeYks534** [comment]
> I am still completely unable to reproduce this.

That's the thing. This is the only time I got it, when I try to reproduce it I never got it again

**Comment by EfeYks534** [comment]
![cumhub](https://user-images.githubusercontent.com/36643011/141947030-823387fe-e2f3-4e4f-9fbe-adb3462a650b.png)

**Comment by TamasB14** [comment]
I only had this once.

**Comment by LushPineapple29** [comment]
I actually had this experience happen in my game, no mods too.

**Comment by Nicovw321** [comment]
happened the same to me before

**Comment by mestiez** [comment]
Possibly fixed?? Can't tell because I still can't reproduce it. Closed until someone experiences it again.

**Comment by BBQGiraffe** [comment]
> Possibly fixed?? Can't tell because I still can't reproduce it. Closed until someone experiences it again.

rise and shine dutch boy

the spot appeared when the human was at the red circle, there wasn't an extra blood particle it just kinda popped into existence 
![Screenshot from 2021-11-25 12-50-47](https://user-images.githubusercontent.com/45021140/143490370-beab8687-1b2b-44e8-8933-162aa213c756.png)

**Comment by GreaterCanada** [comment]
WELCOME. TO THE CUM ZONE.
