### ISSUE TITLE
spiritdragonplayz

### ISSUE THREAD

**Issue by spiritdragonplayz** [studio-minus/ppg-bugs-and-requests#510]
i was trying to play people playground but then it just always crashes at 90% map loaded i tried uninstalling then reinstalling but nothing then i tried deleting some mods but nothing this has been happening to me for moths please fix this

**Comment by spiritdragonplayz** [comment]
i joined github just to put this post in please fix this ive tried everything

**Comment by idotwaffle** [comment]
the very least you could do is provide your pc information, and maybe also explain what all the things you've tried are?
