### ISSUE TITLE
Energy sword can destroy indestructible cables?

### ISSUE THREAD

**Issue by LushPineapple29** [studio-minus/ppg-bugs-and-requests#512]
**Describe the bug**
Energy Sword can delete or "destroy" indestructible cables.

**Clearly describe how to reproduce the bug**
Spawn an Energy Sword and try hitting a indestructible cable with it.

**Mod list**
None.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22.2 (64 bit)
 - GPU: Radeon RX 580 Series
 - CPU: 11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz   3.91 GHz

**Additional notes*
![5mBW5Hf12D](https://user-images.githubusercontent.com/59892936/142030461-15306c69-beca-4878-8fbd-a89ceb545432.gif)
![MCZ4BJuVop](https://user-images.githubusercontent.com/59892936/142031831-551acbef-07b8-4988-8430-acc5f76a4b88.gif)

It actually may take time for the Energy Sword to destroy cables, it took a few tries for me.
*

**Comment by LushPineapple29** [comment]
I'm completely sorry if this isn't a bug at all.

**Comment by BBQGiraffe** [comment]
I think it's because of the heat level of the object, if I put an object in lava it won't let me attach cables of any kind to it, may or may not be a feature.

**Comment by LushPineapple29** [comment]
> I think it's because of the heat level of the object, if I put an object in lava it won't let me attach cables of any kind to it, may or may not be a feature.

![image](https://user-images.githubusercontent.com/59892936/142036296-bf42cf62-fc8e-405a-8ca0-79efb50d2ac9.png)
I'm unsure about that because I can do this?

**Comment by DavidCo113** [comment]
This is a feature.

**Comment by LushPineapple29** [comment]
> This is a feature.

Apologies.
