### ISSUE TITLE
Flamethrower recoil goes the wrong way

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#516]
**Describe the bug**
Flamethrower will go forwards instead of backwards when fired. I'm sure that's not how recoil works.

**Clearly describe how to reproduce the bug**
Get a flamethrower, make it weightless. Now get an activation toggle and make it weightless too. Connect the toggle to the flamethrower and enable it. Flamethrower will go forwards instead of backwards.

**Mod list**
No mods need to be active in order for this game-breaking bug to happen.

**System info (please complete the following information)**
 - Operating system: Linux Mint
 - Game version: 1.22.2
 - GPU: GeForce GTX 650 Ti Boost
 - CPU: Intel(R) Core(TM) i7 CPU 975  @ 3.33GHz

**Additional notes**

No additional notes needed.

**Comment by mestiez** [comment]
Lmao the flamethrower isn't supposed to have recoil. It's pushing itself because it's hitting itself.

**Comment by mestiez** [comment]
Fixed :)

**Comment by EfeYks534** [comment]
Lol
