### ISSUE TITLE
Allow modders to add "Grip position" to items

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#521]
## **Feature description**
Grip position would be a Relative Position value. When a human tries to grab it, it would grab at the point of the grip position.

### It would fix things like this:
<img src="https://user-images.githubusercontent.com/64973205/142489504-0efb8a14-f2a6-4f09-a609-b8bd2ffd361f.png" alt="image" width="160"/>

### To be like this:
<img src= "https://user-images.githubusercontent.com/64973205/142489540-e5b559bd-96a5-4985-838f-def4987ec4ee.png" alt="image" width="160"/>

I am unsure of whether it already exists in some form or not since I'm not a modder, but I'm somewhat sure that modders would've already used the feature if it was.

## **Additional context**
Note: The sword used in the pictures is from some random mod. The point is that it would fix the problem of the human not Grabbing  the item right (see upper picture), the bottom picture is just an example of how it could look with this feature.

**Feel free to ask me for more information, don't just close the feature request since it's somewhat important to me**

**Comment by mestiez** [comment]
Modders can already do this. See the [modding wiki]( https://www.studiominus.nl/ppg-modding/internalReference/PhysicalBehaviour.html#public-vector3-holdingpositions).

To any modders coming across this message:

```cs
var phys = Instance.GetComponent<PhysicalBehaviour>();
phys.HoldingPositions = new Vector3[]{
   new Vector3(0 ,0, 0), //center of the object
   new Vector3(0.4, -0.2, 0), //somewhere else
   new Vector3(0.1, 0.2, 0), //you should have recognised the pattern by now
};
```

**Comment by DindinYT37** [comment]
I guess modders just don't care (or know)
