### ISSUE TITLE
HEAT Cannon fires *too* rapidly when activated through another item after exiting slow-mo

### ISSUE THREAD

**Issue by wave004** [studio-minus/ppg-bugs-and-requests#523]
**Describe the bug**
The new HEAT cannon fires when connected to with a propagation wire (if for example a brick is connected with the wire to the cannon, the brick is held and pressed-and-held "F" on, the cannon fires full-auto). If however while doing that the player slows down time for a moment, then resumes normal time, the cannon fires multiple "stored" shots extremely rapidly.

**Clearly describe how to reproduce the bug**
1. Spawn inert item and the 30mm cannon
2. Propagation wire from item to cannon
3. Hold item, press and hold F on item
4. Slow down time
5. Resume time
6. Observe

(Steps 3 and 4 can be switched places, as long as the item is activated for a longer time while in slow-mo the bug will work.)

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22.2
 - GPU: None, Intel integrated graphics or something
 - CPU: Intel Core i7-4810MQ

**Comment by mestiez** [comment]
This is actually a bug that exists with almost every automatic item in the game.

**Comment by DindinYT37** [comment]
I don't know how people playground was programmed (since I'm not a dev) but I'm pretty sure it's because of the game trying to "catch up" since I assume the intervals are calculated using the systems time? (Unsure, I'm not really that of a unity developer)

**Comment by mestiez** [comment]
> how people playground was programmed

it wasn't programmed very well

> I'm pretty sure it's because of the game trying to "catch up" since I assume the intervals are calculated using the systems time

It's happening because the game incorrectly calculates the firing frequency considering the current timeScale.

**Comment by wave004** [comment]
oh shut up mestiez the game is super fun, even if it's janky at times

**Comment by wave004** [comment]
oh shut up mestiez the game you've made is still super fun, even if it's janky at times

**Comment by mestiez** [comment]
Forgot to mark this as fixed
