### ISSUE TITLE
Custom Tab Support (Hear me out)

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#530]
**Feature description**
Currently my tab-bar looks like this. (I have many mods)
![image](https://user-images.githubusercontent.com/64973205/142759389-ce260cc1-0bc5-4049-9d85-de4b64d4d7d3.png)

And as you can see, nobody is really caring about that it's not supported and all that. So my idea was to add support for it, and instead of adding it directly to the bar, add an arrow or plus (see picture A as example) and when clicked on it, a dropdown menu will appear with all the custom tabs. (See picture B as an example of how the dropdown could look like)

Another small idea of mine, if a mod adds more than one new tab. Have it have it's own header, and maybe make it collapsible. (Mod name, see picture C)

**Feature purpose**
Stops Modders from causing bugs by using this unsupported feature, gives better viewability over the content of a mod, and in generally is better sorted for many custom tabs.
_Could also be somewhat of a solution for #119_

**Additional context**
<details>
<summary>Picture A</summary>

### Version 1:
![image](https://user-images.githubusercontent.com/64973205/142759490-2423f18e-bd33-4df4-b3ac-b6175933b941.png)

### Version 2:
![image](https://user-images.githubusercontent.com/64973205/142759827-92b4d292-3f88-4bf0-aaad-a6492095c388.png)
</details>

<details>
<summary>Picture B</summary>

![image](https://user-images.githubusercontent.com/64973205/142759791-4657273b-84bd-4ec0-b58d-1aeddb61a244.png)
</details>

<details>
<summary>Picture C (Gray used instead of transparent Black)</summary>

![image](https://user-images.githubusercontent.com/64973205/142759770-600214d4-b14d-487a-96a8-f9cf519c2506.png)
</details>

**Comment by mestiez** [comment]
Good idea.

**Comment by humaaaan** [comment]
i came here to request a similar feature and that is add folders in saved contraptions and a default one for workshop items so i dont need to look through hundreds of contraptions

ok ill go make my own req now

**Comment by D3stStrut** [comment]
> Good idea.

Just so you don't forget this is in pins:

Add this to the "To do" list

**Comment by mestiez** [comment]
It's pinned but not accepted yet.

**Comment by 821lemur** [comment]
> İyi bir fikir.

Would you mind my idea of ​​extinguishing a fire with a hose and a water pump, that is, really water?

**Comment by DindinYT37** [comment]
According to the [People Playground Changelog](https://github.com/studio-minus/people-playground-changelog/blob/master/CHANGELOG.md#:~:text=ModAPI.RegisterCategory,supports%20custom%20categories), this was accepted.

**Comment by mestiez** [comment]
Accepted with significant modifications

**Comment by DindinYT37** [comment]
> Accepted with significant modifications

Understandable.

**Comment by TeslaCoil9001** [comment]
CONGRATULATION, YOU WERE THE 1000 ISSUE CLOSED!!!!!

**Comment by ATPGaming** [comment]
> CONGRATULATION, YOU WERE THE 1000 ISSUE CLOSED!!!!!

tone it down a few notches
