### ISSUE TITLE
random sparks

### ISSUE THREAD

**Issue by kotikrandom** [studio-minus/ppg-bugs-and-requests#533]
**Describe the bug**
sometimes sparks would start randomly and push objects slightly

**Clearly describe how to reproduce the bug**
i was messing around with nitroglycerin oil and showerheads

**Mod list**
cyberpunk 2077 trauma medic
skittles sryinge pack (active)
prison mod
active humans
quality of life items (active)

**System info (please complete the following information)**
 - Operating system: windows
 - Game version: 1.22.2
 - GPU:intel graphics
 - CPU:intel i5

**Additional notes**

**Comment by idotwaffle** [comment]
could you be more specific on what sparks are?

**Comment by mestiez** [comment]
Extremely unclear
