### ISSUE TITLE
Pausing makes things jump

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#534]
**Describe the bug**
Instead of the game gradually slowing down when pausing, like it used to. It now comes to an instant stop, and then jumps forward. So basically it is still doing the gradual slow down, but just not showing it, and then jumping to the finished result.

**Clearly describe how to reproduce the bug**
1. Get an object travelling decently fast
2. Pause while it's moving

You should see the object pause, then half a second later; jump forward. I find this is easier to see while in slow motion.

**Mod list**
None

**Additional notes**
I attempted to record this but the thing moved too fast for the recording to even see it.
So here, this is what happens when I throw a soap really fast and then pause:
![image](https://user-images.githubusercontent.com/69184577/142832450-6b1a6460-3689-4fd5-ac9b-21cd464ec5ef.png)

<details>
<summary><b>Settings</b></summary>
<br>

```json
{
  "DropOnDeath": true,
  "LimbCrushing": false,
  "LimbOverflowExplosion": false,
  "TracerBullets": true,
  "FancyEffects": true,
  "StopAnimationOnDamage": false,
  "ExpandedGore": false,
  "Decals": true,
  "ClampVolume": true,
  "ShowOutlines": true,
  "LogDebugMessages": false,
  "ShowFramerate": true,
  "Lighting": false,
  "VSync": true,
  "SMAA": false,
  "ZoomSensitivity": 1.0,
  "MasterVolume": 1.0,
  "SfxVolume": 1.0,
  "UserInterfaceVolume": 1.0,
  "AmbienceVolume": 1.0,
  "ShakeIntensity": 0.099999994,
  "SlowMotionSpeed": 20.0,
  "CrushForceMultiplier": 1000000000000.0,
  "ThermalVisionUpdateRate": 25,
  "DeleteWireByContextMenu": false,
  "SimplifiedBackground": false,
  "AmbientTemperatureTransfer": true,
  "TemperatureUnit": 0,
  "WindowMode": 1,
  "CollisionQuality": 1,
  "TonemappingMode": 0,
  "BloomMode": 0,
  "Brightness": 120.0,
  "PhysicsIterations": 32,
  "RenderScale": 1.0,
  "FramerateLimit": 1000,
  "Resolution": {
    "x": 1920,
    "y": 1080,
    "magnitude": 2202.90723,
    "sqrMagnitude": 4852800
  },
  "ShowTutorial": false,
  "ToyboxSizeOffset": 943.5853,
  "ShowModLoadingFreeze": true,
  "RejectShadyCode": true,
  "MaxModCompilationTime": 10
}
```

</details>

**Comment by TamasB14** [comment]
That's an issue in many games using time pause. I remember Besiege had the same issue. I have no idea what causes it though.

**Comment by DindinYT37** [comment]
> That's an issue in many games using time pause. I remember Besiege had the same issue. I have no idea what causes it though.

Could be because of the updates (positions, etc.) also being slowed down.
Not sure though, I'm not a Unity-Dev.

I'm only saying this because I had the problem I just mentioned when coding slow-motion for a game of mine in Java.

**Comment by idotwaffle** [comment]
> That's an issue in many games using time pause. I remember Besiege had the same issue. I have no idea what causes it though.

okay but that ain't the problem here, there used to be a gradual slow down but now it's gone.

**Comment by TamasB14** [comment]
> > That's an issue in many games using time pause. I remember Besiege had the same issue. I have no idea what causes it though.
> 
> Could be because of the updates (positions, etc.) also being slowed down. Not sure though, I'm not a Unity-Dev.
> 
> I'm only saying this because I had the problem I just mentioned when coding slow-motion for a game of mine in Java.

Indeed, that's the most logical answer for the anomaly. I thought about the same thing.

**Comment by mestiez** [comment]
The actual position of the object is the same as it would be if it had slowed down smoothly. This happens because the game disables physics position interpolation when paused to ensure that the player sees the most accurate representation of the world.

Often this makes it look like the game is lagging or teleporting objects seemingly at random, but that is not the case. This is not a bug, it's just a stupid side effect of interpolation.
