### ISSUE TITLE
Contraptions with humans are corrupted

### ISSUE THREAD

**Issue by ToxicSnake48** [studio-minus/ppg-bugs-and-requests#536]
Whenever I save a thing that has a human/android/gorse and I reload the game the saved contraption gets corrupted

Steps to reproduce the problem.
save a thing with living thing and reload the game and it corrupts
**Mod list**
none

**System info (please complete the following information)**
 -operating system: 64-bit operating system, x64-based processor
 - Game version: 1.22.2
 - GPU: AMD Ryzen 3 3200U with Radeon Vega Mobile Gfx  2.60 GHz

**Comment by DindinYT37** [comment]
Did you try to validate your game files?

**Comment by mestiez** [comment]
I cannot reproduce this.
