### ISSUE TITLE
"DRAG SELECTED" when entering any map

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#539]
*I now realise it probably shouldn't even say "DRAG SELECTED" when loading onto map*

**Describe the bug**
Basically how I see it is there is an invisible counter in the background, this counter is set to zero when you open the game.
Every time you load a map, this counter goes up by one.
When you load up a map it will say "DRAG SELECTED" in the chat, the amount of times it says "DRAG SELECTED" is whatever the counter is at currently.

**Clearly describe how to reproduce the bug**
1. Close the game if open.
2. Open the game.
3. Load onto any map. You should now have just "WELCOME TO PEOPLE PLAYGROUND" and one "DRAG SELECTED" in the chat.
4. Load onto another map, without restarting the game. it should now say "DRAG SELECTED" once more than last time.
5. Repeat step four until satisfied.

**Mod list**
None

**System Information**
- OS: Windows 10 (10.0.19043) 64bit
- Game Version: 1.22
- CPU: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
- GPU: Intel(R) UHD Graphics

**Comment by DindinYT37** [comment]
Lately a lot of new bugs are randomly being added into the game.

**Comment by DindinYT37** [comment]
Did you try reinstalling or validating your game files?

**Comment by UniDuki** [comment]
DindinYT37, I didn't at the time of this report, but now I have. But thanks to that, now I think I've figured out the real problem here.

Every time I load a map it adds another "DRAG SELECTED". So the first time I load a map, it says one "DRAG SELECTED", then the second time it says it two times, then, three times... up to the max of nine, and then you can't tell a difference.

**Comment by DindinYT37** [comment]
> DindinYT37, I didn't at the time of this report, but now I have. But thanks to that, now I think I've figured out the real problem here.
> 
> Every time I load a map it adds another "DRAG SELECTED". So the first time I load a map, it says one "DRAG SELECTED", then the second time it says it two times, then, three times... up to the max of nine, and then you can't tell a difference.

I see. Also (which you probably already knew), it stops at nine because the log only has nine lines displayed.

I guess, we can do nothing but wait for the Developer to update.

**Comment by mestiez** [comment]
This is worrying because it implies some sort of lingering object pile somewhere

**Comment by mestiez** [comment]
Fixed :)

**Comment by DindinYT37** [comment]
@UniDuki

### Mission Passed
**(2x rewards bonus)**
+5 Respect
+10 Experience
