### ISSUE TITLE
RGB Laser

### ISSUE THREAD

**Issue by Nicovw321** [studio-minus/ppg-bugs-and-requests#546]
**Feature description**
Hear me out, a laser that when you send a (for example) red signal through it, it sends a red ray that when hit with one of those laser receivers, it receives a red signal and then transfers it to the red propagation wires (same with blue and green), and i don't mean changing the original laser! just adding a new one that's RGB and changing the laser receiver to detect those signals.

**Feature purpose**
it's just a new type of laser that is better, sending three times the signal and being much more useful :D

**Comment by DavidCo113** [comment]
I think a context menu for this would be better.

**Comment by Nicovw321** [comment]
> I think a context menu for this would be better. Otherwise, good idea.

yeah, also that could work!

**Comment by pjstarr12** [comment]
im going to make this a mod

**Comment by DavidCo113** [comment]
> im going to make this a mod

Ok cool

**Comment by mestiez** [comment]
Technically added a while ago, but not quite
