### ISSUE TITLE
Conveyors do not like to be copied (or saved)

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#549]
**Describe the bug**
If you copy and paste a conveyor, the wheels seem to become objects that the player can interact with.

It's hard to describe what happens to the conveyor, try it yourself. But basically you can "select" them but there's no highlight, and you don't get the context menu options. you can drag it around and connect wires to it though.

**Clearly describe how to reproduce the bug**
1. Copy / Save a conveyor
2. Paste / Load a conveyor

**Mod list**
None

https://user-images.githubusercontent.com/69184577/143325545-57667bf5-d52b-4b3b-bbdb-be8bd7213c30.mp4

**Comment by mestiez** [comment]
I hate the conveyor belt so much.

**Comment by mestiez** [comment]
fixed holy christ
