### ISSUE TITLE
Complex Machine with wires not doing wire things.

### ISSUE THREAD

**Issue by pasta-chan** [studio-minus/ppg-bugs-and-requests#550]
**Describe the bug**
I am making a machine that has a lot of wires and works in fast succession. My wire keep on not turning off/on when they are activated. I am using quite a few laser and laser detectors as those are the only things available for me to use for what I want. I don't think this is apart of the issue but it could be related.  

**Clearly describe how to reproduce the bug**
![fgdsjdfhgjdhgjdgjhmk](https://user-images.githubusercontent.com/95014173/143390960-f7c003ef-8146-4c00-b513-bbe38240a135.PNG)

**Mod list**
I have a LOT of mods, but they were deactivated though so it shouldn't affect anything.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22.2 beta version
 - GPU: 3070ti
 - CPU: i7 9700KF

**Additional notes**
Gates such as and/or/nor would heavily reduce the problem and make machines a lot easier to make due to not having to use lasers for many things. Also this has happened many times in the past but this is the only time it has been consistent and happens in non beta versions.

Edit: I just want to specify that I don't want help with ways around what my machine is doing, I already figured that out.

**Comment by mestiez** [comment]
Can you attach your contraption in an archive (zip, 7z, rar, whatever)?

**Comment by pasta-chan** [comment]
[002 Binary Code wtf.zip](https://github.com/studio-minus/ppg-bugs-and-requests/files/7604472/002.Binary.Code.wtf.zip)
Here is the contraption in the state as posted in the image. To run it just activate one of the displays with letters on them.

**Comment by mestiez** [comment]
After some testing again, this contraption also far exceeds the propagation signal limit. This causes strange and confusing behaviour. Not a bug :(

**Comment by mestiez** [comment]
I have added a little warning in the bottom-right to show whenever the limit is exceeded.
