### ISSUE TITLE
Pistons and/or Radios not function properly.

### ISSUE THREAD

**Issue by pasta-chan** [studio-minus/ppg-bugs-and-requests#552]
At first it appeared that the pistons weren't working but under further inspection it appears that multiple signals are being sent through a radio despite only one signal being inputted.

Video on the issue. (First I show a input that functions as intended and doesn't send multiple signals, then the one that sends multiple signals through the "31110" radio.)
https://user-images.githubusercontent.com/95014173/143664236-d558d4cd-ec34-421c-80d0-d85c3a5edbfc.mp4
(Apologies for the cuts, the GitHub limit made it so I had to cut it down and lower the quality.)
**Mod list**
Disabled all mods prior to loading the contraption.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22.2 Beta
 - GPU: RTX 3070Ti
 - CPU: i7 9700KF

**Additional notes**
The aforementioned failing to work input had worked prior to this play session and was tested to work. I have not changed anything in the area of the contraption in which the "31110" radio would be affected. It also appears that despite the multiple signals going through none of the pistons that should've been affected no matter where they ended up, did not move or make a sound effect.

**Comment by mestiez** [comment]
Can you send the contraption file instead? It's too hard to understand what's happening in the video.

**Comment by pasta-chan** [comment]
I see what you mean, here is the game file. Just one of the displays with letters on them and it'll run. "q" is the only one that works for some odd reason.
[0055 Binary Code 32.zip](https://github.com/studio-minus/ppg-bugs-and-requests/files/7612676/0055.Binary.Code.32.zip)

**Comment by mestiez** [comment]
After some testing, your contraption malfunctions because there is a hard limit (of 1024) on the amount of simultaneous propagation signals.  Your contraption far exceeds this limit unfortunately. This is not a bug, but it must be pretty confusing for a player.
