### ISSUE TITLE
Ability to disable item collision only for selected items

### ISSUE THREAD

**Issue by benitonite** [studio-minus/ppg-bugs-and-requests#555]
This function will have to **remove the subject collision only for certain objects, without affecting the rest**

It is impossible to repeat this in the game, but I believe that this function is necessary to create various kinds of mechanisms. I want to create a humanoid robot from sticks and mechanical parts, it is almost ready for the exhibition in the workshop, I can smell its success, but to create 2 legs that will touch each other, the usual disconnection of the collision will not help, as it will damage the movement system. Thanks for **reading!**

**Comment by mestiez** [comment]
I am unsure what you mean. There is a phase link, which allows two objects to phase through each other. Does that not do what you want?

**Comment by DindinYT37** [comment]
sounds like #118 to me
