### ISSUE TITLE
Uploading Contraptions to Workshop via PPG itself not working, softlocking.

### ISSUE THREAD

**Issue by wave004** [studio-minus/ppg-bugs-and-requests#561]
**Describe the bug**
When using PPG to upload a contraption to the workshop, it uploads an empty addon and softlocks the game.

After selecting what tags the contraption should have and pressing "publish" the game uploads it to 20% completion, after which it displays "Could not create Workshop Item
                                  Fail"
After that the game "uploads" to 100% and softlocks itself - the "100% uploaded" window does not go away, the only way out is an Alt-F4

**Mod list**
-Object Editor by Morzzic (inactive)
-Quick Right Click Options by Pump3d (inactive)
-Scream mod by Skullex(jamesH_2), Aspa102, Kassjak (active)
-Advanced Damage by weirdo (inactive)

**System info (please complete the following information)**
 - Operating system: Windows
 - Game version: Current, no beta selected
 - GPU: None, integrated graphics
 - CPU: intel inside core i7-4810

**Additional notes**
Other users do not appear to have that bug. May be limited to my game. 
After verifying game integrity and deleting every mod besides Scream mod the issue persisted.

**Comment by mestiez** [comment]
Fixed, I think. Obviously I can't reproduce the bug but I fixed all ways in which it could happen, as far as I know.
