### ISSUE TITLE
The PhysicalBehaviour arrays "OverrideShotSounds" and "OverrideImpactSounds" in objects created by CreatePhysicalObject are null

### ISSUE THREAD

**Issue by Aspa102** [studio-minus/ppg-bugs-and-requests#562]
**Describe the bug**
When creating an object via CreatePhysicalObject, the arrays "OverrideShotSounds" and "OverrideImpactSounds" are null. This causes errors when shooting / throwing the object. This took me a while to figure out what was causing the issue once I stumbled upon it.

**Clearly describe how to reproduce the bug**
Create an object with CreatePhysicalObject and shoot it.

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7635501/exported.game.debug.info.md)

**Additional notes**
This is easily fixed by just setting them yourself after creating an object, but it is annoying and some other people may not know how to fix it.

**Comment by mestiez** [comment]
Oh good catch.

**Comment by mestiez** [comment]
Fixed :)
