### ISSUE TITLE
Right click animations wont work

### ISSUE THREAD

**Issue by flxsq** [studio-minus/ppg-bugs-and-requests#564]
So i right click the npcs to use animations like sit,walk etc and it just doesnt work

Right click npcs and it wont work (atleast for me)

Military mod Expansion : Warlords activated
Simple Syringes mod activated
Scream mod activated
flipping heck activated
Terraria mod weapon activated
Active humans activated

 - Operating system: Windows 10
 - Game version:1.22.2
 - GPU:AMD Radeon HD 6670
 - CPU:AMD FX(tm)-6300 Six-Core Processor

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7637232/exported.game.debug.info.md)

**Comment by mestiez** [comment]
Are you trying to make the "active humans" perform animations?

**Comment by flxsq** [comment]
apparently it was the active humans that didnt work and that i need to use the normal npcs thank you

**Comment by flxsq** [comment]
oh wait it works for a few npcs then it just doesnt work and im still using the normal npcs
