### ISSUE TITLE
*Small Bug* Scroll Bar in the Toybox not scaled properly or something

### ISSUE THREAD

**Issue by Aspa102** [studio-minus/ppg-bugs-and-requests#567]
**Describe the bug**
The scroll bar in the toybox does not scale appropriately (Shows as the category being very large & scrolled to the bottom) when you scroll to the bottom of a large category (Misc.) then change to another category (Biohazard, in this example).

Image after performing the bug
![image](https://user-images.githubusercontent.com/79403796/144559894-a840e79d-dd6e-4810-a62f-26264f9dcc60.png)

**Clearly describe how to reproduce the bug**
Head to the misc. category and scroll to the bottom. Change the category to something like Biohazard

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7647417/exported.game.debug.info.md)

**Additional notes**
This isn't like a big deal or even like a major bug. It's just a little nitpick that I can't unsee. I don't really mind if you literally do not care about it.

**Comment by mestiez** [comment]
Fixed 🎈
