### ISSUE TITLE
A random dead zombie's limb slowly rotates sometimes

### ISSUE THREAD

**Issue by Aspa102** [studio-minus/ppg-bugs-and-requests#569]
**Describe the bug**
Killing a zombie (mostly facing the left) will sometimes result in a limb rotating. It's weird.

**Clearly describe how to reproduce the bug**
Inject a human (spawned facing the left) with the zombie virus.
Wait until the zombie is fully rotten (might not matter but eh).
Kill the zombie.

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7649686/exported.game.debug.info.md)

**Additional Notes**
Very strange bug, especially how it appears to only happen to zombies facing the left. Originally I thought it was the head that just did it, but then reproducing the bug caused the upper body limb to rotate. It's odd.

**Comment by Aspa102** [comment]
Just in case you need to know:
I use 64 physics iterations, and continuous mode.

**Comment by TamasB14** [comment]
Yes, I got that issue too.

**Comment by mestiez** [comment]
Fixed :D
