### ISSUE TITLE
Debug.Log Messages duplicate loading into maps multiple times

### ISSUE THREAD

**Issue by Aspa102** [studio-minus/ppg-bugs-and-requests#571]
**Describe the bug**
Messages sent by Debug.Log into the chat duplicate by the amount of times you've loaded into a map (e.g resetting, quitting and choosing new map). This is only a visual issue, and does not affect the actual log file.

Image after resetting in Default. "Test2" should only appear once.
![image](https://user-images.githubusercontent.com/79403796/144607125-bb270f5f-1a76-4c1f-8d6d-3cbd8797b7c5.png)

**Clearly describe how to reproduce the bug**
Set up something that causes a Debug.Log message.
Reset in a map / quit and load into another map.
Watch the chat.

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7649838/exported.game.debug.info.md)

**Additional notes**
Resetting a bunch of times then getting a log message in the chat would flood it, which is kind of annoying (even after just once) when I have the option to enable them on always.

**Comment by mestiez** [comment]
DRAG SELECTED part 2

**Comment by mestiez** [comment]
Fixed :)
