### ISSUE TITLE
Real Time Recording

### ISSUE THREAD

**Issue by pjstarr12** [studio-minus/ppg-bugs-and-requests#574]
**Feature description**
a feature could be that there would be a keybind that records EVERYTHING in a certain square (like the camera, but no movement)
THAT  **ISNT** slo mo or faster than normal
THE OUTPUT: a folder called "Recording" in the game files that has everything you recorded in real time
**Feature purpose**
recording, it could be good for accurate movements in the result

**Additional context**
![RCMode](https://user-images.githubusercontent.com/85199112/144675299-7e504abe-451c-4e7f-9a4e-52181761d9e1.png)
.

**Comment by DindinYT37** [comment]
Make it create a "People Playground" folder in the Videos directory of your System (ex. `C:\Users\DindinYT37\Videos`) and I agree.

**Comment by pjstarr12** [comment]
thats what i meant

**Comment by DindinYT37** [comment]
> thats what i meant

You said game files though, which are located at a completely different path. I guess so, though.

**Comment by pjstarr12** [comment]
could be both

**Comment by mestiez** [comment]
I don't think this will add anything that OBS and a bit of editing can't do already
