### ISSUE TITLE
Fast Motion toggle

### ISSUE THREAD

**Issue by Jz1207** [studio-minus/ppg-bugs-and-requests#584]
**Feature description**
The same as the slow motion toggle, but speeds up time instead

**Feature purpose**
Increasing time speed above 100 is already possible with mods such as time accelerator or extra powers, but having a simple button to do it at will would be great

**Additional context**
Like the Slow mode toggle, there should be a setting for the degree which time is sped up to, x2, x4, x8, etc

**Comment by abdul2178** [comment]
Ngl this would be helpful

**Comment by TamasB14** [comment]
Yeah would be good, but that would cause the physics to go on faster than normal, which could result in alot of lag.

**Comment by Jz1207** [comment]
> 

From what I've seen with time accelerator mods the lag is negligible unless going very overboard, and these are very old unoptimised mods, were it an actual feature of the game I'm sure it'd run fine. Besides, I don't think excluding a feature this good because it may lag lower end PCs only while turned on is really much of a reason.
