### ISSUE TITLE
More realistic physics and disasters

### ISSUE THREAD

**Issue by abdul2178** [studio-minus/ppg-bugs-and-requests#585]
**Feature description**
==More Game Features==
Hello! Could you add more physics to people playground? Example add some water physics when you use freeze ray on it the area in some distance will freeze.
Also you could add something like disasters.

**Feature purpose**
So more "realistic physics" would look cool, And the disasters oh god i just want them so badly in the game you could have so much fun with them.

**Additional context**
So the disasters would be: earthquake, volcano eruption(optional), tsunami, tornado, flash floods, blizzards, storms, in my opinion the game would be more fun.

**Comment by mestiez** [comment]
Feature request have to be as specific as possible. If your suggestion is so vague that you need to start giving examples, you're probably not being clear enough.
