### ISSUE TITLE
Feature Request: Activator item

### ISSUE THREAD

**Issue by wave004** [studio-minus/ppg-bugs-and-requests#587]
**Feature description**
Mechanical Item: Activator. An object that relays activation signals to whatever item it is currently facing.

**Feature purpose**
An item somewhat similar to the detectors already in the game, sending out a beam of variable length in front of it. Upon activation, the item relays the signal through to the object that the beam is touching. 

**Additional context**
None unless requested otherwise.

**Comment by mestiez** [comment]
what is the difference between this and a laser + laser receiver setup?

**Comment by wave004** [comment]
None, actually, other than this item would be slightly more compact. To be honest the laser+receiver setup never even came to mind, which is why I came here. Sorry about that
