### ISSUE TITLE
Native Linux Support

### ISSUE THREAD

**Issue by DavidCo113** [studio-minus/ppg-bugs-and-requests#590]
**Feature description**
GNU/Linux builds made available for the game.

**Feature purpose**
So linux users can play the game without a VM/proton/dual booting etc.

**Comment by EfeYks534** [comment]
It works fine with Proton and it would require a lot of hard work to port it which is not worth it in my opinion.

**Comment by DavidCo113** [comment]
> #290: "There won't be an official linux build" and "Proton works fine in almost all cases."

Ok
