### ISSUE TITLE
Liquid outlet produces white blood

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#591]
**Describe the bug**
When a liquid outlet inside of water is connected to a drowning human, it paints the walls with white blood.

**Clearly describe how to reproduce the bug**
+ Spawn a human
+ Put the said human inside water (possibly the shore in Hybrid because the water is shallow there)
+ Wait until the human is drowning
+ Spawn a liquid outlet and put it into water
+ Connect liquid outlet to human with blood vessel wire
+ It will start emitting the gas particles liquids usually emit in water
+ The ground will be painted with white

**Mod list**
No mods need to present for this bug to occur

**System info (please complete the following information)**
 - Operating system: Linux Mint
 - Game version: 1.22.3
 - GPU: GeForce GTX 650 Ti Boost
 - CPU: Intel(R) Core(TM) i7 CPU  975  @ 3.33GHz

**Additional notes**
![Whiteliquid](https://user-images.githubusercontent.com/36643011/144852966-3aadb955-d575-4b81-9730-6d111f67735b.png)

**Comment by UniDuki** [comment]
I tested this and my results were a bit different so here:
- It does not have to be blood from a drowning human, it doesn't even have to be blood.
- The white particles only appear if the liquid outlet was spawned in water and never left. The coloured gas always appears.
- If spawned out of water, or taken out and put back in, it shows the coloured particles on the floor, alongside the gas.
![image](https://user-images.githubusercontent.com/69184577/144892496-4a778cc1-8d07-4449-a88f-a34f223ceb8d.png)

**Comment by mestiez** [comment]
Great bug report! Fixed :)
