### ISSUE TITLE
Activation Toggle object sending too many activation signals when in 1% speed

### ISSUE THREAD

**Issue by Nicovw321** [studio-minus/ppg-bugs-and-requests#592]
**Describe the bug**
kinda weird, when those Activation Toggle thingies are activated (and connected to another object) while in 1% speed, it triggers the error shown in the video that i also linked down below

**Clearly describe how to reproduce the bug**
1. spawn an Activation Toggle
2. spawn a random object
3. connect the Activation Toggle to the object with a propagation wire
4. Activate the Activation Toggle
5. go to slow mo (1%) and voila

**Mod list**
Working Spraycans MOD, Object Possesor And Earthquake ... (hah, tl;dr), Object Editor, OCM, Raw Pink Liquids, Quick Right Click Options, Quality of Life Items, Scream Mod, Gentle Drag, Metal Things Mod, Flipping Heck, Taser, Aimbot Gun, Human Tiers, Skittle's Syringe Mod, PPG Spy Mod, Hazmat Mod Remastered, Time Accelerator, Active Humans, Overdose.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22.3
 - GPU: Radeon RX 570 Series
 - CPU: AMD Ryzen 5 2600

**Additional notes**
vidio:
https://user-images.githubusercontent.com/89240410/144949041-da38f5ed-13b8-4e7e-94f5-c6a735159341.mp4

**Comment by Nicovw321** [comment]
okay i don't know what just happened, but i can't trigger the message anymore

**Comment by mestiez** [comment]
Ah this makes perfect sense and can probably not be solved without destroying every single contraption that relies on the current activation signal system...

**Comment by Nicovw321** [comment]
holy-

**Comment by EfeYks534** [comment]
> Ah this makes perfect sense and can probably not be solved without destroying every single contraption that relies on the current activation signal system...

You should rewrite this game in a better way sometime..

**Comment by DindinYT37** [comment]
I am somewhat sure that it's like this because it would actually be faster (as fast as in slow motion), it's just that you don't have enough FPS. So the game would need to send more than one signal per frame (which it can't because it makes no sense), which results in it just sending less.

**Comment by Nicovw321** [comment]
> > Ah this makes perfect sense and can probably not be solved without destroying every single contraption that relies on the current activation signal system...
> 
> You should rewrite this game in a better way sometime..

you notice they just said they can't rewrite the game without breaking everything? bruh

**Comment by deathhimself23** [comment]
i have my slow mo at 10%

**Comment by DindinYT37** [comment]
> i have my slow mo at 10%

Okay, and??

**Comment by deathhimself23** [comment]
> > i have my slow mo at 10%
> 
> Okay, and??

the toggle doesnt send enough activation signals

**Comment by DindinYT37** [comment]
> > > i have my slow mo at 10%
> > 
> > 
> > Okay, and??
> 
> the toggle doesnt send enough activation signals

So what has that anything to do with this issue?

**Comment by deathhimself23** [comment]
> > > > i have my slow mo at 10%
> > > 
> > > 
> > > Okay, and??
> > 
> > 
> > the toggle doesnt send enough activation signals
> 
> So what has that anything to do with this issue?

it makes the toggle and any other constant activation completely useless

**Comment by DindinYT37** [comment]
> > > > > i have my slow mo at 10%
> > > > 
> > > > 
> > > > Okay, and??
> > > 
> > > 
> > > the toggle doesnt send enough activation signals
> > 
> > 
> > So what has that anything to do with this issue?
> 
> it makes the toggle and any other constant activation completely useless, and i play at 30 frames capped

My question was how that has anything to do with this issue.

**Comment by deathhimself23** [comment]
> > > > > i have my slow mo at 10%
> > > > 
> > > > 
> > > > Okay, and??
> > > 
> > > 
> > > the toggle doesnt send enough activation signals
> > 
> > 
> > So what has that anything to do with this issue?
> 
> it makes the toggle and any other constant activation completely useless, and i play at 30 frames capped

and your thone who said it was Duplicate of or Related to: this post

**Comment by DindinYT37** [comment]
> > > > > > i have my slow mo at 10%
> > > > > 
> > > > > 
> > > > > Okay, and??
> > > > 
> > > > 
> > > > the toggle doesnt send enough activation signals
> > > 
> > > 
> > > So what has that anything to do with this issue?
> > 
> > 
> > it makes the toggle and any other constant activation completely useless, and i play at 30 frames capped
> 
> and your thone who said it was Duplicate of or Related to: this post

It's related to this issue because they're both about activation signals from activation toggles, that doesn't mean that it has anything to do with this issue in direct sense. Not to mention that your comments on here are also completely obsolete and make no sense in relation to this issue.
