### ISSUE TITLE
Rewind time

### ISSUE THREAD

**Issue by pjstarr12** [studio-minus/ppg-bugs-and-requests#593]
**Feature description**
it kinda explains itself? 
its basically a tool that whenever mousebutton1 is held, it starts rewinding everything that happened and you can stop at any time in the range of 30 seconds

forza and other games did it, so it shouldnt be hard in a 2d game (considering theres only 2 dimensions, not much to keep track of)
**Feature purpose**
useful for contraption makers if they accidentally delete everything and lose all their progress
or if you just do something wrong

**Additional context**
not any

**Comment by idotwaffle** [comment]
if this is added make it be optional, because im sure saving everything every frame is gonna be pretty expensive

**Comment by pjstarr12** [comment]
yeah

**Comment by TamasB14** [comment]
> if this is added make it be optional, because im sure saving everything every frame is gonna be pretty expensive

I agree, that'd be pretty much CPU heavy. The most I could take would be maximum 5 seconds rewind.

**Comment by DindinYT37** [comment]
> > if this is added make it be optional, because im sure saving everything every frame is gonna be pretty expensive
> 
> I agree, that'd be pretty much CPU heavy. The most I could take would be maximum 5 seconds rewind.

But what if only the things that have changed are saved? The things that are not saved to have changed in a specific frame are ignored, basically meaning that the size of each frame(-save) would drastically decrease and easier to iterate over.

This is somewhat of what Forza does, only the cars and things the cars have touched are rewound.
