### ISSUE TITLE
Sticky grenade should unstick from its target when defused

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#594]
**Feature description**
When a sticky grenade is stopped by an EMP, it should unstick from stuff.

**Feature purpose**
It's impossible to break the connections it made with its target when it's defused through natural means which is very annoying.

**Additional context**
There is no additional context.

**Comment by TeslaCoil9001** [comment]
I wish this wasn't rejected :/
