### ISSUE TITLE
speedometer , weight scale,

### ISSUE THREAD

**Issue by vile223** [studio-minus/ppg-bugs-and-requests#595]
Feature description
a machine to measure speed, and a machine to measure weigt...

purpose
it would be nice to have a set of instruments to know more details about stuff

**Comment by TamasB14** [comment]
I'd like that speedometer the most.

**Comment by EfeYks534** [comment]
You can measure speed by marking the visual center of an object using a frozen & disabled collision brick, waiting exactly 1 second then marking the center of it again. Measure the length between the two marked points to find the speed.

**Comment by TamasB14** [comment]
> You can measure speed by marking the visual center of an object using a frozen & disabled collision brick, waiting exactly 1 second then marking the center of it again. Measure the length between the two marked points to find the speed.

Now do that to a plane that needs actual speedometer.

**Comment by satsubatsu347** [comment]
> > You can measure speed by marking the visual center of an object using a frozen & disabled collision brick, waiting exactly 1 second then marking the center of it again. Measure the length between the two marked points to find the speed.
> 
> Now do that to a plane that needs actual speedometer.

Considering the game allows for freezing time, slowing time by percentages, and has a 1m2 grid on the background... It would be frighteningly easy and achingly accurate.

**Comment by YourLocalPlonker** [comment]
I do it the hard way and mark a distance (about 100m) and count how long it roughly takes and then i have the speed in m/s x3.6 is km/h. But a speedometer really would improve this and make it more accurate

**Comment by mestiez** [comment]
grouping suggestions is kind of fucky
