### ISSUE TITLE
Human strength and resilience should increase when scaled up

### ISSUE THREAD

**Issue by Nicovw321** [studio-minus/ppg-bugs-and-requests#596]
**Feature description**
Making humans and other objects behave just like when they had their original size, instead of tearing apart instantly.

**Feature purpose**
when you resize a human, like 20 times it's original size, it doesn't last none until every bone of it's body breaks after touching something, so like, making them handle the different size would be nice.

**Additional context**
i know that maybe how it is now is how the world works but like, having a human that can occupy the entirety of the hybrid map and tryina move there would be pretty funny.

**Comment by EfeYks534** [comment]
You know that resistance is lower when the size is bigger right? It's a feature of real world physics

**Comment by TamasB14** [comment]
Yeah... that's the problem. Resizing, only changes the size, not the values of anything else.

**Comment by Nicovw321** [comment]
> You know that resistance is lower when the size is bigger right? It's a feature of real world physics

i said it in the aditional context part, i know that's how it works in the real world but still, that would a nice feature to be added.

**Comment by DindinYT37** [comment]
> Yeah... that's the problem. Resizing, only changes the size, not the values of anything else.

Well it changes the weight as well, which is probably the reason why the bones tear apart instantly upon dragging. They also instantly break most bones when falling from a height that would be normal for a human of this size, because a 40 meter fall is still a 40 meter fall even if the human is bigger.

**Comment by mestiez** [comment]
forgot about this but this is currently implemented

**Comment by mestiez** [comment]
forgot about this but this is currently implemented

**Comment by mestiez** [comment]
github moment? 
![image](https://user-images.githubusercontent.com/32131519/210122049-fc1cec91-a72e-468d-82ce-b324d26f580b.png)
