### ISSUE TITLE
Spawnable water?

### ISSUE THREAD

**Issue by dmanbop** [studio-minus/ppg-bugs-and-requests#597]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?
Spawnable water that can fill objects or spaces, can spawn a small, medium, or large pocket of water with some weight to it(maybe toggleable in the settings)
**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?
i want this because it could make interesting contraptions, traps, scenes, even new landscapes or self made maps if combined with some mods. i think it would be cool to be able to make a beach or a tank of green liquid for someone to fall into.
**Additional context**

**Comment by DavidCo113** [comment]
> Water physics will not be added.
   - Roadmap

Also, please fill out the template.
