### ISSUE TITLE
Higher Gravity Acceleration for Heavy Objects

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#599]
**Feature description**
For example, this gigantic one ton weight has this floaty behavior because it has the "standard" acceleration. Instead it should have a higher downward acceleration due to it's immense weight.
![floaty behaviour](https://user-images.githubusercontent.com/64973205/145449980-25619d1d-8b4d-44cc-9ee8-68e78a21bea5.gif)

**Feature purpose**
It would make it generally more realistic and nicer to use.

**Additional context**
Screenshake for the win.

**Comment by EfeYks534** [comment]
This is how gravity works. A 1000000 ton weight and a feather would drop at the same rate. The reason this isn't the case on Earth is because of air friction and resistance which don't exist in People Playground

**Comment by DindinYT37** [comment]
> This is how gravity works. A 1000000 ton weight and a feather would drop at the same rate. The reason this isn't the case on Earth is because of air friction and resistance which don't exist in People Playground

It's Acceleration I'm talking about, the physics formula for acceleration is literally `acceleration = Force * mass`. It would be completely stupid to assume they would fall at the same rate, as far as I know you would fall slower than a car would?

**Comment by EfeYks534** [comment]
Yeah? You just told me they fall at the same rate then said it would be stupid to assume they would fall at the same rate

**Comment by DindinYT37** [comment]
> Yeah? You just told me they fall at the same rate then said it would be stupid to assume they would fall at the same rate

I am unsure whether you're trolling or actually just dumb.

**Comment by satsubatsu347** [comment]
> > Yeah? You just told me they fall at the same rate then said it would be stupid to assume they would fall at the same rate
> 
> I'm kinda getting bored of this discussion, if you really insist then add Air resistance. I don't care, I was just saying what I learned in physics a few years ago anyways.

Demand a refund if you paid for that physics class. Gravitational acceleration is 9.80665 m/s2 on the planet known as Earth for ALL OBJECTS; bound by Newton's Law of Universal Gravitation.

You are asking for:
enhanced and expanded drag (& buoyancy)

People Playground already simulates friction (a running car tire held to an entity's head will set it on fire eventually), human and androids appear to be influenced by an isolated drag system (they "fall slower" than other objects), lower mass objects do damage as they approach terminal velocity (like dropping a syringe off of the Tower Map tower), limited buoyancy (drop an entity from on high and they incur damage on hitting the water and then float to the surface), and ambient temperature settings that may affect these interactions as well (I haven't really played with those too much).

Overall, I agree with you. More nuanced and physics accurate interactions with the objects would be great.

**Comment by DindinYT37** [comment]
> > > Yeah? You just told me they fall at the same rate then said it would be stupid to assume they would fall at the same rate
> > 
> > 
> > I'm kinda getting bored of this discussion, if you really insist then add Air resistance. I don't care, I was just saying what I learned in physics a few years ago anyways.
> 
> Demand a refund if you paid for that physics class. Gravitational acceleration is 9.80665 m/s2 on the planet known as Earth for ALL OBJECTS; bound by Newton's Law of Universal Gravitation.
> 
> You are asking for: enhanced and expanded drag (& buoyancy)
> 
> People Playground already simulates friction (a running car tire held to an entity's head will set it on fire eventually), human and androids appear to be influenced by an isolated drag system (they "fall slower" than other objects), lower mass objects do damage as they approach terminal velocity (like dropping a syringe off of the Tower Map tower), limited buoyancy (drop an entity from on high and they incur damage on hitting the water and then float to the surface), and ambient temperature settings that may affect these interactions as well (I haven't really played with those too much).
> 
> Overall, I agree with you. More nuanced and physics accurate interactions with the objects would be great.

- I guess I'll demand a refund then.

- Well it's more about having heavy objects accelerate faster than light objects instead of enhanced or expanded drag, and buoyancy is already a thing.

- *Nothing to say*

- I guess you still understand what I meant.

**Comment by mestiez** [comment]
I haven't read any of this discussion but this is just how large objects behave in real life.

**Comment by username90001** [comment]
any object accelerate by same speed in g force because gforce is not force but deformation of time
and actualy i think 1 ton weight of that size will fall slower than feather because of aerodynamics

**Comment by username90001** [comment]
> > This is how gravity works. A 1000000 ton weight and a feather would drop at the same rate. The reason this isn't the case on Earth is because of air friction and resistance which don't exist in People Playground
> 
> It's Acceleration I'm talking about, the physics formula for acceleration is literally `acceleration = Force / mass`. It would be completely stupid to assume they would fall at the same rate, as far as I know you would fall slower than a car would?

this formula litteraly says heavier object will get more force but due to its mass it will have same acceleration and also it is caused by deformation of time its not force
