### ISSUE TITLE
Revoke access for Modders to use Application.Quit()

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#604]
**Feature description**
Why are they allowed to do that in the first place, I don't want a mod randomly closing/crashing my game without me knowing it was from that mod.

**Feature purpose**
Prevents so-called "Infected-Mods" from being created, they could basically be a copy of a popular mod or even an original one, but with some random part in the code that uses `Application.Quit();` that will close/crash your game with you (most likely) thinking it's just some crash. This would also result in a lot of confusion, if one of those mods emerges and gets popular, you would also likely get many bug reports regarding their game crashing on random occasions.

**Additional context**
`Application.Quit();` = bad

***Edit:***
*Or atleast, make the mod rejected as suspicious mod. Since I've seen some mods not being detected as suspicious even though they're using `Application.Quit();`*

**Comment by EfeYks534** [comment]
The current modding system is pretty bad. Although it is very fast because mods are injected right into the game, it's very unsafe.
Since you can't think of every possibility, it becomes very hard to prevent sussy programs from running.

**Comment by DindinYT37** [comment]
> The current modding system is pretty bad. Although it is very fast because mods are injected right into the game, it's very unsafe. Since you can't think of every possibility, it becomes very hard to prevent sussy programs from running. It's up to you to determine what mods to use and if they're safe or not.

*Lmao "sussy programs"*
Anyways, I know that it's "bad" because @mestiez said so often. Though it would nice to have something like this or atleast have some kind of Verification badge to make sure mods are safe.

**Comment by mestiez** [comment]
The system isn't bad necessarily, it's just unsafe. This is why the suspicious mod rejection system exists.
