### ISSUE TITLE
Grenade should explode after 4 seconds

### ISSUE THREAD

**Issue by TamasB14** [studio-minus/ppg-bugs-and-requests#607]
**Feature description**
Grenade should only explode after 4 seconds, as current grenade is too fast for actually using it as a grenade.

**Feature purpose**
Realism, preventing exploision too close, giving time to throw further without exploding in the air

**Additional context**
Sometimes the current time is just not much. I can barely throw it anywhere further with the hand of a Human.

**Comment by mestiez** [comment]
i agree
