### ISSUE TITLE
Suggestion: Mirror Object option

### ISSUE THREAD

**Issue by wave004** [studio-minus/ppg-bugs-and-requests#609]
**Feature description**
A drop-down menu option to mirror an object (horizontally or vertically)

**Feature purpose**
Make manipulating objects and creating symmetrical contraptions a tad bit easier

**Additional context**
None unless asked for

**Comment by DindinYT37** [comment]
Flipping heck is already a mod for horizontal mirroring, vertical mirroring can probably be done by just editing that mod.
It's a mod because People Playground never intended things to be flipped/mirrored after they have been spawned.

Source: @mestiez
