### ISSUE TITLE
Balloons can store liquids + maybe helium?

### ISSUE THREAD

**Issue by SalreixVonOtsuu** [studio-minus/ppg-bugs-and-requests#610]
**Feature description**
Balloons can store liquid, and release their effect when popped (like syringes when shot). Also maybe helium as a liquid?

**Feature purpose**
Why not? ¯\_(ツ)_/¯

**Additional context**
Helium could make things float or something temporarily, and also maybe there could be a way to make it into liquid helium? idk how it would work because helium is a gas so it might not make sense

**Comment by DindinYT37** [comment]
> **Feature description** Balloons can store liquid, and release their effect when popped (like syringes when shot). Also maybe helium as a liquid?
> 
> **Feature purpose** Why not? ¯_(ツ)_/¯
> 
> **Additional context** Helium could make things float or something temporarily, and also maybe there could be a way to make it into liquid helium? idk how it would work because helium is a gas so it might not make sense

Liquid helium makes sense if it's cold enough.

**Comment by Cboyjet4** [comment]
would you store cool aid in a balloon

+ why?
wouldn't the balloon also be totally useless because it would be essentially a water balloon if they could store.. liquid..
Hey that's a better suggestion, water balloons, still strange but makes sense I guess.

**Comment by SalreixVonOtsuu** [comment]
You do know balloons are hollow, right? The only difference is "water balloons" are filled with water instead of helium, they're the exact same thing

**Comment by YourLocalPlonker** [comment]
Hydrogen would be cool cuz it has explosive properties when exposed to oxygen
