### ISSUE TITLE
Invisible human

### ISSUE THREAD

**Issue by Apevus** [studio-minus/ppg-bugs-and-requests#612]
**Describe the bug**
Invisible human
**Clearly describe how to reproduce the bug**
When I was making my mod and I made 2 human entities, when I spawn them in they just are **invisible**, please help me with this. It happened in one of my other mods.

 - Operating system: Windows 10
 - Game version: 1.22.3
 - GPU: Icore 7
 - CPU: Intel HD family

**Additional notes**

**Comment by DindinYT37** [comment]
You didn't even show us a picture, you could also just be lying.
What is your mod? Can you be sure it's because of your mod? What does your mod do? How is it coded?

There a many questions to be answered before something can be told.

**Comment by mestiez** [comment]
This isn't a modding help place. You can create an issue if you encounter a bug within the game or modding system.
