### ISSUE TITLE
Sometimes gun tracers are not showing up

### ISSUE THREAD

**Issue by Eukalp** [studio-minus/ppg-bugs-and-requests#616]
**Describe the bug**
Sometimes tracers are not showing up when firing a weapon.

**Clearly describe how to reproduce the bug**
Just fire any weapon that uses tracers, sometimes they just fire blank untraced rounds.

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Windows 7
 - Game version: Latest
 - GPU: Radeon HD 7850
 - CPU: FX-4320

**Additional notes**
It's just annoying how sometimes I can't trace the bullets.

**Comment by mestiez** [comment]
There is a maximum number of tracers allowed in the world at once. If the limit is exceeded, tracers aren't rendered / simulated.

Though I've noticed that, occasionally, tracer rounds won't render regardless of the limit. I haven't been able to reproduce the issue though.

**Comment by TamasB14** [comment]
I did some testings, and if I fire the tracers into the sky, it doesn't happen, but when I fire the tracers when other tracers hit a closer object (and they particle on hits) they tracers disappear.

**Comment by DindinYT37** [comment]
Can vouch, happened to me before even when only a single gun is shooting and there are no active bullet-tracers.
