### ISSUE TITLE
Lights in blue room in hybrid can be destroyed, bug? or intentional?

### ISSUE THREAD

**Issue by Glowinspace97** [studio-minus/ppg-bugs-and-requests#618]
**Describe the bug**
Floodlights in the Blue room of hybrid can be destroyed, I assume this is not supposed to happen because if you try to destroy floodlights in the main room, they won't get destroyed

https://user-images.githubusercontent.com/94892441/145918758-b0f4c170-f85f-48ba-8450-10bb79ee9bf0.mp4

**Mod list**
Mods have been deactivated

**Additional notes**
Maybe this was intentional, but if you play around in the blue room or blow up some bombs the floodlights will break, and cannot be repaired, forcing you to restart if you want it to be lit up again, I don't think this is good as whenever i use lightning powers the lights break and i can't see there

**Comment by EfeYks534** [comment]
Smash them with the wrench to repair

**Comment by mestiez** [comment]
Intentional and yes the wrench can repair them
