### ISSUE TITLE
Remote activator (Not like radio)

### ISSUE THREAD

**Issue by YourLocalPlonker** [studio-minus/ppg-bugs-and-requests#620]
An item of the category "Machinery" when activated it activates everything in an adjustable radius except itself

Moving parts do not need cables anymore and do not need a radio attached which saves space in contraptions and makes it all easier to build.

I am building a contraption in which should be fully automated and is run with bombs (pink explosives) working like fuel in an engine. Adding radios to the bombs would cause them to be leftovers blocking the engine. The machine is made to do heavy work autonomously without any human assistance. Adding cables cannot be done autonomously and an remote activator would do it if anything would get in its radius while it is activated.

**Comment by TamasB14** [comment]
So... basically bluetooth. Good!

**Comment by DindinYT37** [comment]
Please follow the template, nonetheless good idea though.

**Comment by UniDuki** [comment]
They are following the template though?

**Comment by DindinYT37** [comment]
> They are following the template though?

I think I get what you mean, but he's still supposed to keep the Headers in the feature request. Their whole point is to make the feature request easier to navigate/read and clearer.

**Comment by mestiez** [comment]
i consider this "accepted" with the recent addition of the activator electrode
