### ISSUE TITLE
Pumpkin particles texture

### ISSUE THREAD

**Issue by souphasapple** [studio-minus/ppg-bugs-and-requests#622]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

break pumpkin and zoom into the particles

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

many mod but it not effect texture

**System info (please complete the following information)**
 - Operating system: windows 10
 - Game version: 1.22.3
 - GPU: nvidia geforce gtx 1080
 - CPU: Intel(R) i7-7700K CPU 

**Additional notes**

![image](https://user-images.githubusercontent.com/85040598/146295986-4c1c6016-d332-4ab9-a281-e5e9cda7bb7c.png)

**Comment by mestiez** [comment]
Lmao oops. thats the whole sprite sheet

**Comment by mestiez** [comment]
Fixed :)
