### ISSUE TITLE
Trying to delete Secret Tile with "Delete" key spams "World Removed"

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#623]
**Describe the bug**
When holding the "Secret" Tile on the Sea map and holding the "Delete" key, it spams with "World Removed".
![image](https://user-images.githubusercontent.com/64973205/146357722-f67a3e27-0d2c-406d-bfd8-f192d1f3988a.png)

**Clearly describe how to reproduce the bug**
Hold the "Secret" Tile on the Sea map and hold the "Delete" key (Default is backspace).

**Additional notes**
I've seen it happen with mods before that try to make props that you can't delete, but obviously didn't report that because it was caused by a Mod. I'm only reporting this now since it happens in vanilla.

**Comment by mestiez** [comment]
Fixed :)

**Comment by DindinYT37** [comment]
Happens again.
