### ISSUE TITLE
math-signal cable

### ISSUE THREAD

**Issue by BBQGiraffe** [studio-minus/ppg-bugs-and-requests#627]
**Feature description**
cable that sends floating point numbers for various objects ex: detectors send distance and servos use the input as an angle.
would also include modules that perform operations such as multiplication and basic functions like sin and cos

**Feature purpose**
this would allow much more complex machinery to be built

**Comment by DindinYT37** [comment]
People Playground Machinery is gradually evolving.

**Comment by mestiez** [comment]
I would also like this but, as I've said before somewhere, this would make the game too complicated. I like the simplicity of the current system and how it forces players to be creative. Redstone philosophy. I think cool badass features like `math-signal cable` are better suited for mods.
