### ISSUE TITLE
limb regrowth syringe

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#629]
**Feature description**
a new item in the "biohazard" category named "limb regrowth syringe" or some variant' when injected into a human their limbs will pop back into existence possibly with some kind of "growing animation" as to make it less jarring 
**Feature purpose**
as of now there is no way to fix limbs as to make a human function properly without spawning a new one in so i believe having this kind of feature would be very helpful

**Additional context**
another way of implementing this would be prosthetics of some kind but that has been suggested before.

**Comment by Aspa102** [comment]
This will never happen unless mestiez decides to make some major changes to the limb system.

**Comment by mestiez** [comment]
> This will never happen unless mestiez decides to make some major changes to the limb system.

Yes

**Comment by fhgb54643689** [comment]
> This will never happen unless mestiez decides to make some major changes to the limb system.

what about prosthetics are those possible to be implemented?
