### ISSUE TITLE
Pasted, Duplicated Conveyor Belts have broken hitbox with coursor.

### ISSUE THREAD

**Issue by TamasB14** [studio-minus/ppg-bugs-and-requests#630]
**Describe the bug**
Basically when I copy-paste a conveyor belt, the coursor doesn't highlight it. Sometimes it highlights only if I just scribble my mouse near the conveyor's middle.

**Clearly describe how to reproduce the bug**
Spawn a conveyor belt
Copy & Paste a Conveyor belt
Moe your coursor on the pasted conveyor
Abrakadabra, coursor doesn't highlight it.

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Win 7
 - Game version: Latest
 - GPU: Radeon 7850
 - CPU: FX-4320

**Additional notes**
Ropes, Welds, Cables cannot be connected to it without the highlight.

**Comment by TamasB14** [comment]
Update:
Been testing it for a while, realised that the issue is with the wheels for the conveyor belt. Those are the things causing the highlight to be wrong.

**Comment by UniDuki** [comment]
This sounds like #549, but slightly different? I can connect wires to the conveyor still, but also to the wheels of the conveyor.

**Comment by TamasB14** [comment]
> This seems like a duplicate of #549 to me. Also you may of realised this but the reason the hover highlight doesn't show is because you aren't hovering over it, you are hovering over one of the wheels, the wheels become objects that the player can interact with once pasted/loaded.

Exactly what I said above.

**Comment by TamasB14** [comment]
But yeah, seems like your were faster about that issue. Closing this issue with the reason: Duplicate
