### ISSUE TITLE
Please make a physical rope. Like the slider but slacked. maybe you could be able to pull it taught. This would massively increase contraption potential.

### ISSUE THREAD

**Issue by ClyMarin** [studio-minus/ppg-bugs-and-requests#633]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by mestiez** [comment]
Please follow the templat
