### ISSUE TITLE
option to turn off human self healing

### ISSUE THREAD

**Issue by wilsonmcpiston** [studio-minus/ppg-bugs-and-requests#639]
Feature description
an option to disable the human self regeneration, it can be on right click or the menu or somewhere else

Feature purpose
to add more customization to the humans, also stuff like zombies regenerating is kinda annoying

Additional context
also sometimes people want to have some scarred humans for proyects or just to play, since the self healing feels too fast sometimes

**Comment by DindinYT37** [comment]
> also sometimes people want to have some scarred humans for proyects or just to play

Actually, this sounds way more interesting. I suggest changing this feature request to Scars/Scarring for Humans. Like how there should/could also be some marks on Androids when attacked by sharp weapons.
