### ISSUE TITLE
Humans don't die if stabbed through head near the cheeks

### ISSUE THREAD

**Issue by TamasB14** [studio-minus/ppg-bugs-and-requests#640]
**Describe the bug**
If I stab humans in the face at the cheeks, even though the sharp object goes through the brain, they survive.

**Clearly describe how to reproduce the bug**
Spawn a Human
Spawn a Sword
Stab the sword through the front of his head, near the mouth's place

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: Win7
 - Game version: Latest
 - GPU: Radeon 7850
 - CPU: Fx-4320

**Additional notes**
![dontdie](https://user-images.githubusercontent.com/26002677/147360332-8b368990-b832-4ab4-b153-0474d738ad2d.png)

You can clearly see how the sword passed the vital area, yet did not die. Out of 8 tries, all 8 survived

**Comment by mestiez** [comment]
Technically identical to #343
