### ISSUE TITLE
Weird detector signal bug

### ISSUE THREAD

**Issue by Nicovw321** [studio-minus/ppg-bugs-and-requests#644]
**Describe the bug**
The detector signal can't pass through a fuse, like it doesn't activate anything.

**Clearly describe how to reproduce the bug**
connect a detector to a fuse, and the fuse to something else and that something else won't get activated when the detector goes off, though the fuse does pop.

**Mod list**
Working Spraycans MOD, Object Possesor And Earthquake ... (hah, tl;dr), Object Editor, OCM, Raw Pink Liquids, Quick Right Click Options, Quality of Life Items, Scream Mod, Gentle Drag, Metal Things Mod, Flipping Heck, Taser, Aimbot Gun, Human Tiers, Skittle's Syringe Mod, PPG Spy Mod, Hazmat Mod Remastered, Time Accelerator, Active Humans, Overdose.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22.3
 - GPU: Radeon RX 570 Series
 - CPU: AMD Ryzen 5 2600

**Additional notes**
**OH I FORGOT, you need to be at 1% speed**
https://user-images.githubusercontent.com/89240410/147394896-865e2e02-6799-4b7d-b848-ec46db24427f.mp4

**Comment by DindinYT37** [comment]
Propagation wires have delays, fuses get destroyed instantly. Usually it happens in the same frame so the game just lets the signal slide through, but in slow motion there are enough frames to display the delay of the propagation wires which also means that the propagation happens at a later time/frame than the actual destruction of the fuse.

**Comment by Nicovw321** [comment]
> Propagation wires have delays, fuses get destroyed instantly. Usually it happens in the same frame so the game just lets the signal slide through, but in slow motion there are enough frames to display the delay of the propagation wires which also means that the propagation happens at a later time/frame than the actual destruction of the fuse.

still, when the signal passes throu- it doesnt... and only with the detector so maybe it's just a bug of the detector's signal or something

**Comment by Nicovw321** [comment]
oh apparently it happens when there's a continous signal, not just one pulse of it
https://user-images.githubusercontent.com/89240410/147421749-766d5b41-106c-4ae0-a3d3-aad3dbac5096.mp4

**Comment by mestiez** [comment]
seems to work now?
