### ISSUE TITLE
zoom thing

### ISSUE THREAD

**Issue by citizenthe** [studio-minus/ppg-bugs-and-requests#645]
im trying to make a mod, but when i zoom out of the guns it shows some random white outline that i found annoying 
![image](https://user-images.githubusercontent.com/96728876/147473236-8dd7b041-a0e9-405c-baec-7ac01ad11910.png)
![image](https://user-images.githubusercontent.com/96728876/147473278-d14d4d90-26d4-4644-9d64-7d21c3fe1ade.png)

is there any way to fix this?

**Comment by EfeYks534** [comment]
Your gun is too high quality. Make its sprite smaller, like 20x20 or something.

**Comment by citizenthe** [comment]
> 

no

**Comment by Nicovw321** [comment]
i mean, this is not how you report a bug but uhh-

**Comment by TheBeeThat** [comment]
> > 
> 
> no

then no fixing for you

**Comment by mestiez** [comment]
This looks like a mipmapping issue. Try making the transparent pixels around your sprite black, but still transparent (rgba value (0,0,0,0))

**Comment by citizenthe** [comment]
thank you, it worked! :)
