### ISSUE TITLE
Magnet power and range should be configurable. 

### ISSUE THREAD

**Issue by TotallyNotALier** [studio-minus/ppg-bugs-and-requests#646]
**Feature description**
There should be two context menu options to change range and power of electromagnet. 

**Feature purpose**
It would be a nice addition to the game and it will be easier to build some contraptions. 

**Additional context**
No.

**Comment by CUBE0R** [comment]
electricity :0

**Comment by TotallyNotALier** [comment]
> electricity :0

You cannot directly change one of parameters. Also you cannot lower them.
