### ISSUE TITLE
Air and air resistance 

### ISSUE THREAD

**Issue by YourLocalPlonker** [studio-minus/ppg-bugs-and-requests#648]
Based on the ratio of Height and Length of an object each side of it will have a different air resistance and less dense materials will have a lower terminal velocity and slower acceleration because less force is required to slow it down. I'm pretty sure there is formulas for that and I would not recommend to give objects an constant air resistance value for each side but a variable because objects can be resized.
In the environment air pressure could be added and in settings the units can be changed (e.g Bar, Psi. kPa, etc.).
Humans and any other living things will start dying if the air pressure is too low. It wouldn't be bad if there was no bubbles in the water if the air pressure is 0. An type of view could be added, which shows air resistance of an object as an arrow and it becomes longer the stronger it is. Air resistance would only apply to objects with collision. Also an option that can switch between air on or off.

This feature would add realism to the game and I am aware that this is not very easy and I also do not expect it to become real because it might also cause performance issues.

**Comment by mestiez** [comment]
This is defintely possible but I don't think the processing cost is worth it.
