### ISSUE TITLE
Vibration Part

### ISSUE THREAD

**Issue by kajetus06** [studio-minus/ppg-bugs-and-requests#649]
**Feature description**
Industrial generator but without electricity generation just vibrations that intensity of them be set in part settings.

**Feature purpose**
To build better vehicles that can vibrate and don't generate heat.

**Additional context**
currently when i use industrial generator to make vibrations i need to make it without collisions otherwise when it accidentally touches anything it electrifies all humans inside. vibration part would not have that problem

**Comment by mestiez** [comment]
The liquid pump vibrates but it also makes noise.
