### ISSUE TITLE
SimpleLightingEmitterBehaviour is misspelt.

### ISSUE THREAD

**Issue by Aspa102** [studio-minus/ppg-bugs-and-requests#650]
**Describe the bug**
You've misspelt lightning. This actually made me think that the behaviour did something else.

**Clearly describe how to reproduce the bug**
Read the name of the monobehaviour "SimpleLightingEmitterBehaviour".

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

[Uploading exported game debug info.md…]()

**Additional notes**
I'm sorry, but I couldn't think of any way to properly tell you this, other than in the form of a bug report. Since when I saw this behaviour and thought it did something else, I'd assume other people would as well.

**Comment by Nicovw321** [comment]
i think it's left like this because i'm certain it will break most mods, maybe just adding one with the new game and keep the old one would be enough

**Comment by mestiez** [comment]
Oops, I'll fix this without breaking everything
