### ISSUE TITLE
Problem with the infrared thermometer

### ISSUE THREAD

**Issue by Paulyfisk** [studio-minus/ppg-bugs-and-requests#653]
When spawning the infrared thermometer is reversed with q, the value on the infrared thermometer is upside down.

Select infrared thermometer
Press q
Observe

**Mod list**
Active Humans

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22.3
 - GPU: NVIDIA GeForce GTX 1650
 - CPU: AMD Rysen 5 4600H

**Additional notes**

**Comment by Lebozored13** [comment]
Unfortunately, this happens with everything. Their sprites get flipped when you press q to spawn them.

**Comment by mestiez** [comment]
Not a bug. Just flipped text being on flipped objects
