### ISSUE TITLE
More destructables

### ISSUE THREAD

**Issue by alikeobservant** [studio-minus/ppg-bugs-and-requests#655]
**Feature description**
This game desperately needs more destructible items, such as destroyable metal.
**Feature purpose**
The purpose of this is to make destructible buildings more satisfying to crumble and also easier to create. Having something like a metal pole that will snap under enough pressure would be great.

**Comment by YourLocalPlonker** [comment]
I think metal rather is going to bend than to snap

**Comment by TotallyNotALier** [comment]
> I think metal rather is going to bend than to snap

Yes, bendable objects should be in the game. Not sure if it is hard to code.

**Comment by mestiez** [comment]
You need to be more specific
