### ISSUE TITLE
"Brain" link - new tool. 

### ISSUE THREAD

**Issue by TotallyNotALier** [studio-minus/ppg-bugs-and-requests#656]
**Feature description**
You will be able connect limbs to human head with this tool, so they can be controlled by brain. If you connect dismembered limb to alive and conscious human head using this tool, it will become alive. 

**Feature purpose**
For example, you will be able to create mutants with many legs or arms. Transplantation of limbs will be possible. Currently, transplantation is not possible because humans can't (obviously) control dismembered limbs . 

**Additional context**
No.

**Comment by DavidCo113** [comment]
Ok. How are the limbs going to be moved, exactly?

**Comment by TotallyNotALier** [comment]
> Ok. How are the limbs going to be moved, exactly?

Just connect limb using ropes to human and it will be moveable. However, if you use this tool, limb will always be alive and controlled by animation.

**Comment by mestiez** [comment]
It's probably a better idea to have blood vessel wires also transmit brain signals.
