### ISSUE TITLE
Heart & Brain glitch

### ISSUE THREAD

**Issue by Cyaut0** [studio-minus/ppg-bugs-and-requests#658]
Whenever I spawn in a human, their brain/heart is for some reason, never in their body. I have to put it back in their body manually using slo-mo and it is really quite aggravating.

**Comment by UniDuki** [comment]
There is no heart or brain (that you can see or interact with). If you have expanded gore on; expanded gore isn't fully supported, and probably never be fixed.

**Comment by alikeobservant** [comment]
> There is no heart or brain (that you can see or interact with). If you have expanded gore on; expanded gore is discontinued, and the bugs will probably never be fixed.

It's discontinued? That sucks. Expanded gore was a super cool concept
