### ISSUE TITLE
(Bendable) Metal Plate

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#659]
**Feature description**
Bendable metal plate. Actually looks like a long stick. Split into multiple parts (seamlessly until bent), parts are connected to eachother with very strong joints. Too hot temperatures decrease joint "strength" but increase breaking force. Too low temperatures increase joint strength but decrease breaking force. All parts that are still connected to eachother should share the same physical properties (electricity, heat etc.)

**Feature purpose**
Allows for "flexible" contraptions that can bend but not break which leads to more possibilities with how things can be designed.

**Additional context**
No need for additional context.

**Comment by TamasB14** [comment]
Not bad, but that's multiple objects connected to eachother with bonds with dynamic personalities, which might be somewhat hard to make.
