### ISSUE TITLE
Objects block light

### ISSUE THREAD

**Issue by alikeobservant** [studio-minus/ppg-bugs-and-requests#660]
**Feature description**
The light coming from light sources cannot pass through objects.
**Feature purpose**
Makes the game much more realistic and makes it easier to create lighting.

For example, the light in the topleft room should not be able to light up the bottom room
![image](https://user-images.githubusercontent.com/89762931/148009120-16253820-13b6-4b4f-8c53-ae887d5bb1e6.png)

**Comment by evactouch** [comment]
It would probably be hard to make, but would be really cool.
