### ISSUE TITLE
Accelerator will fire randomly with activation signals

### ISSUE THREAD

**Issue by DavidCo113** [studio-minus/ppg-bugs-and-requests#663]
**Describe the bug**
The Accelerator weapon will randomly fire while charging with a constant activation signal sent to it

**Clearly describe how to reproduce the bug**
 - Connect an Activation Toggle to an Accelerator with propagation wire
 - Turn on the toggle
 - Wait for a bit or just type in the toolbox's search bar

**Mod list**
All mods have been disabled and the game has been restarted

**System info**
 - Operating system: Arch Linux with Proton Experimental
 - Game version: 1.22.3
 - GPU: NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2
 - CPU: 16 × AMD Ryzen 7 5700G with Radeon Graphics

**Comment by DindinYT37** [comment]
That's because the game is saying "Too many activation signals" which technically turns the wire off for a small amount of time, resulting in it shooting because of the lack of signals.

**Comment by DavidCo113** [comment]
> That's because the game is saying "Too many activation signals" which technically turns the wire off for a small amount of time, resulting in it shooting because of the lack of signals.

The game did not say "Too many activation signals".

**Comment by DindinYT37** [comment]
> > That's because the game is saying "Too many activation signals" which technically turns the wire off for a small amount of time, resulting in it shooting because of the lack of signals.
> 
> The game did not say "Too many activation signals".

Doubt, but I'll check just in case.

**Comment by mestiez** [comment]
This happens mainly because of design flaw #9543: there is no reliable way for an object to tell if it has stopped receiving activation signals. It can only detect the initial activation signal and continuous signals.

When the game skips a few frames, even unnoticably so, the Accelerator could interpret that as an end signal. This is why it shoots randomly for OP, their framerate is unstable.

**Comment by DindinYT37** [comment]
I see, it makes sense that the framerate gets unstable for some frames when typing something into the toolbox's search bar since the it has to index all the objects, especially with many mods like I have.

**Comment by mestiez** [comment]
Fixed
