### ISSUE TITLE
Ash

### ISSUE THREAD

**Issue by HelpMeNowThanks** [studio-minus/ppg-bugs-and-requests#664]
**Feature description**
Ash when you burn humans with high enough temperature. The ash would be like blood particles but grey, so they just stick to whatever object they’re on

**Feature purpose**
I want to be able to burn humans so they turn into ash at high enough temperature (around 600-900 degrees C). The purpose is to make realistic cremation.

**Additional context**
None

**Comment by Glowinspace97** [comment]
Would be laggy if there is so many cloned pixels. but i support this

**Comment by atwal6400** [comment]
> **Feature description** Ash when you burn humans with high enough temperature. The ash would be like blood particles but grey, so they just stick to whatever object they’re on
> 
> **Feature purpose** I want to be able to burn humans so they turn into ash at high enough temperature (around 600-900 degrees C). The purpose is to make realistic cremation.
> 
> **Additional context** None

this could work since one of zoois old games had a game that was physics based with cloned pixels

**Comment by atwal6400** [comment]
> > > **Feature description** Ash when you burn humans with high enough temperature. The ash would be like blood particles but grey, so they just stick to whatever object they’re on
> > > **Feature purpose** I want to be able to burn humans so they turn into ash at high enough temperature (around 600-900 degrees C). The purpose is to make realistic cremation.
> > > **Additional context** None
> > 
> > 
> > this could work since one of zoois old games had a game that was physics based with cloned pixels
> 
> you're thinking of cellular automata, which is a completely different thing from particles

im actually referring to this game https://mestiez.itch.io/falling-sand

**Comment by BBQGiraffe** [comment]
> > > > **Feature description** Ash when you burn humans with high enough temperature. The ash would be like blood particles but grey, so they just stick to whatever object they’re on
> > > > **Feature purpose** I want to be able to burn humans so they turn into ash at high enough temperature (around 600-900 degrees C). The purpose is to make realistic cremation.
> > > > **Additional context** None
> > > 
> > > 
> > > this could work since one of zoois old games had a game that was physics based with cloned pixels
> > 
> > 
> > you're thinking of cellular automata, which is a completely different thing from particles
> 
> im actually referring to this game https://mestiez.itch.io/falling-sand

that is in fact cellular automation

**Comment by DindinYT37** [comment]
> Would be laggy if there is so many cloned pixels. but i support this

You know, it doesn't have to be per 1 pixel. For example, if there were a setting that the user can customize and he sets it to **2**. Then the minimum size of a singular "Ash bit" would be **2x2**. Of course it would still lag, but it would allow the user to customize it on their own according to their will, but it should also be generally toggleable.
