### ISSUE TITLE
Audio settings is found in every setting category apart from general (rare)

### ISSUE THREAD

**Issue by Roozz1** [studio-minus/ppg-bugs-and-requests#666]
**Describe the bug**
Upon going into settings, all settings found in the audio category are gone, apart from one setting, master volume.
The audio settings also replace the general settings, video settings, but not control settings.

I assume this is rare, as this has only happened to me once (the day of making this issue) out of my 1-2 years of playing this game.

**Clearly describe how to reproduce the bug**
1) Load up People Playground... obviously
2) Go to settings
3) Go to either the audio category, video category or general category and you will see that there are no settings apart from master volume, control settings is unaffected (probably rare)

**Mod list**
Sorry, I got way too many mods and I'm too lazy to write out each individual one, although I will provide a link to a video that goes through all of them:
https://gyazo.com/e57c6af0c96a25d72853f36d7abcb32d
(i also got a bunch of contraptions, both workshop and local, if that helps. also when i say "a bunch", i mean **a bunch**)

**System info (please complete the following information)**
 - Operating system:  Windows 10
 - Game version: 1.22.3 (im also in beta)
 - GPU: NVIDIA GeForce GTX 1660
 - CPU: Intel i5 9400F

**Additional notes**
Image of bug:
![image](https://user-images.githubusercontent.com/89425262/148586299-3cec038a-510a-4347-b833-29336eba5425.png)

Bug is most likely extraordinarily rare because as I said before, I've only encountered this once (the day this post has been made) out of my 1-2 years of playing this game.

**Comment by mestiez** [comment]
Please click this button:
![image](https://user-images.githubusercontent.com/32131519/148586579-da40e96d-952f-4be7-b8e4-cde326fa7ba0.png)

It will export all of the information that I need

**Comment by Roozz1** [comment]
Sure, but quick thing, this was exported just now after I restarted my game to get rid of the bug, heres the file anyway
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7830564/exported.game.debug.info.md)
:

**Comment by Roozz1** [comment]
Didn't realise until now, but most of my settings have reset, not the graphics options though.

**Comment by UniDuki** [comment]
This also happened to me before. I could load into any map but do nothing, not move the camera, not select tools, not place anything, nothing... apart from open the settings menu that looked like that.

**Comment by mestiez** [comment]
Closing until there is a way to reproduce this reliably
