### ISSUE TITLE
Vsync not working

### ISSUE THREAD

**Issue by TheBeeThat** [studio-minus/ppg-bugs-and-requests#667]
**Describe the bug**
Hello, for some reason my vsync is not working. Its on, i turned it off and on but still doesnt work.
![image](https://user-images.githubusercontent.com/96020070/148590013-daf327f4-b771-4a29-9539-9892fae16e16.png)
![image](https://user-images.githubusercontent.com/96020070/148590049-1de30a7c-85be-44f7-bc64-682716a6fa4f.png)

**Clearly describe how to reproduce the bug**
No idea

**Mod list**
50+
I dont know a way to copy and paste the mod names, sorry

**System info (please complete the following information)**
 - Operating system: Windows 11 64 Bit
 - Game version: 1.22.3
 - GPU: GT 740 4GB
 - CPU: Intel i-5 4460

**Additional notes**
Here is the game debug info just incase
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7830672/exported.game.debug.info.md)

**Comment by mestiez** [comment]
What do you mean by "not working"?  What do you expect it to do and what does it actually do?

**Comment by TheBeeThat** [comment]
> What do you mean by "not working"? What do you expect it to do and what does it actually do?

My monitor is 60Hz, Vsync should keep the fps at 60 and that causes screen tearing.
It wasn't like this and for some reason it doesn't work now.

**Comment by mestiez** [comment]
I've never been able to reproduce this
