### ISSUE TITLE
blood regaining

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#669]
**Feature description**
blood in humans should regain very slowly over time to 100%' as long as the human is not bleeding.
**Feature purpose**
to allow humans to naturally recover blood from severe blood loss.

**Additional context**
this along with all the other self healing mechanics in place aka regaining integrity naturally' and healing wounds naturally could all be apart of a option in the settings named something such as "natural healing mechanics".

**Comment by fhgb54643689** [comment]
this still does not have the accepted feature tag

**Comment by DindinYT37** [comment]
> this still does not have the accepted feature tag

I think it may be because humans don't regain blood fully but it should be marked as accepted, yeah.

**Comment by mestiez** [comment]
sorry. there are just so many issues these days
