### ISSUE TITLE
Archelix Caster sometimes creates an argument error when shooting humans

### ISSUE THREAD

**Issue by Aspa102** [studio-minus/ppg-bugs-and-requests#674]
**Describe the bug**
Sometimes when using the archelix caster, a "Value cannot be null" error occurs. Once this bug occurs, it will occur every time a human is hit by the gun's projectile.

![image](https://user-images.githubusercontent.com/79403796/149076953-ef4d8c6e-e09f-4a56-9477-4d617367e73f.png)

**Clearly describe how to reproduce the bug**
The bug actually occurs like randomly, so maybe try shooting humans and stuff + modded humans and other living things.

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/7852258/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
Bet the human tries to collide with the projectile, but the projectile's collider has a higher priority so it fires its function first which deletes the collider/projectile and it's gone before the human could react but the human knows it collided

**Comment by mestiez** [comment]
@Aspa102 now that you have access to the source code you can fix this if it occurs again. however i have never been able to replicate this and i will close this issue until its easily reproducible.
