### ISSUE TITLE
Make the power of electromagnets scale with their size

### ISSUE THREAD

**Issue by WWWOWWWPL** [studio-minus/ppg-bugs-and-requests#675]
**Feature description**
The power / range of electromagnets changes with resizing. Small magnets would have a tiny range, but big ones can influence the entire map.

**Feature purpose**
Right now, no matter how small electromagnets are they always pull / repulse metal objects within the same exact range, which means using them in any non-stationary contraption that's made out of metal objects is very unfeasible as everything would just get pulled towards the magnet (unless you wired EVERYTHING to it with fixed wires). Making the electromagnet pulling / repulsing radius scale with resizing would allow players to make much more compact and crash-free assemblies such as railguns or cranes.

**Additional context**
probably a duplicate of #646, but im not sure

**Comment by mestiez** [comment]
this would destroy lots of railguns that depend on tiny magents
