### ISSUE TITLE
Additional support for chemistry for mods

### ISSUE THREAD

**Issue by Dawid23-Gamer** [studio-minus/ppg-bugs-and-requests#678]
**Feature description**
I want for the chemistry code to support creating the **existing + existing = new** as well as **existing + existing = existing** combos for chemistry mixes. It could be done by having a new line of code allowing you to create any mixes by putting a behaviour in the liquid containers or considering that only 3 mixes exist in current code modifing the current code to support something like this

**Feature purpose**
So I have noticed that no chemistry mods exist and wanted to be the one who made the first one but quickly realized the restrictiveness of the code. I know that the game isn't specifically designed to think of mods at every step but this is real restriction of creativity that should be lifted. It is a sandbox game after all

**Additional context**
Yes, I am the guy that e-mailed you earlier

**Comment by Aspa102** [comment]
Doesn't it already have functionality for that?
I am pretty sure I've used it before to mix multiple liquids into a new liquid.

**Comment by Dawid23-Gamer** [comment]
> Doesn't it already have functionality for that? I am pretty sure I've used it before to mix multiple liquids into a new liquid.

Well you can make mixes for new liquids, but you can't make mixes with existing liquids, like you can't make a 100% chemistry-only mod as of now because you can't add existing + existing mixes.

**Comment by mestiez** [comment]
It was probably possible, just unnecessarily difficult and hacky.
