### ISSUE TITLE
In-game Workshop page opener

### ISSUE THREAD

**Issue by Jandro22** [studio-minus/ppg-bugs-and-requests#679]
**Feature description**
Allow the player to click on a button in the workshop creation section to be transported to that items workshop page. It would be placed directly to the left of the "X" (Shown in picture below)
![image](https://user-images.githubusercontent.com/53024346/149858622-d158963e-914b-4993-af67-7ca820fedfe0.png)

**Feature purpose**
There are so many items that have controls that are only specified in the description, such as jets, tanks, and various other vehicles. If there was an easy way to quickly open their respective workshop pages to see their controls, I think that could be really useful.

**Comment by DindinYT37** [comment]
I suggest it to put in the bottom right, other than that I agree.
