### ISSUE TITLE
Water Reacts To Electric

### ISSUE THREAD

**Issue by Whelchur** [studio-minus/ppg-bugs-and-requests#683]
**Feature description**
It would be nice if we throw a Generator (industrial generator, generator, battery, etc.) into the water and when that generator is on, it can electrify all the water.

**Feature purpose**
When I Throw an Open Generator into the Water, None of the People in the Water Died, Only the People Who Touched the Generator Died.

**Additional context**
Since the electricity of the generator will spread over all the water, only thirty or fifty percent of the electricity created by the generator should be effective in the water.

**Comment by mestiez** [comment]
This already happens. It's not very intense and a bit infrequent.
