### ISSUE TITLE
Bug when resizing multiple objects

### ISSUE THREAD

**Issue by Nicovw321** [studio-minus/ppg-bugs-and-requests#684]
**Describe the bug**
There's no limit! you can make them as tiny as possible and at a certain point they just bug out and "dissapear".

**Clearly describe how to reproduce the bug**
https://user-images.githubusercontent.com/89240410/150275706-123b31fc-2e2d-4a71-827e-f7ac899a65ef.mp4

**Mod list**
Working Spraycans MOD, Object Editor, OCM, Raw Pink Liquids, Quick Right Click Options, Quality of Life Items, Scream Mod, Gentle Drag, Metal Things Mod, Flipping Heck, Taser, Aimbot Gun, Human Tiers, Skittle's Syringe Mod, PPG Spy Mod, Hazmat Mod Remastered, Time Accelerator, Active Humans, Overdose.

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.22.3
 - GPU: Radeon RX 570 Series
 - CPU: AMD Ryzen 5 2600

**Additional notes**
I like turtles

**Comment by UniDuki** [comment]
Please don't fix this "bug", I really like having super super tiny stuff :(

**Comment by mestiez** [comment]
its kind of fun to make things inifnitely tiny and see the game cry
