### ISSUE TITLE
New detection methods + Radiation

### ISSUE THREAD

**Issue by D3stStrut** [studio-minus/ppg-bugs-and-requests#685]
**Feature description**
New mechanic/system + spawnable(s)

**Feature purpose**
The purpose of this feature is to expand the detection category of the game and build on the already existing interest of nuclear bombs in ppg. This will be split into two parts as I want to fit 2 suggestions into one.

1. Radiation.
Pretty simple, a way of putting radiation somewhere (I.E Power, process such as decay or bomb) and getting rid of it (perhaps using the existing liquid system or a device to get radiation out of an area)

Damages humans overtime, damages electronics, varies in intensity. It could be implemented like the system of temperature where it lingers in an area after an event happens, can be set as an ambient setting or just leftover from processes and events.

MORE INFORMATION BY REQUEST OF MESTIEZ:

Radiation is NOT the same thing as radioactivity. Radiation is the energy and radioactivity is the process of emitting energy.
So therefore, radioactive objects emit radiation but radiation doesn't make things radioactive.

Radiation starts decaying INSTANTLY but very slowly.

The particle spoken about in this suggestion is Alpha particles. Otherwise it wouldn't be fun to irradiate your doll. 

Possible spawnables:
Geiger counter, detects radiation in a 3m diameter and starts making noise after radiation value is at a point where it is harmful to humans. Displays radiation level on small screen.

Radiation detector, sends an activation signal after a certain value of radiation set by the player is exceeded in a diameter set by the player. 

Radiation suppressor, slowly eliminates radiation in an area somehow. Up to you on how to implement it.

Lead rod, can block and insulate from radiation. Radiation cannot enter or exit a room filled with lead lining.

Final notes on radiation:
"Take radiation damage" setting on machinery can be turned off in case you are planning to use it in high radiation environments.

**Additional context**
N/A.

**Comment by mestiez** [comment]
Please don't group feature requests.

Some proposed changes to/comments on your radiation feature request:

- There should be a defined difference between radioactivity and radiation.
- Radioactive objects emit radiation. 
- Radiation does not cause radioactivity. 
- Radiation decays instantly. If it isn't constantly being created, there should be no radiation. 
- Radioactivity decays extremely slowly.
- Radiation has an amplitude and frequency. Not all radiation is harmful. Only specific ranges of frequencies and amplitudes cause damage to specific objects.

Perhaps the radiation field is only updated every 1/10th of a second, on a background thread. The radiation field resolution should depend on the amount of objects in that area (probably using a quad tree).

**Comment by D3stStrut** [comment]
> Please don't group feature requests.
> 
> Some proposed changes to/comments on your radiation feature request:
> 
> * There should be a defined difference between radioactivity and radiation.
> * Radioactive objects emit radiation.
> * Radiation does not cause radioactivity.
> * Radiation decays instantly. If it isn't constantly being created, there should be no radiation.
> * Radioactivity decays extremely slowly.
> * Radiation has an amplitude and frequency. Not all radiation is harmful. Only specific ranges of frequencies and amplitudes cause damage to specific objects.
> 
> Perhaps the radiation field is only updated every 1/10th of a second, on a background thread. The radiation field resolution should depend on the amount of objects in that area (probably using a quad tree).
> 
> If it isn't already obvious, I've been playing with the idea of a "proper" radiation system for a while now. There exists a vague implementation of it in the game already, but it isn't activated or finished.

I completely understand and will make the changes. Thank you for looking over it.
