### ISSUE TITLE
activation toggles using too much wire signals

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#691]
**Describe the bug**
connecting activation toggles to a few objects causes them to overload the limit very very fast and rendering contraptions using these mostly useless

**Clearly describe how to reproduce the bug**
simply spawn in 1 or 2 activation toggles and hook them up to around 4 or 5 machines

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: windows 11
 - Game version: 1.22.3
 - GPU: gtx 1650 super
 - CPU: i5

**Additional notes**

**Comment by mestiez** [comment]
This is such a disaster. I've explained before why this happens and what needs to be done to solve it:

https://github.com/studio-minus/ppg-bugs-and-requests/issues/701#issuecomment-1024269216

**Comment by mestiez** [comment]
Fixed...

**Comment by fhgb54643689** [comment]
> Fixed...

tysm man

**Comment by fhgb54643689** [comment]
unsure if this is in the next update but this issue still persists to this day unfortunately.
