### ISSUE TITLE
Always show recompile button, Or eneable it in the settings

### ISSUE THREAD

**Issue by CrunchToast** [studio-minus/ppg-bugs-and-requests#694]
**Feature description**
Always show the recompile button at the mods tab.

**Feature purpose**
I am a mod creator and every time I want to change a little thing I need to exit the game wait for all the mods to compile and then get into a map, So could you please make it always visible so I could just recompile my mod and load to a map. Thanks

**Comment by UniDuki** [comment]
#589 "Unfortunately this is not possible with the current system. It's possible with AppDomains and stuff but that's not how the system works right now."
