### ISSUE TITLE
Destructable cables

### ISSUE THREAD

**Issue by Trevor-01** [studio-minus/ppg-bugs-and-requests#696]
**Describe the bug**
Destructible cables break when the object they're attached to heats up. I'm not sure if this is a feature but if it is, it doesn't work correctly. For example, if the object is heated up with a heat-ray, the destructible cable will never break. But with only a second of heating it with a truster, it will? And then even weirder once cooled down to room temperature again, you can never put another destructible cable on the host (The object you first started the cable on) object. This also happens with pink explosions. Another thing I noticed is when an object is heated to an extremely high temperature with a heat ray, the moment you heat it with a thruster, it gets lowered to zero and then heated up by to the rate of said thruster

**Clearly describe how to reproduce the bug**
Get two objects, connect them with any destructible cable. If they are frozen, they will sometimes not break while heating with a thruster but the moment they are unfrozen, the cable breaks (Just don't have the objects frozen). Then heat one of the objects with a thruster and the cable will break. You will not be able to reattach a destructible cable even once it's cooled down.

**Mod list**
I turned every mod off and the bug still occurred.

**System info (please complete the following information)**
 - Operating system: Windows
 - Game version: 1.22.3
 - GPU: GFORCE RTX 2060
 - CPU:11th gen intel core i5

**Additional notes**

**Comment by mestiez** [comment]
Temperature has no effect on destructible constraint strength. The "burn progress" is what matters and thrusters (among other things) affect this value. Not a bug, just an unintuitive feature.

**Comment by Trevor-01** [comment]
Oh alright, thanks.
