### ISSUE TITLE
Different Blood types - A, B, AB, O

### ISSUE THREAD

**Issue by BugMan33** [studio-minus/ppg-bugs-and-requests#697]
**Feature description**
Every Human will now have _**different blood type.**_  **_Blood types will affect mutations, abilities and evolution of the humans._** For example if the human has **_A blood type_** or **_B blood type_** he will **_have different reaction from the zombie syringe than the AB blood type_** or **_O blood type_**. Every human will now have **_have different regeneration speed_** , **_different durability_** or _**different strength**_. For example if the human has **_AB blood type_** he will **_evolve into super zombie_** ( more durable , harder to break into parts ) . . . If the human has **_O blood type_** he will become **_super human if you inject him with Tritium and he will not die from it._**

**Feature purpose**
I think that the **_humans need some upgrade_** and if they can _**have different abilities than other humans**_, **_every single human will be special_** ( different blood type , different height . . . ). **_I think that not every human can be hulk_**. 

**Additional context**
I personally think that this is **_good feature idea_** because **_every human is different._** In this game it is like if they were **_made in 1 factory._**

**Comment by 404CoderNotFound** [comment]
**Why** are **you** using **so much** bold **text**?

**Comment by TheBeeThat** [comment]
> In this game it is like if they were **made in 1 factory.**

well im sure the ppg humans arent actual humans and they are made in the lab.

**Comment by mestiez** [comment]
This was very **_hard to read_**
