### ISSUE TITLE
Quick Select Object

### ISSUE THREAD

**Issue by UniDuki** [studio-minus/ppg-bugs-and-requests#699]
**Feature description**
A new key bind that when pressed will set the object in your hand to whatever your cursor is hovering over at the moment.

**Feature purpose**
Small quality of life change, it will be faster to switch between objects if you're using the same ones lots on a building.

**Additional context**
By 'object in your hand' I mean the box next to the mouse/wire at the top with the item you currently are able to place down.
If that didn't make sense, it's like middle clicking in Minecraft, assuming you know what that does.

**Comment by mestiez** [comment]
Oh like an eye dropper? That's a good idea

**Comment by UniDuki** [comment]
🤦‍♂️I'm stupid. Yes that's what it's called! An eyedropper!

**Comment by D3stStrut** [comment]
bro this guy got one suggestion accepted and is now becoming the suggestion police

**Comment by mestiez** [comment]
> bro this guy got one suggestion accepted and is now becoming the suggestion police

If by suggestion police you mean correctly pointing out that a suggestion is a duplicate then I wish everyone were suggestion police.
