### ISSUE TITLE
option to turn off propagation wire limits

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#701]
**Feature description**
a new setting which when turned on will make the propagation wire limit either much higher or infinite

**Feature purpose**
to allow players to have much more advanced creations at their own computers expense

**Additional context**
as of now most big contraptions do not work as intended due to the wire signal limit going way above and causing many things to break

**Comment by mestiez** [comment]
This is a bad solution. The real problem is design flaw eight trillion: framerate dependent continuous activation signals.
I have to redesign and rewrite the entire activation signal system so that it eats less CPU time and allows for a nearly unlimited amount of simultaneous signals.
