### ISSUE TITLE
Snap to center of mass with frozen objects is bugged

### ISSUE THREAD

**Issue by EfeYks534** [studio-minus/ppg-bugs-and-requests#702]
**Describe the bug**
Using the snap to center of mass feature with pins on frozen objects snaps the pin to a completely different location on the map (I didn't look at where it is yet but I'm positive it's 0,0)

**Clearly describe how to reproduce the bug**
Spawn an object
Freeze the object
Hold the keybind for snap to COM
Put pin on the object
Pin is in completely different location
Unfreeze the object

**Mod list**
No mods need to be present for this bug to happen

**System info**
 - Game version: 1.22.3

**Additional notes**
I think this is caused by COM being at 0,0 on frozen objects. Although detail view shows COM to be the same as virtual center, I'm pretty sure it's not

**Comment by mestiez** [comment]
i couldnt reproduce it but i assume it was fixed along with other COM issues
