### ISSUE TITLE
Reattaching limbs

### ISSUE THREAD

**Issue by EGGWIGGLY** [studio-minus/ppg-bugs-and-requests#709]
**Feature description**
a new tool or tools that re connect limbs so that they stay alive

**Feature purpose**
so that people can reconnect limbs and mix different limbs like a cyborg and keep the reattached limb alive

**Additional context**
it gives people more things to do in the game and in my opinion it would make the game way more fun

**Comment by UniDuki** [comment]
I'm not sure whether your asking for reattaching limbs or prosthetics, but either way I'd call this a duplicate, here's a few very similar requests;
-  #629
- #435
- #254

**Comment by D3stStrut** [comment]
> I'm not sure whether your asking for reattaching limbs or prosthetics, but either way I'd call this a duplicate, here's a few very similar requests;
> 
> * [limb regrowth syringe #629](https://github.com/studio-minus/ppg-bugs-and-requests/issues/629)
> * [Working transplantation #435](https://github.com/studio-minus/ppg-bugs-and-requests/issues/435)
> * [Prosthetic Limbs #254](https://github.com/studio-minus/ppg-bugs-and-requests/issues/254)

Dude what a killjoy.
