### ISSUE TITLE
Resize collisions

### ISSUE THREAD

**Issue by D3stStrut** [studio-minus/ppg-bugs-and-requests#712]
**Describe the bug**
Resize tool does not scale the collision model properly

**Clearly describe how to reproduce the bug**
Resize something

**Mod list**
N/A

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: Beta
 - RX 580 8GB
 - i5-9400F

**Additional notes**
N/A

**Comment by UniDuki** [comment]
This only happens with soap for me. Every other resized object has perfect hitboxes. Unless you're talking about the green outline?

**Comment by mestiez** [comment]
This happens with specific colliders such as circles or rounded rectangles. This cannot be solved.
