### ISSUE TITLE
what if there was a campaign mode

### ISSUE THREAD

**Issue by BrunchIsLiteralBalls** [studio-minus/ppg-bugs-and-requests#714]
**Feature description**
campaign mode for people playground. you had to achieve a certain goal to get to then next level. like kill this human or something or create a black hole. it would only let you use certain maps and certain tools. in most levels (it should) after 5 fails it will give you a hint, and after 10 it will let you skip. maybe every completed level in the campaign mode will give you an item to use in sandbox.
**Feature purpose**
maybe for the people who dont like sandbox games they could play the campaign and have some fun instead of refunding the game
**Additional context**
this suggestion is a stupid idea

**Comment by mestiez** [comment]
the people who dont like sandbox games probably shouldnt buy a sandbox game

**Comment by Squazzyer** [comment]
> the people who dont like sandbox games probably shouldnt buy a sandbox game

gigachad

**Comment by DindinYT37** [comment]
This kind of thing would be better as a "Tutorial" mode for new users.
