### ISSUE TITLE
purple glow

### ISSUE THREAD

**Issue by devinG616** [studio-minus/ppg-bugs-and-requests#721]
whenever i move or shoot things a purple glow surrounds the item

**Comment by StupidRepo** [comment]
This happens in a game called Totally Accurate Battle Simulator (TABS) on my M1 Mac. When I spawn in a character, if it has a certain item on it, it'll glow weirdly and you can't see it. This seems to happen in PPG for you here.

Not sure if it's something to do with Unity, the game or your GPU/Computer but it doesn't happen to me

**Comment by mestiez** [comment]
Thermal vision probably

**Comment by StupidRepo** [comment]
Yeah probably

**Comment by StupidRepo** [comment]
Hey Mestiez, whilst you're online, could you please check out my FR? #722
