### ISSUE TITLE
Paralysing

### ISSUE THREAD

**Issue by debiant69** [studio-minus/ppg-bugs-and-requests#728]
A syringe that will paralyse the human, making him unable to move (he will be conscious)
You can also paralyse the human by stabbing him in the back (injuring his spiral cord)

You might ask, why not just knock him out, well this is so you can still move him around without him making funny poses without being knocked out

**Comment by fhgb54643689** [comment]
> What is the effective difference between this and being unconscious?

not having to have a knockout syringe constantly hooked up to them

**Comment by UniDuki** [comment]
I thought this already happens when you break the middle bone of the body?
