### ISSUE TITLE
bug with box

### ISSUE THREAD

**Issue by YOPLAY13** [studio-minus/ppg-bugs-and-requests#73]
**Describe the bug**
on lava map when the box breaks down his chunks are twitching

**Clearly describe how to reproduce the bug**
on video

https://user-images.githubusercontent.com/86079489/127475612-34c5fe85-a44f-4028-a411-e5766e30f44f.mp4

**Mod list**
syringes++ - off
**System info (please complete the following information)**
 - Operating system: win 10
 - Game version:1.20
 - GPU: RX 570
 - CPU: Ryzen 5 1400

**Additional notes**
idk this bug or no

**Comment by mestiez** [comment]
not really a bug but it does look bad

**Comment by mestiez** [comment]
doesnt happen anymore
