### ISSUE TITLE
Humans having some sort of seizure

### ISSUE THREAD

**Issue by PugDeity** [studio-minus/ppg-bugs-and-requests#730]
**Describe the bug**
So when i spawn a human and ONLY a human when they hit the ground the start shaking their head so hard to break their neck

**Clearly describe how to reproduce the bug**
I Have no idea but It started when I got the "Time accelerator"
**Mod list**
This is gonna be a bit long  Power pack framework Five Nights at People Play Ground MilitaryMod expansion: WARLORDS   (Undead Update 1) Extra Additions To Human Tiers
Human Tiers   Militarymod Expansion: Yugoslav wars (BOSNIAN UPDATE IS REALESED FINALLY) (1.4) Prototype humans mod        (the culprit in my opinion) Time Accelerator
  Far Cry 3 Characters mod   [ SCP-610 Mod ] (Quick Update)   Detroit: Become Human

**System info (please complete the following information)**
 - Operating system: steam
 - Game version: 1.22                  
 -  - GPU:NVIDIA GeForce GTX 960
 - CPU:Intel(R) CORE(TM) i3-6100 CPU @ 3.70GHz

**Additional notes**
This Game is REALLY fun kep on improving! :D

**Comment by mestiez** [comment]
This is likely because you have your physics iterations set to something below 16

**Comment by PugDeity** [comment]
omg im so dumb thats true i wanted to get the Genocide really fast so i tried to get  the as much of performance as possible thank you for letting me know
