### ISSUE TITLE
Bottle of The Unmatched Power of the Sun

### ISSUE THREAD

**Issue by Quid7111onDiscord** [studio-minus/ppg-bugs-and-requests#732]
**Feature description**
It looks like a bottle, any other bottle, but when you press F it burns and obliterates anything within a massive radius (the whole map dingus its the frickin' sun!)

**Feature purpose**
I thought it was funny, also based off of the comic of Bottle of The Unmatched Power of the Sun.

**Additional context**
context is that comic lol
![dfc](https://user-images.githubusercontent.com/99777529/154184466-4d831833-2d39-4a51-b56b-4e9997cb8bbd.jpg)

**Comment by Batteryaccidd** [comment]
no

**Comment by vda8** [comment]
there is prolly a mod for dis
