### ISSUE TITLE
Spawnable smoke/fog machine

### ISSUE THREAD

**Issue by Bravo-xyz** [studio-minus/ppg-bugs-and-requests#733]
**Feature description**
A spawnable item that works somewhat like the industrial generator where it emits smoke, but does not generate electricity or violently vibrate. Smoke/fog color can be edited using the context menu.
**Feature purpose**
Act as an item to enhance visuals by giving the environment as well as other contraptions more depth, i.e. smoke grenades, fog, or exhaust fumes.

**Comment by mestiez** [comment]
yes i would like to add several objects like this. fog generators, smoke generators, harmless fire generators, etc.
