### ISSUE TITLE
Weird bug with tons

### ISSUE THREAD

**Issue by dot-github** [studio-minus/ppg-bugs-and-requests#740]
**Describe the bug**
15 tons heating up and flying all over the map

**Clearly describe how to reproduce the bug**
1. put collision setting to discrete
2. place 15 tons in a pyramid shape
3. fix them together using the fixed cable
4. throw against a wall or other object

**Mod list**
[mods](https://steamcommunity.com/sharedfiles/filedetails/?id=2758287492)

**System info (please complete the following information)**
 - OS: Windows 10 Pro 64-bit | Version 21H2 | OS build 19044.1526
 - Game version: 1.22.3
 - GPU: NVIDIA GeForce 1050
 - CPU: AMD Ryzen 3 1200 Quad-Core Processor 3.35 GHz

**Additional notes**
not sure if this is the only way to reproduce the bu

example video **(EARRAPE WARNING!)**:
https://user-images.githubusercontent.com/88833629/154804736-ec00529d-d876-41cb-8321-b910e66ced03.mp4

**Comment by UniDuki** [comment]
This happens all the time with overly complex, large, fast moving or heavy contraptions.

**Comment by TheBeeThat** [comment]
unity stuff

**Comment by mestiez** [comment]
awesome

**Comment by mestiez** [comment]
cant fix this. its box2d nonsense. the best i can do (this is what most games do) is detect and try to slow down erratic physics objects
