### ISSUE TITLE
make it so light bulbs require electricity to work

### ISSUE THREAD

**Issue by debiant69** [studio-minus/ppg-bugs-and-requests#742]
**Feature description**
Describe the requested feature. Is it a new spawnable item? Is it a new map? A new mechanic or system? How does it work?

**Feature purpose**
Describe the purpose here. What made you request this feature? What is its purpose? Are you sure it doesn't already exist in some form?

**Additional context**

**Comment by mestiez** [comment]
Would this not break all existing contraptions?

**Comment by debiant69** [comment]
i always wanted to electrocute people and power light bulbs with them
