### ISSUE TITLE
Water Level/Change Water to Something else

### ISSUE THREAD

**Issue by DummyTheAllSeeing** [studio-minus/ppg-bugs-and-requests#756]
Instead of making a new map for each new liquid, why wouldnt make it as a feature to change liquid/water level on the map "Sea"?

In enviorement tab, there would be two settings exclusively for the "Sea" map.

First Setting: Would change level of the liquid, basically, making the liquid go higher or lower, you got the point.

Second Setting: Would change the liquid itself. You would be able to change the water to acid, lava or maybe even the liquid which is in the syringes or in the flasks (vanilla ones) ((liquid wouldnt have physics like they do in the flask or syrinenges))

It would be nice to add something like that, because you wouldnt have to go to another map and wait for it to endlessly load. As well as it is just faster and more accsessible.

(I am sorry if my English is bad/broken)

**Comment by D3stStrut** [comment]
That would be nice

**Comment by DummyTheAllSeeing** [comment]
> there is a mod for this https://steamcommunity.com/sharedfiles/filedetails/?id=2776630725
