### ISSUE TITLE
Underwater Rendering Offset

### ISSUE THREAD

**Issue by Joshua66252** [studio-minus/ppg-bugs-and-requests#760]
**Describe the bug**

**When an object is at the bottom of very deep water the selection highlight is very offset from the object.**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Go on hybrid and bring an object to the bottom of the water (Preferably with a light source.)**

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**N/A**

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Windows**
**1.22.3**
**Integrated**
**11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz   3.00 GHz**
**16 GB ram**

**Additional notes**

**I have attached a picture of the glitch**
![Bug](https://user-images.githubusercontent.com/44351387/156127704-b4cd4890-d79b-4f59-9d79-0f8f08187a5c.png)

**Comment by Uniconrzss** [comment]
I think its the water offsetting the texture since water irl kind of works like that where if you put a straight object in it, it gets offset. But id still like to see something being done about this since this makes building very low annoying

**Comment by mestiez** [comment]
Not a bug. The water just refracts the light behind it so it looks offset.
