### ISSUE TITLE
The Ceiling Turret still works after being blown up by a fucking thermonuclear explosive.

### ISSUE THREAD

**Issue by cumslut69** [studio-minus/ppg-bugs-and-requests#762]
**Describe the bug**
title

**Clearly describe how to reproduce the bug**
1. get your hands on a ceiling turret and a classified thermonuclear explosive
2. profit
**Mod list**
none

**System info (please complete the following information)**
 - Operating system: Windows
 - Game version: 1.22.3
 - GPU: 9500 GT
 - CPU: Q6600

**Additional notes**

**Comment by cumslut69** [comment]
my CPU is Q6600* i am i PC nerd but i still forgor 💀

**Comment by mestiez** [comment]
fixed? not really a bug but it was weird
