### ISSUE TITLE
The Car is as tall as a jeep but can hardly fit a human, make it somehow smaller and more spacier???

### ISSUE THREAD

**Issue by cumslut69** [studio-minus/ppg-bugs-and-requests#767]
**Feature description**
the ground clearance is comparable than a nissan patrol, maybe pressing E on the car while holding a human puts the human in?
**Feature purpose**
the car looks huge, pls make it smaller.

**Additional context**
![image](https://user-images.githubusercontent.com/100531599/156477592-c882d538-343d-4510-a5a9-e23c0169033c.png)

**Comment by cumslut69** [comment]
here is a realistic comparison about how it should look vs how it looks

![image](https://user-images.githubusercontent.com/100531599/156479192-8a60cd21-0130-4cda-8fe3-b02ef0e689d2.png)

**Comment by Bon687** [comment]
> here is a realistic comparison about how it should look vs how it looks
> 
> ![image](https://user-images.githubusercontent.com/100531599/156479192-8a60cd21-0130-4cda-8fe3-b02ef0e689d2.png)
I think you just solved your problem. lol

**Comment by mestiez** [comment]
The reason for this is that cars were made for human proportions. In-game humans are incorrectly proportioned such that their upper body is way too large.

**Comment by cumslut69** [comment]
i see, so you're saying that the PPG human is buff? understood.
