### ISSUE TITLE
Metals can melt and more detailed detailed view

### ISSUE THREAD

**Issue by Bon687** [studio-minus/ppg-bugs-and-requests#769]
can you make the metals melt, I think its cool to melt metal :^), and the detailed view more details like how fast the velocity of the object?

**Comment by D3stStrut** [comment]
bruh i want this too but it's not possible in ppg

**Comment by cumslut69** [comment]
maybe when liquid physics get added, but certainly not today lad.

**Comment by DindinYT37** [comment]
Use :clap: The :clap: Template :clap: For :clap: God's :clap: Sake.

**Comment by D3stStrut** [comment]
> Use 👏 The 👏 Template 👏 For 👏 God's 👏 Sake. _Also, suggest one thing at a time, especially when they're not even similar to eachother._
> 
> Oh yeah and, this probably won't happen, per-pixel-destruction is already a very-likely-to-be-denied feature (if isn't already), and this would basically be per-pixel-destruction with liquid simulation - which has already been confirmed to not be added.

ratio

**Comment by DindinYT37** [comment]
> > Use 👏 The 👏 Template 👏 For 👏 God's 👏 Sake. _Also, suggest one thing at a time, especially when they're not even similar to eachother._
> > 
> > Oh yeah and, this probably won't happen, per-pixel-destruction is already a very-likely-to-be-denied feature (if isn't already), and this would basically be per-pixel-destruction with liquid simulation - which has already been confirmed to not be added.
> 
> ratio

This is GitHub, not Twitter.

**Comment by D3stStrut** [comment]
> > > Use 👏 The 👏 Template 👏 For 👏 God's 👏 Sake. _Also, suggest one thing at a time, especially when they're not even similar to eachother._
> > > Oh yeah and, this probably won't happen, per-pixel-destruction is already a very-likely-to-be-denied feature (if isn't already), and this would basically be per-pixel-destruction with liquid simulation - which has already been confirmed to not be added.
> > 
> > 
> > ratio
> 
> This is GitHub, not Twitter.

alright buddy go minimod some more posts /s

**Comment by DindinYT37** [comment]
> > > > Use 👏 The 👏 Template 👏 For 👏 God's 👏 Sake. _Also, suggest one thing at a time, especially when they're not even similar to eachother._
> > > > Oh yeah and, this probably won't happen, per-pixel-destruction is already a very-likely-to-be-denied feature (if isn't already), and this would basically be per-pixel-destruction with liquid simulation - which has already been confirmed to not be added.
> > > 
> > > 
> > > ratio
> > 
> > 
> > This is GitHub, not Twitter.
> 
> alright buddy go minimod some more posts /s

I'm not a "minimod", it's just genuinely annoying, and you've managed to be more annoying than any other person that has ever posted in this repository's issue-page because you keep going on about this.

**Comment by D3stStrut** [comment]
> > > > > Use 👏 The 👏 Template 👏 For 👏 God's 👏 Sake. _Also, suggest one thing at a time, especially when they're not even similar to eachother._
> > > > > Oh yeah and, this probably won't happen, per-pixel-destruction is already a very-likely-to-be-denied feature (if isn't already), and this would basically be per-pixel-destruction with liquid simulation - which has already been confirmed to not be added.
> > > > 
> > > > 
> > > > ratio
> > > 
> > > 
> > > This is GitHub, not Twitter.
> > 
> > 
> > alright buddy go minimod some more posts /s
> 
> I'm not a "minimod", it's just genuinely annoying, and you've managed to be more annoying than any other person that has ever posted in this repository's issue-page because you keep going on about this. _It's also quite visible that you're a twitter user 🗿_

mald
