### ISSUE TITLE
Humans pass out at high temperatures

### ISSUE THREAD

**Issue by blocker2225** [studio-minus/ppg-bugs-and-requests#776]
**Feature description**
Humans are likely to lose consciousness at temperatures over and equal to 120°F or 48°C
**Feature purpose**
In FNaF 6, I noticed that if you let the temperature reach critical levels (120 fahrenheit), you pass out. It's quite realistic considering how many times I passed out in a hot shower. It's just a bit of realism
**Additional context**
N/A

**Comment by mestiez** [comment]
forgot about this but what do you mean by "how many times I passed out in a hot shower"? What the hell are you doing? 
that aside, this does happen in the game now but it's quite subtle / inconsistent by design.

**Comment by Drogo-man** [comment]
dude. what?
