### ISSUE TITLE
Animals

### ISSUE THREAD

**Issue by nicolascore** [studio-minus/ppg-bugs-and-requests#782]
**Feature description**
Various types of animals 

**Feature purpose**
The same purpose of humans being in the game 

**Additional context**
N/A

**Comment by D3stStrut** [comment]
you sadistic son of a b*tch we all know you want to torture dogs

**Comment by fhgb54643689** [comment]
i recall zooi saying something about not wanting to add animals as they believe it would be pretty fucking awful which i agree with. plus imo humans deserve it more

**Comment by nicolascore** [comment]
> i recall zooi saying something about not wanting to add animals as they believe it would be pretty fucking awful which i agree with. plus imo humans deserve it more

The only thing that deserves anything is the player, everyone else is innocent
