### ISSUE TITLE
G

### ISSUE THREAD

**Issue by CGXB** [studio-minus/ppg-bugs-and-requests#786]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**

**Comment by fhgb54643689** [comment]
couldnt have said it better myself
