### ISSUE TITLE
Oxygenator

### ISSUE THREAD

**Issue by TheTypoIsIntentoinal** [studio-minus/ppg-bugs-and-requests#787]
**Feature description**
A spawnable item that provides oxygen via the blood vessel wire to humans. 

**Feature purpose**
This can be used to help with underwater swimming or people with punctured lungs.

**Comment by D3stStrut** [comment]
YES

**Comment by vda8** [comment]
YES PLEASE.

**Comment by DindinYT37** [comment]
> duplicate of #1085

How does this work? Wasn't that issue made over a month after this was?

**Comment by TheTypoIsIntentoinal** [comment]
> > duplicate of #1085
> 
> How does this work? Wasn't that issue made over a month after this was?

Yea, idk why this one got struck down
If it's possible for an issue to be reopened without making a new one, can somebody do so
