### ISSUE TITLE
Water

### ISSUE THREAD

**Issue by fhgb54643689** [studio-minus/ppg-bugs-and-requests#792]
**Feature description**
a new liquid promptly named "water" which can either be collected in a map with water by putting a liquid tank and switching it to pull in the water or be placed down in a flask from the chemicals category, water can then be sprayed onto fire using a liquid outlet (or draining the tank full of water on fire)

**Feature purpose**
a new way of putting out fires with a liquid plus (if its saltwater) it can then be injected into a human to then cause issues and possibly cause them to die

**Additional context**
just to clarify this is not a "physical water" suggestion by any means i am simply suggesting a new liquid using the already existing liquid system

**Comment by D3stStrut** [comment]
nice loophole

**Comment by fhgb54643689** [comment]
> nice loophole

what you on about

**Comment by basedkit** [comment]
yeah this would also be helful if they added a way to make certain liquids less dangerous by adding a water flask to a tank of a poison
