### ISSUE TITLE
search bar in mods

### ISSUE THREAD

**Issue by citizenthe** [studio-minus/ppg-bugs-and-requests#794]
its hard to find other mods that you have subbed to when u have subscribed on alot of mods

maybe something like this
![Screenshot 2022-03-07 150612](https://user-images.githubusercontent.com/96728876/156984042-aefd8995-a67e-4165-807a-52d52106d25c.png)

**Comment by DindinYT37** [comment]
Why was this accepted but the original wasn't? This is a duplicate of #250.

**Comment by Buggem** [comment]
@DindinYT37 https://github.com/studio-minus/ppg-bugs-and-requests/issues/250#issuecomment-939558218
