### ISSUE TITLE
Gates increase forever in slow motion when connected to an Electricity Transformer

### ISSUE THREAD

**Issue by f4563** [studio-minus/ppg-bugs-and-requests#797]
Connect a gate to power with the source being a Electricity Transformer, it should cap at a certain point. Now go into slow motion, the cap stops working and the gates power increases forever (which activates it when it exceeds the threshold).

I have slow motion set to 10%.

**Comment by mestiez** [comment]
This has been fixed already due to the continuous activation rewrite in the next update
