### ISSUE TITLE
More organs

### ISSUE THREAD

**Issue by coolturdsaregood** [studio-minus/ppg-bugs-and-requests#801]
More organs such as lungs, a heart, ect.

**Comment by Mr-Jangoon** [comment]
Lungs are already there, The body dies of too much damage to the upper torso (implying the existence of a heart)

**Comment by 5hart** [comment]
theres a setting in game that adds expanded gore, with organs like a heart, brain, and intestines

**Comment by Cboyjet4** [comment]
all those organs already exist
also this doesn't follow the template.

**Comment by TheTypoIsIntentoinal** [comment]
Expanded gore has officially died (as of the most recent beta), please close this issue
