### ISSUE TITLE
"Flip" Option in the right click menu.

### ISSUE THREAD

**Issue by AzraelTheCountess** [studio-minus/ppg-bugs-and-requests#804]
I would love to see an option to "flip" a human or android. instead of having to spawn another one making it face the other way with Q or E, I think there should also be an option to right click on any body part of the selected humanoid / android and click flip to make the human or android face the other way.
 
I think it'd be useful so people don't have to open the menu again to spawn the same human / android and delete the old one.

**Comment by royalealbert27** [comment]
There's a mod made by a developer that does this. It's called "Flipping Heck".

**Comment by AzraelTheCountess** [comment]
oh awe

> There's a mod made by the developer that does this. It's called "Flipping Heck".
oh awesome! thank you.

**Comment by AzraelTheCountess** [comment]
> There's a mod made by the developer that does this. It's called "Flipping Heck".

oh awesome! thank you :)
