### ISSUE TITLE
Crackling audio on PPG and PPG only

### ISSUE THREAD

**Issue by JustAHubber** [studio-minus/ppg-bugs-and-requests#812]
**Description**
When running the game I am noticing random cuts of audio. I have checked everything and it is definitely people playground as Music still continues to play on spotify with no issues while the game is open and still cutting out. I find this making the game unplayable as sound is very important to me.

**How to find bug**
Running the game instantly has this issue.

**System and Game Info**
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8225043/exported.game.debug.info.md)

**Comment by mestiez** [comment]
I will prevent the ambient mixer from playing any sound below 80 Hz. Hopefully this eliminates the issue.
