### ISSUE TITLE
Make tank not Be a toy

### ISSUE THREAD

**Issue by Gooseman2** [studio-minus/ppg-bugs-and-requests#815]
**Feature description**
Tanks would have motors etc. Because currently theyre toys

**Feature purpose**
Its boring to see a rocket hit a tank and have no effect on it. Would be more realistic if it could break down

**Comment by Mr-Jangoon** [comment]
I also like this idea

**Comment by StealthDrifter** [comment]
zooi never marked this as accepted even though he added it 😔
