### ISSUE TITLE
Right click options not working

### ISSUE THREAD

**Issue by CRAZE-CROC** [studio-minus/ppg-bugs-and-requests#819]
My right-click options are not working and I cannot right-click on a person or anything. Please fix

**Comment by ppgplayer** [comment]
damn bro did you try to restart the game

**Comment by StealthDrifter** [comment]
this is the least helpful bug report i've seen

**Comment by ppgplayer** [comment]
Cool

**Comment by ifrost-source** [comment]
my monitor screen does not turn on, it's all the fault of people playground, fix it zooi 😭😭😭
