### ISSUE TITLE
"temperature lock"option in right click menu

### ISSUE THREAD

**Issue by tomatoiab** [studio-minus/ppg-bugs-and-requests#820]
**Feature description**
an option that can lock a object's temperature

**Comment by mestiez** [comment]
why

**Comment by ppgplayer** [comment]
> why

good question

**Comment by tomatoiab** [comment]
> why

bc i want to make a source that can emit heat forever,I tried to use heatry but the heatray make my game lag, and the heat element's temperature upper limit is 1000℃(i think it's too low) . so i put forward this idea.My bad sry :( .

and thanks for update the changelog

**Comment by tomatoiab** [comment]
> why

bc i want to make a source that can emit heat forever,I tried to use heatry but the heatray make my game lag, and the heat element's temperature upper limit is 1000℃(i think it's too low) . so i put forward this idea.My bad sry :( .

and thanks for update the changelog

**Comment by tomatoiab** [comment]
my English is not good sry,English isn't my mother tongue. sorry :(

**Comment by Skiiitles** [comment]
> > why
> 
> bc i want to make a source that can emit heat forever,I tried to use heatry but the heatray make my game lag, and the heat element's temperature upper limit is 1000℃(i think it's too low) . so i put forward this idea.My bad sry :( .
> 
> and thanks for update the changelog

I made a mod called "Customizable Heat Source + 1000 degree knife (BETA)" a while ago which is basically a heating element but w/o limits, that seems to be what you're looking for? (last I checked I think it worked)

**Comment by tomatoiab** [comment]
> > > why
> > 
> > 
> > bc i want to make a source that can emit heat forever,I tried to use heatry but the heatray make my game lag, and the heat element's temperature upper limit is 1000℃(i think it's too low) . so i put forward this idea.My bad sry :( .
> > and thanks for update the changelog
> 
> I made a mod called "Customizable Heat Source + 1000 degree knife (BETA)" a while ago which is basically a heating element but w/o limits, that seems to be what you're looking for? (last I checked I think it worked)

omg.thank you! thank you very much！

**Comment by tomatoiab** [comment]
> > > why
> > 
> > 
> > bc i want to make a source that can emit heat forever,I tried to use heatry but the heatray make my game lag, and the heat element's temperature upper limit is 1000℃(i think it's too low) . so i put forward this idea.My bad sry :( .
> > and thanks for update the changelog
> 
> I made a mod called "Customizable Heat Source + 1000 degree knife (BETA)" a while ago which is basically a heating element but w/o limits, that seems to be what you're looking for? (last I checked I think it worked)

omg.thank you! thank you very much！
