### ISSUE TITLE
tires can deflate 

### ISSUE THREAD

**Issue by SperoTeStupriMori** [studio-minus/ppg-bugs-and-requests#823]
**Feature description**
Tires can deflate, and maybe spike belt?

**Comment by 5hart** [comment]
a spike belt would be a cool idea, imagine if you could also use those wheel locks police use as well

**Comment by TheTypoIsIntentoinal** [comment]
I would elaborate on the tires thing more and submit a new request for the spike belt, this is a pretty cool idea

**Comment by mestiez** [comment]
they can now deflate
