### ISSUE TITLE
light

### ISSUE THREAD

**Issue by Holder-hash** [studio-minus/ppg-bugs-and-requests#824]
Hello. I apologize in advance if there are errors in the translation. I noticed some error, or even inaccuracy in the mechanics of light. You see, light travels through walls in a very even circle. I don't know if this is intended, but it looks very incorrect. .I suggest you either fix the mechanics of the light itself so that it doesn't pass through closed spaces, or add some kind of adjustment. Thank you for your attention.

**Comment by mestiez** [comment]
im not planning to make light obstructable unfortunately
