### ISSUE TITLE
Cannot select, drag, or interact with anything

### ISSUE THREAD

**Issue by Bayraktar2022** [studio-minus/ppg-bugs-and-requests#829]
I can't interact with anything in the game on all maps
**Mod list**
a lot of mods

**System info**
 - Operating system: Windos 10
 - Game version: 1.23
 - GPU:RX 560 4gb
 - CPU: inter i3 4130

**Additional notes**

**Comment by mestiez** [comment]
I may have solved this in preview 6

**Comment by DindinYT37** [comment]
Not fixed in preview 7. @mestiez

**Comment by mestiez** [comment]
okay NOW its been fixed i think

**Comment by DindinYT37** [comment]
Fixed for me, even with re-enabling the Colored Wires mod.
