### ISSUE TITLE
Accidentally deleting the world except for the showers

### ISSUE THREAD

**Issue by jamesipod** [studio-minus/ppg-bugs-and-requests#830]
**Describe the bug**
In the new substructure map, deleting the chalkboard in the classroom just deletes the world, and says "world deleted" in the bottom right. Whether or not this is intentional, the showers remain in the map. 

**Clearly describe how to reproduce the bug**
Delete the chalkboard

**System info (please complete the following information)**
 - Operating system: Win10
 - Game version: 1.23 Preview
 - GPU: 3070ti 
 - CPU: 11700k

**Additional notes**

**Comment by mestiez** [comment]
fixed
