### ISSUE TITLE
Hello, by some reason on the Preview 1.23 i cant drag or interact with stuff. All that i can do is only spawning stuff. I cant even use wiring.

### ISSUE THREAD

**Issue by Edwardo1P** [studio-minus/ppg-bugs-and-requests#833]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**

**Comment by fhgb54643689** [comment]
this is an issue with the mod ocm if i am correct
