### ISSUE TITLE
Add a emergency stop button on the elevator

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#837]
**Feature description**
It stops the elevator when you press the button

**Feature purpose**
It would be cool

**Additional context**
Also stops all elevator requests when the button is pressed

**Comment by Cboyjet4** [comment]
Do you mean the mechanical belt?

**Comment by Cboyjet4** [comment]
oh!! I haven't checked the new update, forgot there was a new map, oops.
