### ISSUE TITLE
Layering

### ISSUE THREAD

**Issue by evactouch** [studio-minus/ppg-bugs-and-requests#838]
**Feature description**
A way to make certain objects go beneath or above other objects.

**Feature purpose**
Allows changing of layers using numbers. Default is 0 which has the normal game layering.
Could help with contraptions, armor, etc.

**Additional context**
Example of how it can be used:
Spawn a human. and a box. Drag the box over the human, and the human is being seen through the box. Change the box layering to 1 and human to -1 then makes the box seen above the human and human below the block.

![image_2022-03-15_204857](https://user-images.githubusercontent.com/47071177/158500540-11d27246-776a-45de-93e5-60dd6f430cea.png)
![image](https://user-images.githubusercontent.com/47071177/158500577-53c5f093-8af0-441f-b685-92a542cdff0c.png)
![image](https://user-images.githubusercontent.com/47071177/158500629-52938210-eac7-4c5a-b080-0383d0b9badd.png)
![image](https://user-images.githubusercontent.com/47071177/158500673-87b63ce5-3893-4757-a5c2-d93b73db3957.png)

**Comment by unknown-4o4** [comment]
I'm sure everyone would appreciate this feature

**Comment by Gigi-7688** [comment]
good idea

**Comment by ATPGaming** [comment]
you may want to close this since it was added with the beta
