### ISSUE TITLE
New Map Issue

### ISSUE THREAD

**Issue by AccurateAkimbo** [studio-minus/ppg-bugs-and-requests#842]
By zooming out on the new map with a enlarged light you can see out of bounds 
![Screenshot (203)](https://user-images.githubusercontent.com/101710455/158570887-8948e02b-9734-4128-82d8-b7b01a07b377.png)

**Comment by DindinYT37** [comment]
Don't really see how this would be a problem since the walls are thick enough for any kind of light not to be seen but I guess it's a bug.
