### ISSUE TITLE
Electrocuted water

### ISSUE THREAD

**Issue by blocker2225** [studio-minus/ppg-bugs-and-requests#843]
**Feature description**
Anything that's inside an electrocuted body of water also gets shocked.

**Feature purpose**
It makes no sense that when I throw a electrified rod into a pool of water, then throw a human in and the human does not get scorched by the current that should be conducted by the water

**Comment by DindinYT37** [comment]
I like the idea, and it would be the same way of adding the feature as I said for #844.
