### ISSUE TITLE
bottles can be filled and dispersed into a pool of water

### ISSUE THREAD

**Issue by blocker2225** [studio-minus/ppg-bugs-and-requests#844]
**Feature description**
you can fill the bottle with various liquids and hold F while submerging that bottle into water, applying the effects of the liquid to the pool and any living being that swims in the pool
I should mention this should work with the shower head and any other things that can spill liquids

**Feature purpose**
this would be good for making toxic water and traps

**Comment by DindinYT37** [comment]
Doubt this will happen since this, even if it only remotely counts to water-physics. Though I can also see it being added if zooi just saves the point the liquid was applied and linear-interpolated the effects of it from there, giving it a maximum-range based on how much liquid one poured in and maybe a small hitbox so it would add to the original area - not create a new one.

**Comment by blocker2225** [comment]
> Doubt this will happen since this, even if it only remotely counts to water-physics. Though I can also see it being added if zooi just saves the point the liquid was applied and linear-interpolated the effects of it from there, giving it a maximum-range based on how much liquid one poured in and maybe a small hitbox so it would add to the original area - not create a new one.

all it does is make the water apply effects from a liquid on touch

**Comment by DindinYT37** [comment]
> > Doubt this will happen since this, even if it only remotely counts to water-physics. Though I can also see it being added if zooi just saves the point the liquid was applied and linear-interpolated the effects of it from there, giving it a maximum-range based on how much liquid one poured in and maybe a small hitbox so it would add to the original area - not create a new one.
> 
> all it does is make the water apply effects from a liquid on touch

So do you want the entire water to have those effects? Because that could be an insanely annoying and broken feature since it would always occur even when a user doesn't want that.

**Comment by blocker2225** [comment]
> 

you must be stupid, since that would only happen if a bottle breaks inside a pool or is dispensed into it

**Comment by DindinYT37** [comment]
> you must be stupid, since that would only happen if a bottle breaks inside a pool or is dispensed into it

It's entirely your fault for explaining badly. It's also your fault for telling me one thing but denying it in your next comment. This will probably not happen, just as I have said.

**Comment by blocker2225** [comment]
> 

no brain?
