### ISSUE TITLE
humans can drink from bottles through any part of their body

### ISSUE THREAD

**Issue by blocker2225** [studio-minus/ppg-bugs-and-requests#845]
**Describe the bug**
humans can drink from bottles through any part of their body. be it the ass or leg or the dick

**Clearly describe how to reproduce the bug**
grab a bottle
put it to any part of a human except the head
hold f

**Mod list**
no mods

**System info (please complete the following information)**
 - Operating system: W10
 - Game version: 1.23
 - GPU: GTX 1050
 - CPU: Ryzen 5

**Additional notes**

**Comment by 404CoderNotFound** [comment]
Not a bug, read the bottle's description.
