### ISSUE TITLE
Fix the timer

### ISSUE THREAD

**Issue by Dmitry4920** [studio-minus/ppg-bugs-and-requests#848]
I like to repeat the traps from the Saw movies. And most of them require a timer. Unfortunately, not all traps can be repeated because of one feature of the timer. When you start the timer, it immediately transmits a signal to another timer, and that's what gets in my way. I want you to fix this and make it so that the signal is transmitted after the end of the count. I hope that you will hear me.

**Comment by mestiez** [comment]
Huh? You mean lagboxes? They work fine.
