### ISSUE TITLE
Corrupted saves

### ISSUE THREAD

**Issue by Jawrek** [studio-minus/ppg-bugs-and-requests#852]
Hi, so whenever I open up the beta version of the new update and join a game, I try to spawn certain items from my saves into the game, yet for a lot of the saves, mine and from the workshop, it says they are corrupted. I understand the early stages of the update, yet I am unsure if this problem has been bought up. I'm also unsure to what could be triggering the corruptions as its not for all of the saves

**Comment by AlexCodeMan** [comment]
Oh, about me, too, an open topic with this problem. Even the Tungsten mod disappeared.... And the saves flew.

**Comment by mestiez** [comment]
Duplicate of #841
