### ISSUE TITLE
Metrics, measurement devices, and logic.

### ISSUE THREAD

**Issue by TimBomBom** [studio-minus/ppg-bugs-and-requests#853]
**Feature description**
A number of items which measure certain metrics such as altimeters, speedometers, angle sensors/levels, radar guns, laser rangefinders, G-force meters, AND, XOR, OR gates, etc. One would also be able to set thresholds to output an activation signal once that user-set reading has been reached as well as working in tandem with logic gates for further precision.

**Feature purpose**
It would make the building and functionality of complex contraptions much much easier since most contraptions have to rely on timers or other primitive systems. These devices would likely have some sort of value that once the device reaches that, it will output an activation signal (i.e. an angle sensor that detects it has gone over the 15° threshold set by the user, outputs an activation signal that triggers some sort of system to automatically right it-self upwards, or a rocket with an altimeter that shuts off it's engines past 1000 m, etc.). Using logic, multiple metrics can be combined so that machines don't accidentally trigger, and you can have proper control. These devices would really make building contraptions (especially moving ones) infinitely easier. When calculating speed of objects, it is often an imprecise calculation and would be very helpful to remove the tedium and error with an in-game item.

**Additional context**

Below is a form of angle-detection that, despite working, is very primitive and unreliable due to lasers and other detectors lagging behind at high speeds. 

![ppg decoupler](https://user-images.githubusercontent.com/84190142/158652884-3b4d3b08-cbc8-4e92-9d1f-0e07471f566c.png)

Instead of dedicating a lot of weight and space in a rocket to such a large and complex system that requires lasers, precise placement of detectors, gyroscopes, and balance, all of this could be reduced to one small device that sends out a pulse of activation once the desired angle has been met.

Furthermore, this particular rocket relies heavily on timers and dozens of iterations of trial-and-error until a correct timing sequence (often making precise adjustments within <0.25 seconds) is **found.** A much simpler and compact way would to use speedometers to know when to turn rockets on/off. 

Rockets aren't the only thing that this would apply to, of course, and many other moving or mechanical contraptions would benefit from these devices immensely.

**Comment by DindinYT37** [comment]
I don't say it shouldn't be added, but isn't the "Parts and Contraptions" a good solution for most of what you've mentioned? I know, it's limiting for contraptions since they wouldn't be vanilla - which is why I said "I don't say it shouldn't be added" earlier but either way I think it's good a solution even if this doesn't get accepted since many people use that mod, and (as far as I know) zooi is planning to add/has added a way for contraptions to tell the user what mods are required for it.

**Comment by TimBomBom** [comment]
As with most things, I think it would be more convenient for it to be vanilla instead of being told to install a certain mod in order to load a contraption, but there are some nice devices in "Parts and Contraptions." Ig I'll use that for now
