### ISSUE TITLE
Add vanilla map blocks

### ISSUE THREAD

**Issue by 5hart** [studio-minus/ppg-bugs-and-requests#855]
**Feature description**
If possible please add some form of a "map block" and by that I just mean like a solid black (and white for snow) square that you can freeze and resize to terraform

**Feature purpose**
I've already seen plenty of mods for this, just hoping for it to be added into the game itself so you don't need a mod for it.

**Comment by DindinYT37** [comment]
If you set the Color of the new "Resizable Housing" item to 0,0,0 (completely black) or 255,255,255 (completely white) you basically have that.

**Comment by 5hart** [comment]
> If you set the Color of the new "Resizable Housing" item to 0,0,0 (completely black) or 255,255,255 (completely white) you basically have that.

Oh, I didn't know about that, or that you could change the color of it. Thank you!

**Comment by DindinYT37** [comment]
> > If you set the Color of the new "Resizable Housing" item to 0,0,0 (completely black) or 255,255,255 (completely white) you basically have that.
> 
> Oh, I didn't know about that, or that you could change the color of it. Thank you!

No problem, I recommend closing the issue btw.
