### ISSUE TITLE
Shift the map icons a bit to the left

### ISSUE THREAD

**Issue by 5hart** [studio-minus/ppg-bugs-and-requests#856]
**Feature description**
In the choose map screen, the icons for the maps are off centered and not that close to the back button, which makes it all look a bit weird in my opinion. Here's a picture of it and you can see how disproportionate it is:
![image](https://user-images.githubusercontent.com/46716733/158680939-7353dea2-be91-4945-93be-14c89e212afc.png)

**Feature purpose**
In the choose map screen, the icons for the maps are off centered and not that close to the back button, which makes it all look a bit weird in my opinion. You could also move the back button more to the right so it's closer to the icons.

**Additional context**
I could just be nitpicking, and it's like that for a reason, but I just wanted to point it out.

**Comment by DindinYT37** [comment]
I think it's because the UI is separated in two main categories, navigation and content (which you can clearly distinguish which is which on your picture). Why I'm saying it's because of this, is because I think it's probably so far to the right because it doesn't change between menus and the navigation container is originally intended for longer text, it's just a "coincidence" (if you can call it that) that "back" is so short.

**Comment by 5hart** [comment]
> I think it's because the UI is separated in two main categories, navigation and content (which you can clearly distinguish which is which on your picture). Why I'm saying it's because of this, is because I think it's probably so far to the right because it doesn't change between menus and the navigation container is originally intended for longer text, it's just a "coincidence" (if you can call it that) that "back" is so short.

I think I get what you mean. Basically all menu pages use the same format and so that's why the back button is so far to the left is what I'm getting from it. I can definitely see why then, but do you think it's changeable?

**Comment by DindinYT37** [comment]
> > I think it's because the UI is separated in two main categories, navigation and content (which you can clearly distinguish which is which on your picture). Why I'm saying it's because of this, is because I think it's probably so far to the right because it doesn't change between menus and the navigation container is originally intended for longer text, it's just a "coincidence" (if you can call it that) that "back" is so short.
> 
> I think I get what you mean. Basically all menu pages use the same format and so that's why the back button is so far to the left is what I'm getting from it. I can definitely see why then, but do you think it's changeable?

Likely, if the map-chooser GUI gets an individual instance, or the size and position gets changed by script.

**Comment by 5hart** [comment]
> > > I think it's because the UI is separated in two main categories, navigation and content (which you can clearly distinguish which is which on your picture). Why I'm saying it's because of this, is because I think it's probably so far to the right because it doesn't change between menus and the navigation container is originally intended for longer text, it's just a "coincidence" (if you can call it that) that "back" is so short.
> > 
> > 
> > I think I get what you mean. Basically all menu pages use the same format and so that's why the back button is so far to the left is what I'm getting from it. I can definitely see why then, but do you think it's changeable?
> 
> Likely, if the map-chooser GUI gets an individual instance, or the size and position gets changed by script.

Hopefully. I'll keep this issue open for now to see what the creator thinks about if if they ever see it, but thank you for helping out!

**Comment by mestiez** [comment]
![image](https://user-images.githubusercontent.com/32131519/159290856-88c164f2-9078-47ac-8b98-bc9ba0445df8.png)
this okay?

**Comment by DindinYT37** [comment]
Centered text solves all issues. (Atleast if there is only one butotn)

**Comment by 5hart** [comment]
> ![image](https://user-images.githubusercontent.com/32131519/159290856-88c164f2-9078-47ac-8b98-bc9ba0445df8.png) this okay?

yes that's perfect, sorry for the late reply. Thank you!
