### ISSUE TITLE
Option that makes particles from particle projector have functionality. 

### ISSUE THREAD

**Issue by TotallyNotALier** [studio-minus/ppg-bugs-and-requests#857]
**Feature description**
Activating button in context menu for particle projector called "Enable particle functionality" will make particles  function. So if you enable fire option things will set on fire and enabling electrical particles option electrifies objects. 

**Feature purpose**
Just a simple addition to newly added particle projector. 
Creating artificial fire and electrical particles will be easier. 

**Additional context**
No.

**Comment by mestiez** [comment]
the point of the projector is to be purely visual
