### ISSUE TITLE
Bring back the H to flush option!!

### ISSUE THREAD

**Issue by 5hart** [studio-minus/ppg-bugs-and-requests#861]
**Feature description**
When the liquidentifier was first added you could press H to flush whatever was in it, and it's not in the game anymore.

**Feature purpose**
I like having it as a key so I can quickly use it when I need to.

**Comment by mestiez** [comment]
there was never such an option

**Comment by 5hart** [comment]
> there was never such an option

i could have sworn it was in the game, or im just tripping
