### ISSUE TITLE
Link to Wiki is a 404

### ISSUE THREAD

**Issue by CraicX** [studio-minus/ppg-bugs-and-requests#862]
v1.23 Preview announcement has a link regarding **LiquidMixingController** which is taking me to a 404.

**Announcement Url:**
https://steamcommunity.com/games/1118200/announcements/detail/6035392156534983615

**Broken Link:**
https://www.studiominus.nl/ppg-modding/tutorials/tutorialMixing.html

**Comment by mestiez** [comment]
not a bug. the wiki page exists but is not yet online. it will be published when the full release of 1.23 is complete
