### ISSUE TITLE
spawning a character holding a two handed gun has the gun spawn in a wonky, not intentional way

### ISSUE THREAD

**Issue by BigtentacleshoggothGF** [studio-minus/ppg-bugs-and-requests#865]
so, as we all know you can press F on a humans hand to have them hold a gun, and from there you can adjust it to your liking, well after adjusting my human to hold a rifle in a realistic way and i save him and the gun, upon loading the saved human hes holding the gun not at all how i set it to be held when saved. it is very consistent and quite annoying having to re adjust everyones guns to look cool for big battles. i disabled all mods and double checked aswell.

**Comment by DindinYT37** [comment]
That's because they don't save how you positioned the gun, they only save that the human holds the gun in both hands. (Very simplified)

**Comment by mestiez** [comment]
Fixed :)

**Comment by Drogo-man** [comment]
> Fixed :)

WOOOOO YEEAAAH BABY THATS WHAT IVE BEEN WAITING FOR, THATS WHAT ITS ALL ABOUT! WOOOOO!!!
