### ISSUE TITLE
New Map Bug (Substructure)

### ISSUE THREAD

**Issue by boopem24** [studio-minus/ppg-bugs-and-requests#866]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

On the new map added (Substructure), flip the elevator button to completely break the map beyond repair.

**Mod list**
Include a list of your mods here and specify whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect. 

(I have 37 pages of mods, I can't list them all. This is the only one that caused the issue.) 
Flipping Heck

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.23
 - GPU: idk
 - CPU: idk

**Additional notes**

I was just trying to create a scene when I accidentally flipped the elevator call button (not the one IN the elevator) and the entire map disappeared.

**Comment by slaterrr** [comment]
my suggestion would be not to flip the elevator buttons

**Comment by DindinYT37** [comment]
Flipping Heck is a mod, this isn't a bug of the game.
