### ISSUE TITLE
Winches spawned in with Q mirror attached pins/wires

### ISSUE THREAD

**Issue by somepurplekale** [studio-minus/ppg-bugs-and-requests#87]
**Describe the bug**
Attaching a pin or wire to the end of a winch cable while the game is paused will cause the wire to flip sides once the game is unpaused.

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
Pause the game
spawn in a winch
attach a wire to the black box at the end of the cable
unpause

video:
https://www.youtube.com/watch?v=qhDBS--Bl9Q&feature=youtu.be

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

active:
flipping heck
photo mode
halo weapons
controllable anti-air cannon
the steampunker
combat weapons pack v3.0

inactive:
-depletable engines
-doom weapons pack
lightsabers
the greenbrick mod

**System info (please complete the following information)**
 - Operating system: Windows 10
 - Game version: 1.20
 - GPU: RX 560X
 - CPU: AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx 2.10 GHz

**Additional notes**

**Comment by mestiez** [comment]
fixed
