### ISSUE TITLE
A new props

### ISSUE THREAD

**Issue by 2ee4jnufew** [studio-minus/ppg-bugs-and-requests#871]
### A new Decorations

So, Would like more decorations. For example, an elevator from a new map and a school board, another table on top. New mechanisms, in my opinion, a great idea. I especially want an elevator and a lot of decor. And if there is a bottle, why not a cup? thank you in advance

### The best in my opinion

**New table (metal)**
**New chair (metal)**
**Elevator**
**Cup**
**More guns and vehicles**
**physical water**
**Items from the new map.**

### Maps

**I think a lot of people liked the new map. Why not make them even bigger and add something to the "hybrid" map**

### Items from the new map
![first](https://user-images.githubusercontent.com/69415642/158823358-0287c043-d84b-47c8-ab42-33e9ba22d731.jpg)

![two](https://user-images.githubusercontent.com/69415642/158823397-57b26bf6-cfab-4464-b2fd-608a22fd6d11.jpg)

![three](https://user-images.githubusercontent.com/69415642/158823427-e95bf6ac-6dc9-4d39-92b0-89edf6b444d0.jpg)

![four](https://user-images.githubusercontent.com/69415642/158823471-41a76ef9-ece1-43b9-b827-bd12d1c33e6c.jpg)

![five](https://user-images.githubusercontent.com/69415642/158823488-25994f37-5e6d-4111-8417-cc6b84d80d68.jpg)

I want to take these things to my editor;)

Sorry for my english.
 ;)

**Comment by DindinYT37** [comment]
The second picture is a vent.
The last picture are ventilations.

**Comment by 2ee4jnufew** [comment]
Thanks for the correction. But I want it to be a table. Very suit

**Comment by 2ee4jnufew** [comment]
> ### A new Decorations
> So, Would like more decorations. For example, an elevator from a new map and a school board, another table on top. New mechanisms, in my opinion, a great idea. I especially want an elevator and a lot of decor. And if there is a bottle, why not a cup? thank you in advance
> 
> ### The best in my opinion
> **New table (metal)** **New chair (metal)** **Elevator** **Cup** **More guns and vehicles** **physical water** **Items from the new map.**
> 
> ### Maps
> **I think a lot of people liked the new map. Why not make them even bigger and add something to the "hybrid" map**
> 
> ### Items from the new map
> ![first](https://user-images.githubusercontent.com/69415642/158823358-0287c043-d84b-47c8-ab42-33e9ba22d731.jpg)
> 
> ![two](https://user-images.githubusercontent.com/69415642/158823397-57b26bf6-cfab-4464-b2fd-608a22fd6d11.jpg)
> 
> ![three](https://user-images.githubusercontent.com/69415642/158823427-e95bf6ac-6dc9-4d39-92b0-89edf6b444d0.jpg)
> 
> ![four](https://user-images.githubusercontent.com/69415642/158823471-41a76ef9-ece1-43b9-b827-bd12d1c33e6c.jpg)
> 
> ![five](https://user-images.githubusercontent.com/69415642/158823488-25994f37-5e6d-4111-8417-cc6b84d80d68.jpg)
> 
> I want to take these things to my editor;)
> 
> Sorry for my english. ;)
