### ISSUE TITLE
bug on the map Sea

### ISSUE THREAD

**Issue by GuinhoAntonio** [studio-minus/ppg-bugs-and-requests#873]
I go on the map Sea and I move the temperature and the map objects start to fall like all walls, etc.

I go to the map, put 1000 of temperature and then put -100 of temperature and then put 14 and the bug happens

I have the following mods activated in the game:
Human Dynamic Emotions;
Wound Infections;
Inferto Syringe;
Status Icons;
Quick Right Click Options;
Chemical Warfare;
Gravity Generator.

I have the following mods disabled in the game:
Controlled Sea;
Old Maps;
Acid Sea;
Law Enforcement Base: USA;
Uncharted Territory Portal;
Nanotecj Mod;
Gasoline Enavler;
Prototype humans mod;
Freddy Fazbear`s Pizzaria Building;
Prosthetics mod;
Vitals of Steel;
A Speznaz Amor set;
Tornado Mod V1.0;
Working Spraycans MOD;
Node Mapper;
Hats Mod REWORE;
Food Mod;
Powered Magic Wands MOD;
Squid Game Mod;
Item Plus;
OCM;
InvincHuman;
Shitty Syringes Mod;
FNAF Mod: FNAF 3;
FleasyWeapons - Small Guns;
FNAF Mod: FNAF 1;
Emergency Siren;
Animated Weapons+;
Quality of Life Items;
Blocksify`s Crazy Syringes Mod;
Scream mod;
more android;
Metal Things Mod;
depletable engines;
Gasoline Enabler;
The ULTIMATE Minecraft Mod;
Minecraft Buildings Mod;
Police+;
Minecraft Doors Mod;
S.T.A.L.K.E.R: Call Of PPG;
Doors Mod;
Black Hole Syringe;
City People;
Taser;
Spiderman Collection 2;
Human Minus (V.2.3);
Skittle`s Syringe Mod;
Quality of Life Items(Deprecated);
Cyber`s WWII Mod;
Tethers;
The Better Acid Syringe;
Functioning Armor;
FNAF Mod.

 - Operating system: Windows 10
 - Game version: 1.23 preview 9 (64 bit)
 - GPU: NVIDIA GeForce GTX 1050
 - CPU: GPU: AMD Ryzen 5 1400 Quad-Core Processor

**Comment by BBQGiraffe** [comment]
experiencing this exact bug with 0 mods enabled,
setting the temperature to any negative number and then a positive one fucks shit up, probably something to do with the water freezing and becoming solid

![image](https://user-images.githubusercontent.com/45021140/158922278-5f1e80b1-565f-4569-af80-b3b8599971e1.png)


![image](https://user-images.githubusercontent.com/45021140/158922302-4f909b3e-f208-4c45-9234-fde8f1df1345.png)

**Comment by GuinhoAntonio** [comment]
> experiencing this exact bug with 0 mods enabled, setting the temperature to any negative number and then a positive one fucks shit up, probably something to do with the water freezing and becoming solid
> 
> ![image](https://user-images.githubusercontent.com/45021140/158922278-5f1e80b1-565f-4569-af80-b3b8599971e1.png)
> 
> ![image](https://user-images.githubusercontent.com/45021140/158922302-4f909b3e-f208-4c45-9234-fde8f1df1345.png)

sim mano é isso o que me acontece
