### ISSUE TITLE
Bug on map 'Hybrid'

### ISSUE THREAD

**Issue by KaelinGibbs** [studio-minus/ppg-bugs-and-requests#875]
**Describe the bug**
There is a bug on the map 'Hybrid', in which three pillars can detach from their original positions.

**Clearly describe how to reproduce the bug**
I have been able to reproduce this bug several times, by changing the temperature in the 'Environment' tab.
Changing the temperature to any negative number and then back to a positive number appears to cause the issue.

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8288512/exported.game.debug.info.md)

**Additional notes**
Images of the bug:
![20220317165005_1](https://user-images.githubusercontent.com/78939533/158860275-0a4d745f-943a-4fdc-a5a2-5a3c324e4cf1.jpg)
![20220317024056_1](https://user-images.githubusercontent.com/78939533/158860281-0be068c5-64c4-4bb5-97cc-576a8ec5ffc4.jpg)

**Comment by 2ee4jnufew** [comment]
Best bug
