### ISSUE TITLE
When the Conveyor belt gets destroyed, it does not have the usual tech destroyed texture.

### ISSUE THREAD

**Issue by Dozenlist12** [studio-minus/ppg-bugs-and-requests#877]
**Describe the bug**
When the Conveyor belt gets destroyed, it does not have the usual tech destroyed texture.

**Clearly describe how to reproduce the bug**
1st, hook up a laser to the generator to make it explosive, 2nd shot the belt with the explosive laser.

**Mod list**
None.

**System info (please complete the following information)**
 - Operating system: Microsoft Windows 10 pro
 - Game version:1.23 preview 9 
 - GPU:i5 10300h
 - CPU: NIVIDA Geforce GTX 1650

**Additional notes**

**Comment by mestiez** [comment]
it does but the texture is just behind the wheels
