### ISSUE TITLE
Add back blast to the bazooka and rocket launcher

### ISSUE THREAD

**Issue by Paulyfisk** [studio-minus/ppg-bugs-and-requests#884]
**Feature Description**
With the Bazooka and Rocket Launcher, the blast is launched out of the back of the weapon currently it is only visual but I believe that it would be nice if it pushed items and/or injured people.

**Feature Purpose**
Realism

**Comment by vda8** [comment]
man, this would be cool. I was goona recommend this but I see it has already been recommended.

**Comment by LowPolyFruit** [comment]
IRL Rocket Launchers don't have recoil/knockback
