### ISSUE TITLE
A heat seeking missile launcher.

### ISSUE THREAD

**Issue by vda8** [studio-minus/ppg-bugs-and-requests#886]
**Feature description**
A heat-seeking missile launcher. It should work like the archelix blaster, but instead of launching heat-seeking bolts, it launches heat-seeking missiles.

**Feature purpose**
It would be great for tracking vehicles and stuff. Very cool.

**Additional context**
Not really.

**Comment by SomeRandomGuyHere** [comment]
It would be cool if other hot objects like flares stopped missiles.

**Comment by vda8** [comment]
> It would be cool if other hot objects like flares stopped the missiles.
irl flares just distract them. not completely stop them.
