### ISSUE TITLE
Bug with Black Hole. (Preview Version)

### ISSUE THREAD

**Issue by RovarPlaysYT** [studio-minus/ppg-bugs-and-requests#887]
When making Black Hole, some items don't get destroyed when touching black hole
![image](https://user-images.githubusercontent.com/100331909/158977747-121ed180-0ec5-4538-9d1e-a3c340fc4ae0.png)

This happends only on SubStructure map

I deactivated every mod

 - Operating system: Windows 10 Pro
 - Game version: v1.23 preview 9
 - GPU: Amd Radeon(TM) Vega 3 Graphics
 - CPU: Amd Athlon 300U with Radeon Vega Mobile GFX

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8303253/exported.game.debug.info.md)

**Comment by mestiez** [comment]
Fixed
