### ISSUE TITLE
TV don't get repaired

### ISSUE THREAD

**Issue by RovarPlaysYT** [studio-minus/ppg-bugs-and-requests#891]
I can't repair TV
![image](https://user-images.githubusercontent.com/100331909/159003538-fd5c9288-92fa-4661-ae3b-fcd6ee21b535.png)

Map: Sea

Mods:

	zooi-Darker blood-local v1.0 for game v1.22
		Currently inactive

	Kor_BarBeQ-Clone Troopers Mod Pack-2777796898 v1.6 for game v1.19+
		Currently inactive

	Mishanya-Maps-2777501047 v1.2.2 for game v1.22.3+
		Currently inactive

	Wolfzy1-RandomStuff+-local v1.0 for game v1.22.3
		Currently inactive

	Kor_BarBeQ-Stealth Bigtime Suit Pack-2777072288 v1.0 for game v1.19+
		Currently inactive

	royalealbert27-Human with Changeable Feelings-local v1.0 for game v1.22+
		Currently inactive

	Dyadyushka Dyadya-Controlled Sea-2776630725 v1.0 for game v1.22.3+
		Currently inactive

	Quickness-Prison Bus-2776557560 v1.1 for game v1.22.3+
		Currently inactive

	Adamkol-Jellybean Mod-2765896184 v1.0 for game v1.22.3
		Currently inactive

	Skittles-Guns 'N Ammo-2761082698 v1.0 for game vwhatever is the latest
		Currently inactive

	Orsoniks / Navii-SimplePortals-2759460093 v1.0 for game v1.22+
		Currently inactive

	citizen-Modern Firearms-2721105504 v1.0 for game v1.20
		Currently inactive

	MrTul3nchik-Spider-Man No Way Home-2704922128 v1.0 for game v1.20+
		Currently inactive

	Zkryhngro�meister-Science Hazard Minus-2691553761 v1.1 for game v1.23+
		Currently inactive

	Camdog74, Aspa102, Egg-Egg.-2654478569 v1.0 for game vEgg
		Currently inactive

	CTTC321-Working Spraycans MOD-2648741142 v1.0 for game v1.20+
		Currently inactive

	Orsoniks / Navii-Status Icons-2644689646 v0.1 for game v1.22
		Currently inactive

	Nightzz-Item Plus-2612273009 v6.0 for game v1.21.x
		Currently inactive

	Mishanya-Functional Devices Mod-2605252227 v1.1 for game v1.22.3+
		Currently inactive

	Azule, Quickness-Fish Mod-2599934778 v1.3 for game v1.21x
		Currently inactive

	LijmPistool, Nightzz-Army Mod-2592640598 vV0.3.0 for game v1.21.x
		Currently inactive

	Hoodirony360(Snooseal)-Half Life Alyx mod-2591067503 v1.0 for game v1.21+ also i am being held hostage at Asteys house. Please send help
		Currently inactive

	Aubarino-The 3D Mod-2589525170 v1.0 for game v1.20+
		Currently inactive

	Mini-Mini's Roleplay Mod-2587903303 v1.0 for game v1.18
		Currently inactive

	onions-Headcrabs-2583003386 v1.3 for game v1.20
		Currently inactive

	cttc321-CYBERNETIC FACTIONS MOD-2582352232 vv1.0 for game v1.13+
		Currently inactive

	Maxe-Death Note-local v1.0 for game vAny
		Currently inactive

	Maxe-Detroit: Become Human-2571963895 v1.1 for game v1.19+
		Currently inactive

	cttc321-SUPER DROIDS MOD-2566959611 vv1.0 for game v1.13+
		Currently inactive

	Golden-CSGO SAS NPCs Mod-local v1.0 for game v1.9+
		Currently inactive

	IaMFreezz-TABS Mod-2523110121 v1.0 for game v1.18.1+
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently inactive

	Quickness, Mishanya-Titanic Mod-local v1.0 for game v1.18x
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently inactive

	Pumpkin-Quality of Life Items-2500516293 v1.7 for game v1.22.3
		Currently inactive

	Blocksify & Frevv-Blocksify's Crazy Syringes Mod-2498890172 v1,000,000 for game v1.18
		Currently inactive

	Talonphobia-Greenbrick Industries-2476975606 v1.3 for game v1.18+
		Currently inactive

	FredMichalBear-Feelings mod-local v1.0 for game v1.15
		Currently inactive

	JGrimesGamed-Mo' Fluids-2460574441 v1.0 for game v1.16+
		Currently inactive

	zooi-flipping heck-2448120172 v1.6 for game v1.21
		Currently inactive

	Kyrelink and Quickness-The ULTIMATE Minecraft Mod-2442812460 v1.6 for game v1.21+
		Currently inactive

	Mishanya-Police+-2416686384 v6.4 BETA for game v1.21.3+
		Currently inactive

	Mr_kWKD-Military+-local v1.0 for game v1.11
		Currently inactive

	Mishany-Melee Weapons Mod-2389733225 v7.0 for game v1.13+
		Currently inactive

	OzimekPL-S.C.P. Foundation Expanded-2388808764 v1.2 for game v1.12+
		Currently inactive

	jimmyl-Android Injectors-2381177128 v1.4 for game v1.12+
		Currently inactive

	G[DEATH]P-Cry Of Fear Mod-2380646615 v1.0 for game v1.14+
		Currently inactive

	Mini-City People-2376820541 v1.0 for game v1.14
		Currently inactive

	JohnnyTaco-Mulligan-2369099463 v1.86 for game v1.16+
		Currently inactive

	Pumpkin-Simple Syringes Mod-2367972029 v2.2 for game v1.18+
		Currently inactive

	Morzzic-Taser-2361892819 v1.2 for game v1.11+
		Currently inactive

	jimmyl-ExplosiveMod-2337158074 v1 for game v1.10+
		Currently inactive

	Morzzic-Aimbot Gun-2327621346 v1.0 for game v1.8.1
		Currently inactive

	Damianos28,Kyrelink-More Destructible Objects !-2319326006 v1.0 for game v1.13.1
		Currently inactive

	Alibarda-Human Tiers-2308911224 vv4.4 for game v1.12+
		Currently inactive

	Alibarda-PowersMod-2276255188 v1.7 for game v1.12+
		Currently inactive

	Skittles-Skittle's Syringe Mod-2268097682 v1.4 for game v1.19+
		Currently inactive

	Golden, Talon Zane-Among Us Mod-2232883786 v1.0 for game v1.9+
		Currently inactive

	weirdo-Chemical Warfare-2226697361 v2.0 for game v1.22.2+
		Currently inactive

	Teletubbie With A Shotgun-Vietnam Soldiers Mod-2221749809 v1.0.5 for game v1.9+
		Currently inactive

	Talon Zane-Tethers-2211493781 v1.1 for game v1.11.1+
		Currently inactive

	Morzzic-Smart Spawner-2195054961 v2.2 for game v1.10+
		Currently inactive

	weirdo-Functioning Armor-2194511729 v3.0 for game v1.22.2+
		Currently inactive

	Svit and Sky-POT O' Items-2187367733 v1.2 for game v1.9.4
		Currently inactive

	glub just glub-Attack on Titan mod-2183774525 v1.0 for game v1.9
		Currently inactive

	Kyrelink-Star Wars Sith and Jedi Mod 3.3-2182277406 v3.3 for game v1.10+
		Currently inactive

	Sororfortuna-Soror's NPC Pack-2169243678 v11.0 for game v1.19.2
		Currently inactive

	Mr_kWKD-Humans+-2168468454 v1.3.0 for game v1.9
		Currently inactive

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently inactive

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	(RU)Enot builder-Construction kit V0.9.5-2151076041 vV0.9.5 for game v1.8x
		Currently inactive

	(RU)Enot builder-Weapon Mod-2137486750 v0.8 for game v1.7x
		Currently inactive

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently inactive

 - **OS**: Windows 10  (10.0.19044) 64bit

 - **CPU**: AMD Athlon 300U with Radeon Vega Mobile Gfx 

 - **GPU**: AMD Radeon(TM) Vega 3 Graphics

 - **Memory**: 6 GB
 
 - **Version**: People Playground [v1.23 preview 9] [64 bit]

[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8304453/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
The Wrench is for androids I'm pretty sure?

**Comment by RovarPlaysYT** [comment]
> The Wrench is for androids I'm pretty sure?

Wrench for every item in game, wrench can fix broken guns.

**Comment by UniDuki** [comment]
#153

**Comment by vda8** [comment]
not a bug. TVs breaking just works differently.

**Comment by mestiez** [comment]
The television is a very old item that doesn't work together with the "damagable machinery" system. This isn't a bug, just an unintuitive weird thing
