### ISSUE TITLE
theres no new map, its like i have no update for 1.23

### ISSUE THREAD

**Issue by yomammayournoodle** [studio-minus/ppg-bugs-and-requests#892]
**Describe the bug**

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.

**System info (please complete the following information)**
 - Operating system: 
 - Game version:
 - GPU:
 - CPU:

**Additional notes**

**Comment by ppgplayer** [comment]
![image](https://user-images.githubusercontent.com/98086053/159004705-d8c868b2-a5bb-4d9f-953c-758641f03352.png)
![image](https://user-images.githubusercontent.com/98086053/159004723-e95fccc4-1408-4e4d-b762-5126b663c701.png)
![image](https://user-images.githubusercontent.com/98086053/159004735-46d3e12c-4cdc-4ca1-8610-df5734b82d4a.png)

**Comment by DindinYT37** [comment]
What do we have templates even for, if there are people like this?

**Comment by vda8** [comment]
yeah exactly
