### ISSUE TITLE
melee bug

### ISSUE THREAD

**Issue by ROLLOLRIRL** [studio-minus/ppg-bugs-and-requests#898]
**Describe the bug**
the bug is if a human/android have a melee like a knife in their last hand it wil act like its in their first

**Clearly describe how to reproduce the bug**
Steps to reproduce the problem.
open the game
spawn a human/android
give it any a knife/sword and put it in their last hand

**Mod list**
none exept many disabled mods.

**System info (please complete the following information)**
 - Operating system: Windows 10 Pro
 - Game version:1.22.3 64bit
 - GPU:AMD radeon HD 8730M
 - CPU:Intel(R) Core(TM) i7-3537U CPU

--->

**Additional notes**
pls fix

**Comment by ROLLOLRIRL** [comment]
here is my mod list 
	Skittles-Guns 'N Ammo-2761082698 v1.0 for game vwhatever is the latest
		Currently inactive

	citizen-The Troubles-2638986121 v1.2 for game v1.20
		Currently inactive

	Morzzic-Food Mod-local v1.0 for game v1.10+
		Currently inactive

	CTTC321-RC VEHICLES MOD-2623961221 vBETA for game v1.20+
		Currently inactive

	CliffyRocket038-Squid Game Mod-2615439393 v1.0 for game vcurrent versions.
		Currently inactive

	Cioss-Squid Game Mod-2613658743 vwho.cares.0 for game vI dunno.0
		Currently inactive

	Mishanya-Functional Devices Mod-2605252227 v1.1 for game v1.22.3+
		Currently inactive
		Has been initialised

	onions-Headcrabs-2583003386 v1.3 for game v1.20
		Currently inactive

	Golden-Cyberpunk 2077 Trauma Medic Pack-local v1.0 for game v1.9+
		Currently inactive

	letter-Halo weapons REUPLOAD-local v1.3 for game v1.9.3
		Currently inactive

	Punished 'Venom' Ahlad-Hau'Tne Empire-2535163001 v0.1 maybe for game v1.19+
		Currently inactive

	Golden-CSGO SAS NPCs Mod-local v1.0 for game v1.9+
		Currently inactive

	Cardboard-The Playground of Isaac-2530589009 v1.1 for game v1.11
		Currently inactive

	ahlad-small acid swamps-2530315269 v1.0 for game v1.14+
		Currently inactive

	kortl-COMBAT Zombies-local v1.0 for game v1.8.x
		Currently inactive

	bee queen-TF2 Mercenaries-local v1.0 for game v1.15
		Currently inactive

	Mishanya-Animated Weapons+-2503670951 v2.1 for game v1.18.1+
		Currently inactive

	kortl-Combat Knifes-local v1.0 for game v1.7
		Currently inactive

	zooi-flipping heck-2448120172 v1.6 for game v1.21
		Currently inactive
		Has been initialised

	Kyrelink and Quickness-The ULTIMATE Minecraft Mod-2442812460 v1.6 for game v1.21+
		Currently inactive

	Talon Zane-Map Blocks-local v1.0 for game v1.7
		Currently inactive

	kortl-COMBAT SPEC-OPS-local v1.0 for game v1.14
		Currently inactive

	kortl-COMBAT SPEC-OPS MAP-local v1.0 for game v1.14+
		Currently inactive

	zuchian&janb-generic jojo mod-2391194926 v1.0 for game v1.10+
		Currently inactive

	G[DEATH]P-PAYDAY 2: People Playground Edition-2381717092 v1.0 for game v1.14+
		Currently inactive

	Morzzic-Taser-2361892819 v1.2 for game v1.11+
		Currently inactive

	moonSIq-Secure. Contain. Protect [SCP MOD]-2361867196 v1.2 for game v1.12
		Currently inactive

	ImJustAlex-Spy TF2 Pack-2350995426 v1.0 for game v1.12.2+
		Currently inactive

	jimmyl-ExplosiveMod-2337158074 v1 for game v1.10+
		Currently inactive

	sqɐɹ-Tactical Armors-2334842610 v1.1 for game v1.9+
		Currently inactive

	[TSF] Life.exe-S.C.P.F. mod-2332568618 v1.0 for game v1.12+
		Currently inactive

	 TrulyDivined/ fixed by apfirsichdoe-JoJo's Bizarre Mod FIXED-local v1.0 for game vdefinitely up-to date!
		Currently inactive

	Damianos28,Kyrelink-More Destructible Objects !-2319326006 v1.0 for game v1.13.1
		Currently inactive

	zooi-Per Pixel Destruction-2314372940 valpha 7 for game v1.13.1
		Currently inactive

	Alibarda-Human Tiers-2308911224 vv4.2 for game v1.12+
		Currently inactive

	Adskiy Drochila & Woowz11-Madness PACK-2299286896 v1.6.0 for game v1.12.2
		Currently inactive

	apfirsichdoe-R6S Echo Drone-local v1.0 for game vdefinitely up-to date!
		Currently inactive

	Penggrin-С4-local v1.0 for game v1.12.1
		Currently inactive

	Punkkinn-Super Gorse Mod-local vv1.0 for game v1.11+
		Currently inactive

	Memealade-Prison Mod-2280186226 v1.0 for game v1.12+
		Currently inactive

	enigmaburrito21-Hitman Mod-2279170186 v1.5 for game v1.10+
		Currently inactive

	sqɐɹ-Bow mod-local v2.0 for game v1.9
		Currently inactive

	apfirsichdoe-R6S Blitz Shield-2277062329 v1.0 for game vdefinitely up-to date!
		Currently inactive

	Alibarda-PowersMod-2276255188 v1.7 for game v1.12+
		Currently inactive

	apfirsichdoe-R6S Tachanka Mounted LMG / DP-28-local v1.0 for game vdefinitely up-to date!
		Currently inactive

	apfirsichdoe-R6S Montagne Shield-local v1.0 for game vdefinitely up-to date!
		Currently inactive

	Teletubbie With A Shotgun-SCP: Secret Laboratory-local v1.0.5 for game v1.9+
		Currently inactive

	BuzzBoi-Iron Man Mod-2258872261 v1.2 beta for game v1.11.1+
		Currently inactive

	Teletubbie With A Shotgun-PPG Spy Mod-local v1.0.5 for game v1.9+
		Currently inactive

	gwenenenen-More Guns-2235585600 v1.0 for game v1.10.2
		Currently inactive

	Golden, Talon Zane-Among Us Mod-2232883786 v1.0 for game v1.9+
		Currently inactive

	weirdo-Chemical Warfare-2226697361 v2.0 for game v1.22.2+
		Currently inactive

	Teletubbie With A Shotgun-Vietnam Soldiers Mod-2221749809 v1.0.5 for game v1.9+
		Currently inactive

	Golden-Hazmat Mod Remastered-2217857980 v1.3.1 for game v1.9+
		Currently inactive

	weirdo-Advanced Damage-2212880187 v2.1 for game v1.22.2+
		Currently inactive

	CyberPlays26-Cyber's WWII Mod-2212721487 v1.14 for game v1.10+
		Currently inactive

	BuzzBoi-UNSC Soldiers Mod-2212556006 v1.3 beta for game v1.9+
		Currently inactive

	ycson64 the original idea-Horror pack 2-2205316545 v1.0 for game v1.9
		Currently inactive

	ycson64 the original idea-Horror pack-2201579216 v1.0 for game v1.9
		Currently inactive

	DRAGOLITE-Armor Mod (for PM 2)-local v1.0 for game v1.9+
		Currently inactive

	weirdo-Functioning Armor-2194511729 v3.0 for game v1.22.2+
		Currently inactive

	ImJustAlex-Scout TF2 Pack-2191763564 v1.0 for game v1.9
		Currently inactive

	DRAGOLITE-Purple mod 2-2191020236 v1.0 for game v1.9+
		Currently inactive

	Svit and Sky-POT O' Items-2187367733 v1.2 for game v1.9.4
		Currently inactive

	Anushammer-High Power Weapons-local v1.0 for game v1.9.3
		Currently inactive

	glubjustglub-Counter Terrorist Organization Pack-local v1.0 for game v1.9
		Currently inactive

	ApDown-Pepsi and Cola Mod-2177098291 v1.0 for game v1.9.x
		Currently inactive

	little andy-Andy's 50.cal M2 Browning-2175370982 v1.0 for game v1.9+
		Currently inactive

	CyberPlays26-Research Facility Mod-local v1.0 for game v1.9+
		Currently inactive

	odriw-Half-Life PPG-2172043870 v1.0 for game v1.9
		Currently inactive

	WhereAreYourFingers-Tacti-cool attachments-2171934520 v1.0 for game v1.7
		Currently inactive

	Kelly The Dragon-The Tungsten Mod-2170418527 v2.4 for game v1.8 +
		Currently inactive

	Woowz11-BloodEye3-2170110891 v0.5 for game v1.9+
		Currently inactive

	Sororfortuna-Soror's NPC Pack-2169243678 v11.0 for game v1.19.2
		Currently inactive

	Mr_kWKD-Humans+-2168468454 v1.3.0 for game v1.9
		Currently inactive

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently inactive

	kortl-COMBAT Zombies-local v1.0 for game v1.8.x
		Currently inactive

	Kyrelink-Thanos Mod-2147119657 v1.5 for game v1.9+
		Currently inactive

	TailsIsAwesome-Sans Bone-local v1.0 for game v1.8+
		Currently inactive

	Kyrelink-Half Life 2 weapons-2140530282 v1.6 for game v1.7
		Currently inactive

	kortl-COMBAT Weapons Mod Pack-local v1.0 for game v1.7.x
		Currently inactive

	kortl-COMBAT Weapons Pack V3.0-local v3.0 for game v1.7.x
		Currently inactive

	kortl-COMBAT Props Pack-local v1.0 for game v1.7.x
		Currently inactive

	BBQGiraffe-Doom weapons pack-2137895715 v3.0 for game v1.8.x
		Currently inactive

	Grizzly-Ancient Weapons Pack-2137861405 v13.0 for game v1.8.x
		Currently inactive

	Cyxil-Expanded Lightsabers-2137839183 v1.3 for game v1.8
		Currently inactive

	Farsh-Different Bricks-2137705970 v1.1 for game v1.8
		Currently inactive

	kortl-COMBAT Clothes Pack-local v1.0 for game v1.7.x
		Currently inactive

	(RU)Enot builder-Weapon Mod-2137486750 v0.8 for game v1.7x
		Currently inactive

**Comment by vda8** [comment]
tf. u need to learn grammar.

**Comment by wordpass1** [comment]
do you perhaps mean left hand? (assuming you spawn objects facing right by default like a normal person)
