### ISSUE TITLE
Walking when shot

### ISSUE THREAD

**Issue by DrakoNN08** [studio-minus/ppg-bugs-and-requests#901]
**Describe the bug**
Idk if its actually a bug but the new feature "Organisms have a chance to walk a bit when shot" bugs if you shoot a human with an assault rifle thats on full auto, because the feature activates a couple of times and the human doesn't stop walking.

**Clearly describe how to reproduce the bug**
shoot a human with a full auto gun

**Mod list**
my mods we're deactivated

**System info**
 - Operating system: Windows 10
 - Game version: 1.23 (beta)
 - GPU: Nvidia gtx 1070
 - CPU: amd ryzen 7 1700

https://user-images.githubusercontent.com/101907282/159095303-3bc5995d-1792-46d7-bc0d-54701e9a9aec.mp4

**Comment by mestiez** [comment]
fixe
