### ISSUE TITLE
Lights falling off in Default map.

### ISSUE THREAD

**Issue by FutureCorpses** [studio-minus/ppg-bugs-and-requests#902]
**Describe the bug**
I was playing normally when the lights fell off.
**Clearly describe how to reproduce the bug**
I dont really know, i was just shooting with the bazooka at an android then i zoomed out and noticed the lights fell off and  the map was splited in 2, one were light was ok and one were the light was off?
**Mod list**
Deactivated mods : human dynamic emotions, node mapper, crap ton of damage, OCM, Metal humans, raw pink liquids, cyberpunk 2077 Trauma medic pack, Injectable flasks mod, Russian civil war, Vanilla weapons+3, Animated weapons+, scream mod, metal things mod, Nuclear playground, 1000 degree knife, Iraq war mod, Buff human, More weapons mod, Vanilla weapons+2, Military+, SCP Foundation expanded, explosive mod, S.C.P.F mod, chemical warfare, advanced damage, active humans.   Activated Mods :  Object editor, mini roleplay mod, TIme changer tool, The ultimate human mod, quick right click options, Flipping heck, Liquids map.

**System info (please complete the following information)**
 - Operating system:  Windows 10 pro 
 - Game version: 1.23 preview 9
 - GPU: Gtx 1060 6gb
 - CPU: i5 9400f

**Comment by mestiez** [comment]
Related to #1
