### ISSUE TITLE
Pictures.

### ISSUE THREAD

**Issue by RovarPlaysYT** [studio-minus/ppg-bugs-and-requests#905]
## Information
Mechanic, this mechanic would add custom pictures.

To add custom pictures, you should create folder "Pictures" in folder of game

## Example
![new](https://user-images.githubusercontent.com/100331909/159101391-bb06a4b1-e770-4bfe-8553-e18874721379.png)

**Comment by UniDuki** [comment]
How would that work when uploading to the workshop?

**Comment by DindinYT37** [comment]
> How would that work when uploading to the workshop?

Compress image minimum size and resolution - then send as blob.

**Comment by mestiez** [comment]
i think this would just make the workshop an NSFW hell
