### ISSUE TITLE
Laser Projectiles doesn't seem to collide with bottles

### ISSUE THREAD

**Issue by unknown-4o4** [studio-minus/ppg-bugs-and-requests#909]
**Describe the bug**
When firing any laser weapons at bottles, it seems to go through without any damage or collision in my testing.

**Clearly describe how to reproduce the bug**
Fire any laser weaponry (exclusion to beam rifle as it doesn't fire the regular laser projectile) towards a bottle.

**Mod list**
None

**System info (please complete the following information)**
 - Operating system: 
 - Game version: Beta 1.23
 - GPU: 1660ti
 - CPU: i5 9600kf

**Additional notes**
I hope this is an actual bug and not me overlooking a feature of some sort, Please do correct me if I am wrong.

**Comment by UniDuki** [comment]
This is most likely intentional, this also happens with liquid flasks.

**Comment by mestiez** [comment]
yes they are glass

**Comment by unknown-4o4** [comment]
Oh I see, I'm sorry.
