### ISSUE TITLE
make resizable housing heavier

### ISSUE THREAD

**Issue by ifrost-source** [studio-minus/ppg-bugs-and-requests#910]
**Feature description**
I think the title already says it all, but I would like to be able to make vehicles of the colors I want with the resizable housing, but it is lighter than the metal rod and physics goes crazy when you make a vehicle with the same ones tied with fixed cables and collides with something.

**Comment by DindinYT37** [comment]
I think you're supposed to freeze it, but yes, I agree. Since it changes weight on resize anyways, the base weight might as well be heavier.

**Comment by mestiez** [comment]
Rezisable housing is supposed to be decorative and have little influence over the contraption

**Comment by ifrost-source** [comment]
?? that does not justify that it is so light, if you want it to "have little influence on the gadget" for that there is the option of "make weighless" and it is not useful for decoration either, try making the mattress of a bed and when putting the mattress to bed a human it looked like jelly

**Comment by DindinYT37** [comment]
> ?? that does not justify that it is so light, if you want it to "have little influence on the gadget" for that there is the option of "make weighless" and it is not useful for decoration either, try making the mattress of a bed and when putting the mattress to bed a human it looked like jelly

Just put a small I-beam or some metal rods between/under it? And if it still wiggles but less, a mattress is soft 🤷🏼‍♂️

**Comment by DindinYT37** [comment]
Update: I have made a bed with a mattress completely out of resizable housing blocks, and it doesn't jiggle at all - the bed just moves around a bit, but it doesn't jiggle and the moving can be fixed by adding small weights.

![image](https://user-images.githubusercontent.com/64973205/162634247-1658fe33-a187-4ae4-8fe7-a2eb8715ce78.png)
