### ISSUE TITLE
Map falling apart

### ISSUE THREAD

**Issue by wiktor822** [studio-minus/ppg-bugs-and-requests#913]
**Describe the bug**
when you drasticly increase temperature of the room it all falls apart (did it on sea don't know if works in another maps)

**Clearly describe how to reproduce the bug**
Step.1 go to sea map
Step.2 open envirement
Step.3 increase temperature drasticly
Step.4 map falls apart 
Step.5 Success

**Mod list**
Time Accelerator
Acid sea map
Active humans
Alexander Lukashenko
Andrzej duda
Animated weapons+
Army mod outdated
Basic syringes mod
Ben mod
Bombs expanded
bulletproof+
car mod
cinematic mod
Coca cola mod
controlled sea 
Coon & friends south park
CRT television
Dolls for tests 2
doors mod
DreamSMP mod
Dynamic human emotions
Emergency siren
eric cartman,kyle broflovski,stan marsh,kenny maccormnick mods
Explomod 
feelings mod 
Feeling mod DLC
flipping heck
FNAF MOD 
FFP building kit
functional androids
Guns'N ammo
hats mod 
human tiers
humans+
item plus
Katana
KT gun boat
law enforcement base entire series
Madness mod
melon playground 
Metal things mod
Military mod
Military nod expansion WW2 and right lads
modern firearms 
more explosives
mulitate a doll 2 mod
Old maps
ostrumian PME
piano mod
Polish untis
private military contractor
Prop mod
prototype humans mod
Quality of Life items
quick right click options
rooms & furniture
Russia vs ukraine mod 
simple syringes (reupload)
syringes and more
tactical zelensky mod 
the moyai mod
uncharted territory portal 
Undertale mod
Volodimir Putin mod

**System info (please complete the following information)**
 - Operating system: Windows 11
 - Game version: 1.23 preview
 - GPU: NVIDIA Geforce MX330
 - CPU: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.20 GHz

**Comment by mestiez** [comment]
Already fixed and reported before
