### ISSUE TITLE
Water as a usable fluid

### ISSUE THREAD

**Issue by TheTypoIsIntentoinal** [studio-minus/ppg-bugs-and-requests#917]
**Feature description**
Adding water as a liquid that can be put in tanks, syringes, flasks, & bottles.

**Feature purpose**
Water would be a harmless liquid that would be able to dilute things. Maybe you would be able to collect it from bodies of water on the map (e.g. holding a container in pull mode underwater.)

**Comment by mestiez** [comment]
i kind of like the idea that water doesn't exist
