### ISSUE TITLE
gorse blood be funky

### ISSUE THREAD

**Issue by goosevrio** [studio-minus/ppg-bugs-and-requests#920]
![sea](https://user-images.githubusercontent.com/100480028/159141536-cf1971cd-c646-4efd-819f-64947147b866.png)
Human blood turning into gorse blood

**Clearly describe how to reproduce the bug**
1. Infect Human with gorse blood
2. suck blood out of human
3. its green now :)

**Mod list**
Human Dynamic Emotion
Active Humans

 - Operating system: Windows 10
 - Game version: 1.23 beta

**Comment by mestiez** [comment]
this is just because the gorse blood is inside the human and youre pulling that out too

**Comment by goosevrio** [comment]
Yes, but that didn’t happens in the update before this preview
