### ISSUE TITLE
Clear everything button makes lights go black for very small second.

### ISSUE THREAD

**Issue by royalealbert27** [studio-minus/ppg-bugs-and-requests#921]
**Describe the bug**
I don't know if this is a bug or intentional but when you clear everything, the lights go black for very small second.

**Clearly describe how to reproduce the bug**
Go to a map then press clear everything then you will see the light blacks out for like a millisecond

exported game debug info:
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8310320/exported.game.debug.info.md)

**Additional notes**

**Comment by hellothere4534** [comment]
Yea it happens to me too

**Comment by mestiez** [comment]
fixed

**Comment by RovarPlaysYT** [comment]
It happends to me too
