### ISSUE TITLE
Multiplayer with steam friends?

### ISSUE THREAD

**Issue by hellothere4534** [studio-minus/ppg-bugs-and-requests#922]
Multiplayer
With shift + tab you can invite a friend on steam and then when playing multiplayer together you can see what each other
will spawn and do and move. Maybe something up to 4 players ig, the players still have free camera ofc. It might be glitchy and weird but I bet me and my friends and people from the people playground community would love it.

Purpose
I think it will be lots of fun, it's kind of a big thing to add and not a minor update. It's purpose is for friends to have fun
and build together and move humans together and make contraptions together.

and then a small image explaining it
![picc](https://user-images.githubusercontent.com/101953811/159142110-8a1acfd0-64f5-463a-a37d-44e667b1ab5c.PNG)

**Comment by royalealbert27** [comment]
another multiplayer suggestion *sigh*

**Comment by DindinYT37** [comment]
mestiez/zooi has said multiple times that Multiplayer is not planned and will **very** likely never be added.

**Comment by WWWOWWWPL** [comment]
a mod that adds it would be a lot better at this point. like hell if a three dimensional version of the game is possible then some form of multiplayer wouldnt be as big of a stretch as it was when ppg first came out on steam

**Comment by hellothere4534** [comment]
Looks like mestiez has rejected this before, gonna close it down

**Comment by JakeDreemurrYT** [comment]
i agree with mestiez not wanting to work on multiplayer, its genuinely hard to make that system and have it working Greatly with a game such as PPG. its not impossible like other games that have been made multiplayer through community Power such as BeamNG (i think). but it'll just take a lot of time and progression off from the playground
