### ISSUE TITLE
blood is not appearing on the walls and on items 

### ISSUE THREAD

**Issue by imheretoreportbugs** [studio-minus/ppg-bugs-and-requests#923]
**Describe the bug**
A clear and concise description of what the bug is.                            blood is coming out of the human/gorse but not on the walls or 
                                                                                                                                                    items anymore
                                                                                                                                                                   

**Clearly describe how to reproduce the bug**                                  i dunno

Steps to reproduce the problem.

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
                                                                                                                     no mods
**System info (please complete the following information)**
 - Operating system: windows
 - Game version:1.22.3
 - GPU:
 - CPU:

**Additional notes**
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8310484/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
You seem to have Decals disabled in your settings.
