### ISSUE TITLE
NullReferenceException spamming debug logs and lagging game over time

### ISSUE THREAD

**Issue by DindinYT37** [studio-minus/ppg-bugs-and-requests#931]
**Describe the bug**
Everytime I played for some time, I noticed more and more lag coming even though I've not been doing much. Out of interest I enabled Debug Logs and saw this. I have had this issue for quite the time now, but haven't thought much of it as I don't play the same map for very long. Though, today when I did play very long, the lag has become almost unbearable to the point where when I would usually have 150+ fps I'd have barely 10 fps.

![image](https://user-images.githubusercontent.com/64973205/159169738-3324eeae-ab4c-42a0-95e2-813429f5f25d.png)

**Clearly describe how to reproduce the bug**
No idea.

**Exported Game-Debug Info file**
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8311546/exported.game.debug.info.md)

**Additional notes**
Does anyone else have had this issue? I'm guessing it's because of a mod but sadly debug logs don't show me which mod it is from.

**Comment by mestiez** [comment]
This is most certainly caused by some mod
