### ISSUE TITLE
Remove scary thing in tv option

### ISSUE THREAD

**Issue by RovarPlaysYT** [studio-minus/ppg-bugs-and-requests#932]
**Feature description**
New option in settings that removes this scary thing in tv.
![image](https://user-images.githubusercontent.com/100331909/159169801-5affd00f-c537-4200-a745-0a5db819f808.png)

**Feature purpose**
I request this option, because this scary thing scares people when they play at night.

**Additional context**
No

**Comment by royalealbert27** [comment]
Don't play people playground in night then

**Comment by vda8** [comment]
Scared

**Comment by ppgplayer** [comment]
> Don't play people playground in night then

are you trying to set a god damn curfew on ppg

**Comment by vda8** [comment]
I have seen this thing a million times. Imagine getting scared by a sandbox game XDDDD
