### ISSUE TITLE
Space-map

### ISSUE THREAD

**Issue by hellothere4534** [studio-minus/ppg-bugs-and-requests#933]
Space-map
A space map where everything is 0 gravity ( maybe some planets around ), maybe add that there is no oxygen too so humans can suffocate when in space. ( Along with space suits and along with oxygen tanks )

Purpose
I dunno, I just think it would be cool, a space-map, space suits and oxygen tanks.

**Comment by DindinYT37** [comment]
I mean you could go to the void map, set gravity to 0 and make your own planets.

**Comment by vda8** [comment]
Void map. 0 gravity. Easy.

**Comment by DindinYT37** [comment]
> Void map. 0 gravity. Easy.

Everytime I see you comment on something after me, it feels like you just repeated my comment but shorter.

**Comment by vda8** [comment]
> > Void map. 0 gravity. Easy.
> 
> Everytime I see you comment on something after me, it feels like you just repeated my comment but shorter.

I didn't see ur comment. I just clicked and wrote something XD

**Comment by hellothere4534** [comment]
Your guys ideas sound great, but do you guys know anyhow to make an oxygen system in people playground? Like humans suffocate to death if they don't have a helmet, if you know any oxygen/space mods then please tell me :)

**Comment by DindinYT37** [comment]
> Your guys ideas sound great, but do you guys know anyhow to make an oxygen system in people playground? Like humans suffocate to death if they don't have a helmet, if you know any oxygen/space mods then please tell me :)

Bet there's a mod that sets Humans to constantly have 0 Oxygen and require something attached to them, if not, might as well ask for someone to make it in a Modding discord.

**Comment by hellothere4534** [comment]
Ok thank you very much! gonna close this thing down now.
