### ISSUE TITLE
Guns jamming when in contact with water

### ISSUE THREAD

**Issue by atwal6400** [studio-minus/ppg-bugs-and-requests#934]
**Feature description**
When any gun lays in water for a certain amount of time it jams and cannot be fired again,

**Feature purpose**
realism, scenic, and a cool detail

**Comment by unknown-4o4** [comment]
not sure where you sourced this information from.

**Comment by atwal6400** [comment]
> not sure where you sourced this information from.

wdym

**Comment by vda8** [comment]
No

**Comment by bluewoods64** [comment]
> not sure where you sourced this information from.

its a suggestion not a bug report

**Comment by unknown-4o4** [comment]
> > not sure where you sourced this information from.
> 
> its a suggestion not a bug report

Never said it was, guns don't just jam when coming into contact with water; It would be heavily unreliable otherwise

**Comment by TamasB14** [comment]
I really like those "realism" topics where the poster has no idea about how realistic guns work.

There are of course guns that are not possible to fire underwater which are mostly the open pistol systems, but rifles with closed system do not tend to jam under water. AK is known well for being able to shot under water, even in a muddy habitat.
