### ISSUE TITLE
The map selection menu is off-centered

### ISSUE THREAD

**Issue by TheBeeThat** [studio-minus/ppg-bugs-and-requests#935]
**Describe the bug**
because of the new 2 maps (lava 1.20, substructure 1.23) the map selection menu looks off centered now.

ghhh
![image](https://user-images.githubusercontent.com/96020070/159184131-6ef08bb8-d454-4852-966a-a71375c9b074.png)

moved the map menu (or viewport) position a little bit
![image](https://user-images.githubusercontent.com/96020070/159184177-4e4a8021-c10c-498c-a155-4a889e3bb9a7.png)

looks better doesnt it?

**Clearly describe how to reproduce the bug**
Open the game, press play

**System info (please complete the following information)**
 - Operating system: Windows 11 x64
 - Game version: 1.20-1.23
 - GPU: GT 740
 - CPU: Intel i5-4460

**Additional notes**
hello

**Comment by DindinYT37** [comment]
Duplicate of #856

**Comment by TheBeeThat** [comment]
damnit

**Comment by TheBeeThat** [comment]
damnit
