### ISSUE TITLE
Fix/Clean up Substructure without having to reload the entire map

### ISSUE THREAD

**Issue by JakeDreemurrYT** [studio-minus/ppg-bugs-and-requests#936]
**Feature description**
A button in the corner like clean up map/entities/etc. (Mainly for substructure)
**Feature purpose**
it fixes the Substructure's map like the elevator, glass, and Vents without having to reload the entire map, addons, and in-game items.
i haven't seen anything i could do than choosing the same map to reload over and over

**Comment by mestiez** [comment]
this has actually been implemented a while ago now. just press "Clear everything"
