### ISSUE TITLE
Indestructible Cables Are not Indestructible 

### ISSUE THREAD

**Issue by humaaaan** [studio-minus/ppg-bugs-and-requests#938]
**Describe the bug**
The Indestructible cables are not  Indestructible 

**Clearly describe how to reproduce the bug**
get indestructible cables and shoot them with beam rifle or any with similar power and the will break even tho they say indestructible 

**Mod list**

occy0803-Vanilla+-local v1.0 for game v1.22+
		Currently ACTIVE

	Aspa102-Favourites Category-local v1.0 for game v1.23+
		Currently ACTIVE

	Dyadyushka Dyadya-SpawnableLift-2780861030 v1.0 for game v1.23+
		Currently ACTIVE
		Has been initialised

	zooi-Darker blood-local v1.0 for game v1.22
		Currently ACTIVE

	Mishanya-Maps-2777501047 v1.2.2 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Controlled Sea-2776630725 v1.0 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	Quickness-Prison Bus-2776557560 v1.1 for game v1.22.3+
		Currently ACTIVE

	royalealbert27-Albert's Random Maps-2774819209 v1 for game v1.22.3
		Currently ACTIVE
		Has been initialised

	Pumpkin-Old Maps-2765380132 v1.2 for game v1.22.3
		Currently ACTIVE
		Has been initialised

	Orsoniks / Navii-SimplePortals-2759460093 v1.0 for game v1.22+
		Currently ACTIVE

	Dyadyushka Dyadya-Acid Sea-2759438689 v1.0 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	Dyadyushka Dyadya-Random Activation Propagation-2757227786 v1.0 for game v1.22.3+
		Currently ACTIVE

	Dyadyushka Dyadya-Inverse Teleportation-local v1.0 for game v1.11
		Currently ACTIVE

	Dyadyushka Dyadya-Uncharted Territory Portal-local v1.0 for game v1.11
		Currently ACTIVE

	Orsoniks / Navii-Wound Infections-2729065060 v1.0 for game v1.22+
		Currently ACTIVE

	zooi-Buoyant-local v1.0 for game v1.22.4
		Currently ACTIVE

	Aspa102-Limb Regrowth Syringe (Passive)-2708526361 v1.0 for game vpainfully amounts of pain
		Currently ACTIVE

	pjstarr12-Feet Arent Indestructible-local v1.02 for game v1.0+ i think
		Currently ACTIVE

	zuchian-Overclocker-local v1 for game v1.10+
		Currently ACTIVE

	pjstarr12-Bones Break On Shot-local v1.02 for game v1.0+ i think
		Currently ACTIVE

	TitaniumSpyBorgBear-Invisible Pin Tool (Updated!)-local v2.0 for game v1.22.2+
		Currently ACTIVE

	JohnnyTaco-Puppet Master-2668334393 v1.70.4 for game v1.22.x
		Currently ACTIVE
		Has been initialised

	Matyfou-Firecrackers-2666846595 v1.1 for game v1.12.2+
		Currently ACTIVE

	Talonphobia-Talon Zane's Marvelous Weapon Week II-local v1.0 for game v1.22.2+
		Currently ACTIVE
		Has been initialised

	SuperPlayerHK-No Camera Zoom Limit-local v1.0 for game v1.11
		Currently ACTIVE

	Talonphobia-Talon Zane's Marvelous Weapon Week I-2656268059 v1.0 for game v1.22.2+
		Currently ACTIVE
		Has been initialised

	MoodlethenoodIe-Basic Syringes Mod-2646920523 v1.0 for game v1.20+
		Currently ACTIVE

	Mishanya-Car Mod-2645663875 v0.4 for game v1.22.3+
		Currently ACTIVE

	Orsoniks / Navii-Status Icons-2644689646 v0.1 for game v1.22
		Currently ACTIVE

	Talonphobia-Toy Balloon Gun from Boneworks-local v1.0 for game v1.22+
		Currently ACTIVE

	Quickness-More Coloring Vases-local v1.0 for game v1.22
		Currently ACTIVE

	pjstarr12-Customizable Gun Mod-local v1.0 for game v1.21+
		Currently ACTIVE

	PeppRRicoochie-The Grappling Gun Mod-2637017257 v2.1 for game v1.22.3
		Currently ACTIVE

	Quickness-Fishing Rod-local v1.0 for game v1.21x
		Currently ACTIVE

	Azule, Quickness-Fish Mod-2599934778 v1.3 for game v1.21x
		Currently ACTIVE

	Morzzic-Object Editor-2590195142 v1.2 for game v1.17+
		Currently ACTIVE

	Maxe-Double Barrel Shotgun Mod-local v1.0.0 for game v1.19+
		Currently ACTIVE

	fieryhenry-Modifiable Weight-local v1.0 for game v1.20+
		Currently ACTIVE

	jimmyl-Liquid-related Machinery-2550340103 v0.6 for game v1.19+
		Currently ACTIVE

	davidco7777-Tranquilizer Rifle Mod-local v1.0 for game v1.19+
		Currently ACTIVE

	davidco7777-Black Hole Tool-2547353717 v1.0 for game v1.8+
		Currently ACTIVE

	chonk-Skeleton Mod-local v1.0 for game v1.15
		Currently ACTIVE

	davidco7777-Raw Pink Liquids-2546503625 v1.2 for game v1.21+
		Currently ACTIVE

	Pumpkin-Simple Syringes Mod-2522356867 v2.2 for game v1.18+
		Currently ACTIVE

	sneby-Thermal Devices-2518984513 v1.1 for game v1.19+
		Currently ACTIVE

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently ACTIVE

	MR.REX-Emergency Siren-2509362434 v0.6 for game v1.21+
		Currently ACTIVE

	zooi-Signals and Logic Gates-2504621801 v1.3 for game v1.22.3
		Currently ACTIVE
		Has been initialised

	Frosty-Configurable Explosive-local v1.1 for game v1.15
		Currently ACTIVE

	Pumpkin-Quality of Life Items-2500516293 v1.7 for game v1.22.3
		Currently ACTIVE

	The Ninja Scout-Decomposition-2497957604 v1.0 for game v1.11
		Currently ACTIVE

	zooi-Gentle Drag-2490855955 v1.0 for game v1.18 preview 1
		Currently ACTIVE

	Quickness-Metal Things Mod-local v1.0 for game v1.17x
		Currently ACTIVE

	Talonphobia-Greenbrick Industries-2476975606 v1.3 for game v1.18+
		Currently ACTIVE
		Has been initialised

	zooi-depletable engines-2463360042 v1.3 for game v1.19
		Currently ACTIVE

	JGrimesGamed-Mo' Fluids-2460574441 v1.0 for game v1.16+
		Currently ACTIVE

	JGrimesGamed-Gasoline Enabler-local v1.0 for game v1.16+
		Currently ACTIVE

	Aspa102-Wheelchair-2455335631 v1.0 for game v1.16+
		Currently ACTIVE

	Daan Banaan-Retractable Sword Mod-local v1.0 for game v1.14+
		Currently ACTIVE

	zooi-flipping heck-2448120172 v1.6 for game v1.21
		Currently ACTIVE
		Has been initialised

	Talon Zane-Map Blocks-local v1.0 for game v1.7
		Currently ACTIVE

	Pumpkin-Doors Mod-2400494139 v1.4 for game v1.15
		Currently ACTIVE

	2factory-Human-like Android-2396107312 v1.0 for game v1.14
		Currently ACTIVE

	2factory-Android-like Human-2395986724 v1.0 for game v1.14
		Currently ACTIVE

	Mishany-Melee Weapons Mod-2389733225 v7.0 for game v1.13+
		Currently ACTIVE

	Crafter_215-More Explosives-2383112201 v1.1 for game v1.11
		Currently ACTIVE

	ScriptMeat-Drawables-2368861932 v1.0 for game v1.12+
		Currently ACTIVE

	Morzzic-Taser-2361892819 v1.2 for game v1.11+
		Currently ACTIVE

	jimmyl-ExplosiveMod-2337158074 v1 for game v1.10+
		Currently ACTIVE

	Morzzic-Aimbot Gun-2327621346 v1.0 for game v1.8.1
		Currently ACTIVE

	jimmyl-Parts and Contraptions-local v1 for game v1.10+
		Currently ACTIVE

	Sv1t-TheDoll-2260750080 vDoll for game vDoll
		Currently ACTIVE

	weirdo-Chemical Warfare-2226697361 v2.0 for game v1.22.2+
		Currently ACTIVE

	Talon Zane-Tethers-2211493781 v1.1 for game v1.11.1+
		Currently ACTIVE

	Mr_kWKD-Super Slow Motion-2202856707 v1.0 for game v1.9+
		Currently ACTIVE

	ApDown,Woowz11,Morzzic,Azule-Controllable UFO-2198120027 v1.0 for game v1.9.+
		Currently ACTIVE

	Morzzic-Smart Spawner-2195054961 v2.2 for game v1.10+
		Currently ACTIVE

	Morzzic-Russian Roulette Mod-2173352550 v1.1 for game v1.9+
		Currently ACTIVE

	Morzzic-Time Accelerator-2167988616 v1.1 for game v1.8+
		Currently ACTIVE

	quaq-Active Humans-2163278857 v2.0 for game v1.9+
		Currently ACTIVE

	zooi-Hold K to make wires invisible-2137429065 v1.0 for game v1.7.2
		Currently ACTIVE

**System info (please complete the following information)**
## System info

 - **OS**: Windows 10  (10.0.19044) 64bit

 - **CPU**: Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

 - **GPU**: NVIDIA GeForce RTX 2060

 - **Memory**: 16 GB

**Additional notes**
its annoying

**Comment by ppgplayer** [comment]
I'm more surprised you have all of your mods on at the same time

**Comment by DindinYT37** [comment]
This has been happening since they've been added, I'm more surprised you just noticed that - anyway, I think this is actually intended but who knows.

**Comment by mestiez** [comment]
This is intentional
