### ISSUE TITLE
Items in lab

### ISSUE THREAD

**Issue by RovarPlaysYT** [studio-minus/ppg-bugs-and-requests#948]
**Describe the bug**
When you create portal in substructure, items from substructure go to lab.

**Clearly describe how to reproduce the bug**
1. Go to substructure.
2. Make portal.
3. Wait.
4. You see items.

**All loaded mods**
	Eduardoeldo-The Nearby Conflicts Base: Canada-2782773799 v1 for game v1.21.2
		Currently ACTIVE

	Orsoniks / Navii-Blood on walls-2782471815 v1.0 for game v1.23+
		Currently ACTIVE

	Aspa102-Favourites Category-local v1.0 for game v1.23+
		Currently ACTIVE

	Dyadyushka Dyadya-SpawnableLift-2780861030 v1.0 for game v1.23+
		Currently ACTIVE
		Has been initialised

	loudyfam-MilitaryMod Expansion: Slovenia-local v1 for game v1.20
		Currently ACTIVE

	Blocksify-Blocksify's Mafia Mod Remastered-local v1.0 for game vEverybody
		Currently ACTIVE

	590a1shooter-beer flask-local v1.0 for game v1.7+
		Currently ACTIVE

	Dyadyushka Dyadya-Controlled Sea-2776630725 v1.0 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	Quickness-Prison Bus-2776557560 v1.1 for game v1.22.3+
		Currently ACTIVE

	citizen-Private Military Contractors-2775910556 v2.4 for game v1.8 +
		Currently ACTIVE

	Eduardoeldo-Law Enforcement Base: Germany-local v1 for game v1.21.2
		Currently ACTIVE

	Eduardoeldo-Law Enforcement Base: Less Lethal DLC-local v1.2 for game v1.11+
		Currently ACTIVE

	Skittles-Guns 'N Ammo-2761082698 v1.0 for game vwhatever is the latest
		Currently ACTIVE

	Orsoniks / Navii-SimplePortals-2759460093 v1.0 for game v1.22+
		Currently ACTIVE

	Dyadyushka Dyadya-Acid Sea-2759438689 v1.0 for game v1.22.3+
		Currently ACTIVE
		Has been initialised

	Eduardoeldo-Law Enforcement Base: USA-2754575076 v1 for game v1.21.2
		Currently ACTIVE

	01 Studios-Human Dynamic Emotions-2745225441 v1.0 for game v1.22+
		Currently ACTIVE

	JOSIMA-Enhanced Human Sounds-2738554876 v0.1 for game v1.11+
		Currently ACTIVE

	Dyadyushka Dyadya-Uncharted Territory Portal-local v1.0 for game v1.11
		Currently ACTIVE

	fR4n1oo0, Mako, Zuchian and Painter-Five Nights at People Playground-local v1.0 for game v1.19+
		Currently ACTIVE

	Crin-Crin's Civil war Mod-2731616281 v1.1 for game v1.22.3
		Currently ACTIVE

	Senpai-i-i...-Traumatic Gun-2730106495 v1.0 for game vAny
		Currently ACTIVE

	citizen-Modern Firearms-2721105504 v1.0 for game v1.20
		Currently ACTIVE

	Nev~u-Purple guy-local v1.4 for game v1.12+
		Currently ACTIVE

	kirillX-Doll for tests 2-local v1.0 for game v1.15
		Currently ACTIVE

	Matty14-My Singing Monsters Mod-2709078268 v1.20.08 for game v1.11+
		Currently ACTIVE

	megaturn-Wild Medieval-2708133294 v1.2 for game vAny
		Currently ACTIVE

	pjstarr12-Feet Arent Indestructible-local v1.02 for game v1.0+ i think
		Currently ACTIVE

	Mishanya-Prop Mod-2696169016 v1.3 for game v1.22+
		Currently ACTIVE

	enlisted actor-More Humans Mod-2669494511 v1.0 for game v1.14+
		Currently ACTIVE

	Not A Walrus-JSAB Mod: Pure Mod-local v1.0 for game v1.15
		Currently ACTIVE

	RovarPlaysYT-Ukraine Mod-2782518950 v1.1 for game v1.8.1
		Currently ACTIVE

**System info (please complete the following information)**
 - Operating system: Windows 10 Pro Rus (10.0.19044) 64bit
 - Game version: People Playground [v1.23 preview 14] [64 bit]
 - GPU: AMD Athlon 300U with Radeon Vega Mobile Gfx 
 - CPU: AMD Radeon(TM) Vega 3 Graphics
 - Memory: 6 GB

**Additional notes**
![image](https://user-images.githubusercontent.com/100331909/159432703-0f7fda82-2c18-42c6-acf8-99e553e5a4fa.png)
[exported game debug info.md](https://github.com/studio-minus/ppg-bugs-and-requests/files/8322251/exported.game.debug.info.md)

**Comment by DindinYT37** [comment]
Best bug yet

**Comment by mestiez** [comment]
fixed
