### ISSUE TITLE
Brain dead humans

### ISSUE THREAD

**Issue by Tye-Evans2** [studio-minus/ppg-bugs-and-requests#95]
I found a way to kill humans but keep their upper torso alive.

Hook an empty syringe to a blood tank (ideally use LOTS of blood wires so very little blood reenters the human)and stab the syringe into a humans heart. The second he dies switch the blood flow around and pump a small amount of blood back into the human. If done correctly the humans heart will remain alive while everything else is dead.

I recorded this glitch, so if you want me to send it, I can upload it to youtube then send a link.

# EXPORTED GAME DEBUG INFO
## System info

 - **OS**: Windows 10  (10.0.19042) 64bit

 - **CPU**: Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz

 - **GPU**: NVIDIA GeForce GTX 1650

 - **Memory**: 7 GB

## All loaded mods

	davidco7777-Raw Pink Liquids-2546503625 v1.0 for game v1.19+
		Currently inactive

	Pump3d-Quick Right Click Options-2516131949 v1.0 for game v1.15
		Currently ACTIVE

	Mr_kWKD-The Musket Mod-2502525912 v1.3 for game v1.18+
		Currently inactive

	Skullex(jamesH_2), Aspa102, Kassjak-Scream mod-2494555615 v1.0 for game v1.11
		Currently inactive

	Gun_O-Futuristic Weapons Mod +-2494447929 v0.3 for game v1.17
		Currently inactive

	Scringrandmaster347-Grasslands / Map-2489010038 v1.0 for game v1.17+
		Currently inactive

	Quickness-Iraq War mod-2467426507 v1.0 for game v1.16x
		Currently inactive

	Aspa102-Wheelchair-2455335631 v1.0 for game v1.16+
		Currently inactive

	Mini-Vamlejos (V1)-local v1.0 for game v1.14+
		Currently inactive

	Mini-Delta Aersea (V1)-local v1.0 for game v1.14+
		Currently inactive

	zooi-flipping heck-2448120172 v1.4 for game v1.16.2
		Currently ACTIVE
		Has been initialised

	Mini-Xioandia (V1)-local v1.0 for game v1.14+
		Currently inactive

	Mini-Whimule Planet (V1)-local v1.0 for game v1.14+
		Currently inactive

	Aspa102-Ocean-local v1.0 for game v1.14+
		Currently inactive

	kortl-COMBAT SPEC-OPS-local v1.0 for game v1.14
		Currently inactive

	Quickness-Lake Map-2434310949 v1.0 for game v1.14+
		Currently inactive

	Scriptmeat / Aspa102-TEST MAP 2-local v1.0 for game v1.14+
		Currently inactive

	ScriptMeat-TEST MAP-2403144679 v1.0 for game v1.14+
		Currently inactive

	ScriptMeat-Volcanic Map-2395054754 v1.1.2 for game v1.14+
		Currently inactive

	Avien Jones-Front Facing Human-local v1.0 for game v1.7
		Currently inactive

	ScriptMeat-Gravel, Sand and Water-2353091446 v1.0 for game v1.12+
		Currently inactive

	Skittles-Skittle's Syringe Mod-2268097682 v1.4 for game v1.19+
		Currently inactive

	Talonphobia-Syringes++-2146791852 v2.3 for game v1.12.2+
		Currently inactive

## Last log

```
1526.058s [LOG] Action drag is in universe All
1526.058s [LOG] Action delete is in universe All
1526.058s [LOG] Action activateDirect is in universe Game
1526.058s [LOG] Action slowmo is in universe Game
1526.058s [LOG] Action toggleLimbStatus is in universe Game
1526.058s [LOG] Action time is in universe Game
1526.058s [LOG] Action tool1 is in universe Game
1526.058s [LOG] Action tool2 is in universe Game
1526.058s [LOG] Action tool3 is in universe Game
1526.058s [LOG] Action tool4 is in universe Game
1526.058s [LOG] Action tool5 is in universe Game
1526.058s [LOG] Action tool6 is in universe Game
1526.058s [LOG] Action tool7 is in universe Game
1526.058s [LOG] Action tool8 is in universe Game
1526.058s [LOG] Action tool9 is in universe Game
1526.058s [LOG] Action spawnLeft is in universe Game
1526.058s [LOG] Action spawnRight is in universe Game
1526.058s [LOG] Action left is in universe All
1526.058s [LOG] Action right is in universe All
1526.058s [LOG] Action fast is in universe All
1526.058s [LOG] Action undo is in universe All
1526.058s [LOG] Action snap is in universe All
1526.058s [LOG] Action snapToCenter is in universe Game
1526.058s [LOG] Action copy is in universe All
1526.058s [LOG] Action paste is in universe All
1526.058s [LOG] Action context is in universe All
1526.058s [LOG] Action pause is in universe All
1526.058s [LOG] Action toybox is in universe All
1526.058s [LOG] Action toolPowerToggle is in universe Game
1526.058s [LOG] Action pan is in universe All
1526.058s [LOG] Action panRight is in universe All
1526.058s [LOG] Action panLeft is in universe All
1526.058s [LOG] Action panUp is in universe All
1526.058s [LOG] Action panDown is in universe All
1526.058s [LOG] Action zoomIn is in universe All
1526.058s [LOG] Action zoomOut is in universe All
1526.058s [LOG] Action flipSelectedObjects-zooi is in universe Game
1526.058s [LOG] {
  "DropOnDeath": true,
  "LimbCrushing": true,
  "LimbOverflowExplosion": true,
  "TracerBullets": true,
  "FancyEffects": true,
  "ExpandedGore": false,
  "Decals": true,
  "ClampVolume": true,
  "ShowOutlines": true,
  "LogDebugMessages": false,
  "ShowFramerate": true,
  "Lighting": true,
  "VSync": false,
  "SMAA": true,
  "ZoomSensitivity": 1.0,
  "MasterVolume": 1.0,
  "SfxVolume": 1.0,
  "UserInterfaceVolume": 1.0,
  "AmbienceVolume": 1.0,
  "ShakeIntensity": 1.0,
  "SlowMotionSpeed": 20.0,
  "CrushForceMultiplier": 1.0,
  "DeleteWireByContextMenu": true,
  "SimplifiedBackground": false,
  "AmbientTemperatureTransfer": true,
  "TemperatureUnit": 0,
  "WindowMode": 1,
  "CollisionQuality": 1,
  "TonemappingMode": 0,
  "BloomMode": 2,
  "Brightness": 100.0,
  "PhysicsIterations": 128,
  "RenderScale": 1.0,
  "FramerateLimit": 144,
  "Resolution": {
    "x": 1920,
    "y": 1080,
    "magnitude": 2202.90723,
    "sqrMagnitude": 4852800
  },
  "ShowTutorial": false,
  "ShowModLoadingFreeze": true,
  "RejectShadyCode": true
}
```

**Comment by mestiez** [comment]
Unsure if this counts as a bug?

**Comment by Tye-Evans2** [comment]
> Unsure if this counts as a bug?

It should be. So far as I know humans that are brain dead die, fully

**Comment by xpdatabase11** [comment]
Not true, there have been many cases where people's body's still worked while the brain was dead.
