### ISSUE TITLE
Not sure if bug or feature

### ISSUE THREAD

**Issue by malbs** [studio-minus/ppg-bugs-and-requests#956]
basically, you cannot create a endless cycle of electric signals.
video of what I mean:
https://user-images.githubusercontent.com/102204615/159625951-6d82376e-e392-4938-ae14-56a90c2ae5e9.mp4

im not sure if this may have been intentional to prevent too many electric signals from occurring at once, but it prevents me from making loops with electric signals that I need to use for my contraptions. the version currently is 1.22.3

-malbs

**Comment by vda8** [comment]
Have you heard of metranomes?

**Comment by vda8** [comment]
Also you should follow the template.

**Comment by DindinYT37** [comment]
> Have you heard of metranomes?

*Metronomes
But yes, also this was made to avoid infinite loops, which would just eat all of your processing power.
