### ISSUE TITLE
CPR 

### ISSUE THREAD

**Issue by ppgplayer** [studio-minus/ppg-bugs-and-requests#958]
**Feature description**
A way of reviving humans roughly a minute after death. If a reasonable amount of pressure is applied to the heart area the human will start gaining blood pressure slowly if the damage sustained to the human is not too great. Useful for a drowned human and ultimately good for those who like roleplay.

**Feature purpose**
The purpose is to have a new way of reviving humans.

**Additional context**
![image](https://user-images.githubusercontent.com/98086053/159654847-ec10c4aa-99cf-4d36-b2cf-4b4cbdf017c8.png)

**Comment by WWWOWWWPL** [comment]
doesn't electricity achieve a similar effect? this could have been removed, but from what i remember you can apply some electric current to a dead human and it sometimes gets them back up

**Comment by Cboyjet4** [comment]
really pointless due to how the system works

**Comment by UniDuki** [comment]
> doesn't electricity achieve a similar effect...
Yes. That's the whole point of the defibrillator.

**Comment by bluewoods64** [comment]
i dont think this would work well

**Comment by ppgplayer** [comment]
> doesn't electricity achieve a similar effect? this could have been removed, but from what i remember you can apply some electric current to a dead human and it sometimes gets them back up

Yes, but it's a NEW way. What's the point of a defib if you have a life syringe then?

**Comment by ppgplayer** [comment]
> really pointless due to how the system works

Elaborate.

**Comment by ppgplayer** [comment]
> > doesn't electricity achieve a similar effect...
> 
> Yes. That's the whole point of the defibrillator.

No comment, only facts from this guy.

**Comment by ppgplayer** [comment]
> i dont think this would work well

Elaborate.

**Comment by ppgplayer** [comment]
It seems like your guys' reasons are just "It won't work because I said so" or "There is another system that exists and has nothing to do with this suggestion".

**Comment by DeckerExpert** [comment]
> > doesn't electricity achieve a similar effect? this could have been removed, but from what i remember you can apply some electric current to a dead human and it sometimes gets them back up
> 
> Yes, but it's a NEW way. What's the point of a defib if you have a life syringe then?

i know its been like nearly a whole month since this been closed, but with your logic, whats the point in CPR when you have a life syringe?

**Comment by DindinYT37** [comment]
> > > doesn't electricity achieve a similar effect? this could have been removed, but from what i remember you can apply some electric current to a dead human and it sometimes gets them back up
> > 
> > Yes, but it's a NEW way. What's the point of a defib if you have a life syringe then?
> 
> i know its been like nearly a whole month since this been closed, but with your logic, whats the point in CPR when you have a life syringe?

Not "restoring" or grilling a human when saving him, also it's a way of saving a human without any external objects.
