### ISSUE TITLE
30mm cannon recoil pushing objects behind cannon

### ISSUE THREAD

**Issue by Afavertov** [studio-minus/ppg-bugs-and-requests#961]
30mm cannon recoil pushing objects behind cannon

Spawn random object behing 30mm cannon and fire.

No

 - Operating system: Win 10
 - Game version: 1.23 beta, preview 15
 - GPU: 750 ti
 - CPU: Intel Core i5-4590 3.30GHz

https://www.youtube.com/watch?v=H5deqxxHXOI

**Comment by DindinYT37** [comment]
Also, I'm pretty sure it's supposed to do that as in the description it says it has no barrel.

**Comment by WWWOWWWPL** [comment]
big guns always had a 'shockwave' effect that pushed away objects near them when firing. that feature has been amplified in the newest preview so it's more noticeable

**Comment by vda8** [comment]
Not a bug. Just the gasses from the barrel.
