### ISSUE TITLE
rewind feature / change default binding of switch tools & powers

### ISSUE THREAD

**Issue by NotDansk** [studio-minus/ppg-bugs-and-requests#962]
far too many times (once) i've fatfingered left ctrl and destroyed a destructible building i was almost finished with because pull was selected instead of drag.

**Comment by DindinYT37** [comment]
You know I think you can change the keybinds in the settings.

**Comment by vda8** [comment]
Two suggestions in one. One of them is already in the game. The other, well I'm sure zooi won't add that.

**Comment by vda8** [comment]
Also. Could you follow the template please?
