### ISSUE TITLE
Moving bush glitch

### ISSUE THREAD

**Issue by xplodous** [studio-minus/ppg-bugs-and-requests#964]
**Describe the bug**
Moving a bush while paused causes the bush to attempt to travel towards where it was moved frame when unpaused

**Clearly describe how to reproduce the bug**
1 spawn a bush
2 pause
3 select the entire bush
4 move the bush, preferably very far away
5 unpause

**Mod list**
Include a list of your mods here and specifiy whether they're activated or not. Make sure to include deactivated mods, as they could still have an effect.
Time accelerator

**Additional notes**
kind of fun

**Comment by vda8** [comment]
This is really unclear

**Comment by DindinYT37** [comment]
That's because the particles (I guess) are dynamic and **not** statically bound to their emitters.

**Comment by mestiez** [comment]
fixed
