### ISSUE TITLE
Liquid Explosive

### ISSUE THREAD

**Issue by Whelchur** [studio-minus/ppg-bugs-and-requests#966]
**Feature description**
Add an explosive that stores liquids and spread liquids when explode.

**Feature purpose**
For fun

**Additional context**
none

**Comment by vda8** [comment]
Bottle with a bit of nitroglycerin?

**Comment by ppgplayer** [comment]
> Bottle with a bit of nitroglycerin?

No. Doesn't accomplish the idea of the suggestion.

**Comment by DindinYT37** [comment]
> > Bottle with a bit of nitroglycerin?
> 
> No. Doesn't accomplish the idea of the suggestion.

Should be added as sub-feature for nitroglycerin instead of a whole new feature then.

**Comment by vda8** [comment]
> > Bottle with a bit of nitroglycerin?
> 
> No. Doesn't accomplish the idea of the suggestion.
You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.

**Comment by ppgplayer** [comment]
> > > Bottle with a bit of nitroglycerin?
> > 
> > 
> > No. Doesn't accomplish the idea of the suggestion.
> 
> You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.

What about a widespread area? So far you have done everything possible to make suggestions not happen with bad solutions.

**Comment by vda8** [comment]
> > > > Bottle with a bit of nitroglycerin?
> > > 
> > > 
> > > No. Doesn't accomplish the idea of the suggestion.
> > 
> > You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.
> 
> What about a widespread area? So far you have done everything possible to make suggestions not happen with bad solutions.

In a wide area then it would be great to have this not gonna lie. But if you don't need that, you can just do the bottle thing.

**Comment by ppgplayer** [comment]
> > > > > Bottle with a bit of nitroglycerin?
> > > > 
> > > > 
> > > > No. Doesn't accomplish the idea of the suggestion.
> > > 
> > > 
> > > You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.
> > 
> > 
> > What about a widespread area? So far you have done everything possible to make suggestions not happen with bad solutions.
> 
> In a wide area then it would be great to have this not gonna lie. But if you don't need that, you can just do the bottle thing.

There, that was probably the purpose of the suggestion. The only time somebody wants a tiny explosion in PPG of all places is making guns.

**Comment by Whelchur** [comment]
i mean it for a large area

**Comment by vda8** [comment]
> i mean it for a large area
> 

Yeah then for that i would be a great thing to have. You could make a better Molotov this way.

**Comment by vda8** [comment]
> > > > > > Bottle with a bit of nitroglycerin?
> > > > > 
> > > > > 
> > > > > No. Doesn't accomplish the idea of the suggestion.
> > > > 
> > > > 
> > > > You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.
> > > 
> > > 
> > > What about a widespread area? So far you have done everything possible to make suggestions not happen with bad solutions.
> > 
> > In a wide area then it would be great to have this not gonna lie. But if you don't need that, you can just do the bottle thing.
> 
> There, that was probably the purpose of the suggestion. The only time somebody wants a tiny explosion in PPG of all places is making guns.

When you make guns you would usually need a big explosion to make the projectile go. It also useful for other things.

**Comment by ppgplayer** [comment]
> > > > > > > Bottle with a bit of nitroglycerin?
> > > > > > 
> > > > > > 
> > > > > > No. Doesn't accomplish the idea of the suggestion.
> > > > > 
> > > > > 
> > > > > You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.
> > > > 
> > > > 
> > > > What about a widespread area? So far you have done everything possible to make suggestions not happen with bad solutions.
> > > 
> > > 
> > > In a wide area then it would be great to have this not gonna lie. But if you don't need that, you can just do the bottle thing.
> > 
> > 
> > There, that was probably the purpose of the suggestion. The only time somebody wants a tiny explosion in PPG of all places is making guns.
> 
> When you make guns you would usually need a big explosion to make the projectile go. It also useful for other things.

If you have ever made a PPG weapon with explosives you would know that frags are too weak and dynamite is too powerful.

**Comment by DindinYT37** [comment]
> > > > > > > > Bottle with a bit of nitroglycerin?
> > > > > > > 
> > > > > > > 
> > > > > > > No. Doesn't accomplish the idea of the suggestion.
> > > > > > 
> > > > > > 
> > > > > > You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.
> > > > > 
> > > > > 
> > > > > What about a widespread area? So far you have done everything possible to make suggestions not happen with bad solutions.
> > > > 
> > > > 
> > > > In a wide area then it would be great to have this not gonna lie. But if you don't need that, you can just do the bottle thing.
> > > 
> > > 
> > > There, that was probably the purpose of the suggestion. The only time somebody wants a tiny explosion in PPG of all places is making guns.
> > 
> > 
> > When you make guns you would usually need a big explosion to make the projectile go. It also useful for other things.
> 
> If you have ever made a PPG weapon with explosives you would know that frags are too weak and dynamite is too powerful.

Which is why things like #608 or #888 get suggested.

**Comment by ppgplayer** [comment]
> > > > > > > > > Bottle with a bit of nitroglycerin?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > No. Doesn't accomplish the idea of the suggestion.
> > > > > > > 
> > > > > > > 
> > > > > > > You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.
> > > > > > 
> > > > > > 
> > > > > > What about a widespread area? So far you have done everything possible to make suggestions not happen with bad solutions.
> > > > > 
> > > > > 
> > > > > In a wide area then it would be great to have this not gonna lie. But if you don't need that, you can just do the bottle thing.
> > > > 
> > > > 
> > > > There, that was probably the purpose of the suggestion. The only time somebody wants a tiny explosion in PPG of all places is making guns.
> > > 
> > > 
> > > When you make guns you would usually need a big explosion to make the projectile go. It also useful for other things.
> > 
> > 
> > If you have ever made a PPG weapon with explosives you would know that frags are too weak and dynamite is too powerful.
> 
> Which is why things like #608 or #888 get suggested.

Idk bro I think you're a bit of an arsehole now.

**Comment by DindinYT37** [comment]
> > > > > > > > > > Bottle with a bit of nitroglycerin?
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > No. Doesn't accomplish the idea of the suggestion.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.
> > > > > > > 
> > > > > > > 
> > > > > > > What about a widespread area? So far you have done everything possible to make suggestions not happen with bad solutions.
> > > > > > 
> > > > > > 
> > > > > > In a wide area then it would be great to have this not gonna lie. But if you don't need that, you can just do the bottle thing.
> > > > > 
> > > > > 
> > > > > There, that was probably the purpose of the suggestion. The only time somebody wants a tiny explosion in PPG of all places is making guns.
> > > > 
> > > > 
> > > > When you make guns you would usually need a big explosion to make the projectile go. It also useful for other things.
> > > 
> > > 
> > > If you have ever made a PPG weapon with explosives you would know that frags are too weak and dynamite is too powerful.
> > 
> > 
> > Which is why things like #608 or #888 get suggested.
> 
> Idk bro I think you're a bit of an arsehole now.

He insulted me, I trolled him in return. Stupid things need to expect stupid answers.

**Comment by ppgplayer** [comment]
> > > > > > > > > > > Bottle with a bit of nitroglycerin?
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > No. Doesn't accomplish the idea of the suggestion.
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > You can just put a tiny bit of nitroglycerin for an explosion effect, and then whatever liquid you want. When it breaks near someone, the effect of the liquid gets applied to the human. You don't need nitroglycerin, it just makes a weak explosion when it breaks.
> > > > > > > > 
> > > > > > > > 
> > > > > > > > What about a widespread area? So far you have done everything possible to make suggestions not happen with bad solutions.
> > > > > > > 
> > > > > > > 
> > > > > > > In a wide area then it would be great to have this not gonna lie. But if you don't need that, you can just do the bottle thing.
> > > > > > 
> > > > > > 
> > > > > > There, that was probably the purpose of the suggestion. The only time somebody wants a tiny explosion in PPG of all places is making guns.
> > > > > 
> > > > > 
> > > > > When you make guns you would usually need a big explosion to make the projectile go. It also useful for other things.
> > > > 
> > > > 
> > > > If you have ever made a PPG weapon with explosives you would know that frags are too weak and dynamite is too powerful.
> > > 
> > > 
> > > Which is why things like #608 or #888 get suggested.
> > 
> > 
> > Idk bro I think you're a bit of an arsehole now.
> 
> He insulted me, I trolled him in return. Stupid things need to expect stupid answers.

That wasn't a troll I think you are taking this place too seriously. Let zooi handle it if he doesn't like them, after all he can just reject them since he looks at them anyway.

**Comment by DindinYT37** [comment]
> > > Idk bro I think you're a bit of an arsehole now.
> > 
> > 
> > He insulted me, I trolled him in return. Stupid things need to expect stupid answers.
> 
> That wasn't a troll I think you are taking this place too seriously. Let zooi handle it if he doesn't like them, after all he can just reject them since he looks at them anyway.

That... was a troll though? Also this issue is kinda flooded with all the quotes it has.

**Comment by 404CoderNotFound** [comment]
> **Feature description** Add an explosive that stores liquids and spread liquids when explode.
> 
> **Feature purpose** For fun
> 
> **Additional context** none

Use the new 1.23 bottles. They're easy to break and release all the liquids inside of them.

**Comment by DindinYT37** [comment]
> > **Feature description** Add an explosive that stores liquids and spread liquids when explode.
> > **Feature purpose** For fun
> > **Additional context** none
> 
> Use the new 1.23 bottles. They're easy to break and release all the liquids inside of them.

So how does this solve the problem?

**Comment by 5hart** [comment]
Wouldn't syringes that explode into the air have the same effect? Like when you shoot a syringe and the liquid bursts out like a gas.
