### ISSUE TITLE
Boat screw

### ISSUE THREAD

**Issue by ppgplayer** [studio-minus/ppg-bugs-and-requests#967]
**Feature description**
A motor that only provides thrust when submerged. Small but power scales depending on electricity.

**Feature purpose**
Useful for boats and people who don't want to accidentally make an aircraft out of a speedboat.

**Comment by ppgplayer** [comment]
Assuming I will get flooded with such people, good luck to any brave soldier that strays into this comment section.

**Comment by vda8** [comment]
You should call this a boat screw instead. Its more accurate. It's a really good suggestion tho, take my thumbs up.

**Comment by ppgplayer** [comment]
Despite people unanimously agreeing that there is no problem with this suggestion, UniDuki still dislikes it for some reason.

**Comment by DindinYT37** [comment]
> Despite people unanimously agreeing that there is no problem with this suggestion, UniDuki still dislikes it for some reason.

Classic UniDuki moment

**Comment by UniDuki** [comment]
Because I think a motor that only works underwater doesn't make any sense and is basically useless.

**Comment by DindinYT37** [comment]
> Because I think a motor that only works underwater doesn't make any sense and is basically useless.

How would you build a boat that doesn't suddenly turn into an aircraft then?

**Comment by WWWOWWWPL** [comment]
> How would you build a boat that doesn't suddenly turn into an aircraft then?

uh, i'd make the propeller weaker or add some weight to the boat

**Comment by vda8** [comment]
> > How would you build a boat that doesn't suddenly turn into an aircraft then?
> 
> uh, i'd make the propeller weaker or add some weight to the boat

Shut up, this is a good suggestion. Go and tweet some racial slur instead.
