### ISSUE TITLE
Items that can collect, store, and process numeric data.

### ISSUE THREAD

**Issue by Sirblockhead1** [studio-minus/ppg-bugs-and-requests#973]
**Feature description**
Something People Playground has needed for a long time is an item that can take numeric data from things, and another item that can perform math with it. 

What I am requesting is three items.
An item that can collect and store data from various sources (of which I will provide examples)
An item that can use the data to perform calculations
And a one-way wire that will be the medium through which the data is passed through these objects.

**Feature purpose**
Regarding the item that can collect data, we have items already that can take numeric data from other items, (Heart Monitor, Thermometers, the Power Gauge, etc.) however, these are purely for display and you cannot do anything meaningful with these.  Along with being able to store Temperature Data, Electricity Data, etc, a couple of other (far more important) interactions I think would be the key to making this thing very useful are to be able to find the angle of something, either of itself or something it is connected to, and to be able to find the distance of something whilst connected to a laser/detector. 

All of this data will be stored in the item in the form of a number. However, as I said, most of the data-collecting items are purely for display. However, I propose that there be another item that would be able to do math with the data it receives from the data-collecting item, and send an activation signal when a specified outcome happens. A calculator, if you will. For example:

You could set it to send an activation signal when the data collected is greater than 40.
You could set it to send an activation signal when the data collected is less than 35.
You could set it to send an activation signal when the data collected is equal to 90.
You could set it to send an activation signal when the data collected is not equal to 75.
You could set it to send an activation signal when the data collected is greater than or equal to 400.
You could set it to send an activation signal when the data collected is less than or equal to 80.

( [Greater than or equal to], [Less than or equal to], [Greater than], [Less than], [Equal To], [Not Equal To] )

These examples are examples that will send out an activation signal. However, not all calculations will. Some other calculations would be for Multiplication, Division, Addition, and Subtraction. The number to divide/multiply/etc by will be specified in the context menu. 

As I said, these will not output a true or false result, but instead another numeric value, which you will then send to another "calculator" to decide what the output condition should be.

Basically in summary:
-A data collector item gets numeric data from another item
-Through a wire in which the number can be sent, it reaches a calculation device.
-The calculation device can be set to perform an operation, or simply submit an output.
-If it is set to perform an operation, it will do what is set by the player with the data received, and you will have to send the output of the operation to another calculation device.
-This calculation device will determine the output, either true or false (to send an activation signal or not).

--Another special interaction I thought would be very helpful had to do with the radio, and the phase links. To start things off (And this sounds weird at first, but I promise I will explain), the phase links should be able to link the frequency values of the radio. Basically, when two radios are linked together when one changes frequency, the other changes.
The reason for this is, I propose that when you send numeric data from a data collector/calculator to a radio (via the one-way data transmitter wire), the radio changes its frequency to the number being sent to it. If you link two radios together, this will change the frequency of a radio that doesn't have to be connected physically to the data transmitter wire. You can, in turn, use a collector/calculator to take the data from the radio and use it for whatever you need to do.
(All of this should be automatic with the data transmission wire, and shouldn't require the use of activation signals to send data from the radio to the collector, or vice versa. I will explain why in the additional context section.)

Essentially, all this is to create a form of sending data wirelessly, as prior to this, the only data you could send through the radio is an activation signal. No other data can be acquired, and the radio frequency serves only to separate one radio channel from the next.

**Additional context**
This is a lot to ask for, I'm sure. However, I ask that you take it into consideration as it would change the way players create complex contraptions in their entirety.

All of these interactions should be done without the use of activation signals. Basically, until the output of the calculator sends an activation signal out when it reaches a proper outcome, you should not need to activate them (for example) radio in order to send data from itself to the collector. You also shouldn't need to activate the collector to send data from the collector to the calculator. All of that should be done automatically with the data transmitter to provide instantaneous feedback (And also prevents a massive issue from being started if the radio frequency is changed to something another channel is using as its frequency).

The data collector item could be entirely phased out, as its role can be taken up by the calculator item itself. However, I thought that would have made far too many options in the context menu than the calculator already would have had, so I will let you make that decision.

The type of operation the calculator performs should be specified in the context menu. (Subtraction, Addition, etc.) As well as the output condition (Greater Than, Equal To, etc.), as well as (as previously mentioned) the number that the data will perform the operation with. 

Edit: Another interaction I think would be very helpful is to be able to set the target angle of a Servo when it receives data from a calculator.

The rate at which data is sent could also be specified in the settings, just as you can adjust the thermal vision update rate.

**Comment by DindinYT37** [comment]
I'd say mame your own binary version using gates and use a BCD but this is probably better for the not-so-technical people.

**Comment by Sirblockhead1** [comment]
> 

Exactly my thought going into this. I have tried using that mod, but it ends up with you using way too many items for a single adder that it's not even worth it. This would allow for so much more to be done so easily.

**Comment by Sirblockhead1** [comment]
> I'd say make your own binary version using gates and use a BCD but this is probably better for the not-so-technical people.

There exists a mod (created by zooi himself I believe) that lets you use logic gates, however I don't think that entirely solves it. You still cannot receive data from the objects, and instead can only make a counter. Not to mention the fact that just a single counter requires a handful or more logic gates.

**Comment by DindinYT37** [comment]
> > I'd say make your own binary version using gates and use a BCD but this is probably better for the not-so-technical people.
> 
> There exists a mod (created by zooi himself I believe) that lets you use logic gates, however I don't think that entirely solves it. You still cannot receive data from the objects, and instead can only make a counter. Not to mention the fact that just a single counter requires a handful or more logic gates.

You can use a single radio to transmit a series of binary inputs, if you build the corresponding decoder. And like I said, "this is probably better for the not-so-technical people."

**Comment by Sirblockhead1** [comment]
> > > I'd say make your own binary version using gates and use a BCD but this is probably better for the not-so-technical people.
> > 
> > 
> > There exists a mod (created by zooi himself I believe) that lets you use logic gates, however I don't think that entirely solves it. You still cannot receive data from the objects, and instead can only make a counter. Not to mention the fact that just a single counter requires a handful or more logic gates.
> 
> You can use a single radio to transmit a series of binary inputs, if you build the corresponding decoder. And like I said, "this is probably better for the not-so-technical people."

That and, while that sounds like a really cool contraption in and of itself, it doesn't solve the real thing of not being able to get tangible numeric data from objects to transmit in the first place.

**Comment by ppgplayer** [comment]
my brain hurts

**Comment by mestiez** [comment]
This has been requested lots of times but PPG just isn't the kind of game for this stuff.
