### ISSUE TITLE
The Cooler Activation Signal.

### ISSUE THREAD

**Issue by wordpass1** [studio-minus/ppg-bugs-and-requests#983]
**Feature description**
A signal that will turn items on when toggled on, But when destroyed. It will act as if it had been toggled again. Turning off. Basically the cooler activation toggle.

**Feature purpose**
When an appliance is hooked directly to the epic activation signal, it will function as normal, Unless destroyed, In which it will be turned off, Since the power is cut like how every other generator SHOULD work. This could be used to make weak spots on mechs that shut down parts of the mech when destroyed.

**Additional context**
![ndemonstration](https://user-images.githubusercontent.com/102382867/160216284-7053214f-2a0e-45f3-8287-6c280e29f0ff.PNG)
(Demonstration of what happens when you shoot it.)

**Comment by 404CoderNotFound** [comment]
.... first of all this is extremely confusing, second of all this is just a normal activation wire....

**Comment by wordpass1** [comment]
none of you even read it. i'm calling it

**Comment by wordpass1** [comment]
If you spawn an activation toggle RIGHT NOW. and then destroy it. Whatever was toggle by it will STAY ON. If you FUCKING READ IT, YOU WOULD KNOW, THIS FIXES THAT.

**Comment by wordpass1** [comment]
why even link the suggestion fourm if you don't care about them

**Comment by DindinYT37** [comment]
To sum it up for people that don't understand, it works like a normal activation signal, but it also sends a signal when destroyed.
