### ISSUE TITLE
A simple gas dynamics system

### ISSUE THREAD

**Issue by RetroCorruption** [studio-minus/ppg-bugs-and-requests#995]
**Feature description**
A simple gas dynamics system.  Example, in a map such as substructure, you could fill the vents with flammable gas and the gas would travel through then you could make it a large fireball, or you could explode a barrel in the vents and the fireball would travel through them like it would in real life

**Feature purpose**
you could do a lot with a gas dynamics system, for example, unique machinery, steam engines, large firearms

**Comment by DindinYT37** [comment]
I think this would be similar to water physics, so the first thing is likely not to be added but the explosion/gas travelling through a closed room is something that could be added. I'd like to see both though.

**Comment by wordpass1** [comment]
Could just be pre-coded for specific areas. Like using a flamethrower in the vents could ignite the entire system. But as this is a sandbox game, Thats probably a bad idea.

**Comment by wordpass1** [comment]
Good suggestion, But too hard to code.

**Comment by mestiez** [comment]
Gas is more forgiving than liquids because they can be rendered all blurry and vague, and they don't have to move as fast
